DROP TABLE if EXISTS {costco_tblname1};

CREATE TABLE {costco_tblname1} (
ACCOUNT_IPK varchar(11) ENCODE zstd,
MEMBERSHIP_IPK varchar(11) ENCODE zstd,
POSTAL_IPK varchar(11) ENCODE zstd,
FirstName varchar(16) ENCODE zstd,
MiddleName varchar(1) ENCODE zstd,
LastName varchar(30) ENCODE zstd,
CLIENT_KEYCODE varchar(1) ENCODE zstd,
AddressLine1 varchar(40) ENCODE zstd,
AddressUnit varchar(13) ENCODE zstd,
AddressLine2 varchar(40) ENCODE zstd,
City varchar(13) ENCODE zstd,
State varchar(2) ENCODE zstd,
ZIP varchar(5) ENCODE zstd,
ZIP4 varchar(4) ENCODE zstd,
Individual_Id_Varchar varchar(12) ENCODE zstd,
CE_HOUSEHOLD_ID varchar(12) ENCODE zstd,
CE_LOCATION_ID varchar(23) ENCODE zstd,
CE_OWN_RENT_CODE varchar(1) ENCODE zstd,
ADDTYPE varchar(8) ENCODE zstd,
Lems varchar(18) ENCODE zstd,
CE_Match_Level varchar(7) ENCODE zstd,
CE_Match_Score varchar(3) ENCODE zstd,
CE_Matched_Indicator varchar(1) ENCODE zstd,
CE_Household_Status_Code varchar(1) ENCODE zstd,
CE_Household_Head_Age_Code varchar(1) ENCODE zstd,
CE_Selected_Age varchar(3) ENCODE bytedict,
CE_Selected_Individual_YYYYMM_Of_Birth varchar(6) ENCODE zstd,
CE_Selected_Individual_DD_Of_Birth varchar(2) ENCODE zstd,
CE_Selected_Individual_Marital_Status_Code varchar(1) ENCODE zstd,
CE_Selected_Title_Code varchar(1) ENCODE zstd,
CE_Selected_Gender varchar(1) ENCODE zstd,
CE_Selected_Individual_Vendor_Ethnicity_Code varchar(2) ENCODE zstd,
CE_Selected_Individual_Vendor_Ethnic_Group_Code varchar(1) ENCODE zstd,
CE_Selected_Individual_Vendor_Spoken_Language_Code varchar(2) ENCODE zstd,
CE_Selected_Individual_Vendor_Religion_Code varchar(1) ENCODE zstd,
CE_FindIncome varchar(6) ENCODE bytedict,
CE_Costco_Membership_Number varchar(12) ENCODE zstd,
CE_DBI_FILLER varchar(12) ENCODE zstd,
CE_Specialty_Organic_Food_Store_Model varchar(1) ENCODE zstd,
CE_Wholesale_Club_Model varchar(1) ENCODE zstd,
CE_Organic_Food_Model varchar(1) ENCODE zstd,
CE_Heavy_Coupon_User_Model varchar(1) ENCODE zstd,
CE_Cruise_Model varchar(1) ENCODE zstd,
CE_Heavy_Domestic_Travelers_Model varchar(1) ENCODE zstd,
CE_High_End_Electronic_Model varchar(1) ENCODE zstd,
CE_Cook_For_Fun_Model varchar(1) ENCODE zstd,
CE_Cook_From_Scratch_Model varchar(1) ENCODE zstd,
CE_Heavy_Snack_Eaters_Model varchar(1) ENCODE zstd,
CE_Baby_Product_Model varchar(1) ENCODE zstd,
CE_Heavy_Online_Buyer_Model varchar(1) ENCODE zstd,
CE_Green_Model varchar(1) ENCODE zstd,
CE_Diet_Product_Model varchar(1) ENCODE zstd,
CE_Foreign_Travel_Vacation_Model varchar(1) ENCODE zstd,
CE_Garden_Maintenance_Model varchar(1) ENCODE zstd,
CE_Heavy_Vitamin_Model varchar(1) ENCODE zstd,
CE_Home_Improvement_Model varchar(1) ENCODE zstd,
CE_Impulse_Buyer_Model varchar(1) ENCODE zstd,
CE_Life_Insurance_Model varchar(1) ENCODE zstd,
CE_Shopaholics_Model varchar(1) ENCODE zstd,
CE_Luxury_Hotel_Model varchar(1) ENCODE zstd,
CE_Rental_Car_Model varchar(1) ENCODE zstd,
CE_Outdoor_Activities_Model varchar(1) ENCODE zstd,
CE_Frozen_Dinner_Model varchar(1) ENCODE zstd,
CE_Home_Office_Model varchar(1) ENCODE zstd,
CE_Health_Insurance_Model varchar(1) ENCODE zstd,
CE_High_End_Apparel_Model varchar(1) ENCODE zstd,
CE_Gift_Buyers_Model varchar(1) ENCODE zstd,
filler2 varchar(1) ENCODE zstd,
ID bigint IDENTITY UNIQUE distkey sortkey ENCODE delta,
ListID int ENCODE az64,
PermissionType char(1) ENCODE zstd,
Gender char(1) ENCODE zstd,
ListType char(1) ENCODE zstd,
ProductCode char(1) ENCODE zstd,
individual_id bigint ENCODE zstd,
ZipFull Varchar(10) ENCODE zstd,
FullName Varchar(60) ENCODE zstd,
Has_Zip4 Char(1) ENCODE zstd,
Company_ID bigint ENCODE az64,
SCF Varchar(3) ENCODE zstd
);








