DROP TABLE IF EXISTS nosuchtable;
DROP TABLE IF EXISTS {maintable_name} CASCADE;

-- ALTER TABLE IG_CONSUMER_NEW_TEMP RENAME TO ;

CREATE TABLE {maintable_name} (
    id BIGINT IDENTITY PRIMARY KEY DISTKEY SORTKEY ENCODE AZ64,
    listid INTEGER ENCODE AZ64,
    permissiontype CHARACTER VARYING(1) ENCODE ZSTD,
    zipradius CHARACTER VARYING(1) ENCODE ZSTD,
    georadius CHARACTER VARYING(1) ENCODE ZSTD,
    firstname CHARACTER VARYING(25) ENCODE ZSTD,
    middleinitial CHARACTER VARYING(1) ENCODE ZSTD,
    lastname CHARACTER VARYING(30) ENCODE ZSTD,
    last_name_suffix CHARACTER VARYING(3) ENCODE ZSTD,
    title_code CHARACTER VARYING(1) ENCODE ZSTD,
    gender CHARACTER VARYING(1) ENCODE ZSTD,
    house_number CHARACTER VARYING(10) ENCODE ZSTD,
    street_pre_directional CHARACTER VARYING(2) ENCODE ZSTD,
    street_name CHARACTER VARYING(28) ENCODE ZSTD,
    street_suffix CHARACTER VARYING(4) ENCODE ZSTD,
    street_post_directional CHARACTER VARYING(2) ENCODE ZSTD,
    unit_type CHARACTER VARYING(4) ENCODE ZSTD,
    unit_number CHARACTER VARYING(8) ENCODE ZSTD,
    city CHARACTER VARYING(28) ENCODE ZSTD,
    state CHARACTER VARYING(2) ENCODE ZSTD,
    census_state_code_2010 CHARACTER VARYING(2) ENCODE ZSTD,
    county_code CHARACTER VARYING(3) ENCODE ZSTD,
    zip CHARACTER VARYING(5) ENCODE ZSTD,
    zip_four CHARACTER VARYING(4) ENCODE ZSTD,
    carrier_route_code CHARACTER VARYING(4) ENCODE BYTEDICT,
    delivery_point_bar_code CHARACTER VARYING(3) ENCODE ZSTD,
    area_code CHARACTER VARYING(3) ENCODE ZSTD,
    nielsen_county_rank CHARACTER VARYING(1) ENCODE ZSTD,
    time_zone CHARACTER VARYING(1) ENCODE ZSTD,
    age_code CHARACTER VARYING(1) ENCODE ZSTD,
    birth_date CHARACTER VARYING(8) ENCODE ZSTD,
    income CHARACTER VARYING(1) ENCODE ZSTD,
    last_contribution_date CHARACTER VARYING(8) ENCODE ZSTD,
    length_of_residence CHARACTER VARYING(2) ENCODE BYTEDICT,
    residence_type CHARACTER VARYING(1) ENCODE ZSTD,
    delivery_unit_size_raw CHARACTER VARYING(1) ENCODE ZSTD,
    own_rent_indicator CHARACTER VARYING(1) ENCODE ZSTD,
    location_type CHARACTER VARYING(1) ENCODE ZSTD,
    pool_type CHARACTER VARYING(3) ENCODE ZSTD,
    home_value_code CHARACTER VARYING(1) ENCODE ZSTD,
    home_sale_date CHARACTER VARYING(8) ENCODE ZSTD,
    home_sale_price_code CHARACTER VARYING(1) ENCODE ZSTD,
    home_sale_price CHARACTER VARYING(20) ENCODE ZSTD,
    home_equity_estimate CHARACTER VARYING(1) ENCODE ZSTD,
    finance_type CHARACTER VARYING(1) ENCODE ZSTD,
    mortgage_loan_type CHARACTER VARYING(1) ENCODE ZSTD,
    boat_propulsion_code CHARACTER VARYING(1) ENCODE ZSTD,
    mortgage_amount CHARACTER VARYING(1) ENCODE ZSTD,
    congressional_district CHARACTER VARYING(2) ENCODE ZSTD,
    credit_card_code CHARACTER VARYING(22) ENCODE ZSTD,
    number_trade_lines CHARACTER VARYING(1) ENCODE ZSTD,
    marital_status CHARACTER VARYING(1) ENCODE ZSTD,
    spousal_indicator_raw CHARACTER VARYING(3) ENCODE ZSTD,
    cat_owner CHARACTER VARYING(3) ENCODE ZSTD,
    dog_owner CHARACTER VARYING(3) ENCODE ZSTD,
    grandparent_in_house CHARACTER VARYING(3) ENCODE ZSTD,
    veteran_flag CHARACTER VARYING(3) ENCODE ZSTD,
    stocks_or_bonds CHARACTER VARYING(3) ENCODE ZSTD,
    dm_high_tech_household CHARACTER VARYING(3) ENCODE ZSTD,
    female_occupation CHARACTER VARYING(2) ENCODE ZSTD,
    male_occupation CHARACTER VARYING(2) ENCODE ZSTD,
    census_average_years_attended_school_code CHARACTER VARYING(1) ENCODE ZSTD,
    census_phhblack_code CHARACTER VARYING(1) ENCODE ZSTD,
    census_of_population_graduated_college CHARACTER VARYING(1) ENCODE ZSTD,
    census_phhspnsh_code CHARACTER VARYING(1) ENCODE ZSTD,
    census_percent_of_population_married CHARACTER VARYING(1) ENCODE ZSTD,
    census_precent_of_population_single_parent CHARACTER VARYING(1) ENCODE ZSTD,
    expendable_income_rank CHARACTER VARYING(1) ENCODE ZSTD,
    loan_to_value_ratio_ltv CHARACTER VARYING(1) ENCODE ZSTD,
    donor_code CHARACTER VARYING(5) ENCODE ZSTD,
    mail_responsive_current CHARACTER VARYING(1) ENCODE ZSTD,
    mail_responsive_recent CHARACTER VARYING(1) ENCODE ZSTD,
    mail_responsive_ever CHARACTER VARYING(1) ENCODE ZSTD,
    census_tract_2010 CHARACTER VARYING(6) ENCODE ZSTD,
    census_block_group_2010 CHARACTER VARYING(1) ENCODE ZSTD,
    address_type CHARACTER VARYING(1) ENCODE ZSTD,
    hoh_head_of_household CHARACTER VARYING(3) ENCODE ZSTD,
    first_name_hoh CHARACTER VARYING(15) ENCODE ZSTD,
    middle_initial_hoh CHARACTER VARYING(1) ENCODE ZSTD,
    last_name_hoh CHARACTER VARYING(20) ENCODE ZSTD,
    last_name_suffix_hoh CHARACTER VARYING(3) ENCODE ZSTD,
    title_code_hoh CHARACTER VARYING(1) ENCODE ZSTD,
    gender_hoh CHARACTER VARYING(1) ENCODE ZSTD,
    birth_date_hoh CHARACTER VARYING(8) ENCODE ZSTD,
    individual_id_hoh BIGINT ENCODE AZ64,
    hoh_age_code CHARACTER VARYING(1) ENCODE ZSTD,
    number_trade_lines_hoh CHARACTER VARYING(1) ENCODE ZSTD,
    credit_card_code_hoh CHARACTER VARYING(10) ENCODE ZSTD,
    marital_status_hoh CHARACTER VARYING(1) ENCODE ZSTD,
    company_id CHARACTER VARYING(20) ENCODE ZSTD,
    individual_id CHARACTER VARYING(21) ENCODE ZSTD,
    location_id CHARACTER VARYING(12) ENCODE ZSTD,
    usps_delivery_service_type_code CHARACTER VARYING(1) ENCODE ZSTD,
    nielsen_county_region CHARACTER VARYING(1) ENCODE ZSTD,
    lot_size CHARACTER VARYING(7) ENCODE ZSTD,
    home_size CHARACTER VARYING(5) ENCODE ZSTD,
    home_age CHARACTER VARYING(3) ENCODE BYTEDICT,
    actual_age_flag CHARACTER VARYING(1) ENCODE ZSTD,
    political_contribution_amount CHARACTER VARYING(24) ENCODE ZSTD,
    pilot_license_code CHARACTER VARYING(1) ENCODE ZSTD,
    mortgage_interest_rates_old CHARACTER VARYING(4) ENCODE BYTEDICT,
    last_party_contributed_to CHARACTER VARYING(1) ENCODE ZSTD,
    aircraft_type_code CHARACTER VARYING(1) ENCODE ZSTD,
    boat_owner_indicator CHARACTER VARYING(3) ENCODE ZSTD,
    registered_voter CHARACTER VARYING(3) ENCODE ZSTD,
    political_party_affiliation CHARACTER VARYING(1) ENCODE ZSTD,
    number_of_adults_in_household CHARACTER VARYING(1) ENCODE ZSTD,
    household_member_count CHARACTER VARYING(1) ENCODE ZSTD,
    medag18p CHARACTER VARYING(4) ENCODE BYTEDICT,
    census_percent_of_population_with_3_households CHARACTER VARYING(1) ENCODE ZSTD,
    census_phhasian_code CHARACTER VARYING(1) ENCODE ZSTD,
    medhhd1 CHARACTER VARYING(9) ENCODE ZSTD,
    wealth_finder CHARACTER VARYING(1) ENCODE ZSTD,
    numberofchildren CHARACTER VARYING(1) ENCODE ZSTD,
    alternatehhind CHARACTER VARYING(1) ENCODE ZSTD,
    countryoforign CHARACTER VARYING(2) ENCODE ZSTD,
    donotmailflag CHARACTER VARYING(1) ENCODE ZSTD,
    emailpresenceflag CHARACTER VARYING(1) ENCODE ZSTD,
    routetype CHARACTER VARYING(1) ENCODE ZSTD,
    householdarrivaldate_year CHARACTER VARYING(4) ENCODE BYTEDICT,
    householdarrivaldate CHARACTER VARYING(6) ENCODE ZSTD,
    homeagesource CHARACTER VARYING(1) ENCODE ZSTD,
    homebuiltyear CHARACTER VARYING(4) ENCODE BYTEDICT,
    mortgagemonth CHARACTER VARYING(2) ENCODE ZSTD,
    homevaluesource CHARACTER VARYING(1) ENCODE ZSTD,
    actualincome CHARACTER VARYING(7) ENCODE BYTEDICT,
    infopersona_cluster CHARACTER VARYING(2) ENCODE BYTEDICT,
    infopersona_supercluster CHARACTER VARYING(1) ENCODE ZSTD,
    lifestyle CHARACTER VARYING(35) ENCODE ZSTD,
    listtype CHARACTER VARYING(2) ENCODE ZSTD,
    marriedscore CHARACTER VARYING(1) ENCODE ZSTD,
    medhhd2 CHARACTER VARYING(6) ENCODE ZSTD,
    mortgageloantype CHARACTER VARYING(1) ENCODE ZSTD,
    mortgageinterestsource CHARACTER VARYING(1) ENCODE ZSTD,
    occupancycount CHARACTER VARYING(2) ENCODE ZSTD,
    agedatasource CHARACTER VARYING(1) ENCODE ZSTD,
    presenceofchildren CHARACTER VARYING(1) ENCODE ZSTD,
    recencydate CHARACTER VARYING(6) ENCODE BYTEDICT,
    refreshdate CHARACTER VARYING(6) ENCODE BYTEDICT,
    scf CHARACTER VARYING(3) ENCODE ZSTD,
    vendorethnicity CHARACTER VARYING(2) ENCODE ZSTD,
    vendorethnicgroup CHARACTER VARYING(1) ENCODE ZSTD,
    vendorlanguage CHARACTER VARYING(2) ENCODE ZSTD,
    vendorreligion CHARACTER VARYING(1) ENCODE ZSTD,
    censuscountycode2010 CHARACTER VARYING(3) ENCODE ZSTD,
    fulfillmentflag CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender0 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender1 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender2 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender3 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender4 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender5 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender6 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender7 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender8 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender9 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender10 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender11 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender12 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender13 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender14 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender15 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender16 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbygender17 CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage0_5 CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage6_11 CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage12_17 CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage12_17female CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage12_17male CHARACTER VARYING(1) ENCODE ZSTD,
    children0_5 CHARACTER VARYING(1) ENCODE ZSTD,
    children6_11 CHARACTER VARYING(1) ENCODE ZSTD,
    children0_11 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth0 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth1 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth2 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth3 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth4 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth5 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth6 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth7 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth8 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth9 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth10 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth11 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth12 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth13 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth14 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth15 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth16 CHARACTER VARYING(1) ENCODE ZSTD,
    childrenbybirthmonth17 CHARACTER VARYING(1) ENCODE ZSTD,
    purchasing_power_income CHARACTER VARYING(1) ENCODE ZSTD,
    potential_investor_consumer CHARACTER VARYING(2) ENCODE ZSTD,
    sub_family_indicator CHARACTER VARYING(3) ENCODE ZSTD,
    number_of_contributions CHARACTER VARYING(3) ENCODE ZSTD,
    aircraft_mfg_year CHARACTER VARYING(4) ENCODE ZSTD,
    cbsa_code CHARACTER VARYING(5) ENCODE ZSTD,
    heavy_internet_user CHARACTER VARYING(2) ENCODE ZSTD,
    early_technology_adopter CHARACTER VARYING(2) ENCODE ZSTD,
    csa_code CHARACTER VARYING(3) ENCODE BYTEDICT,
    csa_code_description CHARACTER VARYING(50) ENCODE ZSTD,
    cbsa_level CHARACTER VARYING(1) ENCODE ZSTD,
    mail_confidence CHARACTER VARYING(2) ENCODE ZSTD,
    boat_hull_type CHARACTER VARYING(1) ENCODE ZSTD,
    boat_length CHARACTER VARYING(2) ENCODE ZSTD,
    flatitude double precision ENCODE raw,
    flongitude double precision ENCODE raw,
    vendor_matchcode CHARACTER VARYING(1) ENCODE ZSTD,
    do_not_call_flag CHARACTER VARYING(1) ENCODE ZSTD,
    has_primary_telephone CHARACTER VARYING(1) ENCODE ZSTD,
    addressline1 CHARACTER VARYING(40) ENCODE ZSTD,
    digitalmatch CHARACTER VARYING(1) ENCODE ZSTD,
    age CHARACTER VARYING(2) ENCODE BYTEDICT,
    mortgagedate CHARACTER VARYING(8) ENCODE ZSTD,
    loanamount CHARACTER VARYING(4) ENCODE ZSTD,
    lhi_african_american_ethnic_products CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_american_history CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_general_apparel CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_automotive CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_baseball CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_basketball CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_bible CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_birds CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_publish_books CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_business_items CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_cats CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_collectibles CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_college CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_computers CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_cooking CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_general_crafts CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_current_events CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_do_it_yourselfer CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_charitable_donor CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_personalized_products CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_horses CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_culture_arts CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_dogs CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_children_family CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_fishing CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_fitness_exercise CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_football CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_gardening CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_gambling CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_gift_giver CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_golf CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_general_health CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_hispanic_ethnic_products CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_hobbies CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_hockey CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_home_decorating CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_humor CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_hunting CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_inspirational CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_apparel_kids CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_apparel_mens CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_money_making CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_motorcycles CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_music CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_ocean CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_outdoors CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_pets CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_personal_finance CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_rural_farming CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_general_sports CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_stationery CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_general_travel CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_movies CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_wildlife CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_apparel_womens CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_unused_01 CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_photography CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_seniors CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_aviation CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_electionics CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_internet CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_credit_card_user CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_beauty_cosmetic CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_asian_ethnic_products CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_dieting CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_science CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_sweepstakes CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_tobacco CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_bargain_seekers CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_publications CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_catalogs CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_hightech CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_apparel_accessories CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_apparel_mens_fashions CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_apparel_womens_fashions CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_auto_racing CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_trucks CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_home_office_products CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_politically_conservative CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_crocheting CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_knitting CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_needlepoint CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_quilting CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_sewing CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_fiction CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_games CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_unused_03 CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_gourmet CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_history CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_internet_access CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_internet_buying CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_liberal CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_books_nonfiction CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_boating_sailing CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_camping_hiking CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_hunting_fishing CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_photo_processing CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_magazine_subscriber CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_books_science_fiction CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_skiing CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_soccer CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_tennis CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_travel_cruises CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_travel_rv CHARACTER VARYING(1) ENCODE ZSTD,
    lhi_travel_us CHARACTER VARYING(1) ENCODE ZSTD,
    tw_greenmodel CHARACTER VARYING(1) ENCODE ZSTD,
    tw_highvaluesecurityinvestor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_highereducation CHARACTER VARYING(1) ENCODE ZSTD,
    tw_highvaluestockinvestor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavyinvestmenttraders CHARACTER VARYING(1) ENCODE ZSTD,
    tw_physicalfitnessclubs CHARACTER VARYING(1) ENCODE ZSTD,
    tw_highriskinvestor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_lowriskinvestor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_frequentbusinesstraveler CHARACTER VARYING(1) ENCODE ZSTD,
    tw_frequentflyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_annuities CHARACTER VARYING(1) ENCODE ZSTD,
    tw_lifeinsurance CHARACTER VARYING(1) ENCODE ZSTD,
    tw_luxurycarbuyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_cruise CHARACTER VARYING(1) ENCODE ZSTD,
    tw_timeshareowner CHARACTER VARYING(1) ENCODE ZSTD,
    tw_impulsebuyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_luxuryhotel CHARACTER VARYING(1) ENCODE ZSTD,
    tw_pbsdonor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_safetysecurityconscious CHARACTER VARYING(1) ENCODE ZSTD,
    tw_shopaholics CHARACTER VARYING(1) ENCODE ZSTD,
    tw_avidthemeparkvisitor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_foreigntravelvacation CHARACTER VARYING(1) ENCODE ZSTD,
    tw_conservative CHARACTER VARYING(1) ENCODE ZSTD,
    tw_leaningconservative CHARACTER VARYING(1) ENCODE ZSTD,
    tw_leaningliberal CHARACTER VARYING(1) ENCODE ZSTD,
    tw_religiousdonor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_gardenmaintenance CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavyfamilyrestaurantvisitor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavypayperviewsports CHARACTER VARYING(1) ENCODE ZSTD,
    tw_nascar CHARACTER VARYING(1) ENCODE ZSTD,
    tw_liberal CHARACTER VARYING(1) ENCODE ZSTD,
    tw_dogproducts CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavypayperviewmovies CHARACTER VARYING(1) ENCODE ZSTD,
    tw_dietproducts CHARACTER VARYING(1) ENCODE ZSTD,
    tw_organicfoods CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavyvitaminanddietarysupplement CHARACTER VARYING(1) ENCODE ZSTD,
    tw_babyproducts CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavycouponuser CHARACTER VARYING(1) ENCODE ZSTD,
    tw_opinionleaders CHARACTER VARYING(1) ENCODE ZSTD,
    tw_catproducts CHARACTER VARYING(1) ENCODE ZSTD,
    tw_creditcardrewards CHARACTER VARYING(1) ENCODE ZSTD,
    tw_highendsportingequipment CHARACTER VARYING(1) ENCODE ZSTD,
    tw_homeimprovement CHARACTER VARYING(1) ENCODE ZSTD,
    tw_highendelectronicsbuyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_avidgamer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_rentalcar CHARACTER VARYING(1) ENCODE ZSTD,
    tw_avidcellphoneuser CHARACTER VARYING(1) ENCODE ZSTD,
    tw_countryclubmember CHARACTER VARYING(1) ENCODE ZSTD,
    tw_professionaltaxpreparation CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onsitetaxpreparationservice CHARACTER VARYING(1) ENCODE ZSTD,
    tw_classicalmusicconcerts CHARACTER VARYING(1) ENCODE ZSTD,
    tw_rockmusicconcerts CHARACTER VARYING(1) ENCODE ZSTD,
    tw_countrymusicconcerts CHARACTER VARYING(1) ENCODE ZSTD,
    tw_livetheater CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavybookbuyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_freshwaterfishing CHARACTER VARYING(1) ENCODE ZSTD,
    tw_saltwaterfishing CHARACTER VARYING(1) ENCODE ZSTD,
    tw_hunting CHARACTER VARYING(1) ENCODE ZSTD,
    tw_allterrainvehicle CHARACTER VARYING(1) ENCODE ZSTD,
    tw_powerboating CHARACTER VARYING(1) ENCODE ZSTD,
    tw_outdooractivities CHARACTER VARYING(1) ENCODE ZSTD,
    tw_adventureseekers CHARACTER VARYING(1) ENCODE ZSTD,
    tw_lowendsportingequipment CHARACTER VARYING(1) ENCODE ZSTD,
    tw_professionalbaseballsportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_professionalbasketballsportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_professionalfootballsportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_soccersportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_collegebasketballsportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_collegefootballsportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_golfsportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_tennissportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_professionalwrestlingsportsfans CHARACTER VARYING(1) ENCODE ZSTD,
    tw_internationallongdistance CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavyfrozendinner CHARACTER VARYING(1) ENCODE ZSTD,
    tw_cookfromscratch CHARACTER VARYING(1) ENCODE ZSTD,
    tw_cookforfun CHARACTER VARYING(1) ENCODE ZSTD,
    tw_winelover CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onlinepurchasepersonal CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onlinepurchasebusiness CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onlinetravelplan CHARACTER VARYING(1) ENCODE ZSTD,
    tw_blogwriting CHARACTER VARYING(1) ENCODE ZSTD,
    tw_voiceoverinternet CHARACTER VARYING(1) ENCODE ZSTD,
    tw_wifioutsideofhome CHARACTER VARYING(1) ENCODE ZSTD,
    tw_wifiinhome CHARACTER VARYING(1) ENCODE ZSTD,
    tw_wholesaleclub CHARACTER VARYING(1) ENCODE ZSTD,
    tw_autoclub CHARACTER VARYING(1) ENCODE ZSTD,
    tw_diyautomaintenance CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onlinegamingactivity CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onlineinvestmenttrading CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onlinebillpayment CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onlinetvdownload CHARACTER VARYING(1) ENCODE ZSTD,
    tw_mobileinternetaccess CHARACTER VARYING(1) ENCODE ZSTD,
    tw_socialmedianetwork CHARACTER VARYING(1) ENCODE ZSTD,
    tw_specialtyorganicfoodstore CHARACTER VARYING(1) ENCODE ZSTD,
    tw_homeoffice CHARACTER VARYING(1) ENCODE ZSTD,
    tw_businessbanking CHARACTER VARYING(1) ENCODE ZSTD,
    tw_moderate_economyhotel CHARACTER VARYING(1) ENCODE ZSTD,
    tw_e_reader CHARACTER VARYING(1) ENCODE ZSTD,
    tw_cellphoneonlymodel CHARACTER VARYING(1) ENCODE ZSTD,
    tw_alternativemedicine CHARACTER VARYING(1) ENCODE ZSTD,
    tw_non_religiousdonor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_majorhomeremodeling CHARACTER VARYING(1) ENCODE ZSTD,
    tw_avidsmartphoneusers CHARACTER VARYING(1) ENCODE ZSTD,
    tw_healthinsurance CHARACTER VARYING(1) ENCODE ZSTD,
    tw_satellitetv CHARACTER VARYING(1) ENCODE ZSTD,
    tw_onlinemusicdownload CHARACTER VARYING(1) ENCODE ZSTD,
    tw_adulteducation CHARACTER VARYING(1) ENCODE ZSTD,
    tw_pilates_yoga CHARACTER VARYING(1) ENCODE ZSTD,
    tw_fastfood CHARACTER VARYING(1) ENCODE ZSTD,
    tw_hybridcars CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavy_online_buyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_high_end_appparel CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavy_catalog_buyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_gift_buyers CHARACTER VARYING(1) ENCODE ZSTD,
    tw_camping CHARACTER VARYING(1) ENCODE ZSTD,
    tw_sports_fanatics CHARACTER VARYING(1) ENCODE ZSTD,
    tw_financial_planner CHARACTER VARYING(1) ENCODE ZSTD,
    tw_work_health_insurance CHARACTER VARYING(1) ENCODE ZSTD,
    tw_comprehensive_auto_insurance CHARACTER VARYING(1) ENCODE ZSTD,
    tw_small_business_insurance CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavy_snack_eaters CHARACTER VARYING(1) ENCODE ZSTD,
    tw_heavy_domestic_travelers CHARACTER VARYING(1) ENCODE ZSTD,
    tw_new_vehicle_buyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_suv_buyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_minivan_buyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_auto_loan CHARACTER VARYING(1) ENCODE ZSTD,
    tw_education_loan CHARACTER VARYING(1) ENCODE ZSTD,
    tw_real_estate_investment CHARACTER VARYING(1) ENCODE ZSTD,
    tw_fantasy_sports CHARACTER VARYING(1) ENCODE ZSTD,
    tw_hockey_buyer CHARACTER VARYING(1) ENCODE ZSTD,
    tw_auto_lease CHARACTER VARYING(1) ENCODE ZSTD,
    tw_digital_payment CHARACTER VARYING(1) ENCODE ZSTD,
    tw_high_mileage_usage CHARACTER VARYING(1) ENCODE ZSTD,
    tw_motorcycle_owner CHARACTER VARYING(1) ENCODE ZSTD,
    tw_union_member CHARACTER VARYING(1) ENCODE ZSTD,
    tw_national_park_visitor CHARACTER VARYING(1) ENCODE ZSTD,
    tw_online_streaming_and_devices CHARACTER VARYING(1) ENCODE ZSTD,
    tw_road_trip CHARACTER VARYING(1) ENCODE ZSTD,
    tw_social_networking_ad_click CHARACTER VARYING(1) ENCODE ZSTD,
    tw_satellite_radio CHARACTER VARYING(1) ENCODE ZSTD,
    heatingtype_code CHARACTER VARYING(1) ENCODE ZSTD,
    income_producing_assets CHARACTER VARYING(1) ENCODE ZSTD,
    marketarea CHARACTER VARYING(3) ENCODE BYTEDICT,
    phonenumbertype CHARACTER VARYING(1) ENCODE ZSTD,
    revolver_to_transactor CHARACTER VARYING(2) ENCODE ZSTD,
    second_property_ind CHARACTER VARYING(1) ENCODE ZSTD,
    consumerstabilityrawscore CHARACTER VARYING(3) ENCODE BYTEDICT,
    consumerstabilitypercentile CHARACTER VARYING(2) ENCODE BYTEDICT,
    ailments CHARACTER VARYING(15) ENCODE ZSTD,
    mailscore CHARACTER VARYING(2) ENCODE ZSTD,
    populationdensity CHARACTER VARYING(9) ENCODE ZSTD,
    number_of_surnames CHARACTER VARYING(1) ENCODE ZSTD,
    homeowner CHARACTER VARYING(1) ENCODE ZSTD,
    education_model CHARACTER VARYING(1) ENCODE ZSTD,
    education_model_ext CHARACTER VARYING(31) ENCODE ZSTD,
    income_producing_assets_ext CHARACTER VARYING(23) ENCODE BYTEDICT,
    titlecode_ext CHARACTER VARYING(4) ENCODE ZSTD,
    boatpropulsioncode_ext CHARACTER VARYING(19) ENCODE ZSTD,
    vendorethnicity_ext CHARACTER VARYING(39) ENCODE ZSTD,
    vendorreligion_ext CHARACTER VARYING(16) ENCODE ZSTD,
    vendorlanguage_ext CHARACTER VARYING(45) ENCODE ZSTD,
    vendorethnicgroup_ext CHARACTER VARYING(16) ENCODE ZSTD,
    countryoforign_ext CHARACTER VARYING(20) ENCODE ZSTD,
    contributionamount CHARACTER VARYING(7) ENCODE ZSTD,
    lemsmatchcode CHARACTER VARYING(18) ENCODE ZSTD,
    mortgagepresent CHARACTER VARYING(3) ENCODE ZSTD,
    discretionary_income_score CHARACTER VARYING(2) ENCODE BYTEDICT,
    membercount CHARACTER VARYING(1) ENCODE ZSTD,
    sesi CHARACTER VARYING(2) ENCODE BYTEDICT,
    zipfourmatchlevel CHARACTER VARYING(1) ENCODE ZSTD,
    no_stats_indicator CHARACTER VARYING(1) ENCODE ZSTD,
    vacant_indicator CHARACTER VARYING(1) ENCODE ZSTD,
    timezone CHARACTER VARYING(1) ENCODE ZSTD,
    areaprefix CHARACTER VARYING(6) ENCODE ZSTD,
    correctivelensespresence CHARACTER VARYING(1) ENCODE ZSTD,
    actualvacation_expense CHARACTER VARYING(4) ENCODE ZSTD,
    vacation_expense CHARACTER VARYING(1) ENCODE ZSTD,
    vacation_expense_dic CHARACTER VARYING(15) ENCODE BYTEDICT,
    nid CHARACTER VARYING(6) ENCODE ZSTD,
    nid_description CHARACTER VARYING(50) ENCODE ZSTD,
    gui_probable CHARACTER VARYING(1) ENCODE ZSTD,
    gui_probable_mightbe CHARACTER VARYING(1) ENCODE ZSTD,
    gui_accurate CHARACTER VARYING(1) ENCODE ZSTD,
    telemarketingflag CHARACTER VARYING(1) ENCODE ZSTD,
    phoneincludeallflag CHARACTER VARYING(1) ENCODE ZSTD,
    segmentcode_a CHARACTER VARYING(1) ENCODE ZSTD,
    segmentcode_e CHARACTER VARYING(1) ENCODE ZSTD,
    segmentcode_f CHARACTER VARYING(1) ENCODE ZSTD,
    segmentcode_g CHARACTER VARYING(1) ENCODE ZSTD,
    segmentcode_h CHARACTER VARYING(1) ENCODE ZSTD,
    segmentcode_i CHARACTER VARYING(1) ENCODE ZSTD,
    segmentcode_j CHARACTER VARYING(1) ENCODE ZSTD,
    opt_out_flag CHARACTER VARYING(1) ENCODE ZSTD,
    emailaddress CHARACTER VARYING(80) ENCODE ZSTD,
    vendor_code CHARACTER VARYING(2) ENCODE ZSTD,
    categories CHARACTER VARYING(100) ENCODE ZSTD,
    domain CHARACTER VARYING(80) ENCODE ZSTD,
    top_level_domain CHARACTER VARYING(6) ENCODE ZSTD,
    opt_out_date CHARACTER VARYING(8) ENCODE ZSTD,
    car_make CHARACTER VARYING(15) ENCODE ZSTD,
    car_model CHARACTER VARYING(30) ENCODE ZSTD,
    car_year CHARACTER VARYING(4) ENCODE ZSTD,
    date_entered_yyyymm CHARACTER VARYING(6) ENCODE ZSTD,
    email_domain CHARACTER VARYING(20) ENCODE ZSTD,
    open_flag CHARACTER VARYING(1) ENCODE ZSTD,
    open_date_yyyymm CHARACTER VARYING(6) ENCODE ZSTD,
    click_flag CHARACTER VARYING(1) ENCODE ZSTD,
    click_date_yyyymm CHARACTER VARYING(6) ENCODE ZSTD,
    md5_email_lower CHARACTER VARYING(32) ENCODE ZSTD,
    md5_email_upper CHARACTER VARYING(32) ENCODE ZSTD,
    ipaddress CHARACTER VARYING(35) ENCODE ZSTD,
    url CHARACTER VARYING(60) ENCODE ZSTD,
    sha256_email CHARACTER VARYING(64) ENCODE ZSTD,
    sha512_email CHARACTER VARYING(128) ENCODE ZSTD,
    bv_flag CHARACTER VARYING(1) ENCODE ZSTD,
    marigold CHARACTER VARYING(1) ENCODE ZSTD,
    bvt_refresh_date CHARACTER VARYING(8) ENCODE ZSTD,
    ipst_status_code CHARACTER VARYING(1) ENCODE ZSTD,
    ipst_refresh_date CHARACTER VARYING(8) ENCODE ZSTD,
    bestdate CHARACTER VARYING(8) ENCODE ZSTD,
    reactivation_flag CHARACTER VARYING(1) ENCODE ZSTD,
    mgen_match_flag CHARACTER VARYING(1) ENCODE ZSTD,
    bridge_code CHARACTER VARYING(1) ENCODE ZSTD,
    best_date_range CHARACTER VARYING(1) ENCODE ZSTD,
    haspostal CHARACTER VARYING(1) ENCODE ZSTD,
    infogroupcontact CHARACTER VARYING(1) ENCODE ZSTD,
    matchcode_lrfs CHARACTER VARYING(21) ENCODE ZSTD,
    cinclude CHARACTER VARYING(1) ENCODE ZSTD,
    matchlevel CHARACTER VARYING(1) ENCODE ZSTD,
    individual_id_bak BIGINT ENCODE AZ64,
    company_id_bak BIGINT ENCODE AZ64,
    email_deliverable CHARACTER VARYING(1) ENCODE ZSTD,
    email_marketable CHARACTER VARYING(1) ENCODE ZSTD,
    email_reputation_risk CHARACTER VARYING(1) ENCODE ZSTD,
    email_deployable CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage18_44female CHARACTER VARYING(1) ENCODE ZSTD,
    pprofsnl CHARACTER VARYING(6) ENCODE ZSTD,
    pwhitcol CHARACTER VARYING(6) ENCODE ZSTD,
    pbluecol CHARACTER VARYING(6) ENCODE ZSTD,
    pcolgrad CHARACTER VARYING(6) ENCODE ZSTD,
    routenumber CHARACTER VARYING(3) ENCODE ZSTD,
    boxtype CHARACTER VARYING(1) ENCODE ZSTD,
    boxnumber CHARACTER VARYING(6) ENCODE ZSTD,
    nameaddresssource CHARACTER VARYING(1) ENCODE ZSTD,
    mailorderbuyerflag CHARACTER VARYING(1) ENCODE ZSTD,
    creditcard_bank CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage0_11 CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage0_17 CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage18_24female CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage18_24male CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage18_34female CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage18_34male CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage25_34female CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage25_34male CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage35_44female CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage35_44male CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage35_54female CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage35_54male CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage45_54female CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage45_54male CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage50plus CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage55_64female CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage55_64male CHARACTER VARYING(1) ENCODE ZSTD,
    markettargetage65plus CHARACTER VARYING(1) ENCODE ZSTD,
    householdsize1_2 CHARACTER VARYING(1) ENCODE ZSTD,
    householdsize3plus CHARACTER VARYING(1) ENCODE ZSTD,
    phonesourcecat CHARACTER VARYING(1) ENCODE ZSTD,
    secondaryareacode CHARACTER VARYING(3) ENCODE ZSTD,
    secondaryphone CHARACTER VARYING(7) ENCODE ZSTD,
    numberoffireplaces CHARACTER VARYING(1) ENCODE ZSTD,
    pool CHARACTER VARYING(1) ENCODE ZSTD,
    bedroomcount CHARACTER VARYING(2) ENCODE ZSTD,
    bathroomcount CHARACTER VARYING(3) ENCODE ZSTD,
    garagetype CHARACTER VARYING(1) ENCODE ZSTD,
    homeownersource CHARACTER VARYING(1) ENCODE ZSTD,
    salepricesource CHARACTER VARYING(1) ENCODE ZSTD,
    saledatesource CHARACTER VARYING(1) ENCODE ZSTD,
    roomcount CHARACTER VARYING(2) ENCODE ZSTD,
    multipleunit CHARACTER VARYING(1) ENCODE ZSTD,
    purchasing_power_indicator CHARACTER VARYING(7) ENCODE BYTEDICT,
    phone_number CHARACTER VARYING(10) ENCODE ZSTD,
    fips_code CHARACTER VARYING(5) ENCODE ZSTD,
    lifestyle01 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle02 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle03 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle04 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle05 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle06 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle07 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle08 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle09 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle10 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle11 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle12 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle13 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle14 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle15 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle16 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle17 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle18 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle19 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle20 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle21 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle22 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle23 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle24 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle25 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle26 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle27 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle28 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle29 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle30 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle31 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle32 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle33 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle34 CHARACTER VARYING(4) ENCODE ZSTD,
    lifestyle35 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_1 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_2 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_3 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_4 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_5 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_6 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_7 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_8 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_9 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_10 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_11 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_12 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_13 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_14 CHARACTER VARYING(4) ENCODE ZSTD,
    ailments_15 CHARACTER VARYING(4) ENCODE ZSTD,
    census_combined_code CHARACTER VARYING(12) ENCODE ZSTD,
    census_state_country_tract CHARACTER VARYING(11) ENCODE ZSTD,
    contact_name CHARACTER VARYING(36) ENCODE ZSTD,
    donor_code1 CHARACTER VARYING(4) ENCODE ZSTD,
    donor_code2 CHARACTER VARYING(4) ENCODE ZSTD,
    donor_code3 CHARACTER VARYING(4) ENCODE ZSTD,
    donor_code4 CHARACTER VARYING(4) ENCODE ZSTD,
    donor_code5 CHARACTER VARYING(4) ENCODE ZSTD,
    zip9 CHARACTER VARYING(9) ENCODE ZSTD,
    mortgage_interest_rates CHARACTER VARYING(9) ENCODE ZSTD,
    hardkey CHARACTER VARYING(75) ENCODE ZSTD,
    countycodebystatecode CHARACTER VARYING(5) ENCODE ZSTD,
    carrierroutecodebyzipcode CHARACTER VARYING(9) ENCODE ZSTD,
    birthmonth CHARACTER VARYING(8) ENCODE ZSTD,
    birthdayofmonth CHARACTER VARYING(8) ENCODE ZSTD,
    birthyearmonth CHARACTER VARYING(8) ENCODE ZSTD,
    statecity CHARACTER VARYING(30) ENCODE ZSTD,
    fullname CHARACTER VARYING(36) ENCODE ZSTD,
    title CHARACTER VARYING(50) ENCODE ZSTD,
    gui_commonsuppression CHARACTER VARYING(1) ENCODE ZSTD,
    statecountyname CHARACTER VARYING(77) ENCODE ZSTD,
    statecityzip CHARACTER VARYING(49) ENCODE ZSTD,
    zipend CHARACTER VARYING(5) ENCODE ZSTD,
    statecityscf CHARACTER VARYING(47) ENCODE ZSTD,
    statecountycode CHARACTER VARYING(5) ENCODE ZSTD,
    unit_number_flag CHARACTER VARYING(1) ENCODE ZSTD,
    addresszip CHARACTER VARYING(45) ENCODE ZSTD,
    stateneighborhood CHARACTER VARYING(52) ENCODE ZSTD,
    statecityneighborhood CHARACTER VARYING(80) ENCODE ZSTD,
    mailorderbuyer_01 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_02 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_03 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_04 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_05 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_06 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_07 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_08 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_09 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_10 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_11 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_12 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_13 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_14 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_15 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_16 CHARACTER VARYING(2) ENCODE ZSTD,
    mailorderbuyer_18 CHARACTER VARYING(2) ENCODE ZSTD,
    individual_mc CHARACTER VARYING(65535) ENCODE ZSTD,
    company_mc CHARACTER VARYING(65535) ENCODE ZSTD,
    address_mc CHARACTER VARYING(65535) ENCODE ZSTD,
    preferredcity CHARACTER VARYING(33) ENCODE ZSTD,
    cellphone CHARACTER VARYING(10) ENCODE ZSTD,
    cellphone_areacode CHARACTER VARYING(3) ENCODE ZSTD,
    cellphone_number CHARACTER VARYING(7) ENCODE ZSTD,
    cellphone_cordcutter CHARACTER VARYING(1) ENCODE ZSTD,
    cellphone_prepaid_indicator CHARACTER VARYING(1) ENCODE ZSTD,
    cellphone_donotcallflag CHARACTER VARYING(1) ENCODE ZSTD,
    cellphone_verified_code CHARACTER VARYING(1) ENCODE ZSTD,
    cellphone_activitystatus CHARACTER VARYING(2) ENCODE ZSTD,
    cellphone_filterflag CHARACTER VARYING(1) ENCODE ZSTD,
    cellphone_filterreason CHARACTER VARYING(2) ENCODE ZSTD,
    cellphone_isdqi CHARACTER VARYING(1) ENCODE ZSTD,
    cellphone_matchlevel CHARACTER VARYING(7) ENCODE ZSTD,
    cellphone_matchscore CHARACTER VARYING(3) ENCODE ZSTD,
    cellphone_modifiedscore CHARACTER VARYING(3) ENCODE ZSTD,
    cellphone_individualmatch CHARACTER VARYING(1) ENCODE ZSTD,
    nielsen_county_rank_description CHARACTER VARYING(1000) ENCODE ZSTD,
    income_description CHARACTER VARYING(1000) ENCODE ZSTD,
    age_code_description CHARACTER VARYING(1000) ENCODE ZSTD,
    home_equity_estimate_description CHARACTER VARYING(1000) ENCODE ZSTD,
    home_sale_price_code_description CHARACTER VARYING(1000) ENCODE ZSTD,
    home_value_code_description CHARACTER VARYING(1000) ENCODE ZSTD,
    own_rent_indicator_description CHARACTER VARYING(1000) ENCODE ZSTD,
    expendable_income_rank_description CHARACTER VARYING(1000) ENCODE ZSTD,
    mortgage_amount_description CHARACTER VARYING(1000) ENCODE ZSTD,
    mortgage_loan_type_description CHARACTER VARYING(1000) ENCODE ZSTD,
    loan_to_value_ratio_ltv_description CHARACTER VARYING(1000) ENCODE ZSTD,
    censusstatecode2020 CHARACTER VARYING(2) ENCODE ZSTD,
	censuscountycode2020 CHARACTER VARYING(3) ENCODE ZSTD,
	censustract2020 CHARACTER VARYING(6) ENCODE ZSTD,
	censusblockgroup2020 CHARACTER VARYING(1) ENCODE ZSTD,
	secondmortgageamount CHARACTER VARYING(4) ENCODE ZSTD,
	secondmortgagetypecode CHARACTER VARYING(1) ENCODE ZSTD,
	lot_size_sqfeet CHARACTER VARYING(9) ENCODE ZSTD,
	universal_sqfeet CHARACTER VARYING(5) ENCODE ZSTD,
	universal_sqfeet_ind CHARACTER VARYING(1) ENCODE ZSTD,
	living_sqfeet CHARACTER VARYING(5) ENCODE ZSTD,
	groundfloor_sqfeet CHARACTER VARYING(5) ENCODE ZSTD,
	gross_sqfeet CHARACTER VARYING(5) ENCODE ZSTD,
	adjustedgross_sqfeet CHARACTER VARYING(5) ENCODE ZSTD,
	basement_sqfeet CHARACTER VARYING(5) ENCODE ZSTD,
	garage_sqfeet CHARACTER VARYING(5) ENCODE ZSTD,
	fullbath CHARACTER VARYING(1) ENCODE ZSTD,
	halfbath CHARACTER VARYING(1) ENCODE ZSTD,
	fireplace_ind CHARACTER VARYING(1) ENCODE ZSTD,
	fireplacetype CHARACTER VARYING(3) ENCODE ZSTD,
	pooltype CHARACTER VARYING(3) ENCODE ZSTD,
	roofcover CHARACTER VARYING(3) ENCODE ZSTD,
	roofshape CHARACTER VARYING(1) ENCODE ZSTD,
	conditiontype CHARACTER VARYING(1) ENCODE ZSTD,
	exteriorwalltype CHARACTER VARYING(3) ENCODE ZSTD,
	foundationtype CHARACTER VARYING(3) ENCODE ZSTD,
	constructionquality CHARACTER VARYING(1) ENCODE ZSTD,
	stories CHARACTER VARYING(3) ENCODE ZSTD,
	styletype CHARACTER VARYING(3) ENCODE ZSTD,
	airconditioningtype CHARACTER VARYING(3) ENCODE ZSTD,
	electricwiringtype CHARACTER VARYING(3) ENCODE ZSTD,
	fueltype CHARACTER VARYING(3) ENCODE ZSTD,
	sewertype CHARACTER VARYING(1) ENCODE ZSTD,
	watertype CHARACTER VARYING(1) ENCODE ZSTD,
	construction_type_detail CHARACTER VARYING(3) ENCODE ZSTD,
	heating_type_detail CHARACTER VARYING(3) ENCODE ZSTD,
 addressline2 CHARACTER VARYING(40) ENCODE ZSTD,
 autodb_unique_flag CHARACTER VARYING(5)
)
DISTSTYLE KEY;

COPY {maintable_name}
(
    listid,
    permissiontype,
    zipradius,
    georadius,
    firstname,
    middleinitial,
    lastname,
    last_name_suffix,
    title_code,
    gender,
    house_number,
    street_pre_directional,
    street_name,
    street_suffix,
    street_post_directional,
    unit_type,
    unit_number,
    city,
    state,
    census_state_code_2010,
    county_code,
    zip,
    zip_four,
    carrier_route_code,
    delivery_point_bar_code,
    area_code,
    nielsen_county_rank,
    time_zone,
    age_code,
    birth_date,
    income,
    last_contribution_date,
    length_of_residence,
    residence_type,
    delivery_unit_size_raw,
    own_rent_indicator,
    location_type,
    pool_type,
    home_value_code,
    home_sale_date,
    home_sale_price_code,
    home_sale_price,
    home_equity_estimate,
    finance_type,
    mortgage_loan_type,
    boat_propulsion_code,
    mortgage_amount,
    congressional_district,
    credit_card_code,
    number_trade_lines,
    marital_status,
    spousal_indicator_raw,
    cat_owner,
    dog_owner,
    grandparent_in_house,
    veteran_flag,
    stocks_or_bonds,
    dm_high_tech_household,
    female_occupation,
    male_occupation,
    census_average_years_attended_school_code,
    census_phhblack_code,
    census_of_population_graduated_college,
    census_phhspnsh_code,
    census_percent_of_population_married,
    census_precent_of_population_single_parent,
    expendable_income_rank,
    loan_to_value_ratio_ltv,
    donor_code,
    mail_responsive_current,
    mail_responsive_recent,
    mail_responsive_ever,
    census_tract_2010,
    census_block_group_2010,
    address_type,
    hoh_head_of_household,
    first_name_hoh,
    middle_initial_hoh,
    last_name_hoh,
    last_name_suffix_hoh,
    title_code_hoh,
    gender_hoh,
    birth_date_hoh,
    individual_id_hoh,
    hoh_age_code,
    number_trade_lines_hoh,
    credit_card_code_hoh,
    marital_status_hoh,
    company_id,
    individual_id,
    location_id,
    usps_delivery_service_type_code,
    nielsen_county_region,
    lot_size,
    home_size,
    home_age,
    actual_age_flag,
    political_contribution_amount,
    pilot_license_code,
    mortgage_interest_rates_old,
    last_party_contributed_to,
    aircraft_type_code,
    boat_owner_indicator,
    registered_voter,
    political_party_affiliation,
    number_of_adults_in_household,
    household_member_count,
    medag18p,
    census_percent_of_population_with_3_households,
    census_phhasian_code,
    medhhd1,
    wealth_finder,
    numberofchildren,
    alternatehhind,
    countryoforign,
    donotmailflag,
    emailpresenceflag,
    routetype,
    householdarrivaldate_year,
    householdarrivaldate,
    homeagesource,
    homebuiltyear,
    mortgagemonth,
    homevaluesource,
    actualincome,
    infopersona_cluster,
    infopersona_supercluster,
    lifestyle,
    listtype,
    marriedscore,
    medhhd2,
    mortgageloantype,
    mortgageinterestsource,
    occupancycount,
    agedatasource,
    presenceofchildren,
    recencydate,
    refreshdate,
    scf,
    vendorethnicity,
    vendorethnicgroup,
    vendorlanguage,
    vendorreligion,
    censuscountycode2010,
    fulfillmentflag,
    childrenbygender0,
    childrenbygender1,
    childrenbygender2,
    childrenbygender3,
    childrenbygender4,
    childrenbygender5,
    childrenbygender6,
    childrenbygender7,
    childrenbygender8,
    childrenbygender9,
    childrenbygender10,
    childrenbygender11,
    childrenbygender12,
    childrenbygender13,
    childrenbygender14,
    childrenbygender15,
    childrenbygender16,
    childrenbygender17,
    markettargetage0_5,
    markettargetage6_11,
    markettargetage12_17,
    markettargetage12_17female,
    markettargetage12_17male,
    children0_5,
    children6_11,
    children0_11,
    childrenbybirthmonth0,
    childrenbybirthmonth1,
    childrenbybirthmonth2,
    childrenbybirthmonth3,
    childrenbybirthmonth4,
    childrenbybirthmonth5,
    childrenbybirthmonth6,
    childrenbybirthmonth7,
    childrenbybirthmonth8,
    childrenbybirthmonth9,
    childrenbybirthmonth10,
    childrenbybirthmonth11,
    childrenbybirthmonth12,
    childrenbybirthmonth13,
    childrenbybirthmonth14,
    childrenbybirthmonth15,
    childrenbybirthmonth16,
    childrenbybirthmonth17,
    purchasing_power_income,
    potential_investor_consumer,
    sub_family_indicator,
    number_of_contributions,
    aircraft_mfg_year,
    cbsa_code,
    heavy_internet_user,
    early_technology_adopter,
    csa_code,
    csa_code_description,
    cbsa_level,
    mail_confidence,
    boat_hull_type,
    boat_length,
    flatitude,
    flongitude,
    vendor_matchcode,
    do_not_call_flag,
    has_primary_telephone,
    addressline1,
    digitalmatch,
    age,
    mortgagedate,
    loanamount,
    lhi_african_american_ethnic_products,
    lhi_american_history,
    lhi_general_apparel,
    lhi_automotive,
    lhi_baseball,
    lhi_basketball,
    lhi_bible,
    lhi_birds,
    lhi_publish_books,
    lhi_business_items,
    lhi_cats,
    lhi_collectibles,
    lhi_college,
    lhi_computers,
    lhi_cooking,
    lhi_general_crafts,
    lhi_current_events,
    lhi_do_it_yourselfer,
    lhi_charitable_donor,
    lhi_personalized_products,
    lhi_horses,
    lhi_culture_arts,
    lhi_dogs,
    lhi_children_family,
    lhi_fishing,
    lhi_fitness_exercise,
    lhi_football,
    lhi_gardening,
    lhi_gambling,
    lhi_gift_giver,
    lhi_golf,
    lhi_general_health,
    lhi_hispanic_ethnic_products,
    lhi_hobbies,
    lhi_hockey,
    lhi_home_decorating,
    lhi_humor,
    lhi_hunting,
    lhi_inspirational,
    lhi_apparel_kids,
    lhi_apparel_mens,
    lhi_money_making,
    lhi_motorcycles,
    lhi_music,
    lhi_ocean,
    lhi_outdoors,
    lhi_pets,
    lhi_personal_finance,
    lhi_rural_farming,
    lhi_general_sports,
    lhi_stationery,
    lhi_general_travel,
    lhi_movies,
    lhi_wildlife,
    lhi_apparel_womens,
    lhi_unused_01,
    lhi_photography,
    lhi_seniors,
    lhi_aviation,
    lhi_electionics,
    lhi_internet,
    lhi_credit_card_user,
    lhi_beauty_cosmetic,
    lhi_asian_ethnic_products,
    lhi_dieting,
    lhi_science,
    lhi_sweepstakes,
    lhi_tobacco,
    lhi_bargain_seekers,
    lhi_publications,
    lhi_catalogs,
    lhi_hightech,
    lhi_apparel_accessories,
    lhi_apparel_mens_fashions,
    lhi_apparel_womens_fashions,
    lhi_auto_racing,
    lhi_trucks,
    lhi_home_office_products,
    lhi_politically_conservative,
    lhi_crocheting,
    lhi_knitting,
    lhi_needlepoint,
    lhi_quilting,
    lhi_sewing,
    lhi_fiction,
    lhi_games,
    lhi_unused_03,
    lhi_gourmet,
    lhi_history,
    lhi_internet_access,
    lhi_internet_buying,
    lhi_liberal,
    lhi_books_nonfiction,
    lhi_boating_sailing,
    lhi_camping_hiking,
    lhi_hunting_fishing,
    lhi_photo_processing,
    lhi_magazine_subscriber,
    lhi_books_science_fiction,
    lhi_skiing,
    lhi_soccer,
    lhi_tennis,
    lhi_travel_cruises,
    lhi_travel_rv,
    lhi_travel_us,
    tw_greenmodel,
    tw_highvaluesecurityinvestor,
    tw_highereducation,
    tw_highvaluestockinvestor,
    tw_heavyinvestmenttraders,
    tw_physicalfitnessclubs,
    tw_highriskinvestor,
    tw_lowriskinvestor,
    tw_frequentbusinesstraveler,
    tw_frequentflyer,
    tw_annuities,
    tw_lifeinsurance,
    tw_luxurycarbuyer,
    tw_cruise,
    tw_timeshareowner,
    tw_impulsebuyer,
    tw_luxuryhotel,
    tw_pbsdonor,
    tw_safetysecurityconscious,
    tw_shopaholics,
    tw_avidthemeparkvisitor,
    tw_foreigntravelvacation,
    tw_conservative,
    tw_leaningconservative,
    tw_leaningliberal,
    tw_religiousdonor,
    tw_gardenmaintenance,
    tw_heavyfamilyrestaurantvisitor,
    tw_heavypayperviewsports,
    tw_nascar,
    tw_liberal,
    tw_dogproducts,
    tw_heavypayperviewmovies,
    tw_dietproducts,
    tw_organicfoods,
    tw_heavyvitaminanddietarysupplement,
    tw_babyproducts,
    tw_heavycouponuser,
    tw_opinionleaders,
    tw_catproducts,
    tw_creditcardrewards,
    tw_highendsportingequipment,
    tw_homeimprovement,
    tw_highendelectronicsbuyer,
    tw_avidgamer,
    tw_rentalcar,
    tw_avidcellphoneuser,
    tw_countryclubmember,
    tw_professionaltaxpreparation,
    tw_onsitetaxpreparationservice,
    tw_classicalmusicconcerts,
    tw_rockmusicconcerts,
    tw_countrymusicconcerts,
    tw_livetheater,
    tw_heavybookbuyer,
    tw_freshwaterfishing,
    tw_saltwaterfishing,
    tw_hunting,
    tw_allterrainvehicle,
    tw_powerboating,
    tw_outdooractivities,
    tw_adventureseekers,
    tw_lowendsportingequipment,
    tw_professionalbaseballsportsfans,
    tw_professionalbasketballsportsfans,
    tw_professionalfootballsportsfans,
    tw_soccersportsfans,
    tw_collegebasketballsportsfans,
    tw_collegefootballsportsfans,
    tw_golfsportsfans,
    tw_tennissportsfans,
    tw_professionalwrestlingsportsfans,
    tw_internationallongdistance,
    tw_heavyfrozendinner,
    tw_cookfromscratch,
    tw_cookforfun,
    tw_winelover,
    tw_onlinepurchasepersonal,
    tw_onlinepurchasebusiness,
    tw_onlinetravelplan,
    tw_blogwriting,
    tw_voiceoverinternet,
    tw_wifioutsideofhome,
    tw_wifiinhome,
    tw_wholesaleclub,
    tw_autoclub,
    tw_diyautomaintenance,
    tw_onlinegamingactivity,
    tw_onlineinvestmenttrading,
    tw_onlinebillpayment,
    tw_onlinetvdownload,
    tw_mobileinternetaccess,
    tw_socialmedianetwork,
    tw_specialtyorganicfoodstore,
    tw_homeoffice,
    tw_businessbanking,
    tw_moderate_economyhotel,
    tw_e_reader,
    tw_cellphoneonlymodel,
    tw_alternativemedicine,
    tw_non_religiousdonor,
    tw_majorhomeremodeling,
    tw_avidsmartphoneusers,
    tw_healthinsurance,
    tw_satellitetv,
    tw_onlinemusicdownload,
    tw_adulteducation,
    tw_pilates_yoga,
    tw_fastfood,
    tw_hybridcars,
    tw_heavy_online_buyer,
    tw_high_end_appparel,
    tw_heavy_catalog_buyer,
    tw_gift_buyers,
    tw_camping,
    tw_sports_fanatics,
    tw_financial_planner,
    tw_work_health_insurance,
    tw_comprehensive_auto_insurance,
    tw_small_business_insurance,
    tw_heavy_snack_eaters,
    tw_heavy_domestic_travelers,
    tw_new_vehicle_buyer,
    tw_suv_buyer,
    tw_minivan_buyer,
    tw_auto_loan,
    tw_education_loan,
    tw_real_estate_investment,
    tw_fantasy_sports,
    tw_hockey_buyer,
    tw_auto_lease,
    tw_digital_payment,
    tw_high_mileage_usage,
    tw_motorcycle_owner,
    tw_union_member,
    tw_national_park_visitor,
    tw_online_streaming_and_devices,
    tw_road_trip,
    tw_social_networking_ad_click,
    tw_satellite_radio,
    heatingtype_code,
    income_producing_assets,
    marketarea,
    phonenumbertype,
    revolver_to_transactor,
    second_property_ind,
    consumerstabilityrawscore,
    consumerstabilitypercentile,
    ailments,
    mailscore,
    populationdensity,
    number_of_surnames,
    homeowner,
    education_model,
    education_model_ext,
    income_producing_assets_ext,
    titlecode_ext,
    boatpropulsioncode_ext,
    vendorethnicity_ext,
    vendorreligion_ext,
    vendorlanguage_ext,
    vendorethnicgroup_ext,
    countryoforign_ext,
    contributionamount,
    lemsmatchcode,
    mortgagepresent,
    discretionary_income_score,
    membercount,
    sesi,
    zipfourmatchlevel,
    no_stats_indicator,
    vacant_indicator,
    timezone,
    areaprefix,
    correctivelensespresence,
    actualvacation_expense,
    vacation_expense,
    vacation_expense_dic,
    nid,
    nid_description,
    gui_probable,
    gui_probable_mightbe,
    gui_accurate,
    telemarketingflag,
    phoneincludeallflag,
    segmentcode_a,
    segmentcode_e,
    segmentcode_f,
    segmentcode_g,
    segmentcode_h,
    segmentcode_i,
    segmentcode_j,
    opt_out_flag,
    emailaddress,
    vendor_code,
    categories,
    domain,
    top_level_domain,
    opt_out_date,
    car_make,
    car_model,
    car_year,
    date_entered_yyyymm,
    email_domain,
    open_flag,
    open_date_yyyymm,
    click_flag,
    click_date_yyyymm,
    md5_email_lower,
    md5_email_upper,
    ipaddress,
    url,
    sha256_email,
    sha512_email,
    bv_flag,
    marigold,
    bvt_refresh_date,
    ipst_status_code,
    ipst_refresh_date,
    bestdate,
    reactivation_flag,
    mgen_match_flag,
    bridge_code,
    best_date_range,
    haspostal,
    infogroupcontact,
    matchcode_lrfs,
    cinclude,
    matchlevel,
    individual_id_bak,
    company_id_bak,
    email_deliverable,
    email_marketable,
    email_reputation_risk,
    email_deployable,
    markettargetage18_44female,
    pprofsnl,
    pwhitcol,
    pbluecol,
    pcolgrad,
    routenumber,
    boxtype,
    boxnumber,
    nameaddresssource,
    mailorderbuyerflag,
    creditcard_bank,
    markettargetage0_11,
    markettargetage0_17,
    markettargetage18_24female,
    markettargetage18_24male,
    markettargetage18_34female,
    markettargetage18_34male,
    markettargetage25_34female,
    markettargetage25_34male,
    markettargetage35_44female,
    markettargetage35_44male,
    markettargetage35_54female,
    markettargetage35_54male,
    markettargetage45_54female,
    markettargetage45_54male,
    markettargetage50plus,
    markettargetage55_64female,
    markettargetage55_64male,
    markettargetage65plus,
    householdsize1_2,
    householdsize3plus,
    phonesourcecat,
    secondaryareacode,
    secondaryphone,
    numberoffireplaces,
    pool,
    bedroomcount,
    bathroomcount,
    garagetype,
    homeownersource,
    salepricesource,
    saledatesource,
    roomcount,
    multipleunit,
    purchasing_power_indicator,
    phone_number,
    fips_code,
    lifestyle01,
    lifestyle02,
    lifestyle03,
    lifestyle04,
    lifestyle05,
    lifestyle06,
    lifestyle07,
    lifestyle08,
    lifestyle09,
    lifestyle10,
    lifestyle11,
    lifestyle12,
    lifestyle13,
    lifestyle14,
    lifestyle15,
    lifestyle16,
    lifestyle17,
    lifestyle18,
    lifestyle19,
    lifestyle20,
    lifestyle21,
    lifestyle22,
    lifestyle23,
    lifestyle24,
    lifestyle25,
    lifestyle26,
    lifestyle27,
    lifestyle28,
    lifestyle29,
    lifestyle30,
    lifestyle31,
    lifestyle32,
    lifestyle33,
    lifestyle34,
    lifestyle35,
    ailments_1,
    ailments_2,
    ailments_3,
    ailments_4,
    ailments_5,
    ailments_6,
    ailments_7,
    ailments_8,
    ailments_9,
    ailments_10,
    ailments_11,
    ailments_12,
    ailments_13,
    ailments_14,
    ailments_15,
    census_combined_code,
    census_state_country_tract,
    contact_name,
    donor_code1,
    donor_code2,
    donor_code3,
    donor_code4,
    donor_code5,
    zip9,
    mortgage_interest_rates,
    hardkey,
    countycodebystatecode,
    carrierroutecodebyzipcode,
    birthmonth,
    birthdayofmonth,
    birthyearmonth,
    statecity,
    fullname,
    title,
    gui_commonsuppression,
    statecountyname,
    statecityzip,
    zipend,
    statecityscf,
    statecountycode,
    unit_number_flag,
    addresszip,
    stateneighborhood,
    statecityneighborhood,
    mailorderbuyer_01,
    mailorderbuyer_02,
    mailorderbuyer_03,
    mailorderbuyer_04,
    mailorderbuyer_05,
    mailorderbuyer_06,
    mailorderbuyer_07,
    mailorderbuyer_08,
    mailorderbuyer_09,
    mailorderbuyer_10,
    mailorderbuyer_11,
    mailorderbuyer_12,
    mailorderbuyer_13,
    mailorderbuyer_14,
    mailorderbuyer_15,
    mailorderbuyer_16,
    mailorderbuyer_18,
    individual_mc,
    company_mc,
    address_mc,
    preferredcity,
    cellphone,
    cellphone_areacode,
    cellphone_number,
    cellphone_cordcutter,
    cellphone_prepaid_indicator,
    cellphone_donotcallflag,
    cellphone_verified_code,
    cellphone_activitystatus,
    cellphone_filterflag,
    cellphone_filterreason,
    cellphone_isdqi,
    cellphone_matchlevel,
    cellphone_matchscore,
    cellphone_modifiedscore,
    cellphone_individualmatch,
    nielsen_county_rank_description,
    income_description,
    age_code_description,
    home_equity_estimate_description,
    home_sale_price_code_description,
    home_value_code_description,
    own_rent_indicator_description,
    expendable_income_rank_description,
    mortgage_amount_description,
    mortgage_loan_type_description,
    loan_to_value_ratio_ltv_description,
    censusstatecode2020,
    censuscountycode2020,
    censustract2020,
    censusblockgroup2020,
    secondmortgageamount,
    secondmortgagetypecode,
    lot_size_sqfeet,
    universal_sqfeet,
    universal_sqfeet_ind,
    living_sqfeet,
    groundfloor_sqfeet,
    gross_sqfeet,
    adjustedgross_sqfeet,
    basement_sqfeet,
    garage_sqfeet,
    fullbath,
    halfbath,
    fireplace_ind,
    fireplacetype,
    pooltype,
    roofcover,
    roofshape,
    conditiontype,
    exteriorwalltype,
    foundationtype,
    constructionquality,
    stories,
    styletype,
    airconditioningtype,
    electricwiringtype,
    fueltype,
    sewertype,
    watertype,
    construction_type_detail,
    heating_type_detail
)
FROM 's3://idms-7933-prod/temp/consumer/'
IAM_ROLE '{iam}'
FORMAT PARQUET;


UPDATE {maintable_name} set autodb_unique_flag = '';
/*
ALTER TABLE {maintable_name} RENAME COLUMN id TO id_old;
ALTER TABLE {maintable_name} RENAME COLUMN iID TO id;
*/

