DROP TABLE IF EXISTS {tablename1};

/*As per #757849 RB changed field length of "lifestyle_hobby_interest_flags" from varchar(104)to varchar(105 ) */
/*Add Corrective Lenses field at the end of main table jira-1412*/

CREATE TABLE {tablename1} (
lems varchar(18) PRIMARY KEY encode raw,
child1_dob varchar(6) encode zstd,
child1_gender varchar(1) encode zstd,
child2_dob varchar(6) encode zstd,
child2_gender varchar(1) encode zstd,
child3_dob varchar(6) encode zstd,
child3_gender varchar(1) encode zstd,
child4_dob varchar(6) encode zstd,
child4_gender varchar(1) encode zstd,
child5_dob varchar(6) encode zstd,
child5_gender varchar(1) encode zstd,
congressionaldistrict varchar(2) encode zstd,
locationtype varchar(1) encode zstd,
grandparentinhouse varchar(1) encode zstd,
homeequityestimate varchar(1) encode zstd,
income_code varchar(1) encode zstd,
homevalue varchar(1) encode zstd,
findincome varchar(6) encode bytedict,
lengthofresidence varchar(2) encode bytedict,
length_of_residence_code varchar(1) encode zstd,
lines_of_credit_code varchar(1) encode zstd,
mortgageamount varchar(1) encode zstd,
wealthfinder varchar(1) encode zstd,
nielsencountyrank varchar(1) encode zstd,
numberofadults varchar(1) encode zstd,
numberofchildren varchar(1) encode zstd,
femaleoccupation varchar(2) encode zstd,
maleoccupation varchar(2) encode zstd,
ownrent varchar(1) encode zstd,
potentialinvestorconsumer varchar(2) encode zstd,
presenceofchildren varchar(1) encode zstd,
phone varchar(10) encode zstd,
phonenumbertype varchar(1) encode zstd,
workathomeflag varchar(1) encode zstd,
internetusage varchar(2) encode zstd,
heavy_internet_user varchar(2) encode zstd,
dmhightechhousehold varchar(1) encode zstd,
hohagecode varchar(1) encode zstd,
ppi varchar(6) encode bytedict,
ppi_code varchar(1) encode zstd,
children_age_presence_flag varchar(15) encode zstd,
interest_flag varchar(35) encode zstd,
lifestyle_hobby_interest_flags varchar(105) encode zstd,
ailments_flags varchar(15) encode zstd,
credit_card_flag varchar(9) encode zstd,
donor_flags varchar(5) encode zstd,
market_target_age_flags varchar(24) encode zstd,
children_month_of_birth varchar(12) encode zstd,
age0_3 varchar(1) encode zstd,
children_Age_by_gender varchar(54) encode zstd,
politicalparty varchar(1) encode zstd,
DMACodes varchar(3) encode zstd, 
DMAName varchar(50) encode zstd, 
nielsencountyregion varchar(1) encode zstd, 
Veteran_in_HHLD varchar(1) encode zstd, 
Address_Type varchar(1) encode zstd,
Consumer_Stability_Index_Raw_Score varchar(3) encode bytedict, 
Individual_HoH_Head_of_Household_Flag varchar(1) encode zstd, 
Expendable_Income_Rank_Code varchar(1) encode zstd, 
Home_Owner_Flag varchar(1) encode zstd, 
Family_Income_Detector_Code varchar(1) encode zstd, 
Mail_Order_Buyer_Current_Flag varchar(1) encode zstd, 
Mail_Order_Buyer_Ever_Flag varchar(1) encode zstd, 
Household_Head_Married_Score varchar(1) encode zstd, 
Surnames_In_Household varchar(1) encode zstd, 
Occupancy_Count varchar(2) encode zstd, 
Delivery_unit_size varchar(2) encode zstd, 
Family_Income_Detector_Ranges varchar(1) encode zstd,
Home_Age varchar(3) encode bytedict,
Home_Sale_Date varchar(8) encode zstd,
Revolver_To_Transactor_Model varchar(2) encode zstd,
Discretionary_Income_Score varchar(2) encode bytedict,    
Education_Model varchar(1) encode zstd,
Income_Producing_Assets varchar(1) encode zstd,
Pensioner_Present_Flag varchar(1) encode zstd, 
Email_Presence_Flag varchar(1) encode zstd,   
Household_Head_Age_Code_Source  varchar(1) encode zstd,
Corrective_Lenses_Present_Flag varchar(1) encode zstd
)
DISTSTYLE KEY
DISTKEY(LEMS)
SORTKEY(LEMS) ;
/*ALS_Census_Tract_2010      varchar(6), Removed by Niken as per Ticket653641 */
/*emailpresenceflag        varchar(1), Removed by Niken as per Ticket653641 */

COPY {tablename1}
FROM 's3://{s3-internal}{s3-key1}' 
iam_role '{iam}'
fixedwidth 
'lems:18,
child1_dob:6,
child1_gender:1,
child2_dob:6,
child2_gender:1,
child3_dob:6,
child3_gender:1,
child4_dob:6,
child4_gender:1,
child5_dob:6,
child5_gender:1,
congressionaldistrict:2,
locationtype:1,
grandparentinhouse:1,
homeequityestimate:1,
income_code:1,
homevalue:1,
findincome:6,
lengthofresidence:2,
length_of_residence_code:1,
lines_of_credit_code:1,
mortgageamount:1,
wealthfinder:1,
nielsencountyrank:1,
numberofadults:1,
numberofchildren:1,
femaleoccupation:2,
maleoccupation:2,
ownrent:1,
potentialinvestorconsumer:2,
presenceofchildren:1,
phone:10,
phonenumbertype:1,
workathomeflag:1,
internetusage:2,
heavy_internet_user:2,
dmhightechhousehold:1,
hohagecode:1,
ppi:6,
ppi_code:1,
children_age_presence_flag:15,
interest_flag:35,
lifestyle_hobby_interest_flags:105,
ailments_flags:15,
credit_card_flag:9,
donor_flags:5,
market_target_age_flags:24,
children_month_of_birth:12,
age0_3:1,
children_Age_by_gender:54,
politicalparty:1,
DMACodes:3, 
DMAName:50, 
nielsencountyregion:1, 
Veteran_in_HHLD:1, 
Address_Type:1, 
Consumer_Stability_Index_Raw_Score:3, 
Individual_HoH_Head_of_Household_Flag:1, 
Expendable_Income_Rank_Code:1, 
Home_Owner_Flag:1, 
Family_Income_Detector_Code:1, 
Mail_Order_Buyer_Current_Flag:1, 
Mail_Order_Buyer_Ever_Flag:1, 
Household_Head_Married_Score:1, 
Surnames_In_Household:1, 
Occupancy_Count:2, 
Delivery_unit_size:2, 
Family_Income_Detector_Ranges:1, 
Home_Age:3,
Home_Sale_Date:8,
Revolver_To_Transactor_Model:2,
Discretionary_Income_Score:2,  
Education_Model:1,
Income_Producing_Assets:1,
Pensioner_Present_Flag:1,  
Email_Presence_Flag:1, 
Household_Head_Age_Code_Source:1,
Corrective_Lenses_Present_Flag:1';
/*emailpresenceflag:1, Removed by Niken as per Ticket653641 */
/*ALS_Census_Tract_2010:6, Removed by Niken as per Ticket653641 */
/*Email_Presence_Flag:1,   Added by  Reeba as per Incident# 679638 */ 

/* Delete Blank Lems. Incident# 717686*/

DELETE FROM {tablename1} WHERE LTRIM(RTRIM(lems)) = '' OR lems IS NULL; 
