/*
L2_Voter Data
Data Source: l2-ext39, cons univ  ON company_id
Condition:
OrderBy:
Other: pass 0 for nulls

 Update Schedule: Monthly
*/




unload ('select l2.company_id,
       lems,
       l2.individual_id,
       l2_voters_gender,
       l2_voters_age,
       l2_voters_birthdate,
       l2_voters_calculatedregdate,
       l2_us_congressional_district,
       l2_state_house_district,
       l2_state_legislative_district,
       l2_state_senate_district,
       l2_precinct,
       l2_comm_gun_owner,
       l2_comm_veteran,
       l2_comm_donates_to_animal_welfare,
       l2_comm_donates_to_arts_and_culture,
       l2_comm_donates_to_childrens_causes,
       l2_comm_donates_to_healthcare,
       l2_comm_donates_to_international_aid_caus,
       l2_comm_donates_to_veterans_causes,
       l2_comm_donates_to_wildlife_preservation,
       l2_comm_donates_to_conservative_causes,
       l2_comm_donates_to_liberal_causes,
       l2_comm_donates_to_local_community,
       l2_comm_petowner_horse,
       l2_comm_petowner_cat,
       l2_comm_petowner_dog,
       l2_comm_petowner_other,
       l2_fecdonors_numberofdonations,
       l2_fecdonors_totaldonationsamount,
       l2_fecdonors_totaldonationsamt_range,
       l2_fecdonors_lastdonationdate,
       l2_fecdonors_avgdonation,
       l2_fecdonors_avgdonation_range,
       l2_voters_votingperformanceevenyeargeneral,
       l2_voters_votingperformanceevenyearprimary,
       l2_voters_votingperformanceevenyeargeneralprimary,
       l2_voters_votingperformanceminorelection,
       l2_comm_interest_in_history_military_in_h,
       l2_comm_interest_in_current_affairs_polit,
       l2_comm_interest_in_religious_inspiration,
       l2_comm_interest_in_theater_performing_ar,
       l2_comm_interest_in_the_arts_in_household,
       l2_comm_collector_military_in_household,
       l2_comm_interest_in_gaming_casino_in_hous,
       l2_comm_interest_in_exercise_health_in_ho,
       l2_comm_interest_in_exercise_running_jogg,
       l2_comm_interest_in_exercise_walking_in_h,
       l2_comm_interest_in_exercise_aerobic_in_h,
       l2_comm_interest_in_spectatorsports_auto_,
       l2_comm_interest_in_nascar_in_household,
       l2_comm_interest_in_hunting_in_household,
       l2_comm_interest_in_fishing_in_household,
       l2_comm_interest_in_camping_hiking_in_hou,
       l2_comm_interest_in_shooting_in_household,
       l2_comm_gun_owner_concealed_permit,
       l2_primary_2018,
       l2_otherelection_2018,
       l2_anyelection_2017,
       l2_general_2016,
       l2_primary_2016,
       l2_otherelection_2016,
       l2_anyelection_2015,
       l2_general_2014,
       l2_primary_2014,
       l2_otherelection_2014,
       l2_anyelection_2013,
       l2_general_2012,
       l2_primary_2012,
       l2_otherelection_2012,
       l2_anyelection_2011,
       l2_general_2010,
       l2_primary_2010,
       l2_otherelection_2010,
       l2_anyelection_2009,
       l2_general_2008,
       l2_primary_2008,
       l2_otherelection_2008,
       l2_anyelection_2007,
       l2_general_2006,
       l2_primary_2006,
       l2_otherelection_2006,
       l2_anyelection_2005,
       l2_general_2004,
       l2_primary_2004,
       l2_otherelection_2004,
       l2_anyelection_2003,
       l2_general_2002,
       l2_primary_2002,
       l2_otherelection_2002,
       l2_anyelection_2001,
       l2_general_2000,
       l2_primary_2000,
       l2_otherelection_2000,
       l2_pri_blt_2020,
       l2_pri_blt_2019,
       l2_pri_blt_2018,
       l2_pri_blt_2017,
       l2_pri_blt_2016,
       l2_pri_blt_2015,
       l2_pri_blt_2014,
       l2_pri_blt_2013,
       l2_pri_blt_2012,
       l2_pri_blt_2011,
       l2_pri_blt_2010,
       l2_pri_blt_2009,
       l2_pri_blt_2008,
       l2_pri_blt_2007,
       l2_pri_blt_2006,
       l2_pri_blt_2005,
       l2_pri_blt_2004,
       l2_pri_blt_2003,
       l2_pri_blt_2002,
       l2_pri_blt_2001,
       l2_pri_blt_2000,
       l2_phone,
       l2_votertelephones_landlineconfidencecode,
       l2_votertelephones_cellphoneunformatted,
       l2_votertelephones_cellconfidencecode,
       l2_parties_description,
       l2_voters_active,
       l2_general_2020,
       l2_primary_2020,
       l2_otherelection_2020,
       l2_anyelection_2019,
       l2_voters_movedfrom_state,
       l2_voters_movedfrom_date,
       l2_voters_movedfrom_party_description,
       l2_voters_movedfrom_voteperformevenyeargeneral,
       l2_voters_movedfrom_voteperformevenyearprimary,
       l2_voters_movedfrom_voteperformevenyrgeneralprim,
       l2_voters_movedfrom_voteperformminorelection,
       l2_g20_cnty_margin_biden_d,
       l2_g20_cnty_percent_biden_d,
       l2_g20_cnty_vote_biden_d,
       l2_g20_cnty_margin_trump_r,
       l2_g20_cnty_percent_trump_r,
       l2_g20_cnty_vote_trump_r,
       l2_g20countyturnoutallregisteredvoters,
       l2_g20countyturnoutdemocrats,
       l2_g20countyturnoutindependentsallothers,
       l2_g20countyturnoutrepublicans,
       l2_g20precinctturnoutallregisteredvoters,
       l2_g20precinctturnoutdemocrats,
       l2_g20precinctturnoutindependentsallothers,
       l2_g20precinctturnoutrepublicans,
       l2_p20_cnty_pct_biden_d,
       l2_p20_cnty_pct_bloomberg_d,
       l2_p20_cnty_pct_buttigieg_d,
       l2_p20_cnty_pct_gabbard_d,
       l2_p20_cnty_pct_klobuchar_d,
       l2_p20_cnty_pct_sanders_d,
       l2_p20_cnty_pct_warren_d,
       l2_p20_cnty_vote_biden_d,
       l2_p20_cnty_vote_bloomberg_d,
       l2_p20_cnty_vote_buttigieg_d,
       l2_p20_cnty_vote_gabbard_d,
       l2_p20_cnty_vote_klobuchar_d,
       l2_p20_cnty_vote_sanders_d,
       l2_p20_cnty_vote_warren_d,
       l2_p20countyturnoutallregisteredvoters,
       l2_p20countyturnoutdemocrats,
       l2_p20countyturnoutrepublicans,
       l2_p20precinctturnoutallregisteredvoters,
       l2_p20precinctturnoutdemocrats,
       l2_p20precinctturnoutrepublicans,
       l2_voters_officialregdate
--      ,hh_status_code  -- 20221010 CB
from tblexternal45_191_201206 l2
inner join ctas_cons_unv_individ_tobedropped m on l2.individual_id = m.individual_id')
    to 's3://{s3-apogee}{export_mmdb_7}'
    iam_role '{iam}'
    encrypted
    cleanpath
    gzip
    delimiter as '|'
    maxfilesize 6 gb;


insert into apogee_export_count
    (tablename, record_count)
select 'voter_data',  count(*)
from tblexternal45_191_201206 l2
inner join ctas_cons_unv_individ_tobedropped m on l2.individual_id = m.individual_id;
