drop table if exists tblchild34_{build_id}_{build}_int CASCADE;

create table tblchild34_{build_id}_{build}_int
(
cid VARCHAR(18) ENCODE RAW,
ap_id VARCHAR(11) ENCODE ZSTD,
ap_lems VARCHAR(18) ENCODE ZSTD,
company_id BIGINT ENCODE ZSTD,
donormatch VARCHAR(1) ENCODE ZSTD,
ltd_months_since_last_donation_date INT ENCODE AZ64,
ltd_last_donation_date_yyyymm VARCHAR(6) ENCODE BYTEDICT,
ltd_number_of_list_sources INT ENCODE ZSTD,
ltd_average_donation_per_transaction INT ENCODE ZSTD,
m12_number_of_list_sources INT ENCODE ZSTD,
m12_average_donation_per_transaction INT ENCODE ZSTD,
m12_cat_ac_number_of_donation INT ENCODE ZSTD,
m12_cat_an_number_of_donation INT ENCODE ZSTD,
m12_cat_cd_number_of_donation INT ENCODE ZSTD,
m12_cat_cg_number_of_donation INT ENCODE ZSTD,
m12_cat_ch_number_of_donation INT ENCODE ZSTD,
m12_cat_co_number_of_donation INT ENCODE ZSTD,
m12_cat_cs_number_of_donation INT ENCODE ZSTD,
m12_cat_ea_number_of_donation INT ENCODE AZ64,
m12_cat_et_number_of_donation INT ENCODE ZSTD,
m12_cat_hg_number_of_donation INT ENCODE ZSTD,
m12_cat_hs_number_of_donation INT ENCODE ZSTD,
m12_cat_li_number_of_donation INT ENCODE ZSTD,
m12_cat_nt_number_of_donation INT ENCODE ZSTD,
m12_cat_pa_number_of_donation INT ENCODE ZSTD,
m12_cat_rc_number_of_donation INT ENCODE ZSTD,
m12_cat_rd_number_of_donation INT ENCODE ZSTD,
m12_cat_ri_number_of_donation INT ENCODE ZSTD,
m12_cat_rj_number_of_donation INT ENCODE ZSTD,
m12_cat_ss_number_of_donation INT ENCODE ZSTD,
m12_cat_sw_number_of_donation INT ENCODE AZ64,
m12_cat_ve_number_of_donation INT ENCODE ZSTD,
m48_number_of_donation_dollar_cash INT ENCODE ZSTD,
m48_number_of_donation_dollar_check INT ENCODE ZSTD,
m48_cat_an_number_of_donation INT ENCODE ZSTD,
m48_cat_ac_number_of_donation INT ENCODE ZSTD,
m48_cat_cd_number_of_donation INT ENCODE ZSTD,
m48_cat_cs_number_of_donation INT ENCODE ZSTD,
m48_cat_cg_number_of_donation INT ENCODE ZSTD,
m48_cat_ch_number_of_donation INT ENCODE ZSTD,
m48_cat_co_number_of_donation INT ENCODE ZSTD,
m48_cat_ea_number_of_donation INT ENCODE ZSTD,
m48_cat_et_number_of_donation INT ENCODE ZSTD,
m48_cat_hg_number_of_donation INT ENCODE ZSTD,
m48_cat_hs_number_of_donation INT ENCODE ZSTD,
m48_cat_rd_number_of_donation INT ENCODE ZSTD,
m48_cat_ri_number_of_donation INT ENCODE ZSTD,
m48_cat_li_number_of_donation INT ENCODE ZSTD,
m48_cat_nt_number_of_donation INT ENCODE ZSTD,
m48_cat_pa_number_of_donation INT ENCODE ZSTD,
m48_cat_rc_number_of_donation INT ENCODE ZSTD,
m48_cat_rj_number_of_donation INT ENCODE ZSTD,
m48_cat_ss_number_of_donation INT ENCODE ZSTD,
m48_cat_ve_number_of_donation INT ENCODE ZSTD,
m48_cat_sw_number_of_donation INT ENCODE AZ64,
m48_number_of_list_sources INT ENCODE ZSTD,
m48_total_number_of_donations INT ENCODE ZSTD,
m48_total_dollar_donations INT ENCODE ZSTD,
ltd_number_of_donations_0_3_months_ago INT ENCODE ZSTD,
ltd_number_of_donations_0_6_months_ago INT ENCODE ZSTD,
ltd_number_of_donations_0_12_months_ago INT ENCODE ZSTD,
ltd_number_of_donations_13_24_months_ago INT ENCODE ZSTD,
ltd_number_of_donations_over_24_months_ago INT ENCODE ZSTD
)
DISTSTYLE KEY
DISTKEY(cid)
SORTKEY(cid);

insert into tblchild34_{build_id}_{build}_int
(cid,
ap_id,
ap_lems,
company_id,
donormatch,
ltd_months_since_last_donation_date,
ltd_last_donation_date_yyyymm,
ltd_number_of_list_sources,
ltd_average_donation_per_transaction,
m12_number_of_list_sources,
m12_average_donation_per_transaction,
m12_cat_ac_number_of_donation,
m12_cat_an_number_of_donation,
m12_cat_cd_number_of_donation,
m12_cat_cg_number_of_donation,
m12_cat_ch_number_of_donation,
m12_cat_co_number_of_donation,
m12_cat_cs_number_of_donation,
m12_cat_ea_number_of_donation,
m12_cat_et_number_of_donation,
m12_cat_hg_number_of_donation,
m12_cat_hs_number_of_donation,
m12_cat_li_number_of_donation,
m12_cat_nt_number_of_donation,
m12_cat_pa_number_of_donation,
m12_cat_rc_number_of_donation,
m12_cat_rd_number_of_donation,
m12_cat_ri_number_of_donation,
m12_cat_rj_number_of_donation,
m12_cat_ss_number_of_donation,
m12_cat_sw_number_of_donation,
m12_cat_ve_number_of_donation,
m48_number_of_donation_dollar_cash,
m48_number_of_donation_dollar_check,
m48_cat_an_number_of_donation, 
m48_cat_ac_number_of_donation,
m48_cat_cd_number_of_donation,
m48_cat_cs_number_of_donation,
m48_cat_cg_number_of_donation,
m48_cat_ch_number_of_donation,
m48_cat_co_number_of_donation,
m48_cat_ea_number_of_donation,
m48_cat_et_number_of_donation,
m48_cat_hg_number_of_donation,
m48_cat_hs_number_of_donation,
m48_cat_rd_number_of_donation,
m48_cat_ri_number_of_donation,
m48_cat_li_number_of_donation,
m48_cat_nt_number_of_donation,
m48_cat_pa_number_of_donation,
m48_cat_rc_number_of_donation,
m48_cat_rj_number_of_donation,
m48_cat_ss_number_of_donation,
m48_cat_ve_number_of_donation,
m48_cat_sw_number_of_donation,
m48_number_of_list_sources,
m48_total_number_of_donations,
m48_total_dollar_donations,
ltd_number_of_donations_0_3_months_ago,
ltd_number_of_donations_0_6_months_ago,
ltd_number_of_donations_0_12_months_ago,
ltd_number_of_donations_13_24_months_ago,
ltd_number_of_donations_over_24_months_ago
)

select 
cid,
ap_id,
ap_lems,
case when company_id='' then 0 else cast (company_id as bigint ) end,
donormatch,
case when ltd_months_since_last_donation_date='' then 0 else cast (ltd_months_since_last_donation_date as integer) end,
ltd_last_donation_date_yyyymm,
case when ltd_number_of_list_sources='' then 0 else cast (ltd_number_of_list_sources as integer) end,
case when ltd_average_donation_per_transaction='' then 0 else cast (ltd_average_donation_per_transaction as integer) end,
case when m12_number_of_list_sources='' then 0 else cast (m12_number_of_list_sources as integer) end,
case when m12_average_donation_per_transaction='' then 0 else cast (m12_average_donation_per_transaction as integer) end,
case when m12_cat_ac_number_of_donation='' then 0 else cast (m12_cat_ac_number_of_donation as integer) end,
case when m12_cat_an_number_of_donation='' then 0 else cast (m12_cat_an_number_of_donation as integer) end,
case when m12_cat_cd_number_of_donation='' then 0 else cast (m12_cat_cd_number_of_donation as integer) end,
case when m12_cat_cg_number_of_donation='' then 0 else cast (m12_cat_cg_number_of_donation as integer) end,
case when m12_cat_ch_number_of_donation='' then 0 else cast (m12_cat_ch_number_of_donation as integer) end,
case when m12_cat_co_number_of_donation='' then 0 else cast (m12_cat_co_number_of_donation as integer) end,
case when m12_cat_cs_number_of_donation='' then 0 else cast (m12_cat_cs_number_of_donation as integer) end,
case when m12_cat_ea_number_of_donation='' then 0 else cast (m12_cat_ea_number_of_donation as integer) end,
case when m12_cat_et_number_of_donation='' then 0 else cast (m12_cat_et_number_of_donation as integer) end,
case when m12_cat_hg_number_of_donation='' then 0 else cast (m12_cat_hg_number_of_donation as integer) end,
case when m12_cat_hs_number_of_donation='' then 0 else cast (m12_cat_hs_number_of_donation as integer) end,
case when m12_cat_li_number_of_donation='' then 0 else cast (m12_cat_li_number_of_donation as integer) end,
case when m12_cat_nt_number_of_donation='' then 0 else cast (m12_cat_nt_number_of_donation as integer) end,
case when m12_cat_pa_number_of_donation='' then 0 else cast (m12_cat_pa_number_of_donation as integer) end,
case when m12_cat_rc_number_of_donation='' then 0 else cast (m12_cat_rc_number_of_donation as integer) end,
case when m12_cat_rd_number_of_donation='' then 0 else cast (m12_cat_rd_number_of_donation as integer) end,
case when m12_cat_ri_number_of_donation='' then 0 else cast (m12_cat_ri_number_of_donation as integer) end,
case when m12_cat_rj_number_of_donation='' then 0 else cast (m12_cat_rj_number_of_donation as integer) end,
case when m12_cat_ss_number_of_donation='' then 0 else cast (m12_cat_ss_number_of_donation as integer) end,
case when m12_cat_sw_number_of_donation='' then 0 else cast (m12_cat_sw_number_of_donation as integer) end,
case when m12_cat_ve_number_of_donation='' then 0 else cast (m12_cat_ve_number_of_donation as integer) end,
case when m48_number_of_donation_dollar_cash='' then 0 else cast (m48_number_of_donation_dollar_cash as integer) end,
case when m48_number_of_donation_dollar_check='' then 0 else cast (m48_number_of_donation_dollar_check as integer) end,
case when m48_cat_an_number_of_donation='' then 0 else cast (m48_cat_an_number_of_donation as integer) end, 
case when m48_cat_ac_number_of_donation='' then 0 else cast (m48_cat_ac_number_of_donation as integer) end,
case when m48_cat_cd_number_of_donation='' then 0 else cast (m48_cat_cd_number_of_donation as integer) end,
case when m48_cat_cs_number_of_donation='' then 0 else cast (m48_cat_cs_number_of_donation as integer) end,
case when m48_cat_cg_number_of_donation='' then 0 else cast (m48_cat_cg_number_of_donation as integer) end,
case when m48_cat_ch_number_of_donation='' then 0 else cast (m48_cat_ch_number_of_donation as integer) end,
case when m48_cat_co_number_of_donation='' then 0 else cast (m48_cat_co_number_of_donation as integer) end,
case when m48_cat_ea_number_of_donation='' then 0 else cast (m48_cat_ea_number_of_donation as integer) end,
case when m48_cat_et_number_of_donation='' then 0 else cast (m48_cat_et_number_of_donation as integer) end,
case when m48_cat_hg_number_of_donation='' then 0 else cast (m48_cat_hg_number_of_donation as integer) end,
case when m48_cat_hs_number_of_donation='' then 0 else cast (m48_cat_hs_number_of_donation as integer) end,
case when m48_cat_rd_number_of_donation='' then 0 else cast (m48_cat_rd_number_of_donation as integer) end,
case when m48_cat_ri_number_of_donation='' then 0 else cast (m48_cat_ri_number_of_donation as integer) end,
case when m48_cat_li_number_of_donation='' then 0 else cast (m48_cat_li_number_of_donation as integer) end,
case when m48_cat_nt_number_of_donation='' then 0 else cast (m48_cat_nt_number_of_donation as integer) end,
case when m48_cat_pa_number_of_donation='' then 0 else cast (m48_cat_pa_number_of_donation as integer) end,
case when m48_cat_rc_number_of_donation='' then 0 else cast (m48_cat_rc_number_of_donation as integer) end,
case when m48_cat_rj_number_of_donation='' then 0 else cast (m48_cat_rj_number_of_donation as integer) end,
case when m48_cat_ss_number_of_donation='' then 0 else cast (m48_cat_ss_number_of_donation as integer) end,
case when m48_cat_ve_number_of_donation='' then 0 else cast (m48_cat_ve_number_of_donation as integer) end,
case when m48_cat_sw_number_of_donation='' then 0 else cast (m48_cat_sw_number_of_donation as integer) end,
case when m48_number_of_list_sources='' then 0 else cast (m48_number_of_list_sources as integer) end,
case when m48_total_number_of_donations='' then 0 else cast (m48_total_number_of_donations as integer) end,
case when m48_total_dollar_donations='' then 0 else cast (m48_total_dollar_donations as integer) end,
case when ltd_number_of_donations_0_3_months_ago='' then 0 else cast (ltd_number_of_donations_0_3_months_ago as integer) end,
case when ltd_number_of_donations_0_6_months_ago='' then 0 else cast (ltd_number_of_donations_0_6_months_ago as integer) end,
case when ltd_number_of_donations_0_12_months_ago='' then 0 else cast (ltd_number_of_donations_0_12_months_ago as integer) end,
case when ltd_number_of_donations_13_24_months_ago='' then 0 else cast (ltd_number_of_donations_13_24_months_ago as integer) end,
case when ltd_number_of_donations_over_24_months_ago='' then 0 else cast (ltd_number_of_donations_over_24_months_ago as integer) end
from tblchild34_{build_id}_{build}_varchar;

drop table if exists tblchild34_{build_id}_{build} CASCADE;
alter table tblchild34_{build_id}_{build}_int rename to tblchild34_{build_id}_{build};


drop table if exists tblchild34_{build_id}_{build}_varchar;


UNLOAD ('select * from tblchild34_{build_id}_{build}')
TO 's3://{s3-axle-gold}/mgen/{s3_folder_today}/mgen-apogee/'
iam_role '{iam}'
manifest verbose
FORMAT PARQUET;