DROP TABLE IF Exists {tablename1};
CREATE TABLE {tablename1} 
(
    id INT IDENTITY ENCODE AZ64,
    lems VARCHAR(18) ENCODE ZSTD,
    last_transaction_overall_days INT ENCODE AZ64,
    tot_parts INT ENCODE AZ64,
    tot_dlrs_12m INT ENCODE ZSTD,
    tot_trns_12m INT ENCODE ZSTD,
    tot_dlrs_12m_avg INT ENCODE ZSTD,
    last_transaction_catalog_days INT ENCODE AZ64,
    cat_parts INT ENCODE AZ64,
    cat_dlrs_12m INT ENCODE ZSTD,
    cat_trns_12m INT ENCODE ZSTD,
    cat_dlrs_12m_avg INT ENCODE ZSTD,
    last_transaction_web_days INT ENCODE AZ64,
    web_parts INT ENCODE AZ64,
    web_dlrs_12m INT ENCODE ZSTD,
    web_trns_12m INT ENCODE ZSTD,
    last_transaction_retail_days INT ENCODE AZ64,
    rtl_parts INT ENCODE AZ64,
    rtl_dlrs_12m INT ENCODE ZSTD,
    rtl_trns_12m INT ENCODE ZSTD,
    recency_sc01_days INT ENCODE ZSTD,
    sc01_dlrs_12m INT ENCODE ZSTD,
    sc01_dlrs_12m_avg INT ENCODE ZSTD,
    sc01_trns_12m INT ENCODE ZSTD,
    sc01_trns_13p INT ENCODE ZSTD,
    recency_sc02_days INT ENCODE ZSTD,
    sc02_dlrs_12m INT ENCODE ZSTD,
    sc02_dlrs_12m_avg INT ENCODE ZSTD,
    sc02_trns_12m INT ENCODE ZSTD,
    recency_sc03_days INT ENCODE ZSTD,
    sc03_dlrs_12m INT ENCODE ZSTD,
    sc03_dlrs_12m_avg INT ENCODE ZSTD,
    sc03_trns_12m INT ENCODE ZSTD,
    sc03_trns_13p INT ENCODE ZSTD,
    recency_sc04_days INT ENCODE ZSTD,
    sc04_dlrs_12m INT ENCODE ZSTD,
    sc04_dlrs_12m_avg INT ENCODE ZSTD,
    sc04_trns_12m INT ENCODE ZSTD,
    recency_sc05_days INT ENCODE ZSTD,
    sc05_dlrs_12m INT ENCODE ZSTD,
    sc05_dlrs_12m_avg INT ENCODE ZSTD,
    sc05_trns_12m INT ENCODE ZSTD,
    recency_sc06_days INT ENCODE ZSTD,
    sc06_dlrs_12m INT ENCODE ZSTD,
    sc06_dlrs_12m_avg INT ENCODE ZSTD,
    sc06_trns_12m INT ENCODE ZSTD,
    recency_sc07_days INT ENCODE ZSTD,
    sc07_dlrs_12m INT ENCODE ZSTD,
    sc07_dlrs_12m_avg INT ENCODE ZSTD,
    sc07_trns_12m INT ENCODE ZSTD,
    recency_sc08_days INT ENCODE ZSTD,
    sc08_dlrs_12m INT ENCODE ZSTD,
    sc08_dlrs_12m_avg INT ENCODE ZSTD,
    sc08_trns_12m INT ENCODE ZSTD,
    recency_sc09_days INT ENCODE ZSTD,
    sc09_dlrs_12m INT ENCODE ZSTD,
    sc09_dlrs_12m_avg INT ENCODE ZSTD,
    sc09_trns_12m INT ENCODE ZSTD,
    recency_sc10_days INT ENCODE ZSTD,
    sc10_dlrs_12m INT ENCODE ZSTD,
    sc10_dlrs_12m_avg INT ENCODE ZSTD,
    sc10_trns_12m INT ENCODE ZSTD,
    recency_sc11_days INT ENCODE ZSTD,
    sc11_dlrs_12m INT ENCODE ZSTD,
    sc11_dlrs_12m_avg INT ENCODE ZSTD,
    sc11_trns_12m INT ENCODE ZSTD,
    recency_sc12_days INT ENCODE ZSTD,
    sc12_dlrs_12m INT ENCODE ZSTD,
    sc12_dlrs_12m_avg INT ENCODE ZSTD,
    sc12_trns_12m INT ENCODE ZSTD,
    recency_sc13_days INT ENCODE ZSTD,
    sc13_dlrs_12m INT ENCODE ZSTD,
    sc13_dlrs_12m_avg INT ENCODE ZSTD,
    sc13_trns_12m INT ENCODE ZSTD,
    recency_sc14_days INT ENCODE ZSTD,
    sc14_dlrs_12m INT ENCODE ZSTD,
    sc14_trns_12m INT ENCODE ZSTD,
    recency_sc15_days INT ENCODE ZSTD,
    sc15_dlrs_12m INT ENCODE ZSTD,
    sc15_trns_12m INT ENCODE ZSTD,
    recency_sc16_days INT ENCODE ZSTD,
    sc16_dlrs_12m INT ENCODE ZSTD,
    sc16_dlrs_12m_avg INT ENCODE ZSTD,
    sc16_trns_12m INT ENCODE ZSTD,
    recency_sc17_days INT ENCODE ZSTD,
    sc17_dlrs_12m INT ENCODE ZSTD,
    sc17_dlrs_12m_avg INT ENCODE ZSTD,
    sc17_trns_12m INT ENCODE ZSTD,
    recency_sc18_days INT ENCODE ZSTD,
    sc18_dlrs_12m INT ENCODE ZSTD,
    sc18_trns_12m INT ENCODE ZSTD,
    recency_sc19_days INT ENCODE ZSTD,
    sc19_dlrs_12m INT ENCODE ZSTD,
    sc19_trns_12m INT ENCODE ZSTD,
    recency_sc20_days INT ENCODE ZSTD,
    sc20_dlrs_12m INT ENCODE ZSTD,
    sc20_trns_12m INT ENCODE ZSTD,
    sc20_trns_13p INT ENCODE ZSTD,
    recency_sc21_days INT ENCODE ZSTD,
    sc21_dlrs_12m INT ENCODE ZSTD,
    sc21_trns_12m INT ENCODE ZSTD,
    recency_sc22_days INT ENCODE ZSTD,
    sc22_dlrs_12m INT ENCODE ZSTD,
    sc22_trns_12m INT ENCODE ZSTD,
    recency_002_days INT ENCODE ZSTD,
    recency_003_days INT ENCODE ZSTD,
    recency_007_days INT ENCODE ZSTD,
    recency_008_days INT ENCODE ZSTD,
    recency_013_days INT ENCODE ZSTD,
    recency_016_days INT ENCODE ZSTD,
    recency_018_days INT ENCODE ZSTD,
    recency_019_days INT ENCODE ZSTD,
    recency_020_days INT ENCODE ZSTD,
    recency_021_days INT ENCODE ZSTD,
    recency_026_days INT ENCODE ZSTD,
    recency_027_days INT ENCODE ZSTD,
    recency_042_days INT ENCODE ZSTD,
    recency_043_days INT ENCODE ZSTD,
    recency_045_days INT ENCODE ZSTD,
    recency_046_days INT ENCODE ZSTD,
    recency_047_days INT ENCODE ZSTD,
    recency_066_days INT ENCODE ZSTD,
    recency_079_days INT ENCODE ZSTD,
    recency_091_days INT ENCODE ZSTD,
    recency_092_days INT ENCODE ZSTD,
    recency_100_days INT ENCODE ZSTD,
    recency_109_days INT ENCODE ZSTD,
    recency_110_days INT ENCODE ZSTD,
    recency_111_days INT ENCODE ZSTD,
    recency_119_days INT ENCODE ZSTD,
    recency_122_days INT ENCODE ZSTD,
    recency_128_days INT ENCODE ZSTD,
    recency_129_days INT ENCODE ZSTD,
    PRIMARY KEY(lems)
)
DISTSTYLE KEY
DISTKEY(lems)
SORTKEY(lems);


INSERT INTO {tablename1}
(
	lems,
	Last_Transaction_Overall_Days,
	TOT_PARTS,
	TOT_DLRS_12M,
	TOT_TRNS_12M,
	tot_dlrs_12m_avg,
	Last_Transaction_Catalog_Days,
	CAT_PARTS,
	CAT_DLRS_12M,
	CAT_TRNS_12M,
	cat_dlrs_12m_avg,
	Last_Transaction_Web_Days,
	WEB_PARTS,
	WEB_DLRS_12M,
	WEB_TRNS_12M,
	Last_Transaction_Retail_Days,
	RTL_PARTS,
	RTL_DLRS_12M,
	RTL_TRNS_12M,
	Recency_SC01_Days,
	SC01_DLRS_12M,
	sc01_dlrs_12m_avg,
	SC01_TRNS_12M,
	SC01_TRNS_13P,
	Recency_SC02_Days,
	SC02_DLRS_12M,
	sc02_dlrs_12m_avg,
	SC02_TRNS_12M,
	Recency_SC03_Days,
	SC03_DLRS_12M,
	sc03_dlrs_12m_avg,
	SC03_TRNS_12M,
	SC03_TRNS_13P,
	Recency_SC04_Days,
	SC04_DLRS_12M,
	sc04_dlrs_12m_avg,
	SC04_TRNS_12M,
	Recency_SC05_Days,
	SC05_DLRS_12M,
	sc05_dlrs_12m_avg,
	SC05_TRNS_12M,
	Recency_SC06_Days,
	SC06_DLRS_12M,
	sc06_dlrs_12m_avg,
	SC06_TRNS_12M,
	Recency_SC07_Days,
	SC07_DLRS_12M,
	sc07_dlrs_12m_avg,
	SC07_TRNS_12M,
	Recency_SC08_Days,
	SC08_DLRS_12M,
	sc08_dlrs_12m_avg,
	SC08_TRNS_12M,
	Recency_SC09_Days,
	SC09_DLRS_12M,
	sc09_dlrs_12m_avg,
	SC09_TRNS_12M,
	Recency_SC10_Days,
	SC10_DLRS_12M,
	sc10_dlrs_12m_avg,
	SC10_TRNS_12M,
	Recency_SC11_Days,
	SC11_DLRS_12M,
	sc11_dlrs_12m_avg,
	SC11_TRNS_12M,
	Recency_SC12_Days,
	SC12_DLRS_12M,
	sc12_dlrs_12m_avg,
	SC12_TRNS_12M,
	Recency_SC13_Days,
	SC13_DLRS_12M,
	sc13_dlrs_12m_avg,
	SC13_TRNS_12M,
	Recency_SC14_Days,
	SC14_DLRS_12M,
	SC14_TRNS_12M,
	Recency_SC15_Days,
	SC15_DLRS_12M,
	SC15_TRNS_12M,
	Recency_SC16_Days,
	SC16_DLRS_12M,
	sc16_dlrs_12m_avg,
	SC16_TRNS_12M,
	Recency_SC17_Days,
	SC17_DLRS_12M,
	sc17_dlrs_12m_avg,
	SC17_TRNS_12M,
	Recency_SC18_Days,
	SC18_DLRS_12M,
	SC18_TRNS_12M,
	Recency_SC19_Days,
	SC19_DLRS_12M,
	SC19_TRNS_12M,
	Recency_SC20_Days,
	SC20_DLRS_12M,
	SC20_TRNS_12M,
	SC20_TRNS_13P,
	Recency_SC21_Days,
	SC21_DLRS_12M,
	SC21_TRNS_12M,
	Recency_SC22_Days,
	SC22_DLRS_12M,
	SC22_TRNS_12M,
	Recency_002_Days,
	Recency_003_Days,
	Recency_007_Days,
	Recency_008_Days,
	Recency_013_Days,
	Recency_016_Days,
	Recency_018_Days,
	Recency_019_Days,
	Recency_020_Days,
	Recency_021_Days,
	Recency_026_Days,
	Recency_027_Days,
	Recency_042_Days,
	Recency_043_Days,
	Recency_045_Days,
	Recency_046_Days,
	Recency_047_Days,
	Recency_066_Days,
	Recency_079_Days,
	Recency_091_Days,
	Recency_092_Days,
	Recency_100_Days,
	Recency_109_Days,
	Recency_110_Days,
	Recency_111_Days,
	Recency_119_Days,
	Recency_122_Days,
	Recency_128_Days,
	Recency_129_Days
)
SELECT  
	lems,
	CASE when Last_Transaction_Overall_Days= '' then 0 ELSE CAST (Last_Transaction_Overall_Days as INTEGER) END,
	CASE when TOT_PARTS = '' then 0 ELSE CAST (TOT_PARTS as INTEGER) END,
	CASE when TOT_DLRS_12M = '' then 0 ELSE CAST (TOT_DLRS_12M as INTEGER) END,
	CASE when TOT_TRNS_12M = '' then 0 ELSE CAST (TOT_TRNS_12M as INTEGER) END,
	CASE when tot_dlrs_12m_avg = '' then 0 ELSE CAST (tot_dlrs_12m_avg as INTEGER) END,
	CASE when Last_Transaction_Catalog_Days = '' then 0 ELSE CAST (Last_Transaction_Catalog_Days as INTEGER) END,
	CASE when CAT_PARTS = '' then 0 ELSE CAST (CAT_PARTS as INTEGER) END,
	CASE when CAT_DLRS_12M = '' then 0 ELSE CAST (CAT_DLRS_12M as INTEGER) END,
	CASE when CAT_TRNS_12M = '' then 0 ELSE CAST (CAT_TRNS_12M as INTEGER) END,
	CASE when cat_dlrs_12m_avg = '' then 0 ELSE CAST (cat_dlrs_12m_avg as INTEGER) END,
	CASE when Last_Transaction_Web_Days = '' then 0 ELSE CAST (Last_Transaction_Web_Days as INTEGER) END,
	CASE when WEB_PARTS = '' then 0 ELSE CAST (WEB_PARTS as INTEGER) END,
	CASE when WEB_DLRS_12M = '' then 0 ELSE CAST (WEB_DLRS_12M as INTEGER) END,
	CASE when WEB_TRNS_12M = '' then 0 ELSE CAST (WEB_TRNS_12M as INTEGER) END,
	CASE when Last_Transaction_Retail_Days = '' then 0 ELSE CAST (Last_Transaction_Retail_Days as INTEGER) END,
	CASE when RTL_PARTS = '' then 0 ELSE CAST (RTL_PARTS as INTEGER) END,
	CASE when RTL_DLRS_12M = '' then 0 ELSE CAST (RTL_DLRS_12M as INTEGER) END,
	CASE when RTL_TRNS_12M = '' then 0 ELSE CAST (RTL_TRNS_12M as INTEGER) END,
	CASE when Recency_SC01_Days = '' then 0 ELSE CAST (Recency_SC01_Days as INTEGER) END,
	CASE when SC01_DLRS_12M = '' then 0 ELSE CAST (SC01_DLRS_12M as INTEGER) END,
	CASE when sc01_dlrs_12m_avg = '' then 0 ELSE CAST (sc01_dlrs_12m_avg as INTEGER) END,
	CASE when SC01_TRNS_12M = '' then 0 ELSE CAST (SC01_TRNS_12M as INTEGER) END,
	CASE when SC01_TRNS_13P = '' then 0 ELSE CAST (SC01_TRNS_13P as INTEGER) END,
	CASE when Recency_SC02_Days = '' then 0 ELSE CAST (Recency_SC02_Days as INTEGER) END,
	CASE when SC02_DLRS_12M = '' then 0 ELSE CAST (SC02_DLRS_12M as INTEGER) END,
	CASE when sc02_dlrs_12m_avg = '' then 0 ELSE CAST (sc02_dlrs_12m_avg as INTEGER) END,
	CASE when SC02_TRNS_12M = '' then 0 ELSE CAST (SC02_TRNS_12M as INTEGER) END,
	CASE when Recency_SC03_Days = '' then 0 ELSE CAST (Recency_SC03_Days as INTEGER) END,
	CASE when SC03_DLRS_12M = '' then 0 ELSE CAST (SC03_DLRS_12M as INTEGER) END,
	CASE when sc03_dlrs_12m_avg = '' then 0 ELSE CAST (sc03_dlrs_12m_avg as INTEGER) END,
	CASE when SC03_TRNS_12M = '' then 0 ELSE CAST (SC03_TRNS_12M as INTEGER) END,
	CASE when SC03_TRNS_13P = '' then 0 ELSE CAST (SC03_TRNS_13P as INTEGER) END,
	CASE when Recency_SC04_Days = '' then 0 ELSE CAST (Recency_SC04_Days as INTEGER) END,
	CASE when SC04_DLRS_12M = '' then 0 ELSE CAST (SC04_DLRS_12M as INTEGER) END,
	CASE when sc04_dlrs_12m_avg = '' then 0 ELSE CAST (sc04_dlrs_12m_avg as INTEGER) END,
	CASE when SC04_TRNS_12M = '' then 0 ELSE CAST (SC04_TRNS_12M as INTEGER) END,
	CASE when Recency_SC05_Days = '' then 0 ELSE CAST (Recency_SC05_Days as INTEGER) END,
	CASE when SC05_DLRS_12M = '' then 0 ELSE CAST (SC05_DLRS_12M as INTEGER) END,
	CASE when sc05_dlrs_12m_avg = '' then 0 ELSE CAST (sc05_dlrs_12m_avg as INTEGER) END,
	CASE when SC05_TRNS_12M = '' then 0 ELSE CAST (SC05_TRNS_12M as INTEGER) END,
	CASE when Recency_SC06_Days = '' then 0 ELSE CAST (Recency_SC06_Days as INTEGER) END,
	CASE when SC06_DLRS_12M = '' then 0 ELSE CAST (SC06_DLRS_12M as INTEGER) END,
	CASE when sc06_dlrs_12m_avg = '' then 0 ELSE CAST (sc06_dlrs_12m_avg as INTEGER) END,
	CASE when SC06_TRNS_12M = '' then 0 ELSE CAST (SC06_TRNS_12M as INTEGER) END,
	CASE when Recency_SC07_Days = '' then 0 ELSE CAST (Recency_SC07_Days as INTEGER) END,
	CASE when SC07_DLRS_12M = '' then 0 ELSE CAST (SC07_DLRS_12M as INTEGER) END,
	CASE when sc07_dlrs_12m_avg = '' then 0 ELSE CAST (sc07_dlrs_12m_avg as INTEGER) END,
	CASE when SC07_TRNS_12M = '' then 0 ELSE CAST (SC07_TRNS_12M as INTEGER) END,
	CASE when Recency_SC08_Days = '' then 0 ELSE CAST (Recency_SC08_Days as INTEGER) END,
	CASE when SC08_DLRS_12M = '' then 0 ELSE CAST (SC08_DLRS_12M as INTEGER) END,
	CASE when sc08_dlrs_12m_avg = '' then 0 ELSE CAST (sc08_dlrs_12m_avg as INTEGER) END,
	CASE when SC08_TRNS_12M = '' then 0 ELSE CAST (SC08_TRNS_12M as INTEGER) END,
	CASE when Recency_SC09_Days = '' then 0 ELSE CAST (Recency_SC09_Days as INTEGER) END,
	CASE when SC09_DLRS_12M = '' then 0 ELSE CAST (SC09_DLRS_12M as INTEGER) END,
	CASE when sc09_dlrs_12m_avg = '' then 0 ELSE CAST (sc09_dlrs_12m_avg as INTEGER) END,
	CASE when SC09_TRNS_12M = '' then 0 ELSE CAST (SC09_TRNS_12M as INTEGER) END,
	CASE when Recency_SC10_Days = '' then 0 ELSE CAST (Recency_SC10_Days as INTEGER) END,
	CASE when SC10_DLRS_12M = '' then 0 ELSE CAST (SC10_DLRS_12M as INTEGER) END,
	CASE when sc10_dlrs_12m_avg = '' then 0 ELSE CAST (sc10_dlrs_12m_avg as INTEGER) END,
	CASE when SC10_TRNS_12M = '' then 0 ELSE CAST (SC10_TRNS_12M as INTEGER) END,
	CASE when Recency_SC11_Days = '' then 0 ELSE CAST (Recency_SC11_Days as INTEGER) END,
	CASE when SC11_DLRS_12M = '' then 0 ELSE CAST (SC11_DLRS_12M as INTEGER) END,
	CASE when sc11_dlrs_12m_avg = '' then 0 ELSE CAST (sc11_dlrs_12m_avg as INTEGER) END,
	CASE when SC11_TRNS_12M = '' then 0 ELSE CAST (SC11_TRNS_12M as INTEGER) END,
	CASE when Recency_SC12_Days = '' then 0 ELSE CAST (Recency_SC12_Days as INTEGER) END,
	CASE when SC12_DLRS_12M = '' then 0 ELSE CAST (SC12_DLRS_12M as INTEGER) END,
	CASE when sc12_dlrs_12m_avg = '' then 0 ELSE CAST (sc12_dlrs_12m_avg as INTEGER) END,
	CASE when SC12_TRNS_12M = '' then 0 ELSE CAST (SC12_TRNS_12M as INTEGER) END,
	CASE when Recency_SC13_Days = '' then 0 ELSE CAST (Recency_SC13_Days as INTEGER) END,
	CASE when SC13_DLRS_12M = '' then 0 ELSE CAST (SC13_DLRS_12M as INTEGER) END,
	CASE when sc13_dlrs_12m_avg = '' then 0 ELSE CAST (sc13_dlrs_12m_avg as INTEGER) END,
	CASE when SC13_TRNS_12M = '' then 0 ELSE CAST (SC13_TRNS_12M as INTEGER) END,
	CASE when Recency_SC14_Days = '' then 0 ELSE CAST (Recency_SC14_Days as INTEGER) END,
	CASE when SC14_DLRS_12M = '' then 0 ELSE CAST (SC14_DLRS_12M as INTEGER) END,
	CASE when SC14_TRNS_12M = '' then 0 ELSE CAST (SC14_TRNS_12M as INTEGER) END,
	CASE when Recency_SC15_Days = '' then 0 ELSE CAST (Recency_SC15_Days as INTEGER) END,
	CASE when SC15_DLRS_12M = '' then 0 ELSE CAST (SC15_DLRS_12M as INTEGER) END,
	CASE when SC15_TRNS_12M = '' then 0 ELSE CAST (SC15_TRNS_12M as INTEGER) END,
	CASE when Recency_SC16_Days = '' then 0 ELSE CAST (Recency_SC16_Days as INTEGER) END,
	CASE when SC16_DLRS_12M = '' then 0 ELSE CAST (SC16_DLRS_12M as INTEGER) END,
	CASE when sc16_dlrs_12m_avg = '' then 0 ELSE CAST (sc16_dlrs_12m_avg as INTEGER) END,
	CASE when SC16_TRNS_12M = '' then 0 ELSE CAST (SC16_TRNS_12M as INTEGER) END,
	CASE when Recency_SC17_Days = '' then 0 ELSE CAST (Recency_SC17_Days as INTEGER) END,
	CASE when SC17_DLRS_12M = '' then 0 ELSE CAST (SC17_DLRS_12M as INTEGER) END,
	CASE when sc17_dlrs_12m_avg = '' then 0 ELSE CAST (sc17_dlrs_12m_avg as INTEGER) END,
	CASE when SC17_TRNS_12M = '' then 0 ELSE CAST (SC17_TRNS_12M as INTEGER) END,
	CASE when Recency_SC18_Days = '' then 0 ELSE CAST (Recency_SC18_Days as INTEGER) END,
	CASE when SC18_DLRS_12M = '' then 0 ELSE CAST (SC18_DLRS_12M as INTEGER) END,
	CASE when SC18_TRNS_12M = '' then 0 ELSE CAST (SC18_TRNS_12M as INTEGER) END,
	CASE when Recency_SC19_Days = '' then 0 ELSE CAST (Recency_SC19_Days as INTEGER) END,
	CASE when SC19_DLRS_12M = '' then 0 ELSE CAST (SC19_DLRS_12M as INTEGER) END,
	CASE when SC19_TRNS_12M = '' then 0 ELSE CAST (SC19_TRNS_12M as INTEGER) END,
	CASE when Recency_SC20_Days = '' then 0 ELSE CAST (Recency_SC20_Days as INTEGER) END,
	CASE when SC20_DLRS_12M = '' then 0 ELSE CAST (SC20_DLRS_12M as INTEGER) END,
	CASE when SC20_TRNS_12M = '' then 0 ELSE CAST (SC20_TRNS_12M as INTEGER) END,
	CASE when SC20_TRNS_13P = '' then 0 ELSE CAST (SC20_TRNS_13P as INTEGER) END,
	CASE when Recency_SC21_Days = '' then 0 ELSE CAST (Recency_SC21_Days as INTEGER) END,
	CASE when SC21_DLRS_12M = '' then 0 ELSE CAST (SC21_DLRS_12M as INTEGER) END,
	CASE when SC21_TRNS_12M = '' then 0 ELSE CAST (SC21_TRNS_12M as INTEGER) END,
	CASE when Recency_SC22_Days = '' then 0 ELSE CAST (Recency_SC22_Days as INTEGER) END,
	CASE when SC22_DLRS_12M = '' then 0 ELSE CAST (SC22_DLRS_12M as INTEGER) END,
	CASE when SC22_TRNS_12M = '' then 0 ELSE CAST (SC22_TRNS_12M as INTEGER) END,
	CASE when Recency_002_Days = '' then 0 ELSE CAST (Recency_002_Days as INTEGER) END,
	CASE when Recency_003_Days = '' then 0 ELSE CAST (Recency_003_Days as INTEGER) END,
	CASE when Recency_007_Days = '' then 0 ELSE CAST (Recency_007_Days as INTEGER) END,
	CASE when Recency_008_Days = '' then 0 ELSE CAST (Recency_008_Days as INTEGER) END,
	CASE when Recency_013_Days = '' then 0 ELSE CAST (Recency_013_Days as INTEGER) END,
	CASE when Recency_016_Days = '' then 0 ELSE CAST (Recency_016_Days as INTEGER) END,
	CASE when Recency_018_Days = '' then 0 ELSE CAST (Recency_018_Days as INTEGER) END,
	CASE when Recency_019_Days = '' then 0 ELSE CAST (Recency_019_Days as INTEGER) END,
	CASE when Recency_020_Days = '' then 0 ELSE CAST (Recency_020_Days as INTEGER) END,
	CASE when Recency_021_Days = '' then 0 ELSE CAST (Recency_021_Days as INTEGER) END,
	CASE when Recency_026_Days = '' then 0 ELSE CAST (Recency_026_Days as INTEGER) END,
	CASE when Recency_027_Days = '' then 0 ELSE CAST (Recency_027_Days as INTEGER) END,
	CASE when Recency_042_Days = '' then 0 ELSE CAST (Recency_042_Days as INTEGER) END,
	CASE when Recency_043_Days = '' then 0 ELSE CAST (Recency_043_Days as INTEGER) END,
	CASE when Recency_045_Days = '' then 0 ELSE CAST (Recency_045_Days as INTEGER) END,
	CASE when Recency_046_Days = '' then 0 ELSE CAST (Recency_046_Days as INTEGER) END,
	CASE when Recency_047_Days = '' then 0 ELSE CAST (Recency_047_Days as INTEGER) END,
	CASE when Recency_066_Days = '' then 0 ELSE CAST (Recency_066_Days as INTEGER) END,
	CASE when Recency_079_Days = '' then 0 ELSE CAST (Recency_079_Days as INTEGER) END,
	CASE when Recency_091_Days = '' then 0 ELSE CAST (Recency_091_Days as INTEGER) END,
	CASE when Recency_092_Days = '' then 0 ELSE CAST (Recency_092_Days as INTEGER) END,
	CASE when Recency_100_Days = '' then 0 ELSE CAST (Recency_100_Days as INTEGER) END,
	CASE when Recency_109_Days = '' then 0 ELSE CAST (Recency_109_Days as INTEGER) END,
	CASE when Recency_110_Days = '' then 0 ELSE CAST (Recency_110_Days as INTEGER) END,
	CASE when Recency_111_Days = '' then 0 ELSE CAST (Recency_111_Days as INTEGER) END,
	CASE when Recency_119_Days = '' then 0 ELSE CAST (Recency_119_Days as INTEGER) END,
	CASE when Recency_122_Days = '' then 0 ELSE CAST (Recency_122_Days as INTEGER) END,
	CASE when Recency_128_Days = '' then 0 ELSE CAST (Recency_128_Days as INTEGER) END,
	CASE when Recency_129_Days = '' then 0 ELSE CAST (Recency_129_Days as INTEGER) END 
FROM {tablename2}; 


/* Delete Blank Lems. Incident# 717686*/

DELETE FROM {tablename1} WHERE LTRIM(RTRIM(lems)) = '' OR lems IS NULL; 


--Final step
/*This part is moved to Another Job
alter table tblExternal1_191_201206  RENAME old_tblExternal1_191_201206;
alter table tblExternal1_191_201206_Int  RENAME tblExternal1_191_201206;

DROP TABLE IF EXISTS tblExternal1_191_201206_VARCHAR;



*/