/*
call sp_suppress_spamgarbageemails ('tblMain_20610_202011');

Reju Mathew 2021.1.26  Jira: Jira 626
created as SP on 2021.03.02

*/


CREATE OR REPLACE PROCEDURE sp_suppress_spamgarbageemails (cTablename  IN VARCHAR(200))
AS $$
DECLARE
  strSQL VARCHAR(max) ;
  intRowcount int;

BEGIN
  strSQL = ' UPDATE  {tblMain}
	 SET cInclude =''S''
	 from {tblMain}  A
	 WHERE cInclude IN (''Y'',''M'')
	 AND (UPPER(EMAILADDRESS) LIKE ''%ABUSE@%''  OR
	         UPPER(EMAILADDRESS) LIKE ''123@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''1234@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%@123.COM'' OR
	         UPPER(EMAILADDRESS) LIKE ''%@1234.COM'' OR
	         UPPER(EMAILADDRESS) LIKE ''ABC@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%ADMIN@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%ADMINISTRATOR@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%ANTISPAM%'' OR
	         UPPER(EMAILADDRESS) LIKE ''ASDF@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%@ASDF.COM'' OR
	         UPPER(EMAILADDRESS) LIKE ''BULK@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''BULKFOLDER@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''BULKMAIL@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%CONTACT@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%@FLEETWOODASD.K12.PA.US'' OR
	         UPPER(EMAILADDRESS) LIKE ''FTP@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''GARBAGE@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''HELP%'' OR
	         UPPER(EMAILADDRESS) LIKE ''HOSTMASTER@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''HR@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%INFO@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%JUNK%'' OR
	         UPPER(EMAILADDRESS) LIKE ''MAILADMIN@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''MARKETING@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NEWS@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NO@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NOBODY@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NOC@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%NOEMAIL%@'' OR
	         UPPER(EMAILADDRESS) LIKE ''NOMAIL@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NONE@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NOPE@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%NOREPLY@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%NO_SPAM%@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%NOSPAM%@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%NO-SPAM%@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NOT@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NOTHANKS@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''NOWAY@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''POSTMASTER%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%POSTMASTER@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''PRIVACY%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%PRIVACY@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%REPLY%@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%SALES@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%@SINA.COM'' OR
	         UPPER(EMAILADDRESS) LIKE ''SECURITY@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%SPAM%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%SPAMCOP%'' OR
	         UPPER(EMAILADDRESS) LIKE ''SUPPORT@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%SUPPORT@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''SYSADMIN@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''TRASH@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''USENET@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''UUCP@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''WEBADMIN@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%WEBADMIN@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''WEBMASTER%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%WEBMASTER@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''WWW@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''XXX@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%@XXX.COM'' OR
	         UPPER(EMAILADDRESS) LIKE ''XYZ@%'' OR
	         UPPER(EMAILADDRESS) LIKE ''%@XYZ.COM''  );  '  ;

  strSQL = replace(strSQL, '{tblMain}', cTablename);

  --RAISE INFO 'strsql: %  ', strSQL;
  EXECUTE strSQL	;

END;
$$ LANGUAGE plpgsql;
/




