/*  Reju Mathew  2021.01.26  Jira 626. copied from transformer*/
create or replace function  udf_fixcountryname(countryname varchar(500), statecode varchar(500))
returns varchar(500)
stable
as $$
    STATE_ABBREVIATION_BY_NAME = {
    'ALABAMA':                             'AL',
    'ALASKA':                              'AK',
    'ARIZONA':                             'AZ',
    'ARKANSAS':                            'AR',
    'CALIFORNIA':                          'CA',
    'COLORADO':                            'CO',
    'CONNECTICUT':                         'CT',
    'DELAWARE':                            'DE',
    'DISTRICTOFCOLUMBIA':                  'DC',
    'FLORIDA':                             'FL',
    'GEORGIA':                             'GA',
    'HAWAII':                              'HI',
    'IDAHO':                               'ID',
    'ILLINOIS':                            'IL',
    'INDIANA':                             'IN',
    'IOWA':                                'IA',
    'KANSAS':                              'KS',
    'KENTUCKY':                            'KY',
    'LOUISIANA':                           'LA',
    'MAINE':                               'ME',
    'MARYLAND':                            'MD',
    'MASSACHUSETTS':                       'MA',
    'MICHIGAN':                            'MI',
    'MINNESOTA':                           'MN',
    'MISSISSIPPI':                         'MS',
    'MISSOURI':                            'MO',
    'MONTANA':                             'MT',
    'NEBRASKA':                            'NE',
    'NEVADA':                              'NV',
    'NEWHAMPSHIRE':                        'NH',
    'NEWJERSEY':                           'NJ',
    'NEWMEXICO':                           'NM',
    'NEWYORK':                             'NY',
    'NORTHCAROLINA':                       'NC',
    'NORTHDAKOTA':                         'ND',
    'OHIO':                                'OH',
    'OKLAHOMA':                            'OK',
    'OREGON':                              'OR',
    'PENNSYLVANIA':                        'PA',
    'RHODEISLAND':                         'RI',
    'SOUTHCAROLINA':                       'SC',
    'SOUTHDAKOTA':                         'SD',
    'TENNESSEE':                           'TN',
    'TEXAS':                               'TX',
    'UTAH':                                'UT',
    'VERMONT':                             'VT',
    'VIRGINISLANDS':                       'VI',
    'VIRGINIA':                            'VA',
    'WASHINGTON':                          'WA',
    'WESTVIRGINIA':                        'WV',
    'WISCONSIN':                           'WI',
    'WYOMING':                             'WY',
    'ALBERTA':                             'AB',
    'NOVASCOTIA':                          'NS',
    'BRITISHCOLUMBIA':                     'BC',
    'ONTARIO':                             'ON',
    'MANITOBA':                            'MB',
    'PRINCEEDWARDISLAND':                  'PE',
    'NEWBRUNSWICK':                        'NB',
    'QUEBEC':                              'QC',
    'NEWFOUNDLAND':                        'NF',
    'SASKATCHEWAN':                        'SK',
    'NORTHWESTTERRITORIES':                'NT',
    'YUKONTERRITORY':                      'YT',
    'NUNAVUT':                             'NU',
    'AMERICANSAMOA':                       'AS',
    'GUAM':                                'GU',
    'MARSHALLISLANDS':                     'MH',
    'MICRONESIA':                          'FM',
    '(FEDERATEDSTATESOF)PALAU':            'PW',
    'PUERTORICO':                          'PR',
    'U.S.MINOROUTLYINGISLANDS':            'XX',
    'NORTHERNMARIANAISLANDS':              'MP',
    'ARMEDFORCESAFRICA':                   'AE',
    'ARMEDFORCESAMERICASAA(EXCEPTCANADA)': 'AA',
    'ARMEDFORCESCANADA':                   'AE',
    'ARMEDFORCESEUROPEAE':                 'AE',
    'ARMEDFORCESMIDDLEEASTAE':             'AE',
    'ARMEDFORCESPACIFICAP':                'AP',
    'FOREIGNOTHERNOTLISTEDABOVE':          'XX',
}

    COUNTRY_ALIASES = [
        [['USA'], 'USA'],
        [['Canada'], 'CANADA'],
        [['ADMIRALTY ISLANDS'], 'ADMIRALTY ISLANDS'],
        [['AFGHANISTAN'], 'AFGHANISTAN'],
        [['AFRICA'], 'AFRICA'],
        [['ALBANIA'], 'ALBANIA'],
        [['ALGERIA', 'Alg?rie', 'Algérie'], 'ALGERIA'],
        [['AMERICAN SAMOA'], 'AMERICAN SAMOA'],
        [['ANDAMAN/NICOBAR IS.', 'ANDAMAN/NICOBAR ISLANDS', 'ANDAMANNICOBAR'], 'ANDAMAN NICOBAR ISLANDS'],
        [['ANDORRA'], 'ANDORRA'],
        [['CABINDA'], 'ANGOLA'],
        [['ANGOLA'], 'ANGOLA'],
        [['ANGUILLA'], 'ANGUILLA'],
        [['ANTARCTICA'], 'ANTARCTICA'],
        [['ANTIGUA', 'ANTIGUA & BARBUDA', 'ANTIGUA AND BARBUDA'], 'ANTIGUA BARBUDA'],
        [['ARGENTINA', 'Argentine', 'republica argentina'], 'ARGENTINA'],
        [['ARMENIA'], 'ARMENIA'],
        [['ARUBA'], 'ARUBA'],
        [['ASCENSION ISLAND'], 'ASCENSION ISLAND'],
        [['AUSTRALIA', 'AUSTRALIYA', 'AUSTRAILIA', 'AUSTRILIA', 'NSW Australia', 'Queensland', 'Victoria',
          'Victoria Australia 3134', 'Western Australia', 'TASMANIA'], 'AUSTRALIA'],
        [['AUSTRIA', 'ASUTRIA', 'AUTRICHE', 'AUSRTIA'], 'AUSTRIA'],
        [['AZERBAIJAN'], 'AZERBAIJAN'],
        [['AZORES'], 'AZORES'],
        [['BAHAMAS', 'NASSAU', 'THE BAHAMAS', 'GREAT EXUMA', 'Bahama', 'Bahamas The', 'Bahamas, The'], 'BAHAMAS'],
        [['BAHRAIN'], 'BAHRAIN'],
        [['BALEARIC ISLANDS'], 'BALEARIC ISLANDS'],
        [['BANGLADESH'], 'BANGLADESH'],
        [['BARBADOS'], 'BARBADOS'],
        [['BELARUS', 'Belarus (Bielorussie)'], 'BELARUS'],
        [['BELGIUM', 'ZWIJNAARDE', 'BELGUIM', 'Belgique'], 'BELGIUM'],
        [['BELIZE'], 'BELIZE'],
        [['BENIN', 'Bénin'], 'BENIN'],
        [['BERMUDA'], 'BERMUDA'],
        [['BHUTAN'], 'BHUTAN'],
        [['BOLIVIA', 'BOLVIA'], 'BOLIVIA'],
        [['BOSNIA', 'BOSNIA & HERZEGOVINA', 'BOSNIA AND HERZ', 'BOSNIA AND HERZEGOVINA', 'BOSNIA-HERCEGOVINA'],
         'BOSNIA HERZGOVINA'],
        [['BOTSWANA'], 'BOTSWANA'],
        [['BOUVET ISLAND'], 'BOUVET ISLAND'],
        [['BRAZIL', 'BRASIL'], 'BRAZIL'],
        [['BRITAIN'], 'BRITAIN'],
        [['BRISTISH ISLES', 'BRITISH ISLES'], 'BRITISH ISLES'],
        [['ILES VIERGES BRITANNIQUES', 'VIRGIN ISLANDS', 'VIRGIN ISLANDS (GB)', 'VIRGIN ISLANDS (UK)',
          'VIRGIN ISLANDS BRITISH', 'BRITISH VIRGIN', 'BRITISH VIRGIN IS', 'British Virgin Islands'],
         'BRITISH VIRGIN ISLANDS'],
        [['BRITISH W'], 'BRITISH WEST INDIES'],
        [['BRUNEI'], 'BRUNEI'],
        [['BRUNEI DARUSSALAM'], 'BRUNEI'],
        [['BULGARIA'], 'BULGARIA'],
        [['BURKINA FASO', 'UPPER VOLTA'], 'BURKINA FASO'],
        [['BURMA'], 'BURMA'],
        [['BURUNDI'], 'BURUNDI'],
        [['CAICOS'], 'CAICOS'],
        [['KAMPACHEA', 'CAMBODIA', 'CAMBODIA (KAMPUCHEA)'], 'CAMBODIA'],
        [['CAMEROUN', 'CAMEROON'], 'CAMEROON'],
        [['CA', 'CAN', 'CANDAD', 'QUEBEC', 'CANADA', 'British Columbia', 'Ontario''Qu?bec', 'Alberta', 'Nova Scotia',
          'manitoba'], 'CANADA'],
        [['CANARY ISLANDS'], 'CANARY ISLANDS'],
        [['CAP VERT', 'CAPE VERDE'], 'CAPE VERDE ISLANDS'],
        [['CAYMAN ISLANDS'], 'CAYMAN ISLANDS'],
        [['CENTRAL AFRICAN REP', 'CENTRAL AFRICAN REPUBLIC'], 'CENTRAL AFRICAN REPUBLIC'],
        [['CHAD'], 'CHAD'],
        [['CHANNEL ISLANDS'], 'CHANNEL ISLANDS'],
        [['CHILE'], 'CHILE'],
        [['CHINA', 'CHINAPEO REPBL', 'CHINAPEOPLES', 'R.O.C.', 'CHINA  PEOPLES', 'CHINA  PEOPLES', 'CHINA PEO REPBL',
          'ShanDong province China'], 'CHINA'],
        [['COLOMBIA', 'COLUMBIA', 'Colombie'], 'COLOMBIA'],
        [['REP DU CONGO', 'CONGO'], 'CONGO'],
        [['CONGO, DEMOCRATIC REPUBLIC OF', 'CONGO THE DEMOCRATIC REPUBLIC'], 'DR CONGO'],
        [['COOK ISLANDS'], 'COOK ISLANDS'],
        [['CORSICA'], 'CORSICA'],
        [['COSTA RICA', 'COSTARICA', 'COSTA RICA'], 'COSTA RICA'],
        [['CROATIA', 'CROATIZ'], 'CROATIA'],
        [['CUBA'], 'CUBA'],
        [['CURACAO'], 'CURACAO'],
        [['CYPRUS'], 'CYPRUS'],
        [['CZECH REPUBL', 'CZECH REPUBLIC', 'R?PUBLIQUE TCH?QUE'], 'CZECH REPUBLIC'],
        [['DANEMARK', 'DANMARK', 'DENMARK', 'DEMARK'], 'DENMARK'],
        [['AFARS & ISSAS', 'DJIBOUTI'], 'DJIBOUTI'],
        [['DOMINICA'], 'DOMINICA'],
        [['DOMINICAN EPUBLIC', 'DOMINICAN REP', 'DOMINICAN REPUB', 'DOMINICAN REPUBLIC', 'DOMICAN REPUBLIC'],
         'DOMINICAN REPUBLIC'],
        [['EAST TIMOR', 'EAST TIMOR (TIMOR-LESTE)'], 'EAST TIMOR'],
        [['ECUADOR'], 'ECUADOR'],
        [['EGYPT', 'EGYPTE'], 'EGYPT'],
        [['SALVADOR', 'EL SALVADOR'], 'EL SALVADOR'],
        [['CHESHIRE', 'GLOUCESTER', 'MANCHESTER ENGLAND MLX', 'ENGLAND', 'ENGLAND RL', 'London', 'SOMERSET ENGLAND',
          'South Yorkshire', 'Merseyside', 'Berkshire'], 'ENGLAND'],
        [['EQUATORIAL GUINEA'], 'EQUATORIAL GUINEA'],
        [['ERITREA'], 'ERITREA'],
        [['ESTONIA'], 'ESTONIA'],
        [['ETHIOPIA'], 'ETHIOPIA'],
        [['FALKLAND ISLANDS (MALVINAS)', 'FALKLAND ISLANDS'], 'FALKLAND ISLANDS'],
        [['FAROE ISLANDS', 'Faeroe Islands'], 'FAROE ISLANDS'],
        [['FIJI'], 'FIJI'],
        [['FINLAND', 'FINLANDE', 'Finlad'], 'FINLAND'],
        [['PARIS', 'FRANCE', 'FRANCE, METROPOLITAN', 'FRANCEXX'], 'FRANCE'],
        [['FRENCH GUIANA'], 'FRENCH GUIANA'],
        [['FRENCH POLYNESI', 'FRENCH POLYNESIA', 'POLYN?SIE FRAN?AISE', 'POLYNN++SIE FRANN++AISE', 'Polynésie Française'],
         'FRENCH POLYNESIA'],
        [['FRENCH SOUTHERN AND ANTARCTIC'], 'FRENCH STHRN ANTARCTIC LANDS'],
        [['FRENCH WEST INDIES'], 'FRENCH WEST INDIES'],
        [['GABON'], 'GABON'],
        [['GAMBIA', 'GAMBIE'], 'GAMBIA'],
        [['G?ORGIE', 'GEORGIA', 'Géorgie'], 'GEORGIA'],
        [['ALLEMAGNE', 'GEMANY', 'GERMANY', 'GERNANY'], 'GERMANY'],
        [['GHANA', 'Greater Accra'], 'GHANA'],
        [['GIBRALTAR'], 'GIBRALTAR'],
        [['GILBERT ISLANDS'], 'GILBERT ISLANDS'],
        [['GREAT BRITAIN', 'GREAT BRITIAN'], 'GREAT BRITAIN'],
        [['GREECE', 'GR?CE', 'Grèce'], 'GREECE'],
        [['GREENLAND'], 'GREENLAND'],
        [['GRENADA'], 'GRENADA'],
        [['GUADELOUPE'], 'GUADELOUPE'],
        [['GUAM'], 'GUAM'],
        [['GUATEMALA'], 'GUATEMALA'],
        [['GUERNSEY'], 'GUERNSEY'],
        [['GUINEA'], 'GUINEA'],
        [['GUINEA BISSAU', 'GUINEA-BISSAU'], 'GUINEA-BISSAU'],
        [['GUYANA'], 'GUYANA'],
        [['HAITI'], 'HAITI'],
        [['NEITHERLANDS', 'NETHERLAND', 'NETHERLANDS', 'PAYS-BAS', 'THE NETHERLANDS', 'HOLLAND'], 'HOLLAND'],
        [['HONDURAS'], 'HONDURAS'],
        [['HONG KONG - SAR', 'HONG KONG', 'HONG KONGSAR', 'HONG KONG-SAR', 'HONGKONG', 'HONG KONG  SAR', 'HONG KONG  SAR'],
         'HONG KONG'],
        [['HOWLAND ISLAND'], 'HOWLAND ISLAND'],
        [['HONGRIE', 'HUMGARY', 'HUNGARY'], 'HUNGARY'],
        [['ICELAND'], 'ICELAND'],
        [['INDIAN', 'INDE', 'INDIA', 'INIDIA', 'Karnataka', 'karnataka INDIA', 'BRITISH INDIA', 'Maharashtra',
          'andhrapradesh', 'SELANGOR', 'tamilnadu'], 'INDIA'],
        [['SUMATRA', 'INDON?SIE', 'INDONESIA', 'INDONN++SIE', 'JAVA', 'Indonésie', 'jawa timur'], 'INDONESIA'],
        [['IRAN', 'IRANISLAMIC REPUBLIC OF', 'IRAN (ISLAMIC REPUBLIC OF)', 'ISLAMIC REPUBLIC OF IRAN',
          'IRAN ISLAMIC REPUBLIC OF'], 'IRAN'],
        [['IRAQ', 'IRAK'], 'IRAQ'],
        [['REPUBLIC OF IRELAND', 'IRELAND', 'IRLANDE'], 'IRELAND'],
        [['ISLE OF MAN'], 'ISLE OF MAN'],
        [['ISAREL', 'JERUSALEM', 'ISRA?L', 'ISRAEL', 'ISRAN++L', 'ISREAL', 'Israël'], 'ISRAEL'],
        [['SICILY', 'ITALIA', 'ITALIA', 'ITALIE', 'ITALY', 'ITALY 00187'], 'ITALY'],
        [['C?TE D IVOIRE', 'CN++TE D IVOIRE', 'COTE DIVOIRE', 'COTE D''IVOIRE', 'Côte d Ivoire'], 'IVORY COAST'],
        [['JAMAICA'], 'JAMAICA'],
        [['TOKYO', 'JAPAN'], 'JAPAN'],
        [['JERSEY'], 'JERSEY'],
        [['JORDAN', 'Amman'], 'JORDAN'],
        [['KAZAKHSTAN', 'KAZAKSTAN'], 'KAZAKHSTAN'],
        [['KENYA', 'NAIROBI'], 'KENYA'],
        [['KIRIBATI', 'TARAWA'], 'KIRIBATI'],
        [['KORE', 'KOREA'], 'KOREA'],
        [['KOSOVA'], 'KOSOVA'],
        [['KUWAIT', 'Kowe?t', 'Koweït'], 'KUWAIT'],
        [['KYRGYZSTAN'], 'KYRGYZSTAN'],
        [['LAOS'], 'LAOS'],
        [['LATAVIA', 'LATVIA'], 'LATVIA'],
        [['LEBANON', 'LIBAN', 'beirut'], 'LEBANON'],
        [['LESOTHO'], 'LESOTHO'],
        [['LIBERIA'], 'LIBERIA'],
        [['LIBYA', 'LIBYAN ARAB JAM', 'LIBYAN ARAB JAMAHIRIYA'], 'LIBYA'],
        [['LIECHTENSTEIN'], 'LIECHTENSTEIN'],
        [['LITHUANIA'], 'LITHUANIA'],
        [['LUXEMBOURG', 'LUXEMBURG'], 'LUXEMBOURG'],
        [['MACAO', 'MACAU'], 'MACAU'],
        [['MACEDONIA', 'MACEDONIATHE FORMER YUGOSLAV', 'MACEDONIA, FORMER YUGOSLAV REP', 'MACEDONIA THE FORMER YUGOSLAV',
          'FYRO Macedonia'], 'MACEDONIA'],
        [['MADAGASCAR'], 'MADAGASCAR'],
        [['MALAWI'], 'MALAWI'],
        [['MALAYSIA', 'Kuala Lumpur'], 'MALAYSIA'],
        [['MALDIVES'], 'MALDIVES'],
        [['MALI'], 'MALI'],
        [['MALTA'], 'MALTA'],
        [['BIKINI', 'MARSHALL ISLANDS'], 'MARSHALL ISLANDS'],
        [['MARTINIQUE'], 'MARTINIQUE'],
        [['MAURITANIE', 'MAURITIUS'], 'MAURITIUS'],
        [['MAXICO', 'MEXICO', 'MN++XICO', 'M?xico', 'México', 'MEXICO.'], 'MEXICO'],
        [['MONACO'], 'MONACO'],
        [['MONGOLIA'], 'MONGOLIA'],
        [['MONTENEGRO'], 'MONTENEGRO'],
        [['MONTSERRAT'], 'MONTSERRAT'],
        [['MAROC', 'MOROCCO'], 'MOROCCO'],
        [['MOZAMBIQUE'], 'MOZAMBIQUE'],
        [['MYANMAR'], 'MYANMAR'],
        [['NAMIBIA'], 'NAMIBIA'],
        [['NAURU'], 'NAURU'],
        [['NEPAL'], 'NEPAL'],
        [['NETH. ANTILLES', 'NETHERLAND ANTILEES', 'NETHERLANDS ANT', 'NETHERLANDS ANTILLES', 'DUTCH ANTILLES',
          'NETHERLAND ANTI'], 'NETHERLANDS ANTILEES'],
        [['NEW CALEDONIA', 'NOUVELLE CAL?DONIE', 'Nouvelle Calédonie'], 'NEW CALEDONIA'],
        [['NEW ZEALAND', 'NEW-ZEALAND', 'Auckland'], 'NEW ZEALAND'],
        [['NICARAGUA'], 'NICARAGUA'],
        [['NIGER'], 'NIGER'],
        [['NIGERIA'], 'NIGERIA'],
        [['NORFOLK ISLAND'], 'NORFOLK ISLAND'],
        [['KOREADEMOCRATIC PEOPLE''S REP', 'KOREANORTH', 'KOREA DEMOCRAT', 'KOREA DEMOCRATI',
          'KOREA DEMOCRATIC PEOPLES REP', 'KOREA, DEMOCRATIC PEOPLES REP.', 'KOREA, NORTH', 'NORTH KOREA',
          'KOREA DEMOCRATIC PEOPLE''S REP', 'KOREA NORTH'], 'NORTH KOREA'],
        [['NORTHERN IRELAND', 'N. IRELAND'], 'NORTHERN IRELAND'],
        [['NORWAY'], 'NORWAY'],
        [['SPITZBERGEN'], 'NORWAY'],
        [['OMAN'], 'OMAN'],
        [['PAKISTAN'], 'PAKISTAN'],
        [['PANAMA'], 'PANAMA'],
        [['PAPUA NEW GUINE', 'PAPUA NEW GUINEA'], 'PAPUA NEW GUINEA'],
        [['PARAGUAY'], 'PARAGUAY'],
        [['PERU'], 'PERU'],
        [['PHILIPPINES'], 'PHILIPPINES'],
        [['PITCAIRN'], 'PITCAIRN ISLANDS'],
        [['POLAND', 'POLLAND', 'POLOGNE'], 'POLAND'],
        [['PORTUGAL', 'MADEIRA'], 'PORTUGAL'],
        [['PUERTO RICO', 'PUERTO RICO USA'], 'PUERTO RICO'],
        [['QATAR'], 'QATAR'],
        [['MOLDAVIE', 'MOLDOVA', 'MOLDOVAREPUBLIC OF', 'MOLDOVA REPUBLIC OF', 'Moldova, Republic of'],
         'REPUBLIC OF MOLDOVA'],
        [['REUNION', 'REUNION ISLAND'], 'REUNION ISLAND'],
        [['ROMANIA', 'ROUMANIE'], 'ROMANIA'],
        [['MIR', 'RUSSIA', 'RUSSIAN FED', 'RUSSIAN FEDERAT', 'RUSSIAN FEDERATION', 'RUSSIAN FEDERTN', 'RUSSIE'], 'RUSSIA'],
        [['RWANDA'], 'RWANDA'],
        [['SAIPAN'], 'SAIPAN'],
        [['SAMOA'], 'SAMOA'],
        [['SAN MARINO'], 'SAN MARINO'],
        [['ARABIE SAOUDITE', 'KINGDUM OF SAUDI ARABIA', 'SAUDI ARABIA', 'SAUDIA ARABIA', 'EAST SAUDI ARABIA', 'RIYADH'],
         'SAUDI ARABIA'],
        [['ABERDEENSHIRE SCOTLAND', 'SCOTLAND'], 'SCOTLAND'],
        [['S?N?GAL', 'SENEGAL', 'Sénégal'], 'SENEGAL'],
        [['YUGOSLAVIASERBIA', 'SERBIA'], 'SERBIA'],
        [['SERBIA & MONTENEGRO', 'SERBIA AND MONT', 'SERBIA AND MONTENEGRO', 'SERBIA MONTENEG'], 'SERBIA MONTENEGRO'],
        [['SEYCHELLES', 'SEYCHELLES ISLANDS', 'SEYCHELLE ISLANDS'], 'SEYCHELLES ISLANDS'],
        [['SIERRA LEONE'], 'SIERRA LEONE'],
        [['REPUBLIC OF SINGAPORE', 'SINGAPORE', 'SINGAPOUR', 'MALAYA'], 'SINGAPORE'],
        [['SLOVAK REP', 'SLOVAK REPUBLIC', 'SLOVAKIA', 'SLOVAKIA (SLOVAK REPUBLIC)', 'SLOVAKIAN REPUBLIC'],
         'SLOVAK REPUBLIC'],
        [['SLOVANIA', 'SLOVENIA'], 'SLOVENIA'],
        [['SOLOM0N ISLANDS'], 'SOLOM0N ISLANDS'],
        [['SOMALIA'], 'SOMALIA'],
        [['S AFRICA', 'SOUTH AFR', 'SOUTH AFRICA', 'SOUTH AFRICAR', 'SOUTH FARICA', 'SOUTH AFRICA  R', 'SOUTH AFRICA  R',
          'S. AFRICA', 'S-AFRICA'], 'SOUTH AFRICA'],
        [['KOREAREPUBLIC OF', 'KOREAREPUBLIC OF', 'KOREASOUTH', 'KOREA (SOUTH)', 'KOREA REP OF S', 'KOREA REPUBLIC',
          'KOREA REPUBLIC OF', 'KOREA SOUTH', 'KOREA, REPUBLIC OF', 'KOREA, SOUTH', 'REPURBLIC OF KOREA', 'S KOREA',
          'S. KOREA', 'SOUTH KOREA', 'KOREA REPUBLIC OF', 'KOREA SOUTH', 'REPUBLIC OF KOREA', 'KOREA REPUBLIC OF'],
         'SOUTH KOREA'],
        [['YEMEN', 'YEMENPEOPLES REPUB', 'YEMEN (SAN''A'')', 'YEMEN PEOPLES REPUB'], 'SOUTH YEMEN'],
        [['ESPAGNE', 'ESPAIN', 'SPAIN', 'Madrid'], 'SPAIN'],
        [['SRI LANKA', 'SRILANKA'], 'SRI LANKA'],
        [['SAINT BARTHELEMY'], 'ST. BARTHELEMY'],
        [['ST. HELENA'], 'ST. HELENA'],
        [['NEVIS', 'NEVIS WEST INDIES', 'ST KITTS', 'ST KITTS AND NEVIS', 'ST. KITTS NEVIS', 'SAINT KITTS AND NEVIS',
          'ST KITTS AND NE'], 'ST. KITTS NEVIS'],
        [['ST LUCIA', 'ST. LUCIA', 'Saint Lucia'], 'ST. LUCIA'],
        [['ST MAARTEN', 'ST. MARTIN'], 'ST. MARTIN'],
        [['ST VINCENT', 'ST VINCENT AND THE GRENADINES'], 'ST. VINCENT AND THE GRENADINES'],
        [['PALESTINE', 'PALESTINIAN TERRITORIES', 'PALESTINIAN TERRITORYOCCUPIE', 'PALESTINIAN TERRITORY OCCUPIE'],
         'STATE OF PALESTINE'],
        [['SUDAN'], 'SUDAN'],
        [['SURINAME'], 'SURINAME'],
        [['SWAZILAND'], 'SWAZILAND'],
        [['SU?DE', 'SWEDEN', 'SWEEDEN', 'Suède'], 'SWEDEN'],
        [['SUISSE', 'SWISS', 'SWITZERLA', 'SWITZERLAND', 'SWTIZERLAND', 'SWITZERAND'], 'SWITZERLAND'],
        [['SYRIA', 'SYRIAN ARAB REP', 'SYRIAN ARAB REPUBLIC', 'SYRIE'], 'SYRIA'],
        [['TAHITI'], 'TAHITI'],
        [['TAIWAN', 'TAIWANPROVINCE OF CHINA', 'TAIWANROC', 'TAIWAN ROC', 'TAIWAN, PROVINCE OF CHINA',
          'TAIWAN PROVINCE OF CHINA', 'Taiwan ROC'], 'TAIWAN'],
        [['TAJIKISTAN'], 'TAJIKISTAN'],
        [['TANZANIA', 'TANZANIAUNITED REPUBLIC OF', 'TANZANIA, UNITED REPUBLIC OF', 'TANZANIA UNITED REPUBLIC OF'],
         'TANZANIA'],
        [['THAILAND', 'THAILNAD', 'THIALAND', 'Bangkok'], 'THAILAND'],
        [['TIBET'], 'TIBET'],
        [['TOGO'], 'TOGO'],
        [['TORTOLA'], 'TORTOLA'],
        [['TOBAGO', 'TRINIDAD', 'TRINIDAD & TOBA', 'TRINIDAD & TOBAGO', 'TRINIDAD AND TO', 'TRINIDAD AND TOBAGO'],
         'TRINIDAD TOBAGO'],
        [['TUNISIA', 'TUNISIE'], 'TUNISIA'],
        [['TURKEY', 'TURQUIE'], 'TURKEY'],
        [['TURKMENISTAN'], 'TURKMENISTAN'],
        [['TURKS AND CAICO', 'TURKS AND CAICOS ISLANDS', 'CAICOS ISLANDS'], 'TURKS AND CAICOS ISLANDS'],
        [['TUVALU'], 'TUVALU'],
        [['U.S. VIRGIN ISLANDS', 'UNITED STATES VIRGIN ISLANDS', 'US VIRGIN ISLANDS', 'VIRGIN ISLANDS (U.S.)'],
         'U.S. VIRGIN ISLANDS'],
        [['UGANDA'], 'UGANDA'],
        [['UKRAINE', 'UKRAINE, REPUBLIC OF'], 'UKRAINE'],
        [['UNITED ARAB EMI', 'UNITED ARAB EMIRATES', 'UAE', 'U.A.E.', 'UNITED ARAB EMIRATE', 'United Arab Emitrates',
          'Abu Dhabi', 'uae-abudhabi', 'sharjah uae'], 'UNITED ARAB EMIRATES'],
        [['ROYAUME-UNI', 'UNITED KI', 'UNITED KINDGDOM', 'UNITED KINGDOM', 'UNITED KINGDOM (GREAT BRITAIN)',
          'UNITED KINGDON', 'UNITED KNGDOM', 'UNTIED KINGDOM', 'UK', 'U.K.', 'UNITED KINDGOM', 'UNITED KINDGOM',
          'UNITED KINDOM', 'UNITED KING', 'UNITES KINGDOM'], 'UNITED KINGDOM'],
        [['URAGUAY', 'URUGUAY'], 'URUGUAY'],
        [['BARNSTABLE', 'ETATS-UNIS', 'HILLSBORO', 'LAREDO', 'MARION', 'U.S.', 'U.S. OF A.', 'U.S.A', 'U.S.A.',
          'UNITED STATES', 'UNITED STATES MINOR OUTLYING I', 'UNITED STATES OF AMERICA', 'US', 'USA', 'Oregon',
          'New Jersey', 'Texas', 'Louisiana'], 'USA'],
        [['UZBEKISTAN'], 'UZBEKISTAN'],
        [['VANUATU'], 'VANUATU'],
        [['HOLY SEE (VATICAN CITY STATE)', 'HOLY SEE VATIC', 'VATICAN CITY', 'THE VATICAN'], 'VATICAN CITY'],
        [['VENEZUELA', 'VENZUELA'], 'VENEZUELA'],
        [['VIET NAM', 'VIETNAM', 'VIETNAMRPBLC OF', 'VIETNAM RPBLC OF', 'Da Nang'], 'VIETNAM'],
        [['WALES'], 'WALES'],
        [['WALLIS AND FUTUNA'], 'WALLIS AND FUTUNA ISLANDS'],
        [['W AFRICA'], 'WEST AFRICA'],
        [['WEST BANK'], 'WEST BANK'],
        [['WEST INDIES'], 'WEST INDIES'],
        [['WESTERN SAHARA'], 'WESTERN SAHARA'],
        [['WESTERN SAMOA'], 'WESTERN SAMOA'],
        [['YUGOSLAVIA'], 'YUGOSLAVIA'],
        [['ZAIRE'], 'ZAIRE'],
        [['ZAMBIA'], 'ZAMBIA'],
        [['ZIMBABWE'], 'ZIMBABWE']
    ]

    COUNTRY_BY_ALIASES = {}
    for aliases, country in COUNTRY_ALIASES:
        for alias in aliases:
            COUNTRY_BY_ALIASES[alias.upper()] = country.upper()




    def udf_calculatecountry(state_code):
        state_code = str(state_code).strip().upper()
        usa_state_1 = ['AL', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
                       'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
                       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM',
                       'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD',
                       'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
        usa_state_2 = ['AK', 'HI']
        usa_state_3 = ['PR', 'QU', 'VI']
        usa_state_4 = ['AA', 'AE', 'AP', 'FP']
        canada_state = ['AB', 'BC', 'MB', 'NF', 'NS', 'NT', 'ON', 'PE', 'PQ', 'SK',
                        'YT', 'NB', 'NL', 'QC', 'NU']

        result = '6'
        if state_code in usa_state_1:
            result = '1'
        elif state_code in usa_state_2:
            result = '2'
        elif state_code in usa_state_3:
            result = '3'
        elif state_code in usa_state_4:
            result = '4'
        elif state_code in canada_state:
            result = '5'
        return result

    if not countryname:
        countryname= ''
    if not statecode:
        statecode = ''

    if statecode.strip() != '':
        countrycode = udf_calculatecountry(statecode)
        if countrycode in ['1', '2', '3', '4']:
            return 'USA'
        if countrycode == '5':
            return 'CANADA'

    return COUNTRY_BY_ALIASES.get(countryname.upper(), countryname)
$$ language plpythonu;

/*
Select udf_fixcountryname('R.O.C.', '')  --    'CHINA'
Select udf_fixcountryname('sharjah uae', '') --    'UNITED ARAB EMIRATES'
Select  udf_fixcountryname('sharjah uae', 'NJ') --    'USA'
Select  udf_fixcountryname('UnItEd kINg', '') --    'UNITED KINGDOM'
Select  udf_fixcountryname('Moldova, Republic of', '') --    'REPUBLIC OF MOLDOVA'
Select  udf_fixcountryname('Moldova, Republic of', 'AB') ---    'CANADA'
Select  udf_fixcountryname('SAInt Lucia', '') ---    ST. LUCIA
Select udf_fixcountryname('s', 'TX')
Select udf_fixcountryname('', 'TX')

*/
