drop table if exists tblchild1_{build_id}_{build}_load CASCADE;
create table tblchild1_{build_id}_{build}_load
(
    cid VARCHAR(18) ENCODE RAW,
    last_transaction_overall VARCHAR(8) ENCODE ZSTD,
    last_transaction_catalog VARCHAR(8) ENCODE ZSTD,
    last_transaction_web VARCHAR(8) ENCODE ZSTD,
    last_transaction_retail VARCHAR(8) ENCODE ZSTD,
    tot_parts INT ENCODE AZ64,
    cat_parts INT ENCODE AZ64,
    web_parts INT ENCODE AZ64,
    rtl_parts INT ENCODE AZ64,
    tot_dlrs_12m INT ENCODE ZSTD,
    tot_trns_12m INT ENCODE ZSTD,
    tot_dlrs_13p INT ENCODE ZSTD,
    tot_trns_13p INT ENCODE ZSTD,
    cat_dlrs_12m INT ENCODE ZSTD,
    cat_trns_12m INT ENCODE ZSTD,
    cat_dlrs_13p INT ENCODE ZSTD,
    cat_trns_13p INT ENCODE ZSTD,
    web_dlrs_12m INT ENCODE ZSTD,
    web_trns_12m INT ENCODE ZSTD,
    web_dlrs_13p INT ENCODE ZSTD,
    web_trns_13p INT ENCODE ZSTD,
    rtl_dlrs_12m INT ENCODE ZSTD,
    rtl_trns_12m INT ENCODE ZSTD,
    rtl_dlrs_13p INT ENCODE ZSTD,
    rtl_trns_13p INT ENCODE ZSTD,
    pay_12m_db varchar(1) ENCODE ZSTD,
    pay_12m_cc varchar(1) ENCODE ZSTD,
    pay_12m_dc varchar(1) ENCODE ZSTD,
    pay_12m_pc varchar(1) ENCODE ZSTD,
    pay_12m_cash varchar(1) ENCODE ZSTD,
    pay_12m_oth varchar(1) ENCODE ZSTD,
    pay_12m_ukn varchar(1) ENCODE ZSTD,
    pay_13p_db varchar(1) ENCODE ZSTD,
    pay_13p_cc varchar(1) ENCODE ZSTD,
    pay_13p_dc varchar(1) ENCODE ZSTD,
    pay_13p_pc varchar(1) ENCODE ZSTD,
    pay_13p_cash varchar(1) ENCODE ZSTD,
    pay_13p_oth varchar(1) ENCODE ZSTD,
    pay_13p_ukn varchar(1) ENCODE ZSTD,
    cctype_12m_visa varchar(1) ENCODE ZSTD,
    cctype_12m_mc varchar(1) ENCODE ZSTD,
    cctype_12m_amex varchar(1) ENCODE ZSTD,
    cctype_12m_disc varchar(1) ENCODE ZSTD,
    cctype_12m_btq varchar(1) ENCODE ZSTD,
    cctype_12m_oth varchar(1) ENCODE ZSTD,
    cctype_12m_ukn varchar(1) ENCODE ZSTD,
    cctype_13p_visa varchar(1) ENCODE ZSTD,
    cctype_13p_mc varchar(1) ENCODE ZSTD,
    cctype_13p_amex varchar(1) ENCODE ZSTD,
    cctype_13p_disc varchar(1) ENCODE ZSTD,
    cctype_13p_btq varchar(1) ENCODE ZSTD,
    cctype_13p_oth varchar(1) ENCODE ZSTD,
    cctype_13p_ukn varchar(1) ENCODE ZSTD,
    months_overall INT ENCODE AZ64,
    months_cat INT ENCODE AZ64,
    months_rtl INT ENCODE AZ64,
    months_web INT ENCODE AZ64,
    last_transaction_overall_days INT ENCODE AZ64,
    last_transaction_catalog_days INT ENCODE AZ64,
    last_transaction_retail_days INT ENCODE AZ64,
    last_transaction_web_days INT ENCODE AZ64,
    tot_dlrs_12m_avg INT ENCODE ZSTD,
    tot_dlrs_13p_avg INT ENCODE ZSTD,
    cat_dlrs_12m_avg INT ENCODE ZSTD,
    cat_dlrs_13p_avg INT ENCODE ZSTD,
    rtl_dlrs_12m_avg INT ENCODE ZSTD,
    rtl_dlrs_13p_avg INT ENCODE ZSTD,
    web_dlrs_12m_avg INT ENCODE ZSTD,
    web_dlrs_13p_avg INT ENCODE ZSTD,
    tot_date_code varchar(1) ENCODE ZSTD,
    cat_date_code varchar(1) ENCODE ZSTD,
    rtl_date_code varchar(1) ENCODE ZSTD,
    web_date_code varchar(1) ENCODE ZSTD,
    tot_trns_12m_code varchar(1) ENCODE ZSTD,
    cat_trns_12m_code varchar(1) ENCODE ZSTD,
    rtl_trns_12m_code varchar(1) ENCODE ZSTD,
    web_trns_12m_code varchar(1) ENCODE ZSTD,
    tot_trns_13p_code varchar(1) ENCODE ZSTD,
    cat_trns_13p_code varchar(1) ENCODE ZSTD,
    rtl_trns_13p_code varchar(1) ENCODE ZSTD,
    web_trns_13p_code varchar(1) ENCODE ZSTD,
    tot_dlrs_12m_code varchar(1) ENCODE ZSTD,
    cat_dlrs_12m_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_12m_code varchar(1) ENCODE ZSTD,
    web_dlrs_12m_code varchar(1) ENCODE ZSTD,
    tot_dlrs_13p_code varchar(1) ENCODE ZSTD,
    cat_dlrs_13p_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_13p_code varchar(1) ENCODE ZSTD,
    web_dlrs_13p_code varchar(1) ENCODE ZSTD,
    tot_dlrs_12m_avg_code varchar(1) ENCODE ZSTD,
    tot_dlrs_13p_avg_code varchar(1) ENCODE ZSTD,
    cat_dlrs_12m_avg_code varchar(1) ENCODE ZSTD,
    cat_dlrs_13p_avg_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_12m_avg_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_13p_avg_code varchar(1) ENCODE ZSTD,
    web_dlrs_12m_avg_code varchar(1) ENCODE ZSTD,
    web_dlrs_13p_avg_code varchar(1) ENCODE ZSTD,
    tot_dlrs_24p INT ENCODE AZ64,
    tot_trns_24p INT ENCODE AZ64,
    cat_dlrs_24p INT ENCODE ZSTD,
    cat_trns_24p INT ENCODE ZSTD,
    web_dlrs_24p INT ENCODE ZSTD,
    web_trns_24p INT ENCODE AZ64,
    rtl_dlrs_24p INT ENCODE ZSTD,
    rtl_trns_24p INT ENCODE AZ64,
    tot_dlrs_24p_avg INT ENCODE AZ64,
    cat_dlrs_24p_avg INT ENCODE ZSTD,
    rtl_dlrs_24p_avg INT ENCODE ZSTD,
    web_dlrs_24p_avg INT ENCODE BYTEDICT,
    tot_trns_24p_code varchar(1) ENCODE ZSTD,
    cat_trns_24p_code varchar(1) ENCODE ZSTD,
    rtl_trns_24p_code varchar(1) ENCODE ZSTD,
    web_trns_24p_code varchar(1) ENCODE ZSTD,
    tot_dlrs_24p_code varchar(1) ENCODE ZSTD,
    cat_dlrs_24p_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_24p_code varchar(1) ENCODE ZSTD,
    web_dlrs_24p_code varchar(1) ENCODE ZSTD,
    tot_dlrs_24p_avg_code varchar(1) ENCODE ZSTD,
    cat_dlrs_24p_avg_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_24p_avg_code varchar(1) ENCODE ZSTD,
    web_dlrs_24p_avg_code varchar(1) ENCODE ZSTD,
    channeltype_code_3m varchar(1) ENCODE ZSTD,
    channeltype_code_6m varchar(1) ENCODE ZSTD,
    channeltype_code_12m varchar(1) ENCODE ZSTD
)
DISTSTYLE KEY
DISTKEY(cid)
SORTKEY(cid);

---load child1 table
COPY tblchild1_{build_id}_{build}_load
from  's3://{s3-internal}/neptune/mGen/tblChild1_1196_201301.txt'
iam_role '{iam}'
fixedwidth 
'cid:18,
last_transaction_overall:8,
last_transaction_catalog:8,
last_transaction_web:8,
last_transaction_retail:8,
tot_parts:3,
cat_parts:3,
web_parts:3,
rtl_parts:3,
tot_dlrs_12m:5,
tot_trns_12m:3,
tot_dlrs_13p:5,
tot_trns_13p:3,
cat_dlrs_12m:5,
cat_trns_12m:3,
cat_dlrs_13p:5,
cat_trns_13p:3,
web_dlrs_12m:5,
web_trns_12m:3,
web_dlrs_13p:5,
web_trns_13p:3,
rtl_dlrs_12m:5,
rtl_trns_12m:3,
rtl_dlrs_13p:5,
rtl_trns_13p:3,
pay_12m_db:1,
pay_12m_cc:1,
pay_12m_dc:1,
pay_12m_pc:1,
pay_12m_cash:1,
pay_12m_oth:1,
pay_12m_ukn:1,
pay_13p_db:1,
pay_13p_cc:1,
pay_13p_dc:1,
pay_13p_pc:1,
pay_13p_cash:1,
pay_13p_oth:1,
pay_13p_ukn:1,
cctype_12m_visa:1,
cctype_12m_mc:1,
cctype_12m_amex:1,
cctype_12m_disc:1,
cctype_12m_btq:1,
cctype_12m_oth:1,
cctype_12m_ukn:1,
cctype_13p_visa:1,
cctype_13p_mc:1,
cctype_13p_amex:1,
cctype_13p_disc:1,
cctype_13p_btq:1,
cctype_13p_oth:1,
cctype_13p_ukn:1,
months_overall:3,
months_cat:3,
months_rtl:3,
months_web:3,
last_transaction_overall_days:5,
last_transaction_catalog_days:5,
last_transaction_retail_days:5,
last_transaction_web_days:5,
tot_dlrs_12m_avg:5,
tot_dlrs_13p_avg:5,
cat_dlrs_12m_avg:5,
cat_dlrs_13p_avg:5,
rtl_dlrs_12m_avg:5,
rtl_dlrs_13p_avg:5,
web_dlrs_12m_avg:5,
web_dlrs_13p_avg:5,
tot_date_code:1,
cat_date_code:1,
rtl_date_code:1,
web_date_code:1,
tot_trns_12m_code:1,
cat_trns_12m_code:1,
rtl_trns_12m_code:1,
web_trns_12m_code:1,
tot_trns_13p_code:1,
cat_trns_13p_code:1,
rtl_trns_13p_code:1,
web_trns_13p_code:1,
tot_dlrs_12m_code:1,
cat_dlrs_12m_code:1,
rtl_dlrs_12m_code:1,
web_dlrs_12m_code:1,
tot_dlrs_13p_code:1,
cat_dlrs_13p_code:1,
rtl_dlrs_13p_code:1,
web_dlrs_13p_code:1,
tot_dlrs_12m_avg_code:1,
tot_dlrs_13p_avg_code:1,
cat_dlrs_12m_avg_code:1,
cat_dlrs_13p_avg_code:1,
rtl_dlrs_12m_avg_code:1,
rtl_dlrs_13p_avg_code:1,
web_dlrs_12m_avg_code:1,
web_dlrs_13p_avg_code:1,
tot_dlrs_24p:5,
tot_trns_24p:3,
cat_dlrs_24p:5,
cat_trns_24p:3,
web_dlrs_24p:5,
web_trns_24p:3,
rtl_dlrs_24p:5,
rtl_trns_24p:3,
tot_dlrs_24p_avg:5,
cat_dlrs_24p_avg:5,
rtl_dlrs_24p_avg:5,
web_dlrs_24p_avg:5,
tot_trns_24p_code:1,
cat_trns_24p_code:1,
rtl_trns_24p_code:1,
web_trns_24p_code:1,
tot_dlrs_24p_code:1,
cat_dlrs_24p_code:1,
rtl_dlrs_24p_code:1,
web_dlrs_24p_code:1,
tot_dlrs_24p_avg_code:1,
cat_dlrs_24p_avg_code:1,
rtl_dlrs_24p_avg_code:1,
web_dlrs_24p_avg_code:1,
channeltype_code_3m:1,
channeltype_code_6m:1,
channeltype_code_12m:1'
;


drop table if exists tblchild1_{build_id}_{build};
create table tblchild1_{build_id}_{build}
(
    cid VARCHAR(18) ENCODE RAW,
    last_transaction_overall VARCHAR(8) ENCODE ZSTD,
    last_transaction_catalog VARCHAR(8) ENCODE ZSTD,
    last_transaction_web VARCHAR(8) ENCODE ZSTD,
    last_transaction_retail VARCHAR(8) ENCODE ZSTD,
    tot_parts INT ENCODE AZ64,
    cat_parts INT ENCODE AZ64,
    web_parts INT ENCODE AZ64,
    rtl_parts INT ENCODE AZ64,
    tot_dlrs_12m INT ENCODE ZSTD,
    tot_trns_12m INT ENCODE ZSTD,
    tot_dlrs_13p INT ENCODE ZSTD,
    tot_trns_13p INT ENCODE ZSTD,
    cat_dlrs_12m INT ENCODE ZSTD,
    cat_trns_12m INT ENCODE ZSTD,
    cat_dlrs_13p INT ENCODE ZSTD,
    cat_trns_13p INT ENCODE ZSTD,
    web_dlrs_12m INT ENCODE ZSTD,
    web_trns_12m INT ENCODE ZSTD,
    web_dlrs_13p INT ENCODE ZSTD,
    web_trns_13p INT ENCODE ZSTD,
    rtl_dlrs_12m INT ENCODE ZSTD,
    rtl_trns_12m INT ENCODE ZSTD,
    rtl_dlrs_13p INT ENCODE ZSTD,
    rtl_trns_13p INT ENCODE ZSTD,
    pay_12m_db varchar(1) ENCODE ZSTD,
    pay_12m_cc varchar(1) ENCODE ZSTD,
    pay_12m_dc varchar(1) ENCODE ZSTD,
    pay_12m_pc varchar(1) ENCODE ZSTD,
    pay_12m_cash varchar(1) ENCODE ZSTD,
    pay_12m_oth varchar(1) ENCODE ZSTD,
    pay_12m_ukn varchar(1) ENCODE ZSTD,
    pay_13p_db varchar(1) ENCODE ZSTD,
    pay_13p_cc varchar(1) ENCODE ZSTD,
    pay_13p_dc varchar(1) ENCODE ZSTD,
    pay_13p_pc varchar(1) ENCODE ZSTD,
    pay_13p_cash varchar(1) ENCODE ZSTD,
    pay_13p_oth varchar(1) ENCODE ZSTD,
    pay_13p_ukn varchar(1) ENCODE ZSTD,
    cctype_12m_visa varchar(1) ENCODE ZSTD,
    cctype_12m_mc varchar(1) ENCODE ZSTD,
    cctype_12m_amex varchar(1) ENCODE ZSTD,
    cctype_12m_disc varchar(1) ENCODE ZSTD,
    cctype_12m_btq varchar(1) ENCODE ZSTD,
    cctype_12m_oth varchar(1) ENCODE ZSTD,
    cctype_12m_ukn varchar(1) ENCODE ZSTD,
    cctype_13p_visa varchar(1) ENCODE ZSTD,
    cctype_13p_mc varchar(1) ENCODE ZSTD,
    cctype_13p_amex varchar(1) ENCODE ZSTD,
    cctype_13p_disc varchar(1) ENCODE ZSTD,
    cctype_13p_btq varchar(1) ENCODE ZSTD,
    cctype_13p_oth varchar(1) ENCODE ZSTD,
    cctype_13p_ukn varchar(1) ENCODE ZSTD,
    months_overall INT ENCODE AZ64,
    months_cat INT ENCODE AZ64,
    months_rtl INT ENCODE AZ64,
    months_web INT ENCODE AZ64,
    last_transaction_overall_days INT ENCODE AZ64,
    last_transaction_catalog_days INT ENCODE AZ64,
    last_transaction_retail_days INT ENCODE AZ64,
    last_transaction_web_days INT ENCODE AZ64,
    tot_dlrs_12m_avg INT ENCODE ZSTD,
    tot_dlrs_13p_avg INT ENCODE ZSTD,
    cat_dlrs_12m_avg INT ENCODE ZSTD,
    cat_dlrs_13p_avg INT ENCODE ZSTD,
    rtl_dlrs_12m_avg INT ENCODE ZSTD,
    rtl_dlrs_13p_avg INT ENCODE ZSTD,
    web_dlrs_12m_avg INT ENCODE ZSTD,
    web_dlrs_13p_avg INT ENCODE ZSTD,
    tot_date_code varchar(1) ENCODE ZSTD,
    cat_date_code varchar(1) ENCODE ZSTD,
    rtl_date_code varchar(1) ENCODE ZSTD,
    web_date_code varchar(1) ENCODE ZSTD,
    tot_trns_12m_code varchar(1) ENCODE ZSTD,
    cat_trns_12m_code varchar(1) ENCODE ZSTD,
    rtl_trns_12m_code varchar(1) ENCODE ZSTD,
    web_trns_12m_code varchar(1) ENCODE ZSTD,
    tot_trns_13p_code varchar(1) ENCODE ZSTD,
    cat_trns_13p_code varchar(1) ENCODE ZSTD,
    rtl_trns_13p_code varchar(1) ENCODE ZSTD,
    web_trns_13p_code varchar(1) ENCODE ZSTD,
    tot_dlrs_12m_code varchar(1) ENCODE ZSTD,
    cat_dlrs_12m_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_12m_code varchar(1) ENCODE ZSTD,
    web_dlrs_12m_code varchar(1) ENCODE ZSTD,
    tot_dlrs_13p_code varchar(1) ENCODE ZSTD,
    cat_dlrs_13p_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_13p_code varchar(1) ENCODE ZSTD,
    web_dlrs_13p_code varchar(1) ENCODE ZSTD,
    tot_dlrs_12m_avg_code varchar(1) ENCODE ZSTD,
    tot_dlrs_13p_avg_code varchar(1) ENCODE ZSTD,
    cat_dlrs_12m_avg_code varchar(1) ENCODE ZSTD,
    cat_dlrs_13p_avg_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_12m_avg_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_13p_avg_code varchar(1) ENCODE ZSTD,
    web_dlrs_12m_avg_code varchar(1) ENCODE ZSTD,
    web_dlrs_13p_avg_code varchar(1) ENCODE ZSTD,
    tot_dlrs_24p INT ENCODE AZ64,
    tot_trns_24p INT ENCODE AZ64,
    cat_dlrs_24p INT ENCODE ZSTD,
    cat_trns_24p INT ENCODE ZSTD,
    web_dlrs_24p INT ENCODE ZSTD,
    web_trns_24p INT ENCODE AZ64,
    rtl_dlrs_24p INT ENCODE ZSTD,
    rtl_trns_24p INT ENCODE AZ64,
    tot_dlrs_24p_avg INT ENCODE AZ64,
    cat_dlrs_24p_avg INT ENCODE ZSTD,
    rtl_dlrs_24p_avg INT ENCODE ZSTD,
    web_dlrs_24p_avg INT ENCODE BYTEDICT,
    tot_trns_24p_code varchar(1) ENCODE ZSTD,
    cat_trns_24p_code varchar(1) ENCODE ZSTD,
    rtl_trns_24p_code varchar(1) ENCODE ZSTD,
    web_trns_24p_code varchar(1) ENCODE ZSTD,
    tot_dlrs_24p_code varchar(1) ENCODE ZSTD,
    cat_dlrs_24p_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_24p_code varchar(1) ENCODE ZSTD,
    web_dlrs_24p_code varchar(1) ENCODE ZSTD,
    tot_dlrs_24p_avg_code varchar(1) ENCODE ZSTD,
    cat_dlrs_24p_avg_code varchar(1) ENCODE ZSTD,
    rtl_dlrs_24p_avg_code varchar(1) ENCODE ZSTD,
    web_dlrs_24p_avg_code varchar(1) ENCODE ZSTD,
    channeltype_code_3m varchar(1) ENCODE ZSTD,
    channeltype_code_6m varchar(1) ENCODE ZSTD,
    channeltype_code_12m varchar(1) ENCODE ZSTD
)
DISTSTYLE KEY
DISTKEY(cid)
SORTKEY(cid);

INSERT INTO tblchild1_{build_id}_{build}
(
	 cid,
    last_transaction_overall,
    last_transaction_catalog,
    last_transaction_web,
    last_transaction_retail,
    tot_parts,
    cat_parts,
    web_parts,
    rtl_parts,
    tot_dlrs_12m,
    tot_trns_12m,
    tot_dlrs_13p,
    tot_trns_13p,
    cat_dlrs_12m,
    cat_trns_12m,
    cat_dlrs_13p,
    cat_trns_13p,
    web_dlrs_12m,
    web_trns_12m,
    web_dlrs_13p,
    web_trns_13p,
    rtl_dlrs_12m,
    rtl_trns_12m,
    rtl_dlrs_13p,
    rtl_trns_13p,
    pay_12m_db,
    pay_12m_cc,
    pay_12m_dc,
    pay_12m_pc,
    pay_12m_cash,
    pay_12m_oth,
    pay_12m_ukn,
    pay_13p_db,
    pay_13p_cc,
    pay_13p_dc,
    pay_13p_pc,
    pay_13p_cash,
    pay_13p_oth,
    pay_13p_ukn,
    cctype_12m_visa,
    cctype_12m_mc,
    cctype_12m_amex,
    cctype_12m_disc,
    cctype_12m_btq,
    cctype_12m_oth,
    cctype_12m_ukn,
    cctype_13p_visa,
    cctype_13p_mc,
    cctype_13p_amex,
    cctype_13p_disc,
    cctype_13p_btq,
    cctype_13p_oth,
    cctype_13p_ukn,
    months_overall,
    months_cat,
    months_rtl,
    months_web,
    last_transaction_overall_days,
    last_transaction_catalog_days,
    last_transaction_retail_days,
    last_transaction_web_days,
    tot_dlrs_12m_avg,
    tot_dlrs_13p_avg,
    cat_dlrs_12m_avg,
    cat_dlrs_13p_avg,
    rtl_dlrs_12m_avg,
    rtl_dlrs_13p_avg,
    web_dlrs_12m_avg,
    web_dlrs_13p_avg,
    tot_date_code,
    cat_date_code,
    rtl_date_code,
    web_date_code,
    tot_trns_12m_code,
    cat_trns_12m_code,
    rtl_trns_12m_code,
    web_trns_12m_code,
    tot_trns_13p_code,
    cat_trns_13p_code,
    rtl_trns_13p_code,
    web_trns_13p_code,
    tot_dlrs_12m_code,
    cat_dlrs_12m_code,
    rtl_dlrs_12m_code,
    web_dlrs_12m_code,
    tot_dlrs_13p_code,
    cat_dlrs_13p_code,
    rtl_dlrs_13p_code,
    web_dlrs_13p_code,
    tot_dlrs_12m_avg_code,
    tot_dlrs_13p_avg_code,
    cat_dlrs_12m_avg_code,
    cat_dlrs_13p_avg_code,
    rtl_dlrs_12m_avg_code,
    rtl_dlrs_13p_avg_code,
    web_dlrs_12m_avg_code,
    web_dlrs_13p_avg_code,
    tot_dlrs_24p,
    tot_trns_24p,
    cat_dlrs_24p,
    cat_trns_24p,
    web_dlrs_24p,
    web_trns_24p,
    rtl_dlrs_24p,
    rtl_trns_24p,
    tot_dlrs_24p_avg,
    cat_dlrs_24p_avg,
    rtl_dlrs_24p_avg,
    web_dlrs_24p_avg,
    tot_trns_24p_code,
    cat_trns_24p_code,
    rtl_trns_24p_code,
    web_trns_24p_code,
    tot_dlrs_24p_code,
    cat_dlrs_24p_code,
    rtl_dlrs_24p_code,
    web_dlrs_24p_code,
    tot_dlrs_24p_avg_code,
    cat_dlrs_24p_avg_code,
    rtl_dlrs_24p_avg_code,
    web_dlrs_24p_avg_code,
    channeltype_code_3m,
    channeltype_code_6m,
    channeltype_code_12m
)
SELECT
    cid,
    NULLIF(RTRIM(last_transaction_overall),''),
    NULLIF(RTRIM(last_transaction_catalog),''),
    NULLIF(RTRIM(last_transaction_web),''),
    NULLIF(RTRIM(last_transaction_retail),''),
    tot_parts,
    cat_parts,
    web_parts,
    rtl_parts,
    tot_dlrs_12m,
    tot_trns_12m,
    tot_dlrs_13p,
    tot_trns_13p,
    cat_dlrs_12m,
    cat_trns_12m,
    cat_dlrs_13p,
    cat_trns_13p,
    web_dlrs_12m,
    web_trns_12m,
    web_dlrs_13p,
    web_trns_13p,
    rtl_dlrs_12m,
    rtl_trns_12m,
    rtl_dlrs_13p,
    rtl_trns_13p,
    NULLIF(RTRIM(pay_12m_db),''),
    NULLIF(RTRIM(pay_12m_cc),''),
    NULLIF(RTRIM(pay_12m_dc),''),
    NULLIF(RTRIM(pay_12m_pc),''),
    NULLIF(RTRIM(pay_12m_cash),''),
    NULLIF(RTRIM(pay_12m_oth),''),
    NULLIF(RTRIM(pay_12m_ukn),''),
    NULLIF(RTRIM(pay_13p_db),''),
    NULLIF(RTRIM(pay_13p_cc),''),
    NULLIF(RTRIM(pay_13p_dc),''),
    NULLIF(RTRIM(pay_13p_pc),''),
    NULLIF(RTRIM(pay_13p_cash),''),
    NULLIF(RTRIM(pay_13p_oth),''),
    NULLIF(RTRIM(pay_13p_ukn),''),
    NULLIF(RTRIM(cctype_12m_visa),''),
    NULLIF(RTRIM(cctype_12m_mc),''),
    NULLIF(RTRIM(cctype_12m_amex),''),
    NULLIF(RTRIM(cctype_12m_disc),''),
    NULLIF(RTRIM(cctype_12m_btq),''),
    NULLIF(RTRIM(cctype_12m_oth),''),
    NULLIF(RTRIM(cctype_12m_ukn),''),
    NULLIF(RTRIM(cctype_13p_visa),''),
    NULLIF(RTRIM(cctype_13p_mc),''),
    NULLIF(RTRIM(cctype_13p_amex),''),
    NULLIF(RTRIM(cctype_13p_disc),''),
    NULLIF(RTRIM(cctype_13p_btq),''),
    NULLIF(RTRIM(cctype_13p_oth),''),
    NULLIF(RTRIM(cctype_13p_ukn),''),
    months_overall,
    months_cat,
    months_rtl,
    months_web,
    last_transaction_overall_days,
    last_transaction_catalog_days,
    last_transaction_retail_days,
    last_transaction_web_days,
    tot_dlrs_12m_avg,
    tot_dlrs_13p_avg,
    cat_dlrs_12m_avg,
    cat_dlrs_13p_avg,
    rtl_dlrs_12m_avg,
    rtl_dlrs_13p_avg,
    web_dlrs_12m_avg,
    web_dlrs_13p_avg,
    NULLIF(RTRIM(tot_date_code),''),
    NULLIF(RTRIM(cat_date_code),''),
    NULLIF(RTRIM(rtl_date_code),''),
    NULLIF(RTRIM(web_date_code),''),
    NULLIF(RTRIM(tot_trns_12m_code),''),
    NULLIF(RTRIM(cat_trns_12m_code),''),
    NULLIF(RTRIM(rtl_trns_12m_code),''),
    NULLIF(RTRIM(web_trns_12m_code),''),
    NULLIF(RTRIM(tot_trns_13p_code),''),
    NULLIF(RTRIM(cat_trns_13p_code),''),
    NULLIF(RTRIM(rtl_trns_13p_code),''),
    NULLIF(RTRIM(web_trns_13p_code),''),
    NULLIF(RTRIM(tot_dlrs_12m_code),''),
    NULLIF(RTRIM(cat_dlrs_12m_code),''),
    NULLIF(RTRIM(rtl_dlrs_12m_code),''),
    NULLIF(RTRIM(web_dlrs_12m_code),''),
    NULLIF(RTRIM(tot_dlrs_13p_code),''),
    NULLIF(RTRIM(cat_dlrs_13p_code),''),
    NULLIF(RTRIM(rtl_dlrs_13p_code),''),
    NULLIF(RTRIM(web_dlrs_13p_code),''),
    NULLIF(RTRIM(tot_dlrs_12m_avg_code),''),
    NULLIF(RTRIM(tot_dlrs_13p_avg_code),''),
    NULLIF(RTRIM(cat_dlrs_12m_avg_code),''),
    NULLIF(RTRIM(cat_dlrs_13p_avg_code),''),
    NULLIF(RTRIM(rtl_dlrs_12m_avg_code),''),
    NULLIF(RTRIM(rtl_dlrs_13p_avg_code),''),
    NULLIF(RTRIM(web_dlrs_12m_avg_code),''),
    NULLIF(RTRIM(web_dlrs_13p_avg_code),''),
    tot_dlrs_24p,
    tot_trns_24p,
    cat_dlrs_24p,
    cat_trns_24p,
    web_dlrs_24p,
    web_trns_24p,
    rtl_dlrs_24p,
    rtl_trns_24p,
    tot_dlrs_24p_avg,
    cat_dlrs_24p_avg,
    rtl_dlrs_24p_avg,
    web_dlrs_24p_avg,
    NULLIF(RTRIM(tot_trns_24p_code),''),
    NULLIF(RTRIM(cat_trns_24p_code),''),
    NULLIF(RTRIM(rtl_trns_24p_code),''),
    NULLIF(RTRIM(web_trns_24p_code),''),
    NULLIF(RTRIM(tot_dlrs_24p_code),''),
    NULLIF(RTRIM(cat_dlrs_24p_code),''),
    NULLIF(RTRIM(rtl_dlrs_24p_code),''),
    NULLIF(RTRIM(web_dlrs_24p_code),''),
    NULLIF(RTRIM(tot_dlrs_24p_avg_code),''),
    NULLIF(RTRIM(cat_dlrs_24p_avg_code),''),
    NULLIF(RTRIM(rtl_dlrs_24p_avg_code),''),
    NULLIF(RTRIM(web_dlrs_24p_avg_code),''),
    NULLIF(RTRIM(channeltype_code_3m),''),
    NULLIF(RTRIM(channeltype_code_6m),''),
    NULLIF(RTRIM(channeltype_code_12m),'')
FROM tblchild1_{build_id}_{build}_load;

UNLOAD ('select * from tblchild1_{build_id}_{build}')
TO 's3://{s3-axle-gold}/mgen/{s3_folder_today}/mgen-hhld/'
iam_role '{iam}'
manifest verbose
FORMAT PARQUET;


DROP TABLE IF EXISTS tblchild1_{build_id}_{build}_load;
