drop table if exists tblchild35_mgen_tobedropped_load CASCADE;

create table tblchild35_mgen_tobedropped_load
(
statep VARCHAR(2) ENCODE RAW,
county_name VARCHAR(24) ENCODE RAW,
state_code VARCHAR(2) ENCODE RAW,
county_code VARCHAR(3) ENCODE RAW,
obama08_varchar VARCHAR(10) ENCODE RAW,
mccain08_varchar VARCHAR(10) ENCODE RAW,
allother08_varchar VARCHAR(9) ENCODE RAW,
total08_varchar VARCHAR(11) ENCODE RAW,
top2_diff08_varchar VARCHAR(9) ENCODE RAW,
bo_pct08_varchar VARCHAR(6) ENCODE RAW,
jm_pct08_varchar VARCHAR(6) ENCODE RAW,
pct_diff_2008_varchar VARCHAR(6) ENCODE RAW,
winner_2008 VARCHAR(3) ENCODE RAW,
spoiler08_varchar VARCHAR(1) ENCODE RAW,
winmargin08 VARCHAR(1) ENCODE RAW,
obama12_varchar VARCHAR(10) ENCODE RAW,
romney12_varchar VARCHAR(10) ENCODE RAW,
johnson12_varchar VARCHAR(9) ENCODE RAW,
stein12_varchar VARCHAR(7) ENCODE RAW,
allother12_varchar VARCHAR(7) ENCODE RAW,
total12_varchar VARCHAR(11) ENCODE RAW,
top2_diff12_varchar VARCHAR(9) ENCODE RAW,
bo12_pct_varchar VARCHAR(6) ENCODE RAW,
mr12_pct_varchar VARCHAR(6) ENCODE RAW,
pct_diff_2012_varchar VARCHAR(6) ENCODE RAW,
winner_2012 VARCHAR(3) ENCODE RAW,
flip_2012 VARCHAR(3) ENCODE RAW,
spoiler12 VARCHAR(4) ENCODE RAW,
swing0812 VARCHAR(4) ENCODE RAW,
winmargin12 VARCHAR(1) ENCODE RAW,
clinton16_varchar VARCHAR(10) ENCODE RAW,
trump16_varchar VARCHAR(10) ENCODE RAW,
johnson16_varchar VARCHAR(9) ENCODE RAW,
stein_mc16_varchar VARCHAR(9) ENCODE RAW,
all_othr16_varchar VARCHAR(9) ENCODE RAW,
total16_varchar VARCHAR(11) ENCODE RAW,
top2_diff16_varchar VARCHAR(9) ENCODE RAW,
hrc_pct_16_varchar VARCHAR(6) ENCODE RAW,
djt_pct_16_varchar VARCHAR(6) ENCODE RAW,
pct_diff_2016_varchar VARCHAR(6) ENCODE RAW,
winner_2016 VARCHAR(3) ENCODE RAW,
flip_2016 VARCHAR(3) ENCODE RAW,
spoiler16 VARCHAR(4) ENCODE RAW,
swing_1216d VARCHAR(4) ENCODE RAW,
swing_1216r VARCHAR(4) ENCODE RAW,
winmargin16 VARCHAR(1) ENCODE RAW,
last3result VARCHAR(7) ENCODE RAW,
statecountycode VARCHAR(5) ENCODE RAW,
obama08 INT ENCODE RAW,
mccain08 INT ENCODE RAW,
allother08 INT ENCODE RAW,
total08 INT ENCODE RAW,
top2_diff08 INT ENCODE RAW,
bo_pct08 DECIMAL(6,2) ENCODE RAW,
jm_pct08 DECIMAL(6,2) ENCODE RAW,
pct_diff_2008 DECIMAL(6,2) ENCODE RAW,
spoiler08 INT ENCODE RAW,
obama12 INT ENCODE RAW,
romney12 INT ENCODE RAW,
johnson12 INT ENCODE RAW,
stein12 INT ENCODE RAW,
allother12 INT ENCODE RAW,
total12 INT ENCODE RAW,
top2_diff12 INT ENCODE RAW,
bo12_pct DECIMAL(6,2) ENCODE RAW,
mr12_pct DECIMAL(6,2) ENCODE RAW,
pct_diff_2012 DECIMAL(6,2) ENCODE RAW,
clinton16 INT ENCODE RAW,
trump16 INT ENCODE RAW,
johnson16 INT ENCODE RAW,
stein_mc16 INT ENCODE RAW,
all_othr16 INT ENCODE RAW,
total16 INT ENCODE RAW,
top2_diff16 INT ENCODE RAW,
hrc_pct_16 DECIMAL(6,2) ENCODE RAW,
djt_pct_16 DECIMAL(6,2) ENCODE RAW,
pct_diff_2016 DECIMAL(6,2) ENCODE RAW
);

COPY tblchild35_mgen_tobedropped_load
(
statep,
county_name,
state_code,
county_code,
obama08_varchar,
mccain08_varchar,
allother08_varchar,
total08_varchar,
top2_diff08_varchar,
bo_pct08_varchar,
jm_pct08_varchar,
pct_diff_2008_varchar,
winner_2008,
spoiler08_varchar,
winmargin08,
obama12_varchar,
romney12_varchar,
johnson12_varchar,
stein12_varchar,
allother12_varchar,
total12_varchar,
top2_diff12_varchar,
bo12_pct_varchar,
mr12_pct_varchar,
pct_diff_2012_varchar,
winner_2012,
flip_2012,
spoiler12,
swing0812,
winmargin12,
clinton16_varchar,
trump16_varchar,
johnson16_varchar,
stein_mc16_varchar,
all_othr16_varchar,
total16_varchar,
top2_diff16_varchar,
hrc_pct_16_varchar,
djt_pct_16_varchar,
pct_diff_2016_varchar,
winner_2016,
flip_2016,
spoiler16,
swing_1216d,
swing_1216r,
winmargin16,
last3result
)
from 's3://{s3-internal}/neptune/mGen/Child35_PresidentialWinMargin2008_2016.txt'
iam_role '{iam}'
delimiter '|' ignoreheader 1;


drop table if exists tblchild35_mgen_tobedropped CASCADE;

create table tblchild35_mgen_tobedropped
(
statep VARCHAR(2) ENCODE RAW,
county_name VARCHAR(24) ENCODE RAW,
state_code VARCHAR(2) ENCODE RAW,
county_code VARCHAR(3) ENCODE RAW,
obama08_varchar VARCHAR(10) ENCODE RAW,
mccain08_varchar VARCHAR(10) ENCODE RAW,
allother08_varchar VARCHAR(9) ENCODE RAW,
total08_varchar VARCHAR(11) ENCODE RAW,
top2_diff08_varchar VARCHAR(9) ENCODE RAW,
bo_pct08_varchar VARCHAR(6) ENCODE RAW,
jm_pct08_varchar VARCHAR(6) ENCODE RAW,
pct_diff_2008_varchar VARCHAR(6) ENCODE RAW,
winner_2008 VARCHAR(3) ENCODE RAW,
spoiler08_varchar VARCHAR(1) ENCODE RAW,
winmargin08 VARCHAR(1) ENCODE RAW,
obama12_varchar VARCHAR(10) ENCODE RAW,
romney12_varchar VARCHAR(10) ENCODE RAW,
johnson12_varchar VARCHAR(9) ENCODE RAW,
stein12_varchar VARCHAR(7) ENCODE RAW,
allother12_varchar VARCHAR(7) ENCODE RAW,
total12_varchar VARCHAR(11) ENCODE RAW,
top2_diff12_varchar VARCHAR(9) ENCODE RAW,
bo12_pct_varchar VARCHAR(6) ENCODE RAW,
mr12_pct_varchar VARCHAR(6) ENCODE RAW,
pct_diff_2012_varchar VARCHAR(6) ENCODE RAW,
winner_2012 VARCHAR(3) ENCODE RAW,
flip_2012 VARCHAR(3) ENCODE RAW,
spoiler12 VARCHAR(4) ENCODE RAW,
swing0812 VARCHAR(4) ENCODE RAW,
winmargin12 VARCHAR(1) ENCODE RAW,
clinton16_varchar VARCHAR(10) ENCODE RAW,
trump16_varchar VARCHAR(10) ENCODE RAW,
johnson16_varchar VARCHAR(9) ENCODE RAW,
stein_mc16_varchar VARCHAR(9) ENCODE RAW,
all_othr16_varchar VARCHAR(9) ENCODE RAW,
total16_varchar VARCHAR(11) ENCODE RAW,
top2_diff16_varchar VARCHAR(9) ENCODE RAW,
hrc_pct_16_varchar VARCHAR(6) ENCODE RAW,
djt_pct_16_varchar VARCHAR(6) ENCODE RAW,
pct_diff_2016_varchar VARCHAR(6) ENCODE RAW,
winner_2016 VARCHAR(3) ENCODE RAW,
flip_2016 VARCHAR(3) ENCODE RAW,
spoiler16 VARCHAR(4) ENCODE RAW,
swing_1216d VARCHAR(4) ENCODE RAW,
swing_1216r VARCHAR(4) ENCODE RAW,
winmargin16 VARCHAR(1) ENCODE RAW,
last3result VARCHAR(7) ENCODE RAW,
statecountycode VARCHAR(5) ENCODE RAW,
obama08 INT ENCODE RAW,
mccain08 INT ENCODE RAW,
allother08 INT ENCODE RAW,
total08 INT ENCODE RAW,
top2_diff08 INT ENCODE RAW,
bo_pct08 DECIMAL(6,2) ENCODE RAW,
jm_pct08 DECIMAL(6,2) ENCODE RAW,
pct_diff_2008 DECIMAL(6,2) ENCODE RAW,
spoiler08 INT ENCODE RAW,
obama12 INT ENCODE RAW,
romney12 INT ENCODE RAW,
johnson12 INT ENCODE RAW,
stein12 INT ENCODE RAW,
allother12 INT ENCODE RAW,
total12 INT ENCODE RAW,
top2_diff12 INT ENCODE RAW,
bo12_pct DECIMAL(6,2) ENCODE RAW,
mr12_pct DECIMAL(6,2) ENCODE RAW,
pct_diff_2012 DECIMAL(6,2) ENCODE RAW,
clinton16 INT ENCODE RAW,
trump16 INT ENCODE RAW,
johnson16 INT ENCODE RAW,
stein_mc16 INT ENCODE RAW,
all_othr16 INT ENCODE RAW,
total16 INT ENCODE RAW,
top2_diff16 INT ENCODE RAW,
hrc_pct_16 DECIMAL(6,2) ENCODE RAW,
djt_pct_16 DECIMAL(6,2) ENCODE RAW,
pct_diff_2016 DECIMAL(6,2) ENCODE RAW
);

INSERT INTO tblchild35_mgen_tobedropped
(
	statep,
	county_name,
	state_code,
	county_code,
	statecountycode,
	obama08_varchar,
 	mccain08_varchar,
 	allother08_varchar,
 	total08_varchar,
 	top2_diff08_varchar,
 	bo_pct08_varchar,
 	jm_pct08_varchar,
 	pct_diff_2008_varchar,
 	winner_2008,
 	spoiler08_varchar,
 	winmargin08,
 	obama12_varchar,
 	romney12_varchar,
 	johnson12_varchar,
 	stein12_varchar,
 	allother12_varchar,
 	total12_varchar,
 	top2_diff12_varchar,
 	bo12_pct_varchar,
 	mr12_pct_varchar,
 	pct_diff_2012_varchar,
 	winner_2012,
	flip_2012,
	spoiler12,
	swing0812,
	winmargin12,
 	clinton16_varchar,
 	trump16_varchar,
 	johnson16_varchar,
 	stein_mc16_varchar,
 	all_othr16_varchar,
 	total16_varchar,
 	top2_diff16_varchar,
 	hrc_pct_16_varchar,
 	djt_pct_16_varchar,
 	pct_diff_2016_varchar,
 	winner_2016,
	flip_2016,
	spoiler16,
	swing_1216d,
	swing_1216r,
	winmargin16,
	last3result,
 	obama08,
	mccain08,
	allother08,
	total08,
	top2_diff08,
	bo_pct08,
	jm_pct08,
	pct_diff_2008,
	spoiler08,
	obama12,
	romney12,
	johnson12,
	stein12,
	allother12,
	total12,
	top2_diff12,
	bo12_pct,
	mr12_pct,
	pct_diff_2012,
	clinton16,
	trump16,
	johnson16,
	stein_mc16,
	all_othr16,
	total16,
	top2_diff16,
	hrc_pct_16,
	djt_pct_16,
	pct_diff_2016
)
select
statep,
upper(county_name),
state_code,
county_code,
ltrim(rtrim(state_code))+ ltrim(rtrim(county_code )),
CASE WHEN (obama08_varchar is null or ltrim(trim(obama08_varchar)) ='') THEN '0'  ELSE obama08_varchar END,
CASE WHEN (mccain08_varchar is null or ltrim(trim(mccain08_varchar)) ='') THEN '0'  ELSE mccain08_varchar END,
CASE WHEN (allother08_varchar is null or ltrim(trim(allother08_varchar)) ='') THEN '0'  ELSE allother08_varchar END,
CASE WHEN (total08_varchar is null or ltrim(trim(total08_varchar)) ='') THEN '0'  ELSE total08_varchar END,
CASE WHEN (top2_diff08_varchar is null or ltrim(trim(top2_diff08_varchar)) ='') THEN '0'  ELSE top2_diff08_varchar END,
CASE WHEN (bo_pct08_varchar is null or ltrim(trim(bo_pct08_varchar)) ='') THEN '0'  ELSE bo_pct08_varchar END,
CASE WHEN (jm_pct08_varchar is null or ltrim(trim(jm_pct08_varchar)) ='') THEN '0'  ELSE jm_pct08_varchar END,
CASE WHEN (pct_diff_2008_varchar is null or ltrim(trim(pct_diff_2008_varchar)) ='') THEN '0'  ELSE pct_diff_2008_varchar END,
winner_2008,
CASE WHEN (spoiler08_varchar is null or ltrim(trim(spoiler08_varchar)) ='') THEN '0'  ELSE spoiler08_varchar END,
winmargin08,
CASE WHEN (obama12_varchar is null or ltrim(trim(obama12_varchar)) ='') THEN '0'  ELSE obama12_varchar END,
CASE WHEN (romney12_varchar is null or ltrim(trim(romney12_varchar)) ='') THEN '0'  ELSE romney12_varchar END,
CASE WHEN (johnson12_varchar is null or ltrim(trim(johnson12_varchar)) ='') THEN '0'  ELSE johnson12_varchar END,
CASE WHEN (stein12_varchar is null or ltrim(trim(stein12_varchar)) ='') THEN '0'  ELSE stein12_varchar END,
CASE WHEN (allother12_varchar is null or ltrim(trim(allother12_varchar)) ='') THEN '0'  ELSE allother12_varchar END,
CASE WHEN (total12_varchar is null or ltrim(trim(total12_varchar)) ='') THEN '0'  ELSE total12_varchar END,
CASE WHEN (top2_diff12_varchar is null or ltrim(trim(top2_diff12_varchar)) ='') THEN '0'  ELSE top2_diff12_varchar END,
CASE WHEN (bo12_pct_varchar is null or ltrim(trim(bo12_pct_varchar)) ='') THEN '0'  ELSE bo12_pct_varchar END,
CASE WHEN (mr12_pct_varchar is null or ltrim(trim(mr12_pct_varchar)) ='') THEN '0'  ELSE mr12_pct_varchar END,
CASE WHEN (pct_diff_2012_varchar is null or ltrim(trim(pct_diff_2012_varchar)) ='') THEN '0'  ELSE pct_diff_2012_varchar END,
winner_2012,
flip_2012,
spoiler12,
swing0812,
winmargin12,
CASE WHEN (clinton16_varchar is null or ltrim(trim(clinton16_varchar)) ='') THEN '0'  ELSE clinton16_varchar END,
CASE WHEN (trump16_varchar is null or ltrim(trim(trump16_varchar)) ='') THEN '0'  ELSE trump16_varchar END,
CASE WHEN (johnson16_varchar is null or ltrim(trim(johnson16_varchar)) ='') THEN '0'  ELSE johnson16_varchar END,
CASE WHEN (stein_mc16_varchar is null or ltrim(trim(stein_mc16_varchar)) ='') THEN '0'  ELSE stein_mc16_varchar END,
CASE WHEN (all_othr16_varchar is null or ltrim(trim(all_othr16_varchar)) ='') THEN '0'  ELSE all_othr16_varchar END,
CASE WHEN (total16_varchar is null or ltrim(trim(total16_varchar)) ='') THEN '0'  ELSE total16_varchar END,
CASE WHEN (top2_diff16_varchar is null or ltrim(trim(top2_diff16_varchar)) ='') THEN '0'  ELSE top2_diff16_varchar END,
CASE WHEN (hrc_pct_16_varchar is null or ltrim(trim(hrc_pct_16_varchar)) ='') THEN '0'  ELSE hrc_pct_16_varchar END,
CASE WHEN (djt_pct_16_varchar is null or ltrim(trim(djt_pct_16_varchar)) ='') THEN '0'  ELSE djt_pct_16_varchar END,
CASE WHEN (pct_diff_2016_varchar is null or ltrim(trim(pct_diff_2016_varchar)) ='') THEN '0'  ELSE pct_diff_2016_varchar END,
winner_2016,
flip_2016,
spoiler16,
swing_1216d,
swing_1216r,
winmargin16,
last3result,
cast(replace(replace(CASE WHEN (obama08_varchar is null or ltrim(trim(obama08_varchar)) ='') THEN '0'  ELSE obama08_varchar END ,'%',''),',','') as INT),                       
cast(replace(replace(CASE WHEN (mccain08_varchar is null or ltrim(trim(mccain08_varchar)) ='') THEN '0'  ELSE mccain08_varchar END ,'%',''),',','') as INT),                      
cast(replace(replace(CASE WHEN (allother08_varchar is null or ltrim(trim(allother08_varchar)) ='') THEN '0'  ELSE allother08_varchar END ,'%',''),',','') as INT),                    
cast(replace(replace(CASE WHEN (total08_varchar is null or ltrim(trim(total08_varchar)) ='') THEN '0'  ELSE total08_varchar END ,'%',''),',','') as INT),                       
cast(replace(replace(CASE WHEN (top2_diff08_varchar is null or ltrim(trim(top2_diff08_varchar)) ='') THEN '0'  ELSE top2_diff08_varchar END ,'%',''),',','') as INT),                   
cast(replace(replace(CASE WHEN (bo_pct08_varchar is null or ltrim(trim(bo_pct08_varchar)) ='') THEN '0'  ELSE bo_pct08_varchar END ,'%',''),',','') as  DECIMAL(6,2)),             
cast(replace(replace(CASE WHEN (jm_pct08_varchar is null or ltrim(trim(jm_pct08_varchar)) ='') THEN '0'  ELSE jm_pct08_varchar END ,'%',''),',','') as  DECIMAL(6,2)),             
cast(replace(replace(CASE WHEN (pct_diff_2008_varchar is null or ltrim(trim(pct_diff_2008_varchar)) ='') THEN '0'  ELSE pct_diff_2008_varchar END ,'%',''),',','') as  DECIMAL(6,2)),        
cast(replace(replace(CASE WHEN (spoiler08_varchar is null or ltrim(trim(spoiler08_varchar)) ='') THEN '0'  ELSE spoiler08_varchar END ,'%',''),',','') as INT),                     
cast(replace(replace(CASE WHEN (obama12_varchar is null or ltrim(trim(obama12_varchar)) ='') THEN '0'  ELSE obama12_varchar END ,'%',''),',','') as INT),                       
cast(replace(replace(CASE WHEN (romney12_varchar is null or ltrim(trim(romney12_varchar)) ='') THEN '0'  ELSE romney12_varchar END ,'%',''),',','') as INT),                      
cast(replace(replace(CASE WHEN (johnson12_varchar is null or ltrim(trim(johnson12_varchar)) ='') THEN '0'  ELSE johnson12_varchar END ,'%',''),',','') as INT),                     
cast(replace(replace(CASE WHEN (stein12_varchar is null or ltrim(trim(stein12_varchar)) ='') THEN '0'  ELSE stein12_varchar END ,'%',''),',','') as INT),                       
cast(replace(replace(CASE WHEN (allother12_varchar is null or ltrim(trim(allother12_varchar)) ='') THEN '0'  ELSE allother12_varchar END ,'%',''),',','') as INT),                    
cast(replace(replace(CASE WHEN (total12_varchar is null or ltrim(trim(total12_varchar)) ='') THEN '0'  ELSE total12_varchar END ,'%',''),',','') as INT),                       
cast(replace(replace(CASE WHEN (top2_diff12_varchar is null or ltrim(trim(top2_diff12_varchar)) ='') THEN '0'  ELSE top2_diff12_varchar END ,'%',''),',','') as INT),                   
cast(replace(replace(CASE WHEN (bo12_pct_varchar is null or ltrim(trim(bo12_pct_varchar)) ='') THEN '0'  ELSE bo12_pct_varchar END ,'%',''),',','') as  DECIMAL(6,2)),             
cast(replace(replace(CASE WHEN (mr12_pct_varchar is null or ltrim(trim(mr12_pct_varchar)) ='') THEN '0'  ELSE mr12_pct_varchar END ,'%',''),',','') as  DECIMAL(6,2)),             
cast(replace(replace(CASE WHEN (pct_diff_2012_varchar is null or ltrim(trim(pct_diff_2012_varchar)) ='') THEN '0'  ELSE pct_diff_2012_varchar END ,'%',''),',','') as  DECIMAL(6,2)),        
cast(replace(replace(CASE WHEN (clinton16_varchar is null or ltrim(trim(clinton16_varchar)) ='') THEN '0'  ELSE clinton16_varchar END ,'%',''),',','') as INT),                     
cast(replace(replace(CASE WHEN (trump16_varchar is null or ltrim(trim(trump16_varchar)) ='') THEN '0'  ELSE trump16_varchar END ,'%',''),',','') as INT),                       
cast(replace(replace(CASE WHEN (johnson16_varchar is null or ltrim(trim(johnson16_varchar)) ='') THEN '0'  ELSE johnson16_varchar END ,'%',''),',','') as INT),                    
cast(replace(replace(CASE WHEN (stein_mc16_varchar is null or ltrim(trim(stein_mc16_varchar)) ='') THEN '0'  ELSE stein_mc16_varchar END ,'%',''),',','') as INT),                    
cast(replace(replace(CASE WHEN (all_othr16_varchar is null or ltrim(trim(all_othr16_varchar)) ='') THEN '0'  ELSE all_othr16_varchar END ,'%',''),',','') as INT),                    
cast(replace(replace(CASE WHEN (total16_varchar is null or ltrim(trim(total16_varchar)) ='') THEN '0'  ELSE total16_varchar END ,'%',''),',','') as INT),                       
cast(replace(replace(CASE WHEN (top2_diff16_varchar is null or ltrim(trim(top2_diff16_varchar)) ='') THEN '0'  ELSE top2_diff16_varchar END ,'%',''),',','') as INT),                   
cast(replace(replace(CASE WHEN (hrc_pct_16_varchar is null or ltrim(trim(hrc_pct_16_varchar)) ='') THEN '0'  ELSE hrc_pct_16_varchar END ,'%',''),',','') as  DECIMAL(6,2)),           
cast(replace(replace(CASE WHEN (djt_pct_16_varchar is null or ltrim(trim(djt_pct_16_varchar)) ='') THEN '0'  ELSE djt_pct_16_varchar END ,'%',''),',','') as  DECIMAL(6,2)),           
cast(replace(replace(CASE WHEN (pct_diff_2016_varchar is null or ltrim(trim(pct_diff_2016_varchar)) ='') THEN '0'  ELSE pct_diff_2016_varchar END ,'%',''),',','') as  DECIMAL(6,2))
FROM tblchild35_mgen_tobedropped_load
WHERE ltrim(rtrim(state_code))+ ltrim(rtrim(county_code )) <> '';

DROP TABLE IF EXISTS tblchild35_{build_id}_{build} CASCADE;
alter table tblchild35_mgen_tobedropped rename to tblchild35_{build_id}_{build};
DROP TABLE IF EXISTS tblchild35_mgen_tobedropped_load;

UNLOAD ('select * from tblchild35_{build_id}_{build}')
TO 's3://{s3-axle-gold}/mgen/{s3_folder_today}/mgen-presidential-win-margin/'
iam_role '{iam}'
manifest verbose
FORMAT PARQUET;