DROP TABLE IF EXISTS {tablename1};
CREATE TABLE  {tablename1}
(
ID bigint identity unique encode az64,
MMDBKey	VARCHAR(12) encode zstd,
PartyType	VARCHAR(1) encode zstd,
FilingState	VARCHAR(2) encode zstd,
IUSAkey	VARCHAR(19) encode zstd,
OriginalFilingID	VARCHAR(30) encode zstd,
SourceFilingID	VARCHAR(30) encode zstd,
FilingDate	VARCHAR(8) encode zstd,
FilingStatus	VARCHAR(1) encode zstd,
FilingTypeCode	VARCHAR(2) encode zstd,
DateAdded	VARCHAR(8) encode zstd,
DateLastReceived	VARCHAR(8) encode zstd,
ExpirationDate	VARCHAR(8) encode zstd,
CorporateIndividual	VARCHAR(1) encode zstd,
Abinumber	VARCHAR(9) encode zstd,
LocationName	VARCHAR(40) encode zstd,
LastName	VARCHAR(50) encode zstd,
FirstName	VARCHAR(50) encode zstd,
MiddleName	VARCHAR(50) encode zstd,
NameSuffix	VARCHAR(50) encode zstd,
Address	VARCHAR(40) encode zstd,
City	VARCHAR(28) encode zstd,
State	VARCHAR(2) encode zstd,
ZipCode	VARCHAR(5) encode zstd,
ZipFour	VARCHAR(4) encode zstd,
DeliveryPointBarCode	VARCHAR(3) encode zstd,
DeliverabilityScore	VARCHAR(2) encode zstd,
CarrierRouteCode	VARCHAR(4) encode bytedict,
USPSRecordType	VARCHAR(2) encode zstd,
MatchType	VARCHAR(1) encode zstd,
MatchScore	VARCHAR(2) encode zstd,
FullfillmentFlag	VARCHAR(1) encode zstd,
PrimarySIC	VARCHAR(6) encode zstd,
SIC1	VARCHAR(6) encode zstd,
SIC2	VARCHAR(6) encode zstd,
SIC3	VARCHAR(6) encode zstd,
SIC4	VARCHAR(6) encode zstd,
NumberEmployees	VARCHAR(5) encode zstd,
OutputVolume	VARCHAR(9) encode zstd,
OutputVolumeCode	VARCHAR(1) encode zstd,
SecuredParty1LocationName	VARCHAR(40) encode zstd,
SecuredParty1Abinumber	VARCHAR(9) encode zstd,
SecuredParty2LocationName	VARCHAR(40) encode zstd,
SecuredParty2Abinumber	VARCHAR(9) encode zstd,
SecuredParty3LocationName	VARCHAR(40) encode zstd,
SecuredParty3Abinumber	VARCHAR(9) encode zstd,
SecuredParty4LocationName	VARCHAR(40) encode zstd,
SecuredParty4Abinumber	VARCHAR(9) encode zstd,
SecuredParty5LocationName	VARCHAR(40) encode zstd,
SecuredParty5Abinumber	VARCHAR(9) encode zstd,
SecuredParty6LocationName	VARCHAR(40) encode zstd,
SecuredParty6Abinumber	VARCHAR(9) encode zstd,
SecuredParty7LocationName	VARCHAR(40) encode zstd,
SecuredParty7Abinumber	VARCHAR(9) encode zstd,
SecuredParty8LocationName	VARCHAR(40) encode zstd,
SecuredParty8Abinumber	VARCHAR(9) encode zstd,
SecuredParty9LocationName	VARCHAR(40) encode zstd,
SecuredParty9Abinumber	VARCHAR(9) encode zstd,
SecuredParty10LocationName	VARCHAR(40) encode zstd,
SecuredParty10Abinumber	VARCHAR(9) encode zstd,
CollateralType1	VARCHAR(3) encode zstd,
CollateralType2	VARCHAR(3) encode zstd,
CollateralType3	VARCHAR(3) encode zstd,
CollateralType4	VARCHAR(3) encode zstd,
CollateralType5	VARCHAR(3) encode zstd,
CollateralType6	VARCHAR(3) encode zstd,
CollateralType7	VARCHAR(3) encode zstd,
CollateralType8	VARCHAR(3) encode zstd,
CollateralType9	VARCHAR(3) encode zstd,
CollateralType10	VARCHAR(3) encode zstd,
StateCode VARCHAR (2) encode zstd,
CountyCode VARCHAR(3) encode bytedict,
CountyDescription VARCHAR(14))
DISTKEY (ID)
SORTKEY (ID);

COPY {tablename1}
from 's3://idms-7933-internalfiles/uccx/debtors.txt.gz'
iam_role 'arn:aws:iam::479134617933:role/da-idms-redshift-role'
fixedwidth
'MMDBKey:12,
PartyType:1,
FilingState:2,
IUSAkey:19,
OriginalFilingID:30,
SourceFilingID:30,
FilingDate:8,
FilingStatus:1,
FilingTypeCode:2,
DateAdded:8,
DateLastReceived:8,
ExpirationDate:8,
CorporateIndividual:1,
Abinumber:9,
LocationName:40,
LastName:50,
FirstName:50,
MiddleName:50,
NameSuffix:50,
Address:40,
City:28,
State:2,
ZipCode:5,
ZipFour:4,
DeliveryPointBarCode:3,
DeliverabilityScore:2,
CarrierRouteCode:4,
USPSRecordType:2,
MatchType:1,
MatchScore:2,
FullfillmentFlag:1,
PrimarySIC:6,
SIC1:6,
SIC2:6,
SIC3:6,
SIC4:6,
NumberEmployees:5,
OutputVolume:9,
OutputVolumeCode:1,
SecuredParty1LocationName:40,
SecuredParty1Abinumber:9,
SecuredParty2LocationName:40,
SecuredParty2Abinumber:9,
SecuredParty3LocationName:40,
SecuredParty3Abinumber:9,
SecuredParty4LocationName:40,
SecuredParty4Abinumber:9,
SecuredParty5LocationName:40,
SecuredParty5Abinumber:9,
SecuredParty6LocationName:40,
SecuredParty6Abinumber:9,
SecuredParty7LocationName:40,
SecuredParty7Abinumber:9,
SecuredParty8LocationName:40,
SecuredParty8Abinumber:9,
SecuredParty9LocationName:40,
SecuredParty9Abinumber:9,
SecuredParty10LocationName:40,
SecuredParty10Abinumber:9,
CollateralType1:3,
CollateralType2:3,
CollateralType3:3,
CollateralType4:3,
CollateralType5:3,
CollateralType6:3,
CollateralType7:3,
CollateralType8:3,
CollateralType9:3,
CollateralType10:3,
StateCode:2,
CountyCode:3,
CountyDescription:14'
GZIP ACCEPTINVCHARS IGNOREBLANKLINES MAXERROR 1200;


DROP TABLE IF EXISTS {tablename2};
CREATE TABLE  {tablename2}
(
ID bigint identity unique encode delta32k,
MMDBKey	VARCHAR(12) encode zstd,
PartyType	VARCHAR(1) encode zstd,
FilingState	VARCHAR(2) encode zstd,
IUSAkey	VARCHAR(19) encode zstd,
OriginalFilingID	VARCHAR(30) encode zstd,
SourceFilingID	VARCHAR(30) encode zstd,
FilingDate	VARCHAR(8) encode zstd,
FilingStatus	VARCHAR(1) encode zstd,
FilingTypeCode	VARCHAR(2) encode zstd,
CorporateIndividual	VARCHAR(1) encode zstd,
Abinumber	VARCHAR(9) encode zstd,
LocationName	VARCHAR(40) encode zstd,
LastName	VARCHAR(50) encode zstd,
FirstName	VARCHAR(50) encode zstd,
MiddleName	VARCHAR(50) encode zstd,
NameSuffix	VARCHAR(50) encode zstd,
Address	VARCHAR(40) encode zstd,--
City	VARCHAR(28) encode zstd,--
State	VARCHAR(2) encode zstd,
ZipCode	VARCHAR(5) encode zstd,
ZipFour	VARCHAR(4) encode zstd,
DeliveryPointBarCode	VARCHAR(3) encode zstd,
DeliverabilityScore	VARCHAR(2) encode zstd,
CarrierRouteCode	VARCHAR(4) encode bytedict,
USPSRecordType	VARCHAR(2) encode zstd,
MatchType	VARCHAR(1) encode zstd,
MatchScore	VARCHAR(2) encode zstd,
FullfillmentFlag	VARCHAR(1) encode zstd,
PrimarySIC	VARCHAR(6) encode zstd,
SIC1	VARCHAR(6) encode zstd,
SIC2	VARCHAR(6) encode zstd,
SIC3	VARCHAR(6) encode zstd,
SIC4	VARCHAR(6) encode zstd,
NumberEmployees	VARCHAR(5) encode bytedict,
OutputVolume	VARCHAR(9) encode zstd,
OutputVolumeCode	VARCHAR(1))
DISTKEY (ID)
SORTKEY(ID);



COPY {tablename2}
from 's3://idms-7933-internalfiles/uccx/secured.parties.txt.gz'
iam_role 'arn:aws:iam::479134617933:role/da-idms-redshift-role' 
fixedwidth
'MMDBKey:12,
PartyType:1,
FilingState:2,
IUSAkey:19,
OriginalFilingID:30,
SourceFilingID:30,
FilingDate:8,
FilingStatus:1,
FilingTypeCode:2,w
CorporateIndividual:1,
Abinumber:9,
LocationName:40,
LastName:50,
FirstName:50,
MiddleName:50,
NameSuffix:50,
Address:40,
City:28,
State:2,
ZipCode:5,
ZipFour:4,
DeliveryPointBarCode:3,
DeliverabilityScore:2,
CarrierRouteCode:4,
USPSRecordType:2,
MatchType:1,
MatchScore:2,
FullfillmentFlag:1,
PrimarySIC:6,
SIC1:6,
SIC2:6,
SIC3:6,
SIC4:6,
NumberEmployees:5,
OutputVolume:9,
OutputVolumeCode:1'
GZIP ACCEPTINVCHARS IGNOREBLANKLINES MAXERROR 1200;