DROP TABLE IF EXISTS {HarteHanks-stage-table};
CREATE TABLE {HarteHanks-stage-table} 
(
   id INT ENCODE AZ64,
   tdus_first_name VARCHAR(25) ENCODE ZSTD,
   tdus_last_name VARCHAR(25) ENCODE ZSTD,
   tdus_title VARCHAR(75) ENCODE ZSTD,
   tdus_company VARCHAR(75) ENCODE ZSTD,
   tdus_address_line_1 VARCHAR(75) ENCODE ZSTD,
   tdus_address_line_2 VARCHAR(75) ENCODE ZSTD,
   tdus_city VARCHAR(30) ENCODE ZSTD,
   tdus_state VARCHAR(2) ENCODE ZSTD,
   tdus_zip_full VARCHAR(10) ENCODE ZSTD,
   tdus_country_name VARCHAR(30) ENCODE ZSTD,
   tdus_emailaddress VARCHAR(65) ENCODE ZSTD,
   tdus_contact_phone VARCHAR(20) ENCODE ZSTD,
   tdus_valid_email_address VARCHAR(1) ENCODE ZSTD,
   tdus_emple VARCHAR(15) ENCODE ZSTD,
   tdus_reven VARCHAR(15) ENCODE ZSTD,
   tdus_sicgrp VARCHAR(6) ENCODE ZSTD,
   tdus_sicsubgroup VARCHAR(12) ENCODE ZSTD,
   tdus_sicvertical VARCHAR(12) ENCODE ZSTD,
   tdus_dnb_sic2_code VARCHAR(2) ENCODE ZSTD,
   tdus_sic4_code VARCHAR(4) ENCODE ZSTD,
   tdus_language_code VARCHAR(3) ENCODE ZSTD,
   tdus_other_desktops VARCHAR(3) ENCODE ZSTD,
   tdus_other_laptops VARCHAR(3) ENCODE ZSTD,
   tdus_other_workstations VARCHAR(3) ENCODE ZSTD,
   tdus_server_series VARCHAR(12) ENCODE ZSTD,
   tdus_other_servers VARCHAR(3) ENCODE ZSTD,
   tdus_os_model VARCHAR(12) ENCODE ZSTD,
   tdus_other_os VARCHAR(3) ENCODE ZSTD,
   tdus_other_network_printers VARCHAR(3) ENCODE ZSTD,
   tdus_long_distance_carrier VARCHAR(11) ENCODE ZSTD,
   tdus_cell_services_provider VARCHAR(11) ENCODE ZSTD,
   tdus_pbx_maint_provider VARCHAR(11) ENCODE ZSTD,
   tdus_network_line_carrier VARCHAR(11) ENCODE ZSTD,
   tdus_isp_provider VARCHAR(11) ENCODE ZSTD,
   tdus_network_services_provider VARCHAR(11) ENCODE ZSTD,
   tdus_host_remote VARCHAR(20) ENCODE ZSTD,
   tdus_ethernet_tech VARCHAR(12) ENCODE ZSTD,
   tdus_development_sw_tool VARCHAR(11) ENCODE ZSTD,
   tdus_ecommerce_type VARCHAR(15) ENCODE ZSTD,
   tdus_it_staff VARCHAR(12) ENCODE ZSTD,
   tdus_wireless_users VARCHAR(15) ENCODE ZSTD,
   tdus_internet_users VARCHAR(16) ENCODE ZSTD,
   tdus_developers VARCHAR(12) ENCODE ZSTD,
   tdus_callcenter_callers VARCHAR(15) ENCODE ZSTD,
   tdus_pcs VARCHAR(15) ENCODE ZSTD,
   tdus_desktops VARCHAR(15) ENCODE ZSTD,
   tdus_laptops VARCHAR(15) ENCODE ZSTD,
   tdus_servers VARCHAR(15) ENCODE ZSTD,
   tdus_printers VARCHAR(15) ENCODE ZSTD,
   tdus_color_printers VARCHAR(15) ENCODE ZSTD,
   tdus_multifunc_printers VARCHAR(15) ENCODE ZSTD,
   tdus_storage VARCHAR(16) ENCODE ZSTD,
   tdus_network_lines VARCHAR(15) ENCODE ZSTD,
   tdus_extensions VARCHAR(15) ENCODE ZSTD,
   tdus_salesforce VARCHAR(15) ENCODE ZSTD,
   tdus_mobile_workers VARCHAR(15) ENCODE ZSTD,
   tdus_mobile_intl VARCHAR(3) ENCODE ZSTD,
   tdus_fiscl VARCHAR(3) ENCODE ZSTD,
   tdus_year_est VARCHAR(4) ENCODE ZSTD,
   tdus_homepageurl VARCHAR(50) ENCODE ZSTD,
   tdus_channel_flag VARCHAR(3) ENCODE ZSTD,
   tdus_govtlevel VARCHAR(7) ENCODE ZSTD,
   tdus_telco VARCHAR(4) ENCODE ZSTD,
   tdus_telco_name VARCHAR(24) ENCODE ZSTD,
   tdus_voip_hosting VARCHAR(11) ENCODE ZSTD,
   tdus_mobility_contract_expire VARCHAR(6) ENCODE ZSTD,
   tdus_vpn_contract_expire VARCHAR(6) ENCODE ZSTD,
   tdus_it_budget VARCHAR(15) ENCODE ZSTD,
   tdus_hardware_budget VARCHAR(15) ENCODE ZSTD,
   tdus_pc_budget VARCHAR(15) ENCODE ZSTD,
   tdus_server_budget VARCHAR(15) ENCODE ZSTD,
   tdus_other_hardware_budget VARCHAR(15) ENCODE ZSTD,
   tdus_storage_budget VARCHAR(15) ENCODE ZSTD,
   tdus_comm_budget VARCHAR(15) ENCODE ZSTD,
   tdus_software_budget VARCHAR(15) ENCODE ZSTD,
   tdus_services_budget VARCHAR(15) ENCODE ZSTD,
   tdus_desktop_printers VARCHAR(15) ENCODE ZSTD,
   tdus_network_printers VARCHAR(15) ENCODE ZSTD,
   tdus_smartphone_users VARCHAR(15) ENCODE ZSTD,
   tdus_tablets VARCHAR(15) ENCODE ZSTD,
   tdus_workstations VARCHAR(15) ENCODE ZSTD,
   tdus_sw_as_a_service_erp_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_sw_as_a_service_crm_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_sw_as_a_service_storage_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_sw_as_a_service_email_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_sw_as_a_service_other_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_asset_mgmt_sw_manuf VARCHAR(11) ENCODE ZSTD, 
   tdus_enterprise_mgmt_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_storage_mgmt_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_application_server_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_business_intel_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_doc_mgmt_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_app_consolidation_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_human_res_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_supply_chain_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_web_portal_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_email_messaging_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_unified_comm_services_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_video_conf_services_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_network_printer_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_highvolume_printer_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_idaccess_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_tape_library_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_collaborative_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_crm_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_erp_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_accounting_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_datawarehouse_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_desktop_virtualization_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_server_virtualization_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_storage_virtualization_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_antivirus_sw_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_desktop_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_laptop_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_workstation_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_server_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_os_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_copier_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_ups_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_das_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_nas_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_san_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_pbx_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_router_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_switch_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_vpn_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_dbms_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_voip_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_surveillance_manuf VARCHAR(11) ENCODE ZSTD,
   tdus_presence_install_array VARCHAR(200) ENCODE ZSTD,
   tdus_ils_array VARCHAR(80) ENCODE ZSTD,
   tdus_title_array VARCHAR(80) ENCODE ZSTD,
   tdus_function_array VARCHAR(80) ENCODE ZSTD,
   tdus_ent_emple VARCHAR(1) ENCODE ZSTD,
   tdus_ent_reven VARCHAR(1) ENCODE ZSTD,
   company_mc VARCHAR(15) NULL ENCODE ZSTD,
   PRIMARY KEY(company_mc)
)
DISTSTYLE KEY
DISTKEY(company_mc)
SORTKEY(company_mc);

INSERT INTO {HarteHanks-stage-table}
(
    id,
    tdus_first_name,
    tdus_last_name,
    tdus_title,
    tdus_company,
    tdus_address_line_1,
    tdus_address_line_2,
    tdus_city,
    tdus_state,
    tdus_zip_full,
    tdus_country_name,
    tdus_emailaddress,
    tdus_contact_phone,
    tdus_valid_email_address,
    tdus_emple,
    tdus_reven,
    tdus_sicgrp,
    tdus_sicsubgroup,
    tdus_sicvertical,
    tdus_dnb_sic2_code,
    tdus_sic4_code,
    tdus_language_code,
    tdus_other_desktops,
    tdus_other_laptops,
    tdus_other_workstations,
    tdus_server_series,
    tdus_other_servers,
    tdus_os_model,
    tdus_other_os,
    tdus_other_network_printers,
    tdus_long_distance_carrier,
    tdus_cell_services_provider,
    tdus_pbx_maint_provider,
    tdus_network_line_carrier,
    tdus_isp_provider,
    tdus_network_services_provider,
    tdus_host_remote,
    tdus_ethernet_tech,
    tdus_development_sw_tool,
    tdus_ecommerce_type,
    tdus_it_staff,
    tdus_wireless_users,
    tdus_internet_users,
    tdus_developers,
    tdus_callcenter_callers,
    tdus_pcs,
    tdus_desktops,
    tdus_laptops,
    tdus_servers,
    tdus_printers,
    tdus_color_printers,
    tdus_multifunc_printers,
    tdus_storage,
    tdus_network_lines,
    tdus_extensions,
    tdus_salesforce,
    tdus_mobile_workers,
    tdus_mobile_intl,
    tdus_fiscl,
    tdus_year_est,
    tdus_homepageurl,
    tdus_channel_flag,
    tdus_govtlevel,
    tdus_telco,
    tdus_telco_name,
    tdus_voip_hosting,
    tdus_mobility_contract_expire,
    tdus_vpn_contract_expire,
    tdus_it_budget,
    tdus_hardware_budget,
    tdus_pc_budget,
    tdus_server_budget,
    tdus_other_hardware_budget,
    tdus_storage_budget,
    tdus_comm_budget,
    tdus_software_budget,
    tdus_services_budget,
    tdus_desktop_printers,
    tdus_network_printers,
    tdus_smartphone_users,
    tdus_tablets,
    tdus_workstations,
    tdus_sw_as_a_service_erp_manuf,
    tdus_sw_as_a_service_crm_manuf,
    tdus_sw_as_a_service_storage_manuf,
    tdus_sw_as_a_service_email_manuf,
    tdus_sw_as_a_service_other_manuf,
    tdus_asset_mgmt_sw_manuf,
    tdus_enterprise_mgmt_sw_manuf,
    tdus_storage_mgmt_sw_manuf,
    tdus_application_server_sw_manuf,
    tdus_business_intel_sw_manuf,
    tdus_doc_mgmt_sw_manuf,
    tdus_app_consolidation_sw_manuf,
    tdus_human_res_sw_manuf,
    tdus_supply_chain_sw_manuf,
    tdus_web_portal_sw_manuf,
    tdus_email_messaging_sw_manuf,
    tdus_unified_comm_services_manuf,
    tdus_video_conf_services_manuf,
    tdus_network_printer_manuf,
    tdus_highvolume_printer_manuf,
    tdus_idaccess_sw_manuf,
    tdus_tape_library_manuf,
    tdus_collaborative_sw_manuf,
    tdus_crm_sw_manuf,
    tdus_erp_sw_manuf,
    tdus_accounting_sw_manuf,
    tdus_datawarehouse_sw_manuf,
    tdus_desktop_virtualization_manuf,
    tdus_server_virtualization_manuf,
    tdus_storage_virtualization_manuf,
    tdus_antivirus_sw_manuf,
    tdus_desktop_manuf,
    tdus_laptop_manuf,
    tdus_workstation_manuf,
    tdus_server_manuf,
    tdus_os_manuf,
    tdus_copier_manuf,
    tdus_ups_manuf,
    tdus_das_manuf,
    tdus_nas_manuf,
    tdus_san_manuf,
    tdus_pbx_manuf,
    tdus_router_manuf,
    tdus_switch_manuf,
    tdus_vpn_manuf,
    tdus_dbms_manuf,
    tdus_voip_manuf,
    tdus_surveillance_manuf,
    tdus_presence_install_array,
    tdus_ils_array,
    tdus_title_array,
    tdus_function_array,
    tdus_ent_emple,
    tdus_ent_reven,
    company_mc
)
SELECT
      a.id AS id,
      UPPER(a.tdus_first_name),
      UPPER(a.tdus_last_name),
      UPPER(a.tdus_title),
      UPPER(a.tdus_company),
      UPPER(a.tdus_address_line_1),
      UPPER(a.tdus_address_line_2),
      UPPER(a.tdus_city),
      UPPER(a.tdus_state),
      UPPER(a.tdus_zip_full),
      UPPER(a.tdus_country_name),
      UPPER(a.tdus_emailaddress),
      UPPER(a.tdus_contact_phone),
      UPPER(a.tdus_valid_email_address),
      UPPER(a.tdus_emple),
      UPPER(a.tdus_reven),
      UPPER(a.tdus_sicgrp),
      UPPER(a.tdus_sicsubgroup),
      UPPER(a.tdus_sicvertical),
      UPPER(a.tdus_dnb_sic2_code),
      UPPER(a.tdus_sic4_code),
      UPPER(a.tdus_language_code),
      UPPER(a.tdus_other_desktops),
      UPPER(a.tdus_other_laptops),
      UPPER(a.tdus_other_workstations),
      UPPER(a.tdus_server_series),
      UPPER(a.tdus_other_servers),
      UPPER(a.tdus_os_model),
      UPPER(a.tdus_other_os),
      UPPER(a.tdus_other_network_printers),
      UPPER(a.tdus_long_distance_carrier),
      UPPER(a.tdus_cell_services_provider),
      UPPER(a.tdus_pbx_maint_provider),
      UPPER(a.tdus_network_line_carrier),
      UPPER(a.tdus_isp_provider),
      UPPER(a.tdus_network_services_provider),
      UPPER(a.tdus_host_remote),
      UPPER(a.tdus_ethernet_tech),
      UPPER(a.tdus_development_sw_tool),
      UPPER(a.tdus_ecommerce_type),
      UPPER(a.tdus_it_staff),
      UPPER(a.tdus_wireless_users),
      UPPER(a.tdus_internet_users),
      UPPER(a.tdus_developers),
      UPPER(a.tdus_callcenter_callers),
      UPPER(a.tdus_pcs),
      UPPER(a.tdus_desktops),
      UPPER(a.tdus_laptops),
      UPPER(a.tdus_servers),
      UPPER(a.tdus_printers),
      UPPER(a.tdus_color_printers),
      UPPER(a.tdus_multifunc_printers),
      UPPER(a.tdus_storage),
      UPPER(a.tdus_network_lines),
      UPPER(a.tdus_extensions),
      UPPER(a.tdus_salesforce),
      UPPER(a.tdus_mobile_workers),
      UPPER(a.tdus_mobile_intl),
      UPPER(a.tdus_fiscl),
      UPPER(a.tdus_year_est),
      UPPER(a.tdus_homepageurl),
      UPPER(a.tdus_channel_flag),
      UPPER(a.tdus_govtlevel),
      UPPER(a.tdus_telco),
      UPPER(a.tdus_telco_name),
      UPPER(a.tdus_voip_hosting),
      UPPER(a.tdus_mobility_contract_expire),
      UPPER(a.tdus_vpn_contract_expire),
      UPPER(a.tdus_it_budget),
      UPPER(a.tdus_hardware_budget),
      UPPER(a.tdus_pc_budget),
      UPPER(a.tdus_server_budget),
      UPPER(a.tdus_other_hardware_budget),
      UPPER(a.tdus_storage_budget),
      UPPER(a.tdus_comm_budget),
      UPPER(a.tdus_software_budget),
      UPPER(a.tdus_services_budget),
      UPPER(a.tdus_desktop_printers),
      UPPER(a.tdus_network_printers),
      UPPER(a.tdus_smartphone_users),
      UPPER(a.tdus_tablets),
      UPPER(a.tdus_workstations),
      UPPER(a.tdus_sw_as_a_service_erp_manuf),
      UPPER(a.tdus_sw_as_a_service_crm_manuf),
      UPPER(a.tdus_sw_as_a_service_storage_manuf),
      UPPER(a.tdus_sw_as_a_service_email_manuf),
      UPPER(a.tdus_sw_as_a_service_other_manuf),
      UPPER(a.tdus_asset_mgmt_sw_manuf),
      UPPER(a.tdus_enterprise_mgmt_sw_manuf),
      UPPER(a.tdus_storage_mgmt_sw_manuf),
      UPPER(a.tdus_application_server_sw_manuf),
      UPPER(a.tdus_business_intel_sw_manuf),
      UPPER(a.tdus_doc_mgmt_sw_manuf),
      UPPER(a.tdus_app_consolidation_sw_manuf),
      UPPER(a.tdus_human_res_sw_manuf),
      UPPER(a.tdus_supply_chain_sw_manuf),
      UPPER(a.tdus_web_portal_sw_manuf),
      UPPER(a.tdus_email_messaging_sw_manuf),
      UPPER(a.tdus_unified_comm_services_manuf),
      UPPER(a.tdus_video_conf_services_manuf),
      UPPER(a.tdus_network_printer_manuf),
      UPPER(a.tdus_highvolume_printer_manuf),
      UPPER(a.tdus_idaccess_sw_manuf),
      UPPER(a.tdus_tape_library_manuf),
      UPPER(a.tdus_collaborative_sw_manuf),
      UPPER(a.tdus_crm_sw_manuf),
      UPPER(a.tdus_erp_sw_manuf),
      UPPER(a.tdus_accounting_sw_manuf),
      UPPER(a.tdus_datawarehouse_sw_manuf),
      UPPER(a.tdus_desktop_virtualization_manuf),
      UPPER(a.tdus_server_virtualization_manuf),
      UPPER(a.tdus_storage_virtualization_manuf),
      UPPER(a.tdus_antivirus_sw_manuf),
      UPPER(a.tdus_desktop_manuf),
      UPPER(a.tdus_laptop_manuf),
      UPPER(a.tdus_workstation_manuf),
      UPPER(a.tdus_server_manuf),
      UPPER(a.tdus_os_manuf),
      UPPER(a.tdus_copier_manuf),
      UPPER(a.tdus_ups_manuf),
      UPPER(a.tdus_das_manuf),
      UPPER(a.tdus_nas_manuf),
      UPPER(a.tdus_san_manuf),
      UPPER(a.tdus_pbx_manuf),
      UPPER(a.tdus_router_manuf),
      UPPER(a.tdus_switch_manuf),
      UPPER(a.tdus_vpn_manuf),
      UPPER(a.tdus_dbms_manuf),
      UPPER(a.tdus_voip_manuf),
      UPPER(a.tdus_surveillance_manuf),
      UPPER(a.tdus_presence_install_array),
      UPPER(a.tdus_ils_array),
      UPPER(a.tdus_title_array),
      UPPER(a.tdus_function_array),
      UPPER(a.tdus_ent_emple),
      UPPER(a.tdus_ent_reven),
      GetMatchCode(REPLACE(a.tdus_first_name,'|',''), REPLACE(a.tdus_last_name,'|',''), REPLACE(a.tdus_address_line_1,'|',''), REPLACE(REPLACE(a.tdus_zip_full,'|',''),' ', ''), REPLACE(a.tdus_company,'|',''),'C')
FROM {HarteHanks-raw-table} a 
WHERE a.id IN 
(
     SELECT MAX(id) AS id FROM {HarteHanks-raw-table} 
     GROUP BY GetMatchCode(REPLACE(tdus_first_name,'|',''), REPLACE(tdus_last_name,'|',''), REPLACE(tdus_address_line_1,'|',''), REPLACE(REPLACE(tdus_zip_full,'|',''),' ', ''), REPLACE(tdus_company,'|',''),'C')
);


--Rename the stage table
DROP TABLE IF EXISTS {HarteHanks-raw-table};
DROP TABLE IF EXISTS {maintable_name} CASCADE;
ALTER TABLE {HarteHanks-stage-table} RENAME TO {maintable_name};
