DROP TABLE IF EXISTS nosuchtable;
drop table if exists auto_ncoa_out_monthly_infutor;

CREATE TABLE auto_ncoa_out_monthly_infutor
(
    vin VARCHAR(17) ENCODE ZSTD,
    shortvin VARCHAR(10) ENCODE ZSTD,
    fname VARCHAR(30) ENCODE ZSTD,
    mi VARCHAR(1) ENCODE ZSTD,
    lname VARCHAR(30) ENCODE ZSTD,
    addr VARCHAR(50) ENCODE ZSTD,
    city VARCHAR(30) ENCODE ZSTD,
    st VARCHAR(2) ENCODE ZSTD,
    zip VARCHAR(5) ENCODE ZSTD,
    zip4 VARCHAR(4) ENCODE ZSTD,
    dp VARCHAR(2) ENCODE ZSTD,
    scf VARCHAR(3) ENCODE ZSTD,
    gender VARCHAR(1) ENCODE ZSTD,
    make VARCHAR(30) ENCODE BYTEDICT,
    model VARCHAR(30) ENCODE ZSTD,
    year VARCHAR(4) ENCODE BYTEDICT,
    odometer VARCHAR(6) ENCODE ZSTD,
    transaction_date VARCHAR(8) ENCODE ZSTD,
    transyyyymm VARCHAR(6) ENCODE BYTEDICT,
    drive_type VARCHAR(3) ENCODE ZSTD,
    fuel_type VARCHAR(1) ENCODE ZSTD,
    luxnon VARCHAR(1) ENCODE ZSTD,
    bodytype VARCHAR(15) ENCODE ZSTD,
    domimp VARCHAR(1) ENCODE ZSTD,
    vehtype VARCHAR(8) ENCODE ZSTD,
    transyear VARCHAR(4) ENCODE BYTEDICT,
    eor VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_zip4_primary_number VARCHAR(10) ENCODE ZSTD ,
    ah1_mb_zip4_pre_direction VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_primary_name VARCHAR(28) ENCODE ZSTD ,
    ah1_mb_zip4_street_suffix VARCHAR(4) ENCODE ZSTD ,
    ah1_mb_zip4_post_direction VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_unit_type VARCHAR(4) ENCODE ZSTD ,
    ah1_mb_zip4_unit_number VARCHAR(8)ENCODE ZSTD ,
    ah1_mb_zip4_city_name VARCHAR(13) ENCODE ZSTD ,
    ah1_mb_zip4_state_abbreviation VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_zip_code VARCHAR(5) ENCODE ZSTD ,
    ah1_mb_zip4_zip4_code VARCHAR(4) ENCODE ZSTD ,
    ah1_mb_zip4_advanced_bar_code_and_check_digit VARCHAR(3) ENCODE ZSTD ,
    ah1_mb_zip4_carrier_code VARCHAR(4) ENCODE ZSTD ,
    ah1_mb_zip4_zip4_match_level VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_primary_number_is_a_box VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_zip_code_status VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_city_name_has_changed VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_line_of_travel_information VARCHAR(5) ENCODE ZSTD ,
    ah1_mb_zip4_lot_sortation_number VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_state_code VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_county_code VARCHAR(3) ENCODE ZSTD ,
    ah1_mb_zip4_lacs_indicator VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_urbanization_code_for_puerto_rico VARCHAR(28) ENCODE ZSTD ,
    ah1_mb_zip4_unit_return_code_from_finalist VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_FILLER VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_vendor_source VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_city_type_indicator	VARCHAR(1)ENCODE ZSTD ,
    ah1_mb_zip4_address_type_indicator VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_aa VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_a1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_a2 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_a3 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes___expansion1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_d VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_e VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_f VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_zip4_footnotes___expansion2 VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_h VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_zip4_footnotes___expansion3 VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_j VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_k VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_k1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_k2 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_l VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_m1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_m2 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_n1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_n2 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_p1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_p2 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_q1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_q2 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_m3 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_footnote_m4 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes___expansion4 VARCHAR(6) ENCODE ZSTD ,
    ah1_mb_zip4_footnotes_ews VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_aa VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_a1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_bb VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_cc VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_n1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_m1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_m3 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_p1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_rr VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_r1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_confirmation_indicator VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_p3 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_lacs_indicator VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_f1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_g1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dpv_footnote_u1 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_match_level VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_pseudo_sequence VARCHAR(5) ENCODE ZSTD ,
    ah1_mb_dpv___expansion2 VARCHAR(4) ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_educational_indicator VARCHAR(1)	ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_vacant VARCHAR(1) ENCODE ZSTD,
    ah1_mb_dpv_dsf2_seasonal VARCHAR(1) ENCODE ZSTD,
    ah1_mb_dpv_dsf2_residential_business_general_delivery VARCHAR(1) ENCODE ZSTD,
    ah1_mb_dpv_dsf2_throwback VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_delivery_type VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_delivery_drop VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_delivery_drop_count	VARCHAR(3) ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_lacs_indicator VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv_dsf2_no_stat	VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_dpv___expansion3	VARCHAR(48) ENCODE ZSTD ,
    ah1_mb_mailing_address_address_source_code VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_mailing_address_address_status_delivery_code VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_mailing_address_pander_code VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_mailing_address_local_address_line_1 VARCHAR(40) ENCODE ZSTD,
    ah1_mb_mailing_address_unit_information_line VARCHAR(13) ENCODE ZSTD,
    ah1_mb_mailing_address_secondary_address_line VARCHAR(40) ENCODE ZSTD,
    ah1_mb_mailing_address_long_city_name VARCHAR(28) ENCODE ZSTD,
    ah1_mb_mailing_address_short_city_name VARCHAR(13) ENCODE ZSTD,
    ah1_mb_mailing_address_state VARCHAR(2) ENCODE ZSTD,
    ah1_mb_mailing_address_zip_code VARCHAR(5) ENCODE ZSTD,
    ah1_mb_mailing_address_zip_four VARCHAR(4) ENCODE ZSTD,
    ah1_mb_mailing_address___expansion1 VARCHAR(14) ENCODE ZSTD ,
    ah1_mb_mailing_address_mailability_score VARCHAR(2) ENCODE ZSTD,
    ah1_mb_mailing_address___expansion2 VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_mailing_address_military_zip_code VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_mailing_address_opac_match_indicator VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_mailing_address_ndi_affirmed_apt_indicator VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_mailing_address_secondary_address_indicator VARCHAR(1) ENCODE ZSTD ,
    ah1_mb_mailing_address_state_code VARCHAR(2) ENCODE ZSTD ,
    ah1_mb_mailing_address_county_code VARCHAR(3) ENCODE ZSTD,
    ah1_mb_mailing_address_long_city_indicator VARCHAR(1) ENCODE ZSTD,
    ah1_mb_mailing_address_carrier_route_code VARCHAR(4) ENCODE ZSTD,
    ah1_mb_mailing_address_line_of_travel_information VARCHAR(5) ENCODE ZSTD,
    ah1_mb_mailing_address_lot_sortation_number VARCHAR(2) ENCODE ZSTD,
    ah1_mb_mailing_address_prestige_city_name VARCHAR(1) ENCODE ZSTD,
    ah1_mb_mailing_address_zip_addon_delivery_point VARCHAR(12) ENCODE ZSTD,
    ah1_mb_state_zip_matchcode_match_code VARCHAR(18) ENCODE ZSTD,
    supp1_mps_pander VARCHAR(1) ENCODE ZSTD,
    supp1_dts_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_off_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_bus_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_fds_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_reserved VARCHAR(1) ENCODE ZSTD ,
    supp1_dec_pander VARCHAR(1) ENCODE ZSTD,
    supp1_rel_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_ext_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_col_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_mil_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_trl_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_ret_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_nur_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_cli_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_dba_pander VARCHAR(1) ENCODE ZSTD ,
    supp1_aca_pander VARCHAR(1) ENCODE ZSTD,
    supp1_attorney_general_file	VARCHAR(1) ENCODE ZSTD ,
    supp1_tps_telephone	VARCHAR(1) ENCODE ZSTD ,
    supp1_infousa_business_telephone VARCHAR(1) ENCODE ZSTD ,
    supp1_reserved2	VARCHAR(3) ENCODE ZSTD ,
    supp1_email_suppression	VARCHAR(1) ENCODE ZSTD ,
    ce_household_ID VARCHAR(12) ENCODE ZSTD,
    ce_selected_Individual_ID VARCHAR(12) ENCODE ZSTD,
    ge_longitude VARCHAR(11) ENCODE ZSTD,
    ge_latitude VARCHAR(11) ENCODE ZSTD,
    ge_cbsa_code VARCHAR(5) ENCODE ZSTD,
    ge_cbsa_type VARCHAR(5) ENCODE ZSTD,
    ge_cbsa_name VARCHAR(50) ENCODE ZSTD,
    dc_deceasedflag VARCHAR(1) ENCODE ZSTD,
    dc_reasoncode VARCHAR(1) ENCODE ZSTD,
    dc_score VARCHAR(3) ENCODE ZSTD,
    individual_mc VARCHAR(17) ENCODE ZSTD,
    matchcode VARCHAR(21) ENCODE ZSTD
);

COPY auto_ncoa_out_monthly_infutor
(
    vin,
    shortvin,
    fname,
    mi,
    lname,
    addr,
    city,
    st,
    zip,
    zip4,
    dp,
    scf,
    gender,
    make,
    model,
    year,
    odometer,
    transaction_date,
    transyyyymm,
    drive_type,
    fuel_type,
    luxnon,
    bodytype,
    domimp,
    vehtype,
    transyear,
    eor,
    ah1_mb_zip4_primary_number,
    ah1_mb_zip4_pre_direction,
    ah1_mb_zip4_primary_name,
    ah1_mb_zip4_street_suffix,
    ah1_mb_zip4_post_direction,
    ah1_mb_zip4_unit_type,
    ah1_mb_zip4_unit_number,
    ah1_mb_zip4_city_name,
    ah1_mb_zip4_state_abbreviation,
    ah1_mb_zip4_zip_code,
    ah1_mb_zip4_zip4_code,
    ah1_mb_zip4_advanced_bar_code_and_check_digit,
    ah1_mb_zip4_carrier_code,
    ah1_mb_zip4_zip4_match_level,
    ah1_mb_zip4_primary_number_is_a_box,
    ah1_mb_zip4_zip_code_status,
    ah1_mb_zip4_city_name_has_changed,
    ah1_mb_zip4_line_of_travel_information,
    ah1_mb_zip4_lot_sortation_number,
    ah1_mb_zip4_state_code,
    ah1_mb_zip4_county_code,
    ah1_mb_zip4_lacs_indicator,
    ah1_mb_zip4_urbanization_code_for_puerto_rico,
    ah1_mb_zip4_unit_return_code_from_finalist,
    ah1_mb_zip4_FILLER,
    ah1_mb_zip4_vendor_source,
    ah1_mb_zip4_city_type_indicator,
    ah1_mb_zip4_address_type_indicator,
    ah1_mb_zip4_footnotes_footnote_aa,
    ah1_mb_zip4_footnotes_footnote_a1,
    ah1_mb_zip4_footnotes_footnote_a2,
    ah1_mb_zip4_footnotes_footnote_a3,
    ah1_mb_zip4_footnotes___expansion1,
    ah1_mb_zip4_footnotes_footnote_d,
    ah1_mb_zip4_footnotes_footnote_e,
    ah1_mb_zip4_footnotes_footnote_f,
    ah1_mb_zip4_footnotes___expansion2,
    ah1_mb_zip4_footnotes_footnote_h,
    ah1_mb_zip4_footnotes___expansion3,
    ah1_mb_zip4_footnotes_footnote_j,
    ah1_mb_zip4_footnotes_footnote_k,
    ah1_mb_zip4_footnotes_footnote_k1,
    ah1_mb_zip4_footnotes_footnote_k2,
    ah1_mb_zip4_footnotes_footnote_l,
    ah1_mb_zip4_footnotes_footnote_m1,
    ah1_mb_zip4_footnotes_footnote_m2,
    ah1_mb_zip4_footnotes_footnote_n1,
    ah1_mb_zip4_footnotes_footnote_n2,
    ah1_mb_zip4_footnotes_footnote_p1,
    ah1_mb_zip4_footnotes_footnote_p2,
    ah1_mb_zip4_footnotes_footnote_q1,
    ah1_mb_zip4_footnotes_footnote_q2,
    ah1_mb_zip4_footnotes_footnote_m3,
    ah1_mb_zip4_footnotes_footnote_m4,
    ah1_mb_zip4_footnotes___expansion4,
    ah1_mb_zip4_footnotes_ews,
    ah1_mb_dpv_dpv_footnote_aa,
    ah1_mb_dpv_dpv_footnote_a1,
    ah1_mb_dpv_dpv_footnote_bb,
    ah1_mb_dpv_dpv_footnote_cc,
    ah1_mb_dpv_dpv_footnote_n1,
    ah1_mb_dpv_dpv_footnote_m1,
    ah1_mb_dpv_dpv_footnote_m3,
    ah1_mb_dpv_dpv_footnote_p1,
    ah1_mb_dpv_dpv_footnote_rr,
    ah1_mb_dpv_dpv_footnote_r1,
    ah1_mb_dpv_dpv_confirmation_indicator,
    ah1_mb_dpv_dpv_footnote_p3,
    ah1_mb_dpv_dpv_lacs_indicator,
    ah1_mb_dpv_dpv_footnote_f1,
    ah1_mb_dpv_dpv_footnote_g1,
    ah1_mb_dpv_dpv_footnote_u1,
    ah1_mb_dpv_dsf2_match_level,
    ah1_mb_dpv_dsf2_pseudo_sequence,
    ah1_mb_dpv___expansion2,
    ah1_mb_dpv_dsf2_educational_indicator,
    ah1_mb_dpv_dsf2_vacant,
    ah1_mb_dpv_dsf2_seasonal,
    ah1_mb_dpv_dsf2_residential_business_general_delivery,
    ah1_mb_dpv_dsf2_throwback,
    ah1_mb_dpv_dsf2_delivery_type,
    ah1_mb_dpv_dsf2_delivery_drop,
    ah1_mb_dpv_dsf2_delivery_drop_count,
    ah1_mb_dpv_dsf2_lacs_indicator,
    ah1_mb_dpv_dsf2_no_stat,
    ah1_mb_dpv___expansion3,
    ah1_mb_mailing_address_address_source_code,
    ah1_mb_mailing_address_address_status_delivery_code,
    ah1_mb_mailing_address_pander_code,
    ah1_mb_mailing_address_local_address_line_1,
    ah1_mb_mailing_address_unit_information_line,
    ah1_mb_mailing_address_secondary_address_line,
    ah1_mb_mailing_address_long_city_name,
    ah1_mb_mailing_address_short_city_name,
    ah1_mb_mailing_address_state,
    ah1_mb_mailing_address_zip_code,
    ah1_mb_mailing_address_zip_four,
    ah1_mb_mailing_address___expansion1,
    ah1_mb_mailing_address_mailability_score,
    ah1_mb_mailing_address___expansion2,
    ah1_mb_mailing_address_military_zip_code,
    ah1_mb_mailing_address_opac_match_indicator,
    ah1_mb_mailing_address_ndi_affirmed_apt_indicator,
    ah1_mb_mailing_address_secondary_address_indicator,
    ah1_mb_mailing_address_state_code,
    ah1_mb_mailing_address_county_code,
    ah1_mb_mailing_address_long_city_indicator,
    ah1_mb_mailing_address_carrier_route_code,
    ah1_mb_mailing_address_line_of_travel_information,
    ah1_mb_mailing_address_lot_sortation_number,
    ah1_mb_mailing_address_prestige_city_name,
    ah1_mb_mailing_address_zip_addon_delivery_point,
    ah1_mb_state_zip_matchcode_match_code,
    supp1_mps_pander,
    supp1_dts_pander,
    supp1_off_pander,
    supp1_bus_pander,
    supp1_fds_pander,
    supp1_reserved,
    supp1_dec_pander,
    supp1_rel_pander,
    supp1_ext_pander,
    supp1_col_pander,
    supp1_mil_pander,
    supp1_trl_pander,
    supp1_ret_pander,
    supp1_nur_pander,
    supp1_cli_pander,
    supp1_dba_pander,
    supp1_aca_pander,
    supp1_attorney_general_file,
    supp1_tps_telephone,
    supp1_infousa_business_telephone,
    supp1_reserved2,
    supp1_email_suppression,
    ce_household_ID,
    ce_selected_Individual_ID,
    ge_longitude,
    ge_latitude,
    ge_cbsa_code,
    ge_cbsa_type,
    ge_cbsa_name,
    dc_deceasedflag,
    dc_reasoncode,
    dc_score,
    individual_mc,
    matchcode
    )
FROM 's3://{s3-aopoutput}/a09'
IAM_ROLE '{iam}'
ACCEPTINVCHARS
IGNOREBLANKLINES
GZIP
FIXEDWIDTH
'vin:17, 
shortvin:10, 
fname:30, 
mi:1, 
lname:30, 
addr:50, 
city:30, 
st:2, 
zip:5, 
zip4:4, 
dp:2, 
scf:3, 
gender:1, 
make:30, 
model:30, 
year:4, 
odometer:6, 
transaction_date:8, 
transyyyymm:6, 
drive_type:3, 
fuel_type:1, 
luxnon:1, 
bodytype:15, 
domimp:1, 
vehtype:8, 
transyear:4, 
eor:1,  
ah1_mb_zip4_primary_number:10,  
ah1_mb_zip4_pre_direction:2,  
ah1_mb_zip4_primary_name:28,  
ah1_mb_zip4_street_suffix:4,  
ah1_mb_zip4_post_direction:2,  
ah1_mb_zip4_unit_type:4,  
ah1_mb_zip4_unit_number:8,	
ah1_mb_zip4_city_name:13,  
ah1_mb_zip4_state_abbreviation:2,  
ah1_mb_zip4_zip_code:5,  
ah1_mb_zip4_zip4_code:4,  
ah1_mb_zip4_advanced_bar_code_and_check_digit:3,  
ah1_mb_zip4_carrier_code:4,  
ah1_mb_zip4_zip4_match_level:1,  
ah1_mb_zip4_primary_number_is_a_box:1,  
ah1_mb_zip4_zip_code_status:1,  
ah1_mb_zip4_city_name_has_changed:1,  
ah1_mb_zip4_line_of_travel_information:5,  
ah1_mb_zip4_lot_sortation_number:2,  
ah1_mb_zip4_state_code:2,  
ah1_mb_zip4_county_code:3,  
ah1_mb_zip4_lacs_indicator:1,  
ah1_mb_zip4_urbanization_code_for_puerto_rico:28,  
ah1_mb_zip4_unit_return_code_from_finalist:2,  
ah1_mb_zip4_FILLER:1,  
ah1_mb_zip4_vendor_source:1,  
ah1_mb_zip4_city_type_indicator:1,	
ah1_mb_zip4_address_type_indicator:1,  
ah1_mb_zip4_footnotes_footnote_aa:2,  
ah1_mb_zip4_footnotes_footnote_a1:2,  
ah1_mb_zip4_footnotes_footnote_a2:2,  
ah1_mb_zip4_footnotes_footnote_a3:2,  
ah1_mb_zip4_footnotes___expansion1:2,  
ah1_mb_zip4_footnotes_footnote_d:1,  
ah1_mb_zip4_footnotes_footnote_e:1,  
ah1_mb_zip4_footnotes_footnote_f:1,  
ah1_mb_zip4_footnotes___expansion2:1,  
ah1_mb_zip4_footnotes_footnote_h:1,  
ah1_mb_zip4_footnotes___expansion3:1,  
ah1_mb_zip4_footnotes_footnote_j:1,  
ah1_mb_zip4_footnotes_footnote_k:1,  
ah1_mb_zip4_footnotes_footnote_k1:2,  
ah1_mb_zip4_footnotes_footnote_k2:2,  
ah1_mb_zip4_footnotes_footnote_l:1,  
ah1_mb_zip4_footnotes_footnote_m1:2,  
ah1_mb_zip4_footnotes_footnote_m2:2,  
ah1_mb_zip4_footnotes_footnote_n1:2,  
ah1_mb_zip4_footnotes_footnote_n2:2,  
ah1_mb_zip4_footnotes_footnote_p1:2,  
ah1_mb_zip4_footnotes_footnote_p2:2,  
ah1_mb_zip4_footnotes_footnote_q1:2,  
ah1_mb_zip4_footnotes_footnote_q2:2,  
ah1_mb_zip4_footnotes_footnote_m3:2,  
ah1_mb_zip4_footnotes_footnote_m4:2,  
ah1_mb_zip4_footnotes___expansion4:6,  
ah1_mb_zip4_footnotes_ews:1,  
ah1_mb_dpv_dpv_footnote_aa:2,  
ah1_mb_dpv_dpv_footnote_a1:2,  
ah1_mb_dpv_dpv_footnote_bb:2,  
ah1_mb_dpv_dpv_footnote_cc:2,  
ah1_mb_dpv_dpv_footnote_n1:2,  
ah1_mb_dpv_dpv_footnote_m1:2,  
ah1_mb_dpv_dpv_footnote_m3:2,  
ah1_mb_dpv_dpv_footnote_p1:2,  
ah1_mb_dpv_dpv_footnote_rr:2,  
ah1_mb_dpv_dpv_footnote_r1:2,  
ah1_mb_dpv_dpv_confirmation_indicator:1,  
ah1_mb_dpv_dpv_footnote_p3:2,  
ah1_mb_dpv_dpv_lacs_indicator:1,  
ah1_mb_dpv_dpv_footnote_f1:2,  
ah1_mb_dpv_dpv_footnote_g1:2,  
ah1_mb_dpv_dpv_footnote_u1:2,  
ah1_mb_dpv_dsf2_match_level:1,  
ah1_mb_dpv_dsf2_pseudo_sequence:5,  
ah1_mb_dpv___expansion2:4,  
ah1_mb_dpv_dsf2_educational_indicator:1,  
ah1_mb_dpv_dsf2_vacant:1, 
ah1_mb_dpv_dsf2_seasonal:1, 
ah1_mb_dpv_dsf2_residential_business_general_delivery:1, 
ah1_mb_dpv_dsf2_throwback:1,	 
ah1_mb_dpv_dsf2_delivery_type:1,	 
ah1_mb_dpv_dsf2_delivery_drop:1,	 
ah1_mb_dpv_dsf2_delivery_drop_count:3,	 
ah1_mb_dpv_dsf2_lacs_indicator:1,	 
ah1_mb_dpv_dsf2_no_stat:1,	 
ah1_mb_dpv___expansion3:48,	 
ah1_mb_mailing_address_address_source_code:1,	 
ah1_mb_mailing_address_address_status_delivery_code:1,	 
ah1_mb_mailing_address_pander_code:1,	 
ah1_mb_mailing_address_local_address_line_1:40, 
ah1_mb_mailing_address_unit_information_line:13, 
ah1_mb_mailing_address_secondary_address_line:40, 
ah1_mb_mailing_address_long_city_name:28, 
ah1_mb_mailing_address_short_city_name:13, 
ah1_mb_mailing_address_state:2, 
ah1_mb_mailing_address_zip_code:5, 
ah1_mb_mailing_address_zip_four:4, 
ah1_mb_mailing_address___expansion1:14,  
ah1_mb_mailing_address_mailability_score:2, 
ah1_mb_mailing_address___expansion2:2,	 
ah1_mb_mailing_address_military_zip_code:1,	 
ah1_mb_mailing_address_opac_match_indicator:1,	 
ah1_mb_mailing_address_ndi_affirmed_apt_indicator:1,	 
ah1_mb_mailing_address_secondary_address_indicator:1,	 
ah1_mb_mailing_address_state_code:2,	 
ah1_mb_mailing_address_county_code:3, 
ah1_mb_mailing_address_long_city_indicator:1, 
ah1_mb_mailing_address_carrier_route_code:4, 
ah1_mb_mailing_address_line_of_travel_information:5, 
ah1_mb_mailing_address_lot_sortation_number:2, 
ah1_mb_mailing_address_prestige_city_name:1, 
ah1_mb_mailing_address_zip_addon_delivery_point:12, 
ah1_mb_state_zip_matchcode_match_code:18, 
supp1_mps_pander:1, 
supp1_dts_pander:1,	 
supp1_off_pander:1,	 
supp1_bus_pander:1,	 
supp1_fds_pander:1,	 
supp1_reserved:1,	 
supp1_dec_pander:1, 
supp1_rel_pander:1,	 
supp1_ext_pander:1,	 
supp1_col_pander:1,	 
supp1_mil_pander:1,	 
supp1_trl_pander:1,	 
supp1_ret_pander:1,	 
supp1_nur_pander:1,	 
supp1_cli_pander:1,	 
supp1_dba_pander:1,	 
supp1_aca_pander:1, 
supp1_attorney_general_file:1,	 
supp1_tps_telephone:1,	 
supp1_infousa_business_telephone:1,	 
supp1_reserved2:3,
supp1_email_suppression:1,	 
ce_household_ID:12, 
ce_selected_Individual_ID:12, 
ge_longitude:11, 
ge_latitude:11, 
ge_cbsa_code:5, 
ge_cbsa_type:5, 
ge_cbsa_name:50, 
dc_deceasedflag:1, 
dc_reasoncode:1, 
dc_score:3, 
individual_mc:17,
matchcode:21';

DROP TABLE IF EXISTS auto_reformat_infutor;

create table auto_reformat_infutor as
SELECT
    vin,
    shortvin,
    fname,
    CASE WHEN mi in ('q','w','e','r','t','y','u','i','o','p','a','s','d','f','g','h','j',
                      'k','l','z','x','c','v','b','n','m') THEN mi ELSE ' ' END as mi,
    lname,
    addr,
    city,
    st,
    zip,
    zip4,
    dp,
    scf,
    CASE WHEN gender not in ('F','M') THEN 'U' ELSE gender END as gender,
    CASE WHEN UPPER(make)='MERCEDES-BENZ' THEN 'MERCEDES_BENZ'
        WHEN UPPER(make)='ROLLS-ROYCE' THEN 'ROLLS_ROYCE'
        WHEN UPPER(make)='AMERICAN_MOTORS_(AMC)' OR UPPER(make)='AMERICAN MOTORS (AMC)' THEN 'AMC'
        ELSE make END as make,
    model,
    year,
    odometer,
    transaction_date,
    transyyyymm,
    SUBSTRING(drive_type,1,3) as drive_type,
    fuel_type,
    luxnon,
    SUBSTRING(bodytype,1,15) as bodytype,
    domimp,
    vehtype,
    transyear,
    ah1_mb_state_zip_matchcode_match_code as ah1_match_code,
    udf_sim_enhanced_matchcode2(REPLACE(NVL(fname, ''), '|', ''),REPLACE(NVL(lname, ''), '|', ''), REPLACE(NVL(ah1_mb_mailing_address_local_address_line_1, ''), '|', ''),REPLACE(ah1_mb_mailing_address_zip_code,'|',''),' ') as matchcode,
    ce_household_id as company_id,
    ce_selected_Individual_id as individual_id,
    ah1_mb_mailing_address_local_address_line_1 as ah1_local_address,
    ah1_mb_mailing_address_secondary_address_line as ah1_secondary_address,
    ah1_mb_mailing_address_long_city_name as ah1_long_city_name,
    ah1_mb_mailing_address_state as ah1_state_abbreviation,
    ah1_mb_mailing_address_zip_code as ah1_zip_code,
    ah1_mb_mailing_address_zip_four as ah1_zip4_code,
    ah1_mb_mailing_address_mailability_score as ah1_mailability_score,
    ah1_mb_mailing_address_carrier_route_code as ah1_carrier_route,
    ah1_mb_mailing_address_line_of_travel_information as ah1_lot_number,
    ah1_mb_mailing_address_lot_sortation_number as ah1_lot_sortation_number,
    SUBSTRING(ah1_mb_mailing_address_zip_addon_delivery_point,10,3) as dpb,
    ah1_mb_mailing_address_county_code as ah1_county_code,
    ah1_mb_dpv_dsf2_residential_business_general_delivery as ah1_res_bus_indc,
    ge_longitude,
    ge_latitude,
    ge_cbsa_code,
    ge_cbsa_type,
    ge_cbsa_name,
    individual_mc,
    GETMATCHCODE('',
                  REPLACE(NVL(lname, ''), '|', ''),
                  REPLACE(NVL(ah1_mb_mailing_address_local_address_line_1, ''), '|', ''),
                  REPLACE(ah1_mb_mailing_address_zip_code,'|',''),
                  REPLACE(NVL(lname, ''), '|', ''),
                  'C') AS Company_mc,---#testing GETMATCHCODE(A.firstname,a.lastname,a.addressline1,zip,a.lastname,'C')
    GETMATCHCODE( '',
                  '',
                  REPLACE(NVL(A.ah1_mb_mailing_address_local_address_line_1, ''), '|', ''),
                  REPLACE(NVL(A.ah1_mb_mailing_address_zip_code, ''), '|', ''),
                  '',
                  'I') AS address_mc
FROM auto_ncoa_out_monthly_infutor A
WHERE supp1_dec_pander!='Y' AND dc_deceasedflag!='Y'  ;

DROP TABLE IF EXISTS auto_MMDB_infutor;
CREATE TABLE auto_MMDB_infutor AS
SELECT DISTINCT
    company_id,
    Individual_ID,
    LTRIM(RTRIM(vin)) AS vin,
    LTRIM(RTRIM(shortvin)) AS shortvin,
    LTRIM(RTRIM(make)) AS make,
    LTRIM(RTRIM(model)) AS model,
    LTRIM(RTRIM(year)) AS year,
    LTRIM(RTRIM(odometer)) AS odometer,
    LTRIM(RTRIM(transaction_date)) AS transaction_date,
    LTRIM(RTRIM(transyyyymm)) AS transyyyymm,
    SUBSTRING(drive_type,1,3) AS drive_type,
    RTRIM(LTRIM(fuel_type)) AS fuel_type,
    RTRIM(LTRIM(luxnon)) AS luxnon,
    RTRIM(LTRIM(SUBSTRING(bodytype,1,15))) AS bodytype,
    LTRIM(RTRIM(domimp)) AS domimp,
    LTRIM(RTRIM(vehtype)) AS vehtype,
    LTRIM(RTRIM(transyear)) AS transyear,
    SPACE(20) AS vehrecno,
    'X' AS eor
FROM auto_reformat_infutor
WHERE trim(company_id) <>'';

-- need s3 location
UNLOAD('SELECT * FROM auto_MMDB_infutor')
TO 's3://axle-gold-sources/auto/Auto_mmdb_infutor_{mm}{dd}{yyyy}.txt'
IAM_ROLE '{iam}'
GZIP
CLEANPATH
PARALLEL OFF
FIXEDWIDTH
'company_id : 12,
    individual_id : 12
    vin : 17 , 
    shortvin : 10 ,
    make : 30, 
    model : 30, 
    year : 4,
    odometer :6 , 
    transaction_date : 8 , 
    transyyyymm : 6,
    drive_type :3 ,
    fuel_type : 1, 
    luxnon : 1,
    bodytype : 15,
    domimp : 1,
    vehtype:8,
    transyear : 4 , 
    vehrecno :20 ,
    eor:1';