DROP TABLE IF EXISTS business_SEGMENTCODE;
CREATE TABLE business_SEGMENTCODE
DISTKEY (ID)
SORTKEY(ID)
AS 
SELECT   
  tblMain.id AS id, 
	MIN(SEGMENTCODE_1.SEGMENTCODE_1) AS SEGMENTCODE_1,
	MIN(SEGMENTCODE_2.SEGMENTCODE_2) AS SEGMENTCODE_2,
	MIN(SEGMENTCODE_3.SEGMENTCODE_3) AS SEGMENTCODE_3,
	MIN(SEGMENTCODE_4.SEGMENTCODE_4) AS SEGMENTCODE_4,
	MIN(SEGMENTCODE_5.SEGMENTCODE_5) AS SEGMENTCODE_5,
	MIN(SEGMENTCODE_6.SEGMENTCODE_6) AS SEGMENTCODE_6,
	MIN(SEGMENTCODE_7.SEGMENTCODE_7) AS SEGMENTCODE_7,
	MIN(SEGMENTCODE_8.SEGMENTCODE_8) AS SEGMENTCODE_8,
	MIN(SEGMENTCODE_9.SEGMENTCODE_9) AS SEGMENTCODE_9,
	MIN(SEGMENTCODE_A.SEGMENTCODE_A) AS SEGMENTCODE_A,
	MIN(SEGMENTCODE_F.SEGMENTCODE_F) AS SEGMENTCODE_F,
	MIN(SEGMENTCODE_H.SEGMENTCODE_H) AS SEGMENTCODE_H,
	MIN(SEGMENTCODE_I.SEGMENTCODE_I) AS SEGMENTCODE_I
FROM tblBusinessIndividual tblMain
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_1 FROM SegmentCodes_992
  WHERE cvalue = '1' GROUP BY AbiNumber
) SEGMENTCODE_1
ON SEGMENTCODE_1.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_2 FROM SegmentCodes_992
  WHERE cvalue = '2' GROUP BY AbiNumber
) SEGMENTCODE_2
ON SEGMENTCODE_2.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_3 FROM SegmentCodes_992
  WHERE cvalue = '3' GROUP BY AbiNumber
) SEGMENTCODE_3
ON SEGMENTCODE_3.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_4 FROM SegmentCodes_992
  WHERE cvalue = '4' GROUP BY AbiNumber
) SEGMENTCODE_4
ON SEGMENTCODE_4.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_5 FROM SegmentCodes_992
  WHERE cvalue = '5' GROUP BY AbiNumber
) SEGMENTCODE_5
ON SEGMENTCODE_5.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_6 FROM SegmentCodes_992
  WHERE cvalue = '6' GROUP BY AbiNumber
) SEGMENTCODE_6
ON SEGMENTCODE_6.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_7 FROM SegmentCodes_992
  WHERE cvalue = '7' GROUP BY AbiNumber
) SEGMENTCODE_7
ON SEGMENTCODE_7.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_8 FROM SegmentCodes_992
  WHERE cvalue = '8' GROUP BY AbiNumber
) SEGMENTCODE_8
ON SEGMENTCODE_8.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_9 FROM SegmentCodes_992
  WHERE cvalue = '9' GROUP BY AbiNumber
) SEGMENTCODE_9
ON SEGMENTCODE_9.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_A FROM SegmentCodes_992
  WHERE cvalue = 'A' GROUP BY AbiNumber
) SEGMENTCODE_A
ON SEGMENTCODE_A.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_F FROM SegmentCodes_992
  WHERE cvalue = 'F' GROUP BY AbiNumber
) SEGMENTCODE_F
ON SEGMENTCODE_F.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_H FROM SegmentCodes_992
  WHERE cvalue = 'H' GROUP BY AbiNumber
) SEGMENTCODE_H
ON SEGMENTCODE_H.ABINumber = tblMain.AbiNumber
LEFT JOIN 
(
  SELECT AbiNumber AS AbiNumber,  MIN(cvalue) SEGMENTCODE_I FROM SegmentCodes_992
  WHERE cvalue = 'I' GROUP BY AbiNumber
) SEGMENTCODE_I
ON SEGMENTCODE_I.ABINumber = tblMain.AbiNumber
GROUP BY tblMain.id;