drop table if exists mgen_new_load CASCADE;

create table mgen_new_load
(
lrfsid int ENCODE AZ64,
oldid varchar(12) ENCODE ZSTD,
cid varchar(18) ENCODE ZSTD,
firstname varchar(15) ENCODE ZSTD,
lastname varchar(20) ENCODE ZSTD,
fin_gen varchar(1) ENCODE ZSTD,
fin_age_old varchar(3) ENCODE ZSTD ,
fin_indid varchar(12) ENCODE ZSTD,
fin_hhld varchar(12) ENCODE ZSTD,
file_source varchar(1) ENCODE ZSTD,
addressline1 varchar(30) ENCODE ZSTD,
addressline2 varchar(30) ENCODE ZSTD,
city varchar(28) ENCODE ZSTD,
st varchar(2) ENCODE BYTEDICT,
zip varchar(5)  ENCODE ZSTD,
zip4 varchar(4) ENCODE ZSTD,
dma varchar(1) ENCODE ZSTD,
deceased_flag varchar(1) ENCODE ZSTD,
aca varchar(1) ENCODE ZSTD,
fin_dob varchar(8) ENCODE ZSTD,
fin_ethcode varchar(2) ENCODE ZSTD,
fin_ethgroup varchar(1) ENCODE ZSTD,
fin_language varchar(2) ENCODE ZSTD,
fin_relcode varchar(1) ENCODE ZSTD,
fin_active_trade_line varchar(1) ENCODE ZSTD,
fin_marr_date varchar(7) ENCODE ZSTD,
fin_spflag varchar(1) ENCODE ZSTD,
lems varchar(18) ENCODE ZSTD,
fin_married varchar(1) ENCODE ZSTD,
fin_politic varchar(1) ENCODE ZSTD,
fl_lname varchar(1) ENCODE ZSTD,
ld_zip varchar(1) ENCODE ZSTD,
dqi_match_flag varchar(1) ENCODE ZSTD,
scf varchar(3) ENCODE ZSTD,
age_code varchar(1) ENCODE ZSTD,
comp varchar(5)  ENCODE ZSTD,
matchcode varchar(25) ENCODE ZSTD,
dma_code varchar(3) ENCODE BYTEDICT,
zipfull varchar(9) ENCODE ZSTD,
edb_match_flag varchar(1) ENCODE ZSTD,
md5_email_lower varchar(32) ENCODE ZSTD,
combined_age varchar(1) ENCODE ZSTD,
new_mover_flag varchar(1) ENCODE ZSTD,
new_mover_date varchar(5) ENCODE ZSTD,
smb_flag varchar(1) ENCODE ZSTD,
sic_2 varchar(2) ENCODE ZSTD,
sha1_email varchar(40) ENCODE ZSTD,
infopersona_cluster varchar(2) ENCODE BYTEDICT,
infopersona_supercluster varchar(1) ENCODE ZSTD,
cd_rating_2014 varchar(1) ENCODE ZSTD,
crrt varchar(4) ENCODE BYTEDICT,
lot varchar(5) ENCODE ZSTD,
lotsort varchar(2) ENCODE BYTEDICT,
dpv varchar(3) ENCODE ZSTD,
state_code varchar(2) ENCODE BYTEDICT,
county_code varchar(3) ENCODE BYTEDICT,
ce_income_producing_assets varchar(1) ENCODE ZSTD,
ce_discretionary_income_score varchar(2) ENCODE BYTEDICT,
ce_pensioner_present_flag varchar(1) ENCODE ZSTD,
winmargin varchar(1) ENCODE ZSTD,
educational_model varchar(1) ENCODE ZSTD,
consumer_digital_match varchar(1) ENCODE ZSTD,
buy_segment varchar(1) ENCODE ZSTD,
buy_score varchar(3) ENCODE ZSTD,
execureach_match_flag varchar(1) ENCODE ZSTD,
oneperhhd_mc varchar(18) ENCODE ZSTD,
exec_bus_igid varchar(9) ENCODE ZSTD,
exec_bus_titlecode varchar(1) ENCODE ZSTD,
exec_bus_titlecodedescription varchar(30) ENCODE ZSTD,
exec_bus_employeesizecode varchar(1) ENCODE ZSTD,
exec_bus_locationoutputvolumecode varchar(1) ENCODE ZSTD,
exec_bus_primarysiccode_6digit varchar(6) ENCODE ZSTD,
exec_cons_locationtype varchar(1) ENCODE ZSTD,
exec_bus_fulfillment_flag varchar(1) ENCODE ZSTD,
exec_bus_cbsa varchar(5) ENCODE ZSTD,
exec_bus_cbsalevel varchar(1) ENCODE ZSTD,
exec_bus_companyholdingstatus varchar(1) ENCODE ZSTD,
exec_bus_cottagecode varchar(1) ENCODE ZSTD,
exec_bus_mailscore varchar(2) ENCODE ZSTD,
exec_execureach_type varchar(1) ENCODE ZSTD,
exec_execureach_quality varchar(2) ENCODE ZSTD,
exec_bus_actual_location_employeesize varchar(5) ENCODE ZSTD,
exec_bus_corporate_employeesizecode varchar(1) ENCODE ZSTD,
exec_bus_actual_location_outputvolume varchar(9) ENCODE ZSTD,
exec_bus_corporateoutputvolumecode varchar(1) ENCODE ZSTD,
exec_bus_square_footage varchar(1) ENCODE ZSTD,
exec_bus_credit_alphascore varchar(2) ENCODE ZSTD,
exec_bus_rolecode varchar(4) ENCODE ZSTD,
exec_bus_digitalflag varchar(1) ENCODE ZSTD,
exec_bus_businessstatuscode varchar(1) ENCODE ZSTD,
exec_bus_departmentcode varchar(2) ENCODE ZSTD,
exec_bus_levelcode varchar(1) ENCODE ZSTD,
exec_bus_royalty_record varchar(1) ENCODE ZSTD,
exec_bus_email_md5_lower varchar(32) ENCODE ZSTD,
exec_bus_email_md5_upper varchar(32) ENCODE ZSTD,
exec_bus_contactliteraltitlecode varchar(8) ENCODE ZSTD,
exec_bus_contactliteraltitlecode_description varchar(256) ENCODE ZSTD,
exec_bus_contactid varchar(12) ENCODE ZSTD,
exec_bus_professionaltitle varchar(3) ENCODE ZSTD,
exec_bus_companyname_available varchar(1) ENCODE ZSTD,
exec_bus_sic2 varchar(2) ENCODE ZSTD,
exec_bus_sic4 varchar(4) ENCODE ZSTD,
exec_bus_igid_available varchar(1) ENCODE ZSTD,
bluekaiid varchar(32) ENCODE ZSTD,
bluekai_flag varchar(1) ENCODE ZSTD,
haystaq_array varchar(605) ENCODE ZSTD,
lot_size varchar(5) ENCODE ZSTD,
email_deployable varchar(1) ENCODE ZSTD,
Filler varchar(1) ENCODE ZSTD,
id int identity ENCODE ZSTD,
state                           varchar(2) ENCODE LZO ,
zipradius                       varchar(1) ENCODE LZO ,
listid                          int DEFAULT 9357 ENCODE AZ64 ,
permissiontype                  varchar(1) DEFAULT 'R' ENCODE ZSTD,
arr_pay                         varchar(42) DEFAULT '' ENCODE ZSTD,
arr_cc                          varchar(42) DEFAULT '' ENCODE ZSTD,
children_age_presence_flag      varchar(30) DEFAULT '' ENCODE ZSTD,
interest_flag                   varchar(150) DEFAULT '' ENCODE ZSTD,
lifestyle_hobby_interest_flags  varchar(270) DEFAULT '' ENCODE ZSTD,
ailments_flags                  varchar(50) DEFAULT '' ENCODE ZSTD,
credit_card_flag                varchar(50) DEFAULT '' ENCODE ZSTD,
donor_flags                     varchar(12) DEFAULT '' ENCODE ZSTD,
market_target_age_flags         varchar(80) DEFAULT '' ENCODE ZSTD,
children_month_of_birth         varchar(36) DEFAULT '' ENCODE ZSTD,
children_age_by_gender          varchar(150) DEFAULT '' ENCODE ZSTD,
experian_donor_array            varchar(120) DEFAULT '' ENCODE ZSTD,
experian_child_array            varchar(90) DEFAULT '' ENCODE ZSTD,
experian_lifestyle_array        varchar(210) DEFAULT '' ENCODE ZSTD,
dlx_segments                    varchar(500) DEFAULT '' ENCODE ZSTD,
arr_twm                         varchar(500) DEFAULT '' ENCODE ZSTD,
oneperadd_mc varchar(18) ENCODE ZSTD,
fin_age INT ENCODE LZO,
statecountycode varchar(5) ENCODE ZSTD,
individual_mc varchar(17) ENCODE ZSTD,
model_greatcallcluster_decile int ENCODE AZ64,
pub2_moslo int ENCODE LZO,
pub2_total_mag int ENCODE LZO,
pub2_total_pub_books int ENCODE LZO,
pub2_mag_moslo int ENCODE LZO,
pub2_mag_totord int ENCODE LZO,
pub2_active_mag int ENCODE LZO,
pub2_total_cat_books int ENCODE LZO,
pub2_mag_autornwl int ENCODE LZO,
pub2_expire_mag int ENCODE LZO,
pub2_mag_paid int ENCODE LZO,
pub2_mag_paid_cash int ENCODE LZO,
publisher2_source_arr varchar ENCODE LZO,
publisher2_cat1_arr varchar ENCODE LZO,
publisher2_cat2_arr varchar ENCODE LZO
)
DISTSTYLE KEY
DISTKEY(cid)
SORTKEY(cid);


copy mgen_new_load
(
	lrfsid,
	oldid,
	cid,
	firstname,
	lastname,
	fin_gen,
	fin_age_old,
	fin_indid,
	fin_hhld,
	file_source,
	addressline1,
	addressline2,
	city,
	st,
	zip,
	zip4,
	dma,
	deceased_flag,
	aca,
	fin_dob,
	fin_ethcode,
	fin_ethgroup,
	fin_language,
	fin_relcode,
	fin_active_trade_line,
	fin_marr_date,
	fin_spflag,
	lems,
	fin_married,
	fin_politic,
	fl_lname,
	ld_zip,
	dqi_match_flag,
	scf,
	age_code,
	comp,
	matchcode,
	dma_code,
	zipfull,
	edb_match_flag,
	md5_email_lower,
	combined_age,
	new_mover_flag,
	new_mover_date,
	smb_flag,
	sic_2,
	sha1_email,
	infopersona_cluster,
	infopersona_supercluster,
	cd_rating_2014,
	crrt,
	lot,
	lotsort,
	dpv,
	state_code,
	county_code,
	ce_income_producing_assets,
	ce_discretionary_income_score,
	ce_pensioner_present_flag,
	winmargin,
	educational_model,
	consumer_digital_match,
	buy_segment,
	buy_score,
	execureach_match_flag,
	oneperhhd_mc,
	exec_bus_igid,
	exec_bus_titlecode,
	exec_bus_titlecodedescription,
	exec_bus_employeesizecode,
	exec_bus_locationoutputvolumecode,
	exec_bus_primarysiccode_6digit,
	exec_cons_locationtype,
	exec_bus_fulfillment_flag,
	exec_bus_cbsa,
	exec_bus_cbsalevel,
	exec_bus_companyholdingstatus,
	exec_bus_cottagecode,
	exec_bus_mailscore,
	exec_execureach_type,
	exec_execureach_quality,
	exec_bus_actual_location_employeesize,
	exec_bus_corporate_employeesizecode,
	exec_bus_actual_location_outputvolume,
	exec_bus_corporateoutputvolumecode,
	exec_bus_square_footage,
	exec_bus_credit_alphascore,
	exec_bus_rolecode,
	exec_bus_digitalflag,
	exec_bus_businessstatuscode,
	exec_bus_departmentcode,
	exec_bus_levelcode,
	exec_bus_royalty_record,
	exec_bus_email_md5_lower,
	exec_bus_email_md5_upper,
	exec_bus_contactliteraltitlecode,
	exec_bus_contactliteraltitlecode_description,
	exec_bus_contactid,
	exec_bus_professionaltitle,
	exec_bus_companyname_available,
	exec_bus_sic2,
	exec_bus_sic4,
	exec_bus_igid_available,
	bluekaiid,
	bluekai_flag,
	haystaq_array,
	lot_size,
    email_deployable,
	Filler
)
from  's3://{s3-internal}/neptune/mGen/tblMain_1196_201301.txt'
iam_role '{iam}'
fixedwidth
'lrfsid:10,
oldid:12,
cid	:18,
firstname:15,
lastname:20,
fin_gen:1,
fin_age_old:3,
fin_indid:12,
fin_hhld:12,
file_source:1,
addressline1:30,
addressline2:30,
city:28,
st:2,
zip:5,
zip4:4,
dma:1,
deceased_flag:1,
aca:1,
fin_dob:8,
fin_ethcode:2,
fin_ethgroup:1,
fin_language:2,
fin_relcode:1,
fin_active_trade_line:1,
fin_marr_date:7,
fin_spflag:1,
lems:18,
fin_married:1,
fin_politic:1,
fl_lname:1,
ld_zip:1,
dqi_match_flag:1,
scf:3,
age_code:1,
comp:5,
matchcode:25,
dma_code:3,
zipfull:9,
edb_match_flag:1,
md5_email_lower:32,
combined_age:1,
new_mover_flag:1,
new_mover_date:5,
smb_flag:1,
sic_2:2,
sha1_email:40,
infopersona_cluster:2,
infopersona_supercluster:1,
cd_rating_2014:1,
crrt:4,
lot:5,
lotsort:2,
dpv:3,
state_code:2,
county_code:3,
ce_income_producing_assets:1,
ce_discretionary_income_score:2,
ce_pensioner_present_flag:1,
winmargin:1,
educational_model:1,
consumer_digital_match:1,
buy_segment:1,
buy_score:3,
execureach_match_flag:1,
oneperhhd_mc:18,
exec_bus_igid:9,
exec_bus_titlecode:1,
exec_bus_titlecodedescription:30,
exec_bus_employeesizecode:1,
exec_bus_locationoutputvolumecode:1,
exec_bus_primarysiccode_6digit:6,
exec_cons_locationtype:1,
exec_bus_fulfillment_flag:1,
exec_bus_cbsa:5,
exec_bus_cbsalevel:1,
exec_bus_companyholdingstatus:1,
exec_bus_cottagecode:1,
exec_bus_mailscore:2,
exec_execureach_type:1,
exec_execureach_quality:2,
exec_bus_actual_location_employeesize:5,
exec_bus_corporate_employeesizecode:1,
exec_bus_actual_location_outputvolume:9,
exec_bus_corporateoutputvolumecode:1,
exec_bus_square_footage:1,
exec_bus_credit_alphascore:2,
exec_bus_rolecode:4,
exec_bus_digitalflag:1,
exec_bus_businessstatuscode:1,
exec_bus_departmentcode:2,
exec_bus_levelcode:1,
exec_bus_royalty_record:1,
exec_bus_email_md5_lower:32,
exec_bus_email_md5_upper:32,
exec_bus_contactliteraltitlecode:8,
exec_bus_contactliteraltitlecode_description:256,
exec_bus_contactid:12,
exec_bus_professionaltitle:3,
exec_bus_companyname_available:1,
exec_bus_sic2:2,
exec_bus_sic4:4,
exec_bus_igid_available:1,
bluekaiid:32,
bluekai_flag:1,
haystaq_array:605,
lot_size ascii:5,
email_deployable:1,
filler:1'
;
