drop table if exists tblchild34_{build_id}_{build}_varchar CASCADE;

create table tblchild34_{build_id}_{build}_varchar
(
cid VARCHAR(18) ENCODE ZSTD,
ap_id VARCHAR(11) ENCODE ZSTD,
ap_lems VARCHAR(18) ENCODE ZSTD,
company_id VARCHAR(20) ENCODE ZSTD,
donormatch VARCHAR(1) ENCODE BYTEDICT,
ltd_months_since_last_donation_date VARCHAR(3) ENCODE BYTEDICT,
ltd_last_donation_date_yyyymm VARCHAR(6) ENCODE ZSTD,
ltd_number_of_list_sources VARCHAR(3) ENCODE BYTEDICT,
ltd_average_donation_per_transaction VARCHAR(3) ENCODE ZSTD,
m12_number_of_list_sources VARCHAR(3) ENCODE ZSTD,
m12_average_donation_per_transaction VARCHAR(3) ENCODE ZSTD,
m12_cat_ac_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_an_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_cd_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_cg_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_ch_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_co_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_cs_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_ea_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_et_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_hg_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_hs_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_li_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_nt_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_pa_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_rc_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_rd_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_ri_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_rj_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_ss_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_sw_number_of_donation VARCHAR(3) ENCODE ZSTD,
m12_cat_ve_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_number_of_donation_dollar_cash VARCHAR(3) ENCODE ZSTD,
m48_number_of_donation_dollar_check VARCHAR(3) ENCODE ZSTD,
m48_cat_an_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_ac_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_cd_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_cs_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_cg_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_ch_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_co_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_ea_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_et_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_hg_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_hs_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_rd_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_ri_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_li_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_nt_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_pa_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_rc_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_rj_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_ss_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_ve_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_cat_sw_number_of_donation VARCHAR(3) ENCODE ZSTD,
m48_number_of_list_sources VARCHAR(3) ENCODE ZSTD,
m48_total_number_of_donations VARCHAR(3) ENCODE ZSTD,
m48_total_dollar_donations VARCHAR(3) ENCODE ZSTD,
ltd_number_of_donations_0_3_months_ago VARCHAR(3) ENCODE ZSTD,
ltd_number_of_donations_0_6_months_ago VARCHAR(3) ENCODE ZSTD,
ltd_number_of_donations_0_12_months_ago VARCHAR(3) ENCODE ZSTD,
ltd_number_of_donations_13_24_months_ago VARCHAR(3) ENCODE ZSTD,
ltd_number_of_donations_over_24_months_ago VARCHAR(3)ENCODE BYTEDICT
)
DISTSTYLE KEY
DISTKEY(cid)
SORTKEY(cid);

copy tblchild34_{build_id}_{build}_varchar
from 's3://{s3-internal}/neptune/mGen/tblChild34_1196_201301.txt'
iam_role '{iam}'
fixedwidth
'cid:18,
ap_id:11,
ap_lems:18,
company_id:20,
donormatch:1,
ltd_months_since_last_donation_date:3,
ltd_last_donation_date_yyyymm:6,
ltd_number_of_list_sources:3,
ltd_average_donation_per_transaction:3,
m12_number_of_list_sources:3,
m12_average_donation_per_transaction:3,
m12_cat_ac_number_of_donation:3,
m12_cat_an_number_of_donation:3,
m12_cat_cd_number_of_donation:3,
m12_cat_cg_number_of_donation:3,
m12_cat_ch_number_of_donation:3,
m12_cat_co_number_of_donation:3,
m12_cat_cs_number_of_donation:3,
m12_cat_ea_number_of_donation:3,
m12_cat_et_number_of_donation:3,
m12_cat_hg_number_of_donation:3,
m12_cat_hs_number_of_donation:3,
m12_cat_li_number_of_donation:3,
m12_cat_nt_number_of_donation:3,
m12_cat_pa_number_of_donation:3,
m12_cat_rc_number_of_donation:3,
m12_cat_rd_number_of_donation:3,
m12_cat_ri_number_of_donation:3,
m12_cat_rj_number_of_donation:3,
m12_cat_ss_number_of_donation:3,
m12_cat_sw_number_of_donation:3,
m12_cat_ve_number_of_donation:3,
m48_number_of_donation_dollar_cash:3,
m48_number_of_donation_dollar_check:3,
m48_cat_an_number_of_donation:3, 
m48_cat_ac_number_of_donation:3,
m48_cat_cd_number_of_donation:3,
m48_cat_cs_number_of_donation:3,
m48_cat_cg_number_of_donation:3,
m48_cat_ch_number_of_donation:3,
m48_cat_co_number_of_donation:3,
m48_cat_ea_number_of_donation:3,
m48_cat_et_number_of_donation:3,
m48_cat_hg_number_of_donation:3,
m48_cat_hs_number_of_donation:3,
m48_cat_rd_number_of_donation:3,
m48_cat_ri_number_of_donation:3,
m48_cat_li_number_of_donation:3,
m48_cat_nt_number_of_donation:3,
m48_cat_pa_number_of_donation:3,
m48_cat_rc_number_of_donation:3,
m48_cat_rj_number_of_donation:3,
m48_cat_ss_number_of_donation:3,
m48_cat_ve_number_of_donation:3,
m48_cat_sw_number_of_donation:3,
m48_number_of_list_sources:3,
m48_total_number_of_donations:3,
m48_total_dollar_donations:3,
ltd_number_of_donations_0_3_months_ago:3,
ltd_number_of_donations_0_6_months_ago:3,
ltd_number_of_donations_0_12_months_ago:3,
ltd_number_of_donations_13_24_months_ago:3,
ltd_number_of_donations_over_24_months_ago:3';

