DROP TABLE IF EXISTS digital.business_email_fullset_raw;
create table if not exists digital.business_email_fullset_raw
(
    Acquisition_Date              varchar(6),
    VendorID2                     varchar(2),
    Usage_Indicator               varchar(1),
    Firstname                     varchar(15),
    MiddleInitial                 varchar(1),
    Lastname                      varchar(20),
    Gender                        varchar(1),
    Housenumber                   varchar(10),
    Streetpredirectional          varchar(2),
    Streetname                    varchar(28),
    Streetsuffix                  varchar(4),
    Streetpostdirectional         varchar(2),
    UnitType                      varchar(4),
    Unitnumber                    varchar(8),
    City                          varchar(28),
    State                         varchar(2),
    Zipcode                       varchar(6),
    Zipfour                       varchar(4),
    Move_Ind                      varchar(1),
    Emailaddress                  varchar(80),
    Responderdate                 varchar(6),
    Suppression_type              varchar(1),
    FamilyId                      varchar(12),
    IndividualId                  varchar(12),
    Match_Ind                     varchar(1),
    Mailconfidence                varchar(2),
    Recordtype                    varchar(1),
    Alsincome                     varchar(1),
    Alsagecode                    varchar(1),
    Alslengthofresidence          varchar(2),
    Alspurchasingpowerincome      varchar(1),
    Alshomevalue                  varchar(1),
    Alswealthfinder               varchar(1),
    psfducode                     varchar(1),
    p10ducode                     varchar(1),
    pownrocccode                  varchar(1),
    IP_Address                    varchar(15),
    Optin_Date                    varchar(8),
    Url                           varchar(60),
    StateCode                     varchar(2),
    CensusCountyCode              varchar(3),
    CensusTract                   varchar(6),
    CensusBlockGroup              varchar(1),
    MatchCode                     varchar(1),
    Editedaddress                 varchar(40),
    EmailDatabase_Extent          varchar(2),
    OldMasterIndicator            varchar(1),
    PrioritySourceCode            varchar(2),
    RoadRunner_Flag               varchar(1),
    Source_Counter                varchar(2),
    Source_Code_Indicator1        varchar(10),
    Source_Code_Indicator2        varchar(10),
    Source_Code_Indicator3        varchar(10),
    Latitude                      varchar(9),
    Longitude                     varchar(9),
    ContactID                     varchar(12),
    GST_SourceCode_Indicator      varchar(10),
    GST_Source_Counter            varchar(2),
    LemsMatchCode                 varchar(18),
    Reject_Reason                 varchar(3),
    DMA_Code                      varchar(3),
    BVT_Email_Status              varchar(1),
    BVT_Refresh_Date              varchar(8),
    IPST_Validity_Score           varchar(1),
    IPST_Status_Code              varchar(1),
    IPST_Refresh_Date             varchar(8),
    Category                      varchar(36),
    Email_Clickthru_Date          varchar(8),
    Email_Open_Date               varchar(8),
    Domain                        varchar(80),
    Top_Level_Domain              varchar(6),
    DOB_Individual                varchar(8),
    Home_Owner                    varchar(1),
    Best_Date                     varchar(8),
    Emaildb_Flag                  varchar(1),
    CountryCode                   varchar(2),
    Abinumber                     varchar(9),
    LiteralTitle                  varchar(8),
    TitleCode                     varchar(2),
    ProfTitle                     varchar(3),
    ExecutiveSourceCode           varchar(2),
    Database_Flag                 varchar(1),
    CompanyName                   varchar(30),
    AreaCode                      varchar(3),
    PhoneNumber                   varchar(7),
    SICCode                       varchar(6),
    Business_Phonenumber_Flag     varchar(1),
    Sec_Business_Areacode         varchar(3),
    Sec_Business_Ponenumber       varchar(7),
    Sec_Business_Phonenumber_Flag varchar(1),
    emailaddress_md5upper         varchar(32),
    emailaddress_md5lower         varchar(32),
    id_in                         bigint identity
);

COPY digital.business_email_fullset_raw
    FROM 's3://digital-7933-business/input/Business_email/'
    IAM_ROLE '{iam}'
    GZIP
    IGNOREBLANKLINES
    ACCEPTINVCHARS
    MAXERROR 100
    FIXEDWIDTH
    'Acquisition_Date:6,
    VendorID2:2,
    Usage_Indicator:1,
    Firstname:15,
    MiddleInitial:1,
    Lastname:20,
    Gender:1,
    Housenumber:10,
    Streetpredirectional:2,
    Streetname:28,
    Streetsuffix:4,
    Streetpostdirectional:2,
    UnitType:4,
    Unitnumber:8,
    City:28,
    State:2,
    Zipcode:6,
    Zipfour:4,
    Move_Ind:1,
    Emailaddress:80,
    Responderdate:6,
    Suppression_type:1,
    FamilyId:12,
    IndividualId:12,
    Match_Ind:1,
    Mailconfidence:2,
    Recordtype:1,
    Alsincome:1,
    Alsagecode:1,
    Alslengthofresidence:2,
    Alspurchasingpowerincome:1,
    Alshomevalue:1,
    Alswealthfinder:1,
    psfducode:1,
    p10ducode:1,
    pownrocccode:1,
    IP_Address:15,
    Optin_Date:8,
    Url:60,
    StateCode:2,
    CensusCountyCode:3,
    CensusTract:6,
    CensusBlockGroup:1,
    MatchCode:1,
    Editedaddress:40,
    EmailDatabase_Extent:2,
    OldMasterIndicator:1,
    PrioritySourceCode:2,
    RoadRunner_Flag:1,
    Source_Counter:2,
    Source_Code_Indicator1:10,
    Source_Code_Indicator2:10,
    Source_Code_Indicator3:10,
    Latitude:9,
    Longitude:9,
    ContactID:12,
    GST_SourceCode_Indicator:10,
    GST_Source_Counter:2,
    LemsMatchCode:18,
    Reject_Reason:3,
    DMA_Code:3,
    BVT_Email_Status:1,
    BVT_Refresh_Date:8,
    IPST_Validity_Score:1,
    IPST_Status_Code:1,
    IPST_Refresh_Date:8,
    Category:36,
    Email_Clickthru_Date:8,
    Email_Open_Date:8,
    Domain:80,
    Top_Level_Domain:6,
    DOB_Individual:8,
    Home_Owner:1,
    Best_Date:8,
    Emaildb_Flag:1,
    CountryCode:2,
    Abinumber:9,
    LiteralTitle:8,
    TitleCode:2,
    ProfTitle:3,
    ExecutiveSourceCode:2,
    Database_Flag:1,
    CompanyName:30,
    AreaCode:3,
    PhoneNumber:7,
    SICCode:6,
    Business_Phonenumber_Flag:1,
    Sec_Business_Areacode:3,
    Sec_Business_Ponenumber:7,
    Sec_Business_Phonenumber_Flag:1,
    emailaddress_md5upper:32,
    emailaddress_md5lower:32';
