DROP TABLE IF EXISTS {maintable_name} CASCADE;

CREATE TABLE {maintable_name}
(
ID BIGINT IDENTITY,
-- Consumer Fields
ListID INT DEFAULT {consumer_listid},
Company_ID VARCHAR(25) ENCODE ZSTD,
Individual_ID VARCHAR(25) ENCODE ZSTD,
Housenumber VARCHAR(10) ENCODE ZSTD,
Housenumberfraction VARCHAR(3) ENCODE ZSTD,
Streetpredirectional VARCHAR(2) ENCODE ZSTD,
Streetname VARCHAR(28) ENCODE ZSTD,
Streetsuffix VARCHAR(4) ENCODE ZSTD,
Streetpostdirectional VARCHAR(2) ENCODE ZSTD,
Unittype VARCHAR(4) ENCODE ZSTD,
Unitnumber VARCHAR(8) ENCODE ZSTD,
City VARCHAR(30) ENCODE ZSTD,
State VARCHAR(2) ENCODE ZSTD,
Statecode_dictionary VARCHAR(20) ENCODE ZSTD,
Zip VARCHAR(5) ENCODE ZSTD,
Zip4 VARCHAR(4) ENCODE ZSTD,
Lengthofresidence VARCHAR(2) ENCODE ZSTD,
Areacode VARCHAR(3) ENCODE ZSTD,
Phonenumber VARCHAR(7) ENCODE ZSTD,
Secondaryareacode VARCHAR(3) ENCODE ZSTD,
Secondaryphone VARCHAR(7) ENCODE ZSTD,
Areacode3 VARCHAR(3) ENCODE ZSTD,
Phonenumber3 VARCHAR(7) ENCODE ZSTD,
Areacode4 VARCHAR(3) ENCODE ZSTD,
Phonenumber4 VARCHAR(7) ENCODE ZSTD,
Hoh CHAR(1) ENCODE ZSTD,
Firstname VARCHAR(15) ENCODE ZSTD,
Middleinitial CHAR(1) ENCODE ZSTD,
Lastname VARCHAR(20) ENCODE ZSTD,
Lastnamesuffix VARCHAR(2) ENCODE ZSTD,
Gender CHAR(1) ENCODE ZSTD,
Age VARCHAR(2) ENCODE BYTEDICT,
Agecode CHAR(1) ENCODE ZSTD,
Agecode_dictionary VARCHAR(7) ENCODE BYTEDICT,
Maritalstatus CHAR(1) ENCODE ZSTD,
Maritalstatus_dictionary VARCHAR(7) ENCODE ZSTD,
Donotcallflag CHAR(1) ENCODE ZSTD,
Presenceofchildren CHAR(1) ENCODE ZSTD,
Wealthfinder CHAR(1) ENCODE ZSTD,
Wealthfinder_dictionary VARCHAR(24) ENCODE BYTEDICT,
Ownrentindicator CHAR(1) ENCODE ZSTD,
Ownrentindicator_dictionary VARCHAR(15) ENCODE ZSTD,
Mortgageloantype CHAR(1) ENCODE ZSTD,
Mortgageloantype_extended VARCHAR(30) ENCODE ZSTD,
Mortgagepresent CHAR(1) ENCODE ZSTD,
Mortgagepresent_extended VARCHAR(3) ENCODE ZSTD,
Loantovalue CHAR(1) ENCODE ZSTD,
Loantovalue_extended VARCHAR(11) ENCODE ZSTD,
Education_Model CHAR(1) ENCODE ZSTD,
Life_Insurance_Model CHAR(1) ENCODE ZSTD,
Comprehensive_Auto_Insurance_Model CHAR(1) ENCODE ZSTD,
Credit_Card_Rewards_Model CHAR(1) ENCODE ZSTD,
Frequent_Flyer_Model CHAR(1) ENCODE ZSTD,
Cruise_Model CHAR(1) ENCODE ZSTD,
Timeshare_Owner_Model CHAR(1) ENCODE ZSTD,
Rental_Car_Model CHAR(1) ENCODE ZSTD,
Health_Insurance_Model CHAR(1) ENCODE ZSTD,
Locationid VARCHAR(12) ENCODE ZSTD,
Boxtype CHAR(1) ENCODE ZSTD,
Boxnumber VARCHAR(6) ENCODE ZSTD,
Routetype CHAR(1) ENCODE ZSTD,
Routenumber VARCHAR(3) ENCODE ZSTD,
Addresstype CHAR(1) ENCODE ZSTD,
Census_State_Code_2010 VARCHAR(2) ENCODE ZSTD,
Countycode VARCHAR(3) ENCODE ZSTD,
Fipscode VARCHAR(5) ENCODE ZSTD,
Fipscode_dictionary VARCHAR(14) ENCODE ZSTD,
Scf VARCHAR(3) ENCODE ZSTD,
Zipfourmatchlevel CHAR(1) ENCODE ZSTD,
Deliverypointbarcode VARCHAR(3) ENCODE ZSTD,
Matchcode_V CHAR(1) ENCODE ZSTD,
Carrierroutecode VARCHAR(4) ENCODE ZSTD,
Carrierroutetype CHAR(1) ENCODE ZSTD,
Nielsencountyrank CHAR(1) ENCODE ZSTD,
Nielsencountyrank_dictionary VARCHAR(25) ENCODE ZSTD,
Nielsencountyregion CHAR(1) ENCODE ZSTD,
Nielsencountyregion_dictionary VARCHAR(24) ENCODE ZSTD,
Marketarea VARCHAR(3) ENCODE ZSTD,
NID VARCHAR(5) ENCODE ZSTD,
NID_Dictionary VARCHAR(50) ENCODE ZSTD,
Longitude_V VARCHAR(9) ENCODE ZSTD,
Latitude_V VARCHAR(9) ENCODE ZSTD,
Census_County_Code_2010 VARCHAR(3) ENCODE ZSTD,
Census_Tract_2010 VARCHAR(6) ENCODE ZSTD,
Census_Block_Group_2010 CHAR(1) ENCODE ZSTD,
Uspsdeliveryservicetype CHAR(1) ENCODE ZSTD,
Cbsacode VARCHAR(5) ENCODE ZSTD,
Cbsalevel CHAR(1) ENCODE ZSTD,
Csacode VARCHAR(3) ENCODE ZSTD,
Locationtype CHAR(1) ENCODE ZSTD,
Locationtype_dictionary VARCHAR(23) ENCODE ZSTD,
Residencetype CHAR(1) ENCODE ZSTD,
Residencetype_extended CHAR(1) ENCODE ZSTD,
Occupancycount VARCHAR(2) ENCODE ZSTD,
Deliveryunitsizeraw VARCHAR(2) ENCODE ZSTD,
Deliveryunitsizeraw_extended VARCHAR(11) ENCODE ZSTD,
Multipleunit CHAR(1) ENCODE ZSTD,
Householdarrivaldate VARCHAR(6) ENCODE ZSTD,
Householdarrivaldate_Year VARCHAR(4) ENCODE ZSTD,
Householdarrivaldate_Month VARCHAR(2) ENCODE ZSTD,
Areaprefix VARCHAR(6) ENCODE ZSTD,
Prefix VARCHAR(3) ENCODE ZSTD,
Exchange VARCHAR(4) ENCODE ZSTD,
Phonenumbertype CHAR(1) ENCODE ZSTD,
Secondaryphonetype CHAR(1) ENCODE ZSTD,
Phone3Type CHAR(1) ENCODE ZSTD,
Phone4Type CHAR(1) ENCODE ZSTD,
Timezone CHAR(1) ENCODE ZSTD,
Has_Primary_Telephone CHAR(1) ENCODE ZSTD,
Phonesourcecat CHAR(1) ENCODE ZSTD,
Titlecode CHAR(1) ENCODE ZSTD,
Titlecode_dictionary CHAR(1) ENCODE ZSTD,
Refreshdate VARCHAR(6) ENCODE BYTEDICT,
Recencydate VARCHAR(6) ENCODE BYTEDICT,
No_Stats_Indicator CHAR(1) ENCODE ZSTD,
Vacant_Indicator CHAR(1) ENCODE ZSTD,
Birthdate VARCHAR(6) ENCODE ZSTD,
Agedatasource CHAR(1) ENCODE ZSTD,
Marriedscore CHAR(1) ENCODE ZSTD,
Spousalindicator_Raw CHAR(1) ENCODE ZSTD,
Nameaddresssource CHAR(1) ENCODE ZSTD,
Listtype VARCHAR(2) ENCODE ZSTD,
Numbertradelines CHAR(1) ENCODE ZSTD,
Creditcard VARCHAR(10) ENCODE ZSTD,
Creditcard_Travel_And_Entertainment CHAR(1) ENCODE ZSTD,
Creditcard_Premium_Bank CHAR(1) ENCODE ZSTD,
Creditcard_Retail CHAR(1) ENCODE ZSTD,
Creditcard_Oil CHAR(1) ENCODE ZSTD,
Creditcard_Specialty_Retail CHAR(1) ENCODE ZSTD,
Creditcard_Upscale_Retail CHAR(1) ENCODE ZSTD,
Creditcard_Finance CHAR(1) ENCODE ZSTD,
Revolver_To_Transactor VARCHAR(2) ENCODE ZSTD,
Politicalparty CHAR(1) ENCODE ZSTD,
Registeredvoter CHAR(1) ENCODE ZSTD,
Numberofcontributions VARCHAR(3) ENCODE ZSTD,
Lastpartycontributedto CHAR(1) ENCODE ZSTD,
Lastpartycontributedto_dictionary VARCHAR(19) ENCODE ZSTD,
Lastcontributiondate VARCHAR(6) ENCODE ZSTD,
Contributionamount VARCHAR(7) ENCODE ZSTD,
Congressionaldistrict VARCHAR(2) ENCODE ZSTD,
Donorcode CHAR(1) ENCODE ZSTD,
Donotmailflag CHAR(1) ENCODE ZSTD,
Mailscore CHAR(1) ENCODE ZSTD,
Mailconfidence VARCHAR(2) ENCODE ZSTD,
Fulfillmentflag CHAR(1) ENCODE ZSTD,
Householdmembercount CHAR(1) ENCODE ZSTD,
Numberofadults CHAR(1) ENCODE ZSTD,
Numberofchildren CHAR(1) ENCODE ZSTD,
Children12_17 CHAR(1) ENCODE ZSTD,
Children6_11 CHAR(1) ENCODE ZSTD,
Children0_11 CHAR(1) ENCODE ZSTD,
Children0_5 CHAR(1) ENCODE ZSTD,
Purchasing_Power_Indicator VARCHAR(7) ENCODE ZSTD,
Purchasingpowerincome CHAR(1) ENCODE ZSTD,
Purchasingpowerincome_dictionary VARCHAR(19) ENCODE BYTEDICT,
Actualincome VARCHAR(7) ENCODE ZSTD,
Income CHAR(1) ENCODE ZSTD,
Income_extended VARCHAR(19) ENCODE BYTEDICT,
Income_Producing_Assets CHAR(1) ENCODE ZSTD,
Income_Producing_Assets_extended CHAR(1) ENCODE ZSTD,
Discreationary_Income_Score VARCHAR(2) ENCODE ZSTD,
Sesi VARCHAR(2) ENCODE ZSTD,
Expendableincomerank CHAR(1) ENCODE ZSTD,
Expendableincomerank_dictionary VARCHAR(41) ENCODE ZSTD,
Homeowner CHAR(1) ENCODE ZSTD,
Homeownersource CHAR(1) ENCODE ZSTD,
Mortgagedatesource CHAR(1) ENCODE ZSTD,
Mortgageamount_Extended CHAR(1) ENCODE ZSTD,
mortgageamount_dictionary VARCHAR(19) ENCODE ZSTD,
Mortgageinterestsource CHAR(1) ENCODE ZSTD,
Mortgageinterestrate VARCHAR(4) ENCODE ZSTD,
Financetype CHAR(1) ENCODE ZSTD,
Financetype_extended VARCHAR(28) ENCODE ZSTD,
Loanamount VARCHAR(4) ENCODE ZSTD,
Homevalue CHAR(1) ENCODE ZSTD,
Homevalue_extended VARCHAR(19) ENCODE BYTEDICT,
Homevaluesource CHAR(1) ENCODE ZSTD,
Homesaledate VARCHAR(8) ENCODE ZSTD,
Saledatesource CHAR(1) ENCODE ZSTD,
Homesaleprice VARCHAR(5) ENCODE ZSTD,
Salepricesource CHAR(1) ENCODE ZSTD,
Second_Property_Ind CHAR(1) ENCODE ZSTD,
Second_Property_Value VARCHAR(5) ENCODE ZSTD,
Homebuiltyear VARCHAR(4) ENCODE ZSTD,
Homeage VARCHAR(3) ENCODE ZSTD,
Homeagesource CHAR(1) ENCODE ZSTD,
Pool CHAR(1) ENCODE ZSTD,
Bathroomcount VARCHAR(3) ENCODE ZSTD,
Bedroomcount VARCHAR(2) ENCODE ZSTD,
Homeequityestimate CHAR(1) ENCODE ZSTD,
Homeequityestimate_dictionary VARCHAR(18) ENCODE BYTEDICT,
Numberoffireplaces CHAR(1) ENCODE ZSTD,
Garagetype CHAR(1) ENCODE ZSTD,
Homesize VARCHAR(5) ENCODE ZSTD,
Lotsize VARCHAR(5) ENCODE ZSTD,
Roomcount VARCHAR(2) ENCODE ZSTD,
Heatingtype_Code CHAR(1) ENCODE ZSTD,
Femaleoccupation VARCHAR(2) ENCODE ZSTD,
Maleoccupation VARCHAR(2) ENCODE ZSTD,
Mailorderbuyers VARCHAR(24) ENCODE ZSTD,
Mailresponsivecurrent CHAR(1) ENCODE ZSTD,
Mailresponsiveever CHAR(1) ENCODE ZSTD,
Mailresponsiverecent CHAR(1) ENCODE ZSTD,
Catowner CHAR(1) ENCODE ZSTD,
Dogowner CHAR(1) ENCODE ZSTD,
Grandparent_In_House CHAR(1) ENCODE ZSTD,
Veteranflag CHAR(1) ENCODE ZSTD,
Pensionflag CHAR(1) ENCODE ZSTD,
Mailorderbuyerflag CHAR(1) ENCODE ZSTD,
Stocksorbonds CHAR(1) ENCODE ZSTD,
Heavyinternetuser VARCHAR(2) ENCODE ZSTD,
Earlyinternetadopter VARCHAR(2) ENCODE ZSTD,
Potentialinvestorconsumer VARCHAR(2) ENCODE ZSTD,
Potentialinvestorconsumer_dictionary VARCHAR(2) ENCODE ZSTD,
Subfamilyindicator CHAR(1) ENCODE ZSTD,
Vendorethnicity VARCHAR(2) ENCODE ZSTD,
Vendorethnicity_extended VARCHAR(39) ENCODE ZSTD,
Vendorethnicgroup CHAR(1) ENCODE ZSTD,
Vendorethnicgroup_extended VARCHAR(16) ENCODE ZSTD,
Vendorlanguage_extended VARCHAR(45) ENCODE ZSTD,
Vendorreligion CHAR(1) ENCODE ZSTD,
Vendorreligion_extended VARCHAR(16) ENCODE ZSTD,
Countryoforigin VARCHAR(2) ENCODE ZSTD,
Countryoforigin_extended VARCHAR(20) ENCODE ZSTD,
Consumerstabilityrawscore VARCHAR(3) ENCODE ZSTD,
Consumerstabilitypercentile VARCHAR(2) ENCODE ZSTD,
Actualvacation_Expense VARCHAR(4) ENCODE ZSTD,
Vacation_Expense CHAR(1) ENCODE ZSTD,
Vacation_Expense_dictionary VARCHAR(15) ENCODE BYTEDICT,
Boatlength VARCHAR(2) ENCODE ZSTD,
Boatowner CHAR(1) ENCODE ZSTD,
Boatpropulsioncode CHAR(1) ENCODE ZSTD,
Boatpropulsioncode_extended VARCHAR(19) ENCODE ZSTD,
Boathulltype CHAR(1) ENCODE ZSTD,
Aircraftmfgyear VARCHAR(4) ENCODE ZSTD,
Pilotlicensecode CHAR(1) ENCODE ZSTD,
Pilotlicensecode_dictionary VARCHAR(19) ENCODE ZSTD,
Aircrafttypecode CHAR(1) ENCODE ZSTD,
Aircrafttypecode_dictionary VARCHAR(19) ENCODE ZSTD,
Markettargetage0_5 CHAR(1) ENCODE ZSTD,
Markettargetage0_11 CHAR(1) ENCODE ZSTD,
Markettargetage0_17 CHAR(1) ENCODE ZSTD,
Markettargetage6_11 CHAR(1) ENCODE ZSTD,
Markettargetage12_17 CHAR(1) ENCODE ZSTD,
Markettargetage12_17Female CHAR(1) ENCODE ZSTD,
Markettargetage12_17Male CHAR(1) ENCODE ZSTD,
Markettargetage18_24Female CHAR(1) ENCODE ZSTD,
Markettargetage18_24Male CHAR(1) ENCODE ZSTD,
Markettargetage18_34Female CHAR(1) ENCODE ZSTD,
Markettargetage18_34Male CHAR(1) ENCODE ZSTD,
Markettargetage18_44Female CHAR(1) ENCODE ZSTD,
Markettargetage18_44Male CHAR(1) ENCODE ZSTD,
Markettargetage25_34Female CHAR(1) ENCODE ZSTD,
Markettargetage25_34Male CHAR(1) ENCODE ZSTD,
Markettargetage35_44Female CHAR(1) ENCODE ZSTD,
Markettargetage35_44Male CHAR(1) ENCODE ZSTD,
Markettargetage35_54Female CHAR(1) ENCODE ZSTD,
Markettargetage35_54Male CHAR(1) ENCODE ZSTD,
Markettargetage45_54Female CHAR(1) ENCODE ZSTD,
Markettargetage45_54Male CHAR(1) ENCODE ZSTD,
Markettargetage50Plus CHAR(1) ENCODE ZSTD,
Markettargetage55_64Female CHAR(1) ENCODE ZSTD,
Markettargetage55_64Male CHAR(1) ENCODE ZSTD,
Markettargetage65Plus CHAR(1) ENCODE ZSTD,
Householdsize1_2 CHAR(1) ENCODE ZSTD,
Householdsize3Plus CHAR(1) ENCODE ZSTD,
Lifestyle VARCHAR(35) ENCODE ZSTD,
Ailments VARCHAR(15) ENCODE ZSTD,
Emailpresenceflag CHAR(1) ENCODE ZSTD,
Emailaddress VARCHAR(40) ENCODE ZSTD,
Alternate_Hhind CHAR(1) ENCODE ZSTD,
Digitalmatch CHAR(1) ENCODE ZSTD,
Internetuser CHAR(1) ENCODE ZSTD,
Childrenbygender0 CHAR(1) ENCODE ZSTD,
Childrenbygender1 CHAR(1) ENCODE ZSTD,
Childrenbygender2 CHAR(1) ENCODE ZSTD,
Childrenbygender3 CHAR(1) ENCODE ZSTD,
Childrenbygender4 CHAR(1) ENCODE ZSTD,
Childrenbygender5 CHAR(1) ENCODE ZSTD,
Childrenbygender6 CHAR(1) ENCODE ZSTD,
Childrenbygender7 CHAR(1) ENCODE ZSTD,
Childrenbygender8 CHAR(1) ENCODE ZSTD,
Childrenbygender9 CHAR(1) ENCODE ZSTD,
Childrenbygender10 CHAR(1) ENCODE ZSTD,
Childrenbygender11 CHAR(1) ENCODE ZSTD,
Childrenbygender12 CHAR(1) ENCODE ZSTD,
Childrenbygender13 CHAR(1) ENCODE ZSTD,
Childrenbygender14 CHAR(1) ENCODE ZSTD,
Childrenbygender15 CHAR(1) ENCODE ZSTD,
Childrenbygender16 CHAR(1) ENCODE ZSTD,
Childrenbygender17 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth0 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth1 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth2 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth3 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth4 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth5 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth6 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth7 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth8 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth9 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth10 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth11 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth12 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth13 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth14 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth15 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth16 CHAR(1) ENCODE ZSTD,
Childrenbybirthmonth17 CHAR(1) ENCODE ZSTD,
Lhi_African_American_Ethnic_Products CHAR(1) ENCODE ZSTD,
Lhi_American_History CHAR(1) ENCODE ZSTD,
Lhi_General_Apparel CHAR(1) ENCODE ZSTD,
Lhi_Automotive CHAR(1) ENCODE ZSTD,
Lhi_Baseball CHAR(1) ENCODE ZSTD,
Lhi_Basketball CHAR(1) ENCODE ZSTD,
Lhi_Bible CHAR(1) ENCODE ZSTD,
Lhi_Birds CHAR(1) ENCODE ZSTD,
Lhi_Publish_Books CHAR(1) ENCODE ZSTD,
Lhi_Business_Items CHAR(1) ENCODE ZSTD,
Lhi_Cats CHAR(1) ENCODE ZSTD,
Lhi_Collectibles CHAR(1) ENCODE ZSTD,
Lhi_College CHAR(1) ENCODE ZSTD,
Lhi_Computers CHAR(1) ENCODE ZSTD,
Lhi_Cooking CHAR(1) ENCODE ZSTD,
Lhi_General_Crafts CHAR(1) ENCODE ZSTD,
Lhi_Current_Events CHAR(1) ENCODE ZSTD,
Lhi_Do_It_Yourselfer CHAR(1) ENCODE ZSTD,
Lhi_Charitable_Donor CHAR(1) ENCODE ZSTD,
Lhi_Personalized_Products CHAR(1) ENCODE ZSTD,
Lhi_Horses CHAR(1) ENCODE ZSTD,
Lhi_Culture_Arts CHAR(1) ENCODE ZSTD,
Lhi_Dogs CHAR(1) ENCODE ZSTD,
Lhi_Children_Family CHAR(1) ENCODE ZSTD,
Lhi_Fishing CHAR(1) ENCODE ZSTD,
Lhi_Fitness_Exercise CHAR(1) ENCODE ZSTD,
Lhi_Football CHAR(1) ENCODE ZSTD,
Lhi_Gardening CHAR(1) ENCODE ZSTD,
Lhi_Gambling CHAR(1) ENCODE ZSTD,
Lhi_Gift_Giver CHAR(1) ENCODE ZSTD,
Lhi_Golf CHAR(1) ENCODE ZSTD,
Lhi_General_Health CHAR(1) ENCODE ZSTD,
Lhi_Hispanic_Ethnic_Products CHAR(1) ENCODE ZSTD,
Lhi_Hobbies CHAR(1) ENCODE ZSTD,
Lhi_Hockey CHAR(1) ENCODE ZSTD,
Lhi_Home_Decorating CHAR(1) ENCODE ZSTD,
Lhi_Humor CHAR(1) ENCODE ZSTD,
Lhi_Hunting CHAR(1) ENCODE ZSTD,
Lhi_Inspirational CHAR(1) ENCODE ZSTD,
Lhi_Apparel_Kids CHAR(1) ENCODE ZSTD,
Lhi_Apparel_Mens CHAR(1) ENCODE ZSTD,
Lhi_Money_Making CHAR(1) ENCODE ZSTD,
Lhi_Motorcycles CHAR(1) ENCODE ZSTD,
Lhi_Music CHAR(1) ENCODE ZSTD,
Lhi_Ocean CHAR(1) ENCODE ZSTD,
Lhi_Outdoors CHAR(1) ENCODE ZSTD,
Lhi_Pets CHAR(1) ENCODE ZSTD,
Lhi_Personal_Finance CHAR(1) ENCODE ZSTD,
Lhi_Rural_Farming CHAR(1) ENCODE ZSTD,
Lhi_General_Sports CHAR(1) ENCODE ZSTD,
Lhi_Stationery CHAR(1) ENCODE ZSTD,
Lhi_General_Travel CHAR(1) ENCODE ZSTD,
Lhi_Movies CHAR(1) ENCODE ZSTD,
Lhi_Wildlife CHAR(1) ENCODE ZSTD,
Lhi_Apparel_Womens CHAR(1) ENCODE ZSTD,
Lhi_Unused_01 CHAR(1) ENCODE ZSTD,
Lhi_Photography CHAR(1) ENCODE ZSTD,
Lhi_Seniors CHAR(1) ENCODE ZSTD,
Lhi_Aviation CHAR(1) ENCODE ZSTD,
Lhi_Electionics CHAR(1) ENCODE ZSTD,
Lhi_Internet CHAR(1) ENCODE ZSTD,
Lhi_Credit_Card_User CHAR(1) ENCODE ZSTD,
Lhi_Beauty_Cosmetic CHAR(1) ENCODE ZSTD,
Lhi_Asian_Ethnic_Products CHAR(1) ENCODE ZSTD,
Lhi_Dieting CHAR(1) ENCODE ZSTD,
Lhi_Science CHAR(1) ENCODE ZSTD,
Lhi_Sweepstakes CHAR(1) ENCODE ZSTD,
Lhi_Tobacco CHAR(1) ENCODE ZSTD,
Lhi_Bargain_Seekers CHAR(1) ENCODE ZSTD,
Lhi_Publications CHAR(1) ENCODE ZSTD,
Lhi_Catalogs CHAR(1) ENCODE ZSTD,
Lhi_Hightech CHAR(1) ENCODE ZSTD,
Lhi_Apparel_Accessories CHAR(1) ENCODE ZSTD,
Lhi_Apparel_Mens_Fashions CHAR(1) ENCODE ZSTD,
Lhi_Apparel_Womens_Fashions CHAR(1) ENCODE ZSTD,
Lhi_Auto_Racing CHAR(1) ENCODE ZSTD,
Lhi_Trucks CHAR(1) ENCODE ZSTD,
Lhi_Home_Office_Products CHAR(1) ENCODE ZSTD,
Lhi_Politically_Conservative CHAR(1) ENCODE ZSTD,
Lhi_Crocheting CHAR(1) ENCODE ZSTD,
Lhi_Knitting CHAR(1) ENCODE ZSTD,
Lhi_Needlepoint CHAR(1) ENCODE ZSTD,
Lhi_Quilting CHAR(1) ENCODE ZSTD,
Lhi_Sewing CHAR(1) ENCODE ZSTD,
Lhi_Fiction CHAR(1) ENCODE ZSTD,
Lhi_Games CHAR(1) ENCODE ZSTD,
Lhi_Unused_03 CHAR(1) ENCODE ZSTD,
Lhi_Gourmet CHAR(1) ENCODE ZSTD,
Lhi_History CHAR(1) ENCODE ZSTD,
Lhi_Internet_Access CHAR(1) ENCODE ZSTD,
Lhi_Internet_Buying CHAR(1) ENCODE ZSTD,
Lhi_Liberal CHAR(1) ENCODE ZSTD,
Lhi_Books_Nonfiction CHAR(1) ENCODE ZSTD,
Lhi_Boating_Sailing CHAR(1) ENCODE ZSTD,
Lhi_Camping_Hiking CHAR(1) ENCODE ZSTD,
Lhi_Hunting_Fishing CHAR(1) ENCODE ZSTD,
Lhi_Photo_Processing CHAR(1) ENCODE ZSTD,
Lhi_Magazine_Subscriber CHAR(1) ENCODE ZSTD,
Lhi_Books_Science_Fiction CHAR(1) ENCODE ZSTD,
Lhi_Skiing CHAR(1) ENCODE ZSTD,
Lhi_Soccer CHAR(1) ENCODE ZSTD,
Lhi_Tennis CHAR(1) ENCODE ZSTD,
Lhi_Travel_Cruises CHAR(1) ENCODE ZSTD,
Lhi_Travel_Rv CHAR(1) ENCODE ZSTD,
Lhi_Travel_Us CHAR(1) ENCODE ZSTD,
Green_Model CHAR(1) ENCODE ZSTD,
High_Value_Security_Investor_Model CHAR(1) ENCODE ZSTD,
Higher_Education_Model CHAR(1) ENCODE ZSTD,
High_Value_Stock_Investor_Model CHAR(1) ENCODE ZSTD,
Heavy_Investment_Trader_Model CHAR(1) ENCODE ZSTD,
Physical_Fitness_Club_Model CHAR(1) ENCODE ZSTD,
High_Risk_Investor_Model CHAR(1) ENCODE ZSTD,
Low_Risk_Investor_Model CHAR(1) ENCODE ZSTD,
Frequent_Business_Traveler_Model CHAR(1) ENCODE ZSTD,
Annuities_Model CHAR(1) ENCODE ZSTD,
Luxury_Car_Buyer_Model CHAR(1) ENCODE ZSTD,
Impulse_Buyer_Model CHAR(1) ENCODE ZSTD,
Luxury_Hotel_Model CHAR(1) ENCODE ZSTD,
Pbs_Donor_Model CHAR(1) ENCODE ZSTD,
Safety_Security_Conscious_Model CHAR(1) ENCODE ZSTD,
Shopaholics_Model CHAR(1) ENCODE ZSTD,
Avid_Theme_Park_Visitor_Model CHAR(1) ENCODE ZSTD,
Foreign_Travel_Vacation_Model CHAR(1) ENCODE ZSTD,
Conservative_Model CHAR(1) ENCODE ZSTD,
Leaning_Conservative_Model CHAR(1) ENCODE ZSTD,
Leaning_Liberal_Model CHAR(1) ENCODE ZSTD,
Religious_Donor_Model CHAR(1) ENCODE ZSTD,
Garden_Maintenance_Model CHAR(1) ENCODE ZSTD,
Heavy_Family_Restaurant_Visitor_Model CHAR(1) ENCODE ZSTD,
Heavy_Payperview_Sports_Model CHAR(1) ENCODE ZSTD,
Nascar_Model CHAR(1) ENCODE ZSTD,
Liberal_Model CHAR(1) ENCODE ZSTD,
Dog_Product_Model CHAR(1) ENCODE ZSTD,
Heavy_Payperview_Movie_Model CHAR(1) ENCODE ZSTD,
Diet_Product_Model CHAR(1) ENCODE ZSTD,
Organic_Food_Model CHAR(1) ENCODE ZSTD,
Heavy_Vitamin_Model CHAR(1) ENCODE ZSTD,
Baby_Product_Model CHAR(1) ENCODE ZSTD,
Heavy_Coupon_User_Model CHAR(1) ENCODE ZSTD,
Opinion_Leader_Model CHAR(1) ENCODE ZSTD,
Cat_Product_Model CHAR(1) ENCODE ZSTD,
High_End_Sporting_Equipment_Model CHAR(1) ENCODE ZSTD,
Home_Improvement_Model CHAR(1) ENCODE ZSTD,
High_End_Electronic_Model CHAR(1) ENCODE ZSTD,
Avid_Gamers_Model CHAR(1) ENCODE ZSTD,
Avid_Cell_Phone_User_Model CHAR(1) ENCODE ZSTD,
Country_Club_Member_Model CHAR(1) ENCODE ZSTD,
Pro_Tax_Preparation_Model CHAR(1) ENCODE ZSTD,
Onsite_Tax_Preparation_Model CHAR(1) ENCODE ZSTD,
Music_Concert_Classical_Model CHAR(1) ENCODE ZSTD,
Music_Concert_Rock_Model CHAR(1) ENCODE ZSTD,
Music_Concert_Country_Model CHAR(1) ENCODE ZSTD,
Live_Theater_Model CHAR(1) ENCODE ZSTD,
Heavy_Book_Buyer_Model CHAR(1) ENCODE ZSTD,
Fresh_Water_Fishing_Model CHAR(1) ENCODE ZSTD,
Salt_Water_Fishing_Model CHAR(1) ENCODE ZSTD,
Hunting_Model CHAR(1) ENCODE ZSTD,
Atv_Model CHAR(1) ENCODE ZSTD,
Power_Boating_Model CHAR(1) ENCODE ZSTD,
Outdoor_Activities_Model CHAR(1) ENCODE ZSTD,
Adventure_Seekers_Model CHAR(1) ENCODE ZSTD,
Low_End_Sporting_Equipment_Model CHAR(1) ENCODE ZSTD,
Professional_Baseball_Model CHAR(1) ENCODE ZSTD,
Professional_Basketball_Model CHAR(1) ENCODE ZSTD,
Professional_Football_Model CHAR(1) ENCODE ZSTD,
Soccer_Model CHAR(1) ENCODE ZSTD,
College_Basketball_Model CHAR(1) ENCODE ZSTD,
College_Football_Model CHAR(1) ENCODE ZSTD,
Golf_Model CHAR(1) ENCODE ZSTD,
Tennis_Model CHAR(1) ENCODE ZSTD,
Professional_Wrestling_Model CHAR(1) ENCODE ZSTD,
International_Long_Distance_Model CHAR(1) ENCODE ZSTD,
Frozen_Dinner_Model CHAR(1) ENCODE ZSTD,
Cook_From_Scratch_Model CHAR(1) ENCODE ZSTD,
Cook_For_Fun_Model CHAR(1) ENCODE ZSTD,
Wine_Lover_Model CHAR(1) ENCODE ZSTD,
Online_Purchase_Personal_Model CHAR(1) ENCODE ZSTD,
Online_Purchase_Business_Model CHAR(1) ENCODE ZSTD,
Online_Travel_Plan_Model CHAR(1) ENCODE ZSTD,
Blog_Writing_Model CHAR(1) ENCODE ZSTD,
Voice_Over_Internet_Model CHAR(1) ENCODE ZSTD,
Wifi_Outside_Of_Home_Model CHAR(1) ENCODE ZSTD,
Wifi_In_Home_Model CHAR(1) ENCODE ZSTD,
Wholesale_Club_Model CHAR(1) ENCODE ZSTD,
Auto_Club_Model CHAR(1) ENCODE ZSTD,
Diy_Auto_Maintenance_Model CHAR(1) ENCODE ZSTD,
Online_Gaming_Activity_Model CHAR(1) ENCODE ZSTD,
Online_Investment_Trading_Model CHAR(1) ENCODE ZSTD,
Online_Bill_Payment_Model CHAR(1) ENCODE ZSTD,
Online_Tv_Download_Model CHAR(1) ENCODE ZSTD,
Mobile_Internet_Access_Model CHAR(1) ENCODE ZSTD,
Social_Media_Network_Model CHAR(1) ENCODE ZSTD,
Specialty_Organic_Food_Store_Model CHAR(1) ENCODE ZSTD,
Home_Office_Model CHAR(1) ENCODE ZSTD,
Business_Banking_Model CHAR(1) ENCODE ZSTD,
Moderate_Economy_Hotel_Model CHAR(1) ENCODE ZSTD,
Ereader_Model CHAR(1) ENCODE ZSTD,
Cell_Phone_Only_Model CHAR(1) ENCODE ZSTD,
Alternative_Medicine_Model CHAR(1) ENCODE ZSTD,
Non_Religious_Donor_Model CHAR(1) ENCODE ZSTD,
Major_Home_Remodeling_Model CHAR(1) ENCODE ZSTD,
Avid_Smart_Phone_Users_Model CHAR(1) ENCODE ZSTD,
Satellite_Tv_Model CHAR(1) ENCODE ZSTD,
Online_Music_Download_Model CHAR(1) ENCODE ZSTD,
Adult_Education_Model CHAR(1) ENCODE ZSTD,
Pilates_Yoga_Model CHAR(1) ENCODE ZSTD,
Fast_Food_Model CHAR(1) ENCODE ZSTD,
Hybrid_Cars_Model CHAR(1) ENCODE ZSTD,
Heavy_Online_Buyer_Model CHAR(1) ENCODE ZSTD,
High_End_Apparel_Model CHAR(1) ENCODE ZSTD,
Heavy_Catalog_Buyer_Model CHAR(1) ENCODE ZSTD,
Gift_Buyers_Model CHAR(1) ENCODE ZSTD,
Camping_Model CHAR(1) ENCODE ZSTD,
Sports_Fanatics_Model CHAR(1) ENCODE ZSTD,
Financial_Planner_Model CHAR(1) ENCODE ZSTD,
Work_Health_Insurance_Model CHAR(1) ENCODE ZSTD,
Small_Business_Insurance_Model CHAR(1) ENCODE ZSTD,
Heavy_Snack_Eaters_Model CHAR(1) ENCODE ZSTD,
Heavy_Domestic_Travelers_Model CHAR(1) ENCODE ZSTD,
New_Vehicle_Buyer_Model CHAR(1) ENCODE ZSTD,
Suv_Buyer_Model CHAR(1) ENCODE ZSTD,
Minivan_Buyer_Model CHAR(1) ENCODE ZSTD,
Auto_Loan_Model CHAR(1) ENCODE ZSTD,
Education_Loan_Model CHAR(1) ENCODE ZSTD,
Real_Estate_Investment_Model CHAR(1) ENCODE ZSTD,
Fantasy_Sports_Model CHAR(1) ENCODE ZSTD,
Hockey_Buyer_Model CHAR(1) ENCODE ZSTD,
lems VARCHAR(18) ENCODE ZSTD,
Spectrum VARCHAR(2) ENCODE ZSTD,
Spectrum_dictionary VARCHAR(2) ENCODE ZSTD,
Spectrum_Group CHAR(1) ENCODE ZSTD,
Spectrum_Group_dictionary CHAR(1) ENCODE ZSTD,
Household_Status_Code_2010 CHAR(1) ENCODE ZSTD,
DeceasedFlag CHAR(1) ENCODE ZSTD,
AddressLine1 VARCHAR(50) ENCODE ZSTD,
MagazineSubscriber CHAR(1) ENCODE ZSTD,
Infopersona_Cluster	VARCHAR(2) ENCODE ZSTD,
Infopersona_Supercluster CHAR(1) ENCODE ZSTD,
Vendorlanguage CHAR(2) ENCODE ZSTD,
Assimilationcode CHAR(1) ENCODE ZSTD,
HOHAgecode	CHAR(1) ENCODE ZSTD,
LastnameAlpha CHAR(1) ENCODE ZSTD,
ZIP9 VARCHAR(9) ENCODE ZSTD,
lifestyle_fashion_jewelry_interest CHAR(1) ENCODE ZSTD,
lifestyle_books_music_interest CHAR(1) ENCODE ZSTD,
lifestyle_computer_owner CHAR(1) ENCODE ZSTD,
lifestyle_handcrafts_sewing_interest CHAR(1) ENCODE ZSTD,
lifestyle_travel_entertainment_interest CHAR(1) ENCODE ZSTD,
lifestyle_investments_interest CHAR(1) ENCODE ZSTD,
lifestyle_golfer CHAR(1) ENCODE ZSTD,
lifestyle_health_fitness_interest CHAR(1) ENCODE ZSTD,
lifestyle_outdoor_enthusiast CHAR(1) ENCODE ZSTD,
lifestyle_pet_owner CHAR(1) ENCODE ZSTD,
lifestyle_photography_enthusiast CHAR(1) ENCODE ZSTD,
lifestyle_collectibles_interest CHAR(1) ENCODE ZSTD,
lifestyle_stamps_coins_collector CHAR(1) ENCODE ZSTD,
lifestyle_opportunist CHAR(1) ENCODE ZSTD,
lifestyle_hunting CHAR(1) ENCODE ZSTD,
lifestyle_fishing CHAR(1) ENCODE ZSTD,
lifestyle_boatingsailing CHAR(1) ENCODE ZSTD,
lifestyle_foreigntravel CHAR(1) ENCODE ZSTD,
lifestyle_gambling CHAR(1) ENCODE ZSTD,
lifestyle_dietingweightloss CHAR(1) ENCODE ZSTD,
lifestyle_cooking CHAR(1) ENCODE ZSTD,
lifestyle_camping CHAR(1) ENCODE ZSTD,
lifestyle_gardening_horticulture_interest CHAR(1) ENCODE ZSTD,
lifestyle_gourmet_food_wine_interest CHAR(1) ENCODE ZSTD,
lifestyle_car_buff CHAR(1) ENCODE ZSTD,
lifestyle_cat_owner CHAR(1) ENCODE ZSTD,
lifestyle_childrens_products CHAR(1) ENCODE ZSTD,
lifestyle_homedecorating CHAR(1) ENCODE ZSTD,
lifestyle_high_tech CHAR(1) ENCODE ZSTD,
lifestyle_dog_owner CHAR(1) ENCODE ZSTD,
lifestyle_electronics CHAR(1) ENCODE ZSTD,
lifestyle_high_ticket_mail_order_buyer CHAR(1) ENCODE ZSTD,
lifestyle_home_workshop CHAR(1) ENCODE ZSTD,
lifestyle_stocks_bonds_investments CHAR(1) ENCODE ZSTD,
lifestyle_vcr CHAR(1) ENCODE ZSTD,
ailments_diabetes  CHAR(1) ENCODE ZSTD,
ailments_asthma  CHAR(1) ENCODE ZSTD,
ailments_arthritisrheumatism  CHAR(1) ENCODE ZSTD,
ailments_anginaheartdisease  CHAR(1) ENCODE ZSTD,
ailments_emphysema  CHAR(1) ENCODE ZSTD,
ailments_osteoporosis  CHAR(1) ENCODE ZSTD,
ailments_highbloodpressure  CHAR(1) ENCODE ZSTD,
ailments_highcholesterol   CHAR(1) ENCODE ZSTD,
ailments_physicalhandicap  CHAR(1) ENCODE ZSTD,
ailments_allergies  CHAR(1) ENCODE ZSTD,
ailments_hearingdifficulty  CHAR(1) ENCODE ZSTD,
ailments_migraines  CHAR(1) ENCODE ZSTD,
ailments_alzheimers  CHAR(1) ENCODE ZSTD,
ailments_bladdercontroldifficulty  CHAR(1) ENCODE ZSTD,
ailments_frequentheadaches CHAR(1) ENCODE ZSTD,
donor_health  CHAR(1) ENCODE ZSTD,
donor_political  CHAR(1) ENCODE ZSTD,
donor_religious  CHAR(1) ENCODE ZSTD,
donor_environmental  CHAR(1) ENCODE ZSTD,
donor_ever CHAR(1) ENCODE ZSTD,
mailorderbuyers_highticket_merchandise CHAR(1) ENCODE ZSTD,
mailorderbuyers_housekeeping_decorating CHAR(1) ENCODE ZSTD,
mailorderbuyers_golf_interest CHAR(1) ENCODE ZSTD,
mailorderbuyers_do_it_yourself CHAR(1) ENCODE ZSTD,
mailorderbuyers_outdoor_gardening CHAR(1) ENCODE ZSTD,
mailorderbuyers_gourmet_food_wine CHAR(1) ENCODE ZSTD,
mailorderbuyers_car_buff CHAR(1) ENCODE ZSTD,
mailorderbuyers_pet_owner CHAR(1) ENCODE ZSTD,
mailorderbuyers_computer_owner CHAR(1) ENCODE ZSTD,
mailorderbuyers_electronics CHAR(1) ENCODE ZSTD,
mailorderbuyers_health_fitness_interest CHAR(1) ENCODE ZSTD,
mailorderbuyers_craft_sewing_interest CHAR(1) ENCODE ZSTD,
mailorderbuyers_books_music_interest CHAR(1) ENCODE ZSTD,
mailorderbuyers_finance_investment_interest CHAR(1) ENCODE ZSTD,
mailorderbuyers_outdoor_recreational_enthusiast CHAR(1) ENCODE ZSTD,
mailorderbuyers_travel_Entertainment_interest CHAR(1) ENCODE ZSTD,
mailorderbuyers_sweepstakes_gambling CHAR(1) ENCODE ZSTD,
mailorderbuyers_photography_enthusiast CHAR(1) ENCODE ZSTD,
mailorderbuyers_stamps_coins_collector CHAR(1) ENCODE ZSTD,
mailorderbuyers_sports_cards_collectibles_interest CHAR(1) ENCODE ZSTD,
mailorderbuyers_magazines CHAR(1) ENCODE ZSTD,
mailorderbuyers_apparel CHAR(1) ENCODE ZSTD,
mailorderbuyers_computer_software_purchase CHAR(1) ENCODE ZSTD,
mailorderbuyers_children CHAR(1) ENCODE ZSTD,

-- Custom Fields
-- For Non-Matches Donors Load
AccountNo VARCHAR(100) ENCODE ZSTD,
UniqueFlag VARCHAR(2) ENCODE ZSTD DEFAULT 'N',
SuppressUnique VARCHAR(2) ENCODE ZSTD DEFAULT 'N',
Individual_MC VARCHAR(25) ENCODE ZSTD DEFAULT '',
Company_MC VARCHAR(25) ENCODE ZSTD DEFAULT '',
AddressLine2 VARCHAR(50) ENCODE ZSTD DEFAULT '',

flatitude double precision ENCODE raw,
flongitude double precision ENCODE raw
)
DISTSTYLE KEY
DISTKEY(id)
SORTKEY(id);

--Copy data from s3 to redshift staging table
COPY {maintable_name}
(
Company_ID,
Individual_ID,
Housenumber,
Housenumberfraction,
Streetpredirectional,
Streetname,
Streetsuffix,
Streetpostdirectional,
Unittype,
Unitnumber,
City,
State,
Statecode_dictionary,
Zip,
Zip4,
Lengthofresidence,
Areacode,
Phonenumber,
Secondaryareacode,
Secondaryphone,
Areacode3,
Phonenumber3,
Areacode4,
Phonenumber4,
Hoh,
Firstname,
Middleinitial,
Lastname,
Lastnamesuffix,
Gender,
Age,
Agecode,
Agecode_dictionary,
Maritalstatus,
Maritalstatus_dictionary,
Donotcallflag,
Presenceofchildren,
Wealthfinder,
Wealthfinder_dictionary,
Ownrentindicator,
Ownrentindicator_dictionary,
Mortgageloantype,
Mortgageloantype_extended,
Mortgagepresent,
Mortgagepresent_extended,
Loantovalue,
Loantovalue_extended,
Education_Model,
Life_Insurance_Model,
Comprehensive_Auto_Insurance_Model,
Credit_Card_Rewards_Model,
Frequent_Flyer_Model,
Cruise_Model,
Timeshare_Owner_Model,
Rental_Car_Model,
Health_Insurance_Model,
Locationid,
Boxtype,
Boxnumber,
Routetype,
Routenumber,
Addresstype,
Census_State_Code_2010,
Countycode,
Fipscode,
Fipscode_dictionary,
Scf,
Zipfourmatchlevel,
Deliverypointbarcode,
Matchcode_V,
Carrierroutecode,
Carrierroutetype,
Nielsencountyrank,
Nielsencountyrank_dictionary,
Nielsencountyregion,
Nielsencountyregion_dictionary,
Marketarea,
NID,
NID_Dictionary,
Longitude_V,
Latitude_V,
Census_County_Code_2010,
Census_Tract_2010,
Census_Block_Group_2010,
Uspsdeliveryservicetype,
Cbsacode,
Cbsalevel,
Csacode,
Locationtype,
Locationtype_dictionary,
Residencetype,
Residencetype_extended,
Occupancycount,
Deliveryunitsizeraw,
Deliveryunitsizeraw_extended,
Multipleunit,
Householdarrivaldate,
Householdarrivaldate_Year,
Householdarrivaldate_Month,
Areaprefix,
Prefix,
Exchange,
Phonenumbertype,
Secondaryphonetype,
Phone3Type,
Phone4Type,
Timezone,
Has_Primary_Telephone,
Phonesourcecat,
Titlecode,
Titlecode_dictionary,
Refreshdate,
Recencydate,
No_Stats_Indicator,
Vacant_Indicator,
Birthdate,
Agedatasource,
Marriedscore,
Spousalindicator_Raw,
Nameaddresssource,
Listtype,
Numbertradelines,
Creditcard,
Creditcard_Travel_And_Entertainment,
Creditcard_Premium_Bank,
Creditcard_Retail,
Creditcard_Oil,
Creditcard_Specialty_Retail,
Creditcard_Upscale_Retail,
Creditcard_Finance,
Revolver_To_Transactor,
Politicalparty,
Registeredvoter,
Numberofcontributions,
Lastpartycontributedto,
Lastpartycontributedto_dictionary,
Lastcontributiondate,
Contributionamount,
Congressionaldistrict,
Donorcode,
Donotmailflag,
Mailscore,
Mailconfidence,
Fulfillmentflag,
Householdmembercount,
Numberofadults,
Numberofchildren,
Children12_17,
Children6_11,
Children0_11,
Children0_5,
Purchasing_Power_Indicator,
Purchasingpowerincome,
Purchasingpowerincome_dictionary,
Actualincome,
Income,
Income_extended,
Income_Producing_Assets,
Income_Producing_Assets_extended,
Discreationary_Income_Score,
Sesi,
Expendableincomerank,
Expendableincomerank_dictionary,
Homeowner,
Homeownersource,
Mortgagedatesource,
Mortgageamount_Extended,
mortgageamount_dictionary,
Mortgageinterestsource,
Mortgageinterestrate,
Financetype,
Financetype_extended,
Loanamount,
Homevalue,
Homevalue_extended,
Homevaluesource,
Homesaledate,
Saledatesource,
Homesaleprice,
Salepricesource,
Second_Property_Ind,
Second_Property_Value,
Homebuiltyear,
Homeage,
Homeagesource,
Pool,
Bathroomcount,
Bedroomcount,
Homeequityestimate,
Homeequityestimate_dictionary,
Numberoffireplaces,
Garagetype,
Homesize,
Lotsize,
Roomcount,
Heatingtype_Code,
Femaleoccupation,
Maleoccupation,
Mailorderbuyers,
Mailresponsivecurrent,
Mailresponsiveever,
Mailresponsiverecent,
Catowner,
Dogowner,
Grandparent_In_House,
Veteranflag,
Pensionflag,
Mailorderbuyerflag,
Stocksorbonds,
Heavyinternetuser,
Earlyinternetadopter,
Potentialinvestorconsumer,
Potentialinvestorconsumer_dictionary,
Subfamilyindicator,
Vendorethnicity,
Vendorethnicity_extended,
Vendorethnicgroup,
Vendorethnicgroup_extended,
Vendorlanguage_extended,
Vendorreligion,
Vendorreligion_extended,
Countryoforigin,
Countryoforigin_extended,
Consumerstabilityrawscore,
Consumerstabilitypercentile,
Actualvacation_Expense,
Vacation_Expense,
Vacation_Expense_dictionary,
Boatlength,
Boatowner,
Boatpropulsioncode,
Boatpropulsioncode_extended,
Boathulltype,
Aircraftmfgyear,
Pilotlicensecode,
Pilotlicensecode_dictionary,
Aircrafttypecode,
Aircrafttypecode_dictionary,
Markettargetage0_5,
Markettargetage0_11,
Markettargetage0_17,
Markettargetage6_11,
Markettargetage12_17,
Markettargetage12_17Female,
Markettargetage12_17Male,
Markettargetage18_24Female,
Markettargetage18_24Male,
Markettargetage18_34Female,
Markettargetage18_34Male,
Markettargetage18_44Female,
Markettargetage18_44Male,
Markettargetage25_34Female,
Markettargetage25_34Male,
Markettargetage35_44Female,
Markettargetage35_44Male,
Markettargetage35_54Female,
Markettargetage35_54Male,
Markettargetage45_54Female,
Markettargetage45_54Male,
Markettargetage50Plus,
Markettargetage55_64Female,
Markettargetage55_64Male,
Markettargetage65Plus,
Householdsize1_2,
Householdsize3Plus,
Lifestyle,
Ailments,
Emailpresenceflag,
Emailaddress,
Alternate_Hhind,
Digitalmatch,
Internetuser,
Childrenbygender0,
Childrenbygender1,
Childrenbygender2,
Childrenbygender3,
Childrenbygender4,
Childrenbygender5,
Childrenbygender6,
Childrenbygender7,
Childrenbygender8,
Childrenbygender9,
Childrenbygender10,
Childrenbygender11,
Childrenbygender12,
Childrenbygender13,
Childrenbygender14,
Childrenbygender15,
Childrenbygender16,
Childrenbygender17,
Childrenbybirthmonth0,
Childrenbybirthmonth1,
Childrenbybirthmonth2,
Childrenbybirthmonth3,
Childrenbybirthmonth4,
Childrenbybirthmonth5,
Childrenbybirthmonth6,
Childrenbybirthmonth7,
Childrenbybirthmonth8,
Childrenbybirthmonth9,
Childrenbybirthmonth10,
Childrenbybirthmonth11,
Childrenbybirthmonth12,
Childrenbybirthmonth13,
Childrenbybirthmonth14,
Childrenbybirthmonth15,
Childrenbybirthmonth16,
Childrenbybirthmonth17,
Lhi_African_American_Ethnic_Products,
Lhi_American_History,
Lhi_General_Apparel,
Lhi_Automotive,
Lhi_Baseball,
Lhi_Basketball,
Lhi_Bible,
Lhi_Birds,
Lhi_Publish_Books,
Lhi_Business_Items,
Lhi_Cats,
Lhi_Collectibles,
Lhi_College,
Lhi_Computers,
Lhi_Cooking,
Lhi_General_Crafts,
Lhi_Current_Events,
Lhi_Do_It_Yourselfer,
Lhi_Charitable_Donor,
Lhi_Personalized_Products,
Lhi_Horses,
Lhi_Culture_Arts,
Lhi_Dogs,
Lhi_Children_Family,
Lhi_Fishing,
Lhi_Fitness_Exercise,
Lhi_Football,
Lhi_Gardening,
Lhi_Gambling,
Lhi_Gift_Giver,
Lhi_Golf,
Lhi_General_Health,
Lhi_Hispanic_Ethnic_Products,
Lhi_Hobbies,
Lhi_Hockey,
Lhi_Home_Decorating,
Lhi_Humor,
Lhi_Hunting,
Lhi_Inspirational,
Lhi_Apparel_Kids,
Lhi_Apparel_Mens,
Lhi_Money_Making,
Lhi_Motorcycles,
Lhi_Music,
Lhi_Ocean,
Lhi_Outdoors,
Lhi_Pets,
Lhi_Personal_Finance,
Lhi_Rural_Farming,
Lhi_General_Sports,
Lhi_Stationery,
Lhi_General_Travel,
Lhi_Movies,
Lhi_Wildlife,
Lhi_Apparel_Womens,
Lhi_Unused_01,
Lhi_Photography,
Lhi_Seniors,
Lhi_Aviation,
Lhi_Electionics,
Lhi_Internet,
Lhi_Credit_Card_User,
Lhi_Beauty_Cosmetic,
Lhi_Asian_Ethnic_Products,
Lhi_Dieting,
Lhi_Science,
Lhi_Sweepstakes,
Lhi_Tobacco,
Lhi_Bargain_Seekers,
Lhi_Publications,
Lhi_Catalogs,
Lhi_Hightech,
Lhi_Apparel_Accessories,
Lhi_Apparel_Mens_Fashions,
Lhi_Apparel_Womens_Fashions,
Lhi_Auto_Racing,
Lhi_Trucks,
Lhi_Home_Office_Products,
Lhi_Politically_Conservative,
Lhi_Crocheting,
Lhi_Knitting,
Lhi_Needlepoint,
Lhi_Quilting,
Lhi_Sewing,
Lhi_Fiction,
Lhi_Games,
Lhi_Unused_03,
Lhi_Gourmet,
Lhi_History,
Lhi_Internet_Access,
Lhi_Internet_Buying,
Lhi_Liberal,
Lhi_Books_Nonfiction,
Lhi_Boating_Sailing,
Lhi_Camping_Hiking,
Lhi_Hunting_Fishing,
Lhi_Photo_Processing,
Lhi_Magazine_Subscriber,
Lhi_Books_Science_Fiction,
Lhi_Skiing,
Lhi_Soccer,
Lhi_Tennis,
Lhi_Travel_Cruises,
Lhi_Travel_Rv,
Lhi_Travel_Us,
Green_Model,
High_Value_Security_Investor_Model,
Higher_Education_Model,
High_Value_Stock_Investor_Model,
Heavy_Investment_Trader_Model,
Physical_Fitness_Club_Model,
High_Risk_Investor_Model,
Low_Risk_Investor_Model,
Frequent_Business_Traveler_Model,
Annuities_Model,
Luxury_Car_Buyer_Model,
Impulse_Buyer_Model,
Luxury_Hotel_Model,
Pbs_Donor_Model,
Safety_Security_Conscious_Model,
Shopaholics_Model,
Avid_Theme_Park_Visitor_Model,
Foreign_Travel_Vacation_Model,
Conservative_Model,
Leaning_Conservative_Model,
Leaning_Liberal_Model,
Religious_Donor_Model,
Garden_Maintenance_Model,
Heavy_Family_Restaurant_Visitor_Model,
Heavy_Payperview_Sports_Model,
Nascar_Model,
Liberal_Model,
Dog_Product_Model,
Heavy_Payperview_Movie_Model,
Diet_Product_Model,
Organic_Food_Model,
Heavy_Vitamin_Model,
Baby_Product_Model,
Heavy_Coupon_User_Model,
Opinion_Leader_Model,
Cat_Product_Model,
High_End_Sporting_Equipment_Model,
Home_Improvement_Model,
High_End_Electronic_Model,
Avid_Gamers_Model,
Avid_Cell_Phone_User_Model,
Country_Club_Member_Model,
Pro_Tax_Preparation_Model,
Onsite_Tax_Preparation_Model,
Music_Concert_Classical_Model,
Music_Concert_Rock_Model,
Music_Concert_Country_Model,
Live_Theater_Model,
Heavy_Book_Buyer_Model,
Fresh_Water_Fishing_Model,
Salt_Water_Fishing_Model,
Hunting_Model,
Atv_Model,
Power_Boating_Model,
Outdoor_Activities_Model,
Adventure_Seekers_Model,
Low_End_Sporting_Equipment_Model,
Professional_Baseball_Model,
Professional_Basketball_Model,
Professional_Football_Model,
Soccer_Model,
College_Basketball_Model,
College_Football_Model,
Golf_Model,
Tennis_Model,
Professional_Wrestling_Model,
International_Long_Distance_Model,
Frozen_Dinner_Model,
Cook_From_Scratch_Model,
Cook_For_Fun_Model,
Wine_Lover_Model,
Online_Purchase_Personal_Model,
Online_Purchase_Business_Model,
Online_Travel_Plan_Model,
Blog_Writing_Model,
Voice_Over_Internet_Model,
Wifi_Outside_Of_Home_Model,
Wifi_In_Home_Model,
Wholesale_Club_Model,
Auto_Club_Model,
Diy_Auto_Maintenance_Model,
Online_Gaming_Activity_Model,
Online_Investment_Trading_Model,
Online_Bill_Payment_Model,
Online_Tv_Download_Model,
Mobile_Internet_Access_Model,
Social_Media_Network_Model,
Specialty_Organic_Food_Store_Model,
Home_Office_Model,
Business_Banking_Model,
Moderate_Economy_Hotel_Model,
Ereader_Model,
Cell_Phone_Only_Model,
Alternative_Medicine_Model,
Non_Religious_Donor_Model,
Major_Home_Remodeling_Model,
Avid_Smart_Phone_Users_Model,
Satellite_Tv_Model,
Online_Music_Download_Model,
Adult_Education_Model,
Pilates_Yoga_Model,
Fast_Food_Model,
Hybrid_Cars_Model,
Heavy_Online_Buyer_Model,
High_End_Apparel_Model,
Heavy_Catalog_Buyer_Model,
Gift_Buyers_Model,
Camping_Model,
Sports_Fanatics_Model,
Financial_Planner_Model,
Work_Health_Insurance_Model,
Small_Business_Insurance_Model,
Heavy_Snack_Eaters_Model,
Heavy_Domestic_Travelers_Model,
New_Vehicle_Buyer_Model,
Suv_Buyer_Model,
Minivan_Buyer_Model,
Auto_Loan_Model,
Education_Loan_Model,
Real_Estate_Investment_Model,
Fantasy_Sports_Model,
Hockey_Buyer_Model,
lems,
Spectrum,
Spectrum_dictionary,
Spectrum_Group,
Spectrum_Group_dictionary,
Household_Status_Code_2010,
DeceasedFlag,
AddressLine1,
MagazineSubscriber,
Infopersona_Cluster,
Infopersona_Supercluster,
Vendorlanguage,
Assimilationcode,
HOHAgecode,
LastnameAlpha,
ZIP9,
lifestyle_fashion_jewelry_interest,
lifestyle_books_music_interest,
lifestyle_computer_owner,
lifestyle_handcrafts_sewing_interest,
lifestyle_travel_entertainment_interest,
lifestyle_investments_interest,
lifestyle_golfer,
lifestyle_health_fitness_interest,
lifestyle_outdoor_enthusiast,
lifestyle_pet_owner,
lifestyle_photography_enthusiast,
lifestyle_collectibles_interest,
lifestyle_stamps_coins_collector,
lifestyle_opportunist,
lifestyle_hunting,
lifestyle_fishing,
lifestyle_boatingsailing,
lifestyle_foreigntravel,
lifestyle_gambling,
lifestyle_dietingweightloss,
lifestyle_cooking,
lifestyle_camping,
lifestyle_gardening_horticulture_interest,
lifestyle_gourmet_food_wine_interest,
lifestyle_car_buff,
lifestyle_cat_owner,
lifestyle_childrens_products,
lifestyle_homedecorating,
lifestyle_high_tech,
lifestyle_dog_owner,
lifestyle_electronics,
lifestyle_high_ticket_mail_order_buyer,
lifestyle_home_workshop,
lifestyle_stocks_bonds_investments,
lifestyle_vcr,
ailments_diabetes,
ailments_asthma,
ailments_arthritisrheumatism,
ailments_anginaheartdisease,
ailments_emphysema,
ailments_osteoporosis,
ailments_highbloodpressure,
ailments_highcholesterol ,
ailments_physicalhandicap,
ailments_allergies,
ailments_hearingdifficulty,
ailments_migraines,
ailments_alzheimers,
ailments_bladdercontroldifficulty,
ailments_frequentheadaches,
donor_health,
donor_political,
donor_religious,
donor_environmental,
donor_ever,
mailorderbuyers_highticket_merchandise,
mailorderbuyers_housekeeping_decorating,
mailorderbuyers_golf_interest,
mailorderbuyers_do_it_yourself,
mailorderbuyers_outdoor_gardening,
mailorderbuyers_gourmet_food_wine,
mailorderbuyers_car_buff,
mailorderbuyers_pet_owner,
mailorderbuyers_computer_owner,
mailorderbuyers_electronics,
mailorderbuyers_health_fitness_interest,
mailorderbuyers_craft_sewing_interest,
mailorderbuyers_books_music_interest,
mailorderbuyers_finance_investment_interest,
mailorderbuyers_outdoor_recreational_enthusiast,
mailorderbuyers_travel_Entertainment_interest,
mailorderbuyers_sweepstakes_gambling,
mailorderbuyers_photography_enthusiast,
mailorderbuyers_stamps_coins_collector,
mailorderbuyers_sports_cards_collectibles_interest,
mailorderbuyers_magazines,
mailorderbuyers_apparel,
mailorderbuyers_computer_software_purchase,
mailorderbuyers_children
)
FROM 's3://{bucket_name}/{yyyy}-{mm}/'
--FROM 's3://axle-gold-sources/people-mmdb-universe/2022-07/idms_dqiuniv_0000.gz'
IAM_ROLE '{iam}'
GZIP
DELIMITER ','
ACCEPTINVCHARS
REMOVEQUOTES
TRUNCATECOLUMNS
IGNOREHEADER 1;
