Truncate table {tablename3};

INSERT INTO {tablename3}
(
MMDBKey,
DT_PartyType,
DT_FilingState,
IUSAKey,
DT_OriginalFilingID,
DT_SourceFilingID,
DT_Filing_Date,
DT_Filing_Day,
DT_Filing_Month,
DT_Filing_Year,
DT_FilingStatus,
DT_FilingTypeCode,
DT_DateAdded,
DT_DateAdded_Day,
DT_DateAdded_Month,
DT_DateAdded_Year,
DT_DateLastReceived,
DT_DateLastReceived_Day,
DT_DateLastReceived_Month,
DT_DateLastReceived_Year,
DT_ExpirationDate,
DT_ExpirationDate_Day,
DT_ExpirationDate_Month,
DT_ExpirationDate_Year,
DT_CorporateIndividual,
DT_ABINumber,
DT_Company,
DT_LastName,
DT_FirstName,
DT_MiddleName,
DT_NameSuffix,
DT_Address,
DT_City,
DT_State,
DT_ZipCode,
DT_Zip4,
DT_DeliveryPointBarCode,
DT_DeliverabilityScore,
DT_CarrierRouteCode,
DT_USPSRecordType,
DT_MatchType,
DT_MatchScore,
DT_CollateralType,
DT_CollateralType2,
DT_CollateralType3,
DT_CollateralType4,
DT_CollateralType5,
DT_CollateralType6,
DT_CollateralType7,
DT_CollateralType8,
DT_CollateralType9,
DT_CollateralType10,
DT_StateCode,
DT_CountyCode,
DT_CountyCode_Description,

--SECURED PARTY FIELDS
SP_ABINumber,
SP_LocationName,
SP_Address,
SP_City,
SP_State,
SP_Zip,
SP_ZIP4
)

SELECT DISTINCT
A.MMDBKey,
A.PartyType,
A.FilingState,
A.IUSAkey,
A.OriginalFilingID,
A.SourceFilingID,
A.FilingDate,
right(A.FilingDate, 2) Filing_Day,
right(left(A.FilingDate, 6), 2) Filing_Month,
left(A.FilingDate, 4) Filing_Year,
A.FilingStatus,
A.FilingTypeCode,
A.DateAdded,
right(A.DateAdded, 2) DateAdded_Day,
right(left(A.DateAdded, 6), 2) DateAdded_Month,
left(A.DateAdded, 4) DateAdded_Year,
A.DateLastReceived,
right(A.DateLastReceived, 2) DateLastReceived_Day,
right(left(A.DateLastReceived, 6), 2) DateLastReceived_Month,
left(A.DateLastReceived, 4) DateLastReceived_Year,
A.ExpirationDate,
right(A.ExpirationDate, 2) ExpirationDate_Day,
right(left(A.ExpirationDate, 6), 2) ExpirationDate_Month,
left(A.ExpirationDate, 4) ExpirationDate_Year,
A.CorporateIndividual,
A.Abinumber,
A.LocationName,
A.LastName,
A.FirstName,
A.MiddleName,
A.NameSuffix,
A.Address,
A.City,
A.State,
A.ZipCode,
A.ZipFour,
A.DeliveryPointBarCode,
A.DeliverabilityScore,
A.CarrierRouteCode,
A.USPSRecordType,
A.MatchType,
A.MatchScore,
A.CollateralType1,
A.CollateralType2,
A.CollateralType3,
A.CollateralType4,
A.CollateralType5,
A.CollateralType6,
A.CollateralType7,
A.CollateralType8,
A.CollateralType9,
A.CollateralType10,
A.StateCode,
A.CountyCode,
A.CountyDescription,
--SECURED PARTY FIELDS
B.abinumber,
B.locationname,
B.address,
B.city,
B.state,
B.zipcode,
B.zipfour 
FROM {tablename1} a inner join {tablename2} b on a.mmdbkey = b.mmdbkey ;

--select count(*) from rr_ucc_new













































-- Truncate table {tablename3};
-- insert into {tablename3}(
-- MMDBKey,
-- DT_PartyType,
-- DT_FilingState,
-- IUSAKey,
-- DT_OriginalFilingID,
-- DT_SourceFilingID,
-- DT_Filing_Date,
-- DT_Filing_Day,
-- DT_Filing_Month,
-- DT_Filing_Year,
-- DT_FilingStatus,
-- DT_FilingTypeCode,
-- DT_DateAdded,
-- DT_DateAdded_Day,
-- DT_DateAdded_Month,
-- DT_DateAdded_Year,
-- DT_DateLastReceived,
-- DT_DateLastReceived_Day,
-- DT_DateLastReceived_Month,
-- DT_DateLastReceived_Year,
-- DT_ExpirationDate,
-- DT_ExpirationDate_Day,
-- DT_ExpirationDate_Month,
-- DT_ExpirationDate_Year,
-- DT_CorporateIndividual,
-- DT_ABINumber,
-- DT_Company,
-- DT_LastName,
-- DT_FirstName,
-- DT_MiddleName,
-- DT_NameSuffix,
-- DT_Address,
-- DT_City,
-- DT_State,
-- DT_ZipCode,
-- DT_Zip4,
-- DT_DeliveryPointBarCode,
-- DT_DeliverabilityScore,
-- DT_CarrierRouteCode,
-- DT_USPSRecordType,
-- DT_MatchType,
-- DT_MatchScore,
-- DT_CollateralType1,
-- DT_CollateralType2,
-- DT_CollateralType3,
-- DT_CollateralType4,
-- DT_CollateralType5,
-- DT_CollateralType6,
-- DT_CollateralType7,
-- DT_CollateralType8,
-- DT_CollateralType9,
-- DT_CollateralType10,
-- DT_StateCode,
-- DT_CountyCode,
-- DT_CountyCode_Description,
-- --SECURED PARTY FIELDS
-- SP_ABINumber,
-- SP_LocationName,
-- SP_Address,
-- SP_City,
-- SP_State,
-- SP_Zip,
-- SP_ZIP4,

-- --update with 992 data
-- IG_Company,
-- IG_Location_Address,
-- IG_Location_City,
-- IG_Location_State,
-- IG_Location_Zip,
-- IG_Location_ZipFour,
-- IG_Location_CarrierRouteCode,
-- IG_Mailing_Address,
-- IG_Mailing_City,
-- IG_Mailing_State,
-- IG_Mailing_StateCode,
-- IG_Mailing_Zip,
-- IG_Mailing_ZipFour,
-- IG_Mailing_CarrierRouteCode,
-- IG_CountyCode,
-- IG_CensusTract,
-- IG_CensusBlock,
-- fLATITUDE,
-- fLONGITUDE,
-- IG_MatchCode,
-- IG_PhoneNumber,
-- IG_FaxPhone,
-- IG_PrimarySIC6,
-- IG_SICCode1,
-- IG_SICCode2,
-- IG_SICCode3,
-- IG_SICCode4,
-- IG_NAICSCode,
-- IG_NumberEmployees,
-- IG_EmployeeSizeCode2,
-- IG_OutputVolume2,
-- IG_OutputVolumeCode2,
-- IG_CreditNumericScore,
-- IG_CreditAlphaScore,
-- IG_BusinessStatusCode,
-- IG_CallStatusCode,
-- IG_CottageCode,
-- Ig_OwnOrLease,
-- IG_ParentABINumber,
-- IG_SubsidairyABINumber,
-- IG_WebAddress,
-- IG_YearFirstAppeared,
-- IG_CBSACode,
-- IG_CBSALevel,
-- IG_CSACode,
-- FULFILLMENT_FLAG,
-- IG_SquareFootage8,
-- IG_PhoneNumberType,
-- IG_LegalName,
-- IG_Mailing_SCF,
-- AddressLine1,
-- City,
-- State,
-- Zip,
-- IG_Mailing_StateCountyName,
-- IG_Mailing_StateCity,
-- IG_Mailing_StateCityZip,
-- IG_Mailing_StateCountyCode,
-- IG_Mailing_StateCitySCF,
-- IGE_FullName,
-- IGE_TitleCode,
-- IGE_TitleCode_Back,
-- IGE_VendorEthnicity,
-- IGE_ContactID,
-- FirstName,
-- LastName,
-- Gender,
-- TitleCode,
-- BusinessEmailFlag,
-- DT_Filing_YYYYMM,
-- MATCHCODE_LRFS,
-- Has_IG_Mailing_Address,
-- --IG_Mailing_Address,
-- Has_IGE_ContactName,
-- Has_IG_WebAddress,
-- Has_IG_PhoneNumber,
-- --IG_OutputVolumeCode2,
-- DT_statecountycode,
-- Has_DT_FullName,
-- DT_FullName,
-- DT_CollateralType_Comb,
-- DT_CollateralType_Multi,
-- --Fulfillment_Flag,
-- DT_AddressZip,
-- --IGE_TitleCode,
-- --dd values
-- DT_CorporateIndividual_Description,
-- DT_DeliverabilityScore_Description,
-- DT_FilingState_Description,
-- DT_FilingStatus_Description,
-- DT_FilingTypeCode_Description,
-- DT_USPSRecordType_Description,
-- DT_MatchType_Description,
-- DT_CollateralType_Description,
-- IGE_TitleCode_Description,
-- IGE_VendorEthnicity_Description,
-- IG_Mailing_State_Description,
-- IG_MatchCode_Description,
-- IG_EmployeeSizeCode2_Description,
-- IG_OutputVolumeCode2_Description,
-- IG_BusinessStatusCode_Description,
-- IG_CreditAlphaScore_Description,
-- IG_CottageCode_Description,
-- IG_OwnOrLease_Description,
-- IG_Squarefootage8_Description,
-- IG_CallStatusCode_Description,
-- Fulfillment_Flag_Description,
-- IG_CBSALevel_Description,
-- State_Description,
-- IG_PrimarySIC6_Description,
-- IG_SICCode1_Description,
-- IG_SICCode2_Description,
-- IG_SICCode3_Description,
-- IG_SICCode4_Description,
-- IG_NAICSCode_Description,
-- IG_CountyCode_Description
-- )
-- select MMDBKey,
-- DT_PartyType,
-- DT_FilingState,
-- IUSAKey,
-- DT_OriginalFilingID,
-- DT_SourceFilingID,
-- DT_Filing_Date,
-- DT_Filing_Day,
-- DT_Filing_Month,
-- DT_Filing_Year,
-- DT_FilingStatus,
-- DT_FilingTypeCode,
-- DT_DateAdded,
-- DT_DateAdded_Day,
-- DT_DateAdded_Month,
-- DT_DateAdded_Year,
-- DT_DateLastReceived,
-- DT_DateLastReceived_Day,
-- DT_DateLastReceived_Month,
-- DT_DateLastReceived_Year,
-- DT_ExpirationDate,
-- DT_ExpirationDate_Day,
-- DT_ExpirationDate_Month,
-- DT_ExpirationDate_Year,
-- DT_CorporateIndividual,
-- DT_ABINumber,
-- DT_Company,
-- DT_LastName,
-- DT_FirstName,
-- DT_MiddleName,
-- DT_NameSuffix,
-- DT_Address,
-- DT_City,
-- DT_State,
-- DT_ZipCode,
-- DT_Zip4,
-- DT_DeliveryPointBarCode,
-- DT_DeliverabilityScore,
-- DT_CarrierRouteCode,
-- DT_USPSRecordType,
-- DT_MatchType,
-- DT_MatchScore,
-- DT_CollateralType1,
-- DT_CollateralType2,
-- DT_CollateralType3,
-- DT_CollateralType4,
-- DT_CollateralType5,
-- DT_CollateralType6,
-- DT_CollateralType7,
-- DT_CollateralType8,
-- DT_CollateralType9,
-- DT_CollateralType10,
-- DT_StateCode,
-- DT_CountyCode,
-- DT_CountyCode_Description,
-- --SECURED PARTY FIELDS
-- SP_ABINumber,
-- SP_LocationName,
-- SP_Address,
-- SP_City,
-- SP_State,
-- SP_Zip,
-- SP_ZIP4,

-- IG_Company,
-- IG_Location_Address,
-- IG_Location_City,
-- IG_Location_State,
-- IG_Location_Zip,
-- IG_Location_ZipFour,
-- IG_Location_CarrierRouteCode,
-- --IG_Mailing_Address,
-- IG_Mailing_City,
-- IG_Mailing_State,
-- IG_Mailing_StateCode,
-- IG_Mailing_Zip,
-- IG_Mailing_ZipFour,
-- IG_Mailing_CarrierRouteCode,
-- IG_CountyCode,
-- IG_CensusTract,
-- IG_CensusBlock,
-- fLATITUDE,
-- fLONGITUDE,
-- IG_MatchCode,
-- IG_PhoneNumber,
-- IG_FaxPhone,
-- IG_PrimarySIC6,
-- IG_SICCode1,
-- IG_SICCode2,
-- IG_SICCode3,
-- IG_SICCode4,
-- IG_NAICSCode,
-- IG_NumberEmployees,
-- IG_EmployeeSizeCode2,
-- IG_OutputVolume2,
-- IG_OutputVolumeCode2,
-- IG_CreditNumericScore,
-- IG_CreditAlphaScore,
-- IG_BusinessStatusCode,
-- IG_CallStatusCode,
-- IG_CottageCode,
-- Ig_OwnOrLease,
-- IG_ParentABINumber,
-- IG_SubsidairyABINumber,
-- IG_WebAddress,
-- IG_YearFirstAppeared,
-- IG_CBSACode,
-- IG_CBSALevel,
-- IG_CSACode,
-- FULFILLMENT_FLAG,
-- IG_SquareFootage8,
-- IG_PhoneNumberType,
-- IG_LegalName,
-- IG_Mailing_SCF,
-- AddressLine1,
-- City,
-- State,
-- Zip,
-- IG_Mailing_StateCountyName,
-- IG_Mailing_StateCity,
-- IG_Mailing_StateCityZip,
-- IG_Mailing_StateCountyCode,
-- IG_Mailing_StateCitySCF,
-- IGE_FullName,
-- IGE_TitleCode,
-- IGE_TitleCode_Back,
-- IGE_VendorEthnicity,
-- IGE_ContactID,
-- FirstName,
-- LastName,
-- Gender,
-- TitleCode,
-- BusinessEmailFlag,
-- DT_Filing_YYYYMM,
-- MATCHCODE_LRFS,
-- Has_IG_Mailing_Address,
-- IG_Mailing_Address,
-- Has_IGE_ContactName,
-- Has_IG_WebAddress,
-- Has_IG_PhoneNumber,
-- --IG_OutputVolumeCode2,
-- DT_statecountycode,
-- Has_DT_FullName,
-- DT_FullName,
-- DT_CollateralType_Comb,
-- DT_CollateralType_Multi,
-- --Fulfillment_Flag,
-- DT_AddressZip,
-- --IGE_TitleCode,
-- --dd values
-- dd1.cDescription AS DT_CorporateIndividual_Description,
-- dd2.cDescription AS DT_DeliverabilityScore_Description, 
-- dd3.cDescription AS DT_FilingState_Description,
-- dd4.cDescription AS DT_FilingStatus_Description,
-- dd5.cDescription AS DT_FilingTypeCode_Description,
-- dd6.cDescription AS DT_USPSRecordType_Description,
-- dd7.cDescription AS DT_MatchType_Description,
-- dd8.cDescription AS DT_CollateralType_Description, 
-- dd9.cDescription AS IGE_TitleCode_Description,
-- dd10.cDescription AS IG_Mailing_State_Description,
-- dd11.cDescription AS IG_MatchCode_Description,
-- dd12.cDescription AS IG_EmployeeSizeCode2_Description,
-- dd13.cDescription AS IG_OutputVolumeCode2_Description,
-- dd14.cDescription AS IG_BusinessStatusCode_Description, 
-- dd15.cDescription AS IG_CottageCode_Description,
-- dd16.cDescription AS IG_OwnOrLease_Description,
-- dd17.cDescription AS IG_Squarefootage8_Description,
-- dd18.cDescription AS Fulfillment_Flag_Description,
-- dd19.cDescription AS IG_CBSALevel_Description,
-- dd21.cDescription AS IGE_VendorEthnicity_Description,
-- dd22.cDescription AS IG_CreditAlphaScore_Description, 
-- dd23.cDescription AS IG_CallStatusCode_Description,
-- dd24.cDescription AS State_Description,

-- --c.IGE_VendorEthnicity_Description,
-- --c.IG_CreditAlphaScore_Description,
-- --c.IG_CallStatusCode_Description,
-- --c.State_Description,
-- d.SIC_Description as IG_PrimarySIC6_Description,
-- e.SIC_Description as IG_SICCode1_Description,
-- f.SIC_Description as IG_SICCode2_Description,
-- g.SIC_Description as IG_SICCode3_Description,
-- h.SIC_Description as IG_SICCode4_Description,
-- i.Descriptions as IG_NAICSCode_Description,
-- j.cDescription as IG_CountyCode_Description
-- from (
-- SELECT DISTINCT
-- A.MMDBKey MMDBKey,
-- A.PartyType DT_PartyType,
-- A.FilingState DT_FilingState,
-- A.IUSAkey IUSAKey,
-- A.OriginalFilingID DT_OriginalFilingID,
-- A.SourceFilingID DT_SourceFilingID,
-- A.FilingDate DT_Filing_Date,
-- right(A.FilingDate, 2) DT_Filing_Day,
-- right(left(A.FilingDate, 6), 2) DT_Filing_Month,
-- left(A.FilingDate, 4) DT_Filing_Year,
-- A.FilingStatus DT_FilingStatus,
-- A.FilingTypeCode DT_FilingTypeCode,
-- A.DateAdded DT_DateAdded,
-- right(A.DateAdded, 2) DT_DateAdded_Day,
-- right(left(A.DateAdded, 6), 2) DT_DateAdded_Month,
-- left(A.DateAdded, 4) DT_DateAdded_Year,
-- A.DateLastReceived DT_DateLastReceived,
-- right(A.DateLastReceived, 2) DT_DateLastReceived_Day,
-- right(left(A.DateLastReceived, 6), 2) DT_DateLastReceived_Month,
-- left(A.DateLastReceived, 4) DT_DateLastReceived_Year,
-- A.ExpirationDate DT_ExpirationDate,
-- right(A.ExpirationDate, 2) DT_ExpirationDate_Day,
-- right(left(A.ExpirationDate, 6), 2) DT_ExpirationDate_Month,
-- left(A.ExpirationDate, 4) DT_ExpirationDate_Year,
-- A.CorporateIndividual DT_CorporateIndividual,
-- A.Abinumber DT_ABINumber,
-- A.LocationName DT_Company,
-- A.LastName DT_LastName,
-- A.FirstName DT_FirstName,
-- A.MiddleName DT_MiddleName,
-- A.NameSuffix DT_NameSuffix,
-- A.Address DT_Address,
-- A.City DT_City,
-- A.State DT_State,
-- A.ZipCode DT_ZipCode,
-- A.ZipFour DT_Zip4,
-- A.DeliveryPointBarCode DT_DeliveryPointBarCode,
-- A.DeliverabilityScore DT_DeliverabilityScore,
-- A.CarrierRouteCode DT_CarrierRouteCode,
-- A.USPSRecordType DT_USPSRecordType,
-- A.MatchType DT_MatchType,
-- A.MatchScore DT_MatchScore,
-- A.CollateralType1 DT_CollateralType1,
-- A.CollateralType2 DT_CollateralType2,
-- A.CollateralType3 DT_CollateralType3,
-- A.CollateralType4 DT_CollateralType4,
-- A.CollateralType5 DT_CollateralType5,
-- A.CollateralType6 DT_CollateralType6,
-- A.CollateralType7 DT_CollateralType7,
-- A.CollateralType8 DT_CollateralType8,
-- A.CollateralType9 DT_CollateralType9,
-- A.CollateralType10 DT_CollateralType10,
-- A.StateCode DT_StateCode,
-- A.CountyCode DT_CountyCode,
-- A.CountyDescription DT_CountyCode_Description,
-- --SECURED PARTY FIELDS
-- B.abinumber SP_ABINumber,
-- B.locationname SP_LocationName,
-- B.address SP_Address,
-- B.city SP_City,
-- B.state SP_State,
-- B.zipcode SP_Zip,
-- B.zipfour SP_ZIP4,

-- --update with 992 data
-- c.Company IG_Company,
-- c.ADDRESS IG_Location_Address,
-- c.CITY IG_Location_City,
-- c.STATE IG_Location_State,
-- c.ZIP IG_Location_Zip,
-- c.ZIPFOUR IG_Location_ZipFour,
-- c.CARRIERROUTECODE IG_Location_CarrierRouteCode,
-- c.Mailing_ADDRESS IG_Mailing_Address,
-- c.Mailing_CITY IG_Mailing_City,
-- c.Mailing_STATE IG_Mailing_State,
-- c.Mailing_StateCode IG_Mailing_StateCode,
-- c.Mailing_ZIPCode IG_Mailing_Zip,
-- c.Mailing_ZIPFOUR IG_Mailing_ZipFour,
-- c.MAILING_CARRIEROUTECODE IG_Mailing_CarrierRouteCode,
-- c.COUNTYCODE IG_CountyCode,
-- c.CENSUSTRACT IG_CensusTract,
-- c.CENSUSBLOCK IG_CensusBlock,
-- --c.fLATITUDE fLATITUDE,
-- CAST(c.fLATITUDE as FLOAT) as fLATITUDE,
-- --c.fLONGITUDE fLONGITUDE,
-- CAST(c.fLONGITUDE as VARCHAR(11)) as fLONGITUDE,
-- c.MATCHCODE IG_MatchCode,
-- c.PHONENUMBER IG_PhoneNumber,
-- c.FAXPHONE IG_FaxPhone,
-- c.PRIMARYSIC6 IG_PrimarySIC6,
-- c.SICCODE1 IG_SICCode1,
-- c.SICCODE2 IG_SICCode2,
-- c.SICCODE3 IG_SICCode3,
-- c.SICCODE4 IG_SICCode4,
-- c.NAICSCODE IG_NAICSCode,
-- --c.NUMBEREMPLOYEES IG_NumberEmployees,
-- cast(c.NUMBEREMPLOYEES as varchar(20)) IG_NumberEmployees,
-- c.EMPLOYEESIZECODE2 IG_EmployeeSizeCode2,
-- c.OUTPUTVOLUME2 IG_OutputVolume2,--Inferred_Corporate_Sales_Volume_Amount,--c.CORPORATEOUTPUTVOLUME,
-- --c.OUTPUTVOLUMECODE2 IG_OutputVolumeCode2,
-- c.CREDITNUMERICSCORE IG_CreditNumericScore,
-- c.CREDITALPHASCORE IG_CreditAlphaScore,
-- c.BUSINESSSTATUSCODE IG_BusinessStatusCode,
-- c.CALLSTATUSCODE IG_CallStatusCode,
-- c.COTTAGECODE IG_CottageCode,
-- c.OWNORLEASE Ig_OwnOrLease,
-- c.PARENTABINUMBER IG_ParentABINumber,
-- c.SUBSIDAIRYABINUMBER IG_SubsidairyABINumber,
-- c.WEBADDRESS IG_WebAddress,
-- c.YEARFIRSTAPPEARED IG_YearFirstAppeared,
-- c.CBSACODE IG_CBSACode,
-- c.CBSALEVEL IG_CBSALevel,
-- c.CSACODE IG_CSACode,
-- --c.FULFILLMENTFLAG FULFILLMENT_FLAG,
-- c.SQUAREFOOTAGE8 IG_SquareFootage8,
-- c.PHONE_NUMBER_TYPE IG_PhoneNumberType,
-- c.LEGAL_NAME IG_LegalName,
-- c.SCF IG_Mailing_SCF,--addhere
-- c.Mailing_Address AddressLine1,
-- c.Mailing_City City,
-- c.Mailing_State State,
-- c.Mailing_Zipcode Zip,
-- c.StateCountyName IG_Mailing_StateCountyName,
-- c.CityByState IG_Mailing_StateCity,
-- c.StateCityZip IG_Mailing_StateCityZip,
-- c.StateCountyCode IG_Mailing_StateCountyCode,
-- c.StateCitySCF IG_Mailing_StateCitySCF,
-- case when c.typecode='C' then c.fullname else '' end  as IGE_FullName,
-- case when c.typecode='C' then c.TitleCode else '' end  as IGE_TitleCode,
-- case when c.typecode='C' then c.titlecode_Back else '' end  as IGE_TitleCode_Back,
-- case when c.typecode='C' then c.VENDOR_ETHNICITY else '' end  as IGE_VendorEthnicity,
-- case when c.typecode='C' then c.contactid else '' end  as IGE_ContactID,
-- case when c.typecode='C' then c.FirstName else '' end  as FirstName,
-- case when c.typecode='C' then c.LastName else '' end  as LastName,
-- case when c.typecode='C' then c.Gender else '' end  as Gender,
-- CASE WHEN c.titlecode = '!'  THEN 'Z1'
--      WHEN c.TitleCode = '#'  THEN 'Z2'
--      WHEN c.TitleCode = '$'  THEN 'Z3'
--      WHEN c.TitleCode = '%'  THEN 'Z4'
--      WHEN c.TitleCode = '&'  THEN 'Z5'
--      WHEN c.TitleCode = '('  THEN 'Z6'
--      WHEN c.TitleCode = ')'  THEN 'Z7'
--      WHEN c.TitleCode = '+'  THEN 'Z8'
--      WHEN c.TitleCode = '-'  THEN 'Z9'
--      WHEN c.TitleCode = '.'  THEN 'Z10'
--      WHEN c.TitleCode = '/'  THEN 'Z11'
--      WHEN c.TitleCode = ':'  THEN 'Z12'
--      WHEN c.TitleCode = '='  THEN 'Z13'
--      WHEN c.TitleCode = '>'  THEN 'Z14'
--      WHEN c.TitleCode = '?'  THEN 'Z15'
--      WHEN c.TitleCode = '@'  THEN 'Z16'
--      WHEN c.TitleCode = '['  THEN 'Z17'
--      WHEN c.TitleCode = '\\'  THEN 'Z18'
--      WHEN c.TitleCode = ']'  THEN 'Z19'
--      WHEN c.TitleCode = '^'  THEN 'Z20'
--      WHEN c.TitleCode = '_'  THEN 'Z21'
--      WHEN c.TitleCode = '{{'  THEN 'Z22'
--      ELSE c.TitleCode end as TitleCode,
-- d.BusinessEmailFlag as BusinessEmailFlag,
-- --e.BusinessEmailFlag as BusinessEmailFlag
-- left(A.FilingDate, 4) + right(left(A.FilingDate, 6), 2) as DT_Filing_YYYYMM,
-- A.ABINumber+A.SourceFilingID as MATCHCODE_LRFS,
-- CASE WHEN RTRIM(c.Mailing_ADDRESS) = '' THEN 'N' ELSE 'Y' end as Has_IG_Mailing_Address,
-- CASE WHEN RTRIM(c.fullname) = '' THEN 'N' ELSE 'Y' end as Has_IGE_ContactName,
-- CASE WHEN RTRIM(c.WEBADDRESS) = '' THEN 'N' ELSE 'Y' end as Has_IG_WebAddress,
-- CASE WHEN (ISNULL(c.PHONENUMBER,'') ='' AND LTRIM(RTRIM(c.FAXPHONE)) = '') THEN 'N' ELSE 'Y' end as Has_IG_PhoneNumber,
-- CASE WHEN  (c.OUTPUTVOLUMECODE2 IS NULL OR RTRIM(c.OUTPUTVOLUMECODE2) = '') THEN 'Z' ELSE c.OUTPUTVOLUMECODE2 end as IG_OutputVolumeCode2,
-- A.State + A.CountyCode as DT_statecountycode,
-- CASE WHEN LTRIM(RTRIM(a.FirstName+a.LastName))='' THEN 'N' ELSE 'Y' end as Has_DT_FullName,
-- LTRIM(RTRIM(a.FirstName)) + ' ' + LTRIM(RTRIM(a.LastName)) as DT_FullName,
-- (a.CollateralType1 +a.CollateralType2 +a.CollateralType3 + a.CollateralType4 +a.CollateralType5 +a.CollateralType6+ a.CollateralType7 +a.CollateralType8 +a.CollateralType9 + a.CollateralType10) as DT_CollateralType_Comb,
-- (',' + a.CollateralType1 + ',' + a.CollateralType2 + ',' + a.CollateralType3 +',' + a.CollateralType4 + ',' + a.CollateralType5 + ',' + a.CollateralType6 +',' + a.CollateralType7 + ',' + a.CollateralType8 + ',' + a.CollateralType9 +',' + a.CollateralType10 + ',') as DT_CollateralType_Multi,
-- CASE WHEN c.FULFILLMENTFLAG='' THEN 'U' ELSE c.FULFILLMENTFLAG end as Fulfillment_Flag,
-- a.Address+ a.ZipCode as DT_AddressZip
-- --LTRIM(RTRIM(c.TitleCode)) as IGE_TitleCode
-- FROM {tablename1} a 
-- inner JOIN {tablename2} b on a.mmdbkey = b.mmdbkey
-- --join with ig-business-table 992
-- LEFT JOIN tblMain_23102_203208 c on A.ABINumber=c.ABINumber 
-- --join with business mail table
-- LEFT JOIN (select DISTINCT 'Y' as BusinessEmailFlag, ABI_Number_LRFS, LEFT(Company_Name_LRFS, 40) AS Company_Name_LRFS,FullName from business_email_table WHERE LTRIM(RTRIM(Email_Address_LRFS)) <>'') d
-- on A.ABINumber =d.ABI_Number_LRFS  AND (A.LocationName =d.Company_Name_LRFS or ((case when c.typecode='C' then c.fullname else '' end) =d.FullName) ) and (d.BusinessEmailFlag IS null OR d.BusinessEmailFlag <>'Y')
-- --
-- ) a
-- LEFT join DDValues1 DD1  ON A.DT_CorporateIndividual = DD1.cValue AND upper(DD1.cFieldname) ='DT_CORPORATEINDIVIDUAL'
-- LEFT join DDValues1 DD2  ON A.DT_DeliverabilityScore = DD2.cValue AND upper(DD2.cFieldname) ='DT_DELIVERABILITYSCORE'
-- LEFT join DDValues1 DD3  ON A.DT_FilingState = DD3.cValue AND upper(DD3.cFieldname) ='DT_FILINGSTATE'
-- LEFT join DDValues1 DD4  ON A.DT_FilingStatus= DD4.cValue AND upper(DD4.cFieldname) ='DT_FILINGSTATUS'
-- LEFT join DDValues1 DD5  ON A.DT_FilingTypeCode= DD5.cValue AND upper(DD5.cFieldname) ='DT_FILINGTYPECODE'
-- LEFT join DDValues1 DD6  ON A.DT_USPSRecordType= DD6.cValue AND upper(DD6.cFieldname) ='DT_USPSRECORDTYPE'
-- LEFT join DDValues1 DD7  ON A.DT_MatchType = DD7.cValue AND upper(DD7.cFieldname) ='DT_MATCHTYPE'
-- LEFT join DDValues1 DD8  ON A.DT_CollateralType1 = DD8.cValue AND upper(DD8.cFieldname) ='DT_COLLATERALTYPE'
-- LEFT join DDValues1 DD9  ON A.IGE_TitleCode = DD9.cValue AND upper(DD9.cFieldname) ='IGE_TITLECODE'
-- LEFT join DDValues1 DD10 ON A.IG_Mailing_State= DD10.cValue AND upper(DD10.cFieldname) ='IG_MAILING_STATE'
-- LEFT join DDValues1 DD11 ON A.IG_MatchCode= DD11.cValue AND upper(DD11.cFieldname) ='IG_MATCHCODE'
-- LEFT join DDValues1 DD12 ON A.IG_EmployeeSizeCode2= DD12.cValue AND upper(DD12.cFieldname) ='IG_EMPLOYEESIZECODE2'
-- LEFT join DDValues1 DD13 ON A.IG_OutputVolumeCode2 = DD13.cValue AND upper(DD13.cFieldname) ='IG_OUTPUTVOLUMECODE2'
-- LEFT join DDValues1 DD14 ON A.IG_BusinessStatusCode = DD14.cValue AND upper(DD14.cFieldname) ='IG_BUSINESSSTATUSCODE'
-- LEFT join DDValues1 DD15 ON A.IG_CottageCode= DD15.cValue AND upper(DD15.cFieldname) ='IG_COTTAGECODE'
-- LEFT join DDValues1 DD16 ON A.IG_OwnOrLease= DD16.cValue AND upper(DD16.cFieldname) ='IG_OWNORLEASE'
-- LEFT join DDValues1 DD17 ON A.IG_Squarefootage8= DD17.cValue AND upper(DD17.cFieldname) ='IG_SQUAREFOOTAGE8'
-- LEFT join DDValues1 DD18 ON A.Fulfillment_Flag= DD18.cValue AND upper(DD18.cFieldname) ='FULFILLMENT_FLAG'
-- LEFT join DDValues1 DD19 ON A.IG_CBSALevel= DD19.cValue AND upper(DD19.cFieldname) ='IG_CBSALEVEL'
-- left join DDValues2 DD21  ON A.IGE_VendorEthnicity = DD21.cValue AND LTRIM(RTRIM(UPPER(DD21.cFieldname))) ='ETHINICITY'
-- LEFT join DDValues2 DD22  ON A.IG_CreditAlphaScore = DD22.cValue AND LTRIM(RTRIM(UPPER(DD22.cFieldname))) ='BUSINESSCREDITSCORE'
-- LEFT join DDValues2 DD23  ON A.IG_CallStatusCode = DD23.cValue AND LTRIM(RTRIM(UPPER(DD23.cFieldname))) ='PHONECALLSTATUS'
-- LEFT join DDValues2 DD24  ON A.State= DD24.cValue AND LTRIM(RTRIM(UPPER(DD24.cFieldname))) ='STATE_2CHAR'
-- LEFT JOIN SIC_Code_6Digits_Descriptions d on a.IG_PrimarySIC6=d.SIC_Code
-- LEFT JOIN SIC_Code_6Digits_Descriptions e on a.IG_SICCode1=e.SIC_Code
-- LEFT JOIN SIC_Code_6Digits_Descriptions f on a.IG_SICCode2=f.SIC_Code
-- LEFT JOIN SIC_Code_6Digits_Descriptions g on a.IG_SICCode3=g.SIC_Code
-- LEFT JOIN SIC_Code_6Digits_Descriptions h on a.IG_SICCode4=h.SIC_Code
-- LEFT JOIN EXCLUDE_NAICS8_Descriptions i on a.IG_NAICSCode=i.NAICS8
-- LEFT JOIN CountyState_Decode j on a.IG_Mailing_StateCountyCode=j.cCode;