DROP TABLE IF EXISTS {table-businessemail-new-raw};

CREATE TABLE {table-businessemail-new-raw}
(
  abi_number_lrfs VARCHAR(9),
  company_name_lrfs VARCHAR(30),
  addressline1 VARCHAR(40),
  city VARCHAR(28),
  state VARCHAR(2),
  zip VARCHAR(6),
  firstname VARCHAR(15),
  lastname VARCHAR(20),
  title_lrfs VARCHAR(3),
  gender_lrfs VARCHAR(1),
  email_address_lrfs VARCHAR(60) not null distkey,
  primary_sic_code_lrfs VARCHAR(6),
  area_code_lrfs VARCHAR(3),
  phone_number_lrfs VARCHAR(7),
  literaltitle_id VARCHAR(8),
  title_description_lrfs VARCHAR(256),
  unique_id_lrfs VARCHAR(10),--NIKEN
  vendor_id_lrfs VARCHAR(2),
  executive_source_code_lrfs VARCHAR(2),
  bvt_email_status_lrfs VARCHAR(1),
  suppression_type VARCHAR(1),
  responder_date VARCHAR(6),
  scf_lrfs VARCHAR(3),
  a4_digit_primary_sic_lrfs VARCHAR(4),
  a4_digit_secondary_sic_lrfs VARCHAR(4),
  employee_size_code_lrfs VARCHAR(1),
  sales_volume_code_lrfs VARCHAR(1),
  business_status_code_lrfs VARCHAR(1),
  secondary_sic_code_lrfs VARCHAR(6),
  franchise_code_lrfs VARCHAR(6),
  cbsa_lrfs VARCHAR(5),
  ad_size_lrfs VARCHAR(1),
  business_credit_score_code_lrfs VARCHAR(2),
  business_credit_score_lrfs VARCHAR(3),
  call_status_lrfs VARCHAR(1),
  growing_shrinking_indicator_lrfs VARCHAR(1),
  ultimate_number_lrfs VARCHAR(9),
  fax_number_lrfs VARCHAR(10),
  individual_firm_lrfs VARCHAR(1),
  multi_tenant_code_lrfs VARCHAR(1),
  multi_tenant_building_number_lrfs VARCHAR(7),
  number_of_pc_lrfs VARCHAR(1),
  office_size_lrfs VARCHAR(1),
  own_lease_lrfs VARCHAR(1),
  population_code_lrfs VARCHAR(1),
  public_private_code_lrfs VARCHAR(1),
  government_segment_code_lrfs VARCHAR(1),
  square_footage_lrfs VARCHAR(1),
  teleresearch_date_lrfs VARCHAR(6),
  transaction_date_lrfs VARCHAR(6),
  transaction_type_lrfs VARCHAR(1),
  website_lrfs VARCHAR(40),
  year_first_appeared_lrfs VARCHAR(4),
  year_sic_added_lrfs VARCHAR(6),
  zip_end_lrfs VARCHAR(1),
  carrier_route_lrfs VARCHAR(4),
  census_lrfs VARCHAR(6),
  state_code_lrfs VARCHAR(2),
  county_code_lrfs VARCHAR(3),
  csa_lrfs VARCHAR(3),
  zip4_lrfs VARCHAR(4),
  secondary_sic2_lrfs VARCHAR(6),
  secondary_sic3_lrfs VARCHAR(6),
  secondary_sic4_lrfs VARCHAR(6),
  md5upper_lrfs VARCHAR(32),
  md5lower_lrfs VARCHAR(32),
  one_per__abi_lrfs VARCHAR(1),
  seq_lrfs VARCHAR(9),
  title_rank_lrfs VARCHAR(2),
  professional_title_code VARCHAR(3),
  department_code VARCHAR(4),
  job_level_code VARCHAR(4),
  mail_score VARCHAR(2),
  md5saltedhash VARCHAR(32),
  latitude VARCHAR(11),
  longitude VARCHAR(11),
  geo_match_level VARCHAR(1),
  database_flag VARCHAR(1),
  work_at_home_indicator VARCHAR(1),
  sitenumber VARCHAR(9),
  contactid VARCHAR(12),--NIKEN
  sha256lower VARCHAR(64),--KRISHNA
  sha256upper VARCHAR(64),--KRISHNA
  phone_number_type VARCHAR(1),--KRISHNA
  digitalmatch VARCHAR(1),--NAIMEEL
  functional_area_code VARCHAR(4),--NAIMEEL
  literal_title_department_code VARCHAR(2),--NAIMEEL
  role_code VARCHAR(4),--NAIMEEL
  level_code VARCHAR(1),--NAIMEEL
  contactquality VARCHAR(1),--NAIMEEL
  bridge_code VARCHAR(1),
  domain_id VARCHAR(1),   
  topleveldomain VARCHAR(6),
  email_deliverable VARCHAR(1), 
  email_marketable VARCHAR(1),
  email_reputation_risk VARCHAR(1),
  cbsatype VARCHAR(5),
  censusblock VARCHAR(1),
  inferred_corporate_employee_count VARCHAR(6),
  inferred_corporate_employee_range VARCHAR(1),
  inferred_corporate_employee_source_indicator VARCHAR(1),
  inferred_corporate_sales_volume_amount VARCHAR(9),
  inferred_corporate_sales_volume_range VARCHAR(1),
  inferred_corporate_sales_volume_source_indicator VARCHAR(1),
  naicscode VARCHAR(8),
  numberemployees VARCHAR(5),
  outputvolume2 VARCHAR(9),
  subsidairyabinumber VARCHAR(9),
  yearestablished VARCHAR(4),
  creditcardsaccepted_1 VARCHAR(1),
  creditcardsaccepted_2 VARCHAR(1),
  creditcardsaccepted_3 VARCHAR(1),
  creditcardsaccepted_4 VARCHAR(1),
  creditcardsaccepted_5 VARCHAR(1),
  creditcardsaccepted_6 VARCHAR(1),
  creditcardsaccepted_7 VARCHAR(1),
  creditcardsaccepted_8 VARCHAR(1),
  creditcardsaccepted_9 VARCHAR(1),
  creditcardsaccepted_10 VARCHAR(1),
  creditcardsaccepted_11 VARCHAR(1),
  creditcardsaccepted_12 VARCHAR(1),
  creditcardsaccepted_13 VARCHAR(1),
  creditcardsaccepted_14 VARCHAR(1),
  creditcardsaccepted_15 VARCHAR(1),
  addresstype VARCHAR(2),
  femaleexecflag VARCHAR(1),
  truefranchiseflag VARCHAR(1),
  industryspecificfirstbyte VARCHAR(1),
  wealthcode VARCHAR(1),
  bigbusinesssegmentationcode VARCHAR(1),
  smmedbusseg1 VARCHAR(1),
  smmedbusseg2 VARCHAR(1),
  fortuneranking VARCHAR(4),
  hightechbusinessflag VARCHAR(1),
  filingflag VARCHAR(1),
  whitecollar VARCHAR(4),
  whitecollarflag VARCHAR(1),
  primary_mail_confidence VARCHAR(1),
  secondary_mail_confidence VARCHAR(1),
  foreignparentflag VARCHAR(1),
  importexportflag VARCHAR(1),
  highincomeexecflag VARCHAR(1),
  greenadopterscore VARCHAR(1),
  telecommunications_expense VARCHAR(1),
  technology_expense VARCHAR(1),
  office_equipment_expense VARCHAR(1),
  payroll_expense VARCHAR(1),
  rent_leasing_expense VARCHAR(1),
  advertising_expense VARCHAR(1),
  utilities_expense VARCHAR(1),
  accounting_expense VARCHAR(1),
  packagecontainer_expense VARCHAR(1),
  contract_labor_expense VARCHAR(1),
  insurance_expense VARCHAR(1),
  purchased_print_expense VARCHAR(1),
  purchase_mgmtadmin_svc_expense VARCHAR(1),
  legal_expense VARCHAR(1),
  charitable_dontations_expense VARCHAR(1),
  license_fees_taxes VARCHAR(1),
  maintenance_repair VARCHAR(1),
  transportationexpensecode VARCHAR(1),
  franchise_code_1 VARCHAR(3),
  franchise_code_2 VARCHAR(3),
  franchise_code_3 VARCHAR(3),
  franchise_code_4 VARCHAR(3),
  franchise_code_5 VARCHAR(3),
  franchise_code_6 VARCHAR(3),
  fleetsize VARCHAR(1),
  legal_name VARCHAR(120),
  last_modified_date VARCHAR(6),
  vendor_ethnicity VARCHAR(2),
  vendor_ethnic_group VARCHAR(1),
  vendor_language VARCHAR(2),
  vendor_religion VARCHAR(1),
  individual_mc_wb VARCHAR(17),
  company_mc_wb VARCHAR(15),
  email_deployable VARCHAR(1),
  id INT IDENTITY UNIQUE,
  city_available VARCHAR(1),
  fullname VARCHAR(50),
  company VARCHAR(50),
  a2_digit_primary_sic_lrfs VARCHAR(2),
  one_per_abi_lrfs VARCHAR(14),
  domain_name_lrfs VARCHAR(80),
  one_per_abiname_lrfs VARCHAR(129),
  one_per_abi_email_lrfs VARCHAR(69),
  name_available_lrfs VARCHAR(1),
  company_available_lrfs VARCHAR(1),
  abi_available_lrfs VARCHAR(1),
  phone_number_available_lrfs VARCHAR(1),
  royalty_emails_lrfs VARCHAR(1),
  infogroup_emails_lrfs VARCHAR(1),
  a10_digit_phone_lrfs VARCHAR(10),
  state_with_county_code_lrfs VARCHAR(5),
  one_per_contact_name_lrfs VARCHAR(55),
  contacts_per_company_lrfs VARCHAR(80),
  one_per_company_lrfs VARCHAR(30),
  permissiontype VARCHAR(1),
  gender VARCHAR(1),
  listtype VARCHAR(1),
  productcode VARCHAR(1),
  cinclude1 VARCHAR(1),
  bademails VARCHAR(1),
  website_available VARCHAR(1),
  one_per_company_name_title VARCHAR(33),
  job_level_code_multi VARCHAR(9),
  department_code_multi VARCHAR(9),
  oneperflag VARCHAR(1),
  cinclude VARCHAR(1),
  cdomain VARCHAR(50),
  blank_titles VARCHAR(1),
  naicscode6 VARCHAR(6),
  naicscode4 VARCHAR(4),
  naicscode2 VARCHAR(2),
  faxavailable_flag VARCHAR(1),
  creditcardsaccepted VARCHAR(15),
  creditcardsaccepted_multi VARCHAR(50),
  zip9 VARCHAR(9),
  literal_title_available VARCHAR(1),
  flatitude FLOAT,
  flongitude FLOAT,
  cbsalevel VARCHAR(1),
  combined_franchise_code VARCHAR(30),
  individual_mc VARCHAR(17),
  company_mc VARCHAR(15),
  listid INT
);

COPY {table-businessemail-new-raw}
FROM 's3://{s3-internal}{s3-2722internal-path}{s3-businessemail}'
IAM_ROLE '{iam}'
GZIP
IGNOREBLANKLINES
FIXEDWIDTH
'abi_number_lrfs:9,
company_name_lrfs:30,
addressline1:40,
city:28,
state:2,
zip:6,
firstname:15,
lastname:20,
title_lrfs:2,
gender_lrfs:1,
email_address_lrfs:60,
primary_sic_code_lrfs:6,
area_code_lrfs:3,
phone_number_lrfs:7,
literaltitle_id:8,
title_description_lrfs:256,
unique_id_lrfs:10,
vendor_id_lrfs:2,
executive_source_code_lrfs:2,
bvt_email_status_lrfs:1,
suppression_type:1,
responder_date:6,
scf_lrfs:3,
a4_digit_primary_sic_lrfs:4,
a4_digit_secondary_sic_lrfs:4,
employee_size_code_lrfs:1,
sales_volume_code_lrfs:1,
business_status_code_lrfs:1,
secondary_sic_code_lrfs:6,
franchise_code_lrfs:6,
cbsa_lrfs:5,
ad_size_lrfs:1,
business_credit_score_code_lrfs:2,
business_credit_score_lrfs:3,
call_status_lrfs:1,
growing_shrinking_indicator_lrfs:1,
ultimate_number_lrfs:9,
fax_number_lrfs:10,
individual_firm_lrfs:1,
multi_tenant_code_lrfs:1,
multi_tenant_building_number_lrfs:7,
number_of_pc_lrfs:1,
office_size_lrfs:1,
own_lease_lrfs:1,
population_code_lrfs:1,
public_private_code_lrfs:1,
government_segment_code_lrfs:1,
square_footage_lrfs:1,
teleresearch_date_lrfs:6,
transaction_date_lrfs:6,
transaction_type_lrfs:1,
website_lrfs:40,
year_first_appeared_lrfs:4,
year_sic_added_lrfs:6,
zip_end_lrfs:1,
carrier_route_lrfs:4,
census_lrfs:6,
state_code_lrfs:2,
county_code_lrfs:3,
csa_lrfs:3,
zip4_lrfs:4,
secondary_sic2_lrfs:6,
secondary_sic3_lrfs:6,
secondary_sic4_lrfs:6,
md5upper_lrfs:32,
md5lower_lrfs:32,
one_per__abi_lrfs:1,
seq_lrfs:9,
title_rank_lrfs:2,
professional_title_code:3,
department_code:4,
job_level_code:4,
mail_score:2,
md5saltedhash:32,
latitude:11,
longitude:11,
geo_match_level:1,
database_flag:1,
work_at_home_indicator:1,
sitenumber:9,
contactid:12,
sha256lower:64,
sha256upper:64,
phone_number_type:1,
digitalmatch:1,
functional_area_code:4,
literal_title_department_code:2,
role_code:4,
level_code:1,
contactquality:1,
bridge_code:1,
domain_id":1,"
topleveldomain:6,
email_deliverable":1,"
email_marketable:1,
email_reputation_risk:1,
cbsatype:5,
censusblock:1,
inferred_corporate_employee_count:6,
inferred_corporate_employee_range:1,
inferred_corporate_employee_source_indicator:1,
inferred_corporate_sales_volume_amount:9,
inferred_corporate_sales_volume_range:1,
inferred_corporate_sales_volume_source_indicator:1,
naicscode:8,
numberemployees:5,
outputvolume2:9,
subsidairyabinumber:9,
yearestablished:4,
creditcardsaccepted_1:1,
creditcardsaccepted_2:1,
creditcardsaccepted_3:1,
creditcardsaccepted_4:1,
creditcardsaccepted_5:1,
creditcardsaccepted_6:1,
creditcardsaccepted_7:1,
creditcardsaccepted_8:1,
creditcardsaccepted_9:1,
creditcardsaccepted_10:1,
creditcardsaccepted_11:1,
creditcardsaccepted_12:1,
creditcardsaccepted_13:1,
creditcardsaccepted_14:1,
creditcardsaccepted_15:1,
addresstype:2,
femaleexecflag:1,
truefranchiseflag:1,
industryspecificfirstbyte:1,
wealthcode:1,
bigbusinesssegmentationcode:1,
smmedbusseg1:1,
smmedbusseg2:1,
fortuneranking:4,
hightechbusinessflag:1,
filingflag:1,
whitecollar:4,
whitecollarflag:1,
primary_mail_confidence:1,
secondary_mail_confidence:1,
foreignparentflag:1,
importexportflag:1,
highincomeexecflag:1,
greenadopterscore:1,
telecommunications_expense:1,
technology_expense:1,
office_equipment_expense:1,
payroll_expense:1,
rent_leasing_expense:1,
advertising_expense:1,
utilities_expense:1,
accounting_expense:1,
packagecontainer_expense:1,
contract_labor_expense:1,
insurance_expense:1,
purchased_print_expense:1,
purchase_mgmtadmin_svc_expense:1,
legal_expense:1,
charitable_dontations_expense:1,
license_fees_taxes:1,
maintenance_repair:1,
transportationexpensecode:1,
franchise_code_1:3,
franchise_code_2:3,
franchise_code_3:3,
franchise_code_4:3,
franchise_code_5:3,
franchise_code_6:3,
fleetsize:1,
legal_name:120,
last_modified_date:6,
vendor_ethnicity:2,
vendor_ethnic_group:1,
vendor_language:2,
vendor_religion:1,
individual_mc_wb:17,
company_mc_wb:15,
email_deployable:1'
;