DROP TABLE IF EXISTS {table-businessemail-new};

CREATE TABLE {table-businessemail-new}
(
  abi_number_lrfs VARCHAR(9)  ENCODE zstd,
  company_name_lrfs VARCHAR(30)  ENCODE zstd,
  addressline1 VARCHAR(40)  ENCODE zstd,
  city VARCHAR(28)  ENCODE zstd,
  state VARCHAR(2)  ENCODE zstd,
  zip VARCHAR(6)  ENCODE zstd,
  firstname VARCHAR(15)  ENCODE zstd,
  lastname VARCHAR(20)  ENCODE zstd,
  title_lrfs VARCHAR(3)  ENCODE bytedict,
  gender_lrfs VARCHAR(1)  ENCODE zstd,
  email_address_lrfs VARCHAR(60)  not null distkey ENCODE zstd,
  primary_sic_code_lrfs VARCHAR(6)  ENCODE zstd,
  area_code_lrfs VARCHAR(3)  ENCODE zstd,
  phone_number_lrfs VARCHAR(7)  ENCODE zstd,
  literaltitle_id VARCHAR(8)  ENCODE zstd,
  title_description_lrfs VARCHAR(256)  ENCODE zstd,
  unique_id_lrfs VARCHAR(10)  ENCODE zstd,--NIKEN
  vendor_id_lrfs VARCHAR(2)  ENCODE zstd,
  executive_source_code_lrfs VARCHAR(2)  ENCODE zstd,
  bvt_email_status_lrfs VARCHAR(1)  ENCODE zstd,
  suppression_type VARCHAR(1)  ENCODE zstd,
  responder_date VARCHAR(6)  ENCODE zstd,
  scf_lrfs VARCHAR(3)  ENCODE zstd,
  a4_digit_primary_sic_lrfs VARCHAR(4)  ENCODE zstd,
  a4_digit_secondary_sic_lrfs VARCHAR(4)  ENCODE zstd,
  employee_size_code_lrfs VARCHAR(1)  ENCODE zstd,
  sales_volume_code_lrfs VARCHAR(1)  ENCODE zstd,
  business_status_code_lrfs VARCHAR(1)  ENCODE zstd,
  secondary_sic_code_lrfs VARCHAR(6)  ENCODE zstd,
  franchise_code_lrfs VARCHAR(6)  ENCODE zstd,
  cbsa_lrfs VARCHAR(5)  ENCODE zstd,
  ad_size_lrfs VARCHAR(1)  ENCODE zstd,
  business_credit_score_code_lrfs VARCHAR(2)  ENCODE zstd,
  business_credit_score_lrfs VARCHAR(3)  ENCODE zstd,
  call_status_lrfs VARCHAR(1)  ENCODE zstd,
  growing_shrinking_indicator_lrfs VARCHAR(1)  ENCODE zstd,
  ultimate_number_lrfs VARCHAR(9)  ENCODE zstd,
  fax_number_lrfs VARCHAR(10)  ENCODE zstd,
  individual_firm_lrfs VARCHAR(1)  ENCODE zstd,
  multi_tenant_code_lrfs VARCHAR(1)  ENCODE zstd,
  multi_tenant_building_number_lrfs VARCHAR(7)  ENCODE zstd,
  number_of_pc_lrfs VARCHAR(1)  ENCODE zstd,
  office_size_lrfs VARCHAR(1)  ENCODE zstd,
  own_lease_lrfs VARCHAR(1)  ENCODE zstd,
  population_code_lrfs VARCHAR(1)  ENCODE zstd,
  public_private_code_lrfs VARCHAR(1)  ENCODE zstd,
  government_segment_code_lrfs VARCHAR(1)  ENCODE zstd,
  square_footage_lrfs VARCHAR(1)  ENCODE zstd,
  teleresearch_date_lrfs VARCHAR(6)  ENCODE bytedict,
  transaction_date_lrfs VARCHAR(6)  ENCODE zstd,
  transaction_type_lrfs VARCHAR(1)  ENCODE zstd,
  website_lrfs VARCHAR(40)  ENCODE zstd,
  year_first_appeared_lrfs VARCHAR(4)  ENCODE zstd,
  year_sic_added_lrfs VARCHAR(6)  ENCODE zstd,
  zip_end_lrfs VARCHAR(1)  ENCODE zstd,
  carrier_route_lrfs VARCHAR(4)  ENCODE zstd,
  census_lrfs VARCHAR(6)  ENCODE zstd,
  state_code_lrfs VARCHAR(2)  ENCODE zstd,
  county_code_lrfs VARCHAR(3)  ENCODE zstd,
  csa_lrfs VARCHAR(3)  ENCODE zstd,
  zip4_lrfs VARCHAR(4)  ENCODE zstd,
  secondary_sic2_lrfs VARCHAR(6)  ENCODE zstd,
  secondary_sic3_lrfs VARCHAR(6)  ENCODE zstd,
  secondary_sic4_lrfs VARCHAR(6)  ENCODE zstd,
  md5upper_lrfs VARCHAR(32)  ENCODE zstd,
  md5lower_lrfs VARCHAR(32)  ENCODE zstd,
  one_per__abi_lrfs VARCHAR(1)  ENCODE zstd,
  seq_lrfs VARCHAR(9)  ENCODE zstd,
  title_rank_lrfs VARCHAR(2)  ENCODE zstd,
  professional_title_code VARCHAR(3)  ENCODE zstd,
  department_code VARCHAR(4)  ENCODE zstd,
  job_level_code VARCHAR(4)  ENCODE zstd,
  mail_score VARCHAR(2)  ENCODE zstd,
  city_available VARCHAR(1)  ENCODE zstd,
  fullname VARCHAR(50)  ENCODE zstd,
  company VARCHAR(50)  ENCODE zstd,
  a2_digit_primary_sic_lrfs VARCHAR(2)  ENCODE zstd,
  one_per_abi_lrfs VARCHAR(14)  ENCODE zstd,
  domain_name_lrfs VARCHAR(80)  ENCODE zstd,
  one_per_abiname_lrfs VARCHAR(129)  ENCODE zstd,
  one_per_abi_email_lrfs VARCHAR(69)  ENCODE zstd,
  name_available_lrfs VARCHAR(1)  ENCODE zstd,
  company_available_lrfs VARCHAR(1)  ENCODE zstd,
  abi_available_lrfs VARCHAR(1)  ENCODE zstd,
  phone_number_available_lrfs VARCHAR(1)  ENCODE zstd,
  royalty_emails_lrfs VARCHAR(1)  ENCODE zstd,
  infogroup_emails_lrfs VARCHAR(1)  ENCODE zstd,
  a10_digit_phone_lrfs VARCHAR(10)  ENCODE zstd,
  state_with_county_code_lrfs VARCHAR(5)  ENCODE zstd,
  one_per_contact_name_lrfs VARCHAR(55)  ENCODE zstd,
  contacts_per_company_lrfs VARCHAR(80)  ENCODE zstd,
  one_per_company_lrfs VARCHAR(30)  ENCODE zstd,
  id BIGINT UNIQUE sortkey ENCODE delta,
  listid INT  ENCODE az64,
  permissiontype VARCHAR(1)  ENCODE zstd,
  gender VARCHAR(1)  ENCODE zstd,
  listtype VARCHAR(1)  ENCODE zstd,
  productcode VARCHAR(1)  ENCODE zstd,
  cinclude1 VARCHAR(1)  ENCODE zstd,
  bademails VARCHAR(1)  ENCODE zstd,
  website_available VARCHAR(1)  ENCODE zstd,
  one_per_company_name_title VARCHAR(33)  ENCODE zstd,
  job_level_code_multi VARCHAR(9)  ENCODE lzo,
  department_code_multi VARCHAR(9)  ENCODE lzo,
  cinclude VARCHAR(1)  ENCODE zstd,
  cdomain VARCHAR(50)  ENCODE zstd,
  blank_titles VARCHAR(1)  ENCODE zstd,
  md5saltedhash VARCHAR(32)  ENCODE zstd,
  latitude VARCHAR(11)  ENCODE zstd,
  longitude VARCHAR(11)  ENCODE zstd,
  geo_match_level VARCHAR(1)  ENCODE zstd,
  database_flag VARCHAR(1)  ENCODE zstd,
  work_at_home_indicator VARCHAR(1)  ENCODE zstd,
  sitenumber VARCHAR(9)  ENCODE zstd,
  contactid VARCHAR(12)  ENCODE zstd,
  sha256lower VARCHAR(64)  ENCODE zstd,
  sha256upper VARCHAR(64)  ENCODE zstd,
  phone_number_type VARCHAR(1)  ENCODE zstd,
  digitalmatch VARCHAR(1)  ENCODE zstd,
  functional_area_code VARCHAR(4)  ENCODE bytedict,
  literal_title_department_code VARCHAR(2)  ENCODE zstd,
  role_code VARCHAR(4)  ENCODE zstd,
  level_code VARCHAR(1)  ENCODE zstd,
  contactquality VARCHAR(1)  ENCODE zstd,
  bridge_code VARCHAR(1)  ENCODE zstd,
  domain_id VARCHAR(1)  ENCODE zstd,
  topleveldomain VARCHAR(6)  ENCODE zstd,
  email_deliverable VARCHAR(1)  ENCODE zstd,
  email_marketable VARCHAR(1)  ENCODE zstd,
  email_reputation_risk VARCHAR(1)  ENCODE zstd,
  cbsatype VARCHAR(5)  ENCODE zstd,
  censusblock VARCHAR(1)  ENCODE zstd,
  inferred_corporate_employee_count VARCHAR(6)  ENCODE zstd,
  inferred_corporate_employee_range VARCHAR(1)  ENCODE zstd,
  inferred_corporate_employee_source_indicator VARCHAR(1)  ENCODE zstd,
  inferred_corporate_sales_volume_amount VARCHAR(9)  ENCODE zstd,
  inferred_corporate_sales_volume_range VARCHAR(1)  ENCODE zstd,
  inferred_corporate_sales_volume_source_indicator VARCHAR(1)  ENCODE zstd,
  naicscode VARCHAR(8)  ENCODE zstd,
  numberemployees VARCHAR(5)  ENCODE zstd,
  outputvolume2 VARCHAR(9)  ENCODE zstd,
  subsidairyabinumber VARCHAR(9)  ENCODE zstd,
  yearestablished VARCHAR(4)  ENCODE zstd,
  creditcardsaccepted_1 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_2 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_3 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_4 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_5 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_6 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_7 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_8 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_9 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_10 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_11 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_12 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_13 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_14 VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted_15 VARCHAR(1)  ENCODE zstd,
  addresstype VARCHAR(2)  ENCODE zstd,
  femaleexecflag VARCHAR(1)  ENCODE zstd,
  truefranchiseflag VARCHAR(1)  ENCODE zstd,
  industryspecificfirstbyte VARCHAR(1)  ENCODE zstd,
  wealthcode VARCHAR(1)  ENCODE zstd,
  bigbusinesssegmentationcode VARCHAR(1)  ENCODE zstd,
  smmedbusseg1 VARCHAR(1)  ENCODE zstd,
  smmedbusseg2 VARCHAR(1)  ENCODE zstd,
  fortuneranking VARCHAR(4)  ENCODE zstd,
  hightechbusinessflag VARCHAR(1)  ENCODE zstd,
  filingflag VARCHAR(1)  ENCODE zstd,
  whitecollar VARCHAR(4)  ENCODE zstd,
  whitecollarflag VARCHAR(1)  ENCODE zstd,
  primary_mail_confidence VARCHAR(1)  ENCODE zstd,
  secondary_mail_confidence VARCHAR(1)  ENCODE zstd,
  foreignparentflag VARCHAR(1)  ENCODE zstd,
  importexportflag VARCHAR(1)  ENCODE zstd,
  highincomeexecflag VARCHAR(1)  ENCODE zstd,
  greenadopterscore VARCHAR(1)  ENCODE zstd,
  telecommunications_expense VARCHAR(1)  ENCODE zstd,
  technology_expense VARCHAR(1)  ENCODE zstd,
  office_equipment_expense VARCHAR(1)  ENCODE zstd,
  payroll_expense VARCHAR(1)  ENCODE zstd,
  rent_leasing_expense VARCHAR(1)  ENCODE zstd,
  advertising_expense VARCHAR(1)  ENCODE zstd,
  utilities_expense VARCHAR(1)  ENCODE zstd,
  accounting_expense VARCHAR(1)  ENCODE zstd,
  packagecontainer_expense VARCHAR(1)  ENCODE zstd,
  contract_labor_expense VARCHAR(1)  ENCODE zstd,
  insurance_expense VARCHAR(1)  ENCODE zstd,
  purchased_print_expense VARCHAR(1)  ENCODE zstd,
  purchase_mgmtadmin_svc_expense VARCHAR(1)  ENCODE zstd,
  legal_expense VARCHAR(1)  ENCODE zstd,
  charitable_dontations_expense VARCHAR(1)  ENCODE zstd,
  license_fees_taxes VARCHAR(1)  ENCODE zstd,
  maintenance_repair VARCHAR(1)  ENCODE zstd,
  transportationexpensecode VARCHAR(1)  ENCODE zstd,
  franchise_code_1 VARCHAR(3)  ENCODE zstd,
  franchise_code_2 VARCHAR(3)  ENCODE zstd,
  franchise_code_3 VARCHAR(3)  ENCODE zstd,
  franchise_code_4 VARCHAR(3)  ENCODE zstd,
  franchise_code_5 VARCHAR(3)  ENCODE zstd,
  franchise_code_6 VARCHAR(3)  ENCODE zstd,
  fleetsize VARCHAR(1)  ENCODE zstd,
  legal_name VARCHAR(120)  ENCODE zstd,
  last_modified_date VARCHAR(6)  ENCODE bytedict,
  vendor_ethnicity VARCHAR(2)  ENCODE zstd,
  vendor_ethnic_group VARCHAR(1)  ENCODE zstd,
  vendor_language VARCHAR(2)  ENCODE zstd,
  vendor_religion VARCHAR(1)  ENCODE zstd,
  naicscode6 VARCHAR(6)  ENCODE zstd,
  naicscode4 VARCHAR(4)  ENCODE zstd,
  naicscode2 VARCHAR(2)  ENCODE zstd,
  individual_mc_wb VARCHAR(17)  ENCODE zstd,
  company_mc_wb VARCHAR(15)  ENCODE zstd,
  faxavailable_flag VARCHAR(1)  ENCODE zstd,
  creditcardsaccepted VARCHAR(15)  ENCODE zstd,
  creditcardsaccepted_multi VARCHAR(50)  ENCODE zstd,
  zip9 VARCHAR(9)  ENCODE zstd,
  literal_title_available VARCHAR(1)  ENCODE zstd,
  flatitude FLOAT  ENCODE zstd,
  flongitude FLOAT  ENCODE zstd,
  cbsalevel VARCHAR(1)  ENCODE zstd,
  combined_franchise_code VARCHAR(30)  ENCODE zstd,
  individual_mc VARCHAR(17)  ENCODE zstd,
  company_mc VARCHAR(15)  ENCODE zstd,
  email_deployable VARCHAR(1) ENCODE zstd
);

INSERT into {table-businessemail-new}
(
  abi_number_lrfs,
  company_name_lrfs,
  addressline1,
  city,
  state,
  zip,
  firstname,
  lastname,
  title_lrfs,
  gender_lrfs,
  email_address_lrfs,
  primary_sic_code_lrfs,
  area_code_lrfs,
  phone_number_lrfs,
  literaltitle_id,
  title_description_lrfs,
  unique_id_lrfs,
  vendor_id_lrfs,
  executive_source_code_lrfs,
  bvt_email_status_lrfs,
  suppression_type,
  responder_date,
  scf_lrfs,
  a4_digit_primary_sic_lrfs,
  a4_digit_secondary_sic_lrfs,
  employee_size_code_lrfs,
  sales_volume_code_lrfs,
  business_status_code_lrfs,
  secondary_sic_code_lrfs,
  franchise_code_lrfs,
  cbsa_lrfs,
  ad_size_lrfs,
  business_credit_score_code_lrfs,
  business_credit_score_lrfs,
  call_status_lrfs,
  growing_shrinking_indicator_lrfs,
  ultimate_number_lrfs,
  fax_number_lrfs,
  individual_firm_lrfs,
  multi_tenant_code_lrfs,
  multi_tenant_building_number_lrfs,
  number_of_pc_lrfs,
  office_size_lrfs,
  own_lease_lrfs,
  population_code_lrfs,
  public_private_code_lrfs,
  government_segment_code_lrfs,
  square_footage_lrfs,
  teleresearch_date_lrfs,
  transaction_date_lrfs,
  transaction_type_lrfs,
  website_lrfs,
  year_first_appeared_lrfs,
  year_sic_added_lrfs,
  zip_end_lrfs,
  carrier_route_lrfs,
  census_lrfs,
  state_code_lrfs,
  county_code_lrfs,
  csa_lrfs,
  zip4_lrfs,
  secondary_sic2_lrfs,
  secondary_sic3_lrfs,
  secondary_sic4_lrfs,
  md5upper_lrfs,
  md5lower_lrfs,
  one_per__abi_lrfs,
  seq_lrfs,
  title_rank_lrfs,
  professional_title_code,
  department_code,
  job_level_code,
  mail_score,
  city_available,
  fullname,
  company,
  a2_digit_primary_sic_lrfs,
  one_per_abi_lrfs,
  domain_name_lrfs,
  one_per_abiname_lrfs,
  one_per_abi_email_lrfs,
  name_available_lrfs,
  company_available_lrfs,
  abi_available_lrfs,
  phone_number_available_lrfs,
  royalty_emails_lrfs,
  infogroup_emails_lrfs,
  a10_digit_phone_lrfs,
  state_with_county_code_lrfs,
  one_per_contact_name_lrfs,
  contacts_per_company_lrfs,
  one_per_company_lrfs,
  id,
  listid,
  permissiontype,
  gender,
  listtype,
  productcode,
  cinclude1,
  bademails,
  website_available,
  one_per_company_name_title,
  job_level_code_multi,
  department_code_multi,
  cinclude,
  cdomain,
  blank_titles,
  md5saltedhash,
  latitude,
  longitude,
  geo_match_level,
  database_flag,
  work_at_home_indicator,
  sitenumber,
  contactid,
  sha256lower,
  sha256upper,
  phone_number_type,
  digitalmatch,
  functional_area_code,
  literal_title_department_code,
  role_code,
  level_code,
  contactquality,
  bridge_code,
  domain_id,
  topleveldomain,
  email_deliverable,
  email_marketable,
  email_reputation_risk,
  cbsatype,
  censusblock,
  inferred_corporate_employee_count,
  inferred_corporate_employee_range,
  inferred_corporate_employee_source_indicator,
  inferred_corporate_sales_volume_amount,
  inferred_corporate_sales_volume_range,
  inferred_corporate_sales_volume_source_indicator,
  naicscode,
  numberemployees,
  outputvolume2,
  subsidairyabinumber,
  yearestablished,
  creditcardsaccepted_1,
  creditcardsaccepted_2,
  creditcardsaccepted_3,
  creditcardsaccepted_4,
  creditcardsaccepted_5,
  creditcardsaccepted_6,
  creditcardsaccepted_7,
  creditcardsaccepted_8,
  creditcardsaccepted_9,
  creditcardsaccepted_10,
  creditcardsaccepted_11,
  creditcardsaccepted_12,
  creditcardsaccepted_13,
  creditcardsaccepted_14,
  creditcardsaccepted_15,
  addresstype,
  femaleexecflag,
  truefranchiseflag,
  industryspecificfirstbyte,
  wealthcode,
  bigbusinesssegmentationcode,
  smmedbusseg1,
  smmedbusseg2,
  fortuneranking,
  hightechbusinessflag,
  filingflag,
  whitecollar,
  whitecollarflag,
  primary_mail_confidence,
  secondary_mail_confidence,
  foreignparentflag,
  importexportflag,
  highincomeexecflag,
  greenadopterscore,
  telecommunications_expense,
  technology_expense,
  office_equipment_expense,
  payroll_expense,
  rent_leasing_expense,
  advertising_expense,
  utilities_expense,
  accounting_expense,
  packagecontainer_expense,
  contract_labor_expense,
  insurance_expense,
  purchased_print_expense,
  purchase_mgmtadmin_svc_expense,
  legal_expense,
  charitable_dontations_expense,
  license_fees_taxes,
  maintenance_repair,
  transportationexpensecode,
  franchise_code_1,
  franchise_code_2,
  franchise_code_3,
  franchise_code_4,
  franchise_code_5,
  franchise_code_6,
  fleetsize,
  legal_name,
  last_modified_date,
  vendor_ethnicity,
  vendor_ethnic_group,
  vendor_language,
  vendor_religion,
  naicscode6,
  naicscode4,
  naicscode2,
  individual_mc_wb,
  company_mc_wb,
  faxavailable_flag,
  creditcardsaccepted,
  creditcardsaccepted_multi,
  zip9,
  literal_title_available,
  flatitude,
  flongitude,
  cbsalevel,
  combined_franchise_code,
  individual_mc,
  company_mc,
  email_deployable
)
SELECT
     a.abi_number_lrfs AS abi_number_lrfs,
     CASE WHEN a.company_name_lrfs LIKE '%|%' THEN REPLACE(a.company_name_lrfs ,'|',' ')
          WHEN a.company_name_lrfs IS NULL THEN ''
          ELSE a.company_name_lrfs
          END AS company_name_lrfs,  
     CASE WHEN a.addressline1 IS NULL THEN ''
          ELSE a.addressline1 END AS addressline1,
     a.city AS city,
     a.state AS state,
     CASE WHEN a.zip IS NULL THEN '' 
          ELSE a.zip END AS zip,
     CASE WHEN a.firstname IS NULL THEN '' 
          ELSE a.firstname END AS firstname,
     CASE WHEN a.lastname IS NULL THEN '' 
          ELSE a.lastname END AS lastname,
     CASE WHEN a.title_lrfs = '!'  THEN 'Z1'
          WHEN a.title_lrfs = '#'  THEN 'Z2'
          WHEN a.title_lrfs = '$'  THEN 'Z3'
          WHEN a.title_lrfs = '%'  THEN 'Z4'
          WHEN a.title_lrfs = '&'  THEN 'Z5'
          WHEN a.title_lrfs = '('  THEN 'Z6'
          WHEN a.title_lrfs = ')'  THEN 'Z7'
          WHEN a.title_lrfs = '+'  THEN 'Z8'
          WHEN a.title_lrfs = '-'  THEN 'Z9'
          WHEN a.title_lrfs = '.'  THEN 'Z10'
          WHEN a.title_lrfs = '/'  THEN 'Z11'
          WHEN a.title_lrfs = ':'  THEN 'Z12'
          WHEN a.title_lrfs = '='  THEN 'Z13'
          WHEN a.title_lrfs = '>'  THEN 'Z14'
          WHEN a.title_lrfs = '?'  THEN 'Z15'
          WHEN a.title_lrfs = '@'  THEN 'Z16'
          WHEN a.title_lrfs = '['  THEN 'Z17'
          WHEN a.title_lrfs = '\\' THEN 'Z18'
          WHEN a.title_lrfs = ']'  THEN 'Z19'
          WHEN a.title_lrfs = '^'  THEN 'Z20'
          WHEN a.title_lrfs = '_'  THEN 'Z21'
          WHEN a.title_lrfs = '{'  THEN 'Z22'
          ELSE a.title_lrfs END AS title_lrfs,
     a.gender_lrfs AS gender_lrfs,
     CASE WHEN a.email_address_lrfs IS NOT NULL AND 
               a.email_address_lrfs <> '' AND 
               UPPER(a.email_address_lrfs) LIKE '%.CA' THEN '' 
          ELSE a.email_address_lrfs END AS email_address_lrfs,
     a.primary_sic_code_lrfs AS primary_sic_code_lrfs,
     a.area_code_lrfs AS area_code_lrfs,
     a.phone_number_lrfs AS phone_number_lrfs,
     a.literaltitle_id AS literaltitle_id,
     a.title_description_lrfs AS title_description_lrfs,
     a.unique_id_lrfs AS unique_id_lrfs,
     a.vendor_id_lrfs AS vendor_id_lrfs,
     a.executive_source_code_lrfs AS executive_source_code_lrfs,
     a.bvt_email_status_lrfs AS bvt_email_status_lrfs,
     a.suppression_type AS suppression_type,
     a.responder_date AS responder_date,
     a.scf_lrfs AS scf_lrfs,
     a.a4_digit_primary_sic_lrfs AS a4_digit_primary_sic_lrfs,
     a.a4_digit_secondary_sic_lrfs AS a4_digit_secondary_sic_lrfs,
     a.employee_size_code_lrfs AS employee_size_code_lrfs,
     a.sales_volume_code_lrfs AS sales_volume_code_lrfs,
     a.business_status_code_lrfs AS business_status_code_lrfs,
     a.secondary_sic_code_lrfs AS secondary_sic_code_lrfs,
     UPPER(a.franchise_code_lrfs) AS franchise_code_lrfs,
     a.cbsa_lrfs AS cbsa_lrfs,
     a.ad_size_lrfs AS ad_size_lrfs,
     a.business_credit_score_code_lrfs AS business_credit_score_code_lrfs,
     a.business_credit_score_lrfs AS business_credit_score_lrfs,
     a.call_status_lrfs AS call_status_lrfs,
     a.growing_shrinking_indicator_lrfs AS growing_shrinking_indicator_lrfs,
     a.ultimate_number_lrfs AS ultimate_number_lrfs,
     a.fax_number_lrfs AS fax_number_lrfs,
     a.individual_firm_lrfs AS individual_firm_lrfs,
     a.multi_tenant_code_lrfs AS multi_tenant_code_lrfs,
     a.multi_tenant_building_number_lrfs AS multi_tenant_building_number_lrfs,
     a.number_of_pc_lrfs AS number_of_pc_lrfs,
     a.office_size_lrfs AS office_size_lrfs,
     a.own_lease_lrfs AS own_lease_lrfs,
     a.population_code_lrfs AS population_code_lrfs,
     a.public_private_code_lrfs AS public_private_code_lrfs,
     a.government_segment_code_lrfs AS government_segment_code_lrfs,
     a.square_footage_lrfs AS square_footage_lrfs,
     a.teleresearch_date_lrfs AS teleresearch_date_lrfs,
     a.transaction_date_lrfs AS transaction_date_lrfs,
     a.transaction_type_lrfs AS transaction_type_lrfs,
     a.website_lrfs AS website_lrfs,
     a.year_first_appeared_lrfs AS year_first_appeared_lrfs,
     a.year_sic_added_lrfs AS year_sic_added_lrfs,
     a.zip_end_lrfs AS zip_end_lrfs,
     a.carrier_route_lrfs AS carrier_route_lrfs,
     a.census_lrfs AS census_lrfs,
     a.state_code_lrfs AS state_code_lrfs,
     a.county_code_lrfs AS county_code_lrfs,
     a.csa_lrfs AS csa_lrfs,
     a.zip4_lrfs AS zip4_lrfs,
     a.secondary_sic2_lrfs AS secondary_sic2_lrfs,
     a.secondary_sic3_lrfs AS secondary_sic3_lrfs,
     a.secondary_sic4_lrfs AS secondary_sic4_lrfs,
     CASE WHEN a.email_address_lrfs IS NOT NULL AND 
               a.email_address_lrfs <> '' AND 
               UPPER(a.email_address_lrfs) LIKE '%.CA' THEN ''
          ELSE a.md5upper_lrfs END AS md5upper_lrfs,
     CASE WHEN a.email_address_lrfs IS NOT NULL AND 
               a.email_address_lrfs <> '' AND 
               UPPER(a.email_address_lrfs) LIKE '%.CA' THEN '' 
          ELSE a.md5lower_lrfs END AS md5lower_lrfs,
     a.one_per__abi_lrfs AS one_per__abi_lrfs,
     a.seq_lrfs AS seq_lrfs,
     a.title_rank_lrfs AS title_rank_lrfs,
     a.professional_title_code AS professional_title_code,
     a.department_code AS department_code,
     a.job_level_code AS job_level_code,
     a.mail_score AS mail_score,
     CASE WHEN a.city = '' THEN 'N' 
          ELSE 'Y' END AS city_available,  
     LTRIM(RTRIM(a.firstname))+ ' '+ LTRIM(RTRIM(a.lastname)) AS fullname,
     SPACE(1) AS company,
     LEFT(a.a4_digit_primary_sic_lrfs,2) AS a2_digit_primary_sic_lrfs,
     LEFT(a.zip,5)+RTRIM(a.abi_number_lrfs) AS one_per_abi_lrfs, 
     RIGHT(a.email_address_lrfs, CHARINDEX('@', REVERSE(a.email_address_lrfs))-1) AS domain_name_lrfs,
     LEFT(a.abi_number_lrfs,9) + RTRIM(LTRIM(RTRIM(a.firstname)) + LTRIM(RTRIM(a.lastname))) AS one_per_abiname_lrfs,
     LEFT(a.abi_number_lrfs,9) + RTRIM(a.email_address_lrfs) AS one_per_abi_email_lrfs,
     CASE WHEN a.firstname + a.lastname = '' THEN 'N' 
          ELSE 'Y' END AS name_available_lrfs,
     CASE WHEN a.company_name_lrfs = '' THEN 'N' 
          ELSE 'Y' END AS company_available_lrfs,
     CASE WHEN a.abi_number_lrfs = '000000000' THEN 'N' 
          ELSE 'Y' END AS abi_available_lrfs,
     CASE WHEN a.phone_number_lrfs = '' THEN 'N'
          ELSE 'Y' END AS phone_number_available_lrfs,
     CASE WHEN a.vendor_id_lrfs ='36' THEN 'N' 
          ELSE 'Y' END AS royalty_emails_lrfs,
     CASE WHEN a.vendor_id_lrfs ='36' THEN 'Y' 
          ELSE 'N' END AS infogroup_emails_lrfs,
     a.area_code_lrfs + a.phone_number_lrfs AS a10_digit_phone_lrfs,
     a.state + a.county_code_lrfs AS state_with_county_code_lrfs,
     LEFT(a.zip,5) + RTRIM(LTRIM(RTRIM(a.firstname)) + LTRIM(RTRIM(a.lastname))) AS one_per_contact_name_lrfs,
     LTRIM(RTRIM(LEFT(a.company_name_lrfs,30))) + RTRIM(LTRIM(RTRIM(a.firstname)) + LTRIM(RTRIM(a.lastname))) AS contacts_per_company_lrfs ,
     LEFT(a.company_name_lrfs,30) AS one_per_company_lrfs,
     a.id AS id,
     9178 AS listid,
     'R' AS permissiontype,
     a.gender AS gender,
     a.listtype AS listtype,
     a.productcode AS productcode,
     'Y' AS cinclude1,
     CASE WHEN a.email_address_lrfs LIKE 'INFO@%' OR
               a.email_address_lrfs LIKE 'SALES@%' OR
               UPPER(a.email_address_lrfs) LIKE '%.CA' AND
               a.email_address_lrfs <> '' AND
               a.email_address_lrfs IS NOT NULL
          THEN 'Y' 
          ELSE 'N' END AS bademails,
     CASE WHEN a.website_lrfs = '' THEN 'N' 
          ELSE 'Y' END AS website_available,
     LTRIM(RTRIM(LEFT(a.company_name_lrfs,30))) + RTRIM(LTRIM(RTRIM(a.title_lrfs))) AS one_per_company_name_title,
     CASE WHEN a.job_level_code <> '' AND LEN(a.job_level_code) = 1 THEN ',' + a.job_level_code + ','
          WHEN a.job_level_code <> '' AND LEN(a.job_level_code) = 2 THEN ',' + LEFT(a.job_level_code,1) + ',' + RIGHT(a.job_level_code,1) + ','
          WHEN a.job_level_code <> '' AND LEN(a.job_level_code) = 3 THEN  ',' + SUBSTRING(a.job_level_code,1,1) + ',' + SUBSTRING(a.job_level_code,2,1) + ',' + SUBSTRING(a.job_level_code,3,1) + ','
          WHEN a.job_level_code <> '' AND LEN(a.job_level_code) = 4 THEN ',' + SUBSTRING(a.job_level_code,1,1) + ',' + SUBSTRING(a.job_level_code,2,1) + ',' + SUBSTRING(a.job_level_code,3,1) + ',' + SUBSTRING(a.job_level_code,4,1) + ',' END AS job_level_code_multi,
     CASE WHEN a.department_code <> '' AND LEN(a.department_code) = 1 THEN ',' + a.department_code + ','
          WHEN a.department_code <> '' AND LEN(a.department_code) = 2 THEN ',' + LEFT(a.department_code,1) + ',' + RIGHT(a.department_code,1) + ','
          WHEN a.department_code <> '' AND LEN(a.department_code) = 3 THEN ',' + SUBSTRING(a.department_code,1,1) + ',' + SUBSTRING(a.department_code,2,1) + ',' + SUBSTRING(a.department_code,3,1) + ','
          WHEN a.department_code <> '' AND LEN(a.department_code) = 4 THEN ',' + SUBSTRING(a.department_code,1,1) + ',' + SUBSTRING(a.department_code,2,1) + ',' + SUBSTRING(a.department_code,3,1) + ',' + SUBSTRING(a.department_code,4,1) + ',' END AS department_code_multi,
     CASE WHEN a.email_address_lrfs IS NOT NULL AND
               a.email_address_lrfs <> '' AND 
               UPPER(a.email_address_lrfs) LIKE '%.CA' THEN 'C' 
          ELSE 'Y' END AS cinclude,
     CASE SUBSTRING(a.email_address_lrfs,(CHARINDEX('@',a.email_address_lrfs) + 1),(LEN(a.email_address_lrfs)-(CHARINDEX('@',a.email_address_lrfs)))) 
          WHEN 'GMAIL.COM' THEN 'GMAIL.COM' 
          WHEN 'HOTMAIL.COM' THEN 'HOTMAIL.COM' 
          WHEN 'YAHOO.COM' THEN 'YAHOO.COM' 
          WHEN 'AOL.COM' THEN 'AOL.COM' 
          ELSE 'OTHER' END AS cdomain,
     CASE WHEN a.title_lrfs IN ('1','2','3','4','5','6','7','8','9','A','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','V','W','X','Y','1','2','3','4','5','6','7','8','9','A','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','V','W','X','Y','!', '#', '$', '%', '&', '(', ')', '+', '-', '.', '/', ':', '=', '>', '?', '@', '[', ']', '\\', '^', '_', '{') 
          THEN 'A' 
          ELSE 'B' END AS blank_titles,
     CASE WHEN a.email_address_lrfs IS NOT NULL AND 
               a.email_address_lrfs <> '' AND 
               UPPER(a.email_address_lrfs) LIKE '%.CA' THEN ''
          ELSE a.md5saltedhash END AS md5saltedhash,
     a.latitude AS latitude,
     a.longitude AS longitude,
     a.geo_match_level AS geo_match_level,
     a.database_flag AS database_flag,
     a.work_at_home_indicator AS work_at_home_indicator,
     a.sitenumber AS sitenumber,
     a.contactid AS contactid,
     a.sha256lower AS sha256lower,
     a.sha256upper AS sha256upper,
     a.phone_number_type AS phone_number_type,
     a.digitalmatch AS digitalmatch,
     a.functional_area_code AS functional_area_code,
     a.literal_title_department_code AS literal_title_department_code,
     a.role_code AS role_code,
     a.level_code AS level_code,
     a.contactquality AS contactquality,
     a.bridge_code AS bridge_code,
     a.domain_id AS domain_id,
     a.topleveldomain AS topleveldomain,
     a.email_deliverable AS email_deliverable,
     a.email_marketable AS email_marketable,
     a.email_reputation_risk AS email_reputation_risk,
     a.cbsatype AS cbsatype,
     a.censusblock AS censusblock,
     a.inferred_corporate_employee_count AS inferred_corporate_employee_count,
     a.inferred_corporate_employee_range AS inferred_corporate_employee_range,
     a.inferred_corporate_employee_source_indicator AS inferred_corporate_employee_source_indicator,
     a.inferred_corporate_sales_volume_amount AS inferred_corporate_sales_volume_amount,
     a.inferred_corporate_sales_volume_range AS inferred_corporate_sales_volume_range,
     a.inferred_corporate_sales_volume_source_indicator AS inferred_corporate_sales_volume_source_indicator,
     a.naicscode AS naicscode,
     a.numberemployees AS numberemployees,
     a.outputvolume2 AS outputvolume2,
     a.subsidairyabinumber AS subsidairyabinumber,
     a.yearestablished AS yearestablished,
     a.creditcardsaccepted_1 AS creditcardsaccepted_1,
     a.creditcardsaccepted_2 AS creditcardsaccepted_2,
     a.creditcardsaccepted_3 AS creditcardsaccepted_3,
     a.creditcardsaccepted_4 AS creditcardsaccepted_4,
     a.creditcardsaccepted_5 AS creditcardsaccepted_5,
     a.creditcardsaccepted_6 AS creditcardsaccepted_6,
     a.creditcardsaccepted_7 AS creditcardsaccepted_7,
     a.creditcardsaccepted_8 AS creditcardsaccepted_8,
     a.creditcardsaccepted_9 AS creditcardsaccepted_9,
     a.creditcardsaccepted_10 AS creditcardsaccepted_10,
     a.creditcardsaccepted_11 AS creditcardsaccepted_11,
     a.creditcardsaccepted_12 AS creditcardsaccepted_12,
     a.creditcardsaccepted_13 AS creditcardsaccepted_13,
     a.creditcardsaccepted_14 AS creditcardsaccepted_14,
     a.creditcardsaccepted_15 AS creditcardsaccepted_15,
     a.addresstype AS addresstype,
     CASE WHEN a.femaleexecflag = 'Y' THEN '1'
          WHEN a.femaleexecflag IS NULL OR a.femaleexecflag = 'N' THEN ''
          ELSE a.femaleexecflag
          END AS femaleexecflag,
     a.truefranchiseflag AS truefranchiseflag,
     a.industryspecificfirstbyte AS industryspecificfirstbyte,
     CASE WHEN a.wealthcode = '1' THEN 'Y' 
          ELSE 'N' END AS wealthcode,
     a.bigbusinesssegmentationcode AS bigbusinesssegmentationcode,
     a.smmedbusseg1 AS smmedbusseg1,
     a.smmedbusseg2 AS smmedbusseg2,
     a.fortuneranking AS fortuneranking,
     a.hightechbusinessflag AS hightechbusinessflag,
     a.filingflag AS filingflag,
     a.whitecollar AS whitecollar,
     a.whitecollarflag AS whitecollarflag,
     a.primary_mail_confidence AS primary_mail_confidence,
     a.secondary_mail_confidence AS secondary_mail_confidence,
     a.foreignparentflag AS foreignparentflag,
     a.importexportflag AS importexportflag,
     CASE WHEN a.highincomeexecflag = 'Y' THEN '1' 
          WHEN a.highincomeexecflag IS NULL OR a.highincomeexecflag = 'N' THEN ''
          ELSE a.highincomeexecflag
          END AS highincomeexecflag,
     a.greenadopterscore AS greenadopterscore,
     a.telecommunications_expense AS telecommunications_expense,
     a.technology_expense AS technology_expense,
     a.office_equipment_expense AS office_equipment_expense,
     a.payroll_expense AS payroll_expense,
     a.rent_leasing_expense AS rent_leasing_expense,
     a.advertising_expense AS advertising_expense,
     a.utilities_expense AS utilities_expense,
     a.accounting_expense AS accounting_expense,
     a.packagecontainer_expense AS packagecontainer_expense,
     a.contract_labor_expense AS contract_labor_expense,
     a.insurance_expense AS insurance_expense,
     a.purchased_print_expense AS purchased_print_expense,
     a.purchase_mgmtadmin_svc_expense AS purchase_mgmtadmin_svc_expense,
     a.legal_expense AS legal_expense,
     a.charitable_dontations_expense AS charitable_dontations_expense,
     a.license_fees_taxes AS license_fees_taxes,
     a.maintenance_repair AS maintenance_repair,
     a.transportationexpensecode AS transportationexpensecode,
     a.franchise_code_1 AS franchise_code_1,
     a.franchise_code_2 AS franchise_code_2,
     a.franchise_code_3 AS franchise_code_3,
     a.franchise_code_4 AS franchise_code_4,
     a.franchise_code_5 AS franchise_code_5,
     a.franchise_code_6 AS franchise_code_6,
     a.fleetsize AS fleetsize,
     a.legal_name AS legal_name,
     a.last_modified_date AS last_modified_date,
     a.vendor_ethnicity AS vendor_ethnicity,
     a.vendor_ethnic_group AS vendor_ethnic_group,
     a.vendor_language AS vendor_language,
     a.vendor_religion AS vendor_religion,
     LEFT(a.naicscode, 6) AS naicscode6,
     LEFT(a.naicscode, 4) AS naicscode4,
     LEFT(a.naicscode, 2) AS naicscode2,
     a.individual_mc_wb AS individual_mc_wb,
     a.company_mc_wb AS company_mc_wb,
     CASE WHEN LTRIM(RTRIM(a.fax_number_lrfs)) = '' THEN 'N' 
          ELSE 'Y' END AS faxavailable_flag,
     a.creditcardsaccepted_1 + a.creditcardsaccepted_2 + a.creditcardsaccepted_3 + a.creditcardsaccepted_4 + a.creditcardsaccepted_5 + a.creditcardsaccepted_6 + a.creditcardsaccepted_7 + a.creditcardsaccepted_8 + a.creditcardsaccepted_9 + a.creditcardsaccepted_10 + a.creditcardsaccepted_11 + a.creditcardsaccepted_12 +a.creditcardsaccepted_13 + a.creditcardsaccepted_14 + a.creditcardsaccepted_15 AS creditcardsaccepted,
     CASE WHEN a.creditcardsaccepted_1 + a.creditcardsaccepted_2 + a.creditcardsaccepted_3 + a.creditcardsaccepted_4 + a.creditcardsaccepted_5 + 
               a.creditcardsaccepted_6 + a.creditcardsaccepted_7 + a.creditcardsaccepted_8 + a.creditcardsaccepted_9 + a.creditcardsaccepted_10 + 
               a.creditcardsaccepted_11 + a.creditcardsaccepted_12 +a.creditcardsaccepted_13 + a.creditcardsaccepted_14 + a.creditcardsaccepted_15 ='' THEN ''
          ELSE ',' + a.creditcardsaccepted_1 + ',' +  a.creditcardsaccepted_2 + ',' + a.creditcardsaccepted_3 + 
               ',' + a.creditcardsaccepted_4 +',' +  a.creditcardsaccepted_5 + ',' + a.creditcardsaccepted_6 +
               ',' + a.creditcardsaccepted_7 + ',' + a.creditcardsaccepted_8 + ',' + a.creditcardsaccepted_9 + 
               ',' + a.creditcardsaccepted_10 + ',' + a.creditcardsaccepted_11 + ',' + a.creditcardsaccepted_12 +
               ',' + a.creditcardsaccepted_13 + ',' + a.creditcardsaccepted_14 + ',' + a.creditcardsaccepted_15  + ',' END AS creditcardsaccepted_multi,
     a.zip9 AS zip9,
     CASE WHEN LTRIM(RTRIM(a.title_description_lrfs)) <> '' THEN 'Y' 
          ELSE 'N' END AS literal_title_available,
     CASE WHEN a.latitude != '' THEN CAST(a.latitude AS FLOAT) END AS flatitude,
     CASE when a.longitude < 0 and a.longitude != '' THEN CAST(a.longitude AS FLOAT)* -1
          WHEN a.longitude >= 0 and a.longitude != '' THEN CAST(a.longitude AS FLOAT)
          END AS flongitude,
     CASE WHEN a.cbsatype = 'MICRO' THEN '1'
          WHEN a.cbsatype = 'METRO' THEN '2'
          WHEN a.cbsatype = '' OR a.cbsatype IS NULL THEN '0' 
          END AS cbsalevel,
     ',' + CASE WHEN a.franchise_code_1 <> '' THEN a.franchise_code_1 + ',' ELSE '' END + 
           CASE WHEN a.franchise_code_2 <> '' THEN a.franchise_code_2 + ',' ELSE '' END + 
           CASE WHEN a.franchise_code_3 <> '' THEN a.franchise_code_3 + ',' ELSE '' END + 
           CASE WHEN a.franchise_code_4 <> '' THEN a.franchise_code_4 + ',' ELSE '' END + 
           CASE WHEN a.franchise_code_5 <> '' THEN a.franchise_code_5 + ',' ELSE '' END + 
           CASE WHEN a.franchise_code_6 <> '' THEN a.franchise_code_6 + ',' ELSE '' END AS combined_franchise_code,
     GETMATCHCODE (a.firstname, CASE WHEN (a.lastname = '' OR a.lastname IS NULL) THEN a.company_name_lrfs ELSE a.lastname END, a.addressline1, a.zip, '' ,'I') AS individual_mc,
     GETMATCHCODE (a.firstname, a.lastname, a.addressline1, a.zip, CASE WHEN (a.company_name_lrfs = '' OR a.company_name_lrfs IS NULL) THEN a.LastName ELSE a.company_name_lrfs END,'C') AS company_mc,
     A.email_deployable AS email_deployable
FROM {table-businessemail-new-raw} AS a;