DROP TABLE IF EXISTS {DnB-raw-table};
CREATE TABLE {DnB-raw-table} 
(
	id INT IDENTITY,
	dbus_duns VARCHAR(9) NOT NULL,
	dbus_businessname VARCHAR(30) NOT NULL,
	dbus_tradestylename VARCHAR(30) NOT NULL,
	dbus_streetaddress VARCHAR(25) NOT NULL,
	dbus_city VARCHAR(20) NOT NULL,
	dbus_stateabbreviation VARCHAR(2) NOT NULL,
	dbus_zipcodeforstreetaddress VARCHAR(5) NOT NULL,
	dbus_zip_4extentionforstreetaddress VARCHAR(4) NOT NULL,
	dbus_mailingaddress VARCHAR(25) NOT NULL,
	dbus_mailingcityname VARCHAR(20) NOT NULL,
	dbus_mailingstateabbreviation VARCHAR(2) NOT NULL,
	dbus_mailingzipcode VARCHAR(5) NOT NULL,
	dbus_mailingzip_4extention VARCHAR(4) NOT NULL,
	dbus_carrierroutecode VARCHAR(4) NOT NULL,
	dbus_deliverypointpostalcode VARCHAR(2) NOT NULL,
	dbus_nationalcodes VARCHAR(3) NOT NULL,
	dbus_dunandbradstreetstatecode VARCHAR(2) NOT NULL,
	dbus_dunandbradstreetcountycode VARCHAR(3) NOT NULL,
	dbus_dunandbradstreetcitycode VARCHAR(4) NOT NULL,
	dbus_dunandbradstreetsmsacode VARCHAR(3) NOT NULL,
	dbus_telephonenbr VARCHAR(10) NOT NULL,
	dbus_ceoname VARCHAR(30) NOT NULL,
	dbus_ceotitle VARCHAR(30) NOT NULL,
	dbus_salesvolume VARCHAR(15) NOT NULL,
	dbus_codeforestimateorrange1 VARCHAR(1) NOT NULL,
	dbus_employeescompany VARCHAR(9) NOT NULL,
	dbus_codeforestimateorrange2 VARCHAR(1) NOT NULL,
	dbus_employeeslocation VARCHAR(9) NOT NULL,
	dbus_codeforestimateorrange3 VARCHAR(1) NOT NULL,
	dbus_yearstarted VARCHAR(4) NOT NULL,
	dbus_statusindicator VARCHAR(1) NOT NULL,
	filler_1 VARCHAR(80),
	dbus_populationcode VARCHAR(1) NOT NULL,
	dbus_transactioncodes VARCHAR(1) NOT NULL,
	dbus_lastupdatedate VARCHAR(6) NOT NULL,
	dbus_cottageind VARCHAR(1) NOT NULL,
	dbus_smallbusiness VARCHAR(1) NOT NULL,
	dbus_womenowned VARCHAR(1) NOT NULL,
	dbus_minorityownedind VARCHAR(1) NOT NULL,
	dbus_minorityclassif VARCHAR(3) NOT NULL,
	dbus_import_export VARCHAR(1) NOT NULL,
	dbus_filler12 VARCHAR(11) NOT NULL,
	dbus_recordclasstype VARCHAR(1) NOT NULL,
	dbus_lineofbusiness VARCHAR(19) NOT NULL,
	dbus_sic VARCHAR(4) NOT NULL,
	dbus_dunandbradstreet2_2extention1 VARCHAR(4) NOT NULL,
	dbus_dunandbradstreet2_2extention2 VARCHAR(4) NOT NULL,
	dbus_dunandbradstreet2_2extention3 VARCHAR(4) NOT NULL,
	dbus_dunandbradstreet2_2extention4 VARCHAR(4) NOT NULL,
	dbus_sic2sameformatasprimarysic VARCHAR(20) NOT NULL,
	dbus_sic3sameformatasprimarysic VARCHAR(20) NOT NULL,
	dbus_sic4sameformatasprimarysic VARCHAR(20) NOT NULL,
	dbus_sic5sameformatasprimarysic VARCHAR(20) NOT NULL,
	dbus_sic6sameformatasprimarysic VARCHAR(20) NOT NULL,
	dbus_franchisecode VARCHAR(8) NOT NULL,
	dbus_franchisecode2 VARCHAR(8) NOT NULL,
	dbus_franchisecode3 VARCHAR(8) NOT NULL,
	dbus_franchisecode4 VARCHAR(8) NOT NULL,
	dbus_franchisecode5 VARCHAR(8) NOT NULL,
	dbus_franchisecode6 VARCHAR(8) NOT NULL,
	dbus_franchiseind VARCHAR(1) NOT NULL,
	dbus_faxnumber VARCHAR(10) NOT NULL,
	dbus_public_privateind VARCHAR(1) NOT NULL,
	dbus_wholesaleofficesupplieswosbi VARCHAR(2) NOT NULL,
	dbus_fortune1000 VARCHAR(1) NOT NULL,
	dbus_percentgrowthsales3yr VARCHAR(4) NOT NULL,
	dbus_percentgrowthemploy3yr VARCHAR(4) NOT NULL,
	dbus_trendyearsales3yr VARCHAR(15) NOT NULL,
	dbus_trendyearemploy3yr VARCHAR(9) NOT NULL,
	dbus_percentgrowthsales5yr VARCHAR(4) NOT NULL,
	dbus_percentgrowthemploy5yr VARCHAR(4) NOT NULL,
	dbus_trendyearsales5yr VARCHAR(15) NOT NULL,
	dbus_trendyearemploy5yr VARCHAR(9) NOT NULL,
	dbus_baseyearsales VARCHAR(15) NOT NULL,
	dbus_baseyearemployees VARCHAR(9) NOT NULL,
	dbus_headquarterduns VARCHAR(9) NOT NULL,
	dbus_parentduns VARCHAR(9) NOT NULL,
	dbus_domesticultimateduns VARCHAR(9) NOT NULL,
	dbus_ownsrents VARCHAR(1) NOT NULL,
	dbus_squarefootage VARCHAR(9) NOT NULL,
	dbus_legalstatuscode VARCHAR(1) NOT NULL,
	dbus_numberoffamilymembers VARCHAR(5) NOT NULL,
	dbus_estimatedpcs VARCHAR(8) NOT NULL,
	dbus_estimatedprinters VARCHAR(8) NOT NULL,
	dbus_estimatednumberofcopiers VARCHAR(1) NOT NULL,
	filler_2 VARCHAR(2),
	company_mc VARCHAR(15) NULL,
	dbus_hasphone VARCHAR(1),
	employeescompany_recoded VARCHAR(1),
	dbus_employeeslocation_recoded VARCHAR(1),
	dbus_salesvolume_recoded VARCHAR(1),
	dbus_sic6 VARCHAR(6),
	dbus_sic8 VARCHAR(8)
);

COPY {DnB-raw-table} 
(
    dbus_duns,
    dbus_businessname,
    dbus_tradestylename,
    dbus_streetaddress,
    dbus_city,
    dbus_stateabbreviation,
    dbus_zipcodeforstreetaddress,
    dbus_zip_4extentionforstreetaddress,
    dbus_mailingaddress,
    dbus_mailingcityname,
    dbus_mailingstateabbreviation,
    dbus_mailingzipcode,
    dbus_mailingzip_4extention,
    dbus_carrierroutecode,
    dbus_deliverypointpostalcode,
    dbus_nationalcodes,
    dbus_dunandbradstreetstatecode,
    dbus_dunandbradstreetcountycode,
    dbus_dunandbradstreetcitycode,
    dbus_dunandbradstreetsmsacode,
    dbus_telephonenbr,
    dbus_ceoname,
    dbus_ceotitle,
    dbus_salesvolume,
    dbus_codeforestimateorrange1,
    dbus_employeescompany,
    dbus_codeforestimateorrange2,
    dbus_employeeslocation,
    dbus_codeforestimateorrange3,
    dbus_yearstarted,
    dbus_statusindicator,
    filler_1,
    dbus_populationcode,
    dbus_transactioncodes,
    dbus_lastupdatedate,
    dbus_cottageind,
    dbus_smallbusiness,
    dbus_womenowned,
    dbus_minorityownedind,
    dbus_minorityclassif,
    dbus_import_export,
    dbus_filler12,
    dbus_recordclasstype,
    dbus_lineofbusiness,
    dbus_sic,
    dbus_dunandbradstreet2_2extention1 ,
    dbus_dunandbradstreet2_2extention2 ,
    dbus_dunandbradstreet2_2extention3 ,
    dbus_dunandbradstreet2_2extention4 ,
    dbus_sic2sameformatasprimarysic,
    dbus_sic3sameformatasprimarysic,
    dbus_sic4sameformatasprimarysic,
    dbus_sic5sameformatasprimarysic,
    dbus_sic6sameformatasprimarysic,
    dbus_franchisecode,
    dbus_franchisecode2,
    dbus_franchisecode3,
    dbus_franchisecode4,
    dbus_franchisecode5,
    dbus_franchisecode6,
    dbus_franchiseind,
    dbus_faxnumber,
    dbus_public_privateind,
    dbus_wholesaleofficesupplieswosbi,
    dbus_fortune1000,
    dbus_percentgrowthsales3yr,
    dbus_percentgrowthemploy3yr,
    dbus_trendyearsales3yr,
    dbus_trendyearemploy3yr,
    dbus_percentgrowthsales5yr,
    dbus_percentgrowthemploy5yr,
    dbus_trendyearsales5yr,
    dbus_trendyearemploy5yr,
    dbus_baseyearsales,
    dbus_baseyearemployees,
    dbus_headquarterduns,
    dbus_parentduns,
    dbus_domesticultimateduns,
    dbus_ownsrents,
    dbus_squarefootage,
    dbus_legalstatuscode,
    dbus_numberoffamilymembers,
    dbus_estimatedpcs,
    dbus_estimatedprinters,
    dbus_estimatednumberofcopiers,
    filler_2
) 
FROM 's3://{s3-internal}{s3-key}'
IAM_ROLE '{iam}'
IGNOREBLANKLINES
ACCEPTINVCHARS
FIXEDWIDTH
'dbus_duns:9,
dbus_businessname:30,
dbus_tradestylename:30,
dbus_streetaddress:25,
dbus_city:20,
dbus_stateabbreviation:2,
dbus_zipcodeforstreetaddress:5,
dbus_zip_4extentionforstreetaddress:4,
dbus_mailingaddress:25,
dbus_mailingcityname:20,
dbus_mailingstateabbreviation:2,
dbus_mailingzipcode:5,
dbus_mailingzip_4extention:4,
dbus_carrierroutecode:4,
dbus_deliverypointpostalcode:2,
dbus_nationalcodes:3,
dbus_dunandbradstreetstatecode:2,
dbus_dunandbradstreetcountycode:3,
dbus_dunandbradstreetcitycode:4,
dbus_dunandbradstreetsmsacode:3,
dbus_telephonenbr:10,
dbus_ceoname:30,
dbus_ceotitle:30,
dbus_salesvolume:15,
dbus_codeforestimateorrange1:1,
dbus_employeescompany:9,
dbus_codeforestimateorrange2:1,
dbus_employeeslocation:9,
dbus_codeforestimateorrange3:1,
dbus_yearstarted:4,
dbus_statusindicator:1,
filler_1:80,
dbus_populationcode:1,
dbus_transactioncodes:1,
dbus_lastupdatedate:6,
dbus_cottageind:1,
dbus_smallbusiness:1,
dbus_womenowned:1,
dbus_minorityownedind:1,
dbus_minorityclassif:3,
dbus_import_export:1,
dbus_filler12:11,
dbus_recordclasstype:1,
dbus_lineofbusiness:19,
dbus_sic:4,
dbus_dunandbradstreet2_2extention1 :4,
dbus_dunandbradstreet2_2extention2 :4,
dbus_dunandbradstreet2_2extention3 :4,
dbus_dunandbradstreet2_2extention4 :4,
dbus_sic2sameformatasprimarysic:20,
dbus_sic3sameformatasprimarysic:20,
dbus_sic4sameformatasprimarysic:20,
dbus_sic5sameformatasprimarysic:20,
dbus_sic6sameformatasprimarysic:20,
dbus_franchisecode:8,
dbus_franchisecode2:8,
dbus_franchisecode3:8,
dbus_franchisecode4:8,
dbus_franchisecode5:8,
dbus_franchisecode6:8,
dbus_franchiseind:1,
dbus_faxnumber:10,
dbus_public_privateind:1,
dbus_wholesaleofficesupplieswosbi:2,
dbus_fortune1000:1,
dbus_percentgrowthsales3yr:4,
dbus_percentgrowthemploy3yr:4,
dbus_trendyearsales3yr:15,
dbus_trendyearemploy3yr:9,
dbus_percentgrowthsales5yr:4,
dbus_percentgrowthemploy5yr:4,
dbus_trendyearsales5yr:15,
dbus_trendyearemploy5yr:9,
dbus_baseyearsales:15,
dbus_baseyearemployees:9,
dbus_headquarterduns:9,
dbus_parentduns:9,
dbus_domesticultimateduns:9,
dbus_ownsrents:1,
dbus_squarefootage:9,
dbus_legalstatuscode:1,
dbus_numberoffamilymembers:5,
dbus_estimatedpcs:8,
dbus_estimatedprinters:8,
dbus_estimatednumberofcopiers:1,
filler_2:2';