DROP TABLE IF EXISTS nosuchtable;

DROP TABLE IF EXISTS tblIndividual;

CREATE TABLE tblIndividual
(
ID int identity unique,
ABINUMBER varchar(9) SORTKEY DISTKEY,
LASTNAME varchar(14),
FIRSTNAME varchar(11),
SALUTATION varchar(2),
PROFTITLE varchar(3),
TITLECODE varchar(1),
GENDER varchar(1),
EMAIL_FLAG varchar(1),
VENDORID2 varchar(2),
EXECUTIVESOURCECODE varchar(2),
FEMALEEXECFLAG varchar(1),
HIGHINCOMEEXECFLAG varchar(1),
VENDOR_ETHNICITY varchar(2),
VENDOR_ETHNIC_GROUP varchar(1),
VENDOR_LANGUAGE varchar(2),
VENDOR_RELIGION varchar(1),
CONTACTID varchar(12),
CONTACTQUALITY varchar(1),
DIGITALMATCH varchar(1),
FUNCTIONAL_AREA_CODE varchar(4),
DEPARTMENT_CODE varchar(2),
ROLE_CODE varchar(4),
LEVEL_CODE varchar(1),
LiteralTitle_ID varchar(8),
TYPECODE varchar(1),
CONTACTSOURCEDATE varchar(8),
Homeaddress VARCHAR(30),
Homecity VARCHAR(30),
Homestate VARCHAR(2),
Homezipcode VARCHAR(5),
Homezip4 VARCHAR(4),
Homeareacode VARCHAR(3),
Homephonenumber VARCHAR(7),
Donotcallflag VARCHAR(1),
Homecountycode VARCHAR(3),
Homelocationtype VARCHAR(1),
Execgender VARCHAR(1),
Execage VARCHAR(2),
Execincome VARCHAR(1),
Homeowner VARCHAR(1),
Maritalstatus VARCHAR(1),
Job_Function_ID	VARCHAR(3),
Management_Level VARCHAR(25),
Job_Title VARCHAR(80),
Creditcardsaccepted VARCHAR(15),
Creditcardsaccepted_Multi VARCHAR(50)
);

COPY tblIndividual
(
ABINUMBER,
LASTNAME,
FIRSTNAME,
SALUTATION,
PROFTITLE,
TITLECODE,
GENDER,
EMAIL_FLAG,
VENDORID2,
EXECUTIVESOURCECODE,
FEMALEEXECFLAG,
HIGHINCOMEEXECFLAG,
VENDOR_ETHNICITY,
VENDOR_ETHNIC_GROUP,
VENDOR_LANGUAGE,
VENDOR_RELIGION,
CONTACTID,
CONTACTQUALITY,
DIGITALMATCH,
FUNCTIONAL_AREA_CODE,
DEPARTMENT_CODE,
ROLE_CODE,
LEVEL_CODE,
LiteralTitle_ID,
TYPECODE,
CONTACTSOURCEDATE,
Homeaddress,
Homecity,
Homestate,
Homezipcode,
Homezip4,
Homeareacode,
Homephonenumber,
Donotcallflag,
Homecountycode,
Homelocationtype,
Execgender,
Execage,
Execincome,
Homeowner,
Maritalstatus,
Job_Function_ID,
Management_Level,
Job_Title
)
FROM 's3://idms-7933-internalfiles/business-core/IDMSEXEC.gz'
IAM_ROLE 'arn:aws:iam::479134617933:role/da-idms-redshift-role'
IGNOREBLANKLINES
ACCEPTINVCHARS
GZIP
FIXEDWIDTH
'
ABINUMBER:9,
LASTNAME:14,
FIRSTNAME:11,
SALUTATION:2,
PROFTITLE:3,
TITLECODE:1,
GENDER:1,
EMAIL_FLAG:1,
VENDORID2:2,
EXECUTIVESOURCECODE:2,
FEMALEEXECFLAG:1,
HIGHINCOMEEXECFLAG:1,
VENDOR_ETHNICITY:2,
VENDOR_ETHNIC_GROUP:1,
VENDOR_LANGUAGE:2,
VENDOR_RELIGION:1,
CONTACTID:12,
CONTACTQUALITY:1,
DIGITALMATCH:1,
FUNCTIONAL_AREA_CODE:4,
DEPARTMENT_CODE:2,
ROLE_CODE:4,
LEVEL_CODE:1,
LiteralTitle_ID:8,
TYPECODE:1,
CONTACTSOURCEDATE:8,
Homeaddress:30,
Homecity:30,
Homestate:2,
Homezipcode:5,
Homezip4:4,
Homeareacode:3,
Homephonenumber:7,
Donotcallflag:1,
Homecountycode:3,
Homelocationtype:1,
Execgender:1,
Execage:2,
Execincome:1,
Homeowner:1,
Maritalstatus:1,
Job_Function_ID:3,
Management_Level:25,
Job_Title:80';
