DROP TABLE IF exists ddvalues2;

Select DISTINCT
	cFieldName, 
	cValue, 
	cDescription
INTO DDValues2
from sql_tblDDDescriptions
Where Databaseid = 1293
and cValue <>''
and cFieldname in  (
	'ACCOUNTING_EXPENSE',
	'ADVERTISING_EXPENSE',
	'CHARITABLE_DONTATIONS_EXPENSE',
	'CONTRACT_LABOR_EXPENSE',
	'INSURANCE_EXPENSE',
	'LEGAL_EXPENSE',
	'LICENSE_FEES_TAXES',
	'MAINTENANCE_REPAIR',
	'OFFICE_EQUIPMENT_EXPENSE',
	'PACKAGECONTAINER_EXPENSE',
	'PAYROLL_EXPENSE',
	'PURCHASED_PRINT_EXPENSE',
	'PURCHASE_MGMTADMIN_SVC_EXPENSE',
	'RENT_LEASING_EXPENSE',
	'TECHNOLOGY_EXPENSE',
	'TELECOMMUNICATIONS_EXPENSE',
	'TRANSPORTATIONEXPENSECODE',
	'UTILITIES_EXPENSE',
	'SALUTATION',
	'ACL_GROUPCODE',
	'ACL_DENOMINATIONCODE',
	'DMACODE' ,
	'PROFTITLE',
	'ADDRESSTYPE',
	'OWNORLEASE',
	'AMI_BOARDCERTIFIEDINDICATOR',
	'AMI_PRIMARYSPECIALTY',
	'AMI_SECONDARYSPECIALTY',
	'AMI_PROFESSIONALDEGREECODE',
	'AMI_LIC_STATEOFLICENSE',
	'AMI_PRESCRIPTIONSPERWK',
	'PHONE_NUMBER_TYPE',
	'CREDITRATINGCODE',
	'CBSACODE',
	'DISTRICTCODE',
	'TITLECODE',
	'GENDER'
);
	
	
drop table if exists ddvalues_2_dddescriptions_clean;
CREATE TABLE ddvalues_2_dddescriptions_clean
DISTKEY (ID)
SORTKEY(ID)
AS
SELECT 
a.id as id,
(dd1_7.cDescription) as ACCOUNTING_EXPENSE,
(dd1_8.cDescription) as ADVERTISING_EXPENSE,
(dd1_9.cDescription) as CHARITABLE_DONTATIONS_EXPENSE,
(dd1_10.cDescription) as CONTRACT_LABOR_EXPENSE,
(dd1_11.cDescription) as INSURANCE_EXPENSE,
(dd1_12.cDescription) as LEGAL_EXPENSE,
(dd1_13.cDescription) as LICENSE_FEES_TAXES,
(dd1_14.cDescription) as MAINTENANCE_REPAIR,
(dd1_15.cDescription) as OFFICE_EQUIPMENT_EXPENSE,
(dd1_16.cDescription) as PACKAGECONTAINER_EXPENSE,
(dd1_17.cDescription) as PAYROLL_EXPENSE,
(dd1_18.cDescription) as PURCHASED_PRINT_EXPENSE,
(dd1_19.cDescription) as PURCHASE_MGMTADMIN_SVC_EXPENSE,
(dd1_20.cDescription) as RENT_LEASING_EXPENSE,
(dd1_21.cDescription) as TECHNOLOGY_EXPENSE,
(dd1_22.cDescription) as TELECOMMUNICATIONS_EXPENSE,
(dd1_23.cDescription) as TransportationExpenseCode  ,
(dd1_24.cDescription) as UTILITIES_EXPENSE,
(dd1_25.cDescription) as SALUTATION,
(dd1_26.cDescription) as ACL_GROUPCODE,
(dd1_27.cDescription) as ACL_DENOMINATIONCODE,
(dd1_28.cDescription) as DMACode,
(dd1_29.cDescription) as PROFTITLE,
(dd1_30.cDescription) as ADDRESSTYPE,
(dd1_31.cDescription) as OWNORLEASE,
(dd1_32.cDescription) as AMI_BOARDCERTIFIEDINDICATOR,
(dd1_33.cDescription) as AMI_PRIMARYSPECIALTY,
(dd1_34.cDescription) as AMI_SECONDARYSPECIALTY     ,
(dd1_35.cDescription) as AMI_PROFESSIONALDEGREECODE     ,
(dd1_36.cDescription) as AMI_LIC_STATEOFLICENSE,
(dd1_37.cDescription) as AMI_PRESCRIPTIONSPERWK,
(dd1_38.cDescription) as CREDITRATINGCODE,
(dd1_39.cDescription) as PHONE_NUMBER_TYPE,
(dd1_40.cDescription) AS DISTRICT_DESCRIPTION,
(dd1_41.cDescription) AS CREDIT_RATING_DESCRIPTION,
(dd1_42.cDescription) AS TITLE_DESCRIPTION,
(dd1_43.cDescription) AS GENDER_DESCRIPTION,
(dd1_44.cDescription) AS CMA_DESCRIPTION
FROM tblBusinessIndividual a 
left join ddvalues2 DD1_7  ON A.ACCOUNTING_EXPENSE = DD1_7.cValue and DD1_7.cFieldName ='ACCOUNTING_EXPENSE'
left join ddvalues2 DD1_8  ON A.ADVERTISING_EXPENSE = DD1_8.cValue and DD1_8.cFieldName ='ADVERTISING_EXPENSE'
left join ddvalues2 DD1_9  ON A.CHARITABLE_DONTATIONS_EXPENSE = DD1_9.cValue and DD1_9.cFieldName ='CHARITABLE_DONTATIONS_EXPENSE'
left join ddvalues2 DD1_10 ON A.CONTRACT_LABOR_EXPENSE = DD1_10.cValue and DD1_10.cFieldName ='CONTRACT_LABOR_EXPENSE'
left join ddvalues2 DD1_11 ON A.INSURANCE_EXPENSE = DD1_11.cValue and DD1_11.cFieldName ='INSURANCE_EXPENSE'
left join ddvalues2 DD1_12  ON A.LEGAL_EXPENSE = DD1_12.cValue and DD1_12.cFieldName ='LEGAL_EXPENSE'
left join ddvalues2 DD1_13  ON A.LICENSE_FEES_TAXES = DD1_13.cValue and DD1_13.cFieldName ='LICENSE_FEES_TAXES'
left join ddvalues2 DD1_14  ON A.MAINTENANCE_REPAIR = DD1_14.cValue and DD1_14.cFieldName ='MAINTENANCE_REPAIR'
left join ddvalues2 DD1_15  ON A.OFFICE_EQUIPMENT_EXPENSE = DD1_15.cValue and DD1_15.cFieldName ='OFFICE_EQUIPMENT_EXPENSE'
left join ddvalues2 DD1_16  ON A.PACKAGECONTAINER_EXPENSE = DD1_16.cValue and DD1_16.cFieldName ='PACKAGECONTAINER_EXPENSE'
left join ddvalues2 DD1_17  ON A.PAYROLL_EXPENSE = DD1_17.cValue and DD1_17.cFieldName ='PAYROLL_EXPENSE'
left join ddvalues2 DD1_18  ON A.PURCHASED_PRINT_EXPENSE = DD1_18.cValue and DD1_18.cFieldName ='PURCHASED_PRINT_EXPENSE'
left join ddvalues2 DD1_19  ON A.PURCHASE_MGMTADMIN_SVC_EXPENSE = DD1_19.cValue and DD1_19.cFieldName ='PURCHASE_MGMTADMIN_SVC_EXPENSE'
left join ddvalues2 DD1_20  ON A.RENT_LEASING_EXPENSE = DD1_20.cValue and DD1_20.cFieldName ='RENT_LEASING_EXPENSE'
left join ddvalues2 DD1_21  ON A.TECHNOLOGY_EXPENSE = DD1_21.cValue and DD1_21.cFieldName ='TECHNOLOGY_EXPENSE'
left join ddvalues2 DD1_22  ON A.TELECOMMUNICATIONS_EXPENSE = DD1_22.cValue and DD1_22.cFieldName ='TELECOMMUNICATIONS_EXPENSE'
left join ddvalues2 DD1_23  ON A.TransportationExpenseCode = DD1_23.cValue and DD1_23.cFieldName ='TRANSPORTATIONEXPENSECODE'
left join ddvalues2 DD1_24  ON A.UTILITIES_EXPENSE = DD1_24.cValue and DD1_24.cFieldName ='UTILITIES_EXPENSE'
left join ddvalues2 DD1_25  ON A.SALUTATION = DD1_25.cValue and DD1_25.cFieldName ='SALUTATION'
left join ddvalues2 DD1_26  ON A.ACL_GROUPCODE = DD1_26.cValue and DD1_26.cFieldName ='ACL_GROUPCODE'
left join ddvalues2 DD1_27  ON A.ACL_DENOMINATIONCODE = DD1_27.cValue and DD1_27.cFieldName ='ACL_DENOMINATIONCODE'
left join ddvalues2 DD1_28  ON A.DMACode = DD1_28.cValue and DD1_28.cFieldName ='DMACODE'
left join ddvalues2 DD1_29  ON A.PROFTITLE = DD1_29.cValue and DD1_29.cFieldName ='PROFTITLE'
left join ddvalues2 DD1_30  ON A.ADDRESSTYPE = DD1_30.cValue and DD1_30.cFieldName ='ADDRESSTYPE'
left join ddvalues2 DD1_31  ON A.OWNORLEASE = DD1_31.cValue and DD1_31.cFieldName ='OWNORLEASE'
left join ddvalues2 DD1_32  ON A.AMI_BOARDCERTIFIEDINDICATOR = DD1_32.cValue and DD1_32.cFieldName ='AMI_BOARDCERTIFIEDINDICATOR'
left join ddvalues2 DD1_33  ON A.AMI_PRIMARYSPECIALTY = DD1_33.cValue and DD1_33.cFieldName ='AMI_PRIMARYSPECIALTY'
left join ddvalues2 DD1_34  ON A.AMI_SECONDARYSPECIALTY = DD1_34.cValue and DD1_34.cFieldName ='AMI_SECONDARYSPECIALTY'
left join ddvalues2 DD1_35  ON A.AMI_PROFESSIONALDEGREECODE = DD1_35.cValue and DD1_35.cFieldName ='AMI_PROFESSIONALDEGREECODE'
left join ddvalues2 DD1_36  ON A.AMI_LIC_STATEOFLICENSE = DD1_36.cValue and DD1_36.cFieldName ='AMI_LIC_STATEOFLICENSE'
left join ddvalues2 DD1_37  ON A.AMI_PRESCRIPTIONSPERWK = DD1_37.cValue and DD1_37.cFieldName ='AMI_PRESCRIPTIONSPERWK'
left join ddvalues2 DD1_38  ON A.CREDITRATINGCODE = DD1_38.cValue and DD1_38.cFieldName ='CREDITRATINGCODE'
left join ddvalues2 DD1_39  ON A.PHONE_NUMBER_TYPE = DD1_39.cValue and DD1_39.cFieldName ='PHONE_NUMBER_TYPE'
left join ddvalues2 DD1_40  ON A.DISTRICTCODE = DD1_40.cValue and DD1_40.cFieldName ='DISTRICTCODE'
left join ddvalues2 DD1_41  ON A.CREDITRATINGCODE = DD1_41.cValue and DD1_41.cFieldName ='CREDITRATINGCODE'
left join ddvalues2 DD1_42  ON A.TITLECODE = DD1_42.cValue and DD1_42.cFieldName ='TITLECODE'
LEFT join ddvalues2 DD1_43  ON A.GENDER = DD1_43.cValue and DD1_43.cFieldName ='GENDER'
LEFT join ddvalues2 DD1_44  ON A.CBSACODE = DD1_44.cValue and DD1_44.cFieldName ='CBSACODE';


DROP TABLE IF EXISTS ddvalues_2_dddescriptions;
CREATE TABLE ddvalues_2_dddescriptions 
DISTKEY (ID)
SORTKEY(ID)
AS 
SELECT
id,
min(ACCOUNTING_EXPENSE) as ACCOUNTING_EXPENSE,
min(ADVERTISING_EXPENSE) as ADVERTISING_EXPENSE,
min(CHARITABLE_DONTATIONS_EXPENSE) as CHARITABLE_DONTATIONS_EXPENSE,
min(CONTRACT_LABOR_EXPENSE) as CONTRACT_LABOR_EXPENSE,
min(INSURANCE_EXPENSE) as INSURANCE_EXPENSE,
min(LEGAL_EXPENSE) as LEGAL_EXPENSE,
min(LICENSE_FEES_TAXES) as LICENSE_FEES_TAXES,
min(MAINTENANCE_REPAIR) as MAINTENANCE_REPAIR,
min(OFFICE_EQUIPMENT_EXPENSE) as OFFICE_EQUIPMENT_EXPENSE,
min(PACKAGECONTAINER_EXPENSE) as PACKAGECONTAINER_EXPENSE,
min(PAYROLL_EXPENSE) as PAYROLL_EXPENSE,
min(PURCHASED_PRINT_EXPENSE) as PURCHASED_PRINT_EXPENSE,
min(PURCHASE_MGMTADMIN_SVC_EXPENSE) as PURCHASE_MGMTADMIN_SVC_EXPENSE,
min(RENT_LEASING_EXPENSE) as RENT_LEASING_EXPENSE,
min(TECHNOLOGY_EXPENSE) as TECHNOLOGY_EXPENSE,
min(TELECOMMUNICATIONS_EXPENSE) as TELECOMMUNICATIONS_EXPENSE,
min(TransportationExpenseCode) as TransportationExpenseCode,
min(UTILITIES_EXPENSE) as UTILITIES_EXPENSE,
min(SALUTATION) as SALUTATION,
min(ACL_GROUPCODE) as ACL_GROUPCODE,
min(ACL_DENOMINATIONCODE) as ACL_DENOMINATIONCODE,
min(DMACode) as DMACode,
min(PROFTITLE) as PROFTITLE,
min(ADDRESSTYPE) as ADDRESSTYPE,
min(OWNORLEASE) as OWNORLEASE,
min(AMI_BOARDCERTIFIEDINDICATOR) as AMI_BOARDCERTIFIEDINDICATOR,
min(AMI_PRIMARYSPECIALTY) as AMI_PRIMARYSPECIALTY,
min(AMI_SECONDARYSPECIALTY) as AMI_SECONDARYSPECIALTY,
min(AMI_PROFESSIONALDEGREECODE) as AMI_PROFESSIONALDEGREECODE,
min(AMI_LIC_STATEOFLICENSE) as AMI_LIC_STATEOFLICENSE,
min(AMI_PRESCRIPTIONSPERWK) as AMI_PRESCRIPTIONSPERWK,
min(CREDITRATINGCODE) as CREDITRATINGCODE,
min(PHONE_NUMBER_TYPE) as PHONE_NUMBER_TYPE,
min(DISTRICT_DESCRIPTION) as DISTRICT_DESCRIPTION,
min(CREDIT_RATING_DESCRIPTION) as CREDIT_RATING_DESCRIPTION,
min(TITLE_DESCRIPTION) as TITLE_DESCRIPTION,
min(GENDER_DESCRIPTION) as GENDER_DESCRIPTION,
min(CMA_DESCRIPTION) as CMA_DESCRIPTION
FROM ddvalues_2_dddescriptions_clean DDValues
GROUP BY ID
;