DROP TABLE IF EXISTS ca_tblBusinessIndividual_ctas1 CASCADE;

CREATE TABLE ca_tblBusinessIndividual_ctas1
AS
SELECT
a.ID AS ID,
a.ABINUMBER AS ABINUMBER,
CASE WHEN a.COMPANY LIKE '%|%' then REPLACE(a.COMPANY,'|',' ') else a.COMPANY end AS COMPANY_OLD,
LEFT(CASE WHEN a.Company <> '' THEN REPLACE(a.COMPANY,'|',' ') ELSE ltrim(RTRIM(NVL(a.FirstName, ''))) + ' ' + ltrim(RTRIM(NVL(a.LastName, ''))) + ' ' + ltrim(RTRIM(NVL(a.PROFTITLE, ''))) END, 30) AS COMPANY,
a.ADDRESS AS ADDRESS,
a.CITY AS CITY,
a.STATE AS STATE,
a.ZIP_Back AS ZIP_Back,
LEFT(a.ZIP9,6) as ZIP,
a.ZIPFOUR AS ZIPFOUR,
a.ZIP9 AS ZIP9,
a.CARRIERROUTECODE AS CARRIERROUTECODE,
a.MAILING_ADDRESS AS MAILING_ADDRESS,
a.MAILING_CITY AS MAILING_CITY,
a.MAILING_STATE AS MAILING_STATE,
a.MAILING_ZIPCODE AS MAILING_ZIPCODE,
a.MAILING_ZIPFOUR AS MAILING_ZIPFOUR,
a.MAILING_CARRIEROUTECODE AS MAILING_CARRIEROUTECODE,
NVL(a.LANDMARK_ADDRESS,'') AS LANDMARK_ADDRESS,
NVL(a.LANDMARK_CITY,'') AS LANDMARK_CITY,
NVL(a.LANDMARK_STATE,'') AS LANDMARK_STATE,
NVL(a.LANDMARK_ZIPCODE,'') AS LANDMARK_ZIPCODE,
NVL(a.LANDMARK_ZIPFOUR,'') AS LANDMARK_ZIPFOUR,
NVL(a.LANDMARK_CARRIEROUTECODE,'') AS LANDMARK_CARRIEROUTECODE,
a.COUNTYCODE AS COUNTYCODE,
a.CENSUSTRACT AS CENSUSTRACT,
a.CENSUSBLOCK AS CENSUSBLOCK,
NVL(a.fLATITUDE, 0) AS fLATITUDE,
NVL(a.fLONGITUDE, 0) AS fLONGITUDE,
NVL(a.MATCHCODE,'') as MATCHCODE,
nvl(a.TOLLFREEPHONENUMBER,'') as TOLLFREEPHONENUMBER,
NVL(a.RADIALDISTANCE,'') AS RADIALDISTANCE,
CASE WHEN LTRIM(RTRIM(a.PhoneNumber)) Like '%0001111' THEN '' ELSE a.PhoneNumber END AS PHONENUMBER,
a.FAXPHONE AS FAXPHONE,
NVL(a.PRIMARYSIC6,'') as PRIMARYSIC6,
NVL(a.PRIMARYSIC4,'') as  PRIMARYSIC4,
NVL(a.PRIMARYSIC2,'') as PRIMARYSIC2,
NVL(a.PRIMARYSICDESIGINATOR,'') AS PRIMARYSICDESIGINATOR,
a.SICCODE1 AS SICCODE1,
a.SICCODE2 AS SICCODE2,
a.SICCODE3 AS SICCODE3,
a.SICCODE4 AS SICCODE4,
nvl(a.FRANCHISECODE1,'') AS FRANCHISECODE1,
nvl(a.FRANCHISECODE2,'') AS FRANCHISECODE2,
nvl(a.FRANCHISECODE3,'') AS FRANCHISECODE3,
nvl(a.FRANCHISECODE4,'') AS FRANCHISECODE4,
nvl(a.FRANCHISECODE5,'') AS FRANCHISECODE5,
nvl(a.FRANCHISECODE6,'') AS FRANCHISECODE6,
a.TRUEFRANCHISEFLAG AS TRUEFRANCHISEFLAG,
a.INDUSTRYSPECIFICFIRSTBYTE AS INDUSTRYSPECIFICFIRSTBYTE,
a.NAICSCODE AS NAICSCODE,
a.NUMBEREMPLOYEES AS NUMBEREMPLOYEES,
a.EMPLOYEESIZECODE2 AS EMPLOYEESIZECODE2,
a.OUTPUTVOLUME2 AS OUTPUTVOLUME2,
CASE WHEN LTRIM(RTRIM(a.OUTPUTVOLUMECODE2))=''OR a.OUTPUTVOLUMECODE2 IS NULL THEN '*' ELSE a.OUTPUTVOLUMECODE2 END AS OUTPUTVOLUMECODE2,
a.ADSIZECODE AS ADSIZECODE,
a.WEALTHCODE AS WEALTHCODE,
a.BIGBUSINESSSEGMENTATIONCODE AS BIGBUSINESSSEGMENTATIONCODE,
a.CREDITNUMERICSCORE AS CREDITNUMERICSCORE,
a.CREDITALPHASCORE AS CREDITALPHASCORE,
a.BUSINESSSTATUSCODE AS BUSINESSSTATUSCODE,
a.CALLSTATUSCODE AS CALLSTATUSCODE,
a.GROWINGBUSINESSFLAG AS GROWINGBUSINESSFLAG,
a.SMMEDBUSSEG1 AS SMMEDBUSSEG1,
a.SMMEDBUSSEG2 AS SMMEDBUSSEG2,
a.FORTUNERANKING AS FORTUNERANKING,
nvl(a.COTTAGECODE,'') as COTTAGECODE,
a.HIGHTECHBUSINESSFLAG AS HIGHTECHBUSINESSFLAG,
nvl(a.IDENTIFICATIONCODE,'') as IDENTIFICATIONCODE,
a.OFFICESIZECODE AS OFFICESIZECODE,
a.OWNORLEASE AS OWNORLEASE,
a.FILINGFLAG AS FILINGFLAG,
a.COMPANYHOLDINGSTATUS AS COMPANYHOLDINGSTATUS,
NVL(a.STOCKEXCHANGECODE,'') AS STOCKEXCHANGECODE,
NVL(a.STOCKTICKERSYMBOL,'') AS STOCKTICKERSYMBOL,
a.TELERESEARCHUPDATEDATE AS TELERESEARCHUPDATEDATE,
a.PARENTABINUMBER AS PARENTABINUMBER,
a.SUBSIDAIRYABINUMBER AS SUBSIDAIRYABINUMBER,
a.SITENUMBER AS SITENUMBER,
a.WEBADDRESS AS WEBADDRESS,
NVL(a.YELLOWPAGECODE,'') AS YELLOWPAGECODE,
NVL(a.BOOKNUMBER,'') AS BOOKNUMBER,
NVL(a.DATEINDATABASE,'') AS DATEINDATABASE,
a.YEARFIRSTAPPEARED AS YEARFIRSTAPPEARED,
a.YEARESTABLISHED AS YEARESTABLISHED,
NVL(a.DELIVERYPOINTBARCODE1,'') AS DELIVERYPOINTBARCODE1,
NVL(a.DELIVERYPOINTBARCODE2,'') AS DELIVERYPOINTBARCODE2,
NVL(a.MODELEDEMPLOYEESIZEFLAG,'') AS MODELEDEMPLOYEESIZEFLAG,
NVL(a.OUTPUTVOLUMETYPECODE,'') AS OUTPUTVOLUMETYPECODE,
NVL(a.ACRONYMFLAG,'') AS ACRONYMFLAG,
NVL(a.CURRENTTRANSACTIONCODE,'') AS CURRENTTRANSACTIONCODE,
NVL(a.LOCATION_PARSEDADDRESSTYPE,'') AS LOCATION_PARSEDADDRESSTYPE,
NVL(a.LOCATION_PARSEDZIPCODE,'') AS LOCATION_PARSEDZIPCODE,
NVL(a.LOCATION_PARSEDSTREETNAME,'') AS LOCATION_PARSEDSTREETNAME,
NVL(a.LOCATION_PARSEDSUFFIX,'') AS LOCATION_PARSEDSUFFIX,
NVL(a.LOCATION_PARSEDPREDIRECTIONAL,'') AS LOCATION_PARSEDPREDIRECTIONAL,
NVL(a.LOCATION_PARSEDPOSTDIRECTION,'') AS LOCATION_PARSEDPOSTDIRECTION,
NVL(a.LOCATION_PARSEDHOUSENUMBER,'') AS LOCATION_PARSEDHOUSENUMBER,
NVL(a.LOCATION_PARSEDSUITENUMBER,'') AS LOCATION_PARSEDSUITENUMBER,
NVL(a.LOCATION_PARSEDCARRIEROUTE,'') AS LOCATION_PARSEDCARRIEROUTE,
NVL(a.MULTITENANTCODE,'') AS MULTITENANTCODE,
NVL(a.BUILDINGNUMBER,'') AS BUILDINGNUMBER,
NVL(a.MULTITENANTNUMBER,'') AS MULTITENANTNUMBER,
NVL(a.PROPERTYMANAGEMENTABI,'') AS PROPERTYMANAGEMENTABI,
NVL(a.PROPERTYMGMT_BUSINESSNAME,'') AS PROPERTYMGMT_BUSINESSNAME,
NVL(a.PROPERTYMGMT_ADDRESS,'') AS PROPERTYMGMT_ADDRESS,
NVL(a.PROPERTYMGMT_CITY,'') AS PROPERTYMGMT_CITY,
NVL(a.PROPERTYMGMT_STATE,'') AS PROPERTYMGMT_STATE,
NVL(a.PROPERTYMGMT_ZIPCODE,'') AS PROPERTYMGMT_ZIPCODE,
NVL(a.PROPERTYMGMT_ZIPFOUR,'') AS PROPERTYMGMT_ZIPFOUR,
NVL(a.PROPERTYMGMT_FIRSTNAME,'') AS PROPERTYMGMT_FIRSTNAME,
NVL(a.PROPERTYMGMT_LASTNAME,'') AS PROPERTYMGMT_LASTNAME,
a.WHITECOLLAR AS WHITECOLLAR,
a.WHITECOLLARFLAG AS WHITECOLLARFLAG,
a.CBSACODE as CBSACODE,
a.MAILCONFIDENCE_MAILING AS MAILCONFIDENCE_MAILING,
NVL(a.CBSALEVEL,'') AS CBSALEVEL,
a.CSACODE AS CSACODE,
a.GOVERNMENTFLAG AS GOVERNMENTFLAG,
a.FOREIGNPARENTFLAG AS FOREIGNPARENTFLAG,
a.IMPORTEXPORTFLAG AS IMPORTEXPORTFLAG,
NVL(a.MONDAYOPEN,'') AS MONDAYOPEN,
NVL(a.MONDAYCLOSE,'') AS MONDAYCLOSE,
NVL(a.TUESDAYOPEN,'') AS TUESDAYOPEN,
NVL(a.TUESDAYCLOSE,'') AS TUESDAYCLOSE,
NVL(a.WEDNESDAYOPEN,'') AS WEDNESDAYOPEN,
NVL(a.WEDNESDAYCLOSE,'') AS WEDNESDAYCLOSE,
NVL(a.THURSDAYOPEN,'') AS THURSDAYOPEN,
NVL(a.THURSDAYCLOSE,'') AS THURSDAYCLOSE,
NVL(a.FRIDAYOPEN,'') AS FRIDAYOPEN,
NVL(a.FRIDAYCLOSE,'') AS FRIDAYCLOSE,
NVL(a.SATURDAYOPEN,'') AS SATURDAYOPEN,
NVL(a.SATURDAYCLOSE,'') AS SATURDAYCLOSE,
NVL(a.SUNDAYOPEN,'') AS SUNDAYOPEN,
NVL(a.SUNDAYCLOSE,'') AS SUNDAYCLOSE,
NVL(a.PAYATPUMP,'') AS PAYATPUMP,
NVL(a.CREDITCARDSACCEPTED_1,'') AS CREDITCARDSACCEPTED_1,
NVL(a.CREDITCARDSACCEPTED_2,'') AS CREDITCARDSACCEPTED_2,
NVL(a.CREDITCARDSACCEPTED_3,'') AS CREDITCARDSACCEPTED_3,
NVL(a.CREDITCARDSACCEPTED_4,'') AS CREDITCARDSACCEPTED_4,
NVL(a.CREDITCARDSACCEPTED_5,'') AS CREDITCARDSACCEPTED_5,
NVL(a.CREDITCARDSACCEPTED_6,'') AS CREDITCARDSACCEPTED_6,
NVL(a.CREDITCARDSACCEPTED_7,'') AS CREDITCARDSACCEPTED_7,
NVL(a.CREDITCARDSACCEPTED_8,'') AS CREDITCARDSACCEPTED_8,
NVL(a.CREDITCARDSACCEPTED_9,'') AS CREDITCARDSACCEPTED_9,
NVL(a.CREDITCARDSACCEPTED_10,'') AS CREDITCARDSACCEPTED_10,
NVL(a.CREDITCARDSACCEPTED_11,'') AS CREDITCARDSACCEPTED_11,
NVL(a.CREDITCARDSACCEPTED_12,'') AS CREDITCARDSACCEPTED_12,
NVL(a.CREDITCARDSACCEPTED_13,'') AS CREDITCARDSACCEPTED_13,
NVL(a.CREDITCARDSACCEPTED_14,'') AS CREDITCARDSACCEPTED_14,
NVL(a.CREDITCARDSACCEPTED_15,'') AS CREDITCARDSACCEPTED_15,
NVL(a.SuspectReasonCode,'') AS SuspectReasonCode,
a.TELECOMMUNICATIONS_EXPENSE AS TELECOMMUNICATIONS_EXPENSE,
a.TECHNOLOGY_EXPENSE AS TECHNOLOGY_EXPENSE,
a.OFFICE_EQUIPMENT_EXPENSE AS OFFICE_EQUIPMENT_EXPENSE,
a.PAYROLL_EXPENSE AS PAYROLL_EXPENSE,
a.RENT_LEASING_EXPENSE AS RENT_LEASING_EXPENSE,
a.ADVERTISING_EXPENSE AS ADVERTISING_EXPENSE,
a.UTILITIES_EXPENSE AS UTILITIES_EXPENSE,
a.ACCOUNTING_EXPENSE AS ACCOUNTING_EXPENSE,
a.PACKAGECONTAINER_EXPENSE AS PACKAGECONTAINER_EXPENSE,
a.CONTRACT_LABOR_EXPENSE AS CONTRACT_LABOR_EXPENSE,
a.INSURANCE_EXPENSE AS INSURANCE_EXPENSE,
a.PURCHASED_PRINT_EXPENSE AS PURCHASED_PRINT_EXPENSE,
a.PURCHASE_MGMTADMIN_SVC_EXPENSE AS PURCHASE_MGMTADMIN_SVC_EXPENSE,
a.LEGAL_EXPENSE AS LEGAL_EXPENSE,
NVL(a.EIN,'') AS EIN,
a.FRANCHISE_CODE_1 AS FRANCHISE_CODE_1,
a.FRANCHISE_CODE_2 AS FRANCHISE_CODE_2,
a.FRANCHISE_CODE_3 AS FRANCHISE_CODE_3,
a.FRANCHISE_CODE_4 AS FRANCHISE_CODE_4,
a.FRANCHISE_CODE_5 AS FRANCHISE_CODE_5,
a.FRANCHISE_CODE_6 AS FRANCHISE_CODE_6,
NVL(a.SERVICETYPE,'') AS SERVICETYPE,
a.ADDRESSTYPE AS ADDRESSTYPE,
CASE WHEN a.haspostal  ='N' and (a.FULFILLMENTFLAG is Null OR a.FULFILLMENTFLAG ='' )  THEN 'U' ELSE a.FULFILLMENTFLAG END AS FULFILLMENTFLAG,
NVL(a.AFFILIATEDLOCATIONS,'') AS AFFILIATEDLOCATIONS,
NVL(a.AFFILIATEDRECORDS,'') AS AFFILIATEDRECORDS,
NVL(a.LASTNAME,'') as LASTNAME,
NVL(a.FIRSTNAME,'') as FIRSTNAME,
NVL(a.SALUTATION,'') as SALUTATION,
NVL(a.PROFTITLE,'') as PROFTITLE,
NVL(a.TITLECODE,'') as TITLECODE,
NVL(a.GENDER,'') as GENDER,
NVL(a.EMAIL_FLAG,'') AS EMAIL_FLAG,
NVL(a.VENDORID2,'') AS VENDORID2,
NVL(a.EXECUTIVESOURCECODE,'') as EXECUTIVESOURCECODE,
NVL(a.FEMALEEXECFLAG,'') as FEMALEEXECFLAG,
NVL(a.HIGHINCOMEEXECFLAG,'') AS HIGHINCOMEEXECFLAG,
NVL(a.VENDOR_ETHNICITY,'') as VENDOR_ETHNICITY,
NVL(a.VENDOR_ETHNIC_GROUP,'') as VENDOR_ETHNIC_GROUP,
NVL(a.VENDOR_LANGUAGE,'') AS VENDOR_LANGUAGE,
NVL(a.VENDOR_RELIGION,'') as VENDOR_RELIGION,
NVL(a.SHORT_PRIMARY_WEB_Address,'') AS SHORT_PRIMARY_WEB_Address,
NVL(a.LONG_LOCAL_WEB_ADDRESS,'') AS LONG_LOCAL_WEB_ADDRESS,
NVL(UPPER(a.COUPON_LINK),'') AS COUPON_LINK,
NVL(UPPER(a.TWITTER_LINK),'') AS TWITTER_LINK,
NVL(UPPER(a.LINKED_IN_LINK),'') AS LINKED_IN_LINK,
NVL(UPPER(a.FACEBOOK_LINK),'') AS FACEBOOK_LINK,
NVL(UPPER(a.ALTERNATE_SOCIAL_LINK),'') AS ALTERNATE_SOCIAL_LINK,
NVL(UPPER(a.YOU_TUBE_LINK),'') AS YOU_TUBE_LINK,
NVL(UPPER(a.LOGO_LINK),'') AS LOGO_LINK,
NVL(UPPER(a.GOOGLEPLUS_LINK),'') AS GOOGLEPLUS_LINK,
NVL(UPPER(a.PINTEREST_LINK),'') AS PINTEREST_LINK,
NVL(UPPER(a.MYSPACE_LINK),'') AS MYSPACE_LINK,
NVL(UPPER(a.FOURSQUARE),'') AS FOURSQUARE,
NVL(UPPER(a.YELP),'') AS YELP,
NVL(UPPER(a.INSTAGRAM_LINK),'') AS INSTAGRAM_LINK,
a.SQUAREFOOTAGE8 AS SQUAREFOOTAGE8,
NVL(a.POPCODE,'') AS POPCODE,
NVL(a.ECOMMERCEPRESENT,'') AS ECOMMERCEPRESENT,
NVL(a.GOOGECHECKOUT,'') AS GOOGECHECKOUT,
NVL(a.PAYPAL,'') AS PAYPAL,
NVL(a.GREENADOPTERSCORE,'') AS GREENADOPTERSCORE,
NVL(a.LOCATIONLINKAGEID,'') AS LOCATIONLINKAGEID,
NVL(a.LOCATIONLINKAGETYPE,'') AS LOCATIONLINKAGETYPE,
a.FLEETSIZE AS FLEETSIZE,
a.CHARITABLE_DONTATIONS_EXPENSE AS CHARITABLE_DONTATIONS_EXPENSE,
a.LICENSE_FEES_TAXES AS LICENSE_FEES_TAXES,
a.MAINTENANCE_REPAIR AS MAINTENANCE_REPAIR,
NVL(a.NBRC_NEW_ADD_DATE,'') AS NBRC_NEW_ADD_DATE,
NVL(a.NEW_TO_DATABASE_DATE,'') AS NEW_TO_DATABASE_DATE,
NVL(a.PROFESSIONAL_SIC_FLAG,'') AS PROFESSIONAL_SIC_FLAG,
NVL(a.LAST_VERIFICATION_DATE_LIMITED,'') AS LAST_VERIFICATION_DATE_LIMITED,
NVL(a.CONTACTID,'') AS CONTACTID,
a.TransportationExpenseCode AS TransportationExpenseCode,
a.PHONE_NUMBER_TYPE AS PHONE_NUMBER_TYPE,
NVL(a.CONTACTQUALITY,'') as CONTACTQUALITY,
NVL(a.DIGITALMATCH,'') as DIGITALMATCH,
NVL(a.Delivery_Date,'') AS Delivery_Date,
NVL(a.FUNCTIONAL_AREA_CODE,'') as FUNCTIONAL_AREA_CODE,
NVL(a.DEPARTMENT_CODE,'') as DEPARTMENT_CODE,
NVL(a.ROLE_CODE,'') as ROLE_CODE,
NVL(a.LEVEL_CODE,'') as LEVEL_CODE,
NVL(a.LiteralTitle_ID,'') as LiteralTitle_ID,
a.Inferred_Corporate_Employee_Count AS Inferred_Corporate_Employee_Count,
a.Inferred_Corporate_Employee_Range AS Inferred_Corporate_Employee_Range,
a.Inferred_Corporate_Sales_Volume_Amount AS Inferred_Corporate_Sales_Volume_Amount,
CASE WHEN LTRIM(RTRIM(a.Inferred_Corporate_Sales_Volume_Range))='' OR a.Inferred_Corporate_Sales_Volume_Range IS NULL
   THEN '*' ELSE a.Inferred_Corporate_Sales_Volume_Range END AS Inferred_Corporate_Sales_Volume_Range,
a.Inferred_Corporate_Employee_Source_Indicator AS Inferred_Corporate_Employee_Source_Indicator,
a.Inferred_Corporate_Sales_Volume_Source_Indicator AS Inferred_Corporate_Sales_Volume_Source_Indicator,
NVL(a.CHANGE_DATE,'') AS CHANGE_DATE,
NVL(a.TRANSACTION_DATE,'') AS TRANSACTION_DATE,
a.LEGAL_NAME AS LEGAL_NAME,
a.LAST_DATE AS LAST_DATE,
NVL(a.TYPECODE,'') AS TYPECODE,
NVL(a.CONTACTSOURCEDATE,'') AS CONTACTSOURCEDATE,
NVL(a.DISTRICTCODE,'') as DISTRICTCODE,
NVL(a.PREFERREDCORRESPONDENCE,'') AS PREFERREDCORRESPONDENCE,
NVL(a.CREDITRATINGCODE,'') AS CREDITRATINGCODE,
a.ACTUALEMPLOYEES AS ACTUALEMPLOYEES,
a.ACTUALSALES AS ACTUALSALES,
NVL(a.ADDRESSORIGINATIONDATE,'') AS ADDRESSORIGINATIONDATE,
NVL(a.BUSINESSNAMEORIGINATIONDATE,'') AS BUSINESSNAMEORIGINATIONDATE,
NVL(a.DATABASESEGMENTATIONCODE,'') AS DATABASESEGMENTATIONCODE,
NVL(a.GRADE,'') AS GRADE,
NVL(a.HOUSENUMBER,'') AS HOUSENUMBER,
NVL(a.LOCATIONEMPLOYEESIZE,'') AS LOCATIONEMPLOYEESIZE,
NVL(a.LOCATIONNAME,'') AS LOCATIONNAME,
CASE WHEN LTRIM(RTRIM(a.LOCATIONSALESVOLUME))='' OR a.LOCATIONSALESVOLUME is null THEN '*' ELSE a.LOCATIONSALESVOLUME END AS LOCATIONSALESVOLUME,
NVL(a.MAILINGDETAILFLAG,'') AS MAILINGDETAILFLAG,
NVL(a.MAILSCORE,'') AS MAILSCORE,
NVL(a.NEWTODATABASEDATE,'') AS NEWTODATABASEDATE,
NVL(a.PHONEORIGINATIONDATE,'') AS PHONEORIGINATIONDATE,
NVL(a.STREETNAME,'') AS STREETNAME,
NVL(a.STREETPOSTDIRECTIONAL,'') AS STREETPOSTDIRECTIONAL,
NVL(a.STREETPREDIRECTIONAL,'') AS STREETPREDIRECTIONAL,
NVL(a.STREETSUFFIX,'') AS STREETSUFFIX,
NVL(a.WEBSITEFLAG,'') AS WEBSITEFLAG,
NVL(a.UTILITYSOURCE,'') AS UTILITYSOURCE,
NVL(a.ACLFLAG,'') AS ACLFLAG,
NVL(a.AMIFLAG,'') AS AMIFLAG,
NVL(a.FEDERALCONTRACTORFLAG,'') AS FEDERALCONTRACTORFLAG,
NVL(a.CHANGEDTOOUTOFBUSINESSDATE,'') AS CHANGEDTOOUTOFBUSINESSDATE,
NVL(a.AMI_currentlinkagenumber,'') AS AMI_currentlinkagenumber,
NVL(a.AMI_typeofpractice,'') AS AMI_typeofpractice,
NVL(a.AMI_primaryspecialty,'') AS AMI_primaryspecialty,
NVL(a.AMI_secondaryspecialty,'') AS AMI_secondaryspecialty,
NVL(a.AMI_boardcertifiedindicator,'') AS AMI_boardcertifiedindicator,
CASE WHEN (a.AMI_dateofbirth is NOT NULL and AMI_dateofbirth <> '' ) THEN Right(NVL(a.AMI_dateofbirth,''),4) ELSE NVL(a.AMI_dateofbirth,'') END AS AMI_dateofbirth,
NVL(a.AMI_yearofgraduation,'') AS AMI_yearofgraduation,
NVL(a.AMI_medicalschoolcode_0,'') AS AMI_medicalschoolcode_0,
NVL(a.AMI_officemanagerlastname,'') AS AMI_officemanagerlastname,
NVL(a.AMI_officemanagerfirstname,'') AS AMI_officemanagerfirstname,
NVL(a.AMI_professionaldegreecode,'') AS AMI_professionaldegreecode,
NVL(a.AMI_addresstype,'') AS AMI_addresstype,
NVL(a.AMI_upin,'') AS AMI_upin,
NVL(a.AMI_deanumber,'') AS AMI_deanumber,
NVL(a.AMI_sizegrouppractice,'') AS AMI_sizegrouppractice,
NVL(a.AMI_hospitalnumber,'') AS AMI_hospitalnumber,
NVL(a.AMI_numberofnurses,'') AS AMI_numberofnurses,
NVL(a.AMI_nursepractitioners,'') AS AMI_nursepractitioners,
NVL(a.AMI_numberofchairs,'') AS AMI_numberofchairs,
NVL(a.AMI_Lic_stateoflicense,'') AS AMI_Lic_stateoflicense,
NVL(a.AMI_Lic_expirationdate,'') AS AMI_Lic_expirationdate,
NVL(a.AMI_Lic_licenseboardtype,'') AS AMI_Lic_licenseboardtype,
NVL(a.AMI_Lic_licensenumber,'') AS AMI_Lic_licensenumber,
NVL(a.AMI_networkcode,'') AS AMI_networkcode,
NVL(a.AMI_associationcode,'') AS AMI_associationcode,
NVL(a.AMI_npi,'') AS AMI_npi,
NVL(a.AMI_prescriptionsperwk,'') AS AMI_prescriptionsperwk,
NVL(a.AMI_primarywebaddressflag,'') AS AMI_primarywebaddressflag,
NVL(a.AMI_activewebaddressflag,'') AS AMI_activewebaddressflag,
NVL(a.ACL_groupcode,'') AS ACL_groupcode,
NVL(a.ACL_denominationcode,'') AS ACL_denominationcode,
NVL(a.ACL_buyercode1,'') AS ACL_buyercode1,
NVL(a.ACL_buyercode2,'') AS ACL_buyercode2,
NVL(a.ACL_buyercode3,'') AS ACL_buyercode3,
NVL(a.ACL_buyercode4,'') AS ACL_buyercode4,
NVL(a.ACL_buyercode5,'') AS ACL_buyercode5,
NVL(a.ACL_buyercode6,'') AS ACL_buyercode6,
NVL(a.ACL_buyercode7,'') AS ACL_buyercode7,
NVL(a.ACL_buyercode8,'') AS ACL_buyercode8,
NVL(a.ACL_buyercode9,'') AS ACL_buyercode9,
NVL(a.ACL_buyercode10,'') AS ACL_buyercode10,
NVL(a.ACL_buyercode11,'') AS ACL_buyercode11,
NVL(a.ACL_buyercode12,'') AS ACL_buyercode12,
NVL(a.ACL_buyercode13,'') AS ACL_buyercode13,
NVL(a.ACL_buyercode14,'') AS ACL_buyercode14,
NVL(a.ACL_buyercode15,'') AS ACL_buyercode15,
NVL(a.ACL_buyercode16,'') AS ACL_buyercode16,
NVL(a.ACL_buyercode17,'') AS ACL_buyercode17,
NVL(a.ACL_buyercode18,'') AS ACL_buyercode18,
NVL(a.ACL_buyercode19,'') AS ACL_buyercode19,
NVL(a.ACL_buyercode20,'') AS ACL_buyercode20,
NVL(a.ACL_buyercode21,'') AS ACL_buyercode21,
NVL(a.ACL_buyercode22,'') AS ACL_buyercode22,
NVL(a.ACL_buyercode23,'') AS ACL_buyercode23,
NVL(a.ACL_buyercode24,'') AS ACL_buyercode24,
NVL(a.ACL_buyercode25,'') AS ACL_buyercode25,
NVL(a.ACL_buyercode26,'') AS ACL_buyercode26,
NVL(a.ACL_buyercode27,'') AS ACL_buyercode27,
NVL(a.ACL_buyercode28,'') AS ACL_buyercode28,
NVL(a.ACL_buyercode29,'') AS ACL_buyercode29,
NVL(a.ACL_buyercode30,'') AS ACL_buyercode30,
NVL(a.ACL_buyercode31,'') AS ACL_buyercode31,
NVL(a.ACL_buyercode32,'') AS ACL_buyercode32,
NVL(a.ACL_churchsizecode,'') AS ACL_churchsizecode,
NVL(a.ACL_churchsize,'') AS ACL_churchsize,
NVL(a.ACL_attendancecode,'') AS ACL_attendancecode,
NVL(a.ACL_attendance,'') AS ACL_attendance,
NVL(a.ACL_schoolsizecode,'') AS ACL_schoolsizecode,
NVL(a.ACL_raceofcongregation1,'') AS ACL_raceofcongregation1,
NVL(a.ACL_raceofcongregation2,'') AS ACL_raceofcongregation2,
NVL(a.ACL_raceofcongregation3,'') AS ACL_raceofcongregation3,
NVL(a.ACL_raceofcongregation4,'') AS ACL_raceofcongregation4,
NVL(a.ACL_raceofcongregation5,'') AS ACL_raceofcongregation5,
NVL(a.ACL_raceofcongregation6,'') AS ACL_raceofcongregation6,
NVL(a.ACL_membershipsourceflag,'') AS ACL_membershipsourceflag,
NVL(a.ACL_multiplecongregationscode,'') AS ACL_multiplecongregationscode,
NVL(a.ACL_newconstructionlastverificationdate,'') AS ACL_newconstructionlastverificationdate,
NVL(a.Countrycode,'') AS Countrycode,
NVL(a.DMAcode,'') AS DMAcode,
NVL(a.Changedtoverifieddate,'') AS Changedtoverifieddate,
NVL(a.Changedtosuspectdate,'') AS Changedtosuspectdate,
NVL(a.Infoscore,'') AS Infoscore,
NVL(a.Industrygrowthscore,'') AS Industrygrowthscore,
NVL(a.Completenessscore,'') AS Completenessscore,
NVL(a.Stabilityscore,'') AS Stabilityscore,
NVL(a.Reachabilityscore,'') AS Reachabilityscore,
NVL(a.Infograde,'') AS Infograde,
NVL(a.IndustrygrowthGrade,'') AS IndustrygrowthGrade,
NVL(a.CompletenessGrade,'') AS CompletenessGrade,
NVL(a.StabilityGrade,'') AS StabilityGrade,
NVL(a.ReachabilityGrade,'') AS ReachabilityGrade,
NVL(a.AMI_Boardcertificationcount,'') AS AMI_Boardcertificationcount,
NVL(a.AMI_MedicareAccepted,'') AS AMI_MedicareAccepted,
NVL(a.AMI_AcceptingNewPatients,'') AS AMI_AcceptingNewPatients,
NVL(a.NameStandardizationFlag,'') AS NameStandardizationFlag,
NVL(a.TIMEZONE,'') AS TIMEZONE,
NVL(a.Homeaddress,'') AS Homeaddress,
NVL(a.Homecity,'') AS Homecity,
NVL(a.Homestate,'') AS Homestate,
NVL(a.Homezipcode,'') AS Homezipcode,
NVL(a.Homezip4,'') AS Homezip4,
NVL(a.Homeareacode,'') AS Homeareacode,
NVL(a.Homephonenumber,'') AS Homephonenumber,
NVL(a.Donotcallflag,'') AS Donotcallflag,
NVL(a.Homecountycode,'') AS Homecountycode,
NVL(a.Homelocationtype,'') AS Homelocationtype,
NVL(a.Execgender,'') AS Execgender,
NVL(a.Execage,'') AS Execage,
NVL(a.Execincome,'') AS Execincome,
NVL(a.Homeowner,'') AS Homeowner,
NVL(a.Maritalstatus,'') AS Maritalstatus,
NVL(a.Job_Function_ID,'') AS Job_Function_ID,
NVL(a.Management_Level,'') AS Management_Level,
NVL(a.Job_Title,'') AS Job_Title,
NVL(a.EMPLOYEESIZECODE1,'') AS EMPLOYEESIZECODE1,
NVL(a.OUTPUTVOLUME1,'') AS OUTPUTVOLUME1,
NVL(a.OUTPUTVOLUMECODE1,'') AS OUTPUTVOLUMECODE1,
NVL(a.BANKASSETCODE,'') AS BANKASSETCODE,
NVL(a.CORPORATEEMPLOYEES,'') AS CORPORATEEMPLOYEES,
NVL(a.CORPORATEOUTPUTVOLUME,'') AS CORPORATEOUTPUTVOLUME,
NVL(a.CORPORATESALESVOLUME,'') AS CORPORATESALESVOLUME,
NVL(a.fLATITUDE_old,'') AS fLATITUDE_old,
NVL(a.fLONGITUDE_OLD,'') AS fLONGITUDE_OLD,
NVL(a.FullName, '') AS FullName,
a.One_per_ABI AS One_per_ABI,
NVL(a.One_per_ABIName, '') AS One_per_ABIName,
a.Name_Available AS Name_Available,
a.Company_Available AS Company_Available,
a.ABI_Available AS ABI_Available,
CASE WHEN LTRIM(RTRIM(a.PhoneNumber)) Like '%0001111' THEN 'N' ELSE a.Phone_Number_Available END AS Phone_Number_Available,
a.City_Available AS City_Available,
a.Website_Available AS Website_Available,
NVL(a.EIN_Available,'') AS EIN_Available,
NVL(a.One_per_Contact_Name, '') AS One_per_Contact_Name,
NVL(a.One_Per_Company_Name_Title, '') AS One_Per_Company_Name_Title,
NVL(a.Contacts_Per_Company, '') AS Contacts_Per_Company,
NVL(a.ZipRadius,'') AS ZipRadius,
NVL(a.GeoRadius,'') AS GeoRadius,
NVL(a.One_Per_Address_Company,'') AS One_Per_Address_Company,
NVL(a.PRESENCE_OF_LATITUDE,'') AS PRESENCE_OF_LATITUDE,
NVL(a.PRESENCE_OF_LONGITUDE,'') AS PRESENCE_OF_LONGITUDE,
a.Creditcardsaccepted AS Creditcardsaccepted,
case when a.Creditcardsaccepted = '' THEN '' else a.Creditcardsaccepted_Multi end AS Creditcardsaccepted_Multi,
NVL(a.PARENTABINUMBER_Back,'') AS PARENTABINUMBER_Back,
a.haspostal AS Haspostal,
16771 as Listid,
'R' as PermissionType,
NVL(a.Vendor_ID,'') AS Vendor_ID,
NVL(a.Geo_Match_Level,'') AS Geo_Match_Level,
NVL(a.Database_Flag,'') AS Database_Flag,
NVL(a.Work_At_Home_Indicator,'') AS Work_At_Home_Indicator,
NVL(a.TITLECODE_Back,'') AS TITLECODE_Back,
CASE WHEN a.ACL_BuyerCode IS NULL THEN ''
     WHEN a.ACL_BuyerCode <>'' and a.ACL_BuyerCode is not null THEN a.ACL_BuyerCode +',' 
     ELSE a.ACL_BuyerCode end AS ACL_BuyerCode,
NVL(a.EmailAddress,'') as EmailAddress,
NVL(a.cDomain,'') AS cDomain,
NVL(a.BadEmails,'') as BadEmails,
NVL(a.Royalty_Emails,'') AS Royalty_Emails,
NVL(a.Infogroup_Emails,'') AS Infogroup_Emails,
NVL(a.cInclude,'') as cInclude,
NVL(a.MD5Upper,'') as MD5Upper,
NVL(a.MD5Lower,'') as MD5Lower,
NVL(a.MD5SaltedHash,'') as MD5SaltedHash,
NVL(a.SHA256Lower,'') AS SHA256Lower,
NVL(a.SHA256Upper,'') AS SHA256Upper,
NVL(a.BVT_EMAIL_STATUS_Email,'') AS BVT_EMAIL_STATUS_Email,
NVL(a.Bridge_Code,'') AS Bridge_Code,
NVL(a.Domain_ID,'') AS Domain_ID,
NVL(a.TopLevelDomain,'') AS TopLevelDomain,
NVL(a.Email_Marketable,'') AS Email_Marketable,
NVL(a.Email_Deliverable,'') AS Email_Deliverable,
NVL(a.Email_Reputation_Risk,'') AS Email_Reputation_Risk,
NVL(a.DEPARTMENT_CODE_Email,'') AS DEPARTMENT_CODE_Email,
NVL(a.DEPARTMENT_CODE_MULTI_Email,'') AS DEPARTMENT_CODE_MULTI_Email,
NVL(a.FRANCHISE_CODE_Email,'') AS FRANCHISE_CODE_Email,
NVL(a.INDIVIDUAL_FIRM_Email,'') AS INDIVIDUAL_FIRM_Email,
NVL(a.JOB_LEVEL_CODE_Email,'') AS JOB_LEVEL_CODE_Email,
NVL(a.JOB_LEVEL_CODE_MULTI_Email,'') AS JOB_LEVEL_CODE_MULTI_Email,
NVL(a.MAIL_SCORE_Email,'') AS MAIL_SCORE_Email,
NVL(a.ONEPERFLAG_Email,'') AS ONEPERFLAG_Email,
NVL(a.ONE_PER_ABI_EMAIL_Email,'') AS ONE_PER_ABI_EMAIL_Email,
NVL(a.ONE_PER_COMPANY_Email,'') AS ONE_PER_COMPANY_Email,
NVL(a.ONE_PER__ABI_Email,'') AS ONE_PER__ABI_Email,
NVL(a.PRODUCTCODE_Email,'') AS PRODUCTCODE_Email,
NVL(a.RESPONDER_DATE_Email,'') AS RESPONDER_DATE_Email,
NVL(a.SEQ_Email,'') AS SEQ_Email,
NVL(a.SUPPRESSION_TYPE_Email,'') AS SUPPRESSION_TYPE_Email,
CASE WHEN NVL(a.LiteralTitle_ID,'') = i.cCode then NVL(i.cDescription,'') 
     else Nvl(a.TITLE_DESCRIPTION_Email,'') end as TITLE_DESCRIPTION_Email,
NVL(a.TITLE_RANK_Email,'') AS TITLE_RANK_Email,
NVL(a.TRANSACTION_DATE_Email,'') AS TRANSACTION_DATE_Email,
NVL(a.TRANSACTION_TYPE_Email,'') AS TRANSACTION_TYPE_Email,
NVL(a.ULTIMATE_NUMBER_Email,'') AS ULTIMATE_NUMBER_Email,
NVL(a.YEAR_SIC_ADDED_Email,'') AS YEAR_SIC_ADDED_Email,
NVL(a.AdditionalEmailFlag_Email,'') AS AdditionalEmailFlag_Email,
LEFT(LEFT(a.ZIP9,6),3) as SCF,
CASE WHEN LEN(LEFT(a.ZIP9,6)) =5 THEN RIGHT(LEFT(a.ZIP9,6), 1) ELSE '' END as ZIP_END,
NVL(h.APPLICATION_A,'') as APPLICATION_A,
NVL(h.APPLICATION_B,'') as APPLICATION_B,
NVL(h.APPLICATION_C,'') as APPLICATION_C,
NVL(h.APPLICATION_E,'') as APPLICATION_E,
NVL(h.APPLICATION_F,'') as APPLICATION_F,
NVL(h.APPLICATION_G,'') as APPLICATION_G,
CASE WHEN a.ContactID = C.ContactID AND C.cValue = 'H' THEN ISNULL(C.cValue,'') ELSE NVL(h.APPLICATION_H,'') END AS APPLICATION_H,
NVL(h.APPLICATION_I,'') as APPLICATION_I,
NVL(h.APPLICATION_J,'') as APPLICATION_J,
NVL(h.APPLICATION_K,'') as APPLICATION_K,
NVL(h.APPLICATION_L,'') as APPLICATION_L,
NVL(h.APPLICATION_M,'') as APPLICATION_M,
NVL(h.APPLICATION_N,'') as APPLICATION_N,
NVL(h.APPLICATION_P,'') as APPLICATION_P,
NVL(h.SEGMENTCODE_1,'') AS SEGMENTCODE_1,
NVL(h.SEGMENTCODE_2,'') AS SEGMENTCODE_2,
CASE WHEN a.ContactID = D.ContactID AND D.cValue = '3' THEN ISNULL(D.cValue,'') ELSE NVL(h.SEGMENTCODE_3,'') END AS SEGMENTCODE_3,
NVL(h.SEGMENTCODE_4,'') AS SEGMENTCODE_4,
NVL(h.SEGMENTCODE_5,'') AS SEGMENTCODE_5,
NVL(h.SEGMENTCODE_6,'') AS SEGMENTCODE_6,
CASE WHEN a.ContactID = e.ContactID AND e.cValue = '7' THEN ISNULL(e.cValue,'') ELSE NVL(h.SEGMENTCODE_7,'') END AS SEGMENTCODE_7,
NVL(h.SEGMENTCODE_8,'') AS SEGMENTCODE_8,
NVL(h.SEGMENTCODE_9,'') AS SEGMENTCODE_9,
NVL(h.SEGMENTCODE_A,'') AS SEGMENTCODE_A,
NVL(h.SEGMENTCODE_F,'') AS SEGMENTCODE_F,
NVL(h.SEGMENTCODE_H,'') AS SEGMENTCODE_H,
NVL(h.SEGMENTCODE_I,'') AS SEGMENTCODE_I,
CASE WHEN (a.NBRC_NEW_ADD_DATE     is NULL OR a.NBRC_NEW_ADD_DATE ='00000000'  )   THEN '' ELSE LEFT (a.NBRC_NEW_ADD_DATE,6) END AS NBRC_NEW_ADD_DATE_YYYYMM,
CASE WHEN (a.NEW_TO_DATABASE_DATE  is NULL OR a.NEW_TO_DATABASE_DATE ='00000000' ) THEN '' ELSE LEFT (a.NEW_TO_DATABASE_DATE,6) END AS NEW_TO_DATABASE_DATE_YYYYMM,
CASE WHEN (a.TRANSACTION_DATE  is NULL OR a.TRANSACTION_DATE ='00000000' ) THEN '' ELSE LEFT (a.TRANSACTION_DATE,6) END AS TRANSACTION_DATE_YYYYMM,
CASE WHEN a.PHONENUMBER IS NOT NULL THEN left(a.PHONENUMBER,3) 
   ELSE '' END AS AreaCode,
CASE WHEN (a.FAXPHONE  is NULL OR LTRIM(RTRIM(a.FAXPHONE)) ='')  THEN 'N'  ELSE 'Y' END AS FaxAvailable,
NVL(a.State,'') + NVL(a.CountyCode,'') AS StateCOUNTYCODE,
NVL(LTRIM(RTRIM(LEFT(a.ZIP9,6))),'') + NVL(LTRIM(RTRIM(a.CARRIERROUTECODE)),'') AS ZipCarrierRoute,
NVL(a.PRIMARYSIC6,'') + NVL(a.FRANCHISE_CODE_1,'') AS PrimarySIC6Franchise,
CASE WHEN a.PRIMARYSIC6 IN ('602103','784108','598406','738905','554112','735938','573136') THEN 'Y' ELSE 'N' END AS Kiosks_Flag,
REPLACE(NVL(a.ADDRESS,'') + NVL(a.CITY,'') + NVL(a.STATE,'') + NVL(LEFT(a.ZIP9,6),''), ' ', '') AS HardKey,
CASE WHEN a.Address LIKE '%PO BOX%' THEN 'Y' ELSE 'N' END AS POBOX_FLAG,
NVL(a.ParkSuppression,'') AS ParkSuppression,
NVL(a.ADDRESS,'') AS AddressLine1,
NVL(a.AddressLine2,'') AS AddressLine2,
LEFT(CASE WHEN LTRIM(RTRIM(a.PhoneNumber)) Like '%0001111' THEN '' ELSE a.PhoneNumber end,6) AS AreaCode_Prefix,
NVL(LTRIM(RTRIM(a.ADDRESS)),'') + NVL(LTRIM(RTRIM(a.ZIP9)),'') AS One_Per_Address,
CASE WHEN (a.EXECUTIVESOURCECODE = '36' OR a.EXECUTIVESOURCECODE IS NULL OR a.EXECUTIVESOURCECODE = '') THEN 'Y' ELSE 'N' END AS InfogroupContact,
CASE WHEN (a.EXECUTIVESOURCECODE = '36' OR a.EXECUTIVESOURCECODE IS NULL OR a.EXECUTIVESOURCECODE = '') AND a.Vendor_ID  ='36' THEN 'Y' ELSE 'N' END AS InfogroupContactAndEmail,
CASE WHEN (a.MAILCONFIDENCE IN ('1') OR a.MAILCONFIDENCE_MAILING IN ('1'))  AND a.MailScoreCombined ='' THEN '1'
     WHEN (a.MAILCONFIDENCE IN ('2') OR a.MAILCONFIDENCE_MAILING IN ('2'))  AND a.MailScoreCombined ='' THEN '2' 
     WHEN (a.MAILCONFIDENCE IN ('3') OR a.MAILCONFIDENCE_MAILING IN ('3'))  AND a.MailScoreCombined ='' THEN '3' 
     WHEN (a.MAILCONFIDENCE IN ('4') OR a.MAILCONFIDENCE_MAILING IN ('4'))  AND a.MailScoreCombined ='' THEN '4' 
     WHEN (a.MAILCONFIDENCE IN ('5') OR a.MAILCONFIDENCE_MAILING IN ('5'))  AND a.MailScoreCombined ='' THEN '5' 
     WHEN (a.MAILCONFIDENCE IN ('0') OR a.MAILCONFIDENCE_MAILING IN ('0'))  AND a.MailScoreCombined ='' THEN '0' else '' END AS MailScoreCombined,
CASE WHEN a.STATE ='AB' THEN '48'
     WHEN a.STATE ='AK' THEN '02'
     WHEN a.STATE ='AL' THEN '01'
     WHEN a.STATE ='AR' THEN '05'
     WHEN a.STATE ='AZ' THEN '04'
     WHEN a.STATE ='BC' THEN '59'
     WHEN a.STATE ='CA' THEN '06'
     WHEN a.STATE ='CO' THEN '08'
     WHEN a.STATE ='CT' THEN '09'
     WHEN a.STATE ='DC' THEN '11'
     WHEN a.STATE ='DE' THEN '10'
     WHEN a.STATE ='FL' THEN '12'
     WHEN a.STATE ='FM' THEN '64'
     WHEN a.STATE ='GA' THEN '13'
     WHEN a.STATE ='GU' THEN '66'
     WHEN a.STATE ='HI' THEN '15'
     WHEN a.STATE ='IA' THEN '19'
     WHEN a.STATE ='ID' THEN '16'
     WHEN a.STATE ='IL' THEN '17'
     WHEN a.STATE ='IN' THEN '18'
     WHEN a.STATE ='KS' THEN '20'
     WHEN a.STATE ='KY' THEN '21'
     WHEN a.STATE ='LA' THEN '22'
     WHEN a.STATE ='MA' THEN '25'
     WHEN a.STATE ='MB' THEN '46'
     WHEN a.STATE ='MD' THEN '24'
     WHEN a.STATE ='ME' THEN '23'
     WHEN a.STATE ='MH' THEN '68'
     WHEN a.STATE ='MI' THEN '26'
     WHEN a.STATE ='MN' THEN '27'
     WHEN a.STATE ='MO' THEN '29'
     WHEN a.STATE ='MP' THEN '69'
     WHEN a.STATE ='MS' THEN '28'
     WHEN a.STATE ='MT' THEN '30'
     WHEN a.STATE ='NB' THEN '13'
     WHEN a.STATE ='NC' THEN '37'
     WHEN a.STATE ='ND' THEN '38'
     WHEN a.STATE ='NE' THEN '31'
     WHEN a.STATE ='NH' THEN '33'
     WHEN a.STATE ='NJ' THEN '34'
     WHEN a.STATE ='NL' THEN '10'
     WHEN a.STATE ='NM' THEN '35'
     WHEN a.STATE ='NS' THEN '12'
     WHEN a.STATE ='NT' THEN '61'
     WHEN a.STATE ='NU' THEN '62'
     WHEN a.STATE ='NV' THEN '32'
     WHEN a.STATE ='NY' THEN '36'
     WHEN a.STATE ='OH' THEN '39'
     WHEN a.STATE ='OK' THEN '40'
     WHEN a.STATE ='ON' THEN '35'
     WHEN a.STATE ='OR' THEN '41'
     WHEN a.STATE ='PA' THEN '42'
     WHEN a.STATE ='PE' THEN '11'
     WHEN a.STATE ='PR' THEN '72'
     WHEN a.STATE ='PW' THEN '70'
     WHEN a.STATE ='QC' THEN '24'
     WHEN a.STATE ='RI' THEN '44'
     WHEN a.STATE ='SC' THEN '45'
     WHEN a.STATE ='SD' THEN '46'
     WHEN a.STATE ='SK' THEN '47'
     WHEN a.STATE ='TN' THEN '47'
     WHEN a.STATE ='TX' THEN '48'
     WHEN a.STATE ='UT' THEN '49'
     WHEN a.STATE ='VA' THEN '51'
     WHEN a.STATE ='VI' THEN '78'
     WHEN a.STATE ='VT' THEN '50'
     WHEN a.STATE ='WA' THEN '53'
     WHEN a.STATE ='WI' THEN '55'
     WHEN a.STATE ='WV' THEN '54'
     WHEN a.STATE ='WY' THEN '56'
     WHEN a.STATE ='YT' THEN '60'
     ELSE '' END AS Census_State_Code_2010,
a.STATECODE AS STATECODE,
CASE WHEN a.MAILING_STATE ='AB' THEN '48'
     WHEN a.MAILING_STATE ='AK' THEN '02'
     WHEN a.MAILING_STATE ='AL' THEN '01'
     WHEN a.MAILING_STATE ='AR' THEN '05'
     WHEN a.MAILING_STATE ='AZ' THEN '04'
     WHEN a.MAILING_STATE ='BC' THEN '59'
     WHEN a.MAILING_STATE ='CA' THEN '06'
     WHEN a.MAILING_STATE ='CO' THEN '08'
     WHEN a.MAILING_STATE ='CT' THEN '09'
     WHEN a.MAILING_STATE ='DC' THEN '11'
     WHEN a.MAILING_STATE ='DE' THEN '10'
     WHEN a.MAILING_STATE ='FL' THEN '12'
     WHEN a.MAILING_STATE ='FM' THEN '64'
     WHEN a.MAILING_STATE ='GA' THEN '13'
     WHEN a.MAILING_STATE ='GU' THEN '66'
     WHEN a.MAILING_STATE ='HI' THEN '15'
     WHEN a.MAILING_STATE ='IA' THEN '19'
     WHEN a.MAILING_STATE ='ID' THEN '16'
     WHEN a.MAILING_STATE ='IL' THEN '17'
     WHEN a.MAILING_STATE ='IN' THEN '18'
     WHEN a.MAILING_STATE ='KS' THEN '20'
     WHEN a.MAILING_STATE ='KY' THEN '21'
     WHEN a.MAILING_STATE ='LA' THEN '22'
     WHEN a.MAILING_STATE ='MA' THEN '25'
     WHEN a.MAILING_STATE ='MB' THEN '46'
     WHEN a.MAILING_STATE ='MD' THEN '24'
     WHEN a.MAILING_STATE ='ME' THEN '23'
     WHEN a.MAILING_STATE ='MH' THEN '68'
     WHEN a.MAILING_STATE ='MI' THEN '26'
     WHEN a.MAILING_STATE ='MN' THEN '27'
     WHEN a.MAILING_STATE ='MO' THEN '29'
     WHEN a.MAILING_STATE ='MP' THEN '69'
     WHEN a.MAILING_STATE ='MS' THEN '28'
     WHEN a.MAILING_STATE ='MT' THEN '30'
     WHEN a.MAILING_STATE ='NB' THEN '13'
     WHEN a.MAILING_STATE ='NC' THEN '37'
     WHEN a.MAILING_STATE ='ND' THEN '38'
     WHEN a.MAILING_STATE ='NE' THEN '31'
     WHEN a.MAILING_STATE ='NH' THEN '33'
     WHEN a.MAILING_STATE ='NJ' THEN '34'
     WHEN a.MAILING_STATE ='NL' THEN '10'
     WHEN a.MAILING_STATE ='NM' THEN '35'
     WHEN a.MAILING_STATE ='NS' THEN '12'
     WHEN a.MAILING_STATE ='NT' THEN '61'
     WHEN a.MAILING_STATE ='NU' THEN '62'
     WHEN a.MAILING_STATE ='NV' THEN '32'
     WHEN a.MAILING_STATE ='NY' THEN '36'
     WHEN a.MAILING_STATE ='OH' THEN '39'
     WHEN a.MAILING_STATE ='OK' THEN '40'
     WHEN a.MAILING_STATE ='ON' THEN '35'
     WHEN a.MAILING_STATE ='OR' THEN '41'
     WHEN a.MAILING_STATE ='PA' THEN '42'
     WHEN a.MAILING_STATE ='PE' THEN '11'
     WHEN a.MAILING_STATE ='PR' THEN '72'
     WHEN a.MAILING_STATE ='PW' THEN '70'
     WHEN a.MAILING_STATE ='QC' THEN '24'
     WHEN a.MAILING_STATE ='RI' THEN '44'
     WHEN a.MAILING_STATE ='SC' THEN '45'
     WHEN a.MAILING_STATE ='SD' THEN '46'
     WHEN a.MAILING_STATE ='SK' THEN '47'
     WHEN a.MAILING_STATE ='TN' THEN '47'
     WHEN a.MAILING_STATE ='TX' THEN '48'
     WHEN a.MAILING_STATE ='UT' THEN '49'
     WHEN a.MAILING_STATE ='VA' THEN '51'
     WHEN a.MAILING_STATE ='VI' THEN '78'
     WHEN a.MAILING_STATE ='VT' THEN '50'
     WHEN a.MAILING_STATE ='WA' THEN '53'
     WHEN a.MAILING_STATE ='WI' THEN '55'
     WHEN a.MAILING_STATE ='WV' THEN '54'
     WHEN a.MAILING_STATE ='WY' THEN '56'
     WHEN a.MAILING_STATE ='YT' THEN '60'
     ELSE '' END AS MAILING_STATECODE,
a.COUNTYCODEBYSTATECODE AS COUNTYCODEBYSTATECODE,
LEFT(NVL(a.State,'') + NVL(a.City,''), 50) AS CITYBYSTATE,
NVL(a.STATE_COUNTY_CENSUSTRACT_BLOCK,'') AS STATE_COUNTY_CENSUSTRACT_BLOCK,
LEFT(a.NAICSCODE,2) AS NAICS2,
LEFT(a.NAICSCODE,4) AS NAICS4,
LEFT(a.NAICSCODE,6) AS NAICS6,
CASE WHEN a.State in ('FM','GU','MH','MP','PR','PW','VI') THEN 'Y' ELSE 'N' END AS USTerritoryFlag,
NVL(a.state+F.cCounty,'') AS StateCountyName,
NVL(a.STATE,'') + NVL(LTRIM(RTRIM(UPPER(a.CITY))),'') + NVL(LEFT(a.ZIP9,6),'') AS StateCityZip,
NVL(a.STATE,'') + NVL(LTRIM(RTRIM(UPPER(a.CITY))),'') + NVL(LEFT(LEFT(a.ZIP9,6),3),'') AS StateCitySCF,
NVL(a.UNIQUEPROFESSIONALGUI,'') AS UNIQUEPROFESSIONALGUI,
CASE WHEN (a.TITLECODE_back ='C' OR a.TITLECODE ='C') AND a.TitleCodePriority is NULL THEN 1 
  WHEN (a.TITLECODE_back ='1' OR a.TITLECODE ='1') AND a.TitleCodePriority is NULL THEN 2 
  WHEN (a.TITLECODE_back ='9' OR a.TITLECODE ='9') AND a.TitleCodePriority is NULL THEN 3 
  WHEN (a.TITLECODE_back ='2' OR a.TITLECODE ='2') AND a.TitleCodePriority is NULL THEN 4 
  WHEN (a.TITLECODE_back ='I' OR a.TITLECODE ='I') AND a.TitleCodePriority is NULL THEN 5 
  WHEN (a.TITLECODE_back ='J' OR a.TITLECODE ='J') AND a.TitleCodePriority is NULL THEN 6 
  WHEN (a.TITLECODE_back ='K' OR a.TITLECODE ='K') AND a.TitleCodePriority is NULL THEN 7 
  WHEN (a.TITLECODE_back ='4' OR a.TITLECODE ='4') AND a.TitleCodePriority is NULL THEN 8 
  WHEN (a.TITLECODE_back ='7' OR a.TITLECODE ='7') AND a.TitleCodePriority is NULL THEN 9 
  WHEN (a.TITLECODE_back ='5' OR a.TITLECODE ='5') AND a.TitleCodePriority is NULL THEN 10 
  WHEN (a.TITLECODE_back ='6' OR a.TITLECODE ='6') AND a.TitleCodePriority is NULL THEN 11 
  WHEN (a.TITLECODE_back ='8' OR a.TITLECODE ='8') AND a.TitleCodePriority is NULL THEN 12 
  WHEN (a.TITLECODE_back ='(' OR a.TITLECODE ='(') AND a.TitleCodePriority is NULL THEN 13 
  WHEN (a.TITLECODE_back ='{' OR a.TITLECODE ='{') AND a.TitleCodePriority is NULL THEN 14 
  WHEN (a.TITLECODE_back ='>' OR a.TITLECODE ='>') AND a.TitleCodePriority is NULL THEN 15 
  WHEN (a.TITLECODE_back ='_' OR a.TITLECODE ='_') AND a.TitleCodePriority is NULL THEN 16 
  WHEN (a.TITLECODE_back ='?' OR a.TITLECODE ='?') AND a.TitleCodePriority is NULL THEN 17 
  WHEN (a.TITLECODE_back ='3' OR a.TITLECODE ='3') AND a.TitleCodePriority is NULL THEN 18 
  WHEN (a.TITLECODE_back ='X' OR a.TITLECODE ='X') AND a.TitleCodePriority is NULL THEN 19 
  WHEN (a.TITLECODE_back ='A' OR a.TITLECODE ='A') AND a.TitleCodePriority is NULL THEN 20 
  WHEN (a.TITLECODE_back ='W' OR a.TITLECODE ='W') AND a.TitleCodePriority is NULL THEN 21 
  WHEN (a.TITLECODE_back ='E' OR a.TITLECODE ='E') AND a.TitleCodePriority is NULL THEN 22 
  WHEN (a.TITLECODE_back ='F' OR a.TITLECODE ='F') AND a.TitleCodePriority is NULL THEN 23 
  WHEN (a.TITLECODE_back ='L' OR a.TITLECODE ='L') AND a.TitleCodePriority is NULL THEN 24 
  WHEN (a.TITLECODE_back ='$' OR a.TITLECODE ='$') AND a.TitleCodePriority is NULL THEN 25 
  WHEN (a.TITLECODE_back ='@' OR a.TITLECODE ='@') AND a.TitleCodePriority is NULL THEN 26 
  WHEN (a.TITLECODE_back ='P' OR a.TITLECODE ='P') AND a.TitleCodePriority is NULL THEN 27 
  WHEN (a.TITLECODE_back ='T' OR a.TITLECODE ='T') AND a.TitleCodePriority is NULL THEN 28 
  WHEN (a.TITLECODE_back ='%' OR a.TITLECODE ='%') AND a.TitleCodePriority is NULL THEN 29 
  WHEN (a.TITLECODE_back ='R' OR a.TITLECODE ='R') AND a.TitleCodePriority is NULL THEN 30 
  WHEN (a.TITLECODE_back =')' OR a.TITLECODE =')') AND a.TitleCodePriority is NULL THEN 31 
  WHEN (a.TITLECODE_back ='O' OR a.TITLECODE ='O') AND a.TitleCodePriority is NULL THEN 32 
  WHEN (a.TITLECODE_back ='H' OR a.TITLECODE ='H') AND a.TitleCodePriority is NULL THEN 33 
  WHEN (a.TITLECODE_back ='G' OR a.TITLECODE ='G') AND a.TitleCodePriority is NULL THEN 34 
  WHEN (a.TITLECODE_back ='&' OR a.TITLECODE ='&') AND a.TitleCodePriority is NULL THEN 35 
  WHEN (a.TITLECODE_back ='S' OR a.TITLECODE ='S') AND a.TitleCodePriority is NULL THEN 36 
  WHEN (a.TITLECODE_back ='N' OR a.TITLECODE ='N') AND a.TitleCodePriority is NULL THEN 37 
  WHEN (a.TITLECODE_back ='=' OR a.TITLECODE ='=') AND a.TitleCodePriority is NULL THEN 38 
  WHEN (a.TITLECODE_back ='M' OR a.TITLECODE ='M') AND a.TitleCodePriority is NULL THEN 39 
  WHEN (a.TITLECODE_back ='V' OR a.TITLECODE ='V') AND a.TitleCodePriority is NULL THEN 40 
  WHEN (a.TITLECODE_back ='Y' OR a.TITLECODE ='Y') AND a.TitleCodePriority is NULL THEN 41 
  WHEN (a.TITLECODE_back ='!' OR a.TITLECODE ='!') AND a.TitleCodePriority is NULL THEN 42 
  WHEN (a.TITLECODE_back ='^' OR a.TITLECODE ='^') AND a.TitleCodePriority is NULL THEN 43 
  WHEN (a.TITLECODE_back ='-' OR a.TITLECODE ='-') AND a.TitleCodePriority is NULL THEN 44 
  WHEN (a.TITLECODE_back ='\\' OR a.TITLECODE ='\\') AND a.TitleCodePriority is NULL THEN 45 
  WHEN (a.TITLECODE_back ='/' OR a.TITLECODE ='/') AND a.TitleCodePriority is NULL THEN 46 
  WHEN (a.TITLECODE_back ='[' OR a.TITLECODE ='[') AND a.TitleCodePriority is NULL THEN 47 
  WHEN (a.TITLECODE_back ='.' OR a.TITLECODE ='.') AND a.TitleCodePriority is NULL THEN 48 
  WHEN (a.TITLECODE_back ='Q' OR a.TITLECODE ='Q') AND a.TitleCodePriority is NULL THEN 49 
  WHEN (a.TITLECODE_back ='+' OR a.TITLECODE ='+') AND a.TitleCodePriority is NULL THEN 50 
  WHEN (a.TITLECODE_back ='#' OR a.TITLECODE ='#') AND a.TitleCodePriority is NULL THEN 51 
  WHEN (a.TITLECODE_back ='D' OR a.TITLECODE ='D') AND a.TitleCodePriority is NULL THEN 52 
  WHEN (a.TITLECODE_back =':' OR a.TITLECODE =':') AND a.TitleCodePriority is NULL THEN 53 
  WHEN (a.TITLECODE_back =']' OR a.TITLECODE =']') AND a.TitleCodePriority is NULL THEN 54
  WHEN (a.Name_Available='Y') AND  a.TitleCodePriority is NULL THEN 98 
  ELSE 99 END AS TitleCodePriority,
NVL(h.HospitalName,'') AS AMI_HospitalName,
NVL(LEFT(a.Zip_back,5),'') +NVL(LEFT(a.zipfour,4),'') + NVL(LEFT(a.DELIVERYPOINTBARCODE2,3),'') AS Locationzip_zip4_deliverypointbarcode,
h.STATE_DESCRIPTION as STATE_DESCRIPTION,
NVL(h.ETHNICITY_DESCRIPTION,'') as ETHNICITY_DESCRIPTION,
NVL(h.STOCKEXCHANGE_DESCRIPTION,'') as STOCKEXCHANGE_DESCRIPTION,
NVL(h.PHONECALLSTATUS_DESCRIPTION,'') as PHONECALLSTATUS_DESCRIPTION,
NVL(h.BUSINESSCREDITALPHASCORE_DESCRIPTION,'') as BUSINESSCREDITALPHASCORE_DESCRIPTION,
NVL(h.FLEETSIZE_DESCRIPTION,'') as FLEETSIZE_DESCRIPTION,
NVL(h.FRANCHISE_CODE_1_DESCRIPTION,'') as FRANCHISE_CODE_1_DESCRIPTION,
NVL(h.FRANCHISE_CODE_2_DESCRIPTION,'') as FRANCHISE_CODE_2_DESCRIPTION,
NVL(h.FRANCHISE_CODE_3_DESCRIPTION,'') as FRANCHISE_CODE_3_DESCRIPTION,
NVL(h.FRANCHISE_CODE_4_DESCRIPTION,'') as FRANCHISE_CODE_4_DESCRIPTION,
NVL(h.FRANCHISE_CODE_5_DESCRIPTION,'') as FRANCHISE_CODE_5_DESCRIPTION,
NVL(h.FRANCHISE_CODE_6_DESCRIPTION,'') as FRANCHISE_CODE_6_DESCRIPTION,
NVL(h.ACCOUNTING_EXPENSE,'') as ACCOUNTING_EXPENSE_DESCRIPTION,
NVL(h.ADVERTISING_EXPENSE,'') as ADVERTISING_EXPENSE_DESCRIPTION,
NVL(h.CHARITABLE_DONTATIONS_EXPENSE,'') as CHARITABLE_DONTATIONS_EXPENSE_DESCRIPTION,
NVL(h.CONTRACT_LABOR_EXPENSE,'') as CONTRACT_LABOR_EXPENSE_DESCRIPTION,
NVL(h.INSURANCE_EXPENSE,'') as INSURANCE_EXPENSE_DESCRIPTION,
NVL(h.LEGAL_EXPENSE,'') as LEGAL_EXPENSE_DESCRIPTION,
NVL(h.LICENSE_FEES_TAXES,'') as LICENSE_FEES_TAXES_DESCRIPTION,
NVL(h.MAINTENANCE_REPAIR,'') as MAINTENANCE_REPAIR_DESCRIPTION,
NVL(h.OFFICE_EQUIPMENT_EXPENSE,'') as OFFICE_EQUIPMENT_EXPENSE_DESCRIPTION,
NVL(h.PACKAGECONTAINER_EXPENSE,'') as PACKAGECONTAINER_EXPENSE_DESCRIPTION,
NVL(h.PAYROLL_EXPENSE,'') as PAYROLL_EXPENSE_DESCRIPTION,
NVL(h.PURCHASED_PRINT_EXPENSE,'') as PURCHASED_PRINT_EXPENSE_DESCRIPTION,
NVL(h.PURCHASE_MGMTADMIN_SVC_EXPENSE,'') as PURCHASE_MGMTADMIN_SVC_EXPENSE_DESCRIPTION,
NVL(h.RENT_LEASING_EXPENSE,'') as RENT_LEASING_EXPENSE_DESCRIPTION,
NVL(h.TECHNOLOGY_EXPENSE,'') as TECHNOLOGY_EXPENSE_DESCRIPTION,
NVL(h.TELECOMMUNICATIONS_EXPENSE,'') as TELECOMMUNICATIONS_EXPENSE_DESCRIPTION,
NVL(h.TransportationExpenseCode,'') as TransportationExpenseCode_DESCRIPTION,
NVL(h.UTILITIES_EXPENSE,'') as UTILITIES_EXPENSE_DESCRIPTION,
NVL(h.SALUTATION,'') as SALUTATION_DESCRIPTION,
NVL(h.ACL_GROUPCODE,'') as ACL_GROUPCODE_DESCRIPTION,
NVL(h.ACL_DENOMINATIONCODE,'') as ACL_DENOMINATIONCODE_DESCRIPTION,
NVL(h.DMACode,'') as DMACode_DESCRIPTION,
NVL(h.PROFTITLE,'') as PROFTITLE_DESCRIPTION,
NVL(h.ADDRESSTYPE,'') as ADDRESSTYPE_DESCRIPTION,
NVL(h.OWNORLEASE,'') as OWNORLEASE_DESCRIPTION,
NVL(h.AMI_BOARDCERTIFIEDINDICATOR,'') as AMI_BOARDCERTIFIEDINDICATOR_DESCRIPTION,
NVL(h.AMI_PRIMARYSPECIALTY,'') as AMI_PRIMARYSPECIALTY_DESCRIPTION,
NVL(h.AMI_SECONDARYSPECIALTY,'') as AMI_SECONDARYSPECIALTY_DESCRIPTION,
NVL(h.AMI_PROFESSIONALDEGREECODE,'') as AMI_PROFESSIONALDEGREECODE_DESCRIPTION,
NVL(h.AMI_LIC_STATEOFLICENSE,'') as AMI_LIC_STATEOFLICENSE_DESCRIPTION,
NVL(h.AMI_PRESCRIPTIONSPERWK,'') as AMI_PRESCRIPTIONSPERWK_DESCRIPTION,
NVL(h.CREDITRATINGCODE,'') as CREDITRATINGCODE_DESCRIPTION,
NVL(h.PHONE_NUMBER_TYPE,'') as PHONE_NUMBER_TYPE_DESCRIPTION,
NVL(h.PRIMARYSIC2_DESC,'') as PRIMARYSIC2_DESC,
NVL(h.PRIMARYSIC4_DESC,'') as PRIMARYSIC4_DESC,
NVL(h.cIndustryDesc,'') as INDUSTRY_DESC,
NVL(replace(h.DISTRICT_DESCRIPTION, h.STATE_DESCRIPTION, '' ),'') as DISTRICT_DESCRIPTION,
h.CREDIT_RATING_DESCRIPTION as CREDIT_RATING_DESCRIPTION,
NVL(h.TITLE_DESCRIPTION,'') as TITLE_DESCRIPTION,
NVL(h.GENDER_DESCRIPTION,'') as GENDER_DESCRIPTION,
NVL(h.CMA_DESCRIPTION,'') as CMA_DESCRIPTION,
a.RegionCode_Multi AS RegionCode_Multi,
case when LEFT(a.ZIP9,6) LIKE 'B3%'
        OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'B2V' AND 'B2Z'  
        OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'B4A' AND 'B4G' then 'RA' else '' end as RegionCode_01,
case when LEFT(a.ZIP9,6) LIKE 'G0A%'  
    OR LEFT(a.ZIP9,6) LIKE 'G2%'  
    OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'G1A' AND 'G1Z'  
    OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'G3A' AND 'G3K' 
    OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'G6V' AND 'G6X' then 'RB' else '' end as RegionCode_02,
case when LEFT(LEFT(a.ZIP9,6),3) = 'J8X'  
        OR LEFT(a.ZIP9,6) LIKE 'K0A%'  
        OR LEFT(a.ZIP9,6) LIKE 'K1%' 
        OR LEFT(a.ZIP9,6) LIKE 'K2%' 
        OR LEFT(a.ZIP9,6) LIKE 'K4A%' then 'RC' else '' end as RegionCode_03,
case when LEFT(a.ZIP9,6) LIKE 'R3%'  
            OR LEFT(a.ZIP9,6) LIKE 'R4A%' 
            OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'R2C' AND 'R2Z' then 'RD' else '' end as RegionCode_04,
case when LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'T1X' AND 'T3Z'  then 'RE' else '' end as RegionCode_05,
case when LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'T5A' AND 'T6X' then 'RF' else '' end as RegionCode_06,
case when State in ('AB','BC','MB','SK' ) then 'R1' else '' end as RegionCode_07,
case when State in ('NB','NS','PE') then 'R2' else '' end as RegionCode_08,
case when LEFT(a.ZIP9,6) LIKE 'M%'  
          OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L1S' AND 'L1Z'  
          OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L3P' AND 'L3T' 
          OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L4B' AND 'L4L' 
          OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L4S' AND 'L5W'
          OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L6B' AND 'L7A' then 'R3' else '' end as RegionCode_09,
case when LEFT(a.ZIP9,6) LIKE 'L0B%'
        OR LEFT(a.ZIP9,6) LIKE 'L0C%'
        OR LEFT(a.ZIP9,6) LIKE 'L0G%'
        OR LEFT(a.ZIP9,6) LIKE 'L0H%'
        OR LEFT(a.ZIP9,6) LIKE 'L0J%'
        OR LEFT(a.ZIP9,6) LIKE 'L0P%'
        OR LEFT(a.ZIP9,6) LIKE 'L1%'
        OR LEFT(a.ZIP9,6) LIKE 'L3%'
        OR LEFT(a.ZIP9,6) LIKE 'L4%'
        OR LEFT(a.ZIP9,6) LIKE 'L5%'
        OR LEFT(a.ZIP9,6) LIKE 'L6%'
        OR LEFT(a.ZIP9,6) LIKE 'M%' then 'R4' else '' end as RegionCode_10,
case when LEFT(a.ZIP9,6) LIKE 'M%'
            OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L1G' AND 'L1Z'
            OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L2A' AND 'L3M'
            OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L3P' AND 'L3T'
            OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L4B' AND 'L4L'
            OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L4S' AND 'L5W'
            OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L6B' AND 'L7A'
            OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'L7L' AND 'L9K' then 'R5' else '' end as RegionCode_11,
case when LEFT(a.ZIP9,6) LIKE 'L%'  OR LEFT(a.ZIP9,6) LIKE 'M%' then 'R6' else '' end as RegionCode_12,
case when LEFT(a.ZIP9,6) LIKE 'H%'
            OR LEFT(a.ZIP9,6) LIKE 'J0L%'
            OR LEFT(a.ZIP9,6) LIKE 'J0N%'
            OR LEFT(a.ZIP9,6) LIKE 'J0P%'
            OR LEFT(a.ZIP9,6) LIKE 'J0R%'
            OR LEFT(a.ZIP9,6) LIKE 'J0S%'
            OR LEFT(a.ZIP9,6) LIKE 'J0V%'
            OR LEFT(a.ZIP9,6) LIKE 'J3%'
            OR LEFT(a.ZIP9,6) LIKE 'J4%'
            OR LEFT(a.ZIP9,6) LIKE 'J5%'
            OR LEFT(a.ZIP9,6) LIKE 'J6%'
            OR LEFT(a.ZIP9,6) LIKE 'J7%' then 'R7' else '' end as RegionCode_13,
case when LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'V8N' AND 'V9E' then 'R8' else '' end as RegionCode_14,
case when LEFT(a.ZIP9,6) LIKE 'V3%'
        OR LEFT(a.ZIP9,6) LIKE 'V4%'
        OR LEFT(a.ZIP9,6) LIKE 'V5%'
        OR LEFT(a.ZIP9,6) LIKE 'V6%'
        OR LEFT(a.ZIP9,6) LIKE 'V7%'
        OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'V2S' AND 'V2Z'
        OR LEFT(LEFT(a.ZIP9,6),3) BETWEEN 'V1M' AND 'V1M' then 'R9' else '' end as RegionCode_15,
LTRIM(RTRIM(LEFT(a.MAILING_ZIPCODE,3) + LEFT(a.MAILING_ZIPFOUR,3 ))) as PostalCode_Mailing,
LTRIM(RTRIM(LEFT(a.LANDMARK_ZIPCODE,3) + LEFT(a.LANDMARK_ZIPFOUR,3 ))) as PostalCode_Landmark,
'N' AS AMEXSFLAG,
GetMatchCode(NVL(FirstName,''), CASE WHEN NVL(LastName,'') = '' THEN NVL(Company,'') ELSE LastName END, NVL(Address,''), NVL(Zip_back,''), '' ,'I') AS Individual_MC,
GetMatchCode(NVL(FirstName,''), NVL(LastName,''), NVL(Address,''), NVL(Zip_back,''), CASE WHEN NVL(Company, '') = '' THEN NVL(LastName,'') ELSE Company END,'C') AS Company_MC,
GetMatchCode('', '', NVL(Address,''), NVL(Zip_back,''), '' ,'I') AS Address_MC
FROM tblBusinessIndividual a 
LEFT JOIN 
(
   select contactid,cvalue from ApplicationCodes_1293_E group by contactid,cvalue
)C 
ON a.ContactID = C.ContactID AND C.cValue = 'H'
LEFT JOIN 
(
   select contactid,cvalue from SegmentCodes_1293_E where cValue ='3'
)D 
ON a.ContactID = D.ContactID 
LEFT JOIN 
(
   select contactid,cvalue from SegmentCodes_1293_E where cValue ='7'
)e
ON a.ContactID = e.ContactID
LEFT JOIN 
(
  select cDescription, cCode from  EXCLUDE_LiteralTitleIDTally group by cDescription, cCode) i  
ON a.LiteralTitle_ID =i.cCode
LEFT JOIN 
(
  SELECT LTRIM(RTRIM(UPPER(cStateCode))) AS cStateCode , LTRIM(RTRIM(UPPER(cCountycode))) AS cCountycode, LTRIM(RTRIM(UPPER(cCounty))) AS cCounty
  FROM sql_tblstate where databaseid=0 group by cStateCode,cCountycode,cCounty
)F 
on a.state = F.cStatecode AND a.countycode = F.cCountyCode
LEFT JOIN All_Business_Combined h 
ON a.id= h.id;