DROP TABLE IF EXISTS  tblmain_21891_202109_NEW; --create a new table to applied the encoding on existing table

CREATE TABLE tblmain_21891_202109_NEW(
id bigint encode az64 ,
cinclude VARCHAR(101) encode zstd,
epd_haspostal VARCHAR(101) encode zstd,
epd_hasphone VARCHAR(101) encode zstd,
listid int encode az64,
state VARCHAR(102) encode zstd,
addresstype VARCHAR(101) encode zstd,
gender VARCHAR(101) encode zstd,
noofaddresslines VARCHAR(101) encode zstd,
phonenumbertype VARCHAR(101) encode zstd,
prefixcode VARCHAR(101) encode zstd,
listtype VARCHAR(101) encode zstd,
productcode VARCHAR(102) encode zstd,
text_jobfunction1 VARCHAR(105) encode zstd,
text_jobtitle VARCHAR(105) encode zstd,
recordtype VARCHAR(101) encode zstd,
addresstypeindicator VARCHAR(101) encode zstd,
deliverypointdropind VARCHAR(101) encode zstd,
deliverycode VARCHAR(101) encode zstd,
deliverytype VARCHAR(101) encode zstd,
dmamailpreference VARCHAR(101) encode zstd,
dmaphonesuppress VARCHAR(101) encode zstd,
lot VARCHAR(102) encode zstd,
mailabilityscore VARCHAR(102) encode zstd,
resbusindicator VARCHAR(101) encode zstd,
movetype VARCHAR(101) encode zstd,
seasonalindicator VARCHAR(101) encode zstd, 
vacantindicator VARCHAR(101) encode zstd,
prisonrecord VARCHAR(101) encode zstd,
permissiontype VARCHAR(101) encode zstd,
lotinfo VARCHAR(105) encode zstd,
sic4 VARCHAR(104) encode zstd,
sic2 VARCHAR(102) encode zstd,
canadiansic4 VARCHAR(104) encode zstd,
canadiansic2 VARCHAR(102) encode zstd,
activeexpire VARCHAR(110) encode zstd,
epd_domaintype VARCHAR(101) encode zstd,
epd_scf VARCHAR(103) encode zstd,
epd_location VARCHAR(101) encode zstd,
deliverypoint VARCHAR(103) encode zstd,
batchdate VARCHAR(107) encode zstd,
carrierroute VARCHAR(104) encode zstd,
individual_id VARCHAR(117) encode zstd,
company_mc VARCHAR(115) encode zstd,
accountno VARCHAR(115) encode zstd,
fullname VARCHAR(150) encode zstd,
firstname VARCHAR(120) encode zstd,
lastname VARCHAR(120) encode zstd,
title VARCHAR(150) encode zstd,
company VARCHAR(150) encode zstd,
addressline1 VARCHAR(150) encode zstd,
addressline2 VARCHAR(150) encode zstd,
city VARCHAR(130) encode zstd,
zipfull VARCHAR(110) encode zstd,
zip VARCHAR(105) encode zstd,
zip4 VARCHAR(104) encode zstd,
websiteurl VARCHAR(150) encode zstd,
loginsiteurlip VARCHAR(150) encode zstd,
emailaddress_md5 VARCHAR(132) encode zstd,
encryptedemail VARCHAR(220) encode zstd,
epd_domain VARCHAR(150) encode zstd,
emailaddress VARCHAR(165) encode zstd,
countryname VARCHAR(130) encode zstd,
phone VARCHAR(120) encode zstd,
sha256lower VARCHAR(164) encode zstd,
sqltableid int encode az64,
canada_raw01 VARCHAR(180) encode zstd,
hascontact VARCHAR(101) encode zstd,
haszip4 VARCHAR(101) encode zstd,
multibuyercount int encode az64,
hasurl VARCHAR(101) encode zstd,
infousaflag VARCHAR(101) encode zstd,
multibuyercount_byemail int encode az64,
info_yrestblshd VARCHAR(104) encode zstd,
igus_abinum VARCHAR(109) encode zstd,
igcnd_locnum VARCHAR(109) encode zstd,
countbycompanymc int encode az64,
lastclickopen VARCHAR(106) encode zstd,
emailfrequency_90 int encode az64,
briteverifiedemail VARCHAR(103) encode zstd,
emailscoreflag VARCHAR(101) encode zstd,
cbsa VARCHAR(110) encode zstd,
city_state VARCHAR(150) encode zstd,
county_state VARCHAR(150) encode zstd,
countryflag VARCHAR(101) encode zstd,
scf_canada VARCHAR(103) encode zstd,
title_raw  VARCHAR(150) encode zstd,
newnamedate VARCHAR(106) encode zstd,
newemaildate VARCHAR(106) encode zstd,
combinedjobtitleandfunction VARCHAR(112) encode zstd,
parksuppression VARCHAR(101) encode zstd,
email_suppression_flag VARCHAR(101) encode zstd,
dm_tm_suppression_flag VARCHAR(101) encode zstd,
hasnameandtitle VARCHAR(101) encode zstd,
liverampmatchback_email VARCHAR(101) encode zstd,
liverampmatchback_postal VARCHAR(101) encode zstd,
phone_cellflag VARCHAR(101) encode zstd,
phone_quality_flag VARCHAR(101) encode zstd,
phonemultibuyercount int encode az64,
topleveldomain VARCHAR(150) encode zstd,
maxperaddresszip VARCHAR(111) encode zstd,
template_flag VARCHAR(170) encode zstd,
removeddata_raw02 VARCHAR(180) encode zstd,
sic4_prioritized VARCHAR(104) encode zstd,
sic2_prioritized VARCHAR(102) encode zstd,
employeesize_prioritized VARCHAR(110) encode zstd,
employeesatcompany_prioritized VARCHAR(110) encode zstd,
employeescombined_prioritized VARCHAR(110) encode zstd,
salesvolume_prioritized VARCHAR(110) encode zstd,
salesforcompany_prioritized VARCHAR(110) encode zstd,
salescombined_prioritized VARCHAR(105) encode zstd,
text_jobfunction_rollup VARCHAR(102) encode zstd,
text_jobtitle_rollup VARCHAR(102) encode zstd,
combinedjobtitleandfunction_rollup VARCHAR(106) encode zstd,
titlegotpromoted VARCHAR(101) encode zstd,
employeegrowth VARCHAR(101) encode zstd,
salesgrowth VARCHAR(101) encode zstd,
industry_prioritized VARCHAR(106) encode zstd,
jobfunction VARCHAR(600) encode zstd,
specialty VARCHAR(400) encode zstd,
interestarea VARCHAR(600) encode zstd,
productspecified VARCHAR(700) encode zstd,
hardwareonsite VARCHAR(1000) encode zstd,
industry VARCHAR(600) encode zstd,
locationtype VARCHAR(350) encode zstd,
softwareonsite VARCHAR(900) encode zstd,
individual_mc VARCHAR(117) encode zstd,
template_postalus VARCHAR(101) encode zstd,
template_postalcan VARCHAR(101) encode zstd,
template_postalus_telmkt VARCHAR(101) encode zstd,
template_postalus_email VARCHAR(101) encode zstd,
template_postalus_postalemail VARCHAR(101) encode zstd,
template_postalus_posttelmktemail VARCHAR(101) encode zstd,
template_postalus_athome VARCHAR(101) encode zstd)
DISTKEY(id)
SORTKEY(id);

--Insert the existing table data into New Table
INSERT INTO tblMain_21891_202109_NEW (SELECT * FROM tblMain_21891_202109);

DROP TABLE IF EXISTS tblMain_21891_202109; --drop the main table

--Rename the New table name with Main Table
ALTER TABLE tblMain_21891_202109_NEW RENAME TO tblMain_21891_202109;