DROP TABLE IF EXISTS digital.Occupations_qa;
CREATE TABLE IF NOT EXISTS digital.Occupations_qa
             (
                          OCCUPATION_ID                  VARCHAR ( 12 ),
                          FIRST_NAME                     VARCHAR ( 15 ),
                          MIDDLE_NAME                    VARCHAR ( 15 ),
                          LAST_NAME                      VARCHAR ( 20 ),
                          GENERATIONAL_SUFFIX            VARCHAR ( 4 ),
                          ADDRESS                        VARCHAR ( 40 ),
                          HOUSE_NUMBER                   VARCHAR ( 10 ),
                          STREET_PRE_DIRECTIONAL         VARCHAR ( 2 ),
                          STREET_NAME                    VARCHAR ( 28 ),
                          STREET_SUFFIX                  VARCHAR ( 4 ),
                          STREET_POST_DIRECTIONAL        VARCHAR ( 2 ),
                          UNIT_TYPE                      VARCHAR ( 4 ),
                          UNIT_NUMBER                    VARCHAR ( 8 ),
                          CITY                           VARCHAR ( 28 ),
                          STATE                          VARCHAR ( 2 ),
                          ZIP_CODE                       VARCHAR ( 5 ),
                          ZIP_FOUR                       VARCHAR ( 4 ),
                          DELIVERY_POINT_BARCODE         VARCHAR ( 3 ),
                          HIGH_RISE                      VARCHAR ( 2 ),
                          CARRIER_ROUTE_CODE             VARCHAR ( 4 ),
                          CENSUS_STATE_CODE              VARCHAR ( 2 ),
                          CENSUS_COUNTY_CODE             VARCHAR ( 3 ),
                          COUNTY_CODE_DESC               VARCHAR ( 5 ),
                          CENSUS_TRACT                   VARCHAR ( 6 ),
                          CENSUS_BLOCK_GROUP             VARCHAR ( 1 ),
                          MATCH_CODE                     VARCHAR ( 1 ),
                          LATITUDE                       VARCHAR ( 9 ),
                          LONGITUDE                      VARCHAR ( 9 ),
                          MAIL_SCORE                     VARCHAR ( 2 ),
                          RESIDENTIAL_BUSINESS_INDICATOR VARCHAR ( 1 ),
                          EMPLOYER_NAME                  VARCHAR ( 30 ),
                          FAMILY_ID                      VARCHAR ( 12 ),
                          INDIVIDUAL_ID                  VARCHAR ( 12 ),
                          ABI_NUMBER                     VARCHAR ( 9 ),
                          INDUSTRY_TITLE                 VARCHAR ( 50 ),
                          OCCUPATION_TITLE               VARCHAR ( 50 ),
                          SPECIALTY_TITLE                VARCHAR ( 50 ),
                          SIC_CODE                       VARCHAR ( 6 ),
                          NAICS_GROUP                    VARCHAR ( 2 ),
                          LICENSE_STATE                  VARCHAR ( 2 ),
                          LICENSE_ID                     VARCHAR ( 12 ),
                          LICENSE_NUMBER                 VARCHAR ( 25 ),
                          LICENSE_EXP_DATE               VARCHAR ( 8 ),
                          LICENSE_STATUS_CODE            VARCHAR ( 1 ),
                          LICENSE_REFRESH_DATE           VARCHAR ( 8 ),
                          LICENSE_ADD_DATE               VARCHAR ( 8 ),
                          LICENSE_CHANGE_DATE            VARCHAR ( 8 ),
                          YEAR_LICENSED                  VARCHAR ( 4 ),
                          AREA_CODE                      VARCHAR ( 3 ),
                          PHONE_NUMBER                   VARCHAR ( 7 ),
                          SOURCE_CODE                    VARCHAR ( 5 ),
                          MOVE_TYPE                      VARCHAR ( 1 ),
                          MOVE_DATE                      VARCHAR ( 6 ),
                          RECORD_ID                      VARCHAR ( 9 ),
                          eof                            VARCHAR ( 1 )
             );


COPY digital.occupations_qa
    FROM 's3://digital-7933-business/input/ocupation_data/OccupationDigital.gz'
    iam_role {iam}
    REMOVEQUOTES
    GZIP
    IGNOREBLANKLINES
    ACCEPTINVCHARS
    MAXERROR 100
    FIXEDWIDTH
    'OCCUPATION_ID:12,
    FIRST_NAME:15,
    MIDDLE_NAME:15,
    LAST_NAME:20,
    GENERATIONAL_SUFFIX:4,
    ADDRESS:40,
    HOUSE_NUMBER:10,
    STREET_PRE_DIRECTIONAL:2,
    STREET_NAME:28,
    STREET_SUFFIX:4,
    STREET_POST_DIRECTIONAL:2,
    UNIT_TYPE:4,
    UNIT_NUMBER:8,
    CITY:28,
    STATE:2,
    ZIP_CODE:5,
    ZIP_FOUR:4,
    DELIVERY_POINT_BARCODE:3,
    HIGH_RISE:2,
    CARRIER_ROUTE_CODE:4,
    CENSUS_STATE_CODE:2,
    CENSUS_COUNTY_CODE:3,
    COUNTY_CODE_DESC:5,
    CENSUS_TRACT:6,
    CENSUS_BLOCK_GROUP:1,
    MATCH_CODE:1,
    LATITUDE:9,
    LONGITUDE:9,
    MAIL_SCORE:2,
    RESIDENTIAL_BUSINESS_INDICATOR:1,
    EMPLOYER_NAME:30,
    FAMILY_ID:12,
    INDIVIDUAL_ID:12,
    ABI_NUMBER:9,
    INDUSTRY_TITLE:50,
    OCCUPATION_TITLE:50,
    SPECIALTY_TITLE:50,
    SIC_CODE:6,
    NAICS_GROUP:2,
    LICENSE_STATE:2,
    LICENSE_ID:12,
    LICENSE_NUMBER:25,
    LICENSE_EXP_DATE:8,
    LICENSE_STATUS_CODE:1,
    LICENSE_REFRESH_DATE:8,
    LICENSE_ADD_DATE:8,
    LICENSE_CHANGE_DATE:8,
    YEAR_LICENSED:4,
    AREA_CODE:3,
    PHONE_NUMBER:7,
    SOURCE_CODE:5,
    MOVE_TYPE:1,
    MOVE_DATE:6,
    RECORD_ID:9,
    eof:1';
