DROP TABLE IF EXISTS {table-execureach-new-raw};
CREATE TABLE {table-execureach-new-raw}
(
	bus_abinumber VARCHAR(9) ,
	bus_contactname VARCHAR(30) ,
	bus_companyname VARCHAR(30) ,
	bus_address VARCHAR(30) ,
	bus_city VARCHAR(18) ,
	bus_state VARCHAR(2) ,
	bus_zipcode VARCHAR(5) ,
	bus_zipfour VARCHAR(4) ,
	bus_phonenumber VARCHAR(10) ,
	bus_countycode VARCHAR(3) ,
	bus_titlecode VARCHAR(1) ,
	bus_titlecodedescription VARCHAR(30) ,
	bus_employeesizecode VARCHAR(1) ,
	bus_locationoutputvolumecode VARCHAR(1) ,
	bus_primarysiccode VARCHAR(6) ,
	cons_address VARCHAR(30) ,
	cons_city VARCHAR(18) ,
	cons_state VARCHAR(2) ,
	cons_zipcode VARCHAR(5) ,
	cons_zipfour VARCHAR(4) ,
	cons_phonenumber VARCHAR(10) ,
	cons_countycode VARCHAR(3) ,
	cons_locationtype VARCHAR(1) ,
	cons_gender VARCHAR(1) ,
	cons_age VARCHAR(2) ,
	cons_income VARCHAR(1) ,
	cons_name VARCHAR(30) ,
	cons_maritalstatus VARCHAR(1) ,
	cons_creditcardholder VARCHAR(1) ,
	cons_ownrent VARCHAR(1) ,
	matchflag VARCHAR(1) ,
	cons_individualid VARCHAR(12) ,
	cons_familyid VARCHAR(12) ,
	bus_executivesourcecode VARCHAR(5) ,
	bus_executiveid VARCHAR(9) ,
	bus_contactflag VARCHAR(2) ,
	bus_fulfillmentflag VARCHAR(1) ,
	bus_emailaddress VARCHAR(80) ,
	bus_vendorid VARCHAR(2) ,
	bus_cbsa VARCHAR(5) ,
	bus_cbsalevel VARCHAR(1) ,
	bus_companyholdingstatus VARCHAR(1) ,
	bus_cottagecode VARCHAR(1) ,
	bus_mailscore VARCHAR(2) ,
	cons_emailaddress VARCHAR(80) ,
	cons_vendorid VARCHAR(2) ,
	cons_statecode VARCHAR(2) ,
	cons_mailconfidence VARCHAR(2) ,
	cons_presenceofemail VARCHAR(1) ,
	recordtypeindicator VARCHAR(1) ,
	execureachquality VARCHAR(2) ,
	bus_contactquality VARCHAR(1) ,
	matchquality VARCHAR(1) ,
	bus_contactliteraltitlecode VARCHAR(8) ,
	firstname VARCHAR(15) ,
	middleinitial VARCHAR(1) ,
	lastname VARCHAR(20) ,
	bus_contactid VARCHAR(12) , 
	bus_professionaltitle VARCHAR(3) ,
	bus_functionalareacode VARCHAR(4),
	bus_rolecode VARCHAR(4),
	bus_digitalflag VARCHAR(1),
	con_digitalflag VARCHAR(1),
	distancecode VARCHAR(1),
	bus_bvtscore VARCHAR(1), 
	cons_bvtscore VARCHAR(1),
    filler_1 VARCHAR(7),
    filler_2 VARCHAR(5),
	bus_modeledemployeesizeflag VARCHAR(1),/*new fields added aug 5, 2019 sf ticket 796756 */
    filler_3 VARCHAR(9),
	bus_location_outputvolumetypcode VARCHAR(1),
	bus_corporate_employeecount VARCHAR(6),
	bus_corporate_employeerange VARCHAR(1),
	bus_corporate_employeesourceindicator VARCHAR(1),
	bus_corporate_salesvolumeamount VARCHAR(9),
	bus_corporate_salesvolumerange VARCHAR(1),
	bus_corporate_salesvolumesourceindicator VARCHAR(1),
    filler_4 VARCHAR(1),
    filler_5 VARCHAR(1),
	con_carrierroutecode VARCHAR(4),
	con_homevalue VARCHAR(1), /* to here 10 new fields aug 5, 2019 sf */
	bus_email_md5_upper VARCHAR(32) ,
	bus_email_md5_lower VARCHAR(32) , 
	cons_email_md5_upper VARCHAR(32) ,
	cons_email_md5_lower VARCHAR(32) ,
	ce_expendable_income_rank_code VARCHAR(1) ,
	ce_lhi_selected_apparel_general VARCHAR(1) ,
	ce_lhi_selected_apparel_accessories VARCHAR(1) ,
	ce_lhi_selected_apparel_kids VARCHAR(1) ,
	ce_lhi_selected_apparel_mens VARCHAR(1) ,
	ce_lhi_selected_apparel_mens_fashions VARCHAR(1) ,
	ce_lhi_selected_apparel_womens VARCHAR(1) ,
	ce_lhi_selected_apparel_womens_fashions VARCHAR(1) ,
	ce_lhi_selected_automotive VARCHAR(1) ,
	ce_lhi_selected_auto_racing VARCHAR(1) ,
	ce_lhi_selected_auto_trucks VARCHAR(1) ,
	ce_lhi_selected_aviation VARCHAR(1) ,
	ce_lhi_selected_bargain_seekers VARCHAR(1) ,
	ce_lhi_selected_beauty_cosmetic VARCHAR(1) ,
	ce_lhi_selected_bible VARCHAR(1) ,
	ce_lhi_selected_birds VARCHAR(1) ,
	ce_lhi_selected_business_items VARCHAR(1) ,
	ce_lhi_selected_business_home_office VARCHAR(1) ,
	ce_lhi_selected_catalogs VARCHAR(1) ,
	ce_lhi_selected_collectibles VARCHAR(1) ,
	ce_lhi_household_collectibles_stamps_coins VARCHAR(1) ,
	ce_lhi_selected_college VARCHAR(1) ,
	ce_lhi_selected_computers VARCHAR(1) ,
	ce_lhi_selected_cooking VARCHAR(1) ,
	ce_lhi_selected_cooking_gourmet VARCHAR(1) ,
	ce_lhi_selected_crafts_general VARCHAR(1) ,
	ce_lhi_selected_crafts_crocheting VARCHAR(1) ,
	ce_lhi_selected_crafts_knitting VARCHAR(1) ,
	ce_lhi_selected_crafts_needlepoint VARCHAR(1) ,
	ce_lhi_selected_crafts_quilting VARCHAR(1) ,
	ce_lhi_selected_crafts_sewing VARCHAR(1) ,
	ce_lhi_selected_culture_arts VARCHAR(1) ,
	ce_lhi_selected_current_events VARCHAR(1) ,
	ce_lhi_selected_do_it_yourselfer VARCHAR(1) ,
	ce_lhi_selected_charitable_donor VARCHAR(1) ,
	ce_lhi_selected_ego_personalized_products VARCHAR(1) ,
	ce_lhi_selected_electronics VARCHAR(1) ,
	ce_lhi_selected_equestrian VARCHAR(1) ,
	ce_lhi_selected_ethnic_product_african_american VARCHAR(1) ,
	ce_lhi_selected_ethnic_product_asian VARCHAR(1) ,
	ce_lhi_selected_ethnic_product_hispanic VARCHAR(1) ,
	ce_lhi_selected_family VARCHAR(1) ,
	ce_lhi_selected_finance_credit_card_user VARCHAR(1) ,
	ce_lhi_selected_finance_money_making VARCHAR(1) ,
	ce_lhi_selected_finance_personal VARCHAR(1) ,
	ce_lhi_household_finance_stocks_bonds VARCHAR(1) ,
	ce_lhi_selected_gambling VARCHAR(1) ,
	ce_lhi_selected_games VARCHAR(1) ,
	ce_lhi_selected_gardening VARCHAR(1) ,
	ce_lhi_selected_gift_giver VARCHAR(1) ,
	ce_lhi_selected_health_general VARCHAR(1) ,
	ce_lhi_selected_health_dieting VARCHAR(1) ,
	ce_lhi_selected_health_fitness_exercise VARCHAR(1) ,
	ce_lhi_household_high_ticket VARCHAR(1) ,
	ce_lhi_selected_hightech VARCHAR(1) ,
	ce_lhi_selected_history VARCHAR(1) ,
	ce_lhi_selected_history_american VARCHAR(1) ,
	ce_lhi_selected_hobbies VARCHAR(1) ,
	ce_lhi_selected_home_decorating VARCHAR(1) ,
	ce_lhi_selected_humor VARCHAR(1) ,
	ce_lhi_selected_inspirational VARCHAR(1) ,
	ce_lhi_selected_internet VARCHAR(1) ,
	ce_lhi_selected_internet_access VARCHAR(1) ,
	ce_lhi_selected_internet_buying VARCHAR(1) ,
	ce_lhi_selected_motorcycles VARCHAR(1) ,
	ce_lhi_selected_music VARCHAR(1) ,
	ce_lhi_selected_ocean VARCHAR(1) ,
	ce_lhi_selected_outdoors VARCHAR(1) ,
	ce_lhi_selected_outdoors_boating_sailing VARCHAR(1) ,
	ce_lhi_selected_outdoors_camping_hiking VARCHAR(1) ,
	ce_lhi_selected_outdoors_fishing VARCHAR(1) ,
	ce_lhi_selected_outdoors_hunting VARCHAR(1) ,
	ce_lhi_selected_outdoors_hunting_fishing VARCHAR(1) ,
	ce_lhi_selected_pets VARCHAR(1) ,
	ce_lhi_selected_pets_cats VARCHAR(1) ,
	ce_lhi_selected_pets_dogs VARCHAR(1) ,
	ce_lhi_selected_photo_photography VARCHAR(1) ,
	ce_lhi_selected_photo_photoprocessing VARCHAR(1) ,
	ce_lhi_selected_politically_conservative VARCHAR(1) ,
	ce_lhi_selected_politically_liberal VARCHAR(1) ,
	ce_lhi_selected_publish_publications VARCHAR(1) ,
	ce_lhi_selected_publish_books VARCHAR(1) ,
	ce_lhi_selected_publish_fiction VARCHAR(1) ,
	ce_lhi_selected_publish_magazine_subscriber VARCHAR(1) ,
	ce_lhi_selected_publish_nonfiction VARCHAR(1) ,
	ce_lhi_selected_publish_science_fiction VARCHAR(1) ,
	ce_lhi_selected_rural_farming VARCHAR(1) ,
	ce_lhi_selected_science VARCHAR(1) ,
	ce_lhi_selected_seniors VARCHAR(1) ,
	ce_lhi_selected_sports_general VARCHAR(1) ,
	ce_lhi_selected_sports_baseball VARCHAR(1) ,
	ce_lhi_selected_sports_basketball VARCHAR(1) ,
	ce_lhi_selected_sports_football VARCHAR(1) ,
	ce_lhi_selected_sports_golf VARCHAR(1) ,
	ce_lhi_selected_sports_hockey VARCHAR(1) ,
	ce_lhi_selected_sports_skiing VARCHAR(1) ,
	ce_lhi_selected_sports_soccer VARCHAR(1) ,
	ce_lhi_selected_sports_tennis VARCHAR(1) ,
	ce_lhi_selected_stationery VARCHAR(1) ,
	ce_lhi_selected_sweepstakes VARCHAR(1) ,
	ce_lhi_household_technology_vcr VARCHAR(1) ,
	ce_lhi_selected_tobacco VARCHAR(1) ,
	ce_lhi_selected_travel_general VARCHAR(1) ,
	ce_lhi_selected_travel_cruises VARCHAR(1) ,
	ce_lhi_household_travel_foreign VARCHAR(1) ,
	ce_lhi_selected_travel_rv VARCHAR(1) ,
	ce_lhi_selected_travel_us VARCHAR(1) ,
	ce_lhi_selected_tv_movies VARCHAR(1) ,
	ce_lhi_selected_wildlife VARCHAR(1) ,
	ce_mail_responsive_current_flag VARCHAR(1) ,
	ce_mail_responsive_ever_flag VARCHAR(1) ,
	ce_mail_responsive_previous_flag VARCHAR(1) ,
	ce_online_purchase_personal_model VARCHAR(1) ,
	ce_online_purchase_business_model VARCHAR(1) ,
	ce_online_travel_plan_model VARCHAR(1) ,
	ce_blog_writing_model VARCHAR(1) ,
	ce_voice_over_internet_model VARCHAR(1) ,
	ce_wifi_outside_of_home_model VARCHAR(1) ,
	ce_wifi_in_home_model VARCHAR(1) ,
	ce_wholesale_club_model VARCHAR(1) ,
	ce_auto_club_model VARCHAR(1) ,
	ce_diy_auto_maintenance_model VARCHAR(1) ,
	ce_online_gaming_model VARCHAR(1) ,
	ce_online_investment_trading_model VARCHAR(1) ,
	ce_online_bill_payment_model VARCHAR(1) ,
	ce_online_tv_download_model VARCHAR(1) ,
	ce_mobile_internet_access_model VARCHAR(1) ,
	ce_social_media_network_model VARCHAR(1) ,
	ce_specialty_organic_food_store_model VARCHAR(1) ,
	lems VARCHAR(18) ,
	ce_selected_individual_formatted_date_of_birth VARCHAR(10) ,
	ce_adventure_seekers_model VARCHAR(1) ,
	ce_atv_model VARCHAR(1) ,
	ce_annuities_model VARCHAR(1) ,
	ce_avid_cell_phone_user_model VARCHAR(1) ,
	ce_avid_gamers_model VARCHAR(1) ,
	ce_avid_theme_park_visitor_model VARCHAR(1) ,
	ce_baby_product_model VARCHAR(1) ,
	ce_cat_product_model VARCHAR(1) ,
	ce_conservative_model VARCHAR(1) ,
	ce_cook_for_fun_model VARCHAR(1) ,
	ce_cook_from_scratch_model VARCHAR(1) ,
	ce_country_club_member_model VARCHAR(1) ,
	ce_credit_card_rewards_model VARCHAR(1) ,
	ce_cruise_model VARCHAR(1) ,
	ce_diet_product_model VARCHAR(1) ,
	ce_dog_product_model VARCHAR(1) ,
	ce_donors_pbs_npr_model VARCHAR(1) ,
	ce_foreign_travel_vacation_model VARCHAR(1) ,
	ce_frequent_business_traveler_model VARCHAR(1) ,
	ce_frequent_flyer_model VARCHAR(1) ,
	ce_fresh_water_fishing_model VARCHAR(1) ,
	ce_garden_maintenance_model VARCHAR(1) ,
	ce_green_model VARCHAR(1) ,
	ce_heavy_book_buyer_model VARCHAR(1) ,
	ce_heavy_coupon_user_model VARCHAR(1) ,
	ce_heavy_family_restaurant_visitor_model VARCHAR(1) ,
	ce_frozen_dinner_model VARCHAR(1) ,
	ce_heavy_investment_trader_model VARCHAR(1) ,
	ce_heavy_payperview_movie_model VARCHAR(1) ,
	ce_heavy_payperview_sports_model VARCHAR(1) ,
	ce_heavy_vitamin_model VARCHAR(1) ,
	ce_high_risk_investor_model VARCHAR(1) ,
	ce_high_value_security_investor_model VARCHAR(1) ,
	ce_high_value_stock_investor_model VARCHAR(1) ,
	ce_high_end_electronic_model VARCHAR(1) ,
	ce_high_end_sporting_equipment_model VARCHAR(1) ,
	ce_higher_education_model VARCHAR(1) ,
	ce_home_improvement_model VARCHAR(1) ,
	ce_hunting_model VARCHAR(1) ,
	ce_impulse_buyer_model VARCHAR(1) ,
	ce_international_long_distance_model VARCHAR(1) ,
	ce_leaning_conservative_model VARCHAR(1) ,
	ce_leaning_liberal_model VARCHAR(1) ,
	ce_liberal_model VARCHAR(1) ,
	ce_life_insurance_model VARCHAR(1) ,
	ce_live_theater_model VARCHAR(1) ,
	ce_low_risk_investor_model VARCHAR(1) ,
	ce_low_end_sporting_equipment_model VARCHAR(1) ,
	ce_luxury_car_buyer_model VARCHAR(1) ,
	ce_luxury_hotel_model VARCHAR(1) ,
	ce_music_concert_classical_model VARCHAR(1) ,
	ce_music_concert_country_model VARCHAR(1) ,
	ce_music_concert_rock_model VARCHAR(1) ,
	ce_nascar_model VARCHAR(1) ,
	ce_onsite_tax_preparation_model VARCHAR(1) ,
	ce_opinion_leader_model VARCHAR(1) ,
	ce_organic_food_model VARCHAR(1) ,
	ce_outdoor_activities_model VARCHAR(1) ,
	ce_physical_fitness_club_model VARCHAR(1) ,
	ce_power_boating_model VARCHAR(1) ,
	ce_religious_donor_model VARCHAR(1) ,
	ce_rental_car_model VARCHAR(1) ,
	ce_safety_security_conscious_model VARCHAR(1) ,
	ce_salt_water_fishing_model VARCHAR(1) ,
	ce_shopaholics_model VARCHAR(1) ,
	ce_college_basketball_model VARCHAR(1) ,
	ce_college_football_model VARCHAR(1) ,
	ce_golf_model VARCHAR(1) ,
	ce_professional_baseball_model VARCHAR(1) ,
	ce_professional_basketball_model VARCHAR(1) ,
	ce_professional_football_model VARCHAR(1) ,
	ce_professional_wrestling_model VARCHAR(1) ,
	ce_soccer_model VARCHAR(1) ,
	ce_tennis_model VARCHAR(1) ,
	ce_pro_tax_preparation_model VARCHAR(1) ,
	ce_timeshare_owner_model VARCHAR(1) ,
	ce_wine_lover_model VARCHAR(1) ,
	ce_environment_contributor_flag VARCHAR(1) ,
	ce_health_contributor_flag VARCHAR(1) ,
	ce_political_contributor_flag VARCHAR(1) ,
	ce_religious_contributor_flag VARCHAR(1) ,
	ce_donor_ever_contributor_flag VARCHAR(1) ,
	ce_home_office_model VARCHAR(1) ,
	ce_business_banking_model VARCHAR(1) ,
	ce_moderate_economy_hotel_model VARCHAR(1) ,
	ce_e_reader_model VARCHAR(1) ,		
	ce_cell_phone_only_model VARCHAR(1) ,
	ce_alternative_medicine_model VARCHAR(1) ,	
	ce_non_religious_donor_model VARCHAR(1) ,	
	ce_major_home_remodeling_model VARCHAR(1) ,
	ce_avid_smart_phone_users_model VARCHAR(1) ,
	ce_health_insurance_model VARCHAR(1) ,	
	ce_satellite_tv_model VARCHAR(1) ,
	ce_online_music_download_model VARCHAR(1) ,
	ce_adult_education_model VARCHAR(1) ,	
	ce_pilates_yoga_model VARCHAR(1) ,	
	ce_fast_food_model VARCHAR(1) ,	
	ce_hybrid_cars_model VARCHAR(1) ,
	ce_heavy_online_buyer_model VARCHAR(1) ,
	ce_high_end_apparel_model VARCHAR(1) ,	
	ce_heavy_catalog_buyer_model VARCHAR(1) ,
	ce_gift_buyers_model VARCHAR(1) ,
	ce_camping_model VARCHAR(1) ,
	ce_sports_fanatics_model VARCHAR(1) ,
	ce_financial_planner_model VARCHAR(1) ,
	ce_work_health_insurance_model VARCHAR(1) ,
	ce_comprehensive_auto_insurance_model VARCHAR(1) ,
	ce_small_business_insurance_model VARCHAR(1) ,	
	ce_heavy_snack_eaters_model VARCHAR(1) ,
	ce_heavy_domestic_travelers_model VARCHAR(1) ,
	ce_new_vehicle_buyer_model VARCHAR(1) ,
	ce_suv_buyer_model VARCHAR(1) ,
	ce_minivan_buyer_model VARCHAR(1) ,
	ce_auto_loan_model VARCHAR(1) ,
	ce_education_loan_model VARCHAR(1) ,
	ce_real_estate_investment_model VARCHAR(1) ,
	ce_fantasy_sports_model VARCHAR(1) ,
	ce_hockey_buyer_model VARCHAR(1),
	cons_unit_number VARCHAR(8),
	ce_selected_ind_vendor_ethnicity_code VARCHAR(2),		--added sf per ticket 767570 4.8.2019
	ce_selected_ind_vendor_ethnic_group_code VARCHAR (1),	 --added sf per ticket 767570 4.8.2019
	ce_selected_ind_vendor_spoken_language_code VARCHAR (2), --added sf per ticket 767570 4.8.2019
	ce_selected_ind_vendor_religion_code VARCHAR (1),		 --added sf per ticket 767570 4.8.2019
	bus_actual_location_employment_size VARCHAR(5),
	bus_corporate_employment_size_code VARCHAR(1),
	bus_actual_corporate_employment_size VARCHAR(6),
	bus_actual_location_sales_volume VARCHAR(9),
	bus_corporate_sales_volume_code VARCHAR(1),
	bus_actual_corporate_sales_volume VARCHAR(9),
	bus_square_footage VARCHAR(1),
	bus_business_credit_score_code VARCHAR(2),
	bus_business_credit_score VARCHAR(3),
	bus_businessstatuscode VARCHAR(1),
	bus_phonenumbertype VARCHAR(1),
	bus_naics_code8 VARCHAR(8), ----added sf per ticket# 805123 9.9.2019
    bus_web_address_url VARCHAR(40),  -- added cb IDMS-1755 1.25.2022
	bus_email_sha256_upper VARCHAR(64),----added fields by rj per ticket# 835596 2.10.2020
	bus_email_sha256_lower VARCHAR(64),
	con_email_sha256_upper VARCHAR(64),
	con_email_sha256_lower VARCHAR(64),
	bus_email_sha1_upper VARCHAR(40),		
	bus_email_sha1_lower VARCHAR(40),
	con_email_sha1_upper VARCHAR(40),		
	con_email_sha1_lower VARCHAR(40),
	cons_firstname VARCHAR(25), --added cb per jira #idms-630 2021.02.01
	cons_lastname VARCHAR(30), --added cb per jira #idms-630 2021.02.01
	busimatchcode VARCHAR(17), --added cb per jira #idms-630 2021.02.01
	buscmatchcode VARCHAR(15), --added cb per jira #idms-630 2021.02.01
	consimatchcode VARCHAR(17), --added cb per jira #idms-630 2021.02.01
	conshmatchcode VARCHAR(17),  --added cb per jira #idms-630 2021.02.01
    busyearfirstappeared VARCHAR(4),  --added eb per jira #idms-2537 2022.10.12
    busyearCode VARCHAR(1),  --added eb per jira #idms-2537 2022.10.12
	id INT IDENTITY UNIQUE,
	listid INT,
	permissiontype VARCHAR(1),
	listtype VARCHAR(1),
	productcode VARCHAR(1),
	dropflag VARCHAR(1),
	zipradius VARCHAR(1),
	gender VARCHAR(1),
	zip VARCHAR(5),
	bus_scf VARCHAR(3),
	con_scf VARCHAR(3),
	business_zip9 VARCHAR(9),
	consumer_zip9 VARCHAR(9),
	business_addr_available VARCHAR(1),
	consumer_addr_available VARCHAR(1),
	con_areacode VARCHAR(3),
	bus_companynameavailable VARCHAR(1),
	bus_sic_4 VARCHAR(4),
	bus_sic_2 VARCHAR(2),
	business_state_with_county VARCHAR(5),
	consumer_state_with_county_code VARCHAR(5),
	pres_of_bus_phone VARCHAR(1),
	pres_of_cons_phone VARCHAR(1),
	bus_emailaddressavailable VARCHAR(1),
	con_emailaddressavailable VARCHAR(1),
	bus_domain VARCHAR(80),
	con_domain VARCHAR(80),
	bus_bademail VARCHAR(1),
	infogroup_records VARCHAR(1),
	abi_available VARCHAR(1),
	royalty_records VARCHAR(1),
	"state" VARCHAR(2),
	bus_executive_infogroup_data VARCHAR(1),
	bus_emailaddress_infogroup_data VARCHAR(1),
	bus_contactliteraltitlecode_description VARCHAR(256),
	bus_contact_literal_title_description_available VARCHAR(1),
	bus_departmentcode VARCHAR(2),
	bus_levelcode VARCHAR(1),
	titlecode VARCHAR(3),
	statecountycode VARCHAR(5),
	statecountyname VARCHAR(60),
	citybystate VARCHAR(50),
    statecityzip VARCHAR(50),
	statecityscf VARCHAR(50),
	donotcallflag VARCHAR(1),
	bus_corporate_salesVolumerange_description VARCHAR(100),
	bus_corporate_employeerange_description VARCHAR(100),
	bus_naics_code8_description VARCHAR(100)
);

COPY {table-execureach-new-raw} 
(bus_abinumber,
bus_contactname,
bus_companyname,
bus_address,
bus_city,
bus_state,
bus_zipcode,
bus_zipfour,
bus_phonenumber,
bus_countycode,
bus_titlecode,
bus_titlecodedescription,
bus_employeesizecode,
bus_locationoutputvolumecode,
bus_primarysiccode,
cons_address,
cons_city,
cons_state,
cons_zipcode,
cons_zipfour,
cons_phonenumber,
cons_countycode,
cons_locationtype,
cons_gender,
cons_age,
cons_income,
cons_name,
cons_maritalstatus,
cons_creditcardholder,
cons_ownrent,
matchflag,
cons_individualid,
cons_familyid,
bus_executivesourcecode,
bus_executiveid,
bus_contactflag,
bus_fulfillmentflag,
bus_emailaddress,
bus_vendorid,
bus_cbsa,
bus_cbsalevel,
bus_companyholdingstatus,
bus_cottagecode,
bus_mailscore,
cons_emailaddress,
cons_vendorid,
cons_statecode,
cons_mailconfidence,
cons_presenceofemail,
recordtypeindicator,
execureachquality,
bus_contactquality,
matchquality,
bus_contactliteraltitlecode,
firstname,
middleinitial,
lastname,
bus_contactid,
bus_professionaltitle,
bus_functionalareacode,
bus_rolecode,
bus_digitalflag,
con_digitalflag,
distancecode,
bus_bvtscore,
cons_bvtscore,
filler_1,
filler_2,
bus_modeledemployeesizeflag,
filler_3,
bus_location_outputvolumetypcode,
bus_corporate_employeecount,
bus_corporate_employeerange,
bus_corporate_employeesourceindicator,
bus_corporate_salesvolumeamount,
bus_corporate_salesvolumerange,
bus_corporate_salesvolumesourceindicator,
filler_4,
filler_5,
con_carrierroutecode,
con_homevalue,
bus_email_md5_upper,
bus_email_md5_lower,
cons_email_md5_upper,
cons_email_md5_lower,
ce_expendable_income_rank_code,
ce_lhi_selected_apparel_general,
ce_lhi_selected_apparel_accessories,
ce_lhi_selected_apparel_kids,
ce_lhi_selected_apparel_mens,
ce_lhi_selected_apparel_mens_fashions,
ce_lhi_selected_apparel_womens,
ce_lhi_selected_apparel_womens_fashions,
ce_lhi_selected_automotive,
ce_lhi_selected_auto_racing,
ce_lhi_selected_auto_trucks,
ce_lhi_selected_aviation,
ce_lhi_selected_bargain_seekers,
ce_lhi_selected_beauty_cosmetic,
ce_lhi_selected_bible,
ce_lhi_selected_birds,
ce_lhi_selected_business_items,
ce_lhi_selected_business_home_office,
ce_lhi_selected_catalogs,
ce_lhi_selected_collectibles,
ce_lhi_household_collectibles_stamps_coins,
ce_lhi_selected_college,
ce_lhi_selected_computers,
ce_lhi_selected_cooking,
ce_lhi_selected_cooking_gourmet,
ce_lhi_selected_crafts_general,
ce_lhi_selected_crafts_crocheting,
ce_lhi_selected_crafts_knitting,
ce_lhi_selected_crafts_needlepoint,
ce_lhi_selected_crafts_quilting,
ce_lhi_selected_crafts_sewing,
ce_lhi_selected_culture_arts,
ce_lhi_selected_current_events,
ce_lhi_selected_do_it_yourselfer,
ce_lhi_selected_charitable_donor,
ce_lhi_selected_ego_personalized_products,
ce_lhi_selected_electronics,
ce_lhi_selected_equestrian,
ce_lhi_selected_ethnic_product_african_american,
ce_lhi_selected_ethnic_product_asian,
ce_lhi_selected_ethnic_product_hispanic,
ce_lhi_selected_family,
ce_lhi_selected_finance_credit_card_user,
ce_lhi_selected_finance_money_making,
ce_lhi_selected_finance_personal,
ce_lhi_household_finance_stocks_bonds,
ce_lhi_selected_gambling,
ce_lhi_selected_games,
ce_lhi_selected_gardening,
ce_lhi_selected_gift_giver,
ce_lhi_selected_health_general,
ce_lhi_selected_health_dieting,
ce_lhi_selected_health_fitness_exercise,
ce_lhi_household_high_ticket,
ce_lhi_selected_hightech,
ce_lhi_selected_history,
ce_lhi_selected_history_american,
ce_lhi_selected_hobbies,
ce_lhi_selected_home_decorating,
ce_lhi_selected_humor,
ce_lhi_selected_inspirational,
ce_lhi_selected_internet,
ce_lhi_selected_internet_access,
ce_lhi_selected_internet_buying,
ce_lhi_selected_motorcycles,
ce_lhi_selected_music,
ce_lhi_selected_ocean,
ce_lhi_selected_outdoors,
ce_lhi_selected_outdoors_boating_sailing,
ce_lhi_selected_outdoors_camping_hiking,
ce_lhi_selected_outdoors_fishing,
ce_lhi_selected_outdoors_hunting,
ce_lhi_selected_outdoors_hunting_fishing,
ce_lhi_selected_pets,
ce_lhi_selected_pets_cats,
ce_lhi_selected_pets_dogs,
ce_lhi_selected_photo_photography,
ce_lhi_selected_photo_photoprocessing,
ce_lhi_selected_politically_conservative,
ce_lhi_selected_politically_liberal,
ce_lhi_selected_publish_publications,
ce_lhi_selected_publish_books,
ce_lhi_selected_publish_fiction,
ce_lhi_selected_publish_magazine_subscriber,
ce_lhi_selected_publish_nonfiction,
ce_lhi_selected_publish_science_fiction,
ce_lhi_selected_rural_farming,
ce_lhi_selected_science,
ce_lhi_selected_seniors,
ce_lhi_selected_sports_general,
ce_lhi_selected_sports_baseball,
ce_lhi_selected_sports_basketball,
ce_lhi_selected_sports_football,
ce_lhi_selected_sports_golf,
ce_lhi_selected_sports_hockey,
ce_lhi_selected_sports_skiing,
ce_lhi_selected_sports_soccer,
ce_lhi_selected_sports_tennis,
ce_lhi_selected_stationery,
ce_lhi_selected_sweepstakes,
ce_lhi_household_technology_vcr,
ce_lhi_selected_tobacco,
ce_lhi_selected_travel_general,
ce_lhi_selected_travel_cruises,
ce_lhi_household_travel_foreign,
ce_lhi_selected_travel_rv,
ce_lhi_selected_travel_us,
ce_lhi_selected_tv_movies,
ce_lhi_selected_wildlife,
ce_mail_responsive_current_flag,
ce_mail_responsive_ever_flag,
ce_mail_responsive_previous_flag,
ce_online_purchase_personal_model,
ce_online_purchase_business_model,
ce_online_travel_plan_model,
ce_blog_writing_model,
ce_voice_over_internet_model,
ce_wifi_outside_of_home_model,
ce_wifi_in_home_model,
ce_wholesale_club_model,
ce_auto_club_model,
ce_diy_auto_maintenance_model,
ce_online_gaming_model,
ce_online_investment_trading_model,
ce_online_bill_payment_model,
ce_online_tv_download_model,
ce_mobile_internet_access_model,
ce_social_media_network_model,
ce_specialty_organic_food_store_model,
lems,
ce_selected_individual_formatted_date_of_birth,
ce_adventure_seekers_model,
ce_atv_model,
ce_annuities_model,
ce_avid_cell_phone_user_model,
ce_avid_gamers_model,
ce_avid_theme_park_visitor_model,
ce_baby_product_model,
ce_cat_product_model,
ce_conservative_model,
ce_cook_for_fun_model,
ce_cook_from_scratch_model,
ce_country_club_member_model,
ce_credit_card_rewards_model,
ce_cruise_model,
ce_diet_product_model,
ce_dog_product_model,
ce_donors_pbs_npr_model,
ce_foreign_travel_vacation_model,
ce_frequent_business_traveler_model,
ce_frequent_flyer_model,
ce_fresh_water_fishing_model,
ce_garden_maintenance_model,
ce_green_model,
ce_heavy_book_buyer_model,
ce_heavy_coupon_user_model,
ce_heavy_family_restaurant_visitor_model,
ce_frozen_dinner_model,
ce_heavy_investment_trader_model,
ce_heavy_payperview_movie_model,
ce_heavy_payperview_sports_model,
ce_heavy_vitamin_model,
ce_high_risk_investor_model,
ce_high_value_security_investor_model,
ce_high_value_stock_investor_model,
ce_high_end_electronic_model,
ce_high_end_sporting_equipment_model,
ce_higher_education_model,
ce_home_improvement_model,
ce_hunting_model,
ce_impulse_buyer_model,
ce_international_long_distance_model,
ce_leaning_conservative_model,
ce_leaning_liberal_model,
ce_liberal_model,
ce_life_insurance_model,
ce_live_theater_model,
ce_low_risk_investor_model,
ce_low_end_sporting_equipment_model,
ce_luxury_car_buyer_model,
ce_luxury_hotel_model,
ce_music_concert_classical_model,
ce_music_concert_country_model,
ce_music_concert_rock_model,
ce_nascar_model,
ce_onsite_tax_preparation_model,
ce_opinion_leader_model,
ce_organic_food_model,
ce_outdoor_activities_model,
ce_physical_fitness_club_model,
ce_power_boating_model,
ce_religious_donor_model,
ce_rental_car_model,
ce_safety_security_conscious_model,
ce_salt_water_fishing_model,
ce_shopaholics_model,
ce_college_basketball_model,
ce_college_football_model,
ce_golf_model,
ce_professional_baseball_model,
ce_professional_basketball_model,
ce_professional_football_model,
ce_professional_wrestling_model,
ce_soccer_model,
ce_tennis_model,
ce_pro_tax_preparation_model,
ce_timeshare_owner_model,
ce_wine_lover_model,
ce_environment_contributor_flag,
ce_health_contributor_flag,
ce_political_contributor_flag,
ce_religious_contributor_flag,
ce_donor_ever_contributor_flag,
ce_home_office_model,
ce_business_banking_model,
ce_moderate_economy_hotel_model,
ce_e_reader_model,
ce_cell_phone_only_model,
ce_alternative_medicine_model,
ce_non_religious_donor_model,
ce_major_home_remodeling_model,
ce_avid_smart_phone_users_model,
ce_health_insurance_model,
ce_satellite_tv_model,
ce_online_music_download_model,
ce_adult_education_model,
ce_pilates_yoga_model,
ce_fast_food_model,
ce_hybrid_cars_model,
ce_heavy_online_buyer_model,
ce_high_end_apparel_model,
ce_heavy_catalog_buyer_model,
ce_gift_buyers_model,
ce_camping_model,
ce_sports_fanatics_model,
ce_financial_planner_model,
ce_work_health_insurance_model,
ce_comprehensive_auto_insurance_model,
ce_small_business_insurance_model,
ce_heavy_snack_eaters_model,
ce_heavy_domestic_travelers_model,
ce_new_vehicle_buyer_model,
ce_suv_buyer_model,
ce_minivan_buyer_model,
ce_auto_loan_model,
ce_education_loan_model,
ce_real_estate_investment_model,
ce_fantasy_sports_model,
ce_hockey_buyer_model,
cons_unit_number,
ce_selected_ind_vendor_ethnicity_code,
ce_selected_ind_vendor_ethnic_group_code,
ce_selected_ind_vendor_spoken_language_code,
ce_selected_ind_vendor_religion_code,
bus_actual_location_employment_size,
bus_corporate_employment_size_code,
bus_actual_corporate_employment_size,
bus_actual_location_sales_volume,
bus_corporate_sales_volume_code,
bus_actual_corporate_sales_volume,
bus_square_footage,
bus_business_credit_score_code,
bus_business_credit_score,
bus_businessstatuscode,
bus_phonenumbertype,
bus_naics_code8,
bus_web_address_url,
bus_email_sha256_upper,
bus_email_sha256_lower,
con_email_sha256_upper,
con_email_sha256_lower,
bus_email_sha1_upper,
bus_email_sha1_lower,
con_email_sha1_upper,
con_email_sha1_lower,
cons_firstname,
cons_lastname,
busimatchcode,
buscmatchcode,
consimatchcode,
conshmatchcode,
busyearfirstappeared,
busyearCode)
FROM 's3://{s3-internal}{s3-2722internal-path}{s3-execureach}'
IAM_ROLE '{iam}'
ACCEPTINVCHARS
IGNOREBLANKLINES
FIXEDWIDTH
'bus_abinumber:9,
bus_contactname:30,
bus_companyname:30,
bus_address:30,
bus_city:18,
bus_state:2,
bus_zipcode:5,
bus_zipfour:4,
bus_phonenumber:10,
bus_countycode:3,
bus_titlecode:1,
bus_titlecodedescription:30,
bus_employeesizecode:1,
bus_locationoutputvolumecode:1,
bus_primarysiccode:6,
cons_address:30,
cons_city:18,
cons_state:2,
cons_zipcode:5,
cons_zipfour:4,
cons_phonenumber:10,
cons_countycode:3,
cons_locationtype:1,
cons_gender:1,
cons_age:2,
cons_income:1,
cons_name:30,
cons_maritalstatus:1,
cons_creditcardholder:1,
cons_ownrent:1,
matchflag:1,
cons_individualid:12,
cons_familyid:12,
bus_executivesourcecode:5,
bus_executiveid:9,
bus_contactflag:2,
bus_fulfillmentflag:1,
bus_emailaddress:80,
bus_vendorid:2,
bus_cbsa:5,
bus_cbsalevel:1,
bus_companyholdingstatus:1,
bus_cottagecode:1,
bus_mailscore:2,
cons_emailaddress:80,
cons_vendorid:2,
cons_statecode:2,
cons_mailconfidence:2,
cons_presenceofemail:1,
recordtypeindicator:1,
execureachquality:2,
bus_contactquality:1,
matchquality:1,
bus_contactliteraltitlecode:8,
firstname:15,
middleinitial:1,
lastname:20,
bus_contactid:12,
bus_professionaltitle:3,
bus_functionalareacode:4,
bus_rolecode:4,
bus_digitalflag:1,
con_digitalflag:1,
distancecode:1,
bus_bvtscore:1,
cons_bvtscore:1,
filler_1:7,
filler_2:5,
bus_modeledemployeesizeflag:1,
filler_3:9,
bus_location_outputvolumetypcode:1,
bus_corporate_employeecount:6,
bus_corporate_employeerange:1,
bus_corporate_employeesourceindicator:1,
bus_corporate_salesvolumeamount:9,
bus_corporate_salesvolumerange:1,
bus_corporate_salesvolumesourceindicator:1,
filler_4:1,
filler_5:1,
con_carrierroutecode:4,
con_homevalue:1,
bus_email_md5_upper:32,
bus_email_md5_lower:32,
cons_email_md5_upper:32,
cons_email_md5_lower:32,
ce_expendable_income_rank_code:1,
ce_lhi_selected_apparel_general:1,
ce_lhi_selected_apparel_accessories:1,
ce_lhi_selected_apparel_kids:1,
ce_lhi_selected_apparel_mens:1,
ce_lhi_selected_apparel_mens_fashions:1,
ce_lhi_selected_apparel_womens:1,
ce_lhi_selected_apparel_womens_fashions:1,
ce_lhi_selected_automotive:1,
ce_lhi_selected_auto_racing:1,
ce_lhi_selected_auto_trucks:1,
ce_lhi_selected_aviation:1,
ce_lhi_selected_bargain_seekers:1,
ce_lhi_selected_beauty_cosmetic:1,
ce_lhi_selected_bible:1,
ce_lhi_selected_birds:1,
ce_lhi_selected_business_items:1,
ce_lhi_selected_business_home_office:1,
ce_lhi_selected_catalogs:1,
ce_lhi_selected_collectibles:1,
ce_lhi_household_collectibles_stamps_coins:1,
ce_lhi_selected_college:1,
ce_lhi_selected_computers:1,
ce_lhi_selected_cooking:1,
ce_lhi_selected_cooking_gourmet:1,
ce_lhi_selected_crafts_general:1,
ce_lhi_selected_crafts_crocheting:1,
ce_lhi_selected_crafts_knitting:1,
ce_lhi_selected_crafts_needlepoint:1,
ce_lhi_selected_crafts_quilting:1,
ce_lhi_selected_crafts_sewing:1,
ce_lhi_selected_culture_arts:1,
ce_lhi_selected_current_events:1,
ce_lhi_selected_do_it_yourselfer:1,
ce_lhi_selected_charitable_donor:1,
ce_lhi_selected_ego_personalized_products:1,
ce_lhi_selected_electronics:1,
ce_lhi_selected_equestrian:1,
ce_lhi_selected_ethnic_product_african_american:1,
ce_lhi_selected_ethnic_product_asian:1,
ce_lhi_selected_ethnic_product_hispanic:1,
ce_lhi_selected_family:1,
ce_lhi_selected_finance_credit_card_user:1,
ce_lhi_selected_finance_money_making:1,
ce_lhi_selected_finance_personal:1,
ce_lhi_household_finance_stocks_bonds:1,
ce_lhi_selected_gambling:1,
ce_lhi_selected_games:1,
ce_lhi_selected_gardening:1,
ce_lhi_selected_gift_giver:1,
ce_lhi_selected_health_general:1,
ce_lhi_selected_health_dieting:1,
ce_lhi_selected_health_fitness_exercise:1,
ce_lhi_household_high_ticket:1,
ce_lhi_selected_hightech:1,
ce_lhi_selected_history:1,
ce_lhi_selected_history_american:1,
ce_lhi_selected_hobbies:1,
ce_lhi_selected_home_decorating:1,
ce_lhi_selected_humor:1,
ce_lhi_selected_inspirational:1,
ce_lhi_selected_internet:1,
ce_lhi_selected_internet_access:1,
ce_lhi_selected_internet_buying:1,
ce_lhi_selected_motorcycles:1,
ce_lhi_selected_music:1,
ce_lhi_selected_ocean:1,
ce_lhi_selected_outdoors:1,
ce_lhi_selected_outdoors_boating_sailing:1,
ce_lhi_selected_outdoors_camping_hiking:1,
ce_lhi_selected_outdoors_fishing:1,
ce_lhi_selected_outdoors_hunting:1,
ce_lhi_selected_outdoors_hunting_fishing:1,
ce_lhi_selected_pets:1,
ce_lhi_selected_pets_cats:1,
ce_lhi_selected_pets_dogs:1,
ce_lhi_selected_photo_photography:1,
ce_lhi_selected_photo_photoprocessing:1,
ce_lhi_selected_politically_conservative:1,
ce_lhi_selected_politically_liberal:1,
ce_lhi_selected_publish_publications:1,
ce_lhi_selected_publish_books:1,
ce_lhi_selected_publish_fiction:1,
ce_lhi_selected_publish_magazine_subscriber:1,
ce_lhi_selected_publish_nonfiction:1,
ce_lhi_selected_publish_science_fiction:1,
ce_lhi_selected_rural_farming:1,
ce_lhi_selected_science:1,
ce_lhi_selected_seniors:1,
ce_lhi_selected_sports_general:1,
ce_lhi_selected_sports_baseball:1,
ce_lhi_selected_sports_basketball:1,
ce_lhi_selected_sports_football:1,
ce_lhi_selected_sports_golf:1,
ce_lhi_selected_sports_hockey:1,
ce_lhi_selected_sports_skiing:1,
ce_lhi_selected_sports_soccer:1,
ce_lhi_selected_sports_tennis:1,
ce_lhi_selected_stationery:1,
ce_lhi_selected_sweepstakes:1,
ce_lhi_household_technology_vcr:1,
ce_lhi_selected_tobacco:1,
ce_lhi_selected_travel_general:1,
ce_lhi_selected_travel_cruises:1,
ce_lhi_household_travel_foreign:1,
ce_lhi_selected_travel_rv:1,
ce_lhi_selected_travel_us:1,
ce_lhi_selected_tv_movies:1,
ce_lhi_selected_wildlife:1,
ce_mail_responsive_current_flag:1,
ce_mail_responsive_ever_flag:1,
ce_mail_responsive_previous_flag:1,
ce_online_purchase_personal_model:1,
ce_online_purchase_business_model:1,
ce_online_travel_plan_model:1,
ce_blog_writing_model:1,
ce_voice_over_internet_model:1,
ce_wifi_outside_of_home_model:1,
ce_wifi_in_home_model:1,
ce_wholesale_club_model:1,
ce_auto_club_model:1,
ce_diy_auto_maintenance_model:1,
ce_online_gaming_model:1,
ce_online_investment_trading_model:1,
ce_online_bill_payment_model:1,
ce_online_tv_download_model:1,
ce_mobile_internet_access_model:1,
ce_social_media_network_model:1,
ce_specialty_organic_food_store_model:1,
lems:18,
ce_selected_individual_formatted_date_of_birth:10,
ce_adventure_seekers_model:1,
ce_atv_model:1,
ce_annuities_model:1,
ce_avid_cell_phone_user_model:1,
ce_avid_gamers_model:1,
ce_avid_theme_park_visitor_model:1,
ce_baby_product_model:1,
ce_cat_product_model:1,
ce_conservative_model:1,
ce_cook_for_fun_model:1,
ce_cook_from_scratch_model:1,
ce_country_club_member_model:1,
ce_credit_card_rewards_model:1,
ce_cruise_model:1,
ce_diet_product_model:1,
ce_dog_product_model:1,
ce_donors_pbs_npr_model:1,
ce_foreign_travel_vacation_model:1,
ce_frequent_business_traveler_model:1,
ce_frequent_flyer_model:1,
ce_fresh_water_fishing_model:1,
ce_garden_maintenance_model:1,
ce_green_model:1,
ce_heavy_book_buyer_model:1,
ce_heavy_coupon_user_model:1,
ce_heavy_family_restaurant_visitor_model:1,
ce_frozen_dinner_model:1,
ce_heavy_investment_trader_model:1,
ce_heavy_payperview_movie_model:1,
ce_heavy_payperview_sports_model:1,
ce_heavy_vitamin_model:1,
ce_high_risk_investor_model:1,
ce_high_value_security_investor_model:1,
ce_high_value_stock_investor_model:1,
ce_high_end_electronic_model:1,
ce_high_end_sporting_equipment_model:1,
ce_higher_education_model:1,
ce_home_improvement_model:1,
ce_hunting_model:1,
ce_impulse_buyer_model:1,
ce_international_long_distance_model:1,
ce_leaning_conservative_model:1,
ce_leaning_liberal_model:1,
ce_liberal_model:1,
ce_life_insurance_model:1,
ce_live_theater_model:1,
ce_low_risk_investor_model:1,
ce_low_end_sporting_equipment_model:1,
ce_luxury_car_buyer_model:1,
ce_luxury_hotel_model:1,
ce_music_concert_classical_model:1,
ce_music_concert_country_model:1,
ce_music_concert_rock_model:1,
ce_nascar_model:1,
ce_onsite_tax_preparation_model:1,
ce_opinion_leader_model:1,
ce_organic_food_model:1,
ce_outdoor_activities_model:1,
ce_physical_fitness_club_model:1,
ce_power_boating_model:1,
ce_religious_donor_model:1,
ce_rental_car_model:1,
ce_safety_security_conscious_model:1,
ce_salt_water_fishing_model:1,
ce_shopaholics_model:1,
ce_college_basketball_model:1,
ce_college_football_model:1,
ce_golf_model:1,
ce_professional_baseball_model:1,
ce_professional_basketball_model:1,
ce_professional_football_model:1,
ce_professional_wrestling_model:1,
ce_soccer_model:1,
ce_tennis_model:1,
ce_pro_tax_preparation_model:1,
ce_timeshare_owner_model:1,
ce_wine_lover_model:1,
ce_environment_contributor_flag:1,
ce_health_contributor_flag:1,
ce_political_contributor_flag:1,
ce_religious_contributor_flag:1,
ce_donor_ever_contributor_flag:1,
ce_home_office_model:1,
ce_business_banking_model:1,
ce_moderate_economy_hotel_model:1,
ce_e_reader_model:1,
ce_cell_phone_only_model:1,
ce_alternative_medicine_model:1,
ce_non_religious_donor_model:1,
ce_major_home_remodeling_model:1,
ce_avid_smart_phone_users_model:1,
ce_health_insurance_model:1,
ce_satellite_tv_model:1,
ce_online_music_download_model:1,
ce_adult_education_model:1,
ce_pilates_yoga_model:1,
ce_fast_food_model:1,
ce_hybrid_cars_model:1,
ce_heavy_online_buyer_model:1,
ce_high_end_apparel_model:1,
ce_heavy_catalog_buyer_model:1,
ce_gift_buyers_model:1,
ce_camping_model:1,
ce_sports_fanatics_model:1,
ce_financial_planner_model:1,
ce_work_health_insurance_model:1,
ce_comprehensive_auto_insurance_model:1,
ce_small_business_insurance_model:1,
ce_heavy_snack_eaters_model:1,
ce_heavy_domestic_travelers_model:1,
ce_new_vehicle_buyer_model:1,
ce_suv_buyer_model:1,
ce_minivan_buyer_model:1,
ce_auto_loan_model:1,
ce_education_loan_model:1,
ce_real_estate_investment_model:1,
ce_fantasy_sports_model:1,
ce_hockey_buyer_model:1,
cons_unit_number:8,
ce_selected_ind_vendor_ethnicity_code:2,
ce_selected_ind_vendor_ethnic_group_code:1,
ce_selected_ind_vendor_spoken_language_code:2,
ce_selected_ind_vendor_religion_code:1,
bus_actual_location_employment_size:5,
bus_corporate_employment_size_code:1,
bus_actual_corporate_employment_size:6,
bus_actual_location_sales_volume:9,
bus_corporate_sales_volume_code:1,
bus_actual_corporate_sales_volume:9,
bus_square_footage:1,
bus_business_credit_score_code:2,
bus_business_credit_score:3,
bus_businessstatuscode:1,
bus_phonenumbertype:1,
bus_naics_code8:8,
bus_web_address_url:40,
bus_email_sha256_upper:64,
bus_email_sha256_lower:64,
con_email_sha256_upper:64,
con_email_sha256_lower:64,
bus_email_sha1_upper:40,
bus_email_sha1_lower:40,
con_email_sha1_upper:40,
con_email_sha1_lower:40,
cons_firstname:25,
cons_lastname:30,
busimatchcode:17,
buscmatchcode:15,
consimatchcode:17,
conshmatchcode:17,
busyearfirstappeared:4,
busyearCode:1';