DROP TABLE IF EXISTS #DDValues;
SELECT LTRIM(RTRIM(UPPER(cfieldname))) AS cfieldname, 
	   LTRIM(RTRIM(UPPER(cvalue)))AS cvalue, 
	   LTRIM(RTRIM(cdescription))AS cdescription 
INTO #DDValues FROM sql_tblDDDescriptions 
WHERE  databaseid = 1150 AND 
	   LTRIM(RTRIM(cfieldname)) IN ('BUS_CORPORATE_SALESVOLUMERANGE', 'BUS_CORPORATE_EMPLOYEERANGE','BUS_NAICS_CODE8') AND 
	   (cvalue !='' OR cdescription !='')
GROUP BY cfieldname,cvalue,cdescription;

DROP TABLE IF EXISTS {maintable_name};
CREATE TABLE {maintable_name}
(
	bus_abinumber VARCHAR(9)  ENCODE zstd,
	bus_contactname VARCHAR(30)  ENCODE zstd,
	bus_companyname VARCHAR(30)  ENCODE zstd,
	bus_address VARCHAR(30)  ENCODE zstd,
	bus_city VARCHAR(18)  ENCODE zstd,
	bus_state VARCHAR(2)  ENCODE bytedict,
	bus_zipcode VARCHAR(5)  ENCODE zstd,
	bus_zipfour VARCHAR(4)  ENCODE zstd,
	bus_phonenumber VARCHAR(10)  ENCODE zstd,
	bus_countycode VARCHAR(3)  ENCODE bytedict,
	bus_titlecode VARCHAR(1)  ENCODE zstd,
	bus_titlecodedescription VARCHAR(30)  ENCODE bytedict,
	bus_employeesizecode VARCHAR(1)  ENCODE zstd,
	bus_locationoutputvolumecode VARCHAR(1)  ENCODE zstd,
	bus_primarysiccode VARCHAR(6)  ENCODE zstd,
	cons_address VARCHAR(30)  ENCODE zstd,
	cons_city VARCHAR(18)  ENCODE zstd,
	cons_state VARCHAR(2)  ENCODE bytedict,
	cons_zipcode VARCHAR(5)  ENCODE zstd,
	cons_zipfour VARCHAR(4)  ENCODE zstd,
	cons_phonenumber VARCHAR(10)  ENCODE zstd,
	cons_countycode VARCHAR(3)  ENCODE bytedict,
	cons_locationtype VARCHAR(1)  ENCODE zstd,
	cons_gender VARCHAR(1)  ENCODE zstd,
	cons_age VARCHAR(2)  ENCODE bytedict,
	cons_income VARCHAR(1)  ENCODE zstd,
	cons_name VARCHAR(30)  ENCODE zstd,
	cons_maritalstatus VARCHAR(1)  ENCODE zstd,
	cons_creditcardholder VARCHAR(1)  ENCODE zstd,
	cons_ownrent VARCHAR(1)  ENCODE zstd,
	matchflag VARCHAR(1)  ENCODE zstd,
	cons_individualid VARCHAR(12)  ENCODE zstd,
	cons_familyid VARCHAR(12)  ENCODE zstd,
	bus_executivesourcecode VARCHAR(5)  ENCODE zstd,
	bus_executiveid VARCHAR(9)  ENCODE zstd,
	bus_contactflag VARCHAR(2)  ENCODE zstd,
	bus_fulfillmentflag VARCHAR(1)  ENCODE zstd,
	bus_emailaddress VARCHAR(80)  ENCODE zstd,
	bus_vendorid VARCHAR(2)  ENCODE zstd,
	bus_cbsa VARCHAR(5)  ENCODE zstd,
	bus_cbsalevel VARCHAR(1)  ENCODE zstd,
	bus_companyholdingstatus VARCHAR(1)  ENCODE zstd,
	bus_cottagecode VARCHAR(1)  ENCODE zstd,
	bus_mailscore VARCHAR(2)  ENCODE zstd,
	cons_emailaddress VARCHAR(80)  ENCODE zstd,
	cons_vendorid VARCHAR(2)  ENCODE zstd,
	cons_statecode VARCHAR(2)  ENCODE bytedict,
	cons_mailconfidence VARCHAR(2)  ENCODE zstd,
	cons_presenceofemail VARCHAR(1)  ENCODE zstd,
	recordtypeindicator VARCHAR(1)  ENCODE zstd,
	execureachquality VARCHAR(2)  ENCODE zstd,
	bus_contactquality VARCHAR(1)  ENCODE zstd,
	matchquality VARCHAR(1)  ENCODE zstd,
	bus_contactliteraltitlecode VARCHAR(8)  ENCODE zstd,
	firstname VARCHAR(15)  ENCODE zstd,
	middleinitial VARCHAR(1)  ENCODE zstd,
	lastname VARCHAR(20)  ENCODE zstd,
	bus_contactid VARCHAR(12)  ENCODE zstd,
	bus_professionaltitle VARCHAR(3)  ENCODE zstd,
	bus_functionalareacode VARCHAR(4) ENCODE bytedict,
	bus_rolecode VARCHAR(4) ENCODE zstd,
	bus_digitalflag VARCHAR(1) ENCODE zstd,
	con_digitalflag VARCHAR(1) ENCODE zstd,
	distancecode VARCHAR(1) ENCODE zstd,
	bus_bvtscore VARCHAR(1) ENCODE zstd,
	cons_bvtscore VARCHAR(1) ENCODE zstd,
	bus_modeledemployeesizeflag VARCHAR(1) ENCODE zstd,
 	bus_location_outputvolumetypcode VARCHAR(1) ENCODE zstd,
	bus_corporate_employeecount VARCHAR(6) ENCODE zstd,
	bus_corporate_employeerange VARCHAR(1) ENCODE zstd,
	bus_corporate_employeesourceindicator VARCHAR(1) ENCODE zstd,
	bus_corporate_salesvolumeamount VARCHAR(9) ENCODE zstd,
	bus_corporate_salesvolumerange VARCHAR(1) ENCODE zstd,
	bus_corporate_salesvolumesourceindicator VARCHAR(1) ENCODE zstd,
	con_carrierroutecode VARCHAR(4) ENCODE bytedict,
	con_homevalue VARCHAR(1) ENCODE zstd,
	bus_email_md5_upper VARCHAR(32)  ENCODE zstd,
	bus_email_md5_lower VARCHAR(32)  ENCODE zstd,
	cons_email_md5_upper VARCHAR(32)  ENCODE zstd,
	cons_email_md5_lower VARCHAR(32)  ENCODE zstd,
	ce_expendable_income_rank_code VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_apparel_general VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_apparel_accessories VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_apparel_kids VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_apparel_mens VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_apparel_mens_fashions VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_apparel_womens VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_apparel_womens_fashions VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_automotive VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_auto_racing VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_auto_trucks VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_aviation VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_bargain_seekers VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_beauty_cosmetic VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_bible VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_birds VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_business_items VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_business_home_office VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_catalogs VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_collectibles VARCHAR(1)  ENCODE zstd,
	ce_lhi_household_collectibles_stamps_coins VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_college VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_computers VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_cooking VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_cooking_gourmet VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_crafts_general VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_crafts_crocheting VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_crafts_knitting VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_crafts_needlepoint VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_crafts_quilting VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_crafts_sewing VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_culture_arts VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_current_events VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_do_it_yourselfer VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_charitable_donor VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_ego_personalized_products VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_electronics VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_equestrian VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_ethnic_product_african_american VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_ethnic_product_asian VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_ethnic_product_hispanic VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_family VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_finance_credit_card_user VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_finance_money_making VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_finance_personal VARCHAR(1)  ENCODE zstd,
	ce_lhi_household_finance_stocks_bonds VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_gambling VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_games VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_gardening VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_gift_giver VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_health_general VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_health_dieting VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_health_fitness_exercise VARCHAR(1)  ENCODE zstd,
	ce_lhi_household_high_ticket VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_hightech VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_history VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_history_american VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_hobbies VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_home_decorating VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_humor VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_inspirational VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_internet VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_internet_access VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_internet_buying VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_motorcycles VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_music VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_ocean VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_outdoors VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_outdoors_boating_sailing VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_outdoors_camping_hiking VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_outdoors_fishing VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_outdoors_hunting VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_outdoors_hunting_fishing VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_pets VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_pets_cats VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_pets_dogs VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_photo_photography VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_photo_photoprocessing VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_politically_conservative VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_politically_liberal VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_publish_publications VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_publish_books VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_publish_fiction VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_publish_magazine_subscriber VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_publish_nonfiction VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_publish_science_fiction VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_rural_farming VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_science VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_seniors VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_general VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_baseball VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_basketball VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_football VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_golf VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_hockey VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_skiing VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_soccer VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sports_tennis VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_stationery VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_sweepstakes VARCHAR(1)  ENCODE zstd,
	ce_lhi_household_technology_vcr VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_tobacco VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_travel_general VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_travel_cruises VARCHAR(1)  ENCODE zstd,
	ce_lhi_household_travel_foreign VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_travel_rv VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_travel_us VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_tv_movies VARCHAR(1)  ENCODE zstd,
	ce_lhi_selected_wildlife VARCHAR(1)  ENCODE zstd,
	ce_mail_responsive_current_flag VARCHAR(1)  ENCODE zstd,
	ce_mail_responsive_ever_flag VARCHAR(1)  ENCODE zstd,
	ce_mail_responsive_previous_flag VARCHAR(1)  ENCODE zstd,
	ce_online_purchase_personal_model VARCHAR(1)  ENCODE zstd,
	ce_online_purchase_business_model VARCHAR(1)  ENCODE zstd,
	ce_online_travel_plan_model VARCHAR(1)  ENCODE zstd,
	ce_blog_writing_model VARCHAR(1)  ENCODE zstd,
	ce_voice_over_internet_model VARCHAR(1)  ENCODE zstd,
	ce_wifi_outside_of_home_model VARCHAR(1)  ENCODE zstd,
	ce_wifi_in_home_model VARCHAR(1)  ENCODE zstd,
	ce_wholesale_club_model VARCHAR(1)  ENCODE zstd,
	ce_auto_club_model VARCHAR(1)  ENCODE zstd,
	ce_diy_auto_maintenance_model VARCHAR(1)  ENCODE zstd,
	ce_online_gaming_model VARCHAR(1)  ENCODE zstd,
	ce_online_investment_trading_model VARCHAR(1)  ENCODE zstd,
	ce_online_bill_payment_model VARCHAR(1)  ENCODE zstd,
	ce_online_tv_download_model VARCHAR(1)  ENCODE zstd,
	ce_mobile_internet_access_model VARCHAR(1)  ENCODE zstd,
	ce_social_media_network_model VARCHAR(1)  ENCODE zstd,
	ce_specialty_organic_food_store_model VARCHAR(1)  ENCODE zstd,
	lems VARCHAR(18)  ENCODE zstd,
	ce_selected_individual_formatted_date_of_birth VARCHAR(10)  ENCODE zstd,
	ce_adventure_seekers_model VARCHAR(1)  ENCODE zstd,
	ce_atv_model VARCHAR(1)  ENCODE zstd,
	ce_annuities_model VARCHAR(1)  ENCODE zstd,
	ce_avid_cell_phone_user_model VARCHAR(1)  ENCODE zstd,
	ce_avid_gamers_model VARCHAR(1)  ENCODE zstd,
	ce_avid_theme_park_visitor_model VARCHAR(1)  ENCODE zstd,
	ce_baby_product_model VARCHAR(1)  ENCODE zstd,
	ce_cat_product_model VARCHAR(1)  ENCODE zstd,
	ce_conservative_model VARCHAR(1)  ENCODE zstd,
	ce_cook_for_fun_model VARCHAR(1)  ENCODE zstd,
	ce_cook_from_scratch_model VARCHAR(1)  ENCODE zstd,
	ce_country_club_member_model VARCHAR(1)  ENCODE zstd,
	ce_credit_card_rewards_model VARCHAR(1)  ENCODE zstd,
	ce_cruise_model VARCHAR(1)  ENCODE zstd,
	ce_diet_product_model VARCHAR(1)  ENCODE zstd,
	ce_dog_product_model VARCHAR(1)  ENCODE zstd,
	ce_donors_pbs_npr_model VARCHAR(1)  ENCODE zstd,
	ce_foreign_travel_vacation_model VARCHAR(1)  ENCODE zstd,
	ce_frequent_business_traveler_model VARCHAR(1)  ENCODE zstd,
	ce_frequent_flyer_model VARCHAR(1)  ENCODE zstd,
	ce_fresh_water_fishing_model VARCHAR(1)  ENCODE zstd,
	ce_garden_maintenance_model VARCHAR(1)  ENCODE zstd,
	ce_green_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_book_buyer_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_coupon_user_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_family_restaurant_visitor_model VARCHAR(1)  ENCODE zstd,
	ce_frozen_dinner_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_investment_trader_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_payperview_movie_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_payperview_sports_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_vitamin_model VARCHAR(1)  ENCODE zstd,
	ce_high_risk_investor_model VARCHAR(1)  ENCODE zstd,
	ce_high_value_security_investor_model VARCHAR(1)  ENCODE zstd,
	ce_high_value_stock_investor_model VARCHAR(1)  ENCODE zstd,
	ce_high_end_electronic_model VARCHAR(1)  ENCODE zstd,
	ce_high_end_sporting_equipment_model VARCHAR(1)  ENCODE zstd,
	ce_higher_education_model VARCHAR(1)  ENCODE zstd,
	ce_home_improvement_model VARCHAR(1)  ENCODE zstd,
	ce_hunting_model VARCHAR(1)  ENCODE zstd,
	ce_impulse_buyer_model VARCHAR(1)  ENCODE zstd,
	ce_international_long_distance_model VARCHAR(1)  ENCODE zstd,
	ce_leaning_conservative_model VARCHAR(1)  ENCODE zstd,
	ce_leaning_liberal_model VARCHAR(1)  ENCODE zstd,
	ce_liberal_model VARCHAR(1)  ENCODE zstd,
	ce_life_insurance_model VARCHAR(1)  ENCODE zstd,
	ce_live_theater_model VARCHAR(1)  ENCODE zstd,
	ce_low_risk_investor_model VARCHAR(1)  ENCODE zstd,
	ce_low_end_sporting_equipment_model VARCHAR(1)  ENCODE zstd,
	ce_luxury_car_buyer_model VARCHAR(1)  ENCODE zstd,
	ce_luxury_hotel_model VARCHAR(1)  ENCODE zstd,
	ce_music_concert_classical_model VARCHAR(1)  ENCODE zstd,
	ce_music_concert_country_model VARCHAR(1)  ENCODE zstd,
	ce_music_concert_rock_model VARCHAR(1)  ENCODE zstd,
	ce_nascar_model VARCHAR(1)  ENCODE zstd,
	ce_onsite_tax_preparation_model VARCHAR(1)  ENCODE zstd,
	ce_opinion_leader_model VARCHAR(1)  ENCODE zstd,
	ce_organic_food_model VARCHAR(1)  ENCODE zstd,
	ce_outdoor_activities_model VARCHAR(1)  ENCODE zstd,
	ce_physical_fitness_club_model VARCHAR(1)  ENCODE zstd,
	ce_power_boating_model VARCHAR(1)  ENCODE zstd,
	ce_religious_donor_model VARCHAR(1)  ENCODE zstd,
	ce_rental_car_model VARCHAR(1)  ENCODE zstd,
	ce_safety_security_conscious_model VARCHAR(1)  ENCODE zstd,
	ce_salt_water_fishing_model VARCHAR(1)  ENCODE zstd,
	ce_shopaholics_model VARCHAR(1)  ENCODE zstd,
	ce_college_basketball_model VARCHAR(1)  ENCODE zstd,
	ce_college_football_model VARCHAR(1)  ENCODE zstd,
	ce_golf_model VARCHAR(1)  ENCODE zstd,
	ce_professional_baseball_model VARCHAR(1)  ENCODE zstd,
	ce_professional_basketball_model VARCHAR(1)  ENCODE zstd,
	ce_professional_football_model VARCHAR(1)  ENCODE zstd,
	ce_professional_wrestling_model VARCHAR(1)  ENCODE zstd,
	ce_soccer_model VARCHAR(1)  ENCODE zstd,
	ce_tennis_model VARCHAR(1)  ENCODE zstd,
	ce_pro_tax_preparation_model VARCHAR(1)  ENCODE zstd,
	ce_timeshare_owner_model VARCHAR(1)  ENCODE zstd,
	ce_wine_lover_model VARCHAR(1)  ENCODE zstd,
	ce_environment_contributor_flag VARCHAR(1)  ENCODE zstd,
	ce_health_contributor_flag VARCHAR(1)  ENCODE zstd,
	ce_political_contributor_flag VARCHAR(1)  ENCODE zstd,
	ce_religious_contributor_flag VARCHAR(1)  ENCODE zstd,
	ce_donor_ever_contributor_flag VARCHAR(1)  ENCODE zstd,
	ce_home_office_model VARCHAR(1)  ENCODE zstd,
	ce_business_banking_model VARCHAR(1)  ENCODE zstd,
	ce_moderate_economy_hotel_model VARCHAR(1)  ENCODE zstd,
	ce_e_reader_model VARCHAR(1)  ENCODE zstd,
	ce_cell_phone_only_model VARCHAR(1)  ENCODE zstd,
	ce_alternative_medicine_model VARCHAR(1)  ENCODE zstd,
	ce_non_religious_donor_model VARCHAR(1)  ENCODE zstd,
	ce_major_home_remodeling_model VARCHAR(1)  ENCODE zstd,
	ce_avid_smart_phone_users_model VARCHAR(1)  ENCODE zstd,
	ce_health_insurance_model VARCHAR(1)  ENCODE zstd,
	ce_satellite_tv_model VARCHAR(1)  ENCODE zstd,
	ce_online_music_download_model VARCHAR(1)  ENCODE zstd,
	ce_adult_education_model VARCHAR(1)  ENCODE zstd,
	ce_pilates_yoga_model VARCHAR(1)  ENCODE zstd,
	ce_fast_food_model VARCHAR(1)  ENCODE zstd,
	ce_hybrid_cars_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_online_buyer_model VARCHAR(1)  ENCODE zstd,
	ce_high_end_apparel_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_catalog_buyer_model VARCHAR(1)  ENCODE zstd,
	ce_gift_buyers_model VARCHAR(1)  ENCODE zstd,
	ce_camping_model VARCHAR(1)  ENCODE zstd,
	ce_sports_fanatics_model VARCHAR(1)  ENCODE zstd,
	ce_financial_planner_model VARCHAR(1)  ENCODE zstd,
	ce_work_health_insurance_model VARCHAR(1)  ENCODE zstd,
	ce_comprehensive_auto_insurance_model VARCHAR(1)  ENCODE zstd,
	ce_small_business_insurance_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_snack_eaters_model VARCHAR(1)  ENCODE zstd,
	ce_heavy_domestic_travelers_model VARCHAR(1)  ENCODE zstd,
	ce_new_vehicle_buyer_model VARCHAR(1)  ENCODE zstd,
	ce_suv_buyer_model VARCHAR(1)  ENCODE zstd,
	ce_minivan_buyer_model VARCHAR(1)  ENCODE zstd,
	ce_auto_loan_model VARCHAR(1)  ENCODE zstd,
	ce_education_loan_model VARCHAR(1)  ENCODE zstd,
	ce_real_estate_investment_model VARCHAR(1)  ENCODE zstd,
	ce_fantasy_sports_model VARCHAR(1)  ENCODE zstd,
	ce_hockey_buyer_model VARCHAR(1) ENCODE zstd,
	cons_unit_number VARCHAR(8) ENCODE zstd,
	ce_selected_ind_vendor_ethnicity_code VARCHAR(2) ENCODE zstd,
	ce_selected_ind_vendor_ethnic_group_code VARCHAR (1) ENCODE zstd,
	ce_selected_ind_vendor_spoken_language_code VARCHAR (2) ENCODE zstd,
	ce_selected_ind_vendor_religion_code VARCHAR (1) ENCODE zstd,
	bus_actual_location_employment_size VARCHAR(5) ENCODE bytedict,
	bus_corporate_employment_size_code VARCHAR(1) ENCODE zstd,
	bus_actual_corporate_employment_size VARCHAR(6) ENCODE zstd,
	bus_actual_location_sales_volume VARCHAR(9) ENCODE zstd,
	bus_corporate_sales_volume_code VARCHAR(1) ENCODE zstd,
	bus_actual_corporate_sales_volume VARCHAR(9) ENCODE zstd,
	bus_square_footage VARCHAR(1) ENCODE zstd,
	bus_business_credit_score_code VARCHAR(2) ENCODE zstd,
	bus_business_credit_score VARCHAR(3) ENCODE bytedict,
	bus_businessstatuscode VARCHAR(1) ENCODE zstd,
	bus_phonenumbertype VARCHAR(1) ENCODE zstd,
	bus_naics_code8 VARCHAR(8) ENCODE zstd,
    bus_web_address_url VARCHAR(40) ENCODE zstd,
	bus_email_sha256_upper VARCHAR(64) ENCODE zstd,
	bus_email_sha256_lower VARCHAR(64) ENCODE zstd,
	con_email_sha256_upper VARCHAR(64) ENCODE zstd,
	con_email_sha256_lower VARCHAR(64) ENCODE zstd,
	bus_email_sha1_upper VARCHAR(40) ENCODE zstd,
	bus_email_sha1_lower VARCHAR(40) ENCODE zstd,
	con_email_sha1_upper VARCHAR(40) ENCODE zstd,
	con_email_sha1_lower VARCHAR(40) ENCODE zstd,
	cons_firstname VARCHAR(25) ENCODE zstd,
	cons_lastname VARCHAR(30) ENCODE zstd,
	busimatchcode VARCHAR(17) ENCODE zstd,
	buscmatchcode VARCHAR(15) ENCODE zstd,
	consimatchcode VARCHAR(17) ENCODE zstd,
	conshmatchcode VARCHAR(17) ENCODE zstd,
    busyearfirstappeared VARCHAR(4) ENCODE zstd,
    busyearCode VARCHAR(1) ENCODE zstd,
	id BIGINT UNIQUE distkey sortkey ENCODE az64,
	listid INT ENCODE az64,
	permissiontype VARCHAR(1) ENCODE zstd,
	listtype VARCHAR(1) ENCODE lzo,
	productcode VARCHAR(1) ENCODE lzo,
	dropflag VARCHAR(1) ENCODE lzo,
	zipradius VARCHAR(1) ENCODE lzo,
	gender VARCHAR(1) ENCODE lzo,
	zip VARCHAR(5) ENCODE zstd,
	bus_scf VARCHAR(3) ENCODE zstd,
	con_scf VARCHAR(3) ENCODE zstd,
	business_zip9 VARCHAR(9) ENCODE zstd,
	consumer_zip9 VARCHAR(9) ENCODE zstd,
	business_addr_available VARCHAR(1) ENCODE zstd,
	consumer_addr_available VARCHAR(1) ENCODE zstd,
	con_areacode VARCHAR(3) ENCODE zstd,
	bus_companynameavailable VARCHAR(1) ENCODE zstd,
	bus_sic_4 VARCHAR(4) ENCODE zstd,
	bus_sic_2 VARCHAR(2) ENCODE bytedict,
	business_state_with_county VARCHAR(5) ENCODE zstd,
	consumer_state_with_county_code VARCHAR(5) ENCODE zstd,
	pres_of_bus_phone VARCHAR(1) ENCODE zstd,
	pres_of_cons_phone VARCHAR(1) ENCODE zstd,
	bus_emailaddressavailable VARCHAR(1) ENCODE zstd,
	con_emailaddressavailable VARCHAR(1) ENCODE zstd,
	bus_domain VARCHAR(80) ENCODE zstd,
	con_domain VARCHAR(80) ENCODE zstd,
	bus_bademail VARCHAR(1) ENCODE zstd,
	infogroup_records VARCHAR(1) ENCODE zstd,
	abi_available VARCHAR(1) ENCODE zstd,
	royalty_records VARCHAR(1) ENCODE zstd,
	state VARCHAR(2) ENCODE bytedict,
	bus_executive_infogroup_data VARCHAR(1) ENCODE zstd,
	bus_emailaddress_infogroup_data VARCHAR(1) ENCODE zstd,
	bus_contactliteraltitlecode_description VARCHAR(256) ENCODE zstd,
	bus_contact_literal_title_description_available VARCHAR(1) ENCODE zstd,
	bus_departmentcode VARCHAR(2) ENCODE zstd,
	bus_levelcode VARCHAR(1) ENCODE zstd,
	titlecode VARCHAR(3) ENCODE bytedict,
	statecountycode VARCHAR(5) ENCODE zstd,
	statecountyname VARCHAR(60) ENCODE zstd,
	citybystate VARCHAR(50) ENCODE zstd,
    statecityzip VARCHAR(50) ENCODE zstd,
	statecityscf VARCHAR(50) ENCODE zstd,
	donotcallflag VARCHAR(1) ENCODE zstd,
	bus_corporate_salesVolumerange_description VARCHAR(100) ENCODE zstd,
	bus_corporate_employeerange_description VARCHAR(100) ENCODE zstd,
	bus_naics_code8_description VARCHAR(100) ENCODE zstd,
    individual_mc VARCHAR(17) ENCODE zstd,
    company_mc VARCHAR(15) ENCODE zstd,
    consumer_individual_matchcode VARCHAR(17) ENCODE zstd,
    consumer_household_matchcode VARCHAR(15) ENCODE zstd,
    bus_lastname_firstltr VARCHAR(4) ENCODE zstd,
    cons_lastname_firstltr VARCHAR(4) ENCODE zstd
);

insert into {maintable_name}
(
bus_abinumber,
  bus_contactname,
  bus_companyname,
  bus_address,
  bus_city,
  bus_state,
  bus_zipcode,
  bus_zipfour,
  bus_phonenumber,
  bus_countycode,
  bus_titlecode,
  bus_titlecodedescription,
  bus_employeesizecode,
  bus_locationoutputvolumecode,
  bus_primarysiccode,
  cons_address,
  cons_city,
  cons_state,
  cons_zipcode,
  cons_zipfour,
  cons_phonenumber,
  cons_countycode,
  cons_locationtype,
  cons_gender,
  cons_age,
  cons_income,
  cons_name,
  cons_maritalstatus,
  cons_creditcardholder,
  cons_ownrent,
  matchflag,
  cons_individualid,
  cons_familyid,
  bus_executivesourcecode,
  bus_executiveid,
  bus_contactflag,
  bus_fulfillmentflag,
  bus_emailaddress,
  bus_vendorid,
  bus_cbsa,
  bus_cbsalevel,
  bus_companyholdingstatus,
  bus_cottagecode,
  bus_mailscore,
  cons_emailaddress,
  cons_vendorid,
  cons_statecode,
  cons_mailconfidence,
  cons_presenceofemail,
  recordtypeindicator,
  execureachquality,
  bus_contactquality,
  matchquality,
  bus_contactliteraltitlecode,
  firstname,
  middleinitial,
  lastname,
  bus_contactid,
  bus_professionaltitle,
  bus_functionalareacode,
  bus_rolecode,
  bus_digitalflag,
  con_digitalflag,
  distancecode,
  bus_bvtscore,
  cons_bvtscore,
  bus_modeledemployeesizeflag,
  bus_location_outputvolumetypcode,
  bus_corporate_employeecount,
  bus_corporate_employeerange,
  bus_corporate_employeesourceindicator,
  bus_corporate_salesvolumeamount,
  bus_corporate_salesvolumerange,
  bus_corporate_salesvolumesourceindicator,
  con_carrierroutecode,
  con_homevalue,
  bus_email_md5_upper,
  bus_email_md5_lower,
  cons_email_md5_upper,
  cons_email_md5_lower,
  ce_expendable_income_rank_code,
  ce_lhi_selected_apparel_general,
  ce_lhi_selected_apparel_accessories,
  ce_lhi_selected_apparel_kids,
  ce_lhi_selected_apparel_mens,
  ce_lhi_selected_apparel_mens_fashions,
  ce_lhi_selected_apparel_womens,
  ce_lhi_selected_apparel_womens_fashions,
  ce_lhi_selected_automotive,
  ce_lhi_selected_auto_racing,
  ce_lhi_selected_auto_trucks,
  ce_lhi_selected_aviation,
  ce_lhi_selected_bargain_seekers,
  ce_lhi_selected_beauty_cosmetic,
  ce_lhi_selected_bible,
  ce_lhi_selected_birds,
  ce_lhi_selected_business_items,
  ce_lhi_selected_business_home_office,
  ce_lhi_selected_catalogs,
  ce_lhi_selected_collectibles,
  ce_lhi_household_collectibles_stamps_coins,
  ce_lhi_selected_college,
  ce_lhi_selected_computers,
  ce_lhi_selected_cooking,
  ce_lhi_selected_cooking_gourmet,
  ce_lhi_selected_crafts_general,
  ce_lhi_selected_crafts_crocheting,
  ce_lhi_selected_crafts_knitting,
  ce_lhi_selected_crafts_needlepoint,
  ce_lhi_selected_crafts_quilting,
  ce_lhi_selected_crafts_sewing,
  ce_lhi_selected_culture_arts,
  ce_lhi_selected_current_events,
  ce_lhi_selected_do_it_yourselfer,
  ce_lhi_selected_charitable_donor,
  ce_lhi_selected_ego_personalized_products,
  ce_lhi_selected_electronics,
  ce_lhi_selected_equestrian,
  ce_lhi_selected_ethnic_product_african_american,
  ce_lhi_selected_ethnic_product_asian,
  ce_lhi_selected_ethnic_product_hispanic,
  ce_lhi_selected_family,
  ce_lhi_selected_finance_credit_card_user,
  ce_lhi_selected_finance_money_making,
  ce_lhi_selected_finance_personal,
  ce_lhi_household_finance_stocks_bonds,
  ce_lhi_selected_gambling,
  ce_lhi_selected_games,
  ce_lhi_selected_gardening,
  ce_lhi_selected_gift_giver,
  ce_lhi_selected_health_general,
  ce_lhi_selected_health_dieting,
  ce_lhi_selected_health_fitness_exercise,
  ce_lhi_household_high_ticket,
  ce_lhi_selected_hightech,
  ce_lhi_selected_history,
  ce_lhi_selected_history_american,
  ce_lhi_selected_hobbies,
  ce_lhi_selected_home_decorating,
  ce_lhi_selected_humor,
  ce_lhi_selected_inspirational,
  ce_lhi_selected_internet,
  ce_lhi_selected_internet_access,
  ce_lhi_selected_internet_buying,
  ce_lhi_selected_motorcycles,
  ce_lhi_selected_music,
  ce_lhi_selected_ocean,
  ce_lhi_selected_outdoors,
  ce_lhi_selected_outdoors_boating_sailing,
  ce_lhi_selected_outdoors_camping_hiking,
  ce_lhi_selected_outdoors_fishing,
  ce_lhi_selected_outdoors_hunting,
  ce_lhi_selected_outdoors_hunting_fishing,
  ce_lhi_selected_pets,
  ce_lhi_selected_pets_cats,
  ce_lhi_selected_pets_dogs,
  ce_lhi_selected_photo_photography,
  ce_lhi_selected_photo_photoprocessing,
  ce_lhi_selected_politically_conservative,
  ce_lhi_selected_politically_liberal,
  ce_lhi_selected_publish_publications,
  ce_lhi_selected_publish_books,
  ce_lhi_selected_publish_fiction,
  ce_lhi_selected_publish_magazine_subscriber,
  ce_lhi_selected_publish_nonfiction,
  ce_lhi_selected_publish_science_fiction,
  ce_lhi_selected_rural_farming,
  ce_lhi_selected_science,
  ce_lhi_selected_seniors,
  ce_lhi_selected_sports_general,
  ce_lhi_selected_sports_baseball,
  ce_lhi_selected_sports_basketball,
  ce_lhi_selected_sports_football,
  ce_lhi_selected_sports_golf,
  ce_lhi_selected_sports_hockey,
  ce_lhi_selected_sports_skiing,
  ce_lhi_selected_sports_soccer,
  ce_lhi_selected_sports_tennis,
  ce_lhi_selected_stationery,
  ce_lhi_selected_sweepstakes,
  ce_lhi_household_technology_vcr,
  ce_lhi_selected_tobacco,
  ce_lhi_selected_travel_general,
  ce_lhi_selected_travel_cruises,
  ce_lhi_household_travel_foreign,
  ce_lhi_selected_travel_rv,
  ce_lhi_selected_travel_us,
  ce_lhi_selected_tv_movies,
  ce_lhi_selected_wildlife,
  ce_mail_responsive_current_flag,
  ce_mail_responsive_ever_flag,
  ce_mail_responsive_previous_flag,
  ce_online_purchase_personal_model,
  ce_online_purchase_business_model,
  ce_online_travel_plan_model,
  ce_blog_writing_model,
  ce_voice_over_internet_model,
  ce_wifi_outside_of_home_model,
  ce_wifi_in_home_model,
  ce_wholesale_club_model,
  ce_auto_club_model,
  ce_diy_auto_maintenance_model,
  ce_online_gaming_model,
  ce_online_investment_trading_model,
  ce_online_bill_payment_model,
  ce_online_tv_download_model,
  ce_mobile_internet_access_model,
  ce_social_media_network_model,
  ce_specialty_organic_food_store_model,
  lems,
  ce_selected_individual_formatted_date_of_birth,
  ce_adventure_seekers_model,
  ce_atv_model,
  ce_annuities_model,
  ce_avid_cell_phone_user_model,
  ce_avid_gamers_model,
  ce_avid_theme_park_visitor_model,
  ce_baby_product_model,
  ce_cat_product_model,
  ce_conservative_model,
  ce_cook_for_fun_model,
  ce_cook_from_scratch_model,
  ce_country_club_member_model,
  ce_credit_card_rewards_model,
  ce_cruise_model,
  ce_diet_product_model,
  ce_dog_product_model,
  ce_donors_pbs_npr_model,
  ce_foreign_travel_vacation_model,
  ce_frequent_business_traveler_model,
  ce_frequent_flyer_model,
  ce_fresh_water_fishing_model,
  ce_garden_maintenance_model,
  ce_green_model,
  ce_heavy_book_buyer_model,
  ce_heavy_coupon_user_model,
  ce_heavy_family_restaurant_visitor_model,
  ce_frozen_dinner_model,
  ce_heavy_investment_trader_model,
  ce_heavy_payperview_movie_model,
  ce_heavy_payperview_sports_model,
  ce_heavy_vitamin_model,
  ce_high_risk_investor_model,
  ce_high_value_security_investor_model,
  ce_high_value_stock_investor_model,
  ce_high_end_electronic_model,
  ce_high_end_sporting_equipment_model,
  ce_higher_education_model,
  ce_home_improvement_model,
  ce_hunting_model,
  ce_impulse_buyer_model,
  ce_international_long_distance_model,
  ce_leaning_conservative_model,
  ce_leaning_liberal_model,
  ce_liberal_model,
  ce_life_insurance_model,
  ce_live_theater_model,
  ce_low_risk_investor_model,
  ce_low_end_sporting_equipment_model,
  ce_luxury_car_buyer_model,
  ce_luxury_hotel_model,
  ce_music_concert_classical_model,
  ce_music_concert_country_model,
  ce_music_concert_rock_model,
  ce_nascar_model,
  ce_onsite_tax_preparation_model,
  ce_opinion_leader_model,
  ce_organic_food_model,
  ce_outdoor_activities_model,
  ce_physical_fitness_club_model,
  ce_power_boating_model,
  ce_religious_donor_model,
  ce_rental_car_model,
  ce_safety_security_conscious_model,
  ce_salt_water_fishing_model,
  ce_shopaholics_model,
  ce_college_basketball_model,
  ce_college_football_model,
  ce_golf_model,
  ce_professional_baseball_model,
  ce_professional_basketball_model,
  ce_professional_football_model,
  ce_professional_wrestling_model,
  ce_soccer_model,
  ce_tennis_model,
  ce_pro_tax_preparation_model,
  ce_timeshare_owner_model,
  ce_wine_lover_model,
  ce_environment_contributor_flag,
  ce_health_contributor_flag,
  ce_political_contributor_flag,
  ce_religious_contributor_flag,
  ce_donor_ever_contributor_flag,
  ce_home_office_model,
  ce_business_banking_model,
  ce_moderate_economy_hotel_model,
  ce_e_reader_model,
  ce_cell_phone_only_model,
  ce_alternative_medicine_model,
  ce_non_religious_donor_model,
  ce_major_home_remodeling_model,
  ce_avid_smart_phone_users_model,
  ce_health_insurance_model,
  ce_satellite_tv_model,
  ce_online_music_download_model,
  ce_adult_education_model,
  ce_pilates_yoga_model,
  ce_fast_food_model,
  ce_hybrid_cars_model,
  ce_heavy_online_buyer_model,
  ce_high_end_apparel_model,
  ce_heavy_catalog_buyer_model,
  ce_gift_buyers_model,
  ce_camping_model,
  ce_sports_fanatics_model,
  ce_financial_planner_model,
  ce_work_health_insurance_model,
  ce_comprehensive_auto_insurance_model,
  ce_small_business_insurance_model,
  ce_heavy_snack_eaters_model,
  ce_heavy_domestic_travelers_model,
  ce_new_vehicle_buyer_model,
  ce_suv_buyer_model,
  ce_minivan_buyer_model,
  ce_auto_loan_model,
  ce_education_loan_model,
  ce_real_estate_investment_model,
  ce_fantasy_sports_model,
  ce_hockey_buyer_model,
  cons_unit_number,
  ce_selected_ind_vendor_ethnicity_code,
  ce_selected_ind_vendor_ethnic_group_code,
  ce_selected_ind_vendor_spoken_language_code,
  ce_selected_ind_vendor_religion_code,
  bus_actual_location_employment_size,
  bus_corporate_employment_size_code,
  bus_actual_corporate_employment_size,
  bus_actual_location_sales_volume,
  bus_corporate_sales_volume_code,
  bus_actual_corporate_sales_volume,
  bus_square_footage,
  bus_business_credit_score_code,
  bus_business_credit_score,
  bus_businessstatuscode,
  bus_phonenumbertype,
  bus_naics_code8,
  bus_web_address_url,
  bus_email_sha256_upper,
  bus_email_sha256_lower,
  con_email_sha256_upper,
  con_email_sha256_lower,
  bus_email_sha1_upper,
  bus_email_sha1_lower,
  con_email_sha1_upper,
  con_email_sha1_lower,
  cons_firstname,
  cons_lastname,
  busimatchcode,
  buscmatchcode,
  consimatchcode,
  conshmatchcode,
  busyearfirstappeared,
  busyearCode,
  id,
  listid,
  permissiontype,
  listtype,
  productcode,
  dropflag,
  zipradius,
  gender,
  zip,
  bus_scf,
  con_scf,
  business_zip9,
  consumer_zip9,
  business_addr_available,
  consumer_addr_available,
  con_areacode,
  bus_companynameavailable,
  bus_sic_4,
  bus_sic_2,
  business_state_with_county,
  consumer_state_with_county_code,
  pres_of_bus_phone,
  pres_of_cons_phone,
  bus_emailaddressavailable,
  con_emailaddressavailable,
  bus_domain,
  con_domain,
  bus_bademail,
  infogroup_records,
  abi_available,
  royalty_records,
  state,
  bus_executive_infogroup_data,
  bus_emailaddress_infogroup_data,
  bus_contactliteraltitlecode_description,
  bus_contact_literal_title_description_available,
  bus_departmentcode,
  bus_levelcode,
  titlecode,
  statecountycode,
  statecountyname,
  citybystate,
  statecityzip,
  statecityscf,
  donotcallflag,
  bus_corporate_salesvolumerange_description,
  bus_corporate_employeerange_description,
  bus_naics_code8_description,
  individual_mc,
  company_mc,
  consumer_individual_matchcode,
  consumer_household_matchcode,
  bus_lastname_firstltr,
  cons_lastname_firstltr
)
SELECT
	a.bus_abinumber AS bus_abinumber,
	a.bus_contactname AS bus_contactname ,
	CASE WHEN a.bus_companyname LIKE '%|%' THEN REPLACE(a.bus_companyname ,'|',' ') ELSE a.bus_companyname END AS bus_companyname,
	a.bus_address AS bus_address  ,
	a.bus_city AS bus_city  ,
	a.bus_state AS bus_state,
	a.bus_zipcode AS bus_zipcode ,
	a.bus_zipfour AS bus_zipfour,
	a.bus_phonenumber AS bus_phonenumber  ,
	a.bus_countycode AS bus_countycode ,
	a.bus_titlecode AS bus_titlecode ,
	a.bus_titlecodedescription AS bus_titlecodedescription ,
	a.bus_employeesizecode AS bus_employeesizecode ,
	a.bus_locationoutputvolumecode AS bus_locationoutputvolumecode ,
	a.bus_primarysiccode AS bus_primarysiccode ,
	a.cons_address AS cons_address ,
	a.cons_city AS cons_city ,
	a.cons_state AS cons_state ,
	a.cons_zipcode AS cons_zipcode ,
	a.cons_zipfour AS cons_zipfour ,
	a.cons_phonenumber AS cons_phonenumber  ,
	a.cons_countycode AS cons_countycode ,
	a.cons_locationtype AS cons_locationtype ,
	a.cons_gender AS cons_gender ,
	a.cons_age AS cons_age ,
	a.cons_income AS cons_income ,
	a.cons_name AS cons_name  ,
	a.cons_maritalstatus AS cons_maritalstatus ,
	a.cons_creditcardholder AS cons_creditcardholder ,
	a.cons_ownrent AS cons_ownrent ,
	a.matchflag AS matchflag ,
	a.cons_individualid AS cons_individualid  ,
	a.cons_familyid AS cons_familyid  ,
	a.bus_executivesourcecode AS bus_executivesourcecode ,
	a.bus_executiveid AS bus_executiveid ,
	a.bus_contactflag AS bus_contactflag ,
	CASE WHEN LTRIM(RTRIM(a.bus_fulfillmentflag)) =''  OR a.bus_fulfillmentflag IS NULL THEN 'Z' ELSE a.bus_fulfillmentflag END AS bus_fulfillmentflag,
	a.bus_emailaddress AS bus_emailaddress ,
	a.bus_vendorid AS bus_vendorid ,
	a.bus_cbsa AS bus_cbsa ,
	a.bus_cbsalevel AS bus_cbsalevel ,
	a.bus_companyholdingstatus AS bus_companyholdingstatus ,
	a.bus_cottagecode AS bus_cottagecode ,
	a.bus_mailscore AS bus_mailscore ,
	a.cons_emailaddress AS cons_emailaddress   ,
	a.cons_vendorid AS cons_vendorid ,
	a.cons_statecode AS cons_statecode ,
	a.cons_mailconfidence AS cons_mailconfidence ,
	a.cons_presenceofemail AS cons_presenceofemail,
	a.recordtypeindicator AS recordtypeindicator,
	a.execureachquality AS execureachquality,
	a.bus_contactquality AS bus_contactquality ,
	a.matchquality AS matchquality ,
	a.bus_contactliteraltitlecode AS bus_contactliteraltitlecode ,
	a.firstname AS firstname  ,
	a.middleinitial AS middleinitial ,
	a.lastname AS lastname  ,
	a.bus_contactid AS bus_contactid , 
	a.bus_professionaltitle AS bus_professionaltitle ,
	a.bus_functionalareacode AS bus_functionalareacode ,
	a.bus_rolecode AS bus_rolecode ,
	a.bus_digitalflag AS bus_digitalflag ,
	a.con_digitalflag AS con_digitalflag ,
	a.distancecode AS distancecode,
	a.bus_bvtscore AS bus_bvtscore  ,
	a.cons_bvtscore AS cons_bvtscore ,
	a.bus_modeledemployeesizeflag AS bus_modeledemployeesizeflag  /*new fields added aug 5, 2019 sf ticket 796756 */,
	a.bus_location_outputvolumetypcode AS bus_location_outputvolumetypcode  ,
	a.bus_corporate_employeecount AS bus_corporate_employeecount  ,
	a.bus_corporate_employeerange AS bus_corporate_employeerange ,
	a.bus_corporate_employeesourceindicator AS bus_corporate_employeesourceindicator  ,
	a.bus_corporate_salesvolumeamount AS bus_corporate_salesvolumeamount ,
	a.bus_corporate_salesvolumerange AS bus_corporate_salesvolumerange  ,
	a.bus_corporate_salesvolumesourceindicator AS bus_corporate_salesvolumesourceindicator ,
	a.con_carrierroutecode AS con_carrierroutecode  ,
	a.con_homevalue AS con_homevalue   /* to here 10 new fields aug 5, 2019 sf */,
	CASE WHEN LTRIM(RTRIM(a.bus_email_md5_upper)) = ''  OR a.bus_email_md5_upper  IS NULL THEN '' ELSE a.bus_email_md5_upper END AS bus_email_md5_upper,
	CASE WHEN LTRIM(RTRIM(a.bus_email_md5_lower)) = ''  OR a.bus_email_md5_lower  IS NULL THEN '' ELSE a.bus_email_md5_lower END AS bus_email_md5_lower,
	CASE WHEN LTRIM(RTRIM(a.cons_email_md5_upper)) = '' OR a.cons_email_md5_upper IS NULL THEN '' ELSE a.cons_email_md5_upper END AS cons_email_md5_upper,
	CASE WHEN LTRIM(RTRIM(a.cons_email_md5_lower)) = '' OR a.cons_email_md5_lower IS NULL THEN '' ELSE a.cons_email_md5_lower END AS cons_email_md5_lower   ,
	a.ce_expendable_income_rank_code  AS ce_expendable_income_rank_code ,
	a.ce_lhi_selected_apparel_general AS ce_lhi_selected_apparel_general ,
	a.ce_lhi_selected_apparel_accessories AS ce_lhi_selected_apparel_accessories ,
	a.ce_lhi_selected_apparel_kids AS ce_lhi_selected_apparel_kids ,
	a.ce_lhi_selected_apparel_mens AS ce_lhi_selected_apparel_mens ,
	a.ce_lhi_selected_apparel_mens_fashions AS ce_lhi_selected_apparel_mens_fashions ,
	a.ce_lhi_selected_apparel_womens AS ce_lhi_selected_apparel_womens ,
	a.ce_lhi_selected_apparel_womens_fashions AS ce_lhi_selected_apparel_womens_fashions ,
	a.ce_lhi_selected_automotive AS ce_lhi_selected_automotive ,
	a.ce_lhi_selected_auto_racing AS ce_lhi_selected_auto_racing ,
	a.ce_lhi_selected_auto_trucks AS ce_lhi_selected_auto_trucks ,
	a.ce_lhi_selected_aviation AS ce_lhi_selected_aviation ,
	a.ce_lhi_selected_bargain_seekers AS ce_lhi_selected_bargain_seekers ,
	a.ce_lhi_selected_beauty_cosmetic AS ce_lhi_selected_beauty_cosmetic ,
	a.ce_lhi_selected_bible AS ce_lhi_selected_bible ,
	a.ce_lhi_selected_birds AS ce_lhi_selected_birds ,
	a.ce_lhi_selected_business_items AS ce_lhi_selected_business_items,
	a.ce_lhi_selected_business_home_office AS ce_lhi_selected_business_home_office ,
	a.ce_lhi_selected_catalogs AS ce_lhi_selected_catalogs ,
	a.ce_lhi_selected_collectibles AS ce_lhi_selected_collectibles ,
	a.ce_lhi_household_collectibles_stamps_coins AS ce_lhi_household_collectibles_stamps_coins ,
	a.ce_lhi_selected_college AS ce_lhi_selected_college ,
	a.ce_lhi_selected_computers AS ce_lhi_selected_computers ,
	a.ce_lhi_selected_cooking AS ce_lhi_selected_cooking ,
	a.ce_lhi_selected_cooking_gourmet AS ce_lhi_selected_cooking_gourmet ,
	a.ce_lhi_selected_crafts_general AS ce_lhi_selected_crafts_general ,
	a.ce_lhi_selected_crafts_crocheting AS ce_lhi_selected_crafts_crocheting ,
	a.ce_lhi_selected_crafts_knitting AS ce_lhi_selected_crafts_knitting ,
	a.ce_lhi_selected_crafts_needlepoint AS ce_lhi_selected_crafts_needlepoint ,
	a.ce_lhi_selected_crafts_quilting AS ce_lhi_selected_crafts_quilting ,
	a.ce_lhi_selected_crafts_sewing AS ce_lhi_selected_crafts_sewing ,
	a.ce_lhi_selected_culture_arts AS ce_lhi_selected_culture_arts ,
	a.ce_lhi_selected_current_events AS ce_lhi_selected_current_events ,
	a.ce_lhi_selected_do_it_yourselfer AS ce_lhi_selected_do_it_yourselfer ,
	a.ce_lhi_selected_charitable_donor AS ce_lhi_selected_charitable_donor ,
	a.ce_lhi_selected_ego_personalized_products AS ce_lhi_selected_ego_personalized_products ,
	a.ce_lhi_selected_electronics AS ce_lhi_selected_electronics ,
	a.ce_lhi_selected_equestrian AS ce_lhi_selected_equestrian ,
	a.ce_lhi_selected_ethnic_product_african_american AS ce_lhi_selected_ethnic_product_african_american ,
	a.ce_lhi_selected_ethnic_product_asian AS ce_lhi_selected_ethnic_product_asian ,
	a.ce_lhi_selected_ethnic_product_hispanic AS ce_lhi_selected_ethnic_product_hispanic ,
	a.ce_lhi_selected_family AS ce_lhi_selected_family,
	a.ce_lhi_selected_finance_credit_card_user AS ce_lhi_selected_finance_credit_card_user ,
	a.ce_lhi_selected_finance_money_making AS ce_lhi_selected_finance_money_making ,
	a.ce_lhi_selected_finance_personal AS ce_lhi_selected_finance_personal ,
	a.ce_lhi_household_finance_stocks_bonds AS ce_lhi_household_finance_stocks_bonds ,
	a.ce_lhi_selected_gambling AS ce_lhi_selected_gambling ,
	a.ce_lhi_selected_games AS ce_lhi_selected_games ,
	a.ce_lhi_selected_gardening AS ce_lhi_selected_gardening ,
	a.ce_lhi_selected_gift_giver AS ce_lhi_selected_gift_giver ,
	a.ce_lhi_selected_health_general AS ce_lhi_selected_health_general ,
	a.ce_lhi_selected_health_dieting AS ce_lhi_selected_health_dieting ,
	a.ce_lhi_selected_health_fitness_exercise AS ce_lhi_selected_health_fitness_exercise ,
	a.ce_lhi_household_high_ticket AS ce_lhi_household_high_ticket ,
	a.ce_lhi_selected_hightech AS ce_lhi_selected_hightech ,
	a.ce_lhi_selected_history AS ce_lhi_selected_history ,
	a.ce_lhi_selected_history_american AS ce_lhi_selected_history_american ,
	a.ce_lhi_selected_hobbies AS ce_lhi_selected_hobbies ,
	a.ce_lhi_selected_home_decorating AS ce_lhi_selected_home_decorating ,
	a.ce_lhi_selected_humor AS ce_lhi_selected_humor ,
	a.ce_lhi_selected_inspirational AS ce_lhi_selected_inspirational ,
	a.ce_lhi_selected_internet AS ce_lhi_selected_internet ,
	a.ce_lhi_selected_internet_access AS ce_lhi_selected_internet_access ,
	a.ce_lhi_selected_internet_buying AS ce_lhi_selected_internet_buying ,
	a.ce_lhi_selected_motorcycles AS ce_lhi_selected_motorcycles ,
	a.ce_lhi_selected_music AS ce_lhi_selected_music ,
	a.ce_lhi_selected_ocean AS ce_lhi_selected_ocean ,
	a.ce_lhi_selected_outdoors AS ce_lhi_selected_outdoors ,
	a.ce_lhi_selected_outdoors_boating_sailing AS ce_lhi_selected_outdoors_boating_sailing ,
	a.ce_lhi_selected_outdoors_camping_hiking AS ce_lhi_selected_outdoors_camping_hiking ,
	a.ce_lhi_selected_outdoors_fishing AS ce_lhi_selected_outdoors_fishing ,
	a.ce_lhi_selected_outdoors_hunting AS ce_lhi_selected_outdoors_hunting ,
	a.ce_lhi_selected_outdoors_hunting_fishing AS ce_lhi_selected_outdoors_hunting_fishing ,
	a.ce_lhi_selected_pets AS ce_lhi_selected_pets ,
	a.ce_lhi_selected_pets_cats AS ce_lhi_selected_pets_cats ,
	a.ce_lhi_selected_pets_dogs AS ce_lhi_selected_pets_dogs ,
	a.ce_lhi_selected_photo_photography AS ce_lhi_selected_photo_photography ,
	a.ce_lhi_selected_photo_photoprocessing AS ce_lhi_selected_photo_photoprocessing ,
	a.ce_lhi_selected_politically_conservative AS ce_lhi_selected_politically_conservative ,
	a.ce_lhi_selected_politically_liberal AS ce_lhi_selected_politically_liberal ,
	a.ce_lhi_selected_publish_publications AS ce_lhi_selected_publish_publications ,
	a.ce_lhi_selected_publish_books AS ce_lhi_selected_publish_books ,
	a.ce_lhi_selected_publish_fiction AS ce_lhi_selected_publish_fiction ,
	a.ce_lhi_selected_publish_magazine_subscriber AS ce_lhi_selected_publish_magazine_subscriber ,
	a.ce_lhi_selected_publish_nonfiction AS ce_lhi_selected_publish_nonfiction ,
	a.ce_lhi_selected_publish_science_fiction AS ce_lhi_selected_publish_science_fiction ,
	a.ce_lhi_selected_rural_farming AS ce_lhi_selected_rural_farming ,
	a.ce_lhi_selected_science AS ce_lhi_selected_science ,
	a.ce_lhi_selected_seniors AS ce_lhi_selected_seniors ,
	a.ce_lhi_selected_sports_general AS ce_lhi_selected_sports_general ,
	a.ce_lhi_selected_sports_baseball AS ce_lhi_selected_sports_baseball ,
	a.ce_lhi_selected_sports_basketball AS ce_lhi_selected_sports_basketball ,
	a.ce_lhi_selected_sports_football AS ce_lhi_selected_sports_football ,
	a.ce_lhi_selected_sports_golf AS ce_lhi_selected_sports_golf ,
	a.ce_lhi_selected_sports_hockey AS ce_lhi_selected_sports_hockey ,
	a.ce_lhi_selected_sports_skiing AS ce_lhi_selected_sports_skiing ,
	a.ce_lhi_selected_sports_soccer AS ce_lhi_selected_sports_soccer ,
	a.ce_lhi_selected_sports_tennis AS ce_lhi_selected_sports_tennis ,
	a.ce_lhi_selected_stationery AS ce_lhi_selected_stationery ,
	a.ce_lhi_selected_sweepstakes AS ce_lhi_selected_sweepstakes ,
	a.ce_lhi_household_technology_vcr AS ce_lhi_household_technology_vcr ,
	a.ce_lhi_selected_tobacco AS ce_lhi_selected_tobacco ,
	a.ce_lhi_selected_travel_general AS ce_lhi_selected_travel_general ,
	a.ce_lhi_selected_travel_cruises AS ce_lhi_selected_travel_cruises ,
	a.ce_lhi_household_travel_foreign AS ce_lhi_household_travel_foreign ,
	a.ce_lhi_selected_travel_rv AS ce_lhi_selected_travel_rv ,
	a.ce_lhi_selected_travel_us AS ce_lhi_selected_travel_us ,
	a.ce_lhi_selected_tv_movies AS ce_lhi_selected_tv_movies ,
	a.ce_lhi_selected_wildlife AS ce_lhi_selected_wildlife ,
	a.ce_mail_responsive_current_flag AS ce_mail_responsive_current_flag ,
	a.ce_mail_responsive_ever_flag AS ce_mail_responsive_ever_flag ,
	a.ce_mail_responsive_previous_flag AS ce_mail_responsive_previous_flag ,
	a.ce_online_purchase_personal_model AS ce_online_purchase_personal_model ,
	a.ce_online_purchase_business_model AS ce_online_purchase_business_model ,
	a.ce_online_travel_plan_model AS ce_online_travel_plan_model ,
	a.ce_blog_writing_model AS ce_blog_writing_model ,
	a.ce_voice_over_internet_model AS ce_voice_over_internet_model ,
	a.ce_wifi_outside_of_home_model AS ce_wifi_outside_of_home_model ,
	a.ce_wifi_in_home_model AS ce_wifi_in_home_model ,
	a.ce_wholesale_club_model AS ce_wholesale_club_model ,
	a.ce_auto_club_model AS ce_auto_club_model ,
	a.ce_diy_auto_maintenance_model AS ce_diy_auto_maintenance_model ,
	a.ce_online_gaming_model AS ce_online_gaming_model ,
	a.ce_online_investment_trading_model AS ce_online_investment_trading_model ,
	a.ce_online_bill_payment_model AS ce_online_bill_payment_model ,
	a.ce_online_tv_download_model AS ce_online_tv_download_model ,
	a.ce_mobile_internet_access_model AS ce_mobile_internet_access_model ,
	a.ce_social_media_network_model AS ce_social_media_network_model ,
	a.ce_specialty_organic_food_store_model AS ce_specialty_organic_food_store_model ,
	a.lems AS lems  ,
	a.ce_selected_individual_formatted_date_of_birth AS ce_selected_individual_formatted_date_of_birth  ,
	a.ce_adventure_seekers_model AS ce_adventure_seekers_model ,
	a.ce_atv_model AS ce_atv_model ,
	a.ce_annuities_model AS ce_annuities_model ,
	a.ce_avid_cell_phone_user_model AS ce_avid_cell_phone_user_model ,
	a.ce_avid_gamers_model AS ce_avid_gamers_model ,
	a.ce_avid_theme_park_visitor_model AS ce_avid_theme_park_visitor_model ,
	a.ce_baby_product_model AS ce_baby_product_model ,
	a.ce_cat_product_model AS ce_cat_product_model ,
	a.ce_conservative_model AS ce_conservative_model ,
	a.ce_cook_for_fun_model AS ce_cook_for_fun_model ,
	a.ce_cook_from_scratch_model AS ce_cook_from_scratch_model ,
	a.ce_country_club_member_model AS ce_country_club_member_model ,
	a.ce_credit_card_rewards_model AS ce_credit_card_rewards_model ,
	a.ce_cruise_model AS ce_cruise_model ,
	a.ce_diet_product_model AS ce_diet_product_model ,
	a.ce_dog_product_model AS ce_dog_product_model ,
	a.ce_donors_pbs_npr_model AS ce_donors_pbs_npr_model ,
	a.ce_foreign_travel_vacation_model AS ce_foreign_travel_vacation_model ,
	a.ce_frequent_business_traveler_model AS ce_frequent_business_traveler_model ,
	a.ce_frequent_flyer_model AS ce_frequent_flyer_model ,
	a.ce_fresh_water_fishing_model AS ce_fresh_water_fishing_model ,
	a.ce_garden_maintenance_model AS ce_garden_maintenance_model ,
	a.ce_green_model AS ce_green_model ,
	a.ce_heavy_book_buyer_model AS ce_heavy_book_buyer_model ,
	a.ce_heavy_coupon_user_model AS ce_heavy_coupon_user_model ,
	a.ce_heavy_family_restaurant_visitor_model AS ce_heavy_family_restaurant_visitor_model ,
	a.ce_frozen_dinner_model AS ce_frozen_dinner_model ,
	a.ce_heavy_investment_trader_model AS ce_heavy_investment_trader_model ,
	a.ce_heavy_payperview_movie_model AS ce_heavy_payperview_movie_model ,
	a.ce_heavy_payperview_sports_model AS ce_heavy_payperview_sports_model ,
	a.ce_heavy_vitamin_model AS ce_heavy_vitamin_model ,
	a.ce_high_risk_investor_model AS ce_high_risk_investor_model ,
	a.ce_high_value_security_investor_model AS ce_high_value_security_investor_model ,
	a.ce_high_value_stock_investor_model AS ce_high_value_stock_investor_model ,
	a.ce_high_end_electronic_model AS ce_high_end_electronic_model ,
	a.ce_high_end_sporting_equipment_model AS ce_high_end_sporting_equipment_model ,
	a.ce_higher_education_model AS ce_higher_education_model ,
	a.ce_home_improvement_model AS ce_home_improvement_model ,
	a.ce_hunting_model AS ce_hunting_model ,
	a.ce_impulse_buyer_model AS ce_impulse_buyer_model ,
	a.ce_international_long_distance_model AS ce_international_long_distance_model ,
	a.ce_leaning_conservative_model AS ce_leaning_conservative_model ,
	a.ce_leaning_liberal_model AS ce_leaning_liberal_model ,
	a.ce_liberal_model AS ce_liberal_model ,
	a.ce_life_insurance_model AS ce_life_insurance_model ,
	a.ce_live_theater_model AS ce_live_theater_model ,
	a.ce_low_risk_investor_model AS ce_low_risk_investor_model ,
	a.ce_low_end_sporting_equipment_model AS ce_low_end_sporting_equipment_model ,
	a.ce_luxury_car_buyer_model AS ce_luxury_car_buyer_model ,
	a.ce_luxury_hotel_model AS ce_luxury_hotel_model ,
	a.ce_music_concert_classical_model AS ce_music_concert_classical_model ,
	a.ce_music_concert_country_model AS ce_music_concert_country_model ,
	a.ce_music_concert_rock_model AS ce_music_concert_rock_model ,
	a.ce_nascar_model AS ce_nascar_model ,
	a.ce_onsite_tax_preparation_model AS ce_onsite_tax_preparation_model ,
	a.ce_opinion_leader_model AS ce_opinion_leader_model ,
	a.ce_organic_food_model AS ce_organic_food_model ,
	a.ce_outdoor_activities_model AS ce_outdoor_activities_model ,
	a.ce_physical_fitness_club_model AS ce_physical_fitness_club_model ,
	a.ce_power_boating_model AS ce_power_boating_model ,
	a.ce_religious_donor_model AS ce_religious_donor_model ,
	a.ce_rental_car_model AS ce_rental_car_model ,
	a.ce_safety_security_conscious_model AS ce_safety_security_conscious_model ,
	a.ce_salt_water_fishing_model AS ce_salt_water_fishing_model ,
	a.ce_shopaholics_model AS ce_shopaholics_model ,
	a.ce_college_basketball_model AS ce_college_basketball_model ,
	a.ce_college_football_model AS ce_college_football_model ,
	a.ce_golf_model AS ce_golf_model ,
	a.ce_professional_baseball_model AS ce_professional_baseball_model ,
	a.ce_professional_basketball_model AS ce_professional_basketball_model ,
	a.ce_professional_football_model AS ce_professional_football_model ,
	a.ce_professional_wrestling_model AS ce_professional_wrestling_model ,
	a.ce_soccer_model AS ce_soccer_model ,
	a.ce_tennis_model AS ce_tennis_model ,
	a.ce_pro_tax_preparation_model AS ce_pro_tax_preparation_model ,
	a.ce_timeshare_owner_model AS ce_timeshare_owner_model ,
	a.ce_wine_lover_model AS ce_wine_lover_model ,
	a.ce_environment_contributor_flag AS ce_environment_contributor_flag ,
	a.ce_health_contributor_flag AS ce_health_contributor_flag ,
	a.ce_political_contributor_flag AS ce_political_contributor_flag ,
	a.ce_religious_contributor_flag AS ce_religious_contributor_flag ,
	a.ce_donor_ever_contributor_flag AS ce_donor_ever_contributor_flag ,
	a.ce_home_office_model AS ce_home_office_model ,
	a.ce_business_banking_model AS ce_business_banking_model ,
	a.ce_moderate_economy_hotel_model AS ce_moderate_economy_hotel_model ,
	a.ce_e_reader_model AS ce_e_reader_model ,		
	a.ce_cell_phone_only_model AS ce_cell_phone_only_model ,
	a.ce_alternative_medicine_model AS ce_alternative_medicine_model ,	
	a.ce_non_religious_donor_model AS ce_non_religious_donor_model ,	
	a.ce_major_home_remodeling_model AS ce_major_home_remodeling_model ,
	a.ce_avid_smart_phone_users_model AS ce_avid_smart_phone_users_model ,
	a.ce_health_insurance_model AS ce_health_insurance_model ,	
	a.ce_satellite_tv_model AS ce_satellite_tv_model ,
	a.ce_online_music_download_model AS ce_online_music_download_model ,
	a.ce_adult_education_model AS ce_adult_education_model ,	
	a.ce_pilates_yoga_model AS ce_pilates_yoga_model ,	
	a.ce_fast_food_model AS ce_fast_food_model ,	
	a.ce_hybrid_cars_model AS ce_hybrid_cars_model ,
	a.ce_heavy_online_buyer_model AS ce_heavy_online_buyer_model ,
	a.ce_high_end_apparel_model AS ce_high_end_apparel_model ,	
	a.ce_heavy_catalog_buyer_model AS ce_heavy_catalog_buyer_model ,
	a.ce_gift_buyers_model AS ce_gift_buyers_model ,
	a.ce_camping_model AS ce_camping_model ,
	a.ce_sports_fanatics_model AS ce_sports_fanatics_model ,
	a.ce_financial_planner_model AS ce_financial_planner_model ,
	a.ce_work_health_insurance_model AS ce_work_health_insurance_model ,
	a.ce_comprehensive_auto_insurance_model AS ce_comprehensive_auto_insurance_model ,
	a.ce_small_business_insurance_model AS ce_small_business_insurance_model ,	
	a.ce_heavy_snack_eaters_model AS ce_heavy_snack_eaters_model ,
	a.ce_heavy_domestic_travelers_model AS ce_heavy_domestic_travelers_model ,
	a.ce_new_vehicle_buyer_model AS ce_new_vehicle_buyer_model ,
	a.ce_suv_buyer_model AS ce_suv_buyer_model ,
	a.ce_minivan_buyer_model AS ce_minivan_buyer_model ,
	a.ce_auto_loan_model AS ce_auto_loan_model ,
	a.ce_education_loan_model AS ce_education_loan_model ,
	a.ce_real_estate_investment_model AS ce_real_estate_investment_model ,
	a.ce_fantasy_sports_model AS ce_fantasy_sports_model ,
	a.ce_hockey_buyer_model as ce_hockey_buyer_model,
	a.cons_unit_number AS cons_unit_number, 
	a.ce_selected_ind_vendor_ethnicity_code AS ce_selected_ind_vendor_ethnicity_code, 		--added sf per ticket 767570 4.8.2019
	a.ce_selected_ind_vendor_ethnic_group_code AS ce_selected_ind_vendor_ethnic_group_code ,	 --added sf per ticket 767570 4.8.2019
	a.ce_selected_ind_vendor_spoken_language_code AS ce_selected_ind_vendor_spoken_language_code, --added sf per ticket 767570 4.8.2019
	a.ce_selected_ind_vendor_religion_code AS ce_selected_ind_vendor_religion_code,		 --added sf per ticket 767570 4.8.2019
	a.bus_actual_location_employment_size AS bus_actual_location_employment_size ,
	a.bus_corporate_employment_size_code AS bus_corporate_employment_size_code ,
	a.bus_actual_corporate_employment_size AS bus_actual_corporate_employment_size ,
	a.bus_actual_location_sales_volume AS bus_actual_location_sales_volume ,
	a.bus_corporate_sales_volume_code AS bus_corporate_sales_volume_code ,
	a.bus_actual_corporate_sales_volume AS bus_actual_corporate_sales_volume, 
	a.bus_square_footage AS bus_square_footage ,
	a.bus_business_credit_score_code AS bus_business_credit_score_code, 
	a.bus_business_credit_score AS bus_business_credit_score ,
	a.bus_businessstatuscode AS bus_businessstatuscode,
	a.bus_phonenumbertype AS bus_phonenumbertype, 
	a.bus_naics_code8 AS bus_naics_code8  , ----added sf per ticket# 805123 9.9.2019
    a.bus_web_address_url AS bus_web_address_url,
	a.bus_email_sha256_upper AS bus_email_sha256_upper, ----added fields by rj per ticket# 835596 2.10.2020
	a.bus_email_sha256_lower AS bus_email_sha256_lower,
	a.con_email_sha256_upper AS con_email_sha256_upper,
	a.con_email_sha256_lower AS con_email_sha256_lower,
	a.bus_email_sha1_upper AS bus_email_sha1_upper,		
	a.bus_email_sha1_lower AS bus_email_sha1_lower,
	a.con_email_sha1_upper AS con_email_sha1_upper,		
	a.con_email_sha1_lower AS con_email_sha1_lower ,
	REPLACE(a.cons_firstname,'|','') AS cons_firstname, --added cb per jira #idms-630 2021.02.01
	REPLACE(a.cons_lastname,'|','') AS cons_lastname , --added cb per jira #idms-630 2021.02.01
	REPLACE(a.busimatchcode,'|','') AS busimatchcode , --added cb per jira #idms-630 2021.02.01
	REPLACE(a.buscmatchcode,'|','') AS buscmatchcode , --added cb per jira #idms-630 2021.02.01
	REPLACE(a.consimatchcode,'|','') AS consimatchcode, --added cb per jira #idms-630 2021.02.01
	REPLACE(a.conshmatchcode,'|','') AS conshmatchcode,  --added cb per jira #idms-630 2021.02.01
    a.busyearfirstappeared AS busyearfirstappeared,
    a.busyearCode AS busyearCode,
	a.id  AS id ,
	14709 AS listid ,
	'R' AS permissiontype,
	a.listtype AS listtype,
	a.productcode AS productcode,
	a.dropflag AS dropflag,
	a.zipradius AS zipradius,
	a.gender AS gender,
	a.bus_zipcode AS zip,
	LEFT(a.bus_zipcode,3) AS bus_scf ,
	LEFT(a.cons_zipcode,3) AS con_scf, 
	a.bus_zipcode + a.bus_zipfour AS business_zip9 ,
	a.cons_zipcode + a.cons_zipfour AS consumer_zip9 ,
	CASE WHEN LTRIM(RTRIM(a.bus_address)) = '' THEN 'N' ELSE 'Y' END AS business_addr_available, 
	CASE WHEN LTRIM(RTRIM(a.cons_address)) = '' THEN 'N' ELSE 'Y' END AS consumer_addr_available, 
	CASE WHEN (a.cons_phonenumber IS NULL OR LTRIM(RTRIM(a.cons_phonenumber)) ='') THEN '' 
         ELSE LEFT(a.cons_phonenumber,3) END AS con_areacode,
	CASE WHEN LTRIM(RTRIM(a.bus_companyname)) = '' THEN 'N' ELSE 'Y' END AS bus_companynameavailable ,
	LEFT(a.bus_primarysiccode,4) AS bus_sic_4, 
	LEFT(a.bus_primarysiccode,2) AS bus_sic_2,
	a.bus_state + a.bus_countycode AS business_state_with_county ,
	a.cons_state + a.cons_countycode AS consumer_state_with_county_code, 
	CASE WHEN LTRIM(RTRIM(a.bus_phonenumber)) = '' THEN 'N' ELSE 'Y' END AS pres_of_bus_phone,
	CASE WHEN LTRIM(RTRIM(a.cons_phonenumber)) = '' THEN 'N' ELSE 'Y' END AS pres_of_cons_phone, 
	CASE WHEN LTRIM(RTRIM(a.bus_emailaddress )) = '' THEN 'N' ELSE 'Y' END AS bus_emailaddressavailable, 
	CASE WHEN LTRIM(RTRIM(a.cons_emailaddress)) = '' THEN 'N' ELSE 'Y' END AS con_emailaddressavailable ,
	RIGHT(a.bus_emailaddress, LEN(a.bus_emailaddress) -CHARINDEX('@', a.bus_emailaddress)) AS bus_domain ,
	RIGHT(a.cons_emailaddress, LEN(a.cons_emailaddress) -CHARINDEX('@', a.cons_emailaddress)) AS con_domain ,
	CASE WHEN a.bus_emailaddress LIKE 'INFO@%' OR a.bus_emailaddress LIKE 'SALES@%' THEN 'Y' ELSE 'N' END AS bus_bademail ,
	CASE WHEN a.bus_executivesourcecode = '36' THEN 'Y' ELSE 'N' END AS infogroup_records, 
	CASE WHEN LTRIM(RTRIM(a.bus_abinumber)) = '' THEN 'N' ELSE 'Y' END AS abi_available, 
	CASE WHEN a.bus_executivesourcecode ='36' AND a.bus_vendorid ='36' THEN 'N' ELSE 'Y' END  AS royalty_records ,
	a.bus_state AS state ,
	CASE WHEN LTRIM(RTRIM(a.bus_executivesourcecode)) = '36' THEN 'Y' ELSE 'N' END AS bus_executive_infogroup_data  ,
	CASE WHEN LTRIM(RTRIM(a.bus_vendorid)) = '36' THEN 'Y' ELSE 'N' END AS bus_emailaddress_infogroup_data, 
	CASE WHEN UPPER(a.bus_contactliteraltitlecode) = UPPER(b.titleid_var) THEN LEFT(UPPER(b.titledescription),256)
		 ELSE a.bus_contactliteraltitlecode_description END AS bus_contactliteraltitlecode_description,
	CASE WHEN LTRIM(RTRIM(LEFT(UPPER(b.titledescription),256))) <> '' AND LEFT(UPPER(b.titledescription),256) IS NOT NULL THEN 'Y' 
		 ELSE 'N' END AS bus_contact_literal_title_description_available,
	LEFT(a.bus_functionalareacode,2) AS bus_departmentcode,
	LEFT(a.bus_rolecode,1) AS bus_levelcode,
	CASE WHEN a.bus_titleCode = '!'  THEN 'Z1'
		 WHEN a.bus_titleCode = '#'  THEN 'Z2'
		 WHEN a.bus_titleCode = '$'  THEN 'Z3'
		 WHEN a.bus_titleCode = '%'  THEN 'Z4'
		 WHEN a.bus_titleCode = '&'  THEN 'Z5'
		 WHEN a.bus_titleCode = '('  THEN 'Z6'
		 WHEN a.bus_titleCode = ')'  THEN 'Z7'
		 WHEN a.bus_titleCode = '+'  THEN 'Z8'
		 WHEN a.bus_titleCode = '-'  THEN 'Z9'
		 WHEN a.bus_titleCode = '.'  THEN 'Z10'
		 WHEN a.bus_titleCode = '/'  THEN 'Z11'
		 WHEN a.bus_titleCode = ':'  THEN 'Z12'
		 WHEN a.bus_titleCode = '='  THEN 'Z13'
		 WHEN a.bus_titleCode = '>'  THEN 'Z14'
		 WHEN a.bus_titleCode = '?'  THEN 'Z15'
		 WHEN a.bus_titleCode = '@'  THEN 'Z16'
		 WHEN a.bus_titleCode = '['  THEN 'Z17'
		 WHEN a.bus_titleCode = '\\' THEN 'Z18' 
		 WHEN a.bus_titleCode = ']'  THEN 'Z19'
		 WHEN a.bus_titleCode = '^'  THEN 'Z20'
		 WHEN a.bus_titleCode = '_'  THEN 'Z21'
		 WHEN a.bus_titleCode = '{'  THEN 'Z22'
		 ELSE a.bus_titleCode END AS titlecode,
	a.bus_state + a.bus_countycode AS statecountycode,
	CASE WHEN a.Bus_state = c.cStatecode AND a.Bus_countycode = c.cCountyCode THEN a.bus_state + c.ccounty 
		 ELSE '' END AS statecountyname,
	LEFT(a.bus_state + a.bus_city, 50) AS citybystate,
    a.bus_state + LTRIM(RTRIM(UPPER(a.bus_city))) + a.bus_zipcode AS statecityzip,
    a.bus_state + LTRIM(RTRIM(UPPER(a.bus_city))) + LEFT(a.bus_zipcode,3) AS statecityscf,
    CASE WHEN A.cons_phonenumber =d.cphone AND a.cons_phonenumber <> '' THEN 'Y'
		 ELSE a.donotcallflag END AS donotcallflag,
	CASE WHEN a.bus_corporate_salesvolumerange = e.cvalue AND 
			  e.cfieldname ='BUS_CORPORATE_SALESVOLUMERANGE' THEN e.cdescription
		 ELSE '' END AS bus_corporate_salesvolumerange_description,
	CASE WHEN a.bus_corporate_employeerange = f.cValue AND 
			  f.cFieldname ='BUS_CORPORATE_EMPLOYEERANGE' THEN f.cdescription
		 ELSE '' END AS bus_corporate_employeerange_description,
	CASE WHEN a.bus_naics_code8 = g.cvalue AND 
			  g.cfieldname ='BUS_NAICS_CODE8' THEN g.cdescription
		 ELSE '' END AS bus_naics_code8_description,
	GetMatchCode(firstname, lastName, bus_address, bus_zipcode, '', 'I') AS individual_mc,
	GetMatchCode(firstname, lastName, bus_address, bus_zipcode, bus_companyname, 'C') AS company_mc,
	GetMatchCode(cons_firstname, cons_lastname, cons_address, cons_zipcode, '' , 'I') AS consumer_individual_matchcode,
	GetMatchCode(cons_firstname, cons_lastname, cons_address, cons_zipcode, cons_lastName, 'C') AS consumer_household_matchcode,
    substring(a.lastname,1,1) as bus_lastname_firstltr,
    substring(a.cons_lastname,1,1) as cons_lastname_firstltr
FROM {table-execureach-new-raw} a
LEFT JOIN {temp-title-description} b 
ON UPPER(a.bus_contactliteraltitlecode) = UPPER(b.titleid_var)
LEFT JOIN 
(
	SELECT LTRIM(RTRIM(UPPER(c.cstatecode))) AS cstatecode , LTRIM(RTRIM(UPPER(c.ccountycode))) AS ccountycode, LTRIM(RTRIM(UPPER(c.ccounty))) AS ccounty 
	FROM sql_tblstate c 
	GROUP BY cstatecode,ccountycode,ccounty
)c
ON a.bus_state = c.cstatecode AND a.bus_countycode = c.ccountycode
LEFT JOIN exclude_donotcallflag d 
ON a.cons_phonenumber =d.cphone 
LEFT JOIN #DDValues e
ON a.bus_corporate_salesvolumerange = e.cvalue AND e.cfieldname ='BUS_CORPORATE_SALESVOLUMERANGE'
LEFT JOIN #DDValues f
ON a.bus_corporate_employeerange = f.cValue AND f.cFieldname ='BUS_CORPORATE_EMPLOYEERANGE'
LEFT JOIN #DDValues g
ON a.bus_naics_code8 = g.cvalue AND g.cfieldname ='BUS_NAICS_CODE8';