DROP TABLE IF EXISTS nosuchtable;

DROP TABLE IF EXISTS business_email_table;
 
CREATE TABLE business_email_table 
(
    abi_number_lrfs character varying(9) ENCODE zstd,
    company_name_lrfs character varying(30) ENCODE zstd,
    addressline1 character varying(40) ENCODE zstd,
    city character varying(28) ENCODE zstd,
    state character varying(2) ENCODE zstd,
    zip character varying(6) ENCODE zstd,
    firstname character varying(15) ENCODE zstd,
    lastname character varying(20) ENCODE zstd,
    title_lrfs character varying(3) ENCODE bytedict,
    gender_lrfs character varying(1) ENCODE zstd,
    email_address_lrfs character varying(60) ENCODE zstd,
    primary_sic_code_lrfs character varying(6) ENCODE zstd,
    area_code_lrfs character varying(3) ENCODE zstd,
    phone_number_lrfs character varying(7) ENCODE zstd,
    literaltitle_id character varying(8) ENCODE zstd,
    title_description_lrfs character varying(256) ENCODE zstd,
    unique_id_lrfs character varying(10) ENCODE zstd,
    vendor_id_lrfs character varying(2) ENCODE zstd,
    executive_source_code_lrfs character varying(2) ENCODE zstd,
    bvt_email_status_lrfs character varying(1) ENCODE zstd,
    suppression_type character varying(1) ENCODE zstd,
    responder_date character varying(6) ENCODE zstd,
    scf_lrfs character varying(3) ENCODE zstd,
    a4_digit_primary_sic_lrfs character varying(4) ENCODE zstd,
    a4_digit_secondary_sic_lrfs character varying(4) ENCODE zstd,
    employee_size_code_lrfs character varying(1) ENCODE zstd,
    sales_volume_code_lrfs character varying(1) ENCODE zstd,
    business_status_code_lrfs character varying(1) ENCODE zstd,
    secondary_sic_code_lrfs character varying(6) ENCODE zstd,
    franchise_code_lrfs character varying(9) ENCODE zstd,
    cbsa_lrfs character varying(5) ENCODE zstd,
    ad_size_lrfs character varying(1) ENCODE zstd,
    business_credit_score_code_lrfs character varying(2) ENCODE zstd,
    business_credit_score_lrfs character varying(3) ENCODE zstd,
    call_status_lrfs character varying(1) ENCODE zstd,
    growing_shrinking_indicator_lrfs character varying(1) ENCODE zstd,
    ultimate_number_lrfs character varying(9) ENCODE zstd,
    fax_number_lrfs character varying(10) ENCODE zstd,
    individual_firm_lrfs character varying(1) ENCODE zstd,
    multi_tenant_code_lrfs character varying(1) ENCODE zstd,
    multi_tenant_building_number_lrfs character varying(7) ENCODE zstd,
    number_of_pc_lrfs character varying(1) ENCODE zstd,
    office_size_lrfs character varying(1) ENCODE zstd,
    own_lease_lrfs character varying(1) ENCODE zstd,
    population_code_lrfs character varying(1) ENCODE zstd,
    public_private_code_lrfs character varying(1) ENCODE zstd,
    government_segment_code_lrfs character varying(1) ENCODE zstd,
    square_footage_lrfs character varying(1) ENCODE zstd,
    teleresearch_date_lrfs character varying(6) ENCODE bytedict,
    transaction_date_lrfs character varying(6) ENCODE zstd,
    transaction_type_lrfs character varying(1) ENCODE zstd,
    website_lrfs character varying(40) ENCODE zstd,
    year_first_appeared_lrfs character varying(4) ENCODE zstd,
    year_sic_added_lrfs character varying(6) ENCODE zstd,
    zip_end_lrfs character varying(1) ENCODE zstd,
    carrier_route_lrfs character varying(4) ENCODE zstd,
    census_lrfs character varying(6) ENCODE zstd,
    state_code_lrfs character varying(2) ENCODE zstd,
    county_code_lrfs character varying(3) ENCODE zstd,
    csa_lrfs character varying(3) ENCODE zstd,
    zip4_lrfs character varying(4) ENCODE zstd,
    secondary_sic2_lrfs character varying(6) ENCODE zstd,
    secondary_sic3_lrfs character varying(6) ENCODE zstd,
    secondary_sic4_lrfs character varying(6) ENCODE zstd,
    md5upper_lrfs character varying(32) ENCODE zstd,
    md5lower_lrfs character varying(32) ENCODE zstd,
    one_per__abi_lrfs character varying(1) ENCODE zstd,
    seq_lrfs character varying(9) ENCODE zstd,
    title_rank_lrfs character varying(2) ENCODE zstd,
    professional_title_code character varying(3) ENCODE zstd,
    department_code character varying(4) ENCODE zstd,
    job_level_code character varying(4) ENCODE zstd,
    mail_score character varying(2) ENCODE zstd,
    city_available character varying(1) ENCODE zstd,
    fullname character varying(36) ENCODE zstd,
    company character varying(65535) ENCODE zstd,
    a2_digit_primary_sic_lrfs character varying(4) ENCODE zstd,
    one_per_abi_lrfs character varying(15) ENCODE zstd,
    domain_name_lrfs character varying(60) ENCODE zstd,
    one_per_abiname_lrfs character varying(44) ENCODE zstd,
    one_per_abi_email_lrfs character varying(69) ENCODE zstd,
    name_available_lrfs character varying(1) ENCODE zstd,
    company_available_lrfs character varying(1) ENCODE zstd,
    abi_available_lrfs character varying(1) ENCODE zstd,
    phone_number_available_lrfs character varying(1) ENCODE zstd,
    royalty_emails_lrfs character varying(1) ENCODE zstd,
    infogroup_emails_lrfs character varying(1) ENCODE zstd,
    a10_digit_phone_lrfs character varying(10) ENCODE zstd,
    state_with_county_code_lrfs character varying(5) ENCODE zstd,
    one_per_contact_name_lrfs character varying(41) ENCODE zstd,
    contacts_per_company_lrfs character varying(65) ENCODE zstd,
    one_per_company_lrfs character varying(30) ENCODE zstd,
    id Bigint,
    listid integer ENCODE az64,
    permissiontype character varying(1) ENCODE zstd,
    gender character varying(1) ENCODE zstd,
    listtype character varying(1) ENCODE zstd,
    productcode character varying(1) ENCODE zstd,
    cinclude1 character varying(1) ENCODE zstd,
    bademails character varying(1) ENCODE zstd,
    website_available character varying(1) ENCODE zstd,
    one_per_company_name_title character varying(33) ENCODE zstd,
    job_level_code_multi character varying(21) ENCODE lzo,
    department_code_multi character varying(21) ENCODE lzo,
    cinclude character varying(1) ENCODE zstd,
    cdomain character varying(11) ENCODE zstd,
    blank_titles character varying(1) ENCODE zstd,
    md5saltedhash character varying(32) ENCODE zstd,
    latitude character varying(11) ENCODE zstd,
    longitude character varying(11) ENCODE zstd,
    geo_match_level character varying(1) ENCODE zstd,
    database_flag character varying(1) ENCODE zstd,
    work_at_home_indicator character varying(1) ENCODE zstd,
    sitenumber character varying(9) ENCODE zstd,
    contactid character varying(12) ENCODE zstd DISTKEY SORTKEY,
    sha256lower character varying(64) ENCODE zstd,
    sha256upper character varying(64) ENCODE zstd,
    phone_number_type character varying(1) ENCODE zstd,
    digitalmatch character varying(1) ENCODE zstd,
    functional_area_code character varying(4) ENCODE bytedict,
    literal_title_department_code character varying(2) ENCODE zstd,
    role_code character varying(4) ENCODE zstd,
    level_code character varying(1) ENCODE zstd,
    contactquality character varying(1) ENCODE zstd,
    bridge_code character varying(1) ENCODE zstd,
    domain_id character varying(1) ENCODE zstd,
    topleveldomain character varying(6) ENCODE zstd,
    email_deliverable character varying(1) ENCODE zstd,
    email_marketable character varying(1) ENCODE zstd,
    email_reputation_risk character varying(1) ENCODE zstd,
    cbsatype character varying(5) ENCODE zstd,
    censusblock character varying(1) ENCODE zstd,
    inferred_corporate_employee_count character varying(6) ENCODE zstd,
    inferred_corporate_employee_range character varying(1) ENCODE zstd,
    inferred_corporate_employee_source_indicator character varying(1) ENCODE zstd,
    inferred_corporate_sales_volume_amount character varying(9) ENCODE zstd,
    inferred_corporate_sales_volume_range character varying(1) ENCODE zstd,
    inferred_corporate_sales_volume_source_indicator character varying(1) ENCODE zstd,
    naicscode character varying(8) ENCODE zstd,
    numberemployees character varying(5) ENCODE zstd,
    outputvolume2 character varying(9) ENCODE zstd,
    subsidairyabinumber character varying(9) ENCODE zstd,
    yearestablished character varying(4) ENCODE zstd,
    creditcardsaccepted_1 character varying(1) ENCODE zstd,
    creditcardsaccepted_2 character varying(1) ENCODE zstd,
    creditcardsaccepted_3 character varying(1) ENCODE zstd,
    creditcardsaccepted_4 character varying(1) ENCODE zstd,
    creditcardsaccepted_5 character varying(1) ENCODE zstd,
    creditcardsaccepted_6 character varying(1) ENCODE zstd,
    creditcardsaccepted_7 character varying(1) ENCODE zstd,
    creditcardsaccepted_8 character varying(1) ENCODE zstd,
    creditcardsaccepted_9 character varying(1) ENCODE zstd,
    creditcardsaccepted_10 character varying(1) ENCODE zstd,
    creditcardsaccepted_11 character varying(1) ENCODE zstd,
    creditcardsaccepted_12 character varying(1) ENCODE zstd,
    creditcardsaccepted_13 character varying(1) ENCODE zstd,
    creditcardsaccepted_14 character varying(1) ENCODE zstd,
    creditcardsaccepted_15 character varying(1) ENCODE zstd,
    addresstype character varying(2) ENCODE zstd,
    femaleexecflag character varying(1) ENCODE zstd,
    truefranchiseflag character varying(1) ENCODE zstd,
    industryspecificfirstbyte character varying(1) ENCODE zstd,
    wealthcode character varying(1) ENCODE zstd,
    bigbusinesssegmentationcode character varying(1) ENCODE zstd,
    smmedbusseg1 character varying(1) ENCODE zstd,
    smmedbusseg2 character varying(1) ENCODE zstd,
    fortuneranking character varying(4) ENCODE zstd,
    hightechbusinessflag character varying(1) ENCODE zstd,
    filingflag character varying(1) ENCODE zstd,
    whitecollar character varying(4) ENCODE zstd,
    whitecollarflag character varying(1) ENCODE zstd,
    primary_mail_confidence character varying(1) ENCODE zstd,
    secondary_mail_confidence character varying(1) ENCODE zstd,
    foreignparentflag character varying(1) ENCODE zstd,
    importexportflag character varying(1) ENCODE zstd,
    highincomeexecflag character varying(1) ENCODE zstd,
    greenadopterscore character varying(1) ENCODE zstd,
    telecommunications_expense character varying(1) ENCODE zstd,
    technology_expense character varying(1) ENCODE zstd,
    office_equipment_expense character varying(1) ENCODE zstd,
    payroll_expense character varying(1) ENCODE zstd,
    rent_leasing_expense character varying(1) ENCODE zstd,
    advertising_expense character varying(1) ENCODE zstd,
    utilities_expense character varying(1) ENCODE zstd,
    accounting_expense character varying(1) ENCODE zstd,
    packagecontainer_expense character varying(1) ENCODE zstd,
    contract_labor_expense character varying(1) ENCODE zstd,
    insurance_expense character varying(1) ENCODE zstd,
    purchased_print_expense character varying(1) ENCODE zstd,
    purchase_mgmtadmin_svc_expense character varying(1) ENCODE zstd,
    legal_expense character varying(1) ENCODE zstd,
    charitable_dontations_expense character varying(1) ENCODE zstd,
    license_fees_taxes character varying(1) ENCODE zstd,
    maintenance_repair character varying(1) ENCODE zstd,
    transportationexpensecode character varying(1) ENCODE zstd,
    franchise_code_1 character varying(3) ENCODE zstd,
    franchise_code_2 character varying(3) ENCODE zstd,
    franchise_code_3 character varying(3) ENCODE zstd,
    franchise_code_4 character varying(3) ENCODE zstd,
    franchise_code_5 character varying(3) ENCODE zstd,
    franchise_code_6 character varying(3) ENCODE zstd,
    fleetsize character varying(1) ENCODE zstd,
    legal_name character varying(120) ENCODE zstd,
    last_modified_date character varying(6) ENCODE bytedict,
    vendor_ethnicity character varying(2) ENCODE zstd,
    vendor_ethnic_group character varying(1) ENCODE zstd,
    vendor_language character varying(2) ENCODE zstd,
    vendor_religion character varying(1) ENCODE zstd,
    naicscode6 character varying(8) ENCODE zstd,
    naicscode4 character varying(8) ENCODE zstd,
    naicscode2 character varying(8) ENCODE zstd,
    individual_mc_wb character varying(17) ENCODE zstd,
    company_mc_wb character varying(15) ENCODE zstd,
    faxavailable_flag character varying(1) ENCODE zstd,
    creditcardsaccepted character varying(15) ENCODE zstd,
    creditcardsaccepted_multi character varying(31) ENCODE zstd,
    zip9 character varying(9) ENCODE zstd,
    literal_title_available character varying(1) ENCODE zstd,
    flatitude double precision ENCODE raw,
    flongitude double precision ENCODE raw,
    cbsalevel character varying(1) ENCODE zstd,
    combined_franchise_code character varying(25) ENCODE zstd,
    individual_mc character varying(65535) ENCODE zstd,
    company_mc character varying(65535) ENCODE lzo
)
DISTSTYLE KEY;

COPY business_email_table 
FROM 's3://axle-gold-sources/business-email/full' 
IAM_ROLE 'arn:aws:iam::479134617933:role/da-idms-redshift-role'
CSV
GZIP
TRIMBLANKS
DELIMITER '|'
;



/*
Redshift has bug with import or exporting in Parquet format.
Refer to the AWS Case 9420321791
COPY business_email_table 
FROM 's3://axle-gold-sources/business-email/full/' 
IAM_ROLE 'arn:aws:iam::479134617933:role/da-idms-redshift-role'
FORMAT AS PARQUET
;
*/

