DROP TABLE IF EXISTS tblBusinessIndividual;

CREATE TABLE tblBusinessIndividual
(
    ID bigint identity unique,
    ABINUMBER varchar(9) ,
    COMPANY varchar(30) ,
    ADDRESS varchar(30) ,
    CITY varchar(16),
    STATE varchar(2) ,
    ZIP_Back varchar(5) ,
    ZIP varchar(6),
    ZIPFOUR varchar(4) ,
    ZIP9 varchar(9), 
    CARRIERROUTECODE varchar(4) ,
    MAILING_ADDRESS varchar(30),
    MAILING_CITY varchar(16),
    MAILING_STATE varchar(2),
    MAILING_ZIPCODE varchar(5),
    MAILING_ZIPFOUR varchar(4),
    MAILING_CARRIEROUTECODE varchar(4),
    LANDMARK_ADDRESS varchar(30),
    LANDMARK_CITY varchar(16),
    LANDMARK_STATE varchar(2),
    LANDMARK_ZIPCODE varchar(5),
    LANDMARK_ZIPFOUR varchar(4),
    LANDMARK_CARRIEROUTECODE varchar(4),
    COUNTYCODE varchar(3) ,
    CENSUSTRACT varchar(6) ,
    CENSUSBLOCK varchar(1) ,
    fLATITUDE float,
    fLONGITUDE float,
    MATCHCODE varchar(1) ,
    TOLLFREEPHONENUMBER varchar(10) ,
    RADIALDISTANCE varchar(4) ,
    PHONENUMBER varchar(10) ,
    FAXPHONE varchar(10) ,
    PRIMARYSIC6 varchar(6) ,
    PRIMARYSIC4 varchar(4) ,
    PRIMARYSIC2 varchar(2) ,
    PRIMARYSICDESIGINATOR varchar(1) ,
    SICCODE1 varchar(6) ,
    SICCODE2 varchar(6) ,
    SICCODE3 varchar(6) ,
    SICCODE4 varchar(6) ,
    FRANCHISECODE1 varchar(1) ,
    FRANCHISECODE2 varchar(1) ,
    FRANCHISECODE3 varchar(1) ,
    FRANCHISECODE4 varchar(1) ,
    FRANCHISECODE5 varchar(1) ,
    FRANCHISECODE6 varchar(1) ,
    TRUEFRANCHISEFLAG varchar(1) ,
    INDUSTRYSPECIFICFIRSTBYTE varchar(1) ,
    NAICSCODE varchar(8) ,
    NUMBEREMPLOYEES INT ,
    EMPLOYEESIZECODE2 varchar(1) ,
    OUTPUTVOLUME2 INT ,
    OUTPUTVOLUMECODE2 varchar(1) ,
    ADSIZECODE varchar(1) ,
    WEALTHCODE varchar(1) ,
    BIGBUSINESSSEGMENTATIONCODE varchar(1) ,
    CREDITNUMERICSCORE varchar(3) ,
    CREDITALPHASCORE varchar(2) ,
    BUSINESSSTATUSCODE varchar(1) ,
    CALLSTATUSCODE varchar(1) ,
    GROWINGBUSINESSFLAG varchar(1) ,
    SMMEDBUSSEG1 varchar(1) ,
    SMMEDBUSSEG2 varchar(1) ,
    FORTUNERANKING varchar(4) ,
    COTTAGECODE varchar(1) ,
    HIGHTECHBUSINESSFLAG varchar(1) ,
    IDENTIFICATIONCODE varchar(1) ,
    OFFICESIZECODE varchar(1) ,
    OWNORLEASE varchar(1) ,
    FILINGFLAG varchar(1) ,
    COMPANYHOLDINGSTATUS varchar(1) ,
    STOCKEXCHANGECODE varchar(1) ,
    STOCKTICKERSYMBOL varchar(6) ,
    TELERESEARCHUPDATEDATE varchar(6) ,
    PARENTABINUMBER varchar(9) ,
    SUBSIDAIRYABINUMBER varchar(9) ,
    SITENUMBER varchar(9) ,
    WEBADDRESS varchar(40) ,
    YELLOWPAGECODE varchar(5),
    BOOKNUMBER varchar(5) ,
    DATEINDATABASE varchar(6) ,
    YEARFIRSTAPPEARED varchar(4) ,
    YEARESTABLISHED varchar(4) ,
    DELIVERYPOINTBARCODE1 varchar(3) ,
    DELIVERYPOINTBARCODE2 varchar(3) ,
    MODELEDEMPLOYEESIZEFLAG varchar(1) ,
    OUTPUTVOLUMETYPECODE varchar(1) ,
    ACRONYMFLAG varchar(1) ,
    CURRENTTRANSACTIONCODE varchar(1) ,
    LOCATION_PARSEDADDRESSTYPE varchar(1),
    LOCATION_PARSEDZIPCODE varchar(5),
    LOCATION_PARSEDSTREETNAME varchar(28),
    LOCATION_PARSEDSUFFIX varchar(5),
    LOCATION_PARSEDPREDIRECTIONAL varchar(2),
    LOCATION_PARSEDPOSTDIRECTION varchar(2),
    LOCATION_PARSEDHOUSENUMBER varchar(15),
    LOCATION_PARSEDSUITENUMBER varchar(20),
    LOCATION_PARSEDCARRIEROUTE varchar(4),
    MULTITENANTCODE varchar(1) ,
    BUILDINGNUMBER varchar(7) ,
    MULTITENANTNUMBER varchar(7) ,
    PROPERTYMANAGEMENTABI varchar(9) ,
    PROPERTYMGMT_BUSINESSNAME varchar (30),
    PROPERTYMGMT_ADDRESS varchar (30),
    PROPERTYMGMT_CITY varchar (16),
    PROPERTYMGMT_STATE varchar (2),
    PROPERTYMGMT_ZIPCODE varchar (5),
    PROPERTYMGMT_ZIPFOUR varchar (4),
    PROPERTYMGMT_FIRSTNAME varchar (11),
    PROPERTYMGMT_LASTNAME varchar (14),
    WHITECOLLAR varchar(3) ,
    WHITECOLLARFLAG varchar(1) ,
    CBSACODE varchar(5) ,
    MAILCONFIDENCE varchar(1) ,
    MAILCONFIDENCE_MAILING varchar(1) ,
    CBSALEVEL varchar(1) ,
    CSACODE varchar(3) ,
    GOVERNMENTFLAG varchar(1) ,
    FOREIGNPARENTFLAG varchar(1) ,
    IMPORTEXPORTFLAG varchar(1) ,
    MONDAYOPEN varchar(4) ,
    MONDAYCLOSE varchar(4) ,
    TUESDAYOPEN varchar(4) ,
    TUESDAYCLOSE varchar(4) ,
    WEDNESDAYOPEN varchar(4) ,
    WEDNESDAYCLOSE varchar(4) ,
    THURSDAYOPEN varchar(4) ,
    THURSDAYCLOSE varchar(4) ,
    FRIDAYOPEN varchar(4) ,
    FRIDAYCLOSE varchar(4) ,
    SATURDAYOPEN varchar(4) ,
    SATURDAYCLOSE varchar(4) ,
    SUNDAYOPEN varchar(4) ,
    SUNDAYCLOSE varchar(4) ,
    PAYATPUMP varchar(1) ,
    CREDITCARDSACCEPTED_1 varchar(1), 
    CREDITCARDSACCEPTED_2 varchar(1),  
    CREDITCARDSACCEPTED_3 varchar(1), 
    CREDITCARDSACCEPTED_4 varchar(1), 
    CREDITCARDSACCEPTED_5 varchar(1), 
    CREDITCARDSACCEPTED_6 varchar(1), 
    CREDITCARDSACCEPTED_7 varchar(1), 
    CREDITCARDSACCEPTED_8 varchar(1), 
    CREDITCARDSACCEPTED_9 varchar(1), 
    CREDITCARDSACCEPTED_10 varchar(1), 
    CREDITCARDSACCEPTED_11 varchar(1), 
    CREDITCARDSACCEPTED_12 varchar(1), 
    CREDITCARDSACCEPTED_13 varchar(1), 
    CREDITCARDSACCEPTED_14 varchar(1), 
    CREDITCARDSACCEPTED_15 varchar(1), 
    SuspectReasonCode varchar(1) ,
    TELECOMMUNICATIONS_EXPENSE varchar(1) ,
    TECHNOLOGY_EXPENSE varchar(1) ,
    OFFICE_EQUIPMENT_EXPENSE varchar(1) ,
    PAYROLL_EXPENSE varchar(1) ,
    RENT_LEASING_EXPENSE varchar(1) ,
    ADVERTISING_EXPENSE varchar(1) ,
    UTILITIES_EXPENSE varchar(1) ,
    ACCOUNTING_EXPENSE varchar(1) ,
    PACKAGECONTAINER_EXPENSE varchar(1) ,
    CONTRACT_LABOR_EXPENSE varchar(1) ,
    INSURANCE_EXPENSE varchar(1) ,
    PURCHASED_PRINT_EXPENSE varchar(1) ,
    PURCHASE_MGMTADMIN_SVC_EXPENSE varchar(1) ,
    LEGAL_EXPENSE varchar(1) ,
    EIN varchar(9),
    FRANCHISE_CODE_1 varchar(3) ,
    FRANCHISE_CODE_2 varchar(3) ,
    FRANCHISE_CODE_3 varchar(3) ,
    FRANCHISE_CODE_4 varchar(3) ,
    FRANCHISE_CODE_5 varchar(3) ,
    FRANCHISE_CODE_6 varchar(3) ,
    SERVICETYPE varchar(1) ,
    ADDRESSTYPE varchar(2) ,
    FULFILLMENTFLAG varchar(1) ,
    AFFILIATEDLOCATIONS varchar(6) ,
    AFFILIATEDRECORDS varchar(6) ,
    LASTNAME varchar(14) ,
    FIRSTNAME varchar(11) ,
    SALUTATION varchar(2) ,
    PROFTITLE varchar(3) ,
    TITLECODE varchar(3) ,
    GENDER varchar(1) ,
    EMAIL_FLAG varchar(1) ,
    VENDORID2 varchar(2) ,
    EXECUTIVESOURCECODE varchar(2) ,
    FEMALEEXECFLAG varchar(1) ,
    HIGHINCOMEEXECFLAG varchar(1) ,
    VENDOR_ETHNICITY varchar(2) ,
    VENDOR_ETHNIC_GROUP varchar(1) ,
    VENDOR_LANGUAGE varchar(2) ,
    VENDOR_RELIGION varchar(1) ,
    SHORT_PRIMARY_WEB_Address varchar(256),
    LONG_LOCAL_WEB_ADDRESS varchar(256),
    COUPON_LINK varchar(256),
    TWITTER_LINK varchar(256),
    LINKED_IN_LINK varchar(256),
    FACEBOOK_LINK varchar(256),
    ALTERNATE_SOCIAL_LINK varchar(256),
    YOU_TUBE_LINK varchar(256), 
    LOGO_LINK varchar(256),
    GOOGLEPLUS_LINK varchar(256),
    PINTEREST_LINK varchar(256),
    MYSPACE_LINK varchar(256),
    FOURSQUARE varchar(256),
    YELP varchar(256),
    INSTAGRAM_LINK varchar(256),
    SQUAREFOOTAGE8 varchar(1) ,
    POPCODE varchar(1) ,
    ECOMMERCEPRESENT varchar(1) , 
    GOOGECHECKOUT varchar(1) ,
    PAYPAL varchar(1) ,
    GREENADOPTERSCORE varchar(1) , 
    LOCATIONLINKAGEID varchar(9) ,
    LOCATIONLINKAGETYPE varchar(1) ,
    FLEETSIZE varchar(1) ,
    CHARITABLE_DONTATIONS_EXPENSE varchar(1) ,
    LICENSE_FEES_TAXES varchar(1) ,
    MAINTENANCE_REPAIR varchar(1) ,
    NBRC_NEW_ADD_DATE varchar(8) ,
    NEW_TO_DATABASE_DATE varchar(8) ,
    PROFESSIONAL_SIC_FLAG varchar(1) ,
    LAST_VERIFICATION_DATE_LIMITED varchar(6) ,
    CONTACTID varchar(12) ,
    TransportationExpenseCode varchar(1) , 
    PHONE_NUMBER_TYPE varchar(1) ,
    CONTACTQUALITY varchar(1),
    DIGITALMATCH VARCHAR(1), 
    Delivery_Date varchar(8),
    FUNCTIONAL_AREA_CODE varchar(4),
    DEPARTMENT_CODE varchar(2),
    ROLE_CODE varchar(4),
    LEVEL_CODE char(1),
    LiteralTitle_ID VARCHAR(8), 
    Inferred_Corporate_Employee_Count INT,
    Inferred_Corporate_Employee_Range char(1),
    Inferred_Corporate_Sales_Volume_Amount INT,
    Inferred_Corporate_Sales_Volume_Range char(1),
    Inferred_Corporate_Employee_Source_Indicator char(1),
    Inferred_Corporate_Sales_Volume_Source_Indicator  char(1),
    CHANGE_DATE VARCHAR(8), 
    TRANSACTION_DATE VARCHAR(8),  
    LEGAL_NAME VARCHAR(120),  
    LAST_DATE VARCHAR(6),  
    TYPECODE CHAR(1),
    CONTACTSOURCEDATE VARCHAR(8),
    DISTRICTCODE VARCHAR(5),  --changed from 3 to 5 for canadian 5.24.2019 SF8
    PREFERREDCORRESPONDENCE CHAR(1),
    CREDITRATINGCODE CHAR(1),
    ACTUALEMPLOYEES INT,
    ACTUALSALES INT,
    ADDRESSORIGINATIONDATE VARCHAR(6),
    BUSINESSNAMEORIGINATIONDATE VARCHAR(6),
    DATABASESEGMENTATIONCODE CHAR(1),
    GRADE CHAR(1),
    HOUSENUMBER VARCHAR(15),
    LOCATIONEMPLOYEESIZE CHAR(1),
    LOCATIONNAME VARCHAR(30),
    LOCATIONSALESVOLUME CHAR(1),
    MAILINGDETAILFLAG CHAR(1),
    MAILSCORE VARCHAR(2),
    NEWTODATABASEDATE VARCHAR(8),
    PHONEORIGINATIONDATE VARCHAR(6),
    STREETNAME VARCHAR(28),
    STREETPOSTDIRECTIONAL VARCHAR(2),
    STREETPREDIRECTIONAL VARCHAR(2),
    STREETSUFFIX VARCHAR(5),
    WEBSITEFLAG CHAR(1),
    UTILITYSOURCE CHAR(1),
    ACLFLAG CHAR(1),
    AMIFLAG CHAR(1),
    FEDERALCONTRACTORFLAG	CHAR(1), 
    CHANGEDTOOUTOFBUSINESSDATE 	VARCHAR(8),
    AMI_currentlinkagenumber VARCHAR(9),
    AMI_typeofpractice VARCHAR(1),
    AMI_primaryspecialty VARCHAR(3),
    AMI_secondaryspecialty VARCHAR(3),
    AMI_boardcertifiedindicator VARCHAR(1),
    AMI_dateofbirth VARCHAR(6),
    AMI_yearofgraduation VARCHAR(4),
    AMI_medicalschoolcode_0 VARCHAR(5),
    AMI_officemanagerlastname VARCHAR(14),
    AMI_officemanagerfirstname VARCHAR(11),
    AMI_professionaldegreecode VARCHAR(1),
    AMI_addresstype VARCHAR(1),
    AMI_upin VARCHAR(6),
    AMI_deanumber VARCHAR(9),
    AMI_sizegrouppractice VARCHAR(3),
    AMI_hospitalnumber VARCHAR(7),
    AMI_numberofnurses VARCHAR(5),
    AMI_nursepractitioners VARCHAR(5),
    AMI_numberofchairs VARCHAR(5),
    AMI_Lic_stateoflicense VARCHAR(2),
    AMI_Lic_expirationdate VARCHAR(8),
    AMI_Lic_licenseboardtype VARCHAR(3),
    AMI_Lic_licensenumber VARCHAR(30),
    AMI_networkcode VARCHAR(3),
    AMI_associationcode VARCHAR(3),
    AMI_npi VARCHAR(10),
    AMI_prescriptionsperwk VARCHAR(1),
    AMI_primarywebaddressflag VARCHAR(1),
    AMI_activewebaddressflag VARCHAR(1),
    ACL_groupcode VARCHAR(2),
    ACL_denominationcode VARCHAR(4),
    ACL_buyercode1 VARCHAR(2),
    ACL_buyercode2 VARCHAR(2),
    ACL_buyercode3 VARCHAR(2),
    ACL_buyercode4 VARCHAR(2),
    ACL_buyercode5 VARCHAR(2),
    ACL_buyercode6 VARCHAR(2),
    ACL_buyercode7 VARCHAR(2),
    ACL_buyercode8 VARCHAR(2),
    ACL_buyercode9 VARCHAR(2),
    ACL_buyercode10 VARCHAR(2),
    ACL_buyercode11 VARCHAR(2),
    ACL_buyercode12 VARCHAR(2),
    ACL_buyercode13 VARCHAR(2),
    ACL_buyercode14 VARCHAR(2),
    ACL_buyercode15 VARCHAR(2),
    ACL_buyercode16 VARCHAR(2),
    ACL_buyercode17 VARCHAR(2),
    ACL_buyercode18 VARCHAR(2),
    ACL_buyercode19 VARCHAR(2),
    ACL_buyercode20 VARCHAR(2),
    ACL_buyercode21 VARCHAR(2),
    ACL_buyercode22 VARCHAR(2),
    ACL_buyercode23 VARCHAR(2),
    ACL_buyercode24 VARCHAR(2),
    ACL_buyercode25 VARCHAR(2),
    ACL_buyercode26 VARCHAR(2),
    ACL_buyercode27 VARCHAR(2),
    ACL_buyercode28 VARCHAR(2),
    ACL_buyercode29 VARCHAR(2),
    ACL_buyercode30 VARCHAR(2),
    ACL_buyercode31 VARCHAR(2),
    ACL_buyercode32 VARCHAR(2),
    ACL_churchsizecode VARCHAR(1),
    ACL_churchsize VARCHAR(5),
    ACL_attendancecode VARCHAR(1),
    ACL_attendance VARCHAR(5),
    ACL_schoolsizecode VARCHAR(1),
    ACL_raceofcongregation1 VARCHAR(1),
    ACL_raceofcongregation2 VARCHAR(1),
    ACL_raceofcongregation3 VARCHAR(1),
    ACL_raceofcongregation4 VARCHAR(1),
    ACL_raceofcongregation5 VARCHAR(1),
    ACL_raceofcongregation6 VARCHAR(1),
    ACL_membershipsourceflag VARCHAR(1),
    ACL_multiplecongregationscode VARCHAR(1),
    ACL_newconstructionlastverificationdate VARCHAR(8),
    Countrycode VARCHAR(2),
    DMAcode VARCHAR(3),
    Changedtoverifieddate VARCHAR(8),
    Changedtosuspectdate VARCHAR(8),
    Infoscore VARCHAR(3),
    Industrygrowthscore VARCHAR(3),
    Completenessscore VARCHAR(3),
    Stabilityscore VARCHAR(3),
    Reachabilityscore VARCHAR(3),
    Infograde VARCHAR(2),
    IndustrygrowthGrade VARCHAR(2),
    CompletenessGrade VARCHAR(2),
    StabilityGrade VARCHAR(2),
    ReachabilityGrade VARCHAR(2),
    AMI_Boardcertificationcount VARCHAR(5),
    AMI_MedicareAccepted VARCHAR(1),
    AMI_AcceptingNewPatients VARCHAR(1),
    NameStandardizationFlag VARCHAR(1),
    TIMEZONE VARCHAR(3),
    Homeaddress VARCHAR(30),
    Homecity VARCHAR(30),
    Homestate VARCHAR(2),
    Homezipcode VARCHAR(5),
    Homezip4 VARCHAR(4),
    Homeareacode VARCHAR(3),
    Homephonenumber VARCHAR(7),
    Donotcallflag VARCHAR(1),
    Homecountycode VARCHAR(3),
    Homelocationtype VARCHAR(1),
    Execgender VARCHAR(1),
    Execage VARCHAR(2),
    Execincome VARCHAR(1),
    Homeowner VARCHAR(1),
    Maritalstatus VARCHAR(1),
    Job_Function_ID	VARCHAR(3),
    Management_Level VARCHAR(25),
    Job_Title VARCHAR(80),
    EMPLOYEESIZECODE1 varchar(1),
    OUTPUTVOLUME1 varchar(9),
    OUTPUTVOLUMECODE1 varchar(1),
    BANKASSETCODE varchar(1),
    CORPORATEEMPLOYEES VARCHAR(6),
    CORPORATEOUTPUTVOLUME VARCHAR(9),
    CORPORATESALESVOLUME CHAR(1),
    fLATITUDE_old float,
    fLONGITUDE_OLD float,
    FullName VARCHAR(40),
    One_per_ABI VARCHAR(14),
    One_per_ABIName VARCHAR(40),
    Name_Available Varchar(1),
    Company_Available Varchar(1),
    ABI_Available Varchar(1),
    Phone_Number_Available Varchar(1),
    City_Available Varchar(1),
    Website_Available Varchar(1),
    EIN_Available Varchar(1),
    One_per_Contact_Name  VARCHAR(40),
    One_Per_Company_Name_Title  VARCHAR(35),
    Contacts_Per_Company VARCHAR(60),
    ZipRadius char(1),
    GeoRadius char(1),
    One_Per_Address_Company VARCHAR(60), 
    PRESENCE_OF_LATITUDE char(1),
    PRESENCE_OF_LONGITUDE char(1),
    Creditcardsaccepted VARCHAR(15),
    Creditcardsaccepted_Multi VARCHAR(50),
    PARENTABINUMBER_Back  varchar(9),
    Haspostal Char(1),
    Listid int,
    PermissionType Char(1),
    Vendor_ID varchar(2),
    Geo_Match_Level char(1),
    Database_Flag  char(1),
    Work_At_Home_Indicator char(1),
    TITLECODE_Back varchar(1),
    ACL_BuyerCode Varchar(120),
    EmailAddress varchar(60),
    cDomain  varchar(80),
    cDomainType varchar(2),
    BadEmails char(1),
    Royalty_Emails  char(1),
    Infogroup_Emails  char(1),
    cInclude char(1),
    MD5Upper Varchar(32),
    MD5Lower varchar(32),
    MD5SaltedHash  varchar(32),
    SHA256Lower varchar(64),
    SHA256Upper varchar(64),
    BVT_EMAIL_STATUS_Email char(1),
    Bridge_Code char(1),
    Domain_ID char(1),
    TopLevelDomain char(6),
    Email_Marketable varchar(1),
    Email_Deliverable varchar(1),
    Email_Reputation_Risk varchar(1),
    DEPARTMENT_CODE_Email varchar(4),
    DEPARTMENT_CODE_MULTI_Email varchar(9),
    FRANCHISE_CODE_Email varchar(6),
    INDIVIDUAL_FIRM_Email char(1),
    JOB_LEVEL_CODE_Email varchar(4),
    JOB_LEVEL_CODE_MULTI_Email varchar(9),
    MAIL_SCORE_Email varchar(2),
    ONEPERFLAG_Email char(1),
    ONE_PER_ABI_EMAIL_Email varchar(69),
    ONE_PER_COMPANY_Email varchar(30),
    ONE_PER__ABI_Email char(1),
    PRODUCTCODE_Email char(1),
    RESPONDER_DATE_Email varchar(6),
    SEQ_Email varchar(9),
    SUPPRESSION_TYPE_Email char(1),
    TITLE_DESCRIPTION_Email varchar(150),
    TITLE_RANK_Email varchar(2),
    TRANSACTION_DATE_Email varchar(6),
    TRANSACTION_TYPE_Email char(1),
    ULTIMATE_NUMBER_Email varchar(9),
    YEAR_SIC_ADDED_Email varchar(6),
    AdditionalEmailFlag_Email varchar(1),
    SCF varchar(3),
    ZIP_END Char(1),
    APPLICATION_A CHAR(1),
    APPLICATION_B CHAR(1),
    APPLICATION_C CHAR(1),
    APPLICATION_E CHAR(1),
    APPLICATION_F CHAR(1),
    APPLICATION_G CHAR(1),
    APPLICATION_H CHAR(1),
    APPLICATION_I CHAR(1),
    APPLICATION_J CHAR(1),
    APPLICATION_K CHAR(1),
    APPLICATION_L CHAR(1),
    APPLICATION_M CHAR(1),
    APPLICATION_N CHAR(1),
    APPLICATION_P CHAR(1),
    SEGMENTCODE_1 CHAR(1),
    SEGMENTCODE_2 CHAR(1),
    SEGMENTCODE_3 CHAR(1),
    SEGMENTCODE_4 CHAR(1),
    SEGMENTCODE_5 CHAR(1),
    SEGMENTCODE_6 CHAR(1),
    SEGMENTCODE_7 CHAR(1),
    SEGMENTCODE_8 CHAR(1),
    SEGMENTCODE_9 CHAR(1),
    SEGMENTCODE_A CHAR(1),
    SEGMENTCODE_F CHAR(1),
    SEGMENTCODE_H CHAR(1),
    SEGMENTCODE_I CHAR(1),
    NBRC_NEW_ADD_DATE_YYYYMM  VARCHAR(6),
    NEW_TO_DATABASE_DATE_YYYYMM VARCHAR(6),
    TRANSACTION_DATE_YYYYMM VARCHAR(6),
    AreaCode VARCHAR(3),
    FaxAvailable CHAR(1),
    StateCOUNTYCODE CHAR(5),
    ZipCarrierRoute VARCHAR(9),
    PrimarySIC6Franchise VARCHAR(9),
    Kiosks_Flag Varchar(1),
    HardKey VARCHAR(55),
    POBOX_FLAG CHAR(1),
    ParkSuppression  char(1),
    AddressLine1  varchar(30),
    AddressLine2  varchar(30),
    AreaCode_Prefix  varchar(10),
    One_Per_Address   varchar(50),
    InfogroupContact Char(1) Default 'N',
    InfogroupContactAndEmail Char(1) Default 'N',
    MailScoreCombined varCHAR(1) Default '',
    Census_State_Code_2010   VARCHAR(2) default '',
    STATECODE   VARCHAR(2)default '',
    MAILING_STATECODE   VARCHAR(2) default '',
    COUNTYCODEBYSTATECODE VARCHAR(5) default '',
    CITYBYSTATE VARCHAR(50) default '',
    STATE_COUNTY_CENSUSTRACT_BLOCK VARCHAR(12),
    NAICS2 VARCHAR(2),
    NAICS4 VARCHAR(4),
    NAICS6 VARCHAR(6),
    USTerritoryFlag CHAR(1) default 'N',
    StateCountyName VARCHAR(60),
    StateCityZip VARCHAR(50),
    StateCitySCF VARCHAR(50),
    UNIQUEPROFESSIONALGUI VARCHAR(10),
    TitleCodePriority int,
    AMI_HospitalName VARCHAR(27),
    Locationzip_zip4_deliverypointbarcode varchar(15),
    STATE_DESCRIPTION  Varchar(100),
    ETHNICITY_DESCRIPTION  Varchar(100),
    STOCKEXCHANGE_DESCRIPTION  Varchar(100),
    PHONECALLSTATUS_DESCRIPTION  Varchar(100),
    BUSINESSCREDITALPHASCORE_DESCRIPTION  Varchar(100),
    FLEETSIZE_DESCRIPTION  Varchar(100),
    FRANCHISE_CODE_1_DESCRIPTION  Varchar(100),
    FRANCHISE_CODE_2_DESCRIPTION  Varchar(100),
    FRANCHISE_CODE_3_DESCRIPTION  Varchar(100),
    FRANCHISE_CODE_4_DESCRIPTION  Varchar(100),
    FRANCHISE_CODE_5_DESCRIPTION  Varchar(100),
    FRANCHISE_CODE_6_DESCRIPTION  Varchar(100),
    ACCOUNTING_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    ADVERTISING_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    CHARITABLE_DONTATIONS_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    CONTRACT_LABOR_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    INSURANCE_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    LEGAL_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    LICENSE_FEES_TAXES_DESCRIPTION  VARCHAR(100) default '',
    MAINTENANCE_REPAIR_DESCRIPTION  VARCHAR(100) default '',
    OFFICE_EQUIPMENT_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    PACKAGECONTAINER_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    PAYROLL_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    PURCHASED_PRINT_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    PURCHASE_MGMTADMIN_SVC_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    RENT_LEASING_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    TECHNOLOGY_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    TELECOMMUNICATIONS_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    TransportationExpenseCode_DESCRIPTION  VARCHAR(100) default '',
    UTILITIES_EXPENSE_DESCRIPTION  VARCHAR(100) default '',
    SALUTATION_DESCRIPTION  VARCHAR(100) default '',
    ACL_GROUPCODE_DESCRIPTION  VARCHAR(100) default '',
    ACL_DENOMINATIONCODE_DESCRIPTION  VARCHAR(100) default '',
    DMACode_DESCRIPTION  VARCHAR(100) default '',
    PROFTITLE_DESCRIPTION  VARCHAR(100) default '',
    ADDRESSTYPE_DESCRIPTION  VARCHAR(100) default '',
    OWNORLEASE_DESCRIPTION  VARCHAR(100) default '',
    AMI_BOARDCERTIFIEDINDICATOR_DESCRIPTION  VARCHAR(100) default '',
    AMI_PRIMARYSPECIALTY_DESCRIPTION  VARCHAR(100) default '',
    AMI_SECONDARYSPECIALTY_DESCRIPTION  VARCHAR(100) default '',
    AMI_PROFESSIONALDEGREECODE_DESCRIPTION  VARCHAR(100) default '',
    AMI_LIC_STATEOFLICENSE_DESCRIPTION  VARCHAR(100) default '',
    AMI_PRESCRIPTIONSPERWK_DESCRIPTION  VARCHAR(100) default '',
    CREDITRATINGCODE_DESCRIPTION  VARCHAR(100) default '',
    PHONE_NUMBER_TYPE_DESCRIPTION  VARCHAR(100) default '',
    PRIMARYSIC2_DESC VARCHAR(100) default '',
    PRIMARYSIC4_DESC VARCHAR(100)default '',
    INDUSTRY_DESC VARCHAR(100)default '',
    PreferredCity VARCHAR(50),
    DISTRICT_DESCRIPTION Varchar(100),
    CREDIT_RATING_DESCRIPTION Varchar(100),
    TITLE_DESCRIPTION Varchar(100),
    GENDER_DESCRIPTION Varchar(100),
    CMA_DESCRIPTION Varchar(100),
    RegionCode_Multi varchar(60) default '',
    RegionCode_01 varchar(2) default '',
    RegionCode_02 varchar(2) default '',
    RegionCode_03 varchar(2) default '',
    RegionCode_04 varchar(2) default '',
    RegionCode_05 varchar(2) default '',
    RegionCode_06 varchar(2) default '',
    RegionCode_07 varchar(2) default '',
    RegionCode_08 varchar(2) default '',
    RegionCode_09 varchar(2) default '',
    RegionCode_10 varchar(2) default '',
    RegionCode_11 varchar(2) default '',
    RegionCode_12 varchar(2) default '',
    RegionCode_13 varchar(2) default '',
    RegionCode_14 varchar(2) default '',
    RegionCode_15 varchar(2) default '',
    PostalCode_Mailing  Varchar(6),
    PostalCode_Landmark  Varchar(6),
    AMEXSFLAG  VARCHAR(1) Default 'N',
    Individual_MC VARCHAR(17),
    Company_MC VARCHAR(15),
    Address_MC VARCHAR(17)
);