DROP TABLE IF EXISTS DDValues1 ;
CREATE TABLE DDValues1 AS
SELECT
  LTRIM(RTRIM(UPPER(cFieldname))) as cFieldname, 
  LTRIM(RTRIM(UPPER(cValue))) as cValue, 
  LTRIM(RTRIM(cDescription)) as cDescription    
from sql_tblDDDescriptions 
WHERE  databaseid =0 
AND LTRIM(RTRIM(UPPER(cFieldname))) in 
('STATE_2CHAR', 'STOCKEXCHANGE','STATE_2DIGIT', 'ETHINICITY','PHONECALLSTATUS','BUSINESSCREDITSCORE', 'FLEETSIZE'  ) and 
((cValue) <> '' or (cDescription) <>  '');


DROP TABLE IF EXISTS ddvalues_1_dddescriptions_clean;
CREATE TABLE  ddvalues_1_dddescriptions_clean
SORTKEY(id)
DISTKEY(id)
As
select 
a.id as id,
  dd1.cDescription AS STATE_DESCRIPTION,
  dd2.cDescription AS ETHNICITY_DESCRIPTION, 
  dd3.cDescription  AS STOCKEXCHANGE_DESCRIPTION,
  dd4.cDescription AS PHONECALLSTATUS_DESCRIPTION,
  dd5.cDescription AS BUSINESSCREDITALPHASCORE_DESCRIPTION,
  dd6.cDescription AS FLEETSIZE_DESCRIPTION
FROM tblBusinessIndividual a
left join DDValues1 DD1  ON A.STATE = DD1.cValue AND DD1.cFieldname ='STATE_2CHAR'
LEFT join DDValues1 DD2  ON A.VENDOR_ETHNICITY = DD2.cValue AND DD2.cFieldname ='ETHINICITY'
LEFT join DDValues1 DD3  ON A.STOCKEXCHANGECODE = DD3.cValue AND DD3.cFieldname ='STOCKEXCHANGE'
LEFT join DDValues1 DD4  ON A.CALLSTATUSCODE= DD4.cValue AND DD4.cFieldname ='PHONECALLSTATUS'
LEFT join DDValues1 DD5  ON A.CREDITALPHASCORE= DD5.cValue AND DD5.cFieldname ='BUSINESSCREDITSCORE'
LEFT join DDValues1 DD6  ON A.FLEETSIZE= DD6.cValue AND DD6.cFieldname ='FLEETSIZE';

DROP TABLE IF EXISTS ddvalues_1_dddescriptions;
CREATE TABLE ddvalues_1_dddescriptions 
DISTKEY (ID)
SORTKEY(ID)
AS 
SELECT id AS id,
min(STATE_DESCRIPTION) as STATE_DESCRIPTION,
min(ETHNICITY_DESCRIPTION) as ETHNICITY_DESCRIPTION,
min(STOCKEXCHANGE_DESCRIPTION) as STOCKEXCHANGE_DESCRIPTION,
min(PHONECALLSTATUS_DESCRIPTION) as PHONECALLSTATUS_DESCRIPTION,
min(BUSINESSCREDITALPHASCORE_DESCRIPTION) as BUSINESSCREDITALPHASCORE_DESCRIPTION,
min(FLEETSIZE_DESCRIPTION) as FLEETSIZE_DESCRIPTION
FROM ddvalues_1_dddescriptions_clean DDValues
GROUP BY ID;