Drop Table if exists tblChild33_{build_id}_{build};
CREATE TABLE tblChild33_{build_id}_{build}	
(
        ABINUMBER VARCHAR(9) ENCODE ZSTD SORTKEY DISTKEY,
        ADSIZECODE CHAR(1) ENCODE ZSTD,
        ATTORNEYCUISINECODE CHAR(1) ENCODE ZSTD,
        BANKASSETCODE CHAR(1) ENCODE LZO,
        BOOKNUMBER VARCHAR(5) ENCODE ZSTD,
        DATEINDATABASE VARCHAR(6) ENCODE ZSTD,
        FRANCHISECODE1 CHAR(1) ENCODE ZSTD,
        FRANCHISECODE1_EXTENDED VARCHAR(3) ENCODE ZSTD,
        FRANCHISECODE2 CHAR(1) ENCODE ZSTD,
        FRANCHISECODE2_EXTENDED VARCHAR(3) ENCODE ZSTD,
        FRANCHISECODE3 CHAR(1) ENCODE ZSTD,
        FRANCHISECODE3_EXTENDED VARCHAR(3) ENCODE ZSTD,
        FRANCHISECODE4 CHAR(1) ENCODE ZSTD,
        FRANCHISECODE4_EXTENDED VARCHAR(3) ENCODE ZSTD,
        FRANCHISECODE5 CHAR(1) ENCODE ZSTD,
        FRANCHISECODE5_EXTENDED VARCHAR(3) ENCODE ZSTD,
        FRANCHISECODE6 CHAR(1) ENCODE ZSTD,
        FRANCHISECODE6_EXTENDED VARCHAR(3) ENCODE ZSTD,
        INDUSTRYSPECIFICFIRSTBYTE CHAR(1) ENCODE ZSTD,
        PRIMARYNAICSCODE_PSIC VARCHAR(8) ENCODE ZSTD,
        NAICSCODE VARCHAR(8) ENCODE ZSTD,
        PRIMARYSICDESIGNATOR CHAR(1) ENCODE ZSTD,
        PROFESSIONALSICFLAG CHAR(1) ENCODE ZSTD,
        SICCODE_PSIC VARCHAR(6) ENCODE ZSTD,
        SICCODE VARCHAR(6) ENCODE ZSTD,
        SICYEARFIRSTAPPEARED VARCHAR(4) ENCODE BYTEDICT,
        TRUEFRANCHISEFLAG CHAR(1) ENCODE ZSTD,
        UPDATEDATE VARCHAR(6) ENCODE ZSTD,
        YELLOWPAGECODE VARCHAR(5) ENCODE ZSTD,
        BOOKPUBLICATIONDATE VARCHAR(6) ENCODE BYTEDICT,
        SICCOUNT VARCHAR(6) ENCODE ZSTD,
        FRANCHISETYPE1 Varchar(1) ENCODE ZSTD,
        FRANCHISETYPE2 Varchar(1) ENCODE ZSTD,
        FRANCHISETYPE3 Varchar(1) ENCODE ZSTD,
        FRANCHISETYPE4 Varchar(1) ENCODE ZSTD,
        FRANCHISETYPE5 Varchar(1) ENCODE ZSTD,
        FRANCHISETYPE6 Varchar(1) ENCODE ZSTD,
	    NAICS2 VARCHAR(2) ENCODE LZO,
	    NAICS4 VARCHAR(4) ENCODE LZO,
	    NAICS6 VARCHAR(6) ENCODE LZO, 
	    PNAICS2 VARCHAR(2) ENCODE LZO,
	    PNAICS4 VARCHAR(4) ENCODE LZO,
	    PNAICS6 VARCHAR(6) ENCODE LZO,
        MAJORINDUSTRYGROUP  VARCHAR(2) ENCODE LZO,
        MINORINDUSTRYGROUP VARCHAR(4) ENCODE LZO,
        FRANCHISEBYSIC VARCHAR(9) ENCODE LZO,
        INDUSTRYSPECIFICBYSIC VARCHAR(7) ENCODE LZO,
        PRIMARYSICFLAG CHAR(1) ENCODE LZO,
        DATEINDATABASE_YYYY CHAR(4) ENCODE LZO,
        filler1 varchar(1) ENCODE ZSTD,
        filler2 varchar(2) ENCODE ZSTD
);

copy tblChild33_{build_id}_{build}
(
    ABINUMBER,
    ADSIZECODE,
    ATTORNEYCUISINECODE,
    FILLER1,
    BOOKNUMBER,
    DATEINDATABASE,
    FRANCHISECODE1,
    FRANCHISECODE1_EXTENDED,
    FRANCHISECODE2,
    FRANCHISECODE2_EXTENDED,
    FRANCHISECODE3,
    FRANCHISECODE3_EXTENDED,
    FRANCHISECODE4,
    FRANCHISECODE4_EXTENDED,
    FRANCHISECODE5,
    FRANCHISECODE5_EXTENDED,
    FRANCHISECODE6,
    FRANCHISECODE6_EXTENDED,
    INDUSTRYSPECIFICFIRSTBYTE,
    PRIMARYNAICSCODE_PSIC,
    NAICSCODE,
    PRIMARYSICDESIGNATOR,
    PROFESSIONALSICFLAG,
    SICCODE_PSIC,
    SICCODE,
    SICYEARFIRSTAPPEARED,
    TRUEFRANCHISEFLAG,
    UPDATEDATE,
    YELLOWPAGECODE,
    BOOKPUBLICATIONDATE,
    SICCOUNT,
    FRANCHISETYPE1,
    FRANCHISETYPE2,
    FRANCHISETYPE3,
    FRANCHISETYPE4,
    FRANCHISETYPE5,
    FRANCHISETYPE6,
    Filler2
)
FROM 's3://idms-7933-internalfiles/business-core/IDMSSIC.gz'
IAM_ROLE '{iam}'
REMOVEQUOTES
GZIP
IGNOREBLANKLINES
ACCEPTINVCHARS
MAXERROR 100
FIXEDWIDTH
'ABINUMBER:9,
ADSIZECODE:1,
ATTORNEYCUISINECODE:1,
FILLER1: 1,
BOOKNUMBER:5,
DATEINDATABASE:6,
FRANCHISECODE1:1,
FRANCHISECODE1_EXTENDED:3,
FRANCHISECODE2:1,
FRANCHISECODE2_EXTENDED:3,
FRANCHISECODE3:1,
FRANCHISECODE3_EXTENDED:3,
FRANCHISECODE4:1,
FRANCHISECODE4_EXTENDED:3,
FRANCHISECODE5:1,
FRANCHISECODE5_EXTENDED:3,
FRANCHISECODE6:1,
FRANCHISECODE6_EXTENDED:3,
INDUSTRYSPECIFICFIRSTBYTE:1,
PRIMARYNAICSCODE_PSIC:8,
NAICSCODE:8,
PRIMARYSICDESIGNATOR:1,
PROFESSIONALSICFLAG:1,
SICCODE_PSIC:6,
SICCODE:6,
SICYEARFIRSTAPPEARED:4,
TRUEFRANCHISEFLAG:1,
UPDATEDATE:6,
YELLOWPAGECODE:5,
BOOKPUBLICATIONDATE:6,
SICCOUNT:6,
FRANCHISETYPE1: 1,
FRANCHISETYPE2: 1,
FRANCHISETYPE3: 1,
FRANCHISETYPE4: 1,
FRANCHISETYPE5: 1,
FRANCHISETYPE6: 1,
Filler2:1';


DELETE 
FROM tblChild33_{build_id}_{build}
WHERE abinumber NOT IN 
(
    Select abinumber from {maintable_name}
    ); 


-- Explode records by each Franchise Extended Code because FRANCHISEBYSIC queries all 6 fields
INSERT INTO tblChild33_{build_id}_{build} 
(
    FRANCHISEBYSIC, 
    ABINUMBER,
    ADSIZECODE,
    ATTORNEYCUISINECODE,
    BANKASSETCODE,
    BOOKNUMBER,
    DATEINDATABASE,
    FRANCHISECODE1,
    FRANCHISECODE1_EXTENDED,
    FRANCHISECODE2,
    FRANCHISECODE2_EXTENDED,
    FRANCHISECODE3,
    FRANCHISECODE3_EXTENDED,
    FRANCHISECODE4,
    FRANCHISECODE4_EXTENDED,
    FRANCHISECODE5,
    FRANCHISECODE5_EXTENDED,
    FRANCHISECODE6,
    FRANCHISECODE6_EXTENDED,
    INDUSTRYSPECIFICFIRSTBYTE,
    PRIMARYNAICSCODE_PSIC,
    NAICSCODE,
    PRIMARYSICDESIGNATOR,
    PROFESSIONALSICFLAG,
    SICCODE_PSIC,
    SICCODE,
    SICYEARFIRSTAPPEARED,
    TRUEFRANCHISEFLAG,
    UPDATEDATE,
    YELLOWPAGECODE,
    BOOKPUBLICATIONDATE,
    SICCOUNT
)
SELECT 
    SICCODE + FRANCHISECODE2_EXTENDED,
    ABINUMBER,
    ADSIZECODE,
    ATTORNEYCUISINECODE,
    BANKASSETCODE,
    BOOKNUMBER,
    DATEINDATABASE,
    FRANCHISECODE1,
    FRANCHISECODE1_EXTENDED,
    FRANCHISECODE2,
    FRANCHISECODE2_EXTENDED,
    FRANCHISECODE3,
    FRANCHISECODE3_EXTENDED,
    FRANCHISECODE4,
    FRANCHISECODE4_EXTENDED,
    FRANCHISECODE5,
    FRANCHISECODE5_EXTENDED,
    FRANCHISECODE6,
    FRANCHISECODE6_EXTENDED,
    INDUSTRYSPECIFICFIRSTBYTE,
    PRIMARYNAICSCODE_PSIC,
    NAICSCODE,
    PRIMARYSICDESIGNATOR,
    PROFESSIONALSICFLAG,
    SICCODE_PSIC,
    SICCODE,
    SICYEARFIRSTAPPEARED,
    TRUEFRANCHISEFLAG,
    UPDATEDATE,
    YELLOWPAGECODE,
    BOOKPUBLICATIONDATE,
    SICCOUNT
FROM tblChild33_{build_id}_{build}
    WHERE FRANCHISECODE2_EXTENDED <> ''
UNION ALL
SELECT SICCODE + FRANCHISECODE3_EXTENDED,ABINUMBER,ADSIZECODE,ATTORNEYCUISINECODE,BANKASSETCODE,BOOKNUMBER,DATEINDATABASE,FRANCHISECODE1,FRANCHISECODE1_EXTENDED,FRANCHISECODE2,FRANCHISECODE2_EXTENDED,FRANCHISECODE3,FRANCHISECODE3_EXTENDED,FRANCHISECODE4,FRANCHISECODE4_EXTENDED,FRANCHISECODE5,FRANCHISECODE5_EXTENDED,FRANCHISECODE6,FRANCHISECODE6_EXTENDED,INDUSTRYSPECIFICFIRSTBYTE,PRIMARYNAICSCODE_PSIC,NAICSCODE,PRIMARYSICDESIGNATOR,PROFESSIONALSICFLAG,SICCODE_PSIC,SICCODE,SICYEARFIRSTAPPEARED,TRUEFRANCHISEFLAG,UPDATEDATE,YELLOWPAGECODE,BOOKPUBLICATIONDATE,SICCOUNT
    FROM tblChild33_{build_id}_{build}
    WHERE FRANCHISECODE3_EXTENDED <> ''
UNION ALL
SELECT SICCODE + FRANCHISECODE4_EXTENDED,ABINUMBER,ADSIZECODE,ATTORNEYCUISINECODE,BANKASSETCODE,BOOKNUMBER,DATEINDATABASE,FRANCHISECODE1,FRANCHISECODE1_EXTENDED,FRANCHISECODE2,FRANCHISECODE2_EXTENDED,FRANCHISECODE3,FRANCHISECODE3_EXTENDED,FRANCHISECODE4,FRANCHISECODE4_EXTENDED,FRANCHISECODE5,FRANCHISECODE5_EXTENDED,FRANCHISECODE6,FRANCHISECODE6_EXTENDED,INDUSTRYSPECIFICFIRSTBYTE,PRIMARYNAICSCODE_PSIC,NAICSCODE,PRIMARYSICDESIGNATOR,PROFESSIONALSICFLAG,SICCODE_PSIC,SICCODE,SICYEARFIRSTAPPEARED,TRUEFRANCHISEFLAG,UPDATEDATE,YELLOWPAGECODE,BOOKPUBLICATIONDATE,SICCOUNT
    FROM tblChild33_{build_id}_{build}
    WHERE FRANCHISECODE4_EXTENDED <> ''
UNION ALL
SELECT SICCODE + FRANCHISECODE5_EXTENDED,ABINUMBER,ADSIZECODE,ATTORNEYCUISINECODE,BANKASSETCODE,BOOKNUMBER,DATEINDATABASE,FRANCHISECODE1,FRANCHISECODE1_EXTENDED,FRANCHISECODE2,FRANCHISECODE2_EXTENDED,FRANCHISECODE3,FRANCHISECODE3_EXTENDED,FRANCHISECODE4,FRANCHISECODE4_EXTENDED,FRANCHISECODE5,FRANCHISECODE5_EXTENDED,FRANCHISECODE6,FRANCHISECODE6_EXTENDED,INDUSTRYSPECIFICFIRSTBYTE,PRIMARYNAICSCODE_PSIC,NAICSCODE,PRIMARYSICDESIGNATOR,PROFESSIONALSICFLAG,SICCODE_PSIC,SICCODE,SICYEARFIRSTAPPEARED,TRUEFRANCHISEFLAG,UPDATEDATE,YELLOWPAGECODE,BOOKPUBLICATIONDATE,SICCOUNT
    FROM tblChild33_{build_id}_{build}
    WHERE FRANCHISECODE5_EXTENDED <> ''
UNION ALL
SELECT SICCODE + FRANCHISECODE6_EXTENDED,ABINUMBER,ADSIZECODE,ATTORNEYCUISINECODE,BANKASSETCODE,BOOKNUMBER,DATEINDATABASE,FRANCHISECODE1,FRANCHISECODE1_EXTENDED,FRANCHISECODE2,FRANCHISECODE2_EXTENDED,FRANCHISECODE3,FRANCHISECODE3_EXTENDED,FRANCHISECODE4,FRANCHISECODE4_EXTENDED,FRANCHISECODE5,FRANCHISECODE5_EXTENDED,FRANCHISECODE6,FRANCHISECODE6_EXTENDED,INDUSTRYSPECIFICFIRSTBYTE,PRIMARYNAICSCODE_PSIC,NAICSCODE,PRIMARYSICDESIGNATOR,PROFESSIONALSICFLAG,SICCODE_PSIC,SICCODE,SICYEARFIRSTAPPEARED,TRUEFRANCHISEFLAG,UPDATEDATE,YELLOWPAGECODE,BOOKPUBLICATIONDATE,SICCOUNT
    FROM tblChild33_{build_id}_{build}
    WHERE FRANCHISECODE6_EXTENDED <> '';


UPDATE tblChild33_{build_id}_{build} 
    SET NAICS2  = LEFT(NAICSCODE, 2),
		NAICS4  = LEFT(NAICSCODE, 4),
		NAICS6  = LEFT(NAICSCODE, 6),
		PNAICS2 = LEFT(PRIMARYNAICSCODE_PSIC, 2),
		PNAICS4 = LEFT(PRIMARYNAICSCODE_PSIC, 4),
		PNAICS6 = LEFT(PRIMARYNAICSCODE_PSIC, 6),
		MAJORINDUSTRYGROUP = LEFT(SICCODE, 2),
		MINORINDUSTRYGROUP = LEFT(SICCODE,4),
		FRANCHISEBYSIC = CASE WHEN FRANCHISEBYSIC IS NULL THEN SICCODE + FRANCHISECODE1_EXTENDED ELSE FRANCHISEBYSIC END,
		INDUSTRYSPECIFICBYSIC = SICCODE + IndustrySpecificFirstByte,
		PRIMARYSICFLAG = CASE WHEN PRIMARYSICDESIGNATOR IN ('L','T','C','O','R') THEN 'Y' ELSE 'N' END,
		DATEINDATABASE_YYYY = LEFT(DATEINDATABASE,4)
 
   ; 

UPDATE tblChild33_{build_id}_{build}  
SET INDUSTRYSPECIFICBYSIC = SICCODE + AttorneyCuisineCode
WHERE INDUSTRYSPECIFICBYSIC IN ('581208','783201','811103','581206');

--- TO-DO. We have to add this as a separate task
-- VACUUM DELETE ONLY tblChild33_{build_id}_{build};