DROP TABLE IF EXISTS {igcanada-stage-table};

CREATE TABLE {igcanada-stage-table}
(
    id INT ENCODE AZ64,
    igcnd_contct VARCHAR(34) ENCODE ZSTD,
    igcnd_coname VARCHAR(30) ENCODE ZSTD,
    igcnd_addr VARCHAR(30) ENCODE ZSTD,
    igcnd_suite VARCHAR(6) ENCODE ZSTD,
    igcnd_city VARCHAR(30) ENCODE ZSTD,
    igcnd_prov VARCHAR(2) ENCODE ZSTD,
    igcnd_provds VARCHAR(20) ENCODE ZSTD,
    igcnd_zip VARCHAR(7) ENCODE ZSTD,
    igcnd_distr VARCHAR(3) ENCODE ZSTD,
    igcnd_dstdsc VARCHAR(20) ENCODE ZSTD,
    igcnd_french VARCHAR(1) ENCODE ZSTD,
    igcnd_popcod VARCHAR(1) ENCODE ZSTD,
    igcnd_popdsc VARCHAR(20) ENCODE ZSTD,
    igcnd_phone VARCHAR(10) ENCODE ZSTD,
    igcnd_credit VARCHAR(1) ENCODE ZSTD,
    igcnd_crddsc VARCHAR(15) ENCODE ZSTD,
    igcnd_indfrm VARCHAR(1) ENCODE ZSTD,
    igcnd_inddsc VARCHAR(10) ENCODE ZSTD,
    igcnd_empsiz VARCHAR(1) ENCODE ZSTD,
    igcnd_empdsc VARCHAR(15) ENCODE ZSTD,
    igcnd_salvol VARCHAR(1) ENCODE ZSTD,
    igcnd_saldsc VARCHAR(26) ENCODE ZSTD,
    igcnd_sic VARCHAR(6) ENCODE ZSTD,
    igcnd_sicds1 VARCHAR(45) ENCODE ZSTD,
    igcnd_frncod VARCHAR(6) ENCODE ZSTD,
    igcnd_frdsc1 VARCHAR(40) ENCODE ZSTD,
    igcnd_frdsc2 VARCHAR(40) ENCODE ZSTD,
    igcnd_frdsc3 VARCHAR(40) ENCODE ZSTD,
    igcnd_frdsc4 VARCHAR(40) ENCODE ZSTD,
    igcnd_frdsc5 VARCHAR(40) ENCODE ZSTD,
    igcnd_frdsc6 VARCHAR(40) ENCODE ZSTD,
    igcnd_iscode VARCHAR(1) ENCODE ZSTD,
    igcnd_iscdsc VARCHAR(15) ENCODE ZSTD,
    igcnd_adsiz VARCHAR(1) ENCODE ZSTD,
    igcnd_addsc VARCHAR(15) ENCODE ZSTD,
    igcnd_prmsic VARCHAR(6) ENCODE ZSTD,
    igcnd_prmdsc VARCHAR(45) ENCODE ZSTD,
    igcnd_ssic1 VARCHAR(6) ENCODE ZSTD,
    igcnd_sicds2 VARCHAR(45) ENCODE ZSTD,
    igcnd_ssic2 VARCHAR(6) ENCODE ZSTD,
    igcnd_sicds3 VARCHAR(45) ENCODE ZSTD,
    igcnd_ssic3 VARCHAR(6) ENCODE ZSTD,
    igcnd_sicds4 VARCHAR(45) ENCODE ZSTD,
    igcnd_ssic4 VARCHAR(6) ENCODE ZSTD,
    igcnd_sicds5 VARCHAR(45) ENCODE ZSTD,
    igcnd_year VARCHAR(4) ENCODE ZSTD,
    igcnd_lastnm VARCHAR(20) ENCODE ZSTD,
    igcnd_frstnm VARCHAR(11) ENCODE ZSTD,
    igcnd_prottl VARCHAR(3) ENCODE ZSTD,
    igcnd_ttlcd VARCHAR(1) ENCODE ZSTD,
    igcnd_ttldsc VARCHAR(14) ENCODE ZSTD,
    igcnd_gendcd VARCHAR(1) ENCODE ZSTD,
    igcnd_gendsc VARCHAR(6) ENCODE ZSTD,
    igcnd_hdbrch VARCHAR(1) ENCODE ZSTD,
    igcnd_hqbdsc VARCHAR(20) ENCODE ZSTD,
    igcnd_prodat VARCHAR(8) ENCODE ZSTD,
    igcnd_fphone VARCHAR(10) ENCODE ZSTD,
    igcnd_cma VARCHAR(3) ENCODE ZSTD,
    igcnd_cmadsc VARCHAR(25) ENCODE ZSTD,
    igcnd_offsiz VARCHAR(1) ENCODE ZSTD,
    igcnd_offdsc VARCHAR(20) ENCODE ZSTD,
    igcnd_ttladd VARCHAR(30) ENCODE ZSTD,
    igcnd_keycod VARCHAR(20) ENCODE ZSTD,
    igcnd_pubprv VARCHAR(1) ENCODE ZSTD,
    igcnd_pubdsc VARCHAR(6) ENCODE ZSTD,
    igcnd_locnum VARCHAR(9) ENCODE ZSTD,
    igcnd_subnum VARCHAR(9) ENCODE ZSTD,
    igcnd_ultnum VARCHAR(9) ENCODE ZSTD,
    igcnd_stock VARCHAR(1) ENCODE ZSTD,
    igcnd_stkdsc VARCHAR(9) ENCODE ZSTD,
    igcnd_ticker VARCHAR(6) ENCODE ZSTD,
    igcnd_empsdt VARCHAR(6) ENCODE ZSTD,
    igcnd_slsvdt VARCHAR(9) ENCODE ZSTD,
    igcnd_pactem VARCHAR(6) ENCODE ZSTD,
    igcnd_pactsl VARCHAR(9) ENCODE ZSTD,
    igcnd_pempsz VARCHAR(1) ENCODE ZSTD,
    igcnd_pemdsc VARCHAR(15) ENCODE ZSTD,
    igcnd_psalvl VARCHAR(1) ENCODE ZSTD,
    igcnd_psvdsc VARCHAR(26) ENCODE ZSTD,
    igcnd_scaddr VARCHAR(30) ENCODE ZSTD,
    igcnd_sccity VARCHAR(30) ENCODE ZSTD,
    igcnd_scprov VARCHAR(2) ENCODE ZSTD,
    igcnd_sczip VARCHAR(7) ENCODE ZSTD,
    igcnd_naicsc VARCHAR(8) ENCODE ZSTD,
    igcnd_ncsdsc VARCHAR(50) ENCODE ZSTD,
    igcnd_condes VARCHAR(19) ENCODE ZSTD,
    igcnd_pdinfo VARCHAR(19) ENCODE ZSTD,
    igcnd_srtlvl VARCHAR(1) ENCODE ZSTD,
    igcnd_dmde VARCHAR(8) ENCODE ZSTD,
    igcnd_lsmp VARCHAR(8) ENCODE ZSTD,
    igcnd_seqcon VARCHAR(48) ENCODE ZSTD,
    igcnd_expdate VARCHAR(20) ENCODE ZSTD,
    igcnd_prdatef VARCHAR(20) ENCODE ZSTD,
    igcnd_source VARCHAR(10) ENCODE ZSTD,
    company_mc VARCHAR(15) ENCODE ZSTD,
    igcnd_prmsic4 VARCHAR(10) ENCODE ZSTD,
    igcnd_hasphone VARCHAR(2) ENCODE ZSTD,
    Primary key (company_mc)
)
DISTSTYLE KEY
DISTKEY(company_mc)
SORTKEY(company_mc);


INSERT INTO {igcanada-stage-table}
(
   id,
   igcnd_contct,
   igcnd_coname,
   igcnd_addr,
   igcnd_suite,
   igcnd_city,
   igcnd_prov,
   igcnd_provds,
   igcnd_zip,
   igcnd_distr,
   igcnd_dstdsc,
   igcnd_french,
   igcnd_popcod,
   igcnd_popdsc,
   igcnd_phone,
   igcnd_credit,
   igcnd_crddsc,
   igcnd_indfrm,
   igcnd_inddsc,
   igcnd_empsiz,
   igcnd_empdsc,
   igcnd_salvol,
   igcnd_saldsc,
   igcnd_sic,
   igcnd_sicds1,
   igcnd_frncod,
   igcnd_frdsc1,
   igcnd_frdsc2,
   igcnd_frdsc3,
   igcnd_frdsc4,
   igcnd_frdsc5,
   igcnd_frdsc6,
   igcnd_iscode,
   igcnd_iscdsc,
   igcnd_adsiz,
   igcnd_addsc,
   igcnd_prmsic,
   igcnd_prmdsc,
   igcnd_ssic1,
   igcnd_sicds2,
   igcnd_ssic2,
   igcnd_sicds3,
   igcnd_ssic3,
   igcnd_sicds4,
   igcnd_ssic4,
   igcnd_sicds5,
   igcnd_year,
   igcnd_lastnm,
   igcnd_frstnm,
   igcnd_prottl,
   igcnd_ttlcd,
   igcnd_ttldsc,
   igcnd_gendcd,
   igcnd_gendsc,
   igcnd_hdbrch,
   igcnd_hqbdsc,
   igcnd_prodat,
   igcnd_fphone,
   igcnd_cma,
   igcnd_cmadsc,
   igcnd_offsiz,
   igcnd_offdsc,
   igcnd_ttladd,
   igcnd_keycod,
   igcnd_pubprv,
   igcnd_pubdsc,
   igcnd_locnum,
   igcnd_subnum,
   igcnd_ultnum,
   igcnd_stock,
   igcnd_stkdsc,
   igcnd_ticker,
   igcnd_empsdt,
   igcnd_slsvdt,
   igcnd_pactem,
   igcnd_pactsl,
   igcnd_pempsz,
   igcnd_pemdsc,
   igcnd_psalvl,
   igcnd_psvdsc,
   igcnd_scaddr,
   igcnd_sccity,
   igcnd_scprov,
   igcnd_sczip,
   igcnd_naicsc,
   igcnd_ncsdsc,
   igcnd_condes,
   igcnd_pdinfo,
   igcnd_srtlvl,
   igcnd_dmde,
   igcnd_lsmp,
   igcnd_seqcon,
   igcnd_expdate,
   igcnd_prdatef,
   igcnd_source,
   company_mc,
   igcnd_prmsic4,
   igcnd_hasphone
)
SELECT
   a.id,
   UPPER(a.igcnd_contct),
   UPPER(a.igcnd_coname),
   UPPER(a.igcnd_addr),
   UPPER(a.igcnd_suite),
   UPPER(a.igcnd_city),
   UPPER(a.igcnd_prov),
   UPPER(a.igcnd_provds),
   a.igcnd_zip,   
   UPPER(a.igcnd_distr) ,
   UPPER(a.igcnd_dstdsc) ,
   UPPER(a.igcnd_french) ,
   UPPER(a.igcnd_popcod) ,
   UPPER(a.igcnd_popdsc),
   a.igcnd_phone,  
    UPPER(a.igcnd_credit),
   UPPER(a.igcnd_crddsc) ,
   UPPER(a.igcnd_indfrm),
   UPPER(a.igcnd_inddsc),
   UPPER(a.igcnd_empsiz) ,
   UPPER(a.igcnd_empdsc) ,
   UPPER(a.igcnd_salvol),
   UPPER(a.igcnd_saldsc),
   UPPER(a.igcnd_sic),
   UPPER(a.igcnd_sicds1),
   UPPER(a.igcnd_frncod) ,
   UPPER(a.igcnd_frdsc1) ,
   UPPER(a.igcnd_frdsc2) ,
   UPPER(a.igcnd_frdsc3) ,
   UPPER(a.igcnd_frdsc4) ,
   UPPER(a.igcnd_frdsc5) ,
   UPPER(a.igcnd_frdsc6) ,
   UPPER(a.igcnd_iscode) ,
   UPPER(a.igcnd_iscdsc) ,
   UPPER(a.igcnd_adsiz),
   UPPER(a.igcnd_addsc),
   UPPER(a.igcnd_prmsic),
   UPPER(a.igcnd_prmdsc),
   UPPER(a.igcnd_ssic1),
   UPPER(a.igcnd_sicds2),
   UPPER(a.igcnd_ssic2),
   UPPER(a.igcnd_sicds3),
   UPPER(a.igcnd_ssic3) ,
   UPPER(a.igcnd_sicds4),
   UPPER(a.igcnd_ssic4),
   UPPER(a.igcnd_sicds5),
   UPPER(a.igcnd_year),
   UPPER(a.igcnd_lastnm),
   UPPER(a.igcnd_frstnm),
   UPPER(a.igcnd_prottl),
   UPPER(a.igcnd_ttlcd),
   UPPER(a.igcnd_ttldsc),
   UPPER(a.igcnd_gendcd),
   UPPER(a.igcnd_gendsc),
   UPPER(a.igcnd_hdbrch),
   UPPER(a.igcnd_hqbdsc),
   UPPER(a.igcnd_prodat),
   UPPER(a.igcnd_fphone),
   UPPER(a.igcnd_cma),
   UPPER(a.igcnd_cmadsc),
   UPPER(a.igcnd_offsiz),
   UPPER(a.igcnd_offdsc),
   UPPER(a.igcnd_ttladd),
   UPPER(a.igcnd_keycod),
   UPPER(a.igcnd_pubprv),
   UPPER(a.igcnd_pubdsc),
   UPPER(a.igcnd_locnum),
   UPPER(a.igcnd_subnum),
   UPPER(a.igcnd_ultnum),
   UPPER(a.igcnd_stock),
   UPPER(a.igcnd_stkdsc),
   UPPER(a.igcnd_ticker),
   UPPER(a.igcnd_empsdt),
   UPPER(a.igcnd_slsvdt),
   UPPER(a.igcnd_pactem),
   UPPER(a.igcnd_pactsl),
   UPPER(a.igcnd_pempsz),
   UPPER(a.igcnd_pemdsc),
   UPPER(a.igcnd_psalvl),
   UPPER(a.igcnd_psvdsc),
   UPPER(a.igcnd_scaddr),
   UPPER(a.igcnd_sccity),
   UPPER(a.igcnd_scprov),
   UPPER(a.igcnd_sczip),
   UPPER(a.igcnd_naicsc),
   UPPER(a.igcnd_ncsdsc),
   UPPER(a.igcnd_condes),
   UPPER(a.igcnd_pdinfo),
   UPPER(a.igcnd_srtlvl),
   UPPER(a.igcnd_dmde),
   UPPER(a.igcnd_lsmp),
   UPPER(a.igcnd_seqcon),
   UPPER(a.igcnd_expdate),
   UPPER(a.igcnd_prdatef),
   UPPER(a.igcnd_source),
   GETMATCHCODE (REPLACE(a.igcnd_frstnm,'|',''), REPLACE(a.igcnd_lastnm,'|',''),REPLACE(a.igcnd_addr,'|',''),REPLACE(REPLACE(a.igcnd_zip,'|',''),' ', ''), CASE WHEN (a.igcnd_coname = '' or a.igcnd_coname IS NULL) THEN REPLACE(a.igcnd_lastnm,'|','') ELSE REPLACE(a.igcnd_coname,'|','') END,'C') AS company_mc,
   LEFT(a.igcnd_prmsic,4) AS igcnd_prmsic4,
   CASE WHEN LTRIM(RTRIM(a.igcnd_phone)) <>'' THEN 'Y' END AS igcnd_hasphone
FROM {igcanada-raw-table} a
WHERE a.id IN
(
   SELECT MAX(id) AS id FROM {igcanada-raw-table}
    GROUP BY GETMATCHCODE (igcnd_frstnm, igcnd_lastnm, igcnd_addr, igcnd_zip, CASE WHEN (igcnd_coname = '' or igcnd_coname is NULL) THEN igcnd_lastnm ELSE igcnd_coname END,'C')
);

DROP TABLE IF EXISTS {igcanada-raw-table};
DROP TABLE IF EXISTS {maintable_name} CASCADE;
ALTER TABLE {igcanada-stage-table} RENAME TO {maintable_name};
