DROP TABLE IF EXISTS {igus-stage-table};
CREATE TABLE {igus-stage-table} 
(
    id INT ENCODE AZ64,
    igus_contactmrg VARCHAR(30) ENCODE ZSTD,
    igus_coname VARCHAR(30) ENCODE ZSTD,
    igus_prmaddr VARCHAR(30) ENCODE ZSTD,
    igus_prmcity VARCHAR(16) ENCODE ZSTD,
    igus_prmstate VARCHAR(2) ENCODE ZSTD,
    igus_prmzip VARCHAR(5) ENCODE ZSTD,
    igus_prmzip4 VARCHAR(4) ENCODE ZSTD,
    igus_prmzipmrg VARCHAR(10) ENCODE ZSTD,
    igus_prmcrcd VARCHAR(4) ENCODE ZSTD,
    igus_prmstcd VARCHAR(2) ENCODE ZSTD,
    igus_cntycd VARCHAR(3) ENCODE ZSTD,
    igus_cntyds VARCHAR(14) ENCODE ZSTD,
    igus_msacd VARCHAR(4) ENCODE ZSTD ,
    igus_msads VARCHAR(30) ENCODE ZSTD ,
    igus_cbsacd VARCHAR(5) ENCODE ZSTD,
    igus_cbsads VARCHAR(16) ENCODE ZSTD,
    igus_metroind VARCHAR(1) ENCODE ZSTD,
    igus_csacode VARCHAR(3) ENCODE ZSTD,
    igus_csadesc VARCHAR(50) ENCODE ZSTD,
    igus_centrct VARCHAR(6) ENCODE ZSTD,
    igus_blockgrp VARCHAR(1) ENCODE ZSTD,
    igus_latitudeo VARCHAR(10) ENCODE ZSTD,
    igus_longitudeo VARCHAR(11) ENCODE ZSTD,
    igus_matchcd VARCHAR(1) ENCODE ZSTD,
    igus_secaddr VARCHAR(30) ENCODE ZSTD,
    igus_seccity VARCHAR(16) ENCODE ZSTD,
    igus_secstate VARCHAR(2) ENCODE ZSTD,
    igus_secstcd VARCHAR(2) ENCODE ZSTD,
    igus_seczip VARCHAR(5) ENCODE ZSTD,
    igus_seczip4 VARCHAR(4) ENCODE ZSTD,
    igus_seczipmrg VARCHAR(10) ENCODE ZSTD,
    igus_seccrcd VARCHAR(4) ENCODE ZSTD,
    igus_phonenumo VARCHAR(12) ENCODE ZSTD,
    igus_faxnumo VARCHAR(12) ENCODE ZSTD,
    igus_tollfrnumo VARCHAR(12) ENCODE ZSTD,
    igus_webaddr VARCHAR(40) ENCODE ZSTD,
    igus_selsiccd VARCHAR(6) ENCODE ZSTD,
    igus_selsicds VARCHAR(45) ENCODE ZSTD,
    igus_frncd1x VARCHAR(1) ENCODE ZSTD ,
    igus_frnds1 VARCHAR(40) ENCODE ZSTD,
    igus_frncd2x VARCHAR(1) ENCODE ZSTD ,
    igus_frnds2 VARCHAR(40) ENCODE ZSTD,
    igus_frncd3x VARCHAR(1) ENCODE ZSTD ,
    igus_frnds3 VARCHAR(40) ENCODE ZSTD ,
    igus_frncd4x VARCHAR(1) ENCODE ZSTD,
    igus_frnds4 VARCHAR(40) ENCODE ZSTD ,
    igus_frncd5x VARCHAR(1) ENCODE ZSTD,
    igus_frnds5 VARCHAR(40) ENCODE ZSTD,
    igus_frncd6x VARCHAR(1) ENCODE ZSTD,
    igus_frnds6 VARCHAR(40) ENCODE ZSTD,
    igus_trufrnflg VARCHAR(1) ENCODE ZSTD,
    igus_indspccd VARCHAR(1) ENCODE ZSTD ,
    igus_incspcds VARCHAR(40) ENCODE ZSTD,
    igus_prmsiccd VARCHAR(6) ENCODE ZSTD,
    igus_prmsicds VARCHAR(45) ENCODE ZSTD,
    igus_secsiccd1 VARCHAR(6) ENCODE ZSTD,
    igus_secsicds1 VARCHAR(45) ENCODE ZSTD,
    igus_secsiccd2 VARCHAR(6) ENCODE ZSTD,
    igus_secsicds2 VARCHAR(45) ENCODE ZSTD,
    igus_secsiccd3 VARCHAR(6) ENCODE ZSTD,
    igus_secsicds3 VARCHAR(45) ENCODE ZSTD,
    igus_secsiccd4 VARCHAR(6) ENCODE ZSTD,
    igus_secsidds4 VARCHAR(45) ENCODE ZSTD,
    igus_naicscd VARCHAR(8) ENCODE ZSTD,
    igus_naicsds VARCHAR(50) ENCODE ZSTD,
    igus_lempszcd VARCHAR(1) ENCODE ZSTD,
    igus_lempszds VARCHAR(9) ENCODE ZSTD,
    igus_alempsz VARCHAR(5) ENCODE ZSTD,
    igus_cempszcd VARCHAR(1) ENCODE ZSTD ,
    igus_cempszds VARCHAR(9) ENCODE ZSTD,
    igus_acempsz VARCHAR(6) ENCODE ZSTD ,
    igus_modesflg VARCHAR(1) ENCODE ZSTD,
    igus_lsalvolcd VARCHAR(1) ENCODE ZSTD,
    igus_lsalvolds VARCHAR(18) ENCODE ZSTD,
    igus_alslsvol VARCHAR(9) ENCODE ZSTD,
    igus_csalvolcd VARCHAR(1) ENCODE ZSTD,
    igus_csalvolds VARCHAR(18) ENCODE ZSTD ,
    igus_acslsvol VARCHAR(9) ENCODE ZSTD ,
    igus_assetszflg VARCHAR(1) ENCODE ZSTD,
    igus_lastnm VARCHAR(14) ENCODE ZSTD,
    igus_frstnm VARCHAR(11) ENCODE ZSTD,
    igus_salute VARCHAR(2) ENCODE ZSTD,
    igus_gendcd VARCHAR(1) ENCODE ZSTD,
    igus_prottl VARCHAR(3) ENCODE ZSTD,
    igus_ttlcd VARCHAR(1) ENCODE ZSTD,
    igus_ttlds VARCHAR(18) ENCODE ZSTD,
    igus_ethniccode VARCHAR(2) ENCODE ZSTD,
    igus_ehnicddes VARCHAR(40) ENCODE ZSTD,
    igus_keycd VARCHAR(20) ENCODE ZSTD ,
    igus_ttladdr VARCHAR(30) ENCODE ZSTD ,
    igus_abinum VARCHAR(9) ENCODE ZSTD,
    igus_subnum VARCHAR(9) ENCODE ZSTD,
    igus_ultnum VARCHAR(9) ENCODE ZSTD,
    igus_sitenum VARCHAR(9) ENCODE ZSTD,
    igus_busstatcd VARCHAR(1) ENCODE ZSTD,
    igus_busstatds VARCHAR(20) ENCODE ZSTD,
    igus_pubprvcd VARCHAR(1) ENCODE ZSTD,
    igus_stockexcd VARCHAR(1) ENCODE ZSTD,
    igus_stockexds VARCHAR(6) ENCODE ZSTD,
    igus_ticker VARCHAR(6) ENCODE ZSTD,
    igus_pubfiling VARCHAR(1) ENCODE ZSTD,
    igus_fortunernk VARCHAR(4) ENCODE ZSTD,
    igus_indfirmcd VARCHAR(1) ENCODE ZSTD,
    igus_indfirmds VARCHAR(13) ENCODE ZSTD,
    igus_yrsicadded VARCHAR(6) ENCODE ZSTD,
    igus_yrfirstapp VARCHAR(4) ENCODE ZSTD,
    igus_yrestblshd VARCHAR(4) ENCODE ZSTD,
    igus_ypcode VARCHAR(5) ENCODE ZSTD,
    igus_transdate VARCHAR(6) ENCODE ZSTD,
    igus_transtype VARCHAR(1) ENCODE ZSTD,
    igus_telresdate VARCHAR(6) ENCODE ZSTD,
    igus_callstatcd VARCHAR(1) ENCODE ZSTD,
    igus_callstatds VARCHAR(25) ENCODE ZSTD,
    igus_crdscrcd VARCHAR(2) ENCODE ZSTD,
    igus_crdscrds VARCHAR(24) ENCODE ZSTD,
    igus_actcrdscr VARCHAR(3) ENCODE ZSTD,
    igus_adsizecd VARCHAR(1) ENCODE ZSTD,
    igus_adsizeds VARCHAR(15) ENCODE ZSTD,
    igus_offsizcd VARCHAR(1) ENCODE ZSTD,
    igus_offsizds VARCHAR(16) ENCODE ZSTD,
    igus_popcd VARCHAR(1) ENCODE ZSTD,
    igus_popds VARCHAR(20) ENCODE ZSTD,
    igus_workhome VARCHAR(1) ENCODE ZSTD ,
    igus_ownleasecd VARCHAR(1) ENCODE ZSTD ,
    igus_sqfootcd VARCHAR(1) ENCODE ZSTD,
    igus_sqfootds VARCHAR(15) ENCODE ZSTD,
    igus_raddisto VARCHAR(5) ENCODE ZSTD,
    igus_actmultitn VARCHAR(7) ENCODE ZSTD,
    igus_multitntcd VARCHAR(1) ENCODE ZSTD,
    igus_multitntds VARCHAR(9) ENCODE ZSTD,
    igus_bldmultitn VARCHAR(7) ENCODE ZSTD,
    igus_fleetcd VARCHAR(1) ENCODE ZSTD,
    igus_fleetds VARCHAR(40) ENCODE ZSTD,
    igus_affluent VARCHAR(1) ENCODE ZSTD,
    igus_bgbusiness VARCHAR(1) ENCODE ZSTD,
    igus_femowner VARCHAR(1) ENCODE ZSTD,
    igus_bussizechg VARCHAR(1) ENCODE ZSTD,
    igus_highincex VARCHAR(1) ENCODE ZSTD,
    igus_hightech VARCHAR(1) ENCODE ZSTD,
    igus_mdbusentr VARCHAR(1) ENCODE ZSTD,
    igus_smbusentr VARCHAR(1) ENCODE ZSTD,
    igus_maildlptbo VARCHAR(12) ENCODE ZSTD ,
    igus_endorseln VARCHAR(30) ENCODE ZSTD,
    igus_bagnum VARCHAR(9) ENCODE ZSTD,
    igus_bundlenum VARCHAR(9) ENCODE ZSTD,
    igus_pslntravel VARCHAR(7) ENCODE ZSTD,
    igus_teraddr VARCHAR(30) ENCODE ZSTD,
    igus_tercity VARCHAR(16) ENCODE ZSTD,
    igus_terstate VARCHAR(2) ENCODE ZSTD,
    igus_terzip VARCHAR(5) ENCODE ZSTD,
    igus_terzip4 VARCHAR(4) ENCODE ZSTD,
    igus_terzipmrg VARCHAR(10) ENCODE ZSTD,
    igus_tercrcd VARCHAR(4) ENCODE ZSTD,
    igus_wcperctage VARCHAR(4) ENCODE ZSTD,
    igus_wcind VARCHAR(1) ENCODE ZSTD,
    igus_prddate VARCHAR(8) ENCODE ZSTD,
    igus_seqnum VARCHAR(10) ENCODE ZSTD,
    igus_expdate VARCHAR(20) ENCODE ZSTD,
    igus_prdatef VARCHAR(20) ENCODE ZSTD,
    igus_source VARCHAR(10) ENCODE ZSTD,
    igus_booknum VARCHAR(5) ENCODE ZSTD,
    igus_govsegcd VARCHAR(1) ENCODE ZSTD,
    igus_foreignpar VARCHAR(1) ENCODE ZSTD,
    igus_imptexptcd VARCHAR(1) ENCODE ZSTD,
    igus_frncd1 VARCHAR(3) ENCODE ZSTD,
    igus_frncd2 VARCHAR(3) ENCODE ZSTD,
    igus_frncd3 VARCHAR(3) ENCODE ZSTD,
    igus_frncd4 VARCHAR(3) ENCODE ZSTD,
    igus_frncd5 VARCHAR(3) ENCODE ZSTD,
    igus_frncd6 VARCHAR(3) ENCODE ZSTD,
    igus_execemail VARCHAR(60) ENCODE ZSTD,
    company_mc VARCHAR(15) ENCODE ZSTD,
    igus_prmsiccode4 VARCHAR(4) ENCODE ZSTD,
    igus_hasphone VARCHAR(1) ENCODE ZSTD,
    igus_prmsiccode2 VARCHAR(2) ENCODE ZSTD,
    PRIMARY KEY (company_mc)
)
DISTSTYLE KEY
DISTKEY(company_mc)
SORTKEY(company_mc);

INSERT INTO {igus-stage-table}
(
    id,
    igus_contactmrg,
    igus_coname,
    igus_prmaddr,
    igus_prmcity,
    igus_prmstate,
    igus_prmzip,
    igus_prmzip4,
    igus_prmzipmrg,
    igus_prmcrcd,
    igus_prmstcd,
    igus_cntycd,
    igus_cntyds,
    igus_msacd,
    igus_msads,
    igus_cbsacd,
    igus_cbsads,
    igus_metroind,
    igus_csacode,
    igus_csadesc,
    igus_centrct,
    igus_blockgrp,
    igus_latitudeo,
    igus_longitudeo,
    igus_matchcd,
    igus_secaddr,
    igus_seccity,
    igus_secstate,
    igus_secstcd,
    igus_seczip,
    igus_seczip4,
    igus_seczipmrg,
    igus_seccrcd,
    igus_phonenumo,
    igus_faxnumo,
    igus_tollfrnumo,
    igus_webaddr,
    igus_selsiccd,
    igus_selsicds,
    igus_frncd1x,
    igus_frnds1,
    igus_frncd2x,
    igus_frnds2,
    igus_frncd3x,
    igus_frnds3,
    igus_frncd4x,
    igus_frnds4,
    igus_frncd5x,
    igus_frnds5,
    igus_frncd6x,
    igus_frnds6,
    igus_trufrnflg,
    igus_indspccd,
    igus_incspcds,
    igus_prmsiccd,
    igus_prmsicds,
    igus_secsiccd1,
    igus_secsicds1,
    igus_secsiccd2,
    igus_secsicds2,
    igus_secsiccd3,
    igus_secsicds3,
    igus_secsiccd4,
    igus_secsidds4,
    igus_naicscd,
    igus_naicsds,
    igus_lempszcd,
    igus_lempszds,
    igus_alempsz,
    igus_cempszcd,
    igus_cempszds,
    igus_acempsz,
    igus_modesflg,
    igus_lsalvolcd,
    igus_lsalvolds,
    igus_alslsvol,
    igus_csalvolcd,
    igus_csalvolds,
    igus_acslsvol,
    igus_assetszflg,
    igus_lastnm,
    igus_frstnm,
    igus_salute,
    igus_gendcd,
    igus_prottl,
    igus_ttlcd,
    igus_ttlds,
    igus_ethniccode,
    igus_ehnicddes,
    igus_keycd,
    igus_ttladdr,
    igus_abinum,
    igus_subnum,
    igus_ultnum,
    igus_sitenum,
    igus_busstatcd,
    igus_busstatds,
    igus_pubprvcd,
    igus_stockexcd,
    igus_stockexds,
    igus_ticker,
    igus_pubfiling,
    igus_fortunernk,
    igus_indfirmcd,
    igus_indfirmds,
    igus_yrsicadded,
    igus_yrfirstapp,
    igus_yrestblshd,
    igus_ypcode,
    igus_transdate,
    igus_transtype,
    igus_telresdate,
    igus_callstatcd,
    igus_callstatds,
    igus_crdscrcd,
    igus_crdscrds,
    igus_actcrdscr,
    igus_adsizecd,
    igus_adsizeds,
    igus_offsizcd,
    igus_offsizds,
    igus_popcd,
    igus_popds,
    igus_workhome,
    igus_ownleasecd,
    igus_sqfootcd,
    igus_sqfootds,
    igus_raddisto,
    igus_actmultitn,
    igus_multitntcd,
    igus_multitntds,
    igus_bldmultitn,
    igus_fleetcd,
    igus_fleetds,
    igus_affluent,
    igus_bgbusiness,
    igus_femowner,
    igus_bussizechg,
    igus_highincex,
    igus_hightech,
    igus_mdbusentr,
    igus_smbusentr,
    igus_maildlptbo,
    igus_endorseln,
    igus_bagnum,
    igus_bundlenum,
    igus_pslntravel,
    igus_teraddr,
    igus_tercity,
    igus_terstate,
    igus_terzip,
    igus_terzip4,
    igus_terzipmrg,
    igus_tercrcd,
    igus_wcperctage,
    igus_wcind,
    igus_prddate,
    igus_seqnum,
    igus_expdate,
    igus_prdatef,
    igus_source,
    igus_booknum,
    igus_govsegcd,
    igus_foreignpar,
    igus_imptexptcd,
    igus_frncd1,
    igus_frncd2,
    igus_frncd3,
    igus_frncd4,
    igus_frncd5,
    igus_frncd6,
    igus_execemail,
    company_mc,
    igus_prmsiccode4,
    igus_hasphone,
    igus_prmsiccode2
)
SELECT
    a.id,
    UPPER(a.igus_contactmrg),
    UPPER(a.igus_coname),
    UPPER(a.igus_prmaddr),
    UPPER(a.igus_prmcity),
    UPPER(a.igus_prmstate),
    UPPER(a.igus_prmzip),
    UPPER(a.igus_prmzip4),
    UPPER(a.igus_prmzipmrg),
    UPPER(a.igus_prmcrcd),
    UPPER(a.igus_prmstcd),
    UPPER(a.igus_cntycd),
    UPPER(a.igus_cntyds),
    UPPER(a.igus_msacd) ,
    UPPER(a.igus_msads),
    UPPER(a.igus_cbsacd),
    UPPER(a.igus_cbsads),
    UPPER(a.igus_metroind),
    UPPER(a.igus_csacode),
    UPPER(a.igus_csadesc),
    UPPER(a.igus_centrct),
    UPPER(a.igus_blockgrp),
    UPPER(a.igus_latitudeo),
    UPPER(a.igus_longitudeo),
    UPPER(a.igus_matchcd),
    UPPER(a.igus_secaddr),
    UPPER(a.igus_seccity),
    UPPER(a.igus_secstate),
    UPPER(a.igus_secstcd),
    UPPER(a.igus_seczip),
    UPPER(a.igus_seczip4),
    UPPER(a.igus_seczipmrg),
    UPPER(a.igus_seccrcd),
    UPPER(a.igus_phonenumo),
    UPPER(a.igus_faxnumo),
    UPPER(a.igus_tollfrnumo),
    UPPER(a.igus_webaddr),
    UPPER(a.igus_selsiccd),
    UPPER(a.igus_selsicds),
    UPPER(a.igus_frncd1x),
    UPPER(a.igus_frnds1),
    UPPER(a.igus_frncd2x),
    UPPER(a.igus_frnds2),
    UPPER(a.igus_frncd3x),
    UPPER(a.igus_frnds3),
    UPPER(a.igus_frncd4x),
    UPPER(a.igus_frnds4),
    UPPER(a.igus_frncd5x),
    UPPER(a.igus_frnds5),
    UPPER(a.igus_frncd6x),
    UPPER(a.igus_frnds6),
    UPPER(a.igus_trufrnflg),
    UPPER(a.igus_indspccd),
    UPPER(a.igus_incspcds),
    UPPER(a.igus_prmsiccd),
    UPPER(a.igus_prmsicds),
    UPPER(a.igus_secsiccd1),
    UPPER(a.igus_secsicds1),
    UPPER(a.igus_secsiccd2),
    UPPER(a.igus_secsicds2),
    UPPER(a.igus_secsiccd3),
    UPPER(a.igus_secsicds3),
    UPPER(a.igus_secsiccd4),
    UPPER(a.igus_secsidds4),
    UPPER(a.igus_naicscd),
    UPPER(a.igus_naicsds),
    UPPER(a.igus_lempszcd),
    UPPER(a.igus_lempszds),
    UPPER(a.igus_alempsz),
    UPPER(a.igus_cempszcd),
    UPPER(a.igus_cempszds),
    UPPER(a.igus_acempsz),
    UPPER(a.igus_modesflg),
    UPPER(a.igus_lsalvolcd),
    UPPER(a.igus_lsalvolds),
    UPPER(a.igus_alslsvol),
    UPPER(a.igus_csalvolcd),
    UPPER(a.igus_csalvolds),
    UPPER(a.igus_acslsvol),
    UPPER(a.igus_assetszflg),
    UPPER(a.igus_lastnm),
    UPPER(a.igus_frstnm),
    UPPER(a.igus_salute),
    UPPER(a.igus_gendcd),
    UPPER(a.igus_prottl),
    UPPER(a.igus_ttlcd),
    UPPER(a.igus_ttlds),
    UPPER(a.igus_ethniccode),
    UPPER(a.igus_ehnicddes),
    UPPER(a.igus_keycd),
    UPPER(a.igus_ttladdr),
    UPPER(a.igus_abinum),
    UPPER(a.igus_subnum),
    UPPER(a.igus_ultnum),
    UPPER(a.igus_sitenum),
    UPPER(a.igus_busstatcd),
    UPPER(a.igus_busstatds),
    UPPER(a.igus_pubprvcd),
    UPPER(a.igus_stockexcd),
    UPPER(a.igus_stockexds),
    UPPER(a.igus_ticker),
    UPPER(a.igus_pubfiling),
    UPPER(a.igus_fortunernk),
    UPPER(a.igus_indfirmcd),
    UPPER(a.igus_indfirmds),
    UPPER(a.igus_yrsicadded),
    UPPER(a.igus_yrfirstapp),
    UPPER(a.igus_yrestblshd),
    UPPER(a.igus_ypcode),
    UPPER(a.igus_transdate),
    UPPER(a.igus_transtype),
    UPPER(a.igus_telresdate),
    UPPER(a.igus_callstatcd),
    UPPER(a.igus_callstatds),
    UPPER(a.igus_crdscrcd),
    UPPER(a.igus_crdscrds),
    UPPER(a.igus_actcrdscr),
    UPPER(a.igus_adsizecd),
    UPPER(a.igus_adsizeds),
    UPPER(a.igus_offsizcd),
    UPPER(a.igus_offsizds),
    UPPER(a.igus_popcd),
    UPPER(a.igus_popds),
    UPPER(a.igus_workhome),
    UPPER(a.igus_ownleasecd),
    UPPER(a.igus_sqfootcd),
    UPPER(a.igus_sqfootds),
    UPPER(a.igus_raddisto),
    UPPER(a.igus_actmultitn),
    UPPER(a.igus_multitntcd),
    UPPER(a.igus_multitntds),
    UPPER(a.igus_bldmultitn),
    UPPER(a.igus_fleetcd),
    UPPER(a.igus_fleetds),
    UPPER(a.igus_affluent),
    UPPER(a.igus_bgbusiness),
    UPPER(a.igus_femowner),
    UPPER(a.igus_bussizechg),
    UPPER(a.igus_highincex),
    UPPER(a.igus_hightech),
    UPPER(a.igus_mdbusentr),
    UPPER(a.igus_smbusentr),
    UPPER(a.igus_maildlptbo),
    UPPER(a.igus_endorseln),
    UPPER(a.igus_bagnum),
    UPPER(a.igus_bundlenum),
    UPPER(a.igus_pslntravel),
    UPPER(a.igus_teraddr),
    UPPER(a.igus_tercity),
    UPPER(a.igus_terstate),
    UPPER(a.igus_terzip),
    UPPER(a.igus_terzip4),
    UPPER(a.igus_terzipmrg),
    UPPER(a.igus_tercrcd),
    UPPER(a.igus_wcperctage),
    UPPER(a.igus_wcind),
    UPPER(a.igus_prddate),
    UPPER(a.igus_seqnum),
    UPPER(a.igus_expdate),
    UPPER(a.igus_prdatef),
    UPPER(a.igus_source),
    UPPER(a.igus_booknum),
    UPPER(a.igus_govsegcd),
    UPPER(a.igus_foreignpar),
    UPPER(a.igus_imptexptcd),
    UPPER(a.igus_frncd1),
    UPPER(a.igus_frncd2),
    UPPER(a.igus_frncd3),
    UPPER(a.igus_frncd4),
    UPPER(a.igus_frncd5),
    UPPER(a.igus_frncd6),
    UPPER(a.igus_execemail),
    GetMatchCode (REPLACE(a.igus_frstnm,'|',''), REPLACE(a.igus_lastnm,'|',''),REPLACE(a.igus_prmaddr,'|',''), REPLACE(REPLACE(a.igus_prmzip,'|',''),' ', ''), REPLACE(a.igus_coname,'|',''),'C'),
    LEFT(UPPER(a.igus_prmsiccd),4),
    CASE WHEN LTRIM(RTRIM(a.igus_phonenumo)) <> '' THEN 'Y' ELSE a.igus_hasphone END,
    LEFT(UPPER(a.igus_prmsiccd),2)
FROM {igus-raw-table} a
WHERE a.id IN 
(
    SELECT MAX(id) AS id FROM {igus-raw-table}
    GROUP BY GetMatchCode (igus_frstnm, igus_lastnm, igus_prmaddr, igus_prmzip, igus_coname,'C')
);

