drop table if exists {auto_tablename4};

CREATE TABLE  {auto_tablename4} (
vin varchar(17),
shortvin varchar(10),
firstname varchar(30),
MIDDLE_INITIAL varchar(1),
lastname varchar(30),
gender varchar(1),
make varchar(30),
model varchar(30),
year varchar(4),
odometer varchar(6),
transaction_date varchar(8),
transyyyymm varchar(6),
drive_type varchar(3),
fuel_type varchar(1),
luxnon varchar(1),
bodytype varchar(15),
domimp varchar(1),
vehtype varchar(5),
transyear varchar(4),
vehrecno varchar(20),
lems varchar(18),
CE_Household_ID varchar(12),
CE_Selected_Individual_ID varchar(12),
SQLMC varchar(25),
AddressLine1 varchar(40),
AddressLine2 varchar(40),
City varchar(28),
State varchar(2),
ZIP varchar(5),
ZIP4 varchar(4),
AH1_MAILABILITY_SCORE varchar(2),
CARRIER_ROUTE_CODE varchar(4),
AH1_LOT_NUMBER varchar(5),
AH1_LOT_SORTATION_NUMBER varchar(2),
DPBC varchar(3),
Email_Address_s varchar(80),
open_flag varchar(1),
open_date_YYYYMM varchar(6),
click_flag varchar(1),
click_date_yyyymm varchar(6),
Vendor_Code varchar(2),
Domain varchar(80),
email_domain varchar(20),
md5_email_lower varchar(32),
md5_email_upper varchar(32),
IHASH varchar(32),
bestdate_yyyymm varchar(6),
individual_mc varchar(17),
company varchar(1),
zipfull varchar(9),
scf varchar(3),
oneperhhld varchar(18),
pres_of_Email_address_flag varchar(1),
COUNTY_CODE varchar(3),
RES_BUS_INDC varchar(1),
LONGITUDE Varchar(11),
LATITUDE Varchar(11),
NTF_VIN varchar(7),                   /* Added by Reeba J on 02.14.2019 as per  Incident: 753241 */
CAR_NUMBER  varchar(12),              /* Added by Reeba J on 05.14.2019 as per Incident: 777184 */
CBSA_CODE  varchar(5),                /* Added by Reeba J on 11.14.2019 as per Incident: 820688 */
CBSA_TYPE  varchar(5),                /* Added by Reeba J on 11.14.2019 as per Incident: 820688 */
CBSA_NAME  varchar(50),                /* Added by Reeba J on 11.14.2019 as per Incident: 820688 */
eor varchar(1),
ID int IDENTITY UNIQUE
);

copy {auto_tablename4}
from 's3://{s3-internal}/internaltransfer/UPDATE_1025_{build_id}.txt'
iam_role '{iam}'
acceptinvchars
fixedwidth
'vin:17,
shortvin:10,
firstname:30,
MIDDLE_INITIAL:1,
lastname:30,
gender:1,
make:30,
model:30,
year:4,
odometer:6,
transaction_date:8,
transyyyymm:6,
drive_type:3,
fuel_type:1,
luxnon:1,
bodytype:15,
domimp:1,
vehtype:5,
transyear:4,
vehrecno:20,
lems:18,
CE_Household_ID:12,
CE_Selected_Individual_ID:12,
SQLMC:25,
AddressLine1:40,
AddressLine2:40,
City:28,
State:2,
ZIP:5,
ZIP4:4,
AH1_MAILABILITY_SCORE:2,
CARRIER_ROUTE_CODE:4,
AH1_LOT_NUMBER:5,
AH1_LOT_SORTATION_NUMBER:2,
DPBC:3,
Email_Address_s:80,
open_flag:1,
open_date_YYYYMM:6,
click_flag:1,
click_date_yyyymm:6,
Vendor_Code:2,
Domain:80,
email_domain:20,
md5_email_lower:32,
md5_email_upper:32,
IHASH:32,
bestdate_yyyymm:6,
individual_mc:17,
company:1,
zipfull:9,
scf:3,
oneperhhld:18,
pres_of_Email_address_flag:1,
COUNTY_CODE:3,
RES_BUS_INDC:1,
LONGITUDE:11,
LATITUDE:11,
NTF_VIN:7,
CAR_NUMBER:12,
CBSA_CODE:5,
CBSA_TYPE:5,
CBSA_NAME:50,
eor:1'
;

