DROP TABLE IF EXISTS {tablename1} ;

CREATE TABLE {tablename1}
(
	lastname VARCHAR(20),
	firstname VARCHAR(15),
	middlename VARCHAR(15),
	title VARCHAR(1),
	gender VARCHAR(1),
	addressline1 VARCHAR(40),
	city VARCHAR(28),
	state VARCHAR(2),
	zip VARCHAR(5),
	zipfour VARCHAR(4),
	carrierroutecode VARCHAR(4),
	delivery_point_bar_code VARCHAR(3),
	industrytitle VARCHAR(50),
	occupationtitle VARCHAR(50),
	specialtytitle VARCHAR(50),
	censusstatecode VARCHAR(2),
	censuscountycode VARCHAR(3),
	censustract VARCHAR(6),
	censusblockgroup VARCHAR(1),
	highrise VARCHAR(2),
	yearlicensed VARCHAR(4),
	licensestate VARCHAR(2),
	licensenumber VARCHAR(25),
	enhancedphone VARCHAR(1),
	area_code VARCHAR(3),
	phone_number VARCHAR(7),
	time_zone VARCHAR(1),
	numberofchildren VARCHAR(1),
	childrenbygender0 VARCHAR(1),
	childrenbygender1 VARCHAR(1),
	childrenbygender2 VARCHAR(1),
	childrenbygender3 VARCHAR(1),
	childrenbygender4 VARCHAR(1),
	childrenbygender5 VARCHAR(1),
	childrenbygender6 VARCHAR(1),
	childrenbygender7 VARCHAR(1),
	childrenbygender8 VARCHAR(1),
	childrenbygender9 VARCHAR(1),
	childrenbygender10 VARCHAR(1),
	childrenbygender11 VARCHAR(1),
	childrenbygender12 VARCHAR(1),
	childrenbygender13 VARCHAR(1),
	childrenbygender14 VARCHAR(1),
	childrenbygender15 VARCHAR(1),
	childrenbygender16 VARCHAR(1),
	childrenbygender17 VARCHAR(1),
	length_of_residence VARCHAR(2),
	own_rent_indicator VARCHAR(1),
	find_income VARCHAR(6),
	activebankcard VARCHAR(1),
	donor_ever VARCHAR(1),
	home_value_code VARCHAR(1),
	cat_owner VARCHAR(1),
	dog_owner VARCHAR(1),
	mail_responsive VARCHAR(1),
	mail_responsive_previous VARCHAR(1),
	mail_order VARCHAR(1),
	marital_status VARCHAR(1),
	health_contributor VARCHAR(1),
	political_contributor VARCHAR(1),
	religious_contirbutor VARCHAR(1),
	personal_computer VARCHAR(1),
	age VARCHAR(3),
	latitude VARCHAR(9),
	longitude VARCHAR(9),
	geo_match_code VARCHAR(1),
	cbsa_code VARCHAR(5),
	cbsa_code_description VARCHAR(50),
	cbsa_level_description VARCHAR(5),
	county_code VARCHAR(3),
	mailscore VARCHAR(2),
	housenumber VARCHAR(10),
	streetpredirectional VARCHAR(2),
	streetname VARCHAR(28),
	streetsuffix VARCHAR(4),
	streetpostdirectional VARCHAR(2),
	unittype VARCHAR(4),
	unitnumber VARCHAR(8),
	vendorethnicity VARCHAR(2),
	occupationid VARCHAR(12),
	fulfillmentflag VARCHAR(1),
	emailaddress VARCHAR(60),
	emailmatchindicator VARCHAR(1),
	emailsource VARCHAR(2),
	residentialbusinessindicator VARCHAR(1),
	employername VARCHAR(30),
	familyid VARCHAR(12),
	individualid VARCHAR(12),
	abinumber VARCHAR(9),
	siccode VARCHAR(6),
	scf VARCHAR(3),
	licensestatuscode VARCHAR(1),
	md5_upper VARCHAR(32),
	md5_lower VARCHAR(32),
	state_donotcall_flag VARCHAR(1),
	ce_education_model VARCHAR(1),
	ce_education_model_desc	VARCHAR(31),
	individual_mc_wb VARCHAR(17),
	company_mc_wb VARCHAR(17),
	email_marketable VARCHAR(1),
	email_reputation_risk VARCHAR(1),
	BV_flag VARCHAR(1),
	filler_1 VARCHAR(2),
	id Int identity,
	zipradius VARCHAR(1),
	georadius VARCHAR(1),
	fullname VARCHAR(50),
	zipfull VARCHAR(9),
	emailavailable VARCHAR(1),
	fax VARCHAR(20),
	phone VARCHAR(20),
	phone_available VARCHAR(1),
	domain_name VARCHAR(60),
	company VARCHAR(30),
	addressline2 VARCHAR(50),
	listid integer,
	productcode VARCHAR(2),
	listtype VARCHAR(1),
	permissiontype VARCHAR(1),
	dropflag VARCHAR(1),
	industrytitlecode VARCHAR(2),
	occupationtitlecode VARCHAR(3),
	specialtytitlecode VARCHAR(3),
	hardkey VARCHAR(55),
	flatitude float,
	flongitude float,
	statecountyname VARCHAR(60),
	statecity VARCHAR(50),
	statecityzip VARCHAR(50),
	statecountycode VARCHAR(5),
	statecityscf VARCHAR(50),
	county_code_description VARCHAR(100),
	donotcallflag VARCHAR(1),
	individual_mc VARCHAR(17),
	company_mc VARCHAR(17)
);

--Truncate Table {tablename1} ;
COPY {tablename1}
(
	lastname,
	firstname,
	middlename,
	title,
	gender,
	addressline1,
	city,
	state,
	zip,
	zipfour,
	carrierroutecode,
	delivery_point_bar_code,
	industrytitle,
	occupationtitle,
	specialtytitle,
	censusstatecode,
	censuscountycode,
	censustract,
	censusblockgroup,
	highrise,
	yearlicensed,
	licensestate,
	licensenumber,
	enhancedphone,
	area_code,
	phone_number,
	time_zone,
	numberofchildren,
	childrenbygender0,
	childrenbygender1,
	childrenbygender2,
	childrenbygender3,
	childrenbygender4,
	childrenbygender5,
	childrenbygender6,
	childrenbygender7,
	childrenbygender8,
	childrenbygender9,
	childrenbygender10,
	childrenbygender11,
	childrenbygender12,
	childrenbygender13,
	childrenbygender14,
	childrenbygender15,
	childrenbygender16,
	childrenbygender17,
	length_of_residence,
	own_rent_indicator,
	find_income,
	activebankcard,
	donor_ever,
	home_value_code,
	cat_owner,
	dog_owner,
	mail_responsive,
	mail_responsive_previous,
	mail_order,
	marital_status,
	health_contributor,
	political_contributor,
	religious_contirbutor,
	personal_computer,
	age,
	latitude,
	longitude,
	geo_match_code,
	cbsa_code,
	cbsa_code_description,
	cbsa_level_description,
	county_code,
	mailscore,
	housenumber,
	streetpredirectional,
	streetname,
	streetsuffix,
	streetpostdirectional,
	unittype,
	unitnumber,
	vendorethnicity,
	occupationid,
	fulfillmentflag,
	emailaddress,
	emailmatchindicator,
	emailsource,
	residentialbusinessindicator,
	employername,
	familyid,
	individualid,
	abinumber,
	siccode,
	scf,
	licensestatuscode,
	md5_upper,
	md5_lower,
	state_donotcall_flag,
	ce_education_model,
	ce_education_model_desc,
	individual_mc_wb,
	company_mc_wb,
	email_marketable,
	email_reputation_risk,
	BV_flag,
	filler_1
)
FROM 's3://{s3-internal}{s3-key1}'
IAM_ROLE '{iam}'
IGNOREBLANKLINES
FIXEDWIDTH
'lastname:20,
firstname:15,
middlename:15,
title:1,
gender:1,
addressline1:40,
city:28,
state:2,
zip:5,
zipfour:4,
carrierroutecode:4,
delivery_point_bar_code:3,
industrytitle:50,
occupationtitle:50,
specialtytitle:50,
censusstatecode:2,
censuscountycode:3,
censustract:6,
censusblockgroup:1,
highrise:2,
yearlicensed:4,
licensestate:2,
licensenumber:25,
enhancedphone:1,
area_code:3,
phone_number:7,
time_zone:1,
numberofchildren:1,
childrenbygender0:1,
childrenbygender1:1,
childrenbygender2:1,
childrenbygender3:1,
childrenbygender4:1,
childrenbygender5:1,
childrenbygender6:1,
childrenbygender7:1,
childrenbygender8:1,
childrenbygender9:1,
childrenbygender10:1,
childrenbygender11:1,
childrenbygender12:1,
childrenbygender13:1,
childrenbygender14:1,
childrenbygender15:1,
childrenbygender16:1,
childrenbygender17:1,
length_of_residence:2,
own_rent_indicator:1,
find_income:6,
activebankcard:1,
donor_ever:1,
home_value_code:1,
cat_owner:1,
dog_owner:1,
mail_responsive:1,
mail_responsive_previous:1,
mail_order:1,
marital_status:1,
health_contributor:1,
political_contributor:1,
religious_contirbutor:1,
personal_computer:1,
age:3,
latitude:9,
longitude:9,
geo_match_code:1,
cbsa_code:5,
cbsa_code_description:50,
cbsa_level_description:5,
county_code:3,
mailscore:2,
housenumber:10,
streetpredirectional:2,
streetname:28,
streetsuffix:4,
streetpostdirectional:2,
unittype:4,
unitnumber:8,
vendorethnicity:2,
occupationid:12,
fulfillmentflag:1,
emailaddress:60,
emailmatchindicator:1,
emailsource:2,
residentialbusinessindicator:1,
employername:30,
familyid:12,
individualid:12,
abinumber:9,
siccode:6,
scf:3,
licensestatuscode:1,
md5_upper:32,
md5_lower:32,
state_donotcall_flag:1,
ce_education_model:1,
ce_education_model_desc:31,
individual_mc:17,
company_mc:17,
email_marketable:1,
email_reputation_risk:1,
BV_flag:1,
filler_1:2';