--Create a log table to send as email
DROP TABLE IF EXISTS  PRYORPARK_Log_ToBeDropped;

CREATE TABLE  PRYORPARK_Log_ToBeDropped
(ID INT IDENTITY UNIQUE,
cLog  Varchar(300)
);


DROP TABLE IF EXISTS  PRYORPARK_NEW;
CREATE TABLE  PRYORPARK_NEW
(
ID INT IDENTITY UNIQUE,
ListID  INT  DEFAULT 14754,
LISTTYPE CHAR DEFAULT 'Z',
PRODUCTCODE  VARCHAR(2)DEFAULT '99',
PERMISSIONTYPE CHAR(1) DEFAULT 'R',
FILE_DATE VARCHAR(8),
STATE VARCHAR(2),
VIP_NO VARCHAR(13),
REPCIRNO VARCHAR(6),
EMAILADDRESS VARCHAR(50),
DOMAIN_NAME VARCHAR(25),
EVENT_CODE CHAR(1),
EVENT_DATE VARCHAR(8),
EVENT_TIME VARCHAR(8),
EVENT_IP_ADDRESS VARCHAR(15)
);



/* Load 1 */
COPY PRYORPARK_NEW
(
VIP_NO,
REPCIRNO,
EMAILADDRESS,
DOMAIN_NAME,
EVENT_CODE,
EVENT_DATE,
EVENT_TIME,
EVENT_IP_ADDRESS
)
FROM 's3://{bucket_name}/{file_key}'
IAM_ROLE '{iam}'
ACCEPTINVCHARS
fixedwidth
'VIP_NO:13,
REPCIRNO:6,
EMAILADDRESS:50,
DOMAIN_NAME:25,
EVENT_CODE:1,
EVENT_DATE:8,
EVENT_TIME:8,
EVENT_IP_ADDRESS:50';

/* Update file date*/
 UPDATE PRYORPARK_NEW SET FILE_DATE= REPLACE(current_date,'-','') WHERE FILE_DATE ='' or FILE_DATE is NULL; 
 UPDATE PRYORPARK_NEW SET EMAILADDRESS = UPPER(EMAILADDRESS); 

--Complete. Add to log
INSERT INTO PRYORPARK_Log_ToBeDropped (cLog)
	SELECT 'Records inserted - File date: '+ FILE_DATE + '     Count:'+ Cast(COUNT(FILE_DATE) as Varchar(10) ) as cLog
	from PRYORPARK_NEW  
	group by FILE_DATE 
	order by FILE_DATE;
