
name: develop
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - develop
      - main
jobs:
  my_validation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - run: python --version
    - run: pip --version
    - name: Install Airflow
      run: pip install "apache-airflow==2.4.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.4.3/constraints-no-providers-3.8.txt"
    - run: airflow info
    - run: ls
    - name: Install dependencies
      run: pip install --no-cache-dir -r idms-requirements.txt
    - name: Run DB Init
      run: airflow db init
    - name: Sleep
      run: sleep 5
    - name: Import variables
      run: airflow variables import dev_variables_export.json
    - name: Import connections
      run: airflow connections import dev_connections_export.json
    - name: List variables
      run: airflow variables list
    - name: Copy IDMS Dags to airflow
      run: cp -a idms/dag /home/runner/airflow/dags
    - name: Copy Example Dag to airflow
      run: cp *.py /home/runner/airflow/dags
    - run: ls
    - name: Sleep
      run: sleep 5
    - name: Run Dags report
      run: airflow dags report -v > /tmp/reports.txt
    - name: Run linting
      run: |
        pip install pylint-airflow
        pylint --load-plugins=pylint_airflow --disable=R,C,I /home/runner/airflow/dags || true
    - name: Display report
      run: cat /tmp/reports.txt
    - name: Display Module errors
      run: grep ModuleNotFoundError /tmp/reports.txt || echo "No ModuleNotFoundErrors"
    - name: Display Key errors
      run: grep KeyError /tmp/reports.txt || echo "No KeyError"
    - name: Check report for errors
      run: |
        if grep -Fwq "ERROR" /tmp/reports.txt 
        then 
          echo "Error detected. See detailed report in Display step above"
          cat /tmp/reports.txt | grep "ERROR"
          exit 1 
        fi 
        
