
name: develop
on:
  push:
    branches: [ develop ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: apache/airflow:2.4.2
      env:
        VARIABLE1: development
      ports:
        - 8080
      volumes:
        - airflow:/opt/airflow
    steps:
      - name: Sleep 10s
        run: sleep 10
      - name: Run Airflow DAG report
        run: airflow dags report -v > /tmp/report.log
      - name: Print report
        run: cat /tmp/report.log
