
name: develop
on:
  push:
    branches: [ develop ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: apache/airflow:2.4.2-python3.8
      env:
        VARIABLE1: development
      ports:
        - 8080
      volumes:
        - airflow_log:/opt/airflow/logs
      options: --entrypoint ""
    steps:
      - name: Run Airflow Info
        run: ./airflow info
