
name: develop
on:
  push:
    branches: [ develop ]
jobs:
  my_validation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - run: python --version
    - run: pip --version
    - run: pip install "apache-airflow==2.4.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.4.2/constraints-no-providers-3.8.txt"
    - run: airflow info
    - run: ls
    - run: cp *.py /home/runner/airflow/dags
    - run: ls /home/runner/airflow/dags
    - run: sleep 5
    - run: airflow db init
    - run: sleep 5
    - run: airflow dags report -v > /tmp/reports.txt
    - run: cat /tmp/reports.txt
    - run: |
        if grep -Fwq "ERROR" /tmp/reports.txt \
        then \
          echo "Error detected" \
          exit 1 \
        fi \
        
