name: Third party airflow validate action (not working yet)
on: 
  push:
    branches:
      - main
env:
  SECRETS_CONTEXT: ${{ toJson(secrets) }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Validate DAGs'
        uses: ./
        with:
          requirements-file: project/requirements.txt
          dags-path: project/dags
          dags-test-folder: project/tests
