copy {costco_tblname1}
from 's3://{s3-internal}/internaltransfer/Costco/UPDATE_1078_{build_id}.txt.gz'
iam_role '{iam}'
gzip
acceptinvchars
fixedwidth
'ACCOUNT_IPK:11,
MEMBERSHIP_IPK:11,
POSTAL_IPK:11,
FirstName:16,
MiddleName:1,
LastName:30,
CLIENT_KEYCODE:1,
AddressLine1:40,
AddressUnit:13,
AddressLine2:40,
City:13,
State:2,
ZIP:5,
ZIP4:4,
Individual_Id_Varchar:12,
CE_HOUSEHOLD_ID:12,
CE_LOCATION_ID:23,
CE_OWN_RENT_CODE:1,
AddType:8,
Lems:18,
CE_Match_Level:7,
CE_Match_Score:3,
CE_Matched_Indicator:1,
CE_Household_Status_Code:1,
CE_Household_Head_Age_Code:1,
CE_Selected_Age:3,
CE_Selected_Individual_YYYYMM_Of_Birth:6,
CE_Selected_Individual_DD_Of_Birth:2,
CE_Selected_Individual_Marital_Status_Code:1,
CE_Selected_Title_Code:1,
CE_Selected_Gender:1,
CE_Selected_Individual_Vendor_Ethnicity_Code:2,
CE_Selected_Individual_Vendor_Ethnic_Group_Code:1,
CE_Selected_Individual_Vendor_Spoken_Language_Code:2,
CE_Selected_Individual_Vendor_Religion_Code:1,
CE_FindIncome:6,
CE_Costco_Membership_Number:12,
ce_dbi_filler:12,
CE_Specialty_Organic_Food_Store_Model:1,
CE_Wholesale_Club_Model:1,
CE_Organic_Food_Model:1,
CE_Heavy_Coupon_User_Model:1,
CE_Cruise_Model:1,
CE_Heavy_Domestic_Travelers_Model:1,
CE_High_End_Electronic_Model:1,
CE_Cook_For_Fun_Model:1,
CE_Cook_From_Scratch_Model:1,
CE_Heavy_Snack_Eaters_Model:1,
CE_Baby_Product_Model:1,
CE_Heavy_Online_Buyer_Model:1,
CE_Green_Model:1,
CE_Diet_Product_Model:1,
CE_Foreign_Travel_Vacation_Model:1,
CE_Garden_Maintenance_Model:1,
CE_Heavy_Vitamin_Model:1,
CE_Home_Improvement_Model:1,
CE_Impulse_Buyer_Model:1,
CE_Life_Insurance_Model:1,
CE_Shopaholics_Model:1,
CE_Luxury_Hotel_Model:1,
CE_Rental_Car_Model:1,
CE_Outdoor_Activities_Model:1,
CE_Frozen_Dinner_Model:1,
CE_Home_Office_Model:1,
CE_Health_Insurance_Model:1,
CE_High_End_Apparel_Model:1,
CE_Gift_Buyers_Model:1,
Filler2:1'
;

alter table {costco_tblname1} drop column ce_dbi_filler;



